package com.woolworths.shop.checkout.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.sdui.shop.fragment.selections.AnalyticsFieldsSelections;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.ApplyCheckoutPromoCodeResponse;
import au.com.woolworths.shop.graphql.type.ApplyPromoCodeBannerType;
import au.com.woolworths.shop.graphql.type.ApplyPromoCodeResult;
import au.com.woolworths.shop.graphql.type.CheckoutContent;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.InsetBanner;
import au.com.woolworths.shop.graphql.type.InsetBannerAction;
import au.com.woolworths.shop.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.shop.graphql.type.InsetBannerActionType;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.Mutation;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.woolworths.shop.checkout.fragment.selections.CheckoutContentSummarySelections;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/checkout/selections/ApplyCheckoutPromoCodeMutationSelections;", "", "shop-checkout_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class ApplyCheckoutPromoCodeMutationSelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f22547a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c());
        f22547a = listQ;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c());
        b = listQ2;
        List listR = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("primaryButtonTitle", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("secondaryButtonTitle", CompiledGraphQL.b(customScalarType)).c());
        c = listR;
        InsetBannerActionPlacement.e.getClass();
        CompiledField compiledFieldC = new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.f)).c();
        InsetBannerActionType.e.getClass();
        List listR2 = CollectionsKt.R(compiledFieldC, new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.f)).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        d = listR2;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        List list = AnalyticsFieldsSelections.b;
        builder.b(list);
        List listR3 = CollectionsKt.R(compiledFieldC2, builder.a());
        e = listR3;
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC3 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.f)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g("iconUrl", customScalarType);
        CompiledField compiledFieldC5 = new CompiledField.Builder("title", customScalarType).c();
        CompiledField.Builder builder2 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.f11510a);
        builder2.e = listR2;
        CompiledField compiledFieldC6 = builder2.c();
        ObjectType objectType = Analytics.f11028a;
        CompiledField.Builder builder3 = new CompiledField.Builder("analytics", objectType);
        builder3.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC3, compiledFieldC4, compiledFieldG, compiledFieldC5, compiledFieldC6, builder3.c());
        f = listR4;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder4.d = list;
        List listR5 = CollectionsKt.R(compiledFieldC7, builder4.a());
        g = listR5;
        ApplyPromoCodeBannerType.e.getClass();
        CompiledField compiledFieldC8 = new CompiledField.Builder("type", CompiledGraphQL.b(ApplyPromoCodeBannerType.f)).c();
        CompiledField.Builder builder5 = new CompiledField.Builder("banner", CompiledGraphQL.b(InsetBanner.f11509a));
        builder5.e = listR4;
        CompiledField compiledFieldC9 = builder5.c();
        CompiledField.Builder builder6 = new CompiledField.Builder("clickAnalytics", CompiledGraphQL.b(objectType));
        builder6.e = listR5;
        List listR6 = CollectionsKt.R(compiledFieldC8, compiledFieldC9, builder6.c());
        h = listR6;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("ApplyPromoCodeFail", CollectionsKt.Q("ApplyPromoCodeFail"));
        builder7.d = listQ;
        CompiledFragment compiledFragmentA = builder7.a();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("ApplyPromoCodeSuccess", CollectionsKt.Q("ApplyPromoCodeSuccess"));
        builder8.d = listQ2;
        CompiledFragment compiledFragmentA2 = builder8.a();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("ApplyPromoCodeReplaceConfirmation", CollectionsKt.Q("ApplyPromoCodeReplaceConfirmation"));
        builder9.d = listR;
        CompiledFragment compiledFragmentA3 = builder9.a();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("ApplyPromoCodeAdditionalInfo", CollectionsKt.Q("ApplyPromoCodeAdditionalInfo"));
        builder10.d = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC10, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, builder10.a());
        i = listR7;
        CompiledField compiledFieldC11 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("CheckoutContent", CollectionsKt.Q("CheckoutContent"));
        builder11.b(CheckoutContentSummarySelections.w0);
        List listR8 = CollectionsKt.R(compiledFieldC11, builder11.a());
        j = listR8;
        CompiledField.Builder builder12 = new CompiledField.Builder(lqlqqlq.m006Dm006Dm006Dm, CompiledGraphQL.b(ApplyPromoCodeResult.f11040a));
        builder12.e = listR7;
        CompiledField compiledFieldC12 = builder12.c();
        CompiledField.Builder builder13 = new CompiledField.Builder("checkoutSummary", CheckoutContent.f11192a);
        builder13.e = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC12, builder13.c());
        k = listR9;
        CompiledField.Builder builder14 = new CompiledField.Builder("applyCheckoutPromoCode", CompiledGraphQL.b(ApplyCheckoutPromoCodeResponse.f11036a));
        new CompiledArgument.Builder(Mutation.V);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Mutation.W);
        builder14.d = CollectionsKt.R(compiledArgument, new CompiledArgument());
        builder14.e = listR9;
        l = CollectionsKt.Q(builder14.c());
    }
}
