package com.woolworths.shop.checkout.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.shop.graphql.type.AdBannerNativeSize;
import au.com.woolworths.shop.graphql.type.BroadcastBanner;
import au.com.woolworths.shop.graphql.type.BroadcastBannerType;
import au.com.woolworths.shop.graphql.type.CardHeight;
import au.com.woolworths.shop.graphql.type.CheckoutOrderAddressSegment;
import au.com.woolworths.shop.graphql.type.CheckoutOrderMarketSellerInfo;
import au.com.woolworths.shop.graphql.type.CheckoutOrderTotalDetailsRow;
import au.com.woolworths.shop.graphql.type.CheckoutOrderTotalDetailsRowMessage;
import au.com.woolworths.shop.graphql.type.CheckoutProductInfo;
import au.com.woolworths.shop.graphql.type.CheckoutSummaryValueType;
import au.com.woolworths.shop.graphql.type.GoogleAdBannerCard;
import au.com.woolworths.shop.graphql.type.GoogleAdCustomTargeting;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLFloat;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.InsetBanner;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.OrderConfirmationContent;
import au.com.woolworths.shop.graphql.type.OrderConfirmationContentSegment;
import au.com.woolworths.shop.graphql.type.OrderInfo;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.TealiumAnalytics;
import au.com.woolworths.shop.graphql.type.UniversalInventoryNextBestAction;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.google.android.gms.ads.OutOfContextTestingActivity;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/checkout/selections/OrderConfirmationQuerySelections;", "", "shop-checkout_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class OrderConfirmationQuerySelections {
    public static final List A;

    /* renamed from: a, reason: collision with root package name */
    public static final List f22555a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        List listR = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        f22555a = listR;
        CompiledField compiledFieldC = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CheckoutSummaryValueType.e.getClass();
        EnumType enumType = CheckoutSummaryValueType.f;
        List listR2 = CollectionsKt.R(compiledFieldC, new CompiledField.Builder("titleType", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("value", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("valueType", CompiledGraphQL.b(enumType)).c(), d.g("imageUrl", customScalarType));
        b = listR2;
        CompiledField compiledFieldC2 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC3 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType = CheckoutOrderTotalDetailsRow.f11224a;
        CompiledField.Builder builder = new CompiledField.Builder("order", a.f(objectType));
        builder.e = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC2, compiledFieldC3, builder.c());
        c = listR3;
        List listR4 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("addressText", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("fulfilmentWindow", CompiledGraphQL.b(customScalarType)).c());
        d = listR4;
        List listR5 = CollectionsKt.R(new CompiledField.Builder("sellerName", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("dispatchNote", CompiledGraphQL.b(customScalarType)).c());
        e = listR5;
        CompiledField compiledFieldC4 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC5 = new CompiledField.Builder("addressText", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC6 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder2 = new CompiledField.Builder("sellerInfo", a.f(CheckoutOrderMarketSellerInfo.f11221a));
        builder2.e = listR5;
        List listR6 = CollectionsKt.R(compiledFieldC4, compiledFieldC5, compiledFieldC6, builder2.c());
        f = listR6;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("CheckoutOrderGroceryAddress", CollectionsKt.Q("CheckoutOrderGroceryAddress"));
        builder3.d = listR4;
        CompiledFragment compiledFragmentA = builder3.a();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("CheckoutOrderMarketAddress", CollectionsKt.Q("CheckoutOrderMarketAddress"));
        builder4.d = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC7, compiledFragmentA, builder4.a());
        g = listR7;
        InsetBannerDisplayType.e.getClass();
        List listR8 = CollectionsKt.R(new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.f)).c(), new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c());
        h = listR8;
        CompiledField compiledFieldC8 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder5 = new CompiledField.Builder("addressSections", d.j(CheckoutOrderAddressSegment.f11217a));
        builder5.e = listR7;
        CompiledField compiledFieldC9 = builder5.c();
        CompiledField.Builder builder6 = new CompiledField.Builder("insetBanner", InsetBanner.f11509a);
        builder6.e = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC8, compiledFieldC9, builder6.c());
        i = listR9;
        List listR10 = CollectionsKt.R(d.g("title", customScalarType), d.g("body", customScalarType));
        j = listR10;
        CompiledField compiledFieldC10 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC11 = new CompiledField.Builder("titleType", CompiledGraphQL.b(enumType)).c();
        CompiledField compiledFieldC12 = new CompiledField.Builder("value", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC13 = new CompiledField.Builder("valueType", CompiledGraphQL.b(enumType)).c();
        CompiledField compiledFieldG = d.g("imageUrl", customScalarType);
        CompiledField.Builder builder7 = new CompiledField.Builder("message", CheckoutOrderTotalDetailsRowMessage.f11225a);
        builder7.e = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC10, compiledFieldC11, compiledFieldC12, compiledFieldC13, compiledFieldG, builder7.c());
        k = listR11;
        CompiledField compiledFieldC14 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG2 = d.g("summaryText", customScalarType);
        CompiledField.Builder builder8 = new CompiledField.Builder("sections", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(objectType))))));
        builder8.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC14, compiledFieldG2, builder8.c());
        l = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c());
        m = listR13;
        List listQ = CollectionsKt.Q(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c());
        n = listQ;
        CompiledField compiledFieldC15 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("link", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("image", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC18 = new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c();
        CardHeight.e.getClass();
        EnumType enumType2 = CardHeight.f;
        CompiledField compiledFieldC19 = new CompiledField.Builder("cardHeight", CompiledGraphQL.b(enumType2)).c();
        CustomScalarType customScalarType2 = TealiumAnalytics.f11963a;
        CompiledField compiledFieldC20 = new CompiledField.Builder("analytics", customScalarType2).c();
        CustomScalarType customScalarType3 = GraphQLBoolean.f11439a;
        List listR14 = CollectionsKt.R(compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, compiledFieldC19, compiledFieldC20, new CompiledField.Builder("_excluded", customScalarType3).c());
        o = listR14;
        CompiledField compiledFieldC21 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC22 = new CompiledField.Builder(OutOfContextTestingActivity.AD_UNIT_KEY, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC23 = new CompiledField.Builder("nativeCustomTemplateId", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC24 = new CompiledField.Builder("iabSpec", CompiledGraphQL.b(customScalarType3)).c();
        CompiledField compiledFieldG3 = d.g("iabSize", customScalarType);
        AdBannerNativeSize.e.getClass();
        EnumType enumType3 = AdBannerNativeSize.f;
        CompiledField compiledFieldC25 = new CompiledField.Builder("height", CompiledGraphQL.b(enumType3)).c();
        CustomScalarType customScalarType4 = GoogleAdCustomTargeting.f11436a;
        List listR15 = CollectionsKt.R(compiledFieldC21, compiledFieldC22, compiledFieldC23, compiledFieldC24, compiledFieldG3, compiledFieldC25, new CompiledField.Builder("targeting", customScalarType4).c(), d.g("_excluded", customScalarType3));
        p = listR15;
        List listR16 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(OutOfContextTestingActivity.AD_UNIT_KEY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("nativeCustomTemplateId", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("iabSpec", CompiledGraphQL.b(customScalarType3)).c(), d.g("iabSize", customScalarType), new CompiledField.Builder("height", CompiledGraphQL.b(enumType3)).c(), d.g("targeting", customScalarType4), d.g("correlator", customScalarType), d.g("_excluded", customScalarType3));
        q = listR16;
        List listR17 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("link", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("image", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("cardHeight", CompiledGraphQL.b(enumType2)).c(), d.g("analytics", customScalarType2), d.g("_excluded", customScalarType3));
        r = listR17;
        CompiledField compiledFieldC26 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder9.d = listR17;
        List listR18 = CollectionsKt.R(compiledFieldC26, builder9.a());
        s = listR18;
        CompiledField.Builder builder10 = new CompiledField.Builder("googleAdBannerCard", GoogleAdBannerCard.f11435a);
        builder10.e = listR16;
        CompiledField compiledFieldC27 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("nextBestAction", UniversalInventoryNextBestAction.f11980a);
        builder11.e = listR18;
        List listR19 = CollectionsKt.R(compiledFieldC27, builder11.c());
        t = listR19;
        CompiledField compiledFieldC28 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG4 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        BroadcastBannerType.e.getClass();
        List listR20 = CollectionsKt.R(compiledFieldC28, compiledFieldG4, new CompiledField.Builder("type", CompiledGraphQL.b(BroadcastBannerType.f)).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c(), d.g("analyticsLabel", customScalarType), d.g("bannerId", customScalarType), d.g("dismissible", customScalarType3));
        u = listR20;
        CompiledField.Builder builder12 = new CompiledField.Builder("banner", BroadcastBanner.f11060a);
        builder12.e = listR20;
        List listQ2 = CollectionsKt.Q(builder12.c());
        v = listQ2;
        CompiledField compiledFieldC29 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("OrderConfirmationBannerImage", CollectionsKt.Q("OrderConfirmationBannerImage"));
        builder13.d = listR;
        CompiledFragment compiledFragmentA2 = builder13.a();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("OrderConfirmationHeader", CollectionsKt.Q("OrderConfirmationHeader"));
        builder14.d = listR3;
        CompiledFragment compiledFragmentA3 = builder14.a();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("CheckoutOrderAddresses", CollectionsKt.Q("CheckoutOrderAddresses"));
        builder15.d = listR9;
        CompiledFragment compiledFragmentA4 = builder15.a();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("CheckoutOrderSummary", CollectionsKt.Q("CheckoutOrderSummary"));
        builder16.d = listR12;
        CompiledFragment compiledFragmentA5 = builder16.a();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("IconTextBanner", CollectionsKt.Q("IconTextBanner"));
        builder17.d = listR13;
        CompiledFragment compiledFragmentA6 = builder17.a();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("OrderConfirmationFooterText", CollectionsKt.Q("OrderConfirmationFooterText"));
        builder18.d = listQ;
        CompiledFragment compiledFragmentA7 = builder18.a();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder19.d = listR14;
        CompiledFragment compiledFragmentA8 = builder19.a();
        CompiledFragment.Builder builder20 = new CompiledFragment.Builder("GoogleAdBannerCard", CollectionsKt.Q("GoogleAdBannerCard"));
        builder20.c = a.s("includeUniversalInventoryFallback", true);
        builder20.d = listR15;
        CompiledFragment compiledFragmentA9 = builder20.a();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("UniversalInventoryContainer", CollectionsKt.Q("UniversalInventoryContainer"));
        builder21.c = a.s("includeUniversalInventoryFallback", false);
        builder21.d = listR19;
        CompiledFragment compiledFragmentA10 = builder21.a();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("OrderConfirmationCMOBroadcastBanner", CollectionsKt.Q("OrderConfirmationCMOBroadcastBanner"));
        builder22.c = a.s("includeCmoBanner", false);
        builder22.d = listQ2;
        List listR21 = CollectionsKt.R(compiledFieldC29, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, compiledFragmentA8, compiledFragmentA9, compiledFragmentA10, builder22.a());
        w = listR21;
        CompiledField compiledFieldC30 = new CompiledField.Builder("productId", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC31 = new CompiledField.Builder("productName", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType5 = GraphQLFloat.f11440a;
        List listR22 = CollectionsKt.R(compiledFieldC30, compiledFieldC31, new CompiledField.Builder("price", CompiledGraphQL.b(customScalarType5)).c(), new CompiledField.Builder("quantity", CompiledGraphQL.b(customScalarType5)).c(), new CompiledField.Builder("subtotal", CompiledGraphQL.b(customScalarType5)).c(), new CompiledField.Builder("isAvailable", CompiledGraphQL.b(customScalarType3)).c(), d.g("sellerName", customScalarType), d.g("brandName", customScalarType), d.g("dispatchNote", customScalarType), d.g("source", customScalarType));
        x = listR22;
        CompiledField.Builder builder23 = new CompiledField.Builder("productsInfo", a.f(CheckoutProductInfo.f11231a));
        builder23.e = listR22;
        List listR23 = CollectionsKt.R(builder23.c(), new CompiledField.Builder("isDeliveryNow", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("isDirectToBootNow", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("isDeliveryUnlimited", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("shopperID", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("orderNumber", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("orderTotal", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("deliveryFee", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("deliveryCity", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("deliveryMethod", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("isCrowdSourced", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("packagingFeeLabel", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("hasRewards", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("orderDiscount", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("subtotal", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("rewardsCreditsUsed", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("fulfilmentMethod", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("isEditedOrder", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("orderReference", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("rewardsDollarsAmount", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("storeCreditAmount", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("promoCodeCreditAmount", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("discountSavingsTotal", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("storeCreditCode", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("promoCodeValue", CompiledGraphQL.b(customScalarType)).c());
        y = listR23;
        CompiledField.Builder builder24 = new CompiledField.Builder("content", d.j(OrderConfirmationContentSegment.f11639a));
        builder24.e = listR21;
        CompiledField compiledFieldC32 = builder24.c();
        CompiledField compiledFieldG5 = d.g("buttonTitle", customScalarType);
        CompiledField.Builder builder25 = new CompiledField.Builder("orderInfo", CompiledGraphQL.b(OrderInfo.f11654a));
        builder25.e = listR23;
        List listR24 = CollectionsKt.R(compiledFieldC32, compiledFieldG5, builder25.c());
        z = listR24;
        CompiledField.Builder builder26 = new CompiledField.Builder("orderConfirmation", OrderConfirmationContent.f11638a);
        new CompiledArgument.Builder(Query.d2);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.e2);
        CompiledArgument compiledArgument2 = new CompiledArgument();
        new CompiledArgument.Builder(Query.f2);
        builder26.d = CollectionsKt.R(compiledArgument, compiledArgument2, new CompiledArgument());
        builder26.e = listR24;
        A = CollectionsKt.Q(builder26.c());
    }
}
