package com.woolworths.shop.homepage.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.shop.aem.components.recipes.fragment.selections.RecipeSummaryCardFragmentSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionMetaData;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.AlertIndicator;
import au.com.woolworths.shop.graphql.type.AlertIndicatorType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.AnalyticsExtraContent;
import au.com.woolworths.shop.graphql.type.BroadcastBannerType;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.CardHeight;
import au.com.woolworths.shop.graphql.type.CarouselItem;
import au.com.woolworths.shop.graphql.type.ChatEntryCardContext;
import au.com.woolworths.shop.graphql.type.ChatEntryCardContextData;
import au.com.woolworths.shop.graphql.type.ChatEntryCardCta;
import au.com.woolworths.shop.graphql.type.ChatEntryCardElement;
import au.com.woolworths.shop.graphql.type.ContentCardFooter;
import au.com.woolworths.shop.graphql.type.ContentCardSize;
import au.com.woolworths.shop.graphql.type.ContentCta;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerUI;
import au.com.woolworths.shop.graphql.type.DividerCard;
import au.com.woolworths.shop.graphql.type.DownloadableAsset;
import au.com.woolworths.shop.graphql.type.DownloadableAssetFit;
import au.com.woolworths.shop.graphql.type.DownloadableAssetType;
import au.com.woolworths.shop.graphql.type.FooterStyle;
import au.com.woolworths.shop.graphql.type.FulfilmentStatusBanner;
import au.com.woolworths.shop.graphql.type.GenericPageFeedItem;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLID;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.HeroBannerBody;
import au.com.woolworths.shop.graphql.type.HeroBannerTermsAndConditions;
import au.com.woolworths.shop.graphql.type.HeroBannerTitleSize;
import au.com.woolworths.shop.graphql.type.HomeDeliveryNowBanner;
import au.com.woolworths.shop.graphql.type.HomeDeliveryNowBannerUnion;
import au.com.woolworths.shop.graphql.type.HomeFulfilmentWindowContainerOrientation;
import au.com.woolworths.shop.graphql.type.HomeFulfilmentWindowTile;
import au.com.woolworths.shop.graphql.type.HomeFulfilmentWindowTileAnalytics;
import au.com.woolworths.shop.graphql.type.HomeFulfilmentWindowTileStyle;
import au.com.woolworths.shop.graphql.type.HomeHeaderItems;
import au.com.woolworths.shop.graphql.type.HomeList;
import au.com.woolworths.shop.graphql.type.HomeListDeliveryNow;
import au.com.woolworths.shop.graphql.type.HomeOnlineShoppingModeVariantTile;
import au.com.woolworths.shop.graphql.type.HomeOnlineShoppingModeVariantTileAnalytics;
import au.com.woolworths.shop.graphql.type.HomePage;
import au.com.woolworths.shop.graphql.type.HorizontalListItem;
import au.com.woolworths.shop.graphql.type.IconAsset;
import au.com.woolworths.shop.graphql.type.ImageWithAlt;
import au.com.woolworths.shop.graphql.type.InStoreDetailsCard;
import au.com.woolworths.shop.graphql.type.InsetBannerAction;
import au.com.woolworths.shop.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.shop.graphql.type.InsetBannerActionType;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.Link;
import au.com.woolworths.shop.graphql.type.OrderStatus;
import au.com.woolworths.shop.graphql.type.OverlayAnimation;
import au.com.woolworths.shop.graphql.type.ProductCard;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.TealiumAnalytics;
import au.com.woolworths.shop.graphql.type.TextWithAlt;
import au.com.woolworths.shop.graphql.type.TextWithLink;
import au.com.woolworths.shop.graphql.type.UnreadChatbotMsg;
import au.com.woolworths.shop.graphql.type.VideoAd;
import au.com.woolworths.shop.graphql.type.VideoAdBottomSheet;
import au.com.woolworths.shop.graphql.type.VideoAdEventAnalytics;
import au.com.woolworths.shop.graphql.type.VideoAdUnitCarousel;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.google.android.gms.common.api.internal.a;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.salesforce.marketingcloud.storage.db.k;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/homepage/selections/HomeContentPageQuerySelections;", "", "homepage_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class HomeContentPageQuerySelections {
    public static final List A;
    public static final List A0;
    public static final List A1;
    public static final List B;
    public static final List B0;
    public static final List B1;
    public static final List C;
    public static final List C0;
    public static final List C1;
    public static final List D;
    public static final List D0;
    public static final List E;
    public static final List E0;
    public static final List F;
    public static final List F0;
    public static final List G;
    public static final List G0;
    public static final List H;
    public static final List H0;
    public static final List I;
    public static final List I0;
    public static final List J;
    public static final List J0;
    public static final List K;
    public static final List K0;
    public static final List L;
    public static final List L0;
    public static final List M;
    public static final List M0;
    public static final List N;
    public static final List N0;
    public static final List O;
    public static final List O0;
    public static final List P;
    public static final List P0;
    public static final List Q;
    public static final List Q0;
    public static final List R;
    public static final List R0;
    public static final List S;
    public static final List S0;
    public static final List T;
    public static final List T0;
    public static final List U;
    public static final List U0;
    public static final List V;
    public static final List V0;
    public static final List W;
    public static final List W0;
    public static final List X;
    public static final List X0;
    public static final List Y;
    public static final List Y0;
    public static final List Z;
    public static final List Z0;

    /* renamed from: a, reason: collision with root package name */
    public static final List f23222a;
    public static final List a0;
    public static final List a1;
    public static final List b;
    public static final List b0;
    public static final List b1;
    public static final List c;
    public static final List c0;
    public static final List c1;
    public static final List d;
    public static final List d0;
    public static final List d1;
    public static final List e;
    public static final List e0;
    public static final List e1;
    public static final List f;
    public static final List f0;
    public static final List f1;
    public static final List g;
    public static final List g0;
    public static final List g1;
    public static final List h;
    public static final List h0;
    public static final List h1;
    public static final List i;
    public static final List i0;
    public static final List i1;
    public static final List j;
    public static final List j0;
    public static final List j1;
    public static final List k;
    public static final List k0;
    public static final List k1;
    public static final List l;
    public static final List l0;
    public static final List l1;
    public static final List m;
    public static final List m0;
    public static final List m1;
    public static final List n;
    public static final List n0;
    public static final List n1;
    public static final List o;
    public static final List o0;
    public static final List o1;
    public static final List p;
    public static final List p0;
    public static final List p1;
    public static final List q;
    public static final List q0;
    public static final List q1;
    public static final List r;
    public static final List r0;
    public static final List r1;
    public static final List s;
    public static final List s0;
    public static final List s1;
    public static final List t;
    public static final List t0;
    public static final List t1;
    public static final List u;
    public static final List u0;
    public static final List u1;
    public static final List v;
    public static final List v0;
    public static final List v1;
    public static final List w;
    public static final List w0;
    public static final List w1;
    public static final List x;
    public static final List x0;
    public static final List x1;
    public static final List y;
    public static final List y0;
    public static final List y1;
    public static final List z;
    public static final List z0;
    public static final List z1;

    static {
        List listR = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        f23222a = listR;
        CompiledField compiledFieldC = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ButtonStyle.e.getClass();
        List listR2 = CollectionsKt.R(compiledFieldC, new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        b = listR2;
        CompiledField compiledFieldC2 = new CompiledField.Builder("fulfilmentWindowStateTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType = TextWithAlt.f11967a;
        CompiledField.Builder builder = new CompiledField.Builder("fulfilmentWindowStateSubtitle", TextWithAlt.Companion.a());
        builder.e(listR);
        CompiledField compiledFieldC3 = builder.c();
        ObjectType objectType2 = Button.f11080a;
        CompiledField.Builder builder2 = new CompiledField.Builder("fulfilmentWindowStateButton", CompiledGraphQL.b(Button.Companion.a()));
        builder2.e(listR2);
        List listR3 = CollectionsKt.R(compiledFieldC2, compiledFieldC3, builder2.c());
        c = listR3;
        List listR4 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        d = listR4;
        CompiledField.Builder builder3 = new CompiledField.Builder("_", GraphQLBoolean.Companion.a());
        builder3.a("_excluded");
        List listQ = CollectionsKt.Q(builder3.c());
        e = listQ;
        CompiledField.Builder builder4 = new CompiledField.Builder("button", CompiledGraphQL.b(Button.Companion.a()));
        builder4.e(listR4);
        CompiledField compiledFieldC4 = builder4.c();
        CompiledField.Builder builder5 = new CompiledField.Builder("deliveryNowBanner", HomeDeliveryNowBanner.f11455a);
        builder5.e(listQ);
        CompiledField compiledFieldC5 = builder5.c();
        HomeFulfilmentWindowContainerOrientation.e.getClass();
        List listR5 = CollectionsKt.R(compiledFieldC4, compiledFieldC5, new CompiledField.Builder("orientation", CompiledGraphQL.b(HomeFulfilmentWindowContainerOrientation.f)).c());
        f = listR5;
        List listR6 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        g = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        h = listR7;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        i = listQ2;
        HomeFulfilmentWindowTileStyle.e.getClass();
        CompiledField compiledFieldC6 = new CompiledField.Builder("style", CompiledGraphQL.b(HomeFulfilmentWindowTileStyle.f)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("iconUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC8 = new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder6 = new CompiledField.Builder("title", CompiledGraphQL.b(TextWithAlt.Companion.a()));
        builder6.e(listR6);
        CompiledField compiledFieldC9 = builder6.c();
        CompiledField.Builder builder7 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, TextWithAlt.Companion.a());
        builder7.e(listR7);
        CompiledField compiledFieldC10 = builder7.c();
        CompiledField.Builder builder8 = new CompiledField.Builder("analytics", CompiledGraphQL.b(HomeFulfilmentWindowTileAnalytics.f11462a));
        builder8.e(listQ2);
        List listR8 = CollectionsKt.R(compiledFieldC6, compiledFieldC7, compiledFieldC8, compiledFieldC9, compiledFieldC10, builder8.c());
        j = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        k = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        l = listR10;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        m = listQ3;
        CompiledField compiledFieldC11 = new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder9 = new CompiledField.Builder("title", TextWithAlt.Companion.a());
        builder9.e(listR9);
        CompiledField compiledFieldC12 = builder9.c();
        CompiledField.Builder builder10 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, TextWithAlt.Companion.a());
        builder10.e(listR10);
        CompiledField compiledFieldC13 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("analytics", CompiledGraphQL.b(HomeOnlineShoppingModeVariantTileAnalytics.f11469a));
        builder11.e(listQ3);
        List listR11 = CollectionsKt.R(compiledFieldC11, compiledFieldC12, compiledFieldC13, builder11.c());
        n = listR11;
        CompiledField.Builder builder12 = new CompiledField.Builder("_", GraphQLBoolean.Companion.a());
        builder12.a("_excluded");
        List listQ4 = CollectionsKt.Q(builder12.c());
        o = listQ4;
        DownloadableAssetType.e.getClass();
        CompiledField compiledFieldC14 = new CompiledField.Builder("assetType", CompiledGraphQL.b(DownloadableAssetType.f)).c();
        CompiledField compiledFieldC15 = new CompiledField.Builder("assetUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("assetWidth", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("assetHeight", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        DownloadableAssetFit.e.getClass();
        List listR12 = CollectionsKt.R(compiledFieldC14, compiledFieldC15, compiledFieldC16, compiledFieldC17, new CompiledField.Builder("fit", DownloadableAssetFit.f).c(), new CompiledField.Builder("altText", GraphQLString.Companion.a()).c());
        p = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        q = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        r = listR14;
        CompiledField compiledFieldC18 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC19 = new CompiledField.Builder("bottomSheetTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC20 = new CompiledField.Builder("bottomSheetBody", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC21 = new CompiledField.Builder("showOnceOnly", GraphQLBoolean.Companion.a()).c();
        CompiledField.Builder builder13 = new CompiledField.Builder("bannerAsset", DownloadableAsset.f11349a);
        builder13.e(listR12);
        CompiledField compiledFieldC22 = builder13.c();
        ObjectType objectType3 = ContentCta.f11282a;
        CompiledField.Builder builder14 = new CompiledField.Builder("primaryCta", ContentCta.Companion.a());
        builder14.e(listR13);
        CompiledField compiledFieldC23 = builder14.c();
        CompiledField.Builder builder15 = new CompiledField.Builder("secondaryCta", ContentCta.Companion.a());
        builder15.e(listR14);
        List listR15 = CollectionsKt.R(compiledFieldC18, compiledFieldC19, compiledFieldC20, compiledFieldC21, compiledFieldC22, compiledFieldC23, builder15.c());
        s = listR15;
        CompiledField.Builder builder16 = new CompiledField.Builder("_", GraphQLBoolean.Companion.a());
        builder16.a("_excluded");
        List listQ5 = CollectionsKt.Q(builder16.c());
        t = listQ5;
        CompiledField compiledFieldC24 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("HomeDeliveryNowBottomBanner", CollectionsKt.Q("HomeDeliveryNowBottomBanner"));
        builder17.b(listR15);
        CompiledFragment compiledFragmentA = builder17.a();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("HomeDeliveryNowBanner", CollectionsKt.Q("HomeDeliveryNowBanner"));
        builder18.b(listQ5);
        List listR16 = CollectionsKt.R(compiledFieldC24, compiledFragmentA, builder18.a());
        u = listR16;
        List listR17 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        v = listR17;
        List listR18 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        w = listR18;
        ObjectType objectType4 = TextWithLink.f11968a;
        CompiledField.Builder builder19 = new CompiledField.Builder("storeName", objectType4);
        builder19.e(listR17);
        CompiledField compiledFieldC25 = builder19.c();
        CompiledField.Builder builder20 = new CompiledField.Builder("storeTime", objectType4);
        builder20.e(listR18);
        List listR19 = CollectionsKt.R(compiledFieldC25, builder20.c(), new CompiledField.Builder("isLocationMapped", GraphQLBoolean.Companion.a()).c());
        x = listR19;
        CompiledField.Builder builder21 = new CompiledField.Builder("fulfilmentWindowTile", HomeFulfilmentWindowTile.f11461a);
        builder21.e(listR8);
        CompiledField compiledFieldC26 = builder21.c();
        CompiledField.Builder builder22 = new CompiledField.Builder("onlineShoppingModeVariantTile", HomeOnlineShoppingModeVariantTile.f11468a);
        builder22.e(listR11);
        CompiledField compiledFieldC27 = builder22.c();
        CompiledField.Builder builder23 = new CompiledField.Builder("divider", DividerCard.f11348a);
        builder23.e(listQ4);
        CompiledField compiledFieldC28 = builder23.c();
        CompiledField.Builder builder24 = new CompiledField.Builder("deliveryNowBanner", HomeDeliveryNowBannerUnion.f11456a);
        builder24.e(listR16);
        CompiledField compiledFieldC29 = builder24.c();
        CompiledField.Builder builder25 = new CompiledField.Builder("inStoreDetailsCard", InStoreDetailsCard.f11490a);
        builder25.e(listR19);
        List listR20 = CollectionsKt.R(compiledFieldC26, compiledFieldC27, compiledFieldC28, compiledFieldC29, builder25.c());
        y = listR20;
        CompiledField compiledFieldC30 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("HomeFulfilmentWindowBanner", CollectionsKt.Q("HomeFulfilmentWindowBanner"));
        builder26.b(listR3);
        CompiledFragment compiledFragmentA2 = builder26.a();
        CompiledFragment.Builder builder27 = new CompiledFragment.Builder("HomeFulfilmentWindowContainer", CollectionsKt.Q("HomeFulfilmentWindowContainer"));
        builder27.b(listR5);
        CompiledFragment compiledFragmentA3 = builder27.a();
        CompiledFragment.Builder builder28 = new CompiledFragment.Builder("HomeModeSelectorContainer", CollectionsKt.Q("HomeModeSelectorContainer"));
        builder28.b(listR20);
        List listR21 = CollectionsKt.R(compiledFieldC30, compiledFragmentA2, compiledFragmentA3, builder28.a());
        z = listR21;
        List listR22 = CollectionsKt.R(new CompiledField.Builder("status", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("expressDeliveryStoreId", GraphQLInt.Companion.a()).c());
        A = listR22;
        List listQ6 = CollectionsKt.Q(new CompiledField.Builder("count", CompiledGraphQL.b(GraphQLInt.Companion.a())).c());
        B = listQ6;
        CompiledField.Builder builder29 = new CompiledField.Builder("headerItems", CompiledGraphQL.b(CompiledGraphQL.a(HomeHeaderItems.f11463a)));
        builder29.e(listR21);
        CompiledField compiledFieldC31 = builder29.c();
        CompiledField.Builder builder30 = new CompiledField.Builder("deliveryNow", HomeListDeliveryNow.f11466a);
        builder30.e(listR22);
        CompiledField compiledFieldC32 = builder30.c();
        CompiledField.Builder builder31 = new CompiledField.Builder("unreadChatbotMsg", UnreadChatbotMsg.f11990a);
        builder31.e(listQ6);
        List listR23 = CollectionsKt.R(compiledFieldC31, compiledFieldC32, builder31.c());
        C = listR23;
        List listR24 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        D = listR24;
        List listR25 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        E = listR25;
        List listQ7 = CollectionsKt.Q(new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c());
        F = listQ7;
        List listR26 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        G = listR26;
        List listR27 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        H = listR27;
        CompiledField compiledFieldC33 = new CompiledField.Builder("link", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC34 = new CompiledField.Builder("image", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CardHeight.e.getClass();
        CompiledField compiledFieldC35 = new CompiledField.Builder("cardHeight", CompiledGraphQL.b(CardHeight.Companion.a())).c();
        CompiledField compiledFieldC36 = new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC37 = new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c();
        CompiledField compiledFieldC38 = new CompiledField.Builder("analytics", TealiumAnalytics.Companion.a()).c();
        ObjectType objectType5 = Analytics.f11028a;
        CompiledField.Builder builder32 = new CompiledField.Builder("actionableCardImpressionAnalytics", Analytics.Companion.a());
        builder32.e(listR26);
        CompiledField compiledFieldC39 = builder32.c();
        CompiledField.Builder builder33 = new CompiledField.Builder("actionableCardClickAnalytics", Analytics.Companion.a());
        builder33.e(listR27);
        List listR28 = CollectionsKt.R(compiledFieldC33, compiledFieldC34, compiledFieldC35, compiledFieldC36, compiledFieldC37, compiledFieldC38, compiledFieldC39, builder33.c());
        I = listR28;
        InsetBannerActionPlacement.e.getClass();
        CompiledField compiledFieldC40 = new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.Companion.a())).c();
        InsetBannerActionType.e.getClass();
        List listR29 = CollectionsKt.R(compiledFieldC40, new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        J = listR29;
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC41 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField compiledFieldC42 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder34 = new CompiledField.Builder("title", GraphQLString.Companion.a());
        builder34.a("bannerTitle");
        CompiledField compiledFieldC43 = builder34.c();
        ObjectType objectType6 = InsetBannerAction.f11510a;
        CompiledField.Builder builder35 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.Companion.a());
        builder35.e(listR29);
        List listR30 = CollectionsKt.R(compiledFieldC41, compiledFieldC42, compiledFieldC43, builder35.c());
        K = listR30;
        List listR31 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        L = listR31;
        List listR32 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        M = listR32;
        List listQ8 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        N = listQ8;
        List listQ9 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        O = listQ9;
        CompiledField compiledFieldC44 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder36 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder36.b(listQ8);
        CompiledFragment compiledFragmentA4 = builder36.a();
        CompiledFragment.Builder builder37 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder37.b(listQ9);
        List listR33 = CollectionsKt.R(compiledFieldC44, compiledFragmentA4, builder37.a());
        P = listR33;
        CompiledField compiledFieldC45 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC46 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CoreBroadcastBannerStyle.e.getClass();
        CompiledField compiledFieldC47 = new CompiledField.Builder("style", CompiledGraphQL.b(CoreBroadcastBannerStyle.Companion.a())).c();
        UnionType unionType = IconAsset.f11477a;
        CompiledField.Builder builder38 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(IconAsset.Companion.a()));
        builder38.e(listR33);
        List listR34 = CollectionsKt.R(compiledFieldC45, compiledFieldC46, compiledFieldC47, builder38.c());
        Q = listR34;
        List listR35 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        R = listR35;
        CompiledField compiledFieldC48 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC49 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        ActionType.e.getClass();
        CompiledField compiledFieldC50 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField.Builder builder39 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder39.e(listR35);
        List listR36 = CollectionsKt.R(compiledFieldC48, compiledFieldC49, compiledFieldC50, builder39.c());
        S = listR36;
        CompiledField.Builder builder40 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder40.e(listR31);
        CompiledField compiledFieldC51 = builder40.c();
        CompiledField.Builder builder41 = new CompiledField.Builder("broadcastBannerDismissAnalytics", Analytics.Companion.a());
        builder41.e(listR32);
        CompiledField compiledFieldC52 = builder41.c();
        ObjectType objectType7 = CoreBroadcastBannerUI.f11286a;
        CompiledField.Builder builder42 = new CompiledField.Builder("broadcastBannerUI", CompiledGraphQL.b(CoreBroadcastBannerUI.Companion.a()));
        builder42.e(listR34);
        CompiledField compiledFieldC53 = builder42.c();
        ObjectType objectType8 = Action.f10997a;
        CompiledField.Builder builder43 = new CompiledField.Builder("broadcastBannerAction", Action.Companion.a());
        builder43.e(listR36);
        List listR37 = CollectionsKt.R(compiledFieldC51, compiledFieldC52, compiledFieldC53, builder43.c(), new CompiledField.Builder("broadcastBannerActionLabel", GraphQLString.Companion.a()).c(), new CompiledField.Builder("broadcastBannerId", GraphQLString.Companion.a()).c(), new CompiledField.Builder("broadcastBannerDismissible", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        T = listR37;
        AlertIndicatorType.e.getClass();
        EnumType enumType = AlertIndicatorType.f;
        List listR38 = CollectionsKt.R(new CompiledField.Builder("indicatorType", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        U = listR38;
        List listR39 = CollectionsKt.R(new CompiledField.Builder("indicatorType", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        V = listR39;
        CompiledField compiledFieldC54 = new CompiledField.Builder("edrNumber", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC55 = new CompiledField.Builder("rewardsState", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC56 = new CompiledField.Builder("offersTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC57 = new CompiledField.Builder("currentBalance", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC58 = new CompiledField.Builder("goalBalance", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC59 = new CompiledField.Builder("actionUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC60 = new CompiledField.Builder("pointsDescriptionFormat", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC61 = new CompiledField.Builder("pointsDescriptionReplacements", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        CompiledField compiledFieldC62 = new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType9 = AlertIndicator.f11016a;
        CompiledField.Builder builder44 = new CompiledField.Builder("offersAlertIndicator", objectType9);
        builder44.e(listR38);
        CompiledField compiledFieldC63 = builder44.c();
        CompiledField.Builder builder45 = new CompiledField.Builder("pointsAlertIndicator", objectType9);
        builder45.e(listR39);
        List listR40 = CollectionsKt.R(compiledFieldC54, compiledFieldC55, compiledFieldC56, compiledFieldC57, compiledFieldC58, compiledFieldC59, compiledFieldC60, compiledFieldC61, compiledFieldC62, compiledFieldC63, builder45.c());
        W = listR40;
        CompiledField compiledFieldC64 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC65 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC66 = new CompiledField.Builder("deeplink", GraphQLString.Companion.a()).c();
        BroadcastBannerType.e.getClass();
        List listR41 = CollectionsKt.R(compiledFieldC64, compiledFieldC65, compiledFieldC66, new CompiledField.Builder("type", CompiledGraphQL.b(BroadcastBannerType.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("actionLabel", GraphQLString.Companion.a()).c(), new CompiledField.Builder("analyticsLabel", GraphQLString.Companion.a()).c(), new CompiledField.Builder("dismissible", GraphQLBoolean.Companion.a()).c(), new CompiledField.Builder("bannerId", GraphQLString.Companion.a()).c());
        X = listR41;
        List listR42 = CollectionsKt.R(new CompiledField.Builder("myListTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("myListSubtitle", GraphQLString.Companion.a()).c(), new CompiledField.Builder("myListActionTitle", GraphQLString.Companion.a()).c(), new CompiledField.Builder("myListDeepLink", GraphQLString.Companion.a()).c());
        Y = listR42;
        List listR43 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        Z = listR43;
        CompiledField compiledFieldC67 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder46 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder46.e(listR43);
        List listR44 = CollectionsKt.R(compiledFieldC67, builder46.c(), new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c());
        a0 = listR44;
        List listR45 = CollectionsKt.R(new CompiledField.Builder("key", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("value", GraphQLString.Companion.a()).c());
        b0 = listR45;
        CompiledField compiledFieldC68 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment compiledFragmentD = d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics")));
        CompiledField.Builder builder47 = new CompiledField.Builder("extraContent", CompiledGraphQL.a(CompiledGraphQL.b(AnalyticsExtraContent.f11029a)));
        builder47.e(listR45);
        List listR46 = CollectionsKt.R(compiledFieldC68, compiledFragmentD, builder47.c());
        c0 = listR46;
        List listR47 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        d0 = listR47;
        List listQ10 = CollectionsKt.Q(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        e0 = listQ10;
        List listR48 = CollectionsKt.R(new CompiledField.Builder("code", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        f0 = listR48;
        CompiledField compiledFieldC69 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder48 = new CompiledFragment.Builder("HeroBannerBodyText", CollectionsKt.Q("HeroBannerBodyText"));
        builder48.b(listQ10);
        CompiledFragment compiledFragmentA5 = builder48.a();
        CompiledFragment.Builder builder49 = new CompiledFragment.Builder("HeroBannerPromoBody", CollectionsKt.Q("HeroBannerPromoBody"));
        builder49.b(listR48);
        List listR49 = CollectionsKt.R(compiledFieldC69, compiledFragmentA5, builder49.a());
        g0 = listR49;
        List listR50 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        h0 = listR50;
        List listR51 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        i0 = listR51;
        List listR52 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        j0 = listR52;
        List listR53 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        k0 = listR53;
        CompiledField compiledFieldC70 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC71 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC72 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder50 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder50.e(listR53);
        List listR54 = CollectionsKt.R(compiledFieldC70, compiledFieldC71, compiledFieldC72, builder50.c());
        l0 = listR54;
        CompiledField compiledFieldC73 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder51 = new CompiledField.Builder(UrlHandler.ACTION, Action.Companion.a());
        builder51.a("heroBannerTermsAndConditionAction");
        builder51.e(listR54);
        List listR55 = CollectionsKt.R(compiledFieldC73, builder51.c());
        m0 = listR55;
        CompiledField compiledFieldC74 = new CompiledField.Builder("heroBannerId", CompiledGraphQL.b(GraphQLID.Companion.a())).c();
        CompiledField.Builder builder52 = new CompiledField.Builder("heroBannerAction", CompiledGraphQL.b(Action.Companion.a()));
        builder52.e(listR44);
        CompiledField compiledFieldC75 = builder52.c();
        CompiledField.Builder builder53 = new CompiledField.Builder("heroBannerAnalytics", CompiledGraphQL.b(Analytics.Companion.a()));
        builder53.e(listR46);
        CompiledField compiledFieldC76 = builder53.c();
        CompiledField.Builder builder54 = new CompiledField.Builder("heroBannerImpressionAnalytics", CompiledGraphQL.b(Analytics.Companion.a()));
        builder54.e(listR47);
        CompiledField compiledFieldC77 = builder54.c();
        CompiledField compiledFieldC78 = new CompiledField.Builder("heroBannerBackgroundColour", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC79 = new CompiledField.Builder("heroBannerTextColour", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder55 = new CompiledField.Builder("heroBannerBody", HeroBannerBody.f11451a);
        builder55.e(listR49);
        CompiledField compiledFieldC80 = builder55.c();
        ObjectType objectType10 = ImageWithAlt.f11487a;
        CompiledField.Builder builder56 = new CompiledField.Builder("heroBannerBrandsLogo", ImageWithAlt.Companion.a());
        builder56.e(listR50);
        CompiledField compiledFieldC81 = builder56.c();
        CompiledField.Builder builder57 = new CompiledField.Builder("heroBannerGraphics", CompiledGraphQL.a(CompiledGraphQL.b(ImageWithAlt.Companion.a())));
        builder57.e(listR51);
        CompiledField compiledFieldC82 = builder57.c();
        CompiledField.Builder builder58 = new CompiledField.Builder("heroBannerImages", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(ImageWithAlt.Companion.a()))));
        builder58.e(listR52);
        CompiledField compiledFieldC83 = builder58.c();
        CompiledField.Builder builder59 = new CompiledField.Builder("heroBannerTermsAndConditions", HeroBannerTermsAndConditions.f11454a);
        builder59.e(listR55);
        CompiledField compiledFieldC84 = builder59.c();
        CompiledField compiledFieldC85 = new CompiledField.Builder("heroBannerTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        HeroBannerTitleSize.e.getClass();
        List listR56 = CollectionsKt.R(compiledFieldC74, compiledFieldC75, compiledFieldC76, compiledFieldC77, compiledFieldC78, compiledFieldC79, compiledFieldC80, compiledFieldC81, compiledFieldC82, compiledFieldC83, compiledFieldC84, compiledFieldC85, new CompiledField.Builder("heroBannerTitleSize", CompiledGraphQL.b(HeroBannerTitleSize.f)).c());
        n0 = listR56;
        CompiledField compiledFieldC86 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder60 = new CompiledFragment.Builder("HeroBanner", CollectionsKt.Q("HeroBanner"));
        builder60.b(listR56);
        List listR57 = CollectionsKt.R(compiledFieldC86, builder60.a());
        o0 = listR57;
        CompiledField.Builder builder61 = new CompiledField.Builder("carouselItems", d.j(CarouselItem.f11098a));
        builder61.e(listR57);
        List listQ11 = CollectionsKt.Q(builder61.c());
        p0 = listQ11;
        List listQ12 = CollectionsKt.Q(new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c());
        q0 = listQ12;
        List listR58 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        r0 = listR58;
        CompiledField compiledFieldC87 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder62 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder62.b(listR58);
        List listR59 = CollectionsKt.R(compiledFieldC87, builder62.a());
        s0 = listR59;
        CompiledField compiledFieldC88 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC89 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC90 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC91 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC92 = new CompiledField.Builder("deepLink", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC93 = new CompiledField.Builder("tigerOfferIds", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        UnionType unionType2 = HorizontalListItem.f11475a;
        CompiledField.Builder builder63 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder63.e(listR59);
        List listR60 = CollectionsKt.R(compiledFieldC88, compiledFieldC89, compiledFieldC90, compiledFieldC91, compiledFieldC92, compiledFieldC93, builder63.c());
        t0 = listR60;
        List listR61 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        u0 = listR61;
        List listR62 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        v0 = listR62;
        CompiledField compiledFieldC94 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC95 = new CompiledField.Builder("contentMarkdown", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC96 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC97 = new CompiledField.Builder("buttonText", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC98 = new CompiledField.Builder("accessibilityText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder64 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder64.e(listR62);
        List listR63 = CollectionsKt.R(compiledFieldC94, compiledFieldC95, compiledFieldC96, compiledFieldC97, compiledFieldC98, builder64.c());
        w0 = listR63;
        List listR64 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        x0 = listR64;
        CompiledField compiledFieldC99 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC100 = new CompiledField.Builder("contentMarkdown", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC101 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC102 = new CompiledField.Builder("buttonText", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC103 = new CompiledField.Builder("accessibilityText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder65 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder65.e(listR64);
        List listR65 = CollectionsKt.R(compiledFieldC99, compiledFieldC100, compiledFieldC101, compiledFieldC102, compiledFieldC103, builder65.c());
        y0 = listR65;
        List listR66 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        z0 = listR66;
        List listR67 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        A0 = listR67;
        List listR68 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        B0 = listR68;
        List listR69 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        C0 = listR69;
        List listR70 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        D0 = listR70;
        CompiledField.Builder builder66 = new CompiledField.Builder("impression", Analytics.Companion.a());
        builder66.e(listR67);
        CompiledField compiledFieldC104 = builder66.c();
        CompiledField.Builder builder67 = new CompiledField.Builder("videoPlay", Analytics.Companion.a());
        builder67.e(listR68);
        CompiledField compiledFieldC105 = builder67.c();
        CompiledField.Builder builder68 = new CompiledField.Builder("videoPause", Analytics.Companion.a());
        builder68.e(listR69);
        CompiledField compiledFieldC106 = builder68.c();
        CompiledField.Builder builder69 = new CompiledField.Builder("videoErrorImpression", Analytics.Companion.a());
        builder69.e(listR70);
        List listR71 = CollectionsKt.R(compiledFieldC104, compiledFieldC105, compiledFieldC106, builder69.c());
        E0 = listR71;
        CompiledField compiledFieldC107 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC108 = new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder70 = new CompiledField.Builder("fallbackImage", ImageWithAlt.Companion.a());
        builder70.e(listR61);
        CompiledField compiledFieldC109 = builder70.c();
        CompiledField compiledFieldC110 = new CompiledField.Builder("duration", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        ObjectType objectType11 = VideoAdBottomSheet.f12008a;
        CompiledField.Builder builder71 = new CompiledField.Builder("transcript", VideoAdBottomSheet.Companion.a());
        builder71.e(listR63);
        CompiledField compiledFieldC111 = builder71.c();
        CompiledField.Builder builder72 = new CompiledField.Builder("termsAndConditions", VideoAdBottomSheet.Companion.a());
        builder72.e(listR65);
        CompiledField compiledFieldC112 = builder72.c();
        CompiledField.Builder builder73 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder73.e(listR66);
        CompiledField compiledFieldC113 = builder73.c();
        CompiledField.Builder builder74 = new CompiledField.Builder("eventAnalytics", VideoAdEventAnalytics.f12009a);
        builder74.e(listR71);
        List listR72 = CollectionsKt.R(compiledFieldC107, compiledFieldC108, compiledFieldC109, compiledFieldC110, compiledFieldC111, compiledFieldC112, compiledFieldC113, builder74.c());
        F0 = listR72;
        List listR73 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        G0 = listR73;
        CompiledField compiledFieldC114 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder75 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder75.b(listR73);
        List listR74 = CollectionsKt.R(compiledFieldC114, builder75.a());
        H0 = listR74;
        CompiledField compiledFieldC115 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder76 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder76.e(listR74);
        List listR75 = CollectionsKt.R(compiledFieldC115, builder76.c());
        I0 = listR75;
        List listR76 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        J0 = listR76;
        List listR77 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        K0 = listR77;
        CompiledField compiledFieldC116 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC117 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC118 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder77 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder77.e(listR77);
        List listR78 = CollectionsKt.R(compiledFieldC116, compiledFieldC117, compiledFieldC118, builder77.c(), new CompiledField.Builder("id", GraphQLString.Companion.a()).c());
        L0 = listR78;
        CompiledField compiledFieldC119 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC120 = new CompiledField.Builder("linkId", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder78 = new CompiledField.Builder("linkTextWithAlt", CompiledGraphQL.b(TextWithAlt.Companion.a()));
        builder78.e(listR76);
        CompiledField compiledFieldC121 = builder78.c();
        CompiledField.Builder builder79 = new CompiledField.Builder("linkAction", CompiledGraphQL.b(Action.Companion.a()));
        builder79.e(listR78);
        List listR79 = CollectionsKt.R(compiledFieldC119, compiledFieldC120, compiledFieldC121, builder79.c());
        M0 = listR79;
        CompiledField compiledFieldC122 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder80 = new CompiledField.Builder("videoAdUnitVideoAd", CompiledGraphQL.b(VideoAd.f12007a));
        builder80.e(listR72);
        CompiledField compiledFieldC123 = builder80.c();
        ObjectType objectType12 = VideoAdUnitCarousel.f12011a;
        CompiledField.Builder builder81 = new CompiledField.Builder("videoAdUnitCarousel", VideoAdUnitCarousel.Companion.a());
        builder81.e(listR75);
        CompiledField compiledFieldC124 = builder81.c();
        ObjectType objectType13 = Link.f11514a;
        CompiledField.Builder builder82 = new CompiledField.Builder("videoAdUnitBottomLink", Link.Companion.a());
        builder82.e(listR79);
        List listR80 = CollectionsKt.R(compiledFieldC122, compiledFieldC123, compiledFieldC124, builder82.c());
        N0 = listR80;
        List listR81 = CollectionsKt.R(new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        O0 = listR81;
        List listR82 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        P0 = listR82;
        CompiledField compiledFieldC125 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC126 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder83 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder83.e(listR82);
        List listR83 = CollectionsKt.R(compiledFieldC125, compiledFieldC126, builder83.c(), new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c());
        Q0 = listR83;
        CompiledField.Builder builder84 = new CompiledField.Builder("linkTextWithAlt", CompiledGraphQL.b(TextWithAlt.Companion.a()));
        builder84.e(listR81);
        CompiledField compiledFieldC127 = builder84.c();
        CompiledField compiledFieldC128 = new CompiledField.Builder("linkId", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder85 = new CompiledField.Builder("linkAction", CompiledGraphQL.b(Action.Companion.a()));
        builder85.e(listR83);
        List listR84 = CollectionsKt.R(compiledFieldC127, compiledFieldC128, builder85.c());
        R0 = listR84;
        List listR85 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        S0 = listR85;
        List listR86 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        T0 = listR86;
        List listR87 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        U0 = listR87;
        List listR88 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("buttonLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        V0 = listR88;
        List listR89 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        W0 = listR89;
        CompiledField compiledFieldC129 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC130 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder86 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder86.e(listR89);
        List listR90 = CollectionsKt.R(compiledFieldC129, compiledFieldC130, builder86.c());
        X0 = listR90;
        CompiledField compiledFieldC131 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC132 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC133 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        OrderStatus.e.getClass();
        CompiledField compiledFieldC134 = new CompiledField.Builder("status", CompiledGraphQL.b(OrderStatus.f)).c();
        CompiledField compiledFieldC135 = new CompiledField.Builder("orderCardId", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC136 = new CompiledField.Builder("total", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC137 = new CompiledField.Builder("timeLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC138 = new CompiledField.Builder("timeValue", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC139 = new CompiledField.Builder("date", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder87 = new CompiledField.Builder("fulfilmentStatusBanner", FulfilmentStatusBanner.f11412a);
        builder87.e(listR88);
        CompiledField compiledFieldC140 = builder87.c();
        CompiledField.Builder builder88 = new CompiledField.Builder("orderCardAction", CompiledGraphQL.b(Action.Companion.a()));
        builder88.e(listR90);
        List listR91 = CollectionsKt.R(compiledFieldC131, compiledFieldC132, compiledFieldC133, compiledFieldC134, compiledFieldC135, compiledFieldC136, compiledFieldC137, compiledFieldC138, compiledFieldC139, compiledFieldC140, builder88.c());
        Y0 = listR91;
        List listR92 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        Z0 = listR92;
        CompiledField compiledFieldC141 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC142 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder89 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder89.e(listR92);
        List listR93 = CollectionsKt.R(compiledFieldC141, compiledFieldC142, builder89.c());
        a1 = listR93;
        List listR94 = CollectionsKt.R(new CompiledField.Builder("source", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("playCount", CompiledGraphQL.b(GraphQLInt.Companion.a())).c());
        b1 = listR94;
        CompiledField compiledFieldC143 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC144 = new CompiledField.Builder("linkCardTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC145 = new CompiledField.Builder("linkCardSubtitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC146 = new CompiledField.Builder("linkCardImage", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder90 = new CompiledField.Builder("linkCardAction", CompiledGraphQL.b(Action.Companion.a()));
        builder90.e(listR93);
        List listR95 = CollectionsKt.R(compiledFieldC143, compiledFieldC144, compiledFieldC145, compiledFieldC146, builder90.c(), a.e("includeCampaignAnimation", false, new CompiledField.Builder("linkCardAnimation", OverlayAnimation.f11679a), listR94), new CompiledField.Builder("isQuickLinkView", GraphQLBoolean.Companion.a()).c());
        c1 = listR95;
        CompiledField compiledFieldC147 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder91 = new CompiledFragment.Builder("RecipeSummaryCard", CollectionsKt.Q("RecipeSummaryCard"));
        builder91.b(RecipeSummaryCardFragmentSelections.d);
        List listR96 = CollectionsKt.R(compiledFieldC147, builder91.a());
        d1 = listR96;
        List listQ13 = CollectionsKt.Q(new CompiledField.Builder(k.a.g, CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c());
        e1 = listQ13;
        List listQ14 = CollectionsKt.Q(new CompiledField.Builder("source", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        f1 = listQ14;
        CompiledField compiledFieldC148 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder92 = new CompiledFragment.Builder("RecipeTagList", CollectionsKt.Q("RecipeTagList"));
        builder92.b(listQ13);
        CompiledFragment compiledFragmentA6 = builder92.a();
        CompiledFragment.Builder builder93 = new CompiledFragment.Builder("RecipeSource", CollectionsKt.Q("RecipeSource"));
        builder93.b(listQ14);
        List listR97 = CollectionsKt.R(compiledFieldC148, compiledFragmentA6, builder93.a());
        g1 = listR97;
        CompiledField.Builder builder94 = new CompiledField.Builder("actionMetadata", d.j(ActionMetaData.f10998a));
        builder94.e(listR97);
        List listQ15 = CollectionsKt.Q(builder94.c());
        h1 = listQ15;
        List listR98 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        i1 = listR98;
        CompiledField compiledFieldC149 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC150 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder95 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder95.e(listR98);
        List listR99 = CollectionsKt.R(compiledFieldC149, compiledFieldC150, builder95.c());
        j1 = listR99;
        List listR100 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        k1 = listR100;
        FooterStyle.e.getClass();
        CompiledField compiledFieldC151 = new CompiledField.Builder("style", CompiledGraphQL.b(FooterStyle.f)).c();
        CompiledField compiledFieldC152 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, GraphQLString.Companion.a()).c();
        CompiledField.Builder builder96 = new CompiledField.Builder("logo", ImageWithAlt.Companion.a());
        builder96.e(listR100);
        List listR101 = CollectionsKt.R(compiledFieldC151, compiledFieldC152, builder96.c());
        l1 = listR101;
        List listR102 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        m1 = listR102;
        CompiledField compiledFieldC153 = new CompiledField.Builder("contentCardId", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC154 = new CompiledField.Builder("contentCardImageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC155 = new CompiledField.Builder("contentCardTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC156 = new CompiledField.Builder("contentCardDescription", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder97 = new CompiledField.Builder("contentCardAction", Action.Companion.a());
        builder97.e(listR99);
        CompiledField compiledFieldC157 = builder97.c();
        CompiledField.Builder builder98 = new CompiledField.Builder("contentCardFooter", ContentCardFooter.f11281a);
        builder98.e(listR101);
        CompiledField compiledFieldC158 = builder98.c();
        CompiledField.Builder builder99 = new CompiledField.Builder("contentCardBrandImage", ImageWithAlt.Companion.a());
        builder99.e(listR102);
        CompiledField compiledFieldC159 = builder99.c();
        CompiledField compiledFieldC160 = new CompiledField.Builder("contentCardIsVideoAvailable", GraphQLBoolean.Companion.a()).c();
        ContentCardSize.e.getClass();
        List listR103 = CollectionsKt.R(compiledFieldC153, compiledFieldC154, compiledFieldC155, compiledFieldC156, compiledFieldC157, compiledFieldC158, compiledFieldC159, compiledFieldC160, new CompiledField.Builder("contentCardSize", ContentCardSize.f).c());
        n1 = listR103;
        List listR104 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        o1 = listR104;
        List listR105 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        p1 = listR105;
        List listR106 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        q1 = listR106;
        ObjectType objectType14 = ProductCard.f11717a;
        CompiledField.Builder builder100 = new CompiledField.Builder("promotionCardProduct", CompiledGraphQL.b(ProductCard.Companion.a()));
        builder100.e(listR104);
        CompiledField compiledFieldC161 = builder100.c();
        CompiledField compiledFieldC162 = new CompiledField.Builder("promotionCardOfferId", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder101 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder101.e(listR105);
        CompiledField compiledFieldC163 = builder101.c();
        CompiledField.Builder builder102 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder102.e(listR106);
        List listR107 = CollectionsKt.R(compiledFieldC161, compiledFieldC162, compiledFieldC163, builder102.c());
        r1 = listR107;
        CompiledField compiledFieldC164 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder103 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder103.b(listR87);
        CompiledFragment compiledFragmentA7 = builder103.a();
        CompiledFragment.Builder builder104 = new CompiledFragment.Builder("OrderCard", CollectionsKt.Q("OrderCard"));
        builder104.b(listR91);
        CompiledFragment compiledFragmentA8 = builder104.a();
        CompiledFragment.Builder builder105 = new CompiledFragment.Builder("QuickLinkCard", CollectionsKt.Q("QuickLinkCard"));
        builder105.b(listR95);
        CompiledFragment compiledFragmentA9 = builder105.a();
        CompiledFragment.Builder builder106 = new CompiledFragment.Builder("RecipeSummaryCard", CollectionsKt.Q("RecipeSummaryCard"));
        builder106.b(listR96);
        CompiledFragment compiledFragmentA10 = builder106.a();
        CompiledFragment.Builder builder107 = new CompiledFragment.Builder("RecipeMoreCard", CollectionsKt.Q("RecipeMoreCard"));
        builder107.b(listQ15);
        CompiledFragment compiledFragmentA11 = builder107.a();
        CompiledFragment.Builder builder108 = new CompiledFragment.Builder("ContentCard", CollectionsKt.Q("ContentCard"));
        builder108.b(listR103);
        CompiledFragment compiledFragmentA12 = builder108.a();
        CompiledFragment.Builder builder109 = new CompiledFragment.Builder("PromotionCard", CollectionsKt.Q("PromotionCard"));
        builder109.b(listR107);
        List listR108 = CollectionsKt.R(compiledFieldC164, compiledFragmentA7, compiledFragmentA8, compiledFragmentA9, compiledFragmentA10, compiledFragmentA11, compiledFragmentA12, builder109.a());
        s1 = listR108;
        CompiledField compiledFieldC165 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder110 = new CompiledField.Builder("horizontalListTrailingLink", Link.Companion.a());
        builder110.e(listR84);
        CompiledField compiledFieldC166 = builder110.c();
        CompiledField.Builder builder111 = new CompiledField.Builder("horizontalListAnalytics", Analytics.Companion.a());
        builder111.e(listR85);
        CompiledField compiledFieldC167 = builder111.c();
        CompiledField.Builder builder112 = new CompiledField.Builder("horizontalListImpressionAnalytics", Analytics.Companion.a());
        builder112.e(listR86);
        CompiledField compiledFieldC168 = builder112.c();
        CompiledField compiledFieldC169 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC170 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC171 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC172 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC173 = new CompiledField.Builder("deepLink", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder113 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder113.e(listR108);
        List listR109 = CollectionsKt.R(compiledFieldC165, compiledFieldC166, compiledFieldC167, compiledFieldC168, compiledFieldC169, compiledFieldC170, compiledFieldC171, compiledFieldC172, compiledFieldC173, builder113.c());
        t1 = listR109;
        List listR110 = CollectionsKt.R(new CompiledField.Builder("key", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("value", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        u1 = listR110;
        CompiledField compiledFieldC174 = new CompiledField.Builder("source", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType15 = ChatEntryCardContextData.f11180a;
        CompiledField.Builder builder114 = new CompiledField.Builder("data", CompiledGraphQL.a(CompiledGraphQL.b(ChatEntryCardContextData.Companion.a())));
        builder114.e(listR110);
        List listR111 = CollectionsKt.R(compiledFieldC174, builder114.c());
        v1 = listR111;
        List listR112 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        w1 = listR112;
        CompiledField compiledFieldC175 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC176 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC177 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField.Builder builder115 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder115.e(listR112);
        List listR113 = CollectionsKt.R(compiledFieldC175, compiledFieldC176, compiledFieldC177, builder115.c());
        x1 = listR113;
        CompiledField compiledFieldC178 = new CompiledField.Builder("chatEntryCardCtaIconUrl", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC179 = new CompiledField.Builder("chatEntryCardPrompts", CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a()))).c();
        ChatEntryCardElement.e.getClass();
        CompiledField compiledFieldC180 = new CompiledField.Builder("chatEntryCardElement", CompiledGraphQL.b(ChatEntryCardElement.Companion.a())).c();
        ObjectType objectType16 = ChatEntryCardContext.f11179a;
        CompiledField.Builder builder116 = new CompiledField.Builder("chatEntryCardContext", CompiledGraphQL.b(ChatEntryCardContext.Companion.a()));
        builder116.e(listR111);
        CompiledField compiledFieldC181 = builder116.c();
        CompiledField.Builder builder117 = new CompiledField.Builder("chatEntryCardAction", CompiledGraphQL.b(Action.Companion.a()));
        builder117.e(listR113);
        List listR114 = CollectionsKt.R(compiledFieldC178, compiledFieldC179, compiledFieldC180, compiledFieldC181, builder117.c());
        y1 = listR114;
        CompiledField compiledFieldC182 = new CompiledField.Builder("chatEntryCardTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC183 = new CompiledField.Builder("chatEntryCardSubtitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC184 = new CompiledField.Builder("chatEntryCardShowBeta", GraphQLBoolean.Companion.a()).c();
        CompiledField compiledFieldC185 = new CompiledField.Builder("chatEntryCardImageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType17 = ChatEntryCardCta.f11181a;
        CompiledField.Builder builder118 = new CompiledField.Builder("chatEntryCardCtas", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(ChatEntryCardCta.Companion.a()))));
        builder118.e(listR114);
        List listR115 = CollectionsKt.R(compiledFieldC182, compiledFieldC183, compiledFieldC184, compiledFieldC185, builder118.c());
        z1 = listR115;
        CompiledField compiledFieldC186 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder119 = new CompiledFragment.Builder("RegistrationCard", CollectionsKt.Q("RegistrationCard"));
        builder119.b(listQ7);
        CompiledFragment compiledFragmentA13 = builder119.a();
        CompiledFragment.Builder builder120 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder120.b(listR28);
        CompiledFragment compiledFragmentA14 = builder120.a();
        CompiledFragment.Builder builder121 = new CompiledFragment.Builder("InsetBanner", CollectionsKt.Q("InsetBanner"));
        builder121.b(listR30);
        CompiledFragment compiledFragmentA15 = builder121.a();
        CompiledFragment.Builder builder122 = new CompiledFragment.Builder("BasicCoreBroadcastBanner", CollectionsKt.Q("BasicCoreBroadcastBanner"));
        builder122.b(listR37);
        CompiledFragment compiledFragmentA16 = builder122.a();
        CompiledFragment.Builder builder123 = new CompiledFragment.Builder("RewardsBalanceCard", CollectionsKt.Q("RewardsBalanceCard"));
        builder123.b(listR40);
        CompiledFragment compiledFragmentA17 = builder123.a();
        CompiledFragment.Builder builder124 = new CompiledFragment.Builder("BroadcastBanner", CollectionsKt.Q("BroadcastBanner"));
        builder124.b(listR41);
        CompiledFragment compiledFragmentA18 = builder124.a();
        CompiledFragment.Builder builder125 = new CompiledFragment.Builder("MyShoppingLists", CollectionsKt.Q("MyShoppingLists"));
        builder125.b(listR42);
        CompiledFragment compiledFragmentA19 = builder125.a();
        CompiledFragment.Builder builder126 = new CompiledFragment.Builder("Carousel", CollectionsKt.Q("Carousel"));
        builder126.b(listQ11);
        CompiledFragment compiledFragmentA20 = builder126.a();
        CompiledFragment.Builder builder127 = new CompiledFragment.Builder("RegistrationCard", CollectionsKt.Q("RegistrationCard"));
        builder127.b(listQ12);
        CompiledFragment compiledFragmentA21 = builder127.a();
        CompiledFragment.Builder builder128 = new CompiledFragment.Builder("BoosterHorizontalList", CollectionsKt.Q("BoosterHorizontalList"));
        builder128.b(listR60);
        CompiledFragment compiledFragmentA22 = builder128.a();
        CompiledFragment compiledFragmentI = d.i("includeVideoAdUnit", false, new CompiledFragment.Builder("VideoAdUnit", CollectionsKt.Q("VideoAdUnit")), listR80);
        CompiledFragment.Builder builder129 = new CompiledFragment.Builder("HorizontalList", CollectionsKt.Q("HorizontalList"));
        builder129.b(listR109);
        List listR116 = CollectionsKt.R(compiledFieldC186, compiledFragmentA13, compiledFragmentA14, compiledFragmentA15, compiledFragmentA16, compiledFragmentA17, compiledFragmentA18, compiledFragmentA19, compiledFragmentA20, compiledFragmentA21, compiledFragmentA22, compiledFragmentI, builder129.a(), d.i("includeChatEntryCard", false, new CompiledFragment.Builder("ChatEntryCardV2", CollectionsKt.Q("ChatEntryCardV2")), listR115));
        A1 = listR116;
        CompiledField.Builder builder130 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder130.e(listR24);
        CompiledField compiledFieldC187 = builder130.c();
        CompiledField.Builder builder131 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder131.e(listR25);
        CompiledField compiledFieldC188 = builder131.c();
        CompiledField.Builder builder132 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(GenericPageFeedItem.f11427a)));
        builder132.e(listR116);
        List listR117 = CollectionsKt.R(compiledFieldC187, compiledFieldC188, builder132.c());
        B1 = listR117;
        CompiledField.Builder builder133 = new CompiledField.Builder("home", HomeList.f11464a);
        new CompiledArgument.Builder(Query.r);
        CompiledArgument compiledArgumentA = CompiledArgument.Builder.a();
        new CompiledArgument.Builder(Query.u);
        CompiledArgument compiledArgumentA2 = CompiledArgument.Builder.a();
        new CompiledArgument.Builder(Query.t);
        CompiledArgument compiledArgumentA3 = CompiledArgument.Builder.a();
        new CompiledArgument.Builder(Query.s);
        CompiledArgument compiledArgumentA4 = CompiledArgument.Builder.a();
        new CompiledArgument.Builder(Query.v);
        builder133.b(CollectionsKt.R(compiledArgumentA, compiledArgumentA2, compiledArgumentA3, compiledArgumentA4, CompiledArgument.Builder.a()));
        builder133.e(listR23);
        CompiledField compiledFieldC189 = builder133.c();
        ObjectType objectType18 = HomePage.f11470a;
        CompiledField.Builder builder134 = new CompiledField.Builder("homePage", CompiledGraphQL.b(HomePage.Companion.a()));
        new CompiledArgument.Builder(Query.Companion.a());
        builder134.b(CollectionsKt.Q(CompiledArgument.Builder.a()));
        builder134.e(listR117);
        C1 = CollectionsKt.R(compiledFieldC189, builder134.c());
    }
}
