package com.woolworths.shop.homepage.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.shop.aem.components.recipes.fragment.selections.RecipeSummaryCardFragmentSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionMetaData;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.AdBannerNativeSize;
import au.com.woolworths.shop.graphql.type.AlertIndicator;
import au.com.woolworths.shop.graphql.type.AlertIndicatorType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.AnalyticsExtraContent;
import au.com.woolworths.shop.graphql.type.BroadcastBannerType;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.CardHeight;
import au.com.woolworths.shop.graphql.type.CarouselItem;
import au.com.woolworths.shop.graphql.type.ContentCta;
import au.com.woolworths.shop.graphql.type.DividerCard;
import au.com.woolworths.shop.graphql.type.DownloadableAsset;
import au.com.woolworths.shop.graphql.type.DownloadableAssetFit;
import au.com.woolworths.shop.graphql.type.DownloadableAssetType;
import au.com.woolworths.shop.graphql.type.FulfilmentStatusBanner;
import au.com.woolworths.shop.graphql.type.GoogleAdCustomTargeting;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLID;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.HeroBannerBody;
import au.com.woolworths.shop.graphql.type.HeroBannerTermsAndConditions;
import au.com.woolworths.shop.graphql.type.HeroBannerTitleSize;
import au.com.woolworths.shop.graphql.type.HomeDeliveryNowBanner;
import au.com.woolworths.shop.graphql.type.HomeDeliveryNowBannerUnion;
import au.com.woolworths.shop.graphql.type.HomeFeed;
import au.com.woolworths.shop.graphql.type.HomeFulfilmentWindowContainerOrientation;
import au.com.woolworths.shop.graphql.type.HomeFulfilmentWindowTile;
import au.com.woolworths.shop.graphql.type.HomeFulfilmentWindowTileAnalytics;
import au.com.woolworths.shop.graphql.type.HomeFulfilmentWindowTileStyle;
import au.com.woolworths.shop.graphql.type.HomeHeaderItems;
import au.com.woolworths.shop.graphql.type.HomeList;
import au.com.woolworths.shop.graphql.type.HomeListAnalytics;
import au.com.woolworths.shop.graphql.type.HomeListDeliveryNow;
import au.com.woolworths.shop.graphql.type.HomeOnlineShoppingModeVariantTile;
import au.com.woolworths.shop.graphql.type.HomeOnlineShoppingModeVariantTileAnalytics;
import au.com.woolworths.shop.graphql.type.HorizontalListItem;
import au.com.woolworths.shop.graphql.type.ImageWithAlt;
import au.com.woolworths.shop.graphql.type.InStoreDetailsCard;
import au.com.woolworths.shop.graphql.type.InsetBannerAction;
import au.com.woolworths.shop.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.shop.graphql.type.InsetBannerActionType;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.OrderStatus;
import au.com.woolworths.shop.graphql.type.OverlayAnimation;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.QuickLinkCard;
import au.com.woolworths.shop.graphql.type.TealiumAnalytics;
import au.com.woolworths.shop.graphql.type.TextWithAlt;
import au.com.woolworths.shop.graphql.type.TextWithLink;
import au.com.woolworths.shop.graphql.type.UnreadChatbotMsg;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.google.android.gms.ads.OutOfContextTestingActivity;
import com.google.android.gms.common.api.internal.a;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.salesforce.marketingcloud.storage.db.k;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/homepage/selections/HomeQuerySelections;", "", "homepage_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class HomeQuerySelections {
    public static final List A;
    public static final List A0;
    public static final List B;
    public static final List B0;
    public static final List C;
    public static final List C0;
    public static final List D;
    public static final List D0;
    public static final List E;
    public static final List E0;
    public static final List F;
    public static final List F0;
    public static final List G;
    public static final List G0;
    public static final List H;
    public static final List H0;
    public static final List I;
    public static final List I0;
    public static final List J;
    public static final List K;
    public static final List L;
    public static final List M;
    public static final List N;
    public static final List O;
    public static final List P;
    public static final List Q;
    public static final List R;
    public static final List S;
    public static final List T;
    public static final List U;
    public static final List V;
    public static final List W;
    public static final List X;
    public static final List Y;
    public static final List Z;

    /* renamed from: a, reason: collision with root package name */
    public static final List f23223a;
    public static final List a0;
    public static final List b;
    public static final List b0;
    public static final List c;
    public static final List c0;
    public static final List d;
    public static final List d0;
    public static final List e;
    public static final List e0;
    public static final List f;
    public static final List f0;
    public static final List g;
    public static final List g0;
    public static final List h;
    public static final List h0;
    public static final List i;
    public static final List i0;
    public static final List j;
    public static final List j0;
    public static final List k;
    public static final List k0;
    public static final List l;
    public static final List l0;
    public static final List m;
    public static final List m0;
    public static final List n;
    public static final List n0;
    public static final List o;
    public static final List o0;
    public static final List p;
    public static final List p0;
    public static final List q;
    public static final List q0;
    public static final List r;
    public static final List r0;
    public static final List s;
    public static final List s0;
    public static final List t;
    public static final List t0;
    public static final List u;
    public static final List u0;
    public static final List v;
    public static final List v0;
    public static final List w;
    public static final List w0;
    public static final List x;
    public static final List x0;
    public static final List y;
    public static final List y0;
    public static final List z;
    public static final List z0;

    static {
        List listR = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        f23223a = listR;
        CompiledField compiledFieldC = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ButtonStyle.e.getClass();
        List listR2 = CollectionsKt.R(compiledFieldC, new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        b = listR2;
        CompiledField compiledFieldC2 = new CompiledField.Builder("fulfilmentWindowStateTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType = TextWithAlt.f11967a;
        CompiledField.Builder builder = new CompiledField.Builder("fulfilmentWindowStateSubtitle", TextWithAlt.Companion.a());
        builder.e(listR);
        CompiledField compiledFieldC3 = builder.c();
        ObjectType objectType2 = Button.f11080a;
        CompiledField.Builder builder2 = new CompiledField.Builder("fulfilmentWindowStateButton", CompiledGraphQL.b(Button.Companion.a()));
        builder2.e(listR2);
        List listR3 = CollectionsKt.R(compiledFieldC2, compiledFieldC3, builder2.c());
        c = listR3;
        List listR4 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        d = listR4;
        CompiledField.Builder builder3 = new CompiledField.Builder("_", GraphQLBoolean.Companion.a());
        builder3.a("_excluded");
        List listQ = CollectionsKt.Q(builder3.c());
        e = listQ;
        CompiledField.Builder builder4 = new CompiledField.Builder("button", CompiledGraphQL.b(Button.Companion.a()));
        builder4.e(listR4);
        CompiledField compiledFieldC4 = builder4.c();
        CompiledField.Builder builder5 = new CompiledField.Builder("deliveryNowBanner", HomeDeliveryNowBanner.f11455a);
        builder5.e(listQ);
        CompiledField compiledFieldC5 = builder5.c();
        HomeFulfilmentWindowContainerOrientation.e.getClass();
        List listR5 = CollectionsKt.R(compiledFieldC4, compiledFieldC5, new CompiledField.Builder("orientation", CompiledGraphQL.b(HomeFulfilmentWindowContainerOrientation.f)).c());
        f = listR5;
        List listR6 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        g = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        h = listR7;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        i = listQ2;
        HomeFulfilmentWindowTileStyle.e.getClass();
        CompiledField compiledFieldC6 = new CompiledField.Builder("style", CompiledGraphQL.b(HomeFulfilmentWindowTileStyle.f)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("iconUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC8 = new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder6 = new CompiledField.Builder("title", CompiledGraphQL.b(TextWithAlt.Companion.a()));
        builder6.e(listR6);
        CompiledField compiledFieldC9 = builder6.c();
        CompiledField.Builder builder7 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, TextWithAlt.Companion.a());
        builder7.e(listR7);
        CompiledField compiledFieldC10 = builder7.c();
        CompiledField.Builder builder8 = new CompiledField.Builder("analytics", CompiledGraphQL.b(HomeFulfilmentWindowTileAnalytics.f11462a));
        builder8.e(listQ2);
        List listR8 = CollectionsKt.R(compiledFieldC6, compiledFieldC7, compiledFieldC8, compiledFieldC9, compiledFieldC10, builder8.c());
        j = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        k = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        l = listR10;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        m = listQ3;
        CompiledField compiledFieldC11 = new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder9 = new CompiledField.Builder("title", TextWithAlt.Companion.a());
        builder9.e(listR9);
        CompiledField compiledFieldC12 = builder9.c();
        CompiledField.Builder builder10 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, TextWithAlt.Companion.a());
        builder10.e(listR10);
        CompiledField compiledFieldC13 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("analytics", CompiledGraphQL.b(HomeOnlineShoppingModeVariantTileAnalytics.f11469a));
        builder11.e(listQ3);
        List listR11 = CollectionsKt.R(compiledFieldC11, compiledFieldC12, compiledFieldC13, builder11.c());
        n = listR11;
        CompiledField.Builder builder12 = new CompiledField.Builder("_", GraphQLBoolean.Companion.a());
        builder12.a("_excluded");
        List listQ4 = CollectionsKt.Q(builder12.c());
        o = listQ4;
        DownloadableAssetType.e.getClass();
        CompiledField compiledFieldC14 = new CompiledField.Builder("assetType", CompiledGraphQL.b(DownloadableAssetType.f)).c();
        CompiledField compiledFieldC15 = new CompiledField.Builder("assetUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("assetWidth", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("assetHeight", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        DownloadableAssetFit.e.getClass();
        List listR12 = CollectionsKt.R(compiledFieldC14, compiledFieldC15, compiledFieldC16, compiledFieldC17, new CompiledField.Builder("fit", DownloadableAssetFit.f).c(), new CompiledField.Builder("altText", GraphQLString.Companion.a()).c());
        p = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        q = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        r = listR14;
        CompiledField compiledFieldC18 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC19 = new CompiledField.Builder("bottomSheetTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC20 = new CompiledField.Builder("bottomSheetBody", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC21 = new CompiledField.Builder("showOnceOnly", GraphQLBoolean.Companion.a()).c();
        CompiledField.Builder builder13 = new CompiledField.Builder("bannerAsset", DownloadableAsset.f11349a);
        builder13.e(listR12);
        CompiledField compiledFieldC22 = builder13.c();
        ObjectType objectType3 = ContentCta.f11282a;
        CompiledField.Builder builder14 = new CompiledField.Builder("primaryCta", ContentCta.Companion.a());
        builder14.e(listR13);
        CompiledField compiledFieldC23 = builder14.c();
        CompiledField.Builder builder15 = new CompiledField.Builder("secondaryCta", ContentCta.Companion.a());
        builder15.e(listR14);
        List listR15 = CollectionsKt.R(compiledFieldC18, compiledFieldC19, compiledFieldC20, compiledFieldC21, compiledFieldC22, compiledFieldC23, builder15.c());
        s = listR15;
        CompiledField.Builder builder16 = new CompiledField.Builder("_", GraphQLBoolean.Companion.a());
        builder16.a("_excluded");
        List listQ5 = CollectionsKt.Q(builder16.c());
        t = listQ5;
        CompiledField compiledFieldC24 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("HomeDeliveryNowBottomBanner", CollectionsKt.Q("HomeDeliveryNowBottomBanner"));
        builder17.b(listR15);
        CompiledFragment compiledFragmentA = builder17.a();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("HomeDeliveryNowBanner", CollectionsKt.Q("HomeDeliveryNowBanner"));
        builder18.b(listQ5);
        List listR16 = CollectionsKt.R(compiledFieldC24, compiledFragmentA, builder18.a());
        u = listR16;
        List listR17 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        v = listR17;
        List listR18 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        w = listR18;
        ObjectType objectType4 = TextWithLink.f11968a;
        CompiledField.Builder builder19 = new CompiledField.Builder("storeName", objectType4);
        builder19.e(listR17);
        CompiledField compiledFieldC25 = builder19.c();
        CompiledField.Builder builder20 = new CompiledField.Builder("storeTime", objectType4);
        builder20.e(listR18);
        List listR19 = CollectionsKt.R(compiledFieldC25, builder20.c(), new CompiledField.Builder("isLocationMapped", GraphQLBoolean.Companion.a()).c());
        x = listR19;
        CompiledField.Builder builder21 = new CompiledField.Builder("fulfilmentWindowTile", HomeFulfilmentWindowTile.f11461a);
        builder21.e(listR8);
        CompiledField compiledFieldC26 = builder21.c();
        CompiledField.Builder builder22 = new CompiledField.Builder("onlineShoppingModeVariantTile", HomeOnlineShoppingModeVariantTile.f11468a);
        builder22.e(listR11);
        CompiledField compiledFieldC27 = builder22.c();
        CompiledField.Builder builder23 = new CompiledField.Builder("divider", DividerCard.f11348a);
        builder23.e(listQ4);
        CompiledField compiledFieldC28 = builder23.c();
        CompiledField.Builder builder24 = new CompiledField.Builder("deliveryNowBanner", HomeDeliveryNowBannerUnion.f11456a);
        builder24.e(listR16);
        CompiledField compiledFieldC29 = builder24.c();
        CompiledField.Builder builder25 = new CompiledField.Builder("inStoreDetailsCard", InStoreDetailsCard.f11490a);
        builder25.e(listR19);
        List listR20 = CollectionsKt.R(compiledFieldC26, compiledFieldC27, compiledFieldC28, compiledFieldC29, builder25.c());
        y = listR20;
        CompiledField compiledFieldC30 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("HomeFulfilmentWindowBanner", CollectionsKt.Q("HomeFulfilmentWindowBanner"));
        builder26.b(listR3);
        CompiledFragment compiledFragmentA2 = builder26.a();
        CompiledFragment.Builder builder27 = new CompiledFragment.Builder("HomeFulfilmentWindowContainer", CollectionsKt.Q("HomeFulfilmentWindowContainer"));
        builder27.b(listR5);
        CompiledFragment compiledFragmentA3 = builder27.a();
        CompiledFragment.Builder builder28 = new CompiledFragment.Builder("HomeModeSelectorContainer", CollectionsKt.Q("HomeModeSelectorContainer"));
        builder28.b(listR20);
        List listR21 = CollectionsKt.R(compiledFieldC30, compiledFragmentA2, compiledFragmentA3, builder28.a());
        z = listR21;
        List listR22 = CollectionsKt.R(new CompiledField.Builder("tnta", GraphQLString.Companion.a()).c(), new CompiledField.Builder("pe", GraphQLString.Companion.a()).c(), new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c());
        A = listR22;
        List listR23 = CollectionsKt.R(new CompiledField.Builder("marketplaceOrderCount", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder("woolworthsOrderCount", CompiledGraphQL.b(GraphQLInt.Companion.a())).c());
        B = listR23;
        CompiledField compiledFieldC31 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder29 = new CompiledFragment.Builder("AdobeTargetAnalytics", CollectionsKt.Q("AdobeTargetAnalytics"));
        builder29.b(listR22);
        CompiledFragment compiledFragmentA4 = builder29.a();
        CompiledFragment.Builder builder30 = new CompiledFragment.Builder("OrderAnalytics", CollectionsKt.Q("OrderAnalytics"));
        builder30.b(listR23);
        List listR24 = CollectionsKt.R(compiledFieldC31, compiledFragmentA4, builder30.a());
        C = listR24;
        List listR25 = CollectionsKt.R(new CompiledField.Builder("status", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("expressDeliveryStoreId", GraphQLInt.Companion.a()).c());
        D = listR25;
        List listR26 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        E = listR26;
        CompiledField compiledFieldC32 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType5 = Analytics.f11028a;
        CompiledField.Builder builder31 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder31.e(listR26);
        CompiledField compiledFieldC33 = builder31.c();
        ActionType.e.getClass();
        List listR27 = CollectionsKt.R(compiledFieldC32, compiledFieldC33, new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c());
        F = listR27;
        List listR28 = CollectionsKt.R(new CompiledField.Builder("key", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("value", GraphQLString.Companion.a()).c());
        G = listR28;
        CompiledField compiledFieldC34 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment compiledFragmentD = d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics")));
        CompiledField.Builder builder32 = new CompiledField.Builder("extraContent", CompiledGraphQL.a(CompiledGraphQL.b(AnalyticsExtraContent.f11029a)));
        builder32.e(listR28);
        List listR29 = CollectionsKt.R(compiledFieldC34, compiledFragmentD, builder32.c());
        H = listR29;
        List listR30 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        I = listR30;
        List listQ6 = CollectionsKt.Q(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        J = listQ6;
        List listR31 = CollectionsKt.R(new CompiledField.Builder("code", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        K = listR31;
        CompiledField compiledFieldC35 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder33 = new CompiledFragment.Builder("HeroBannerBodyText", CollectionsKt.Q("HeroBannerBodyText"));
        builder33.b(listQ6);
        CompiledFragment compiledFragmentA5 = builder33.a();
        CompiledFragment.Builder builder34 = new CompiledFragment.Builder("HeroBannerPromoBody", CollectionsKt.Q("HeroBannerPromoBody"));
        builder34.b(listR31);
        List listR32 = CollectionsKt.R(compiledFieldC35, compiledFragmentA5, builder34.a());
        L = listR32;
        List listR33 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        M = listR33;
        List listR34 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        N = listR34;
        List listR35 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        O = listR35;
        List listR36 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        P = listR36;
        CompiledField compiledFieldC36 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC37 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC38 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder35 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder35.e(listR36);
        List listR37 = CollectionsKt.R(compiledFieldC36, compiledFieldC37, compiledFieldC38, builder35.c());
        Q = listR37;
        CompiledField compiledFieldC39 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType6 = Action.f10997a;
        CompiledField.Builder builder36 = new CompiledField.Builder(UrlHandler.ACTION, Action.Companion.a());
        builder36.a("heroBannerTermsAndConditionAction");
        builder36.e(listR37);
        List listR38 = CollectionsKt.R(compiledFieldC39, builder36.c());
        R = listR38;
        CompiledField compiledFieldC40 = new CompiledField.Builder("heroBannerId", CompiledGraphQL.b(GraphQLID.Companion.a())).c();
        CompiledField.Builder builder37 = new CompiledField.Builder("heroBannerAction", CompiledGraphQL.b(Action.Companion.a()));
        builder37.e(listR27);
        CompiledField compiledFieldC41 = builder37.c();
        CompiledField.Builder builder38 = new CompiledField.Builder("heroBannerAnalytics", CompiledGraphQL.b(Analytics.Companion.a()));
        builder38.e(listR29);
        CompiledField compiledFieldC42 = builder38.c();
        CompiledField.Builder builder39 = new CompiledField.Builder("heroBannerImpressionAnalytics", CompiledGraphQL.b(Analytics.Companion.a()));
        builder39.e(listR30);
        CompiledField compiledFieldC43 = builder39.c();
        CompiledField compiledFieldC44 = new CompiledField.Builder("heroBannerBackgroundColour", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC45 = new CompiledField.Builder("heroBannerTextColour", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder40 = new CompiledField.Builder("heroBannerBody", HeroBannerBody.f11451a);
        builder40.e(listR32);
        CompiledField compiledFieldC46 = builder40.c();
        ObjectType objectType7 = ImageWithAlt.f11487a;
        CompiledField.Builder builder41 = new CompiledField.Builder("heroBannerBrandsLogo", ImageWithAlt.Companion.a());
        builder41.e(listR33);
        CompiledField compiledFieldC47 = builder41.c();
        CompiledField.Builder builder42 = new CompiledField.Builder("heroBannerGraphics", CompiledGraphQL.a(CompiledGraphQL.b(ImageWithAlt.Companion.a())));
        builder42.e(listR34);
        CompiledField compiledFieldC48 = builder42.c();
        CompiledField.Builder builder43 = new CompiledField.Builder("heroBannerImages", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(ImageWithAlt.Companion.a()))));
        builder43.e(listR35);
        CompiledField compiledFieldC49 = builder43.c();
        CompiledField.Builder builder44 = new CompiledField.Builder("heroBannerTermsAndConditions", HeroBannerTermsAndConditions.f11454a);
        builder44.e(listR38);
        CompiledField compiledFieldC50 = builder44.c();
        CompiledField compiledFieldC51 = new CompiledField.Builder("heroBannerTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        HeroBannerTitleSize.e.getClass();
        List listR39 = CollectionsKt.R(compiledFieldC40, compiledFieldC41, compiledFieldC42, compiledFieldC43, compiledFieldC44, compiledFieldC45, compiledFieldC46, compiledFieldC47, compiledFieldC48, compiledFieldC49, compiledFieldC50, compiledFieldC51, new CompiledField.Builder("heroBannerTitleSize", CompiledGraphQL.b(HeroBannerTitleSize.f)).c());
        S = listR39;
        CompiledField compiledFieldC52 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder45 = new CompiledFragment.Builder("HeroBanner", CollectionsKt.Q("HeroBanner"));
        builder45.b(listR39);
        List listR40 = CollectionsKt.R(compiledFieldC52, builder45.a());
        T = listR40;
        CompiledField.Builder builder46 = new CompiledField.Builder("carouselItems", d.j(CarouselItem.f11098a));
        builder46.e(listR40);
        List listQ7 = CollectionsKt.Q(builder46.c());
        U = listQ7;
        List listQ8 = CollectionsKt.Q(new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c());
        V = listQ8;
        AlertIndicatorType.e.getClass();
        EnumType enumType = AlertIndicatorType.f;
        List listR41 = CollectionsKt.R(new CompiledField.Builder("indicatorType", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        W = listR41;
        List listR42 = CollectionsKt.R(new CompiledField.Builder("indicatorType", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        X = listR42;
        CompiledField compiledFieldC53 = new CompiledField.Builder("edrNumber", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC54 = new CompiledField.Builder("offersTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC55 = new CompiledField.Builder("currentBalance", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC56 = new CompiledField.Builder("goalBalance", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC57 = new CompiledField.Builder("actionUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC58 = new CompiledField.Builder("pointsDescriptionFormat", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC59 = new CompiledField.Builder("pointsDescriptionReplacements", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        CompiledField compiledFieldC60 = new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType8 = AlertIndicator.f11016a;
        CompiledField.Builder builder47 = new CompiledField.Builder("offersAlertIndicator", objectType8);
        builder47.e(listR41);
        CompiledField compiledFieldC61 = builder47.c();
        CompiledField.Builder builder48 = new CompiledField.Builder("pointsAlertIndicator", objectType8);
        builder48.e(listR42);
        List listR43 = CollectionsKt.R(compiledFieldC53, compiledFieldC54, compiledFieldC55, compiledFieldC56, compiledFieldC57, compiledFieldC58, compiledFieldC59, compiledFieldC60, compiledFieldC61, builder48.c(), new CompiledField.Builder("rewardsState", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        Y = listR43;
        List listR44 = CollectionsKt.R(new CompiledField.Builder("addRewardsCardTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("addRewardsCardSubtitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        Z = listR44;
        CompiledField compiledFieldC62 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC63 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC64 = new CompiledField.Builder("deeplink", GraphQLString.Companion.a()).c();
        BroadcastBannerType.e.getClass();
        List listR45 = CollectionsKt.R(compiledFieldC62, compiledFieldC63, compiledFieldC64, new CompiledField.Builder("type", CompiledGraphQL.b(BroadcastBannerType.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("actionLabel", GraphQLString.Companion.a()).c(), new CompiledField.Builder("analyticsLabel", GraphQLString.Companion.a()).c(), new CompiledField.Builder("dismissible", GraphQLBoolean.Companion.a()).c(), new CompiledField.Builder("bannerId", GraphQLString.Companion.a()).c());
        a0 = listR45;
        CompiledField.Builder builder49 = new CompiledField.Builder("_", GraphQLBoolean.Companion.a());
        builder49.a("_excluded");
        List listQ9 = CollectionsKt.Q(builder49.c());
        b0 = listQ9;
        CompiledField compiledFieldC65 = new CompiledField.Builder("url", GraphQLString.Companion.a()).c();
        InsetBannerActionType.e.getClass();
        CompiledField compiledFieldC66 = new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.Companion.a())).c();
        InsetBannerActionPlacement.e.getClass();
        List listR46 = CollectionsKt.R(compiledFieldC65, compiledFieldC66, new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        c0 = listR46;
        CompiledField compiledFieldC67 = new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c();
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC68 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField compiledFieldC69 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder50 = new CompiledField.Builder("title", GraphQLString.Companion.a());
        builder50.a("bannerTitle");
        CompiledField compiledFieldC70 = builder50.c();
        CompiledField compiledFieldC71 = new CompiledField.Builder("iconUrl", GraphQLString.Companion.a()).c();
        ObjectType objectType9 = InsetBannerAction.f11510a;
        CompiledField.Builder builder51 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.Companion.a());
        builder51.e(listR46);
        List listR47 = CollectionsKt.R(compiledFieldC67, compiledFieldC68, compiledFieldC69, compiledFieldC70, compiledFieldC71, builder51.c());
        d0 = listR47;
        CompiledField compiledFieldC72 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder52 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a()));
        builder52.a("catalogueCardSubtitle");
        List listR48 = CollectionsKt.R(compiledFieldC72, builder52.c(), new CompiledField.Builder("imageLeft", GraphQLString.Companion.a()).c(), new CompiledField.Builder("imageRight", GraphQLString.Companion.a()).c(), new CompiledField.Builder("imageBackground", GraphQLString.Companion.a()).c());
        e0 = listR48;
        List listR49 = CollectionsKt.R(new CompiledField.Builder("marketplaceCardBannerImage", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("marketplaceCardBannerAltText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        f0 = listR49;
        List listR50 = CollectionsKt.R(new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        g0 = listR50;
        List listR51 = CollectionsKt.R(new CompiledField.Builder("source", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("playCount", CompiledGraphQL.b(GraphQLInt.Companion.a())).c());
        h0 = listR51;
        CompiledField compiledFieldC73 = new CompiledField.Builder("linkCardImage", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC74 = new CompiledField.Builder("linkCardSubtitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC75 = new CompiledField.Builder("linkCardTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder53 = new CompiledField.Builder("linkCardAction", CompiledGraphQL.b(Action.Companion.a()));
        builder53.e(listR50);
        List listR52 = CollectionsKt.R(compiledFieldC73, compiledFieldC74, compiledFieldC75, builder53.c(), a.e("includeCampaignAnimation", false, new CompiledField.Builder("linkCardAnimation", OverlayAnimation.f11679a), listR51));
        i0 = listR52;
        CompiledField compiledFieldC76 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder54 = new CompiledFragment.Builder("QuickLinkCard", CollectionsKt.Q("QuickLinkCard"));
        builder54.b(listR52);
        List listR53 = CollectionsKt.R(compiledFieldC76, builder54.a());
        j0 = listR53;
        ObjectType objectType10 = QuickLinkCard.f11810a;
        CompiledField.Builder builder55 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(QuickLinkCard.Companion.a()))));
        builder55.e(listR53);
        List listQ10 = CollectionsKt.Q(builder55.c());
        k0 = listQ10;
        List listR54 = CollectionsKt.R(new CompiledField.Builder("myListTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("myListSubtitle", GraphQLString.Companion.a()).c(), new CompiledField.Builder("myListActionTitle", GraphQLString.Companion.a()).c(), new CompiledField.Builder("myListDeepLink", GraphQLString.Companion.a()).c());
        l0 = listR54;
        CompiledField compiledFieldC77 = new CompiledField.Builder("image", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC78 = new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CardHeight.e.getClass();
        List listR55 = CollectionsKt.R(compiledFieldC77, compiledFieldC78, new CompiledField.Builder("cardHeight", CompiledGraphQL.b(CardHeight.Companion.a())).c(), new CompiledField.Builder("link", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("analytics", TealiumAnalytics.Companion.a()).c(), new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c());
        m0 = listR55;
        CompiledField compiledFieldC79 = new CompiledField.Builder(OutOfContextTestingActivity.AD_UNIT_KEY, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC80 = new CompiledField.Builder("nativeCustomTemplateId", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC81 = new CompiledField.Builder("targeting", GoogleAdCustomTargeting.Companion.a()).c();
        AdBannerNativeSize.e.getClass();
        List listR56 = CollectionsKt.R(compiledFieldC79, compiledFieldC80, compiledFieldC81, new CompiledField.Builder("height", CompiledGraphQL.b(AdBannerNativeSize.Companion.a())).c(), new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c());
        n0 = listR56;
        CompiledField compiledFieldC82 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder56 = new CompiledFragment.Builder("RecipeSummaryCard", CollectionsKt.Q("RecipeSummaryCard"));
        builder56.b(RecipeSummaryCardFragmentSelections.d);
        List listR57 = CollectionsKt.R(compiledFieldC82, builder56.a());
        o0 = listR57;
        List listQ11 = CollectionsKt.Q(new CompiledField.Builder(k.a.g, CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c());
        p0 = listQ11;
        List listQ12 = CollectionsKt.Q(new CompiledField.Builder("source", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        q0 = listQ12;
        CompiledField compiledFieldC83 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder57 = new CompiledFragment.Builder("RecipeTagList", CollectionsKt.Q("RecipeTagList"));
        builder57.b(listQ11);
        CompiledFragment compiledFragmentA6 = builder57.a();
        CompiledFragment.Builder builder58 = new CompiledFragment.Builder("RecipeSource", CollectionsKt.Q("RecipeSource"));
        builder58.b(listQ12);
        List listR58 = CollectionsKt.R(compiledFieldC83, compiledFragmentA6, builder58.a());
        r0 = listR58;
        CompiledField.Builder builder59 = new CompiledField.Builder("actionMetadata", d.j(ActionMetaData.f10998a));
        builder59.e(listR58);
        List listQ13 = CollectionsKt.Q(builder59.c());
        s0 = listQ13;
        CompiledField compiledFieldC84 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder60 = new CompiledFragment.Builder("RecipeSummaryCard", CollectionsKt.Q("RecipeSummaryCard"));
        builder60.b(listR57);
        CompiledFragment compiledFragmentA7 = builder60.a();
        CompiledFragment.Builder builder61 = new CompiledFragment.Builder("RecipeMoreCard", CollectionsKt.Q("RecipeMoreCard"));
        builder61.b(listQ13);
        List listR59 = CollectionsKt.R(compiledFieldC84, compiledFragmentA7, builder61.a());
        t0 = listR59;
        CompiledField compiledFieldC85 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC86 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC87 = new CompiledField.Builder("deepLink", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC88 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        UnionType unionType = HorizontalListItem.f11475a;
        CompiledField.Builder builder62 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder62.e(listR59);
        List listR60 = CollectionsKt.R(compiledFieldC85, compiledFieldC86, compiledFieldC87, compiledFieldC88, builder62.c());
        u0 = listR60;
        List listR61 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("buttonLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        v0 = listR61;
        CompiledField compiledFieldC89 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC90 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        OrderStatus.e.getClass();
        CompiledField compiledFieldC91 = new CompiledField.Builder("status", CompiledGraphQL.b(OrderStatus.f)).c();
        CompiledField compiledFieldC92 = new CompiledField.Builder("orderCardId", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC93 = new CompiledField.Builder("total", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC94 = new CompiledField.Builder("timeLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC95 = new CompiledField.Builder("timeValue", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC96 = new CompiledField.Builder("date", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder63 = new CompiledField.Builder("fulfilmentStatusBanner", FulfilmentStatusBanner.f11412a);
        builder63.e(listR61);
        List listR62 = CollectionsKt.R(compiledFieldC89, compiledFieldC90, compiledFieldC91, compiledFieldC92, compiledFieldC93, compiledFieldC94, compiledFieldC95, compiledFieldC96, builder63.c());
        w0 = listR62;
        CompiledField compiledFieldC97 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder64 = new CompiledFragment.Builder("OrderCard", CollectionsKt.Q("OrderCard"));
        builder64.b(listR62);
        List listR63 = CollectionsKt.R(compiledFieldC97, builder64.a());
        x0 = listR63;
        CompiledField compiledFieldC98 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC99 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC100 = new CompiledField.Builder("deepLink", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC101 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder65 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder65.e(listR63);
        List listR64 = CollectionsKt.R(compiledFieldC98, compiledFieldC99, compiledFieldC100, compiledFieldC101, builder65.c());
        y0 = listR64;
        List listR65 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        z0 = listR65;
        CompiledField compiledFieldC102 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder66 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder66.b(listR65);
        List listR66 = CollectionsKt.R(compiledFieldC102, builder66.a());
        A0 = listR66;
        CompiledField compiledFieldC103 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC104 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC105 = new CompiledField.Builder("deepLink", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC106 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder67 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder67.e(listR66);
        List listR67 = CollectionsKt.R(compiledFieldC103, compiledFieldC104, compiledFieldC105, compiledFieldC106, builder67.c());
        B0 = listR67;
        List listR68 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        C0 = listR68;
        CompiledField compiledFieldC107 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder68 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder68.b(listR68);
        List listR69 = CollectionsKt.R(compiledFieldC107, builder68.a());
        D0 = listR69;
        CompiledField compiledFieldC108 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC109 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC110 = new CompiledField.Builder("deepLink", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC111 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC112 = new CompiledField.Builder("tigerOfferIds", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        CompiledField.Builder builder69 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder69.e(listR69);
        List listR70 = CollectionsKt.R(compiledFieldC108, compiledFieldC109, compiledFieldC110, compiledFieldC111, compiledFieldC112, builder69.c());
        E0 = listR70;
        CompiledField compiledFieldC113 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder70 = new CompiledFragment.Builder("Carousel", CollectionsKt.Q("Carousel"));
        builder70.b(listQ7);
        CompiledFragment compiledFragmentA8 = builder70.a();
        CompiledFragment.Builder builder71 = new CompiledFragment.Builder("RegistrationCard", CollectionsKt.Q("RegistrationCard"));
        builder71.b(listQ8);
        CompiledFragment compiledFragmentA9 = builder71.a();
        CompiledFragment.Builder builder72 = new CompiledFragment.Builder("RewardsBalanceCard", CollectionsKt.Q("RewardsBalanceCard"));
        builder72.b(listR43);
        CompiledFragment compiledFragmentA10 = builder72.a();
        CompiledFragment.Builder builder73 = new CompiledFragment.Builder("AddRewardsCard", CollectionsKt.Q("AddRewardsCard"));
        builder73.b(listR44);
        CompiledFragment compiledFragmentA11 = builder73.a();
        CompiledFragment compiledFragmentI = d.i("includeBroadcastBanner", false, new CompiledFragment.Builder("BroadcastBanner", CollectionsKt.Q("BroadcastBanner")), listR45);
        CompiledFragment.Builder builder74 = new CompiledFragment.Builder("DividerCard", CollectionsKt.Q("DividerCard"));
        builder74.b(listQ9);
        CompiledFragment compiledFragmentA12 = builder74.a();
        CompiledFragment.Builder builder75 = new CompiledFragment.Builder("InsetBanner", CollectionsKt.Q("InsetBanner"));
        builder75.b(listR47);
        CompiledFragment compiledFragmentA13 = builder75.a();
        CompiledFragment compiledFragmentI2 = d.i("includeCatalogueCard", false, new CompiledFragment.Builder("CatalogueCard", CollectionsKt.Q("CatalogueCard")), listR48);
        CompiledFragment.Builder builder76 = new CompiledFragment.Builder("MarketplaceCard", CollectionsKt.Q("MarketplaceCard"));
        builder76.b(listR49);
        CompiledFragment compiledFragmentA14 = builder76.a();
        CompiledFragment.Builder builder77 = new CompiledFragment.Builder("QuickLinkHorizontalList", CollectionsKt.Q("QuickLinkHorizontalList"));
        builder77.b(listQ10);
        CompiledFragment compiledFragmentA15 = builder77.a();
        CompiledFragment.Builder builder78 = new CompiledFragment.Builder("MyShoppingLists", CollectionsKt.Q("MyShoppingLists"));
        builder78.b(listR54);
        CompiledFragment compiledFragmentA16 = builder78.a();
        CompiledFragment.Builder builder79 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder79.b(listR55);
        CompiledFragment compiledFragmentA17 = builder79.a();
        CompiledFragment.Builder builder80 = new CompiledFragment.Builder("GoogleAdBannerCard", CollectionsKt.Q("GoogleAdBannerCard"));
        builder80.b(listR56);
        CompiledFragment compiledFragmentA18 = builder80.a();
        CompiledFragment.Builder builder81 = new CompiledFragment.Builder("RecipeHorizontalList", CollectionsKt.Q("RecipeHorizontalList"));
        builder81.b(listR60);
        CompiledFragment compiledFragmentA19 = builder81.a();
        CompiledFragment.Builder builder82 = new CompiledFragment.Builder("OrderHorizontalList", CollectionsKt.Q("OrderHorizontalList"));
        builder82.b(listR64);
        CompiledFragment compiledFragmentA20 = builder82.a();
        CompiledFragment.Builder builder83 = new CompiledFragment.Builder("ProductHorizontalList", CollectionsKt.Q("ProductHorizontalList"));
        builder83.b(listR67);
        CompiledFragment compiledFragmentA21 = builder83.a();
        CompiledFragment.Builder builder84 = new CompiledFragment.Builder("BoosterHorizontalList", CollectionsKt.Q("BoosterHorizontalList"));
        builder84.b(listR70);
        List listR71 = CollectionsKt.R(compiledFieldC113, compiledFragmentA8, compiledFragmentA9, compiledFragmentA10, compiledFragmentA11, compiledFragmentI, compiledFragmentA12, compiledFragmentA13, compiledFragmentI2, compiledFragmentA14, compiledFragmentA15, compiledFragmentA16, compiledFragmentA17, compiledFragmentA18, compiledFragmentA19, compiledFragmentA20, compiledFragmentA21, builder84.a());
        F0 = listR71;
        List listQ14 = CollectionsKt.Q(new CompiledField.Builder("count", CompiledGraphQL.b(GraphQLInt.Companion.a())).c());
        G0 = listQ14;
        CompiledField.Builder builder85 = new CompiledField.Builder("headerItems", CompiledGraphQL.b(CompiledGraphQL.a(HomeHeaderItems.f11463a)));
        builder85.e(listR21);
        CompiledField compiledFieldC114 = builder85.c();
        UnionType unionType2 = HomeListAnalytics.f11465a;
        CompiledField.Builder builder86 = new CompiledField.Builder("analytics", CompiledGraphQL.b(CompiledGraphQL.a(HomeListAnalytics.Companion.a())));
        builder86.e(listR24);
        CompiledField compiledFieldC115 = builder86.c();
        CompiledField.Builder builder87 = new CompiledField.Builder("deliveryNow", HomeListDeliveryNow.f11466a);
        builder87.e(listR25);
        CompiledField compiledFieldC116 = builder87.c();
        UnionType unionType3 = HomeFeed.f11458a;
        CompiledField.Builder builder88 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(HomeFeed.Companion.a())));
        builder88.e(listR71);
        CompiledField compiledFieldC117 = builder88.c();
        CompiledField.Builder builder89 = new CompiledField.Builder("unreadChatbotMsg", UnreadChatbotMsg.f11990a);
        builder89.e(listQ14);
        List listR72 = CollectionsKt.R(compiledFieldC114, compiledFieldC115, compiledFieldC116, compiledFieldC117, builder89.c());
        H0 = listR72;
        CompiledField.Builder builder90 = new CompiledField.Builder("home", HomeList.f11464a);
        new CompiledArgument.Builder(Query.r);
        CompiledArgument compiledArgumentA = CompiledArgument.Builder.a();
        new CompiledArgument.Builder(Query.Companion.b());
        CompiledArgument compiledArgumentA2 = CompiledArgument.Builder.a();
        new CompiledArgument.Builder(Query.Companion.c());
        CompiledArgument compiledArgumentA3 = CompiledArgument.Builder.a();
        new CompiledArgument.Builder(Query.u);
        CompiledArgument compiledArgumentA4 = CompiledArgument.Builder.a();
        new CompiledArgument.Builder(Query.t);
        CompiledArgument compiledArgumentA5 = CompiledArgument.Builder.a();
        new CompiledArgument.Builder(Query.s);
        CompiledArgument compiledArgumentA6 = CompiledArgument.Builder.a();
        new CompiledArgument.Builder(Query.v);
        builder90.b(CollectionsKt.R(compiledArgumentA, compiledArgumentA2, compiledArgumentA3, compiledArgumentA4, compiledArgumentA5, compiledArgumentA6, CompiledArgument.Builder.a()));
        builder90.e(listR72);
        I0 = CollectionsKt.Q(builder90.c());
    }
}
