package com.woolworths.feature.shop.wpay.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.sdui.shop.fragment.selections.AnalyticsFieldsSelections;
import au.com.woolworths.shop.graphql.type.AddPayPalAlert;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.GiftCardItem;
import au.com.woolworths.shop.graphql.type.GiftCardSection;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.InsetBanner;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.PaymentInstrumentTotalDetails;
import au.com.woolworths.shop.graphql.type.PaymentInstrumentsResponse;
import au.com.woolworths.shop.graphql.type.PaymentMethodItem;
import au.com.woolworths.shop.graphql.type.PaymentMethodSection;
import au.com.woolworths.shop.graphql.type.PlaceOrderButton;
import au.com.woolworths.shop.graphql.type.Query;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/feature/shop/wpay/selections/PaymentInstrumentsQuerySelections;", "", "wpay_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class PaymentInstrumentsQuerySelections {
    public static final List A;
    public static final List B;
    public static final List C;
    public static final List D;
    public static final List E;
    public static final List F;
    public static final List G;
    public static final List H;

    /* renamed from: a, reason: collision with root package name */
    public static final List f20474a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        List list = AnalyticsFieldsSelections.b;
        builder.b(list);
        List listR = CollectionsKt.R(compiledFieldC, builder.a());
        f20474a = listR;
        CompiledField compiledFieldC2 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType = Analytics.f11028a;
        CompiledField.Builder builder2 = new CompiledField.Builder("clickAnalytics", CompiledGraphQL.b(objectType));
        builder2.e = listR;
        List listR2 = CollectionsKt.R(compiledFieldC2, builder2.c());
        b = listR2;
        CompiledField compiledFieldC3 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder3.b(list);
        List listR3 = CollectionsKt.R(compiledFieldC3, builder3.a());
        c = listR3;
        InsetBannerDisplayType.e.getClass();
        EnumType enumType = InsetBannerDisplayType.f;
        CompiledField compiledFieldC4 = new CompiledField.Builder("displayType", CompiledGraphQL.b(enumType)).c();
        CompiledField compiledFieldC5 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder4 = new CompiledField.Builder("analytics", objectType);
        builder4.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC4, compiledFieldC5, builder4.c());
        d = listR4;
        CompiledField compiledFieldC6 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLBoolean.f11439a;
        CompiledField compiledFieldC8 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC9 = new CompiledField.Builder("amountTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC10 = new CompiledField.Builder("amountValue", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType3 = GraphQLInt.f11442a;
        CompiledField compiledFieldC11 = new CompiledField.Builder("amountRedeem", CompiledGraphQL.b(customScalarType3)).c();
        ObjectType objectType2 = InsetBanner.f11509a;
        CompiledField.Builder builder5 = new CompiledField.Builder("errorBanner", objectType2);
        builder5.e = listR4;
        List listR5 = CollectionsKt.R(compiledFieldC6, compiledFieldC7, compiledFieldC8, compiledFieldC9, compiledFieldC10, compiledFieldC11, builder5.c(), d.g("snackBarMessage", customScalarType));
        e = listR5;
        CompiledField compiledFieldC12 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder6.b(list);
        List listR6 = CollectionsKt.R(compiledFieldC12, builder6.a());
        f = listR6;
        CompiledField compiledFieldC13 = new CompiledField.Builder("displayType", CompiledGraphQL.b(enumType)).c();
        CompiledField compiledFieldC14 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder7 = new CompiledField.Builder("analytics", objectType);
        builder7.e = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC13, compiledFieldC14, builder7.c());
        g = listR7;
        CompiledField compiledFieldC15 = new CompiledField.Builder("number", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("pin", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC18 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC19 = new CompiledField.Builder("amountTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC20 = new CompiledField.Builder("amountValue", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC21 = new CompiledField.Builder("amountRedeem", CompiledGraphQL.b(customScalarType3)).c();
        CompiledField.Builder builder8 = new CompiledField.Builder("errorBanner", objectType2);
        builder8.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, compiledFieldC19, compiledFieldC20, compiledFieldC21, builder8.c(), d.g("snackBarMessage", customScalarType));
        h = listR8;
        CompiledField compiledFieldC22 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("AddGiftCard", CollectionsKt.Q("AddGiftCard"));
        builder9.d = listR2;
        CompiledFragment compiledFragmentA = builder9.a();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("LinkedGiftCard", CollectionsKt.Q("LinkedGiftCard"));
        builder10.d = listR5;
        CompiledFragment compiledFragmentA2 = builder10.a();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("UnlinkedGiftCard", CollectionsKt.Q("UnlinkedGiftCard"));
        builder11.d = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC22, compiledFragmentA, compiledFragmentA2, builder11.a());
        i = listR9;
        CompiledField compiledFieldC23 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder12 = new CompiledField.Builder("giftCards", d.j(GiftCardItem.f11433a));
        builder12.e = listR9;
        List listR10 = CollectionsKt.R(compiledFieldC23, builder12.c());
        j = listR10;
        CompiledField compiledFieldC24 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder13.b(list);
        List listR11 = CollectionsKt.R(compiledFieldC24, builder13.a());
        k = listR11;
        CompiledField compiledFieldC25 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder14 = new CompiledField.Builder("clickAnalytics", CompiledGraphQL.b(objectType));
        builder14.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC25, builder14.c());
        l = listR12;
        CompiledField compiledFieldC26 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder15.b(list);
        List listR13 = CollectionsKt.R(compiledFieldC26, builder15.a());
        m = listR13;
        CompiledField compiledFieldC27 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC28 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC29 = new CompiledField.Builder("primaryButtonTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC30 = new CompiledField.Builder("secondaryButtonTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder16 = new CompiledField.Builder("clickAnalytics", CompiledGraphQL.b(objectType));
        builder16.e = listR13;
        List listR14 = CollectionsKt.R(compiledFieldC27, compiledFieldC28, compiledFieldC29, compiledFieldC30, builder16.c());
        n = listR14;
        CompiledField compiledFieldC31 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC32 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder17 = new CompiledField.Builder("alert", CompiledGraphQL.b(AddPayPalAlert.f11009a));
        builder17.e = listR14;
        List listR15 = CollectionsKt.R(compiledFieldC31, compiledFieldC32, builder17.c());
        o = listR15;
        List listR16 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType), new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("isSelected", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("amountTitle", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amountValue", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amountToPay", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("cvvUrl", CompiledGraphQL.b(customScalarType)).c());
        p = listR16;
        List listR17 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType), new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("isSelected", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("amountTitle", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amountValue", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amountToPay", CompiledGraphQL.b(customScalarType3)).c());
        q = listR17;
        List listR18 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType), new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(customScalarType)).c());
        r = listR18;
        List listR19 = CollectionsKt.R(new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("isSelected", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("amountTitle", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amountValue", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amountToPay", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c());
        s = listR19;
        List listR20 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("isSelected", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("amountTitle", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amountValue", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amountToPay", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("supportedNetworks", a.e(customScalarType)).c());
        t = listR20;
        CompiledField compiledFieldC33 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("AddCreditCard", CollectionsKt.Q("AddCreditCard"));
        builder18.d = listR12;
        CompiledFragment compiledFragmentA3 = builder18.a();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("AddPayPal", CollectionsKt.Q("AddPayPal"));
        builder19.d = listR15;
        CompiledFragment compiledFragmentA4 = builder19.a();
        CompiledFragment.Builder builder20 = new CompiledFragment.Builder("LinkedCreditCard", CollectionsKt.Q("LinkedCreditCard"));
        builder20.d = listR16;
        CompiledFragment compiledFragmentA5 = builder20.a();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("UnlinkedCreditCard", CollectionsKt.Q("UnlinkedCreditCard"));
        builder21.d = listR17;
        CompiledFragment compiledFragmentA6 = builder21.a();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("ExpiredCreditCard", CollectionsKt.Q("ExpiredCreditCard"));
        builder22.d = listR18;
        CompiledFragment compiledFragmentA7 = builder22.a();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("LinkedPayPal", CollectionsKt.Q("LinkedPayPal"));
        builder23.d = listR19;
        CompiledFragment compiledFragmentA8 = builder23.a();
        CompiledFragment.Builder builder24 = new CompiledFragment.Builder("GooglePay", CollectionsKt.Q("GooglePay"));
        builder24.c = a.s("isGooglePayEnabled", false);
        builder24.d = listR20;
        List listR21 = CollectionsKt.R(compiledFieldC33, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, compiledFragmentA8, builder24.a());
        u = listR21;
        CompiledField compiledFieldC34 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder25 = new CompiledField.Builder("paymentMethods", d.j(PaymentMethodItem.f11691a));
        builder25.e = listR21;
        List listR22 = CollectionsKt.R(compiledFieldC34, builder25.c());
        v = listR22;
        CompiledField compiledFieldC35 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder26.b(list);
        List listR23 = CollectionsKt.R(compiledFieldC35, builder26.a());
        w = listR23;
        CompiledField compiledFieldC36 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC37 = new CompiledField.Builder("isEnabled", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder27 = new CompiledField.Builder("analytics", CompiledGraphQL.b(objectType));
        builder27.e = listR23;
        List listR24 = CollectionsKt.R(compiledFieldC36, compiledFieldC37, builder27.c());
        x = listR24;
        CompiledField compiledFieldC38 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder28 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder28.b(list);
        List listR25 = CollectionsKt.R(compiledFieldC38, builder28.a());
        y = listR25;
        CompiledField.Builder builder29 = new CompiledField.Builder("analytics", CompiledGraphQL.b(objectType));
        builder29.e = listR25;
        List listQ = CollectionsKt.Q(builder29.c());
        z = listQ;
        CompiledField compiledFieldC39 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder30 = new CompiledFragment.Builder("PlaceOrderButtonDefault", CollectionsKt.Q("PlaceOrderButtonDefault"));
        builder30.d = listR24;
        CompiledFragment compiledFragmentA9 = builder30.a();
        CompiledFragment.Builder builder31 = new CompiledFragment.Builder("PlaceOrderButtonGooglePay", CollectionsKt.Q("PlaceOrderButtonGooglePay"));
        builder31.d = listQ;
        List listR26 = CollectionsKt.R(compiledFieldC39, compiledFragmentA9, builder31.a());
        A = listR26;
        CompiledField compiledFieldC40 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC41 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder32 = new CompiledField.Builder("button", CompiledGraphQL.b(PlaceOrderButton.f11702a));
        builder32.e = listR26;
        CompiledField compiledFieldC42 = builder32.c();
        CompiledField.Builder builder33 = new CompiledField.Builder("panelMarkdown", customScalarType);
        builder33.c = a.s("includePanelMarkdown", false);
        List listR27 = CollectionsKt.R(compiledFieldC40, compiledFieldC41, compiledFieldC42, builder33.c());
        B = listR27;
        CompiledField compiledFieldC43 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder34 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder34.b(list);
        List listR28 = CollectionsKt.R(compiledFieldC43, builder34.a());
        C = listR28;
        CompiledField.Builder builder35 = new CompiledField.Builder("giftCardSection", CompiledGraphQL.b(GiftCardSection.f11434a));
        builder35.e = listR10;
        CompiledField compiledFieldC44 = builder35.c();
        CompiledField.Builder builder36 = new CompiledField.Builder("paymentMethodSection", CompiledGraphQL.b(PaymentMethodSection.f11692a));
        builder36.e = listR22;
        CompiledField compiledFieldC45 = builder36.c();
        CompiledField.Builder builder37 = new CompiledField.Builder("paymentInstrumentTotalDetails", CompiledGraphQL.b(PaymentInstrumentTotalDetails.f11688a));
        builder37.e = listR27;
        CompiledField compiledFieldC46 = builder37.c();
        CompiledField compiledFieldG = d.g("snackBarMessage", customScalarType);
        CompiledField compiledFieldG2 = d.g("footerMessageMd", customScalarType);
        CompiledField.Builder builder38 = new CompiledField.Builder("analytics", a.f(objectType));
        builder38.e = listR28;
        List listR29 = CollectionsKt.R(compiledFieldC44, compiledFieldC45, compiledFieldC46, compiledFieldG, compiledFieldG2, builder38.c());
        D = listR29;
        CompiledField compiledFieldC47 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder39 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder39.b(list);
        List listR30 = CollectionsKt.R(compiledFieldC47, builder39.a());
        E = listR30;
        CompiledField compiledFieldC48 = new CompiledField.Builder("errorMessage", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC49 = new CompiledField.Builder("errorTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder40 = new CompiledField.Builder("impressionAnalytics", objectType);
        builder40.e = listR30;
        List listR31 = CollectionsKt.R(compiledFieldC48, compiledFieldC49, builder40.c());
        F = listR31;
        CompiledField compiledFieldC50 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder41 = new CompiledFragment.Builder("PaymentInstrumentResponseSuccess", CollectionsKt.Q("PaymentInstrumentResponseSuccess"));
        builder41.d = listR29;
        CompiledFragment compiledFragmentA10 = builder41.a();
        CompiledFragment.Builder builder42 = new CompiledFragment.Builder("PaymentInstrumentResponseValidationFailure", CollectionsKt.Q("PaymentInstrumentResponseValidationFailure"));
        builder42.d = listR31;
        List listR32 = CollectionsKt.R(compiledFieldC50, compiledFragmentA10, builder42.a());
        G = listR32;
        CompiledField.Builder builder43 = new CompiledField.Builder("paymentInstruments", CompiledGraphQL.b(PaymentInstrumentsResponse.f11690a));
        new CompiledArgument.Builder(Query.b2);
        builder43.d = au.com.woolworths.android.onesite.a.v();
        builder43.e = listR32;
        H = CollectionsKt.Q(builder43.c());
    }
}
