package com.woolworths.shop.specials.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.graphql.common.fragment.selections.ProductCardSelections;
import au.com.woolworths.sdui.shop.fragment.selections.AnalyticsFieldsSelections;
import au.com.woolworths.shop.aem.components.contentcard.fragment.selections.ContentCardSelections;
import au.com.woolworths.shop.aem.components.offercard.fragment.selections.OfferCardSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.BannerImageFormat;
import au.com.woolworths.shop.graphql.type.CardHeight;
import au.com.woolworths.shop.graphql.type.CatalogueCardType;
import au.com.woolworths.shop.graphql.type.EditorialBannerFooter;
import au.com.woolworths.shop.graphql.type.FooterStyle;
import au.com.woolworths.shop.graphql.type.GenericPageFeedItem;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLID;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.HorizontalListItem;
import au.com.woolworths.shop.graphql.type.ImageWithAlt;
import au.com.woolworths.shop.graphql.type.ParagraphTextItemType;
import au.com.woolworths.shop.graphql.type.ProductCard;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.SpecialsHomePage;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/specials/selections/SpecialsHomeQuerySelections;", "", "specials_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class SpecialsHomeQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f23755a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;

    static {
        ActionType.e.getClass();
        EnumType enumType = ActionType.f;
        CompiledField compiledFieldC = new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c();
        CustomScalarType customScalarType = GraphQLString.f11443a;
        List listR = CollectionsKt.R(compiledFieldC, new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c());
        f23755a = listR;
        CompiledField compiledFieldG = d.g("linkCardImage", customScalarType);
        CompiledField compiledFieldC2 = new CompiledField.Builder("linkCardTitle", CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType = Action.f10997a;
        CompiledField.Builder builder = new CompiledField.Builder("linkCardAction", CompiledGraphQL.b(objectType));
        builder.e = listR;
        List listR2 = CollectionsKt.R(compiledFieldG, compiledFieldC2, builder.c());
        b = listR2;
        CompiledField compiledFieldC3 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        List list = ProductCardSelections.A;
        builder2.b(list);
        List listR3 = CollectionsKt.R(compiledFieldC3, builder2.a());
        c = listR3;
        CompiledField compiledFieldC4 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("OfferCard", CollectionsKt.Q("OfferCard"));
        builder3.b(OfferCardSelections.f);
        List listR4 = CollectionsKt.R(compiledFieldC4, builder3.a());
        d = listR4;
        CompiledField compiledFieldC5 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("ContentCard", CollectionsKt.Q("ContentCard"));
        builder4.b(ContentCardSelections.e);
        List listR5 = CollectionsKt.R(compiledFieldC5, builder4.a());
        e = listR5;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder5.d = list;
        List listR6 = CollectionsKt.R(compiledFieldC6, builder5.a());
        f = listR6;
        CompiledField.Builder builder6 = new CompiledField.Builder("promotionCardProduct", CompiledGraphQL.b(ProductCard.f11717a));
        builder6.e = listR6;
        List listR7 = CollectionsKt.R(builder6.c(), d.g("promotionCardOfferId", customScalarType));
        g = listR7;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("QuickLinkCard", CollectionsKt.Q("QuickLinkCard"));
        builder7.d = listR2;
        CompiledFragment compiledFragmentA = builder7.a();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder8.d = listR3;
        CompiledFragment compiledFragmentA2 = builder8.a();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("OfferCard", CollectionsKt.Q("OfferCard"));
        builder9.d = listR4;
        CompiledFragment compiledFragmentA3 = builder9.a();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("ContentCard", CollectionsKt.Q("ContentCard"));
        builder10.d = listR5;
        CompiledFragment compiledFragmentA4 = builder10.a();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("PromotionCard", CollectionsKt.Q("PromotionCard"));
        builder11.c = a.s("includePromotionCard", false);
        builder11.d = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC7, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, builder11.a());
        h = listR8;
        CompiledField compiledFieldC8 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG2 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField compiledFieldG3 = d.g("actionTitle", customScalarType);
        CompiledField compiledFieldG4 = d.g("deepLink", customScalarType);
        CompiledField.Builder builder12 = new CompiledField.Builder("items", d.j(HorizontalListItem.f11475a));
        builder12.e = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC8, compiledFieldG2, compiledFieldG3, compiledFieldG4, builder12.c());
        i = listR9;
        CustomScalarType customScalarType2 = GraphQLID.f11441a;
        CompiledField compiledFieldC9 = new CompiledField.Builder("id", customScalarType2).c();
        CompiledField compiledFieldC10 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC11 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG5 = d.g("imageLeft", customScalarType);
        CatalogueCardType.e.getClass();
        List listR10 = CollectionsKt.R(compiledFieldC9, compiledFieldC10, compiledFieldC11, compiledFieldG5, new CompiledField.Builder("catalogueCardType", CatalogueCardType.f).c());
        j = listR10;
        CompiledField compiledFieldC12 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        List list2 = AnalyticsFieldsSelections.b;
        builder13.b(list2);
        List listR11 = CollectionsKt.R(compiledFieldC12, builder13.a());
        k = listR11;
        CompiledField compiledFieldC13 = new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c();
        CompiledField compiledFieldC14 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG6 = d.g("id", customScalarType);
        ObjectType objectType2 = Analytics.f11028a;
        CompiledField.Builder builder14 = new CompiledField.Builder("analytics", objectType2);
        builder14.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC13, compiledFieldC14, compiledFieldG6, builder14.c());
        l = listR12;
        CompiledField compiledFieldC15 = new CompiledField.Builder("chatEntryCardTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("chatEntryCardSubtitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("chatEntryCardShowBeta", GraphQLBoolean.f11439a).c();
        CompiledField compiledFieldC18 = new CompiledField.Builder("chatEntryCardTextPrompts", a.e(customScalarType)).c();
        CompiledField compiledFieldC19 = new CompiledField.Builder("chatEntryCardImageUrl", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder15 = new CompiledField.Builder("chatEntryCardAction", CompiledGraphQL.b(objectType));
        builder15.e = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, compiledFieldC19, builder15.c());
        m = listR13;
        CardHeight.e.getClass();
        List listR14 = CollectionsKt.R(new CompiledField.Builder("cardHeight", CompiledGraphQL.b(CardHeight.f)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("image", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("link", CompiledGraphQL.b(customScalarType)).c());
        n = listR14;
        List listR15 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        o = listR15;
        CompiledField compiledFieldC20 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder16.d = list2;
        List listR16 = CollectionsKt.R(compiledFieldC20, builder16.a());
        p = listR16;
        CompiledField compiledFieldC21 = new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c();
        CompiledField compiledFieldC22 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG7 = d.g("id", customScalarType);
        CompiledField.Builder builder17 = new CompiledField.Builder("analytics", objectType2);
        builder17.e = listR16;
        List listR17 = CollectionsKt.R(compiledFieldC21, compiledFieldC22, compiledFieldG7, builder17.c());
        q = listR17;
        List listR18 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        r = listR18;
        FooterStyle.e.getClass();
        CompiledField compiledFieldC23 = new CompiledField.Builder("style", CompiledGraphQL.b(FooterStyle.f)).c();
        CompiledField compiledFieldG8 = d.g(TextBundle.TEXT_ENTRY, customScalarType);
        ObjectType objectType3 = ImageWithAlt.f11487a;
        CompiledField.Builder builder18 = new CompiledField.Builder("logo", objectType3);
        builder18.e = listR18;
        List listR19 = CollectionsKt.R(compiledFieldC23, compiledFieldG8, builder18.c());
        s = listR19;
        CompiledField compiledFieldC24 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder19.d = list2;
        List listR20 = CollectionsKt.R(compiledFieldC24, builder19.a());
        t = listR20;
        CompiledField compiledFieldC25 = new CompiledField.Builder("editorialBannerId", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC26 = new CompiledField.Builder("editorialBannerBackgroundColour", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder20 = new CompiledField.Builder("editorialBannerImage", objectType3);
        builder20.e = listR15;
        CompiledField compiledFieldC27 = builder20.c();
        CompiledField compiledFieldG9 = d.g("editorialBannerTitle", customScalarType);
        CompiledField compiledFieldG10 = d.g("editorialBannerSubtitle", customScalarType);
        CompiledField.Builder builder21 = new CompiledField.Builder("editorialBannerAction", objectType);
        builder21.e = listR17;
        CompiledField compiledFieldC28 = builder21.c();
        CompiledField.Builder builder22 = new CompiledField.Builder("editorialBannerFooter", EditorialBannerFooter.f11375a);
        builder22.e = listR19;
        CompiledField compiledFieldC29 = builder22.c();
        BannerImageFormat.e.getClass();
        CompiledField compiledFieldC30 = new CompiledField.Builder("editorialBannerImageFormat", CompiledGraphQL.b(BannerImageFormat.f)).c();
        CompiledField.Builder builder23 = new CompiledField.Builder("editorialBannerAnalytics", objectType2);
        builder23.e = listR20;
        List listR21 = CollectionsKt.R(compiledFieldC25, compiledFieldC26, compiledFieldC27, compiledFieldG9, compiledFieldG10, compiledFieldC28, compiledFieldC29, compiledFieldC30, builder23.c());
        u = listR21;
        CompiledField compiledFieldC31 = new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c();
        ParagraphTextItemType.e.getClass();
        List listR22 = CollectionsKt.R(compiledFieldC31, new CompiledField.Builder("type", CompiledGraphQL.b(ParagraphTextItemType.f)).c());
        v = listR22;
        CompiledField compiledFieldC32 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder24 = new CompiledFragment.Builder("HorizontalList", CollectionsKt.Q("HorizontalList"));
        builder24.d = listR9;
        CompiledFragment compiledFragmentA5 = builder24.a();
        CompiledFragment.Builder builder25 = new CompiledFragment.Builder("CatalogueCard", CollectionsKt.Q("CatalogueCard"));
        builder25.d = listR10;
        CompiledFragment compiledFragmentA6 = builder25.a();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("ChatEntryCard", CollectionsKt.Q("ChatEntryCard"));
        builder26.c = a.s("includeChatEntryCard", false);
        builder26.d = listR13;
        CompiledFragment compiledFragmentA7 = builder26.a();
        CompiledFragment.Builder builder27 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder27.c = a.s("includeActionableCard", false);
        builder27.d = listR14;
        CompiledFragment compiledFragmentA8 = builder27.a();
        CompiledFragment.Builder builder28 = new CompiledFragment.Builder("EditorialBanner", CollectionsKt.Q("EditorialBanner"));
        builder28.c = a.s("includeEditorialBanner", false);
        builder28.d = listR21;
        CompiledFragment compiledFragmentA9 = builder28.a();
        CompiledFragment.Builder builder29 = new CompiledFragment.Builder("ParagraphTextItem", CollectionsKt.Q("ParagraphTextItem"));
        builder29.c = a.s("includeParagraphText", false);
        builder29.d = listR22;
        List listR23 = CollectionsKt.R(compiledFieldC32, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, compiledFragmentA8, compiledFragmentA9, builder29.a());
        w = listR23;
        CompiledField.Builder builder30 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(GenericPageFeedItem.f11427a)));
        builder30.e = listR23;
        List listQ = CollectionsKt.Q(builder30.c());
        x = listQ;
        CompiledField.Builder builder31 = new CompiledField.Builder("specialsHome", SpecialsHomePage.f11927a);
        new CompiledArgument.Builder(Query.B2);
        builder31.d = au.com.woolworths.android.onesite.a.v();
        builder31.e = listQ;
        y = CollectionsKt.Q(builder31.c());
    }
}
