package com.woolworths.feature.shop.account.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.shop.graphql.type.AccountDetailsPage;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.CoreRowUI;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.IconAsset;
import au.com.woolworths.shop.graphql.type.MyAccountFeedItem;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/feature/shop/account/selections/AccountDetailsQuerySelections;", "", "account_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class AccountDetailsQuerySelections {
    public static final List A;
    public static final List B;
    public static final List C;
    public static final List D;
    public static final List E;
    public static final List F;
    public static final List G;
    public static final List H;
    public static final List I;
    public static final List J;
    public static final List K;
    public static final List L;

    /* renamed from: a, reason: collision with root package name */
    public static final List f19389a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        f19389a = listQ;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(customScalarType)).c());
        b = listQ2;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder.d = listQ;
        CompiledFragment compiledFragmentA = builder.a();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder2.d = listQ2;
        List listR = CollectionsKt.R(compiledFieldC, compiledFragmentA, builder2.a());
        c = listR;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        d = listQ3;
        List listQ4 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(customScalarType)).c());
        e = listQ4;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder3.d = listQ3;
        CompiledFragment compiledFragmentA2 = builder3.a();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder4.d = listQ4;
        List listR2 = CollectionsKt.R(compiledFieldC2, compiledFragmentA2, builder4.a());
        f = listR2;
        CompiledField compiledFieldG = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CompiledField compiledFieldC3 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        UnionType unionType = IconAsset.f11477a;
        CompiledField.Builder builder5 = new CompiledField.Builder("leadingAsset", unionType);
        builder5.e = listR;
        CompiledField compiledFieldC4 = builder5.c();
        CompiledField compiledFieldG2 = d.g("overlineText", customScalarType);
        CompiledField.Builder builder6 = new CompiledField.Builder("trailingAsset", unionType);
        builder6.e = listR2;
        List listR3 = CollectionsKt.R(compiledFieldG, compiledFieldC3, compiledFieldC4, compiledFieldG2, builder6.c());
        g = listR3;
        CompiledField compiledFieldC5 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG3 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        ObjectType objectType = CoreRowUI.f11293a;
        CompiledField.Builder builder7 = new CompiledField.Builder("rowItems", a.f(objectType));
        builder7.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC5, compiledFieldG3, builder7.c());
        h = listR4;
        List listQ5 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        i = listQ5;
        List listQ6 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(customScalarType)).c());
        j = listQ6;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder8.d = listQ5;
        CompiledFragment compiledFragmentA3 = builder8.a();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder9.d = listQ6;
        List listR5 = CollectionsKt.R(compiledFieldC6, compiledFragmentA3, builder9.a());
        k = listR5;
        List listQ7 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        l = listQ7;
        List listQ8 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(customScalarType)).c());
        m = listQ8;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder10.d = listQ7;
        CompiledFragment compiledFragmentA4 = builder10.a();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder11.d = listQ8;
        List listR6 = CollectionsKt.R(compiledFieldC7, compiledFragmentA4, builder11.a());
        n = listR6;
        CompiledField compiledFieldG4 = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CompiledField compiledFieldC8 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder12 = new CompiledField.Builder("leadingAsset", unionType);
        builder12.e = listR5;
        CompiledField compiledFieldC9 = builder12.c();
        CompiledField compiledFieldG5 = d.g("overlineText", customScalarType);
        CompiledField.Builder builder13 = new CompiledField.Builder("trailingAsset", unionType);
        builder13.e = listR6;
        List listR7 = CollectionsKt.R(compiledFieldG4, compiledFieldC8, compiledFieldC9, compiledFieldG5, builder13.c());
        o = listR7;
        CompiledField compiledFieldC10 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG6 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField.Builder builder14 = new CompiledField.Builder("rowItems", a.f(objectType));
        builder14.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC10, compiledFieldG6, builder14.c());
        p = listR8;
        List listQ9 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        q = listQ9;
        List listQ10 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(customScalarType)).c());
        r = listQ10;
        CompiledField compiledFieldC11 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder15.d = listQ9;
        CompiledFragment compiledFragmentA5 = builder15.a();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder16.d = listQ10;
        List listR9 = CollectionsKt.R(compiledFieldC11, compiledFragmentA5, builder16.a());
        s = listR9;
        List listQ11 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        t = listQ11;
        List listQ12 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(customScalarType)).c());
        u = listQ12;
        CompiledField compiledFieldC12 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder17.d = listQ11;
        CompiledFragment compiledFragmentA6 = builder17.a();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder18.d = listQ12;
        List listR10 = CollectionsKt.R(compiledFieldC12, compiledFragmentA6, builder18.a());
        v = listR10;
        CompiledField compiledFieldG7 = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CompiledField compiledFieldC13 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder19 = new CompiledField.Builder("leadingAsset", unionType);
        builder19.e = listR9;
        CompiledField compiledFieldC14 = builder19.c();
        CompiledField compiledFieldG8 = d.g("overlineText", customScalarType);
        CompiledField.Builder builder20 = new CompiledField.Builder("trailingAsset", unionType);
        builder20.e = listR10;
        List listR11 = CollectionsKt.R(compiledFieldG7, compiledFieldC13, compiledFieldC14, compiledFieldG8, builder20.c());
        w = listR11;
        CompiledField compiledFieldC15 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG9 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField.Builder builder21 = new CompiledField.Builder("rowItems", a.f(objectType));
        builder21.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC15, compiledFieldG9, builder21.c());
        x = listR12;
        List listQ13 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        y = listQ13;
        List listQ14 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(customScalarType)).c());
        z = listQ14;
        CompiledField compiledFieldC16 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder22.d = listQ13;
        CompiledFragment compiledFragmentA7 = builder22.a();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder23.d = listQ14;
        List listR13 = CollectionsKt.R(compiledFieldC16, compiledFragmentA7, builder23.a());
        A = listR13;
        List listQ15 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        B = listQ15;
        List listQ16 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(customScalarType)).c());
        C = listQ16;
        CompiledField compiledFieldC17 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder24 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder24.d = listQ15;
        CompiledFragment compiledFragmentA8 = builder24.a();
        CompiledFragment.Builder builder25 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder25.d = listQ16;
        List listR14 = CollectionsKt.R(compiledFieldC17, compiledFragmentA8, builder25.a());
        D = listR14;
        CompiledField compiledFieldG10 = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CompiledField compiledFieldC18 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder26 = new CompiledField.Builder("leadingAsset", unionType);
        builder26.e = listR13;
        CompiledField compiledFieldC19 = builder26.c();
        CompiledField compiledFieldG11 = d.g("overlineText", customScalarType);
        CompiledField.Builder builder27 = new CompiledField.Builder("trailingAsset", unionType);
        builder27.e = listR14;
        List listR15 = CollectionsKt.R(compiledFieldG10, compiledFieldC18, compiledFieldC19, compiledFieldG11, builder27.c());
        E = listR15;
        CompiledField compiledFieldC20 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG12 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField.Builder builder28 = new CompiledField.Builder("rowItems", a.f(objectType));
        builder28.e = listR15;
        List listR16 = CollectionsKt.R(compiledFieldC20, compiledFieldG12, builder28.c());
        F = listR16;
        CompiledField compiledFieldG13 = d.g("id", customScalarType);
        CompiledField compiledFieldC21 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        ActionType.e.getClass();
        List listR17 = CollectionsKt.R(compiledFieldG13, compiledFieldC21, new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.f)).c());
        G = listR17;
        CompiledField compiledFieldC22 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        ButtonStyle.e.getClass();
        CompiledField compiledFieldC23 = new CompiledField.Builder("style", ButtonStyle.f).c();
        CompiledField compiledFieldC24 = new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.f11439a)).c();
        CompiledField.Builder builder29 = new CompiledField.Builder("buttonAction", Action.f10997a);
        builder29.e = listR17;
        List listR18 = CollectionsKt.R(compiledFieldC22, compiledFieldC23, compiledFieldC24, builder29.c(), d.g("iconUrl", customScalarType));
        H = listR18;
        CompiledField.Builder builder30 = new CompiledField.Builder("button", CompiledGraphQL.b(Button.f11080a));
        builder30.e = listR18;
        List listQ17 = CollectionsKt.Q(builder30.c());
        I = listQ17;
        CompiledField compiledFieldC25 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder31 = new CompiledFragment.Builder("MyAccountPersonalDetails", CollectionsKt.Q("MyAccountPersonalDetails"));
        builder31.d = listR4;
        CompiledFragment compiledFragmentA9 = builder31.a();
        CompiledFragment.Builder builder32 = new CompiledFragment.Builder("MyAccountBusinessDetails", CollectionsKt.Q("MyAccountBusinessDetails"));
        builder32.d = listR8;
        CompiledFragment compiledFragmentA10 = builder32.a();
        CompiledFragment.Builder builder33 = new CompiledFragment.Builder("MyAccountContactDetails", CollectionsKt.Q("MyAccountContactDetails"));
        builder33.d = listR12;
        CompiledFragment compiledFragmentA11 = builder33.a();
        CompiledFragment.Builder builder34 = new CompiledFragment.Builder("MyAccountPreferences", CollectionsKt.Q("MyAccountPreferences"));
        builder34.d = listR16;
        CompiledFragment compiledFragmentA12 = builder34.a();
        CompiledFragment.Builder builder35 = new CompiledFragment.Builder("MyAccountFooter", CollectionsKt.Q("MyAccountFooter"));
        builder35.d = listQ17;
        List listR19 = CollectionsKt.R(compiledFieldC25, compiledFragmentA9, compiledFragmentA10, compiledFragmentA11, compiledFragmentA12, builder35.a());
        J = listR19;
        CompiledField.Builder builder36 = new CompiledField.Builder("feed", CompiledGraphQL.b(CompiledGraphQL.a(MyAccountFeedItem.f11607a)));
        builder36.e = listR19;
        List listQ18 = CollectionsKt.Q(builder36.c());
        K = listQ18;
        CompiledField.Builder builder37 = new CompiledField.Builder("accountDetails", CompiledGraphQL.b(AccountDetailsPage.f10996a));
        builder37.e = listQ18;
        L = CollectionsKt.Q(builder37.c());
    }
}
