package com.woolworths.rewards.account.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.rewards.graphql.type.AccountBanner;
import au.com.woolworths.rewards.graphql.type.AccountHomeFooter;
import au.com.woolworths.rewards.graphql.type.AccountHomeOption;
import au.com.woolworths.rewards.graphql.type.AccountHomeOptionAction;
import au.com.woolworths.rewards.graphql.type.AccountHomeSection;
import au.com.woolworths.rewards.graphql.type.Action;
import au.com.woolworths.rewards.graphql.type.ActionType;
import au.com.woolworths.rewards.graphql.type.Analytics;
import au.com.woolworths.rewards.graphql.type.BannerNotificationDisplayType;
import au.com.woolworths.rewards.graphql.type.BasicInsetAlert;
import au.com.woolworths.rewards.graphql.type.ContentCta;
import au.com.woolworths.rewards.graphql.type.CoreAlertStyle;
import au.com.woolworths.rewards.graphql.type.CoreInsetAlertUI;
import au.com.woolworths.rewards.graphql.type.GraphQLBoolean;
import au.com.woolworths.rewards.graphql.type.GraphQLID;
import au.com.woolworths.rewards.graphql.type.GraphQLInt;
import au.com.woolworths.rewards.graphql.type.GraphQLString;
import au.com.woolworths.rewards.graphql.type.HomeOptionAction;
import au.com.woolworths.rewards.graphql.type.IconListItemAction;
import au.com.woolworths.rewards.graphql.type.Query;
import au.com.woolworths.rewards.graphql.type.RewardsAccountHome;
import au.com.woolworths.rewards.graphql.type.UnreadChatbotMsg;
import au.com.woolworths.sdui.rewards.fragment.selections.AnalyticsFieldsSelections;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/rewards/account/selections/AccountHomeQuerySelections;", "", "account_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class AccountHomeQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f20639a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;

    static {
        CustomScalarType customScalarType = GraphQLString.f9617a;
        CompiledField compiledFieldC = new CompiledField.Builder("title", customScalarType).c();
        CompiledField compiledFieldG = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CoreAlertStyle.e.getClass();
        List listR = CollectionsKt.R(compiledFieldC, compiledFieldG, new CompiledField.Builder("style", CompiledGraphQL.b(CoreAlertStyle.f)).c());
        f20639a = listR;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder.b(AnalyticsFieldsSelections.b);
        List listR2 = CollectionsKt.R(compiledFieldC2, builder.a());
        b = listR2;
        CompiledField compiledFieldG2 = d.g("id", customScalarType);
        ActionType.e.getClass();
        CompiledField compiledFieldC3 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.f)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder2 = new CompiledField.Builder("analytics", Analytics.f9421a);
        builder2.e = listR2;
        List listR3 = CollectionsKt.R(compiledFieldG2, compiledFieldC3, compiledFieldC4, builder2.c());
        c = listR3;
        CompiledField.Builder builder3 = new CompiledField.Builder("insetAlertUI", CompiledGraphQL.b(CoreInsetAlertUI.f9491a));
        builder3.e = listR;
        CompiledField compiledFieldC5 = builder3.c();
        CompiledField.Builder builder4 = new CompiledField.Builder("insetAlertAction", Action.f9400a);
        builder4.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC5, builder4.c(), d.g("insetAlertActionLabel", customScalarType));
        d = listR4;
        List listR5 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        e = listR5;
        CustomScalarType customScalarType2 = GraphQLID.f9615a;
        CompiledField compiledFieldC6 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c();
        BannerNotificationDisplayType.e.getClass();
        CompiledField compiledFieldC7 = new CompiledField.Builder("displayType", CompiledGraphQL.b(BannerNotificationDisplayType.f)).c();
        CompiledField compiledFieldG3 = d.g("title", customScalarType);
        CompiledField compiledFieldC8 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder5 = new CompiledField.Builder("primaryCta", ContentCta.f9485a);
        builder5.e = listR5;
        CompiledField compiledFieldC9 = builder5.c();
        CustomScalarType customScalarType3 = GraphQLBoolean.f9613a;
        List listR6 = CollectionsKt.R(compiledFieldC6, compiledFieldC7, compiledFieldG3, compiledFieldC8, compiledFieldC9, new CompiledField.Builder("canDismiss", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("shouldShowNewBadge", CompiledGraphQL.b(customScalarType3)).c());
        f = listR6;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("AccountBannerNotification", CollectionsKt.Q("AccountBannerNotification"));
        builder6.d = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC10, builder6.a());
        g = listR7;
        HomeOptionAction.e.getClass();
        EnumType enumType = HomeOptionAction.f;
        List listR8 = CollectionsKt.R(new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        h = listR8;
        CompiledField compiledFieldC11 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC12 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType = AccountHomeOptionAction.f9390a;
        CompiledField.Builder builder7 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(objectType));
        builder7.e = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC11, compiledFieldC12, builder7.c(), d.g("shouldShowNewBadge", customScalarType3));
        i = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("page", CompiledGraphQL.b(customScalarType)).c(), d.g("shouldShowNewBadge", customScalarType3));
        j = listR10;
        List listR11 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("page", CompiledGraphQL.b(customScalarType)).c(), d.g("shouldShowNewBadge", customScalarType3));
        k = listR11;
        List listR12 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c(), d.g("shouldShowNewBadge", customScalarType3));
        l = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("formId", CompiledGraphQL.b(customScalarType2)).c(), d.g("shouldShowNewBadge", customScalarType3));
        m = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        n = listR14;
        CompiledField compiledFieldC13 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC14 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder8 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(objectType));
        builder8.e = listR14;
        List listR15 = CollectionsKt.R(compiledFieldC13, compiledFieldC14, builder8.c(), d.g("shouldShowNewBadge", customScalarType3));
        o = listR15;
        List listR16 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("page", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("callbackURL", CompiledGraphQL.b(customScalarType)).c(), d.g("shouldShowNewBadge", customScalarType3));
        p = listR16;
        CompiledField compiledFieldC15 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("AccountHomeOptionItem", CollectionsKt.Q("AccountHomeOptionItem"));
        builder9.d = listR9;
        CompiledFragment compiledFragmentA = builder9.a();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("AccountHomeOptionMagicLinkItem", CollectionsKt.Q("AccountHomeOptionMagicLinkItem"));
        builder10.d = listR10;
        CompiledFragment compiledFragmentA2 = builder10.a();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("AccountHomeOptionMandyItem", CollectionsKt.Q("AccountHomeOptionMandyItem"));
        builder11.d = listR11;
        CompiledFragment compiledFragmentA3 = builder11.a();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("AccountHomeAndroidAppReviewLinkItem", CollectionsKt.Q("AccountHomeAndroidAppReviewLinkItem"));
        builder12.d = listR12;
        CompiledFragment compiledFragmentA4 = builder12.a();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("AccountHomeAndroidMedalliaItem", CollectionsKt.Q("AccountHomeAndroidMedalliaItem"));
        builder13.d = listR13;
        CompiledFragment compiledFragmentA5 = builder13.a();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("AccountHomeOnboardingItem", CollectionsKt.Q("AccountHomeOnboardingItem"));
        builder14.d = listR15;
        CompiledFragment compiledFragmentA6 = builder14.a();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("AccountHomeOptionCanCloseAccountItem", CollectionsKt.Q("AccountHomeOptionCanCloseAccountItem"));
        builder15.d = listR16;
        List listR17 = CollectionsKt.R(compiledFieldC15, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, builder15.a());
        q = listR17;
        CompiledField compiledFieldC16 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder16 = new CompiledField.Builder("options", d.j(AccountHomeOption.f9389a));
        builder16.e = listR17;
        List listR18 = CollectionsKt.R(compiledFieldC16, builder16.c());
        r = listR18;
        List listR19 = CollectionsKt.R(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c(), d.g(AnnotatedPrivateKey.LABEL, customScalarType));
        s = listR19;
        CompiledField compiledFieldC17 = new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC18 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder17 = new CompiledField.Builder(UrlHandler.ACTION, IconListItemAction.f9627a);
        builder17.e = listR19;
        List listR20 = CollectionsKt.R(compiledFieldC17, compiledFieldC18, builder17.c());
        t = listR20;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("count", CompiledGraphQL.b(GraphQLInt.f9616a)).c());
        u = listQ;
        CompiledField.Builder builder18 = new CompiledField.Builder("appUpgrade", BasicInsetAlert.f9438a);
        builder18.c = a.s("includeBasicInsetAlert", false);
        builder18.e = listR4;
        CompiledField compiledFieldC19 = builder18.c();
        CompiledField.Builder builder19 = new CompiledField.Builder("accountBanner", AccountBanner.f9380a);
        builder19.e = listR7;
        CompiledField compiledFieldC20 = builder19.c();
        CompiledField.Builder builder20 = new CompiledField.Builder("sections", CompiledGraphQL.a(CompiledGraphQL.b(AccountHomeSection.f9398a)));
        builder20.e = listR18;
        CompiledField compiledFieldC21 = builder20.c();
        CompiledField.Builder builder21 = new CompiledField.Builder("accountHomeFooter", AccountHomeFooter.f9385a);
        builder21.e = listR20;
        CompiledField compiledFieldC22 = builder21.c();
        CompiledField.Builder builder22 = new CompiledField.Builder("unreadChatbotMsg", UnreadChatbotMsg.f9933a);
        builder22.e = listQ;
        List listR21 = CollectionsKt.R(compiledFieldC19, compiledFieldC20, compiledFieldC21, compiledFieldC22, builder22.c());
        v = listR21;
        CompiledField.Builder builder23 = new CompiledField.Builder("rewardsAccountHome", RewardsAccountHome.f9798a);
        new CompiledArgument.Builder(Query.b);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.f9776a);
        builder23.d = CollectionsKt.R(compiledArgument, new CompiledArgument());
        builder23.e = listR21;
        w = CollectionsKt.Q(builder23.c());
    }
}
