package com.woolworths.rewards.account.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.rewards.graphql.type.AccountBanner;
import au.com.woolworths.rewards.graphql.type.AccountHomeFooter;
import au.com.woolworths.rewards.graphql.type.AccountHomeOption;
import au.com.woolworths.rewards.graphql.type.AccountHomeOptionAction;
import au.com.woolworths.rewards.graphql.type.AccountMenuSection;
import au.com.woolworths.rewards.graphql.type.BannerNotificationDisplayType;
import au.com.woolworths.rewards.graphql.type.ContentCta;
import au.com.woolworths.rewards.graphql.type.GraphQLBoolean;
import au.com.woolworths.rewards.graphql.type.GraphQLID;
import au.com.woolworths.rewards.graphql.type.GraphQLString;
import au.com.woolworths.rewards.graphql.type.HomeOptionAction;
import au.com.woolworths.rewards.graphql.type.IconListItemAction;
import au.com.woolworths.rewards.graphql.type.RewardsAccountMenu;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/rewards/account/selections/AccountMenuQuerySelections;", "", "account_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class AccountMenuQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f20640a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;

    static {
        CustomScalarType customScalarType = GraphQLString.f9617a;
        List listR = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        f20640a = listR;
        CustomScalarType customScalarType2 = GraphQLID.f9615a;
        CompiledField compiledFieldC = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c();
        BannerNotificationDisplayType.e.getClass();
        CompiledField compiledFieldC2 = new CompiledField.Builder("displayType", CompiledGraphQL.b(BannerNotificationDisplayType.f)).c();
        CompiledField compiledFieldG = d.g("title", customScalarType);
        CompiledField compiledFieldC3 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder = new CompiledField.Builder("primaryCta", ContentCta.f9485a);
        builder.e = listR;
        CompiledField compiledFieldC4 = builder.c();
        CustomScalarType customScalarType3 = GraphQLBoolean.f9613a;
        List listR2 = CollectionsKt.R(compiledFieldC, compiledFieldC2, compiledFieldG, compiledFieldC3, compiledFieldC4, new CompiledField.Builder("canDismiss", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("shouldShowNewBadge", CompiledGraphQL.b(customScalarType3)).c());
        b = listR2;
        CompiledField compiledFieldC5 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("AccountBannerNotification", CollectionsKt.Q("AccountBannerNotification"));
        builder2.d = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC5, builder2.a());
        c = listR3;
        HomeOptionAction.e.getClass();
        EnumType enumType = HomeOptionAction.f;
        List listR4 = CollectionsKt.R(new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        d = listR4;
        CompiledField compiledFieldC6 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType = AccountHomeOptionAction.f9390a;
        CompiledField.Builder builder3 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(objectType));
        builder3.e = listR4;
        List listR5 = CollectionsKt.R(compiledFieldC6, compiledFieldC7, builder3.c(), d.g("shouldShowNewBadge", customScalarType3));
        e = listR5;
        List listR6 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("page", CompiledGraphQL.b(customScalarType)).c(), d.g("shouldShowNewBadge", customScalarType3));
        f = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("page", CompiledGraphQL.b(customScalarType)).c(), d.g("shouldShowNewBadge", customScalarType3));
        g = listR7;
        List listR8 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c(), d.g("shouldShowNewBadge", customScalarType3));
        h = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("formId", CompiledGraphQL.b(customScalarType2)).c(), d.g("shouldShowNewBadge", customScalarType3));
        i = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        j = listR10;
        CompiledField compiledFieldC8 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC9 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder4 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(objectType));
        builder4.e = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC8, compiledFieldC9, builder4.c(), d.g("shouldShowNewBadge", customScalarType3));
        k = listR11;
        List listR12 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("page", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("callbackURL", CompiledGraphQL.b(customScalarType)).c(), d.g("shouldShowNewBadge", customScalarType3));
        l = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c());
        m = listR13;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("AccountHomeOptionItem", CollectionsKt.Q("AccountHomeOptionItem"));
        builder5.d = listR5;
        CompiledFragment compiledFragmentA = builder5.a();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("AccountHomeOptionMagicLinkItem", CollectionsKt.Q("AccountHomeOptionMagicLinkItem"));
        builder6.d = listR6;
        CompiledFragment compiledFragmentA2 = builder6.a();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("AccountHomeOptionMandyItem", CollectionsKt.Q("AccountHomeOptionMandyItem"));
        builder7.d = listR7;
        CompiledFragment compiledFragmentA3 = builder7.a();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("AccountHomeAndroidAppReviewLinkItem", CollectionsKt.Q("AccountHomeAndroidAppReviewLinkItem"));
        builder8.d = listR8;
        CompiledFragment compiledFragmentA4 = builder8.a();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("AccountHomeAndroidMedalliaItem", CollectionsKt.Q("AccountHomeAndroidMedalliaItem"));
        builder9.d = listR9;
        CompiledFragment compiledFragmentA5 = builder9.a();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("AccountHomeOnboardingItem", CollectionsKt.Q("AccountHomeOnboardingItem"));
        builder10.d = listR11;
        CompiledFragment compiledFragmentA6 = builder10.a();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("AccountHomeOptionCanCloseAccountItem", CollectionsKt.Q("AccountHomeOptionCanCloseAccountItem"));
        builder11.d = listR12;
        CompiledFragment compiledFragmentA7 = builder11.a();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("AccountHomeOptionDeleteAccountItem", CollectionsKt.Q("AccountHomeOptionDeleteAccountItem"));
        builder12.d = listR13;
        List listR14 = CollectionsKt.R(compiledFieldC10, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, builder12.a());
        n = listR14;
        CompiledField compiledFieldC11 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder13 = new CompiledField.Builder("items", d.j(AccountHomeOption.f9389a));
        builder13.e = listR14;
        List listR15 = CollectionsKt.R(compiledFieldC11, builder13.c());
        o = listR15;
        List listR16 = CollectionsKt.R(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c(), d.g(AnnotatedPrivateKey.LABEL, customScalarType));
        p = listR16;
        CompiledField compiledFieldC12 = new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC13 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder14 = new CompiledField.Builder(UrlHandler.ACTION, IconListItemAction.f9627a);
        builder14.e = listR16;
        List listR17 = CollectionsKt.R(compiledFieldC12, compiledFieldC13, builder14.c());
        q = listR17;
        CompiledField.Builder builder15 = new CompiledField.Builder("accountBanner", AccountBanner.f9380a);
        builder15.e = listR3;
        CompiledField compiledFieldC14 = builder15.c();
        CompiledField.Builder builder16 = new CompiledField.Builder("sections", CompiledGraphQL.a(CompiledGraphQL.b(AccountMenuSection.f9399a)));
        builder16.e = listR15;
        CompiledField compiledFieldC15 = builder16.c();
        CompiledField.Builder builder17 = new CompiledField.Builder("accountHomeFooter", AccountHomeFooter.f9385a);
        builder17.e = listR17;
        List listR18 = CollectionsKt.R(compiledFieldC14, compiledFieldC15, builder17.c());
        r = listR18;
        CompiledField.Builder builder18 = new CompiledField.Builder("rewardsAccountMenu", RewardsAccountMenu.f9800a);
        builder18.e = listR18;
        s = CollectionsKt.Q(builder18.c());
    }
}
