package au.com.woolworths.feature.rewards.everydayextras.signup.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.rewards.graphql.type.CardProviderIcon;
import au.com.woolworths.rewards.graphql.type.DividerType;
import au.com.woolworths.rewards.graphql.type.EverydayExtraButton;
import au.com.woolworths.rewards.graphql.type.EverydayExtraButtonStyle;
import au.com.woolworths.rewards.graphql.type.EverydayExtraSummary;
import au.com.woolworths.rewards.graphql.type.EverydayExtraSummaryContent;
import au.com.woolworths.rewards.graphql.type.EverydayExtraSummaryFooter;
import au.com.woolworths.rewards.graphql.type.EverydayExtraSummaryItem;
import au.com.woolworths.rewards.graphql.type.EverydayExtraWpayError;
import au.com.woolworths.rewards.graphql.type.EverydayExtraWpayErrorItem;
import au.com.woolworths.rewards.graphql.type.EverydayExtraWpayErrors;
import au.com.woolworths.rewards.graphql.type.EverydayExtraWpayExternalError;
import au.com.woolworths.rewards.graphql.type.GraphQLBoolean;
import au.com.woolworths.rewards.graphql.type.GraphQLID;
import au.com.woolworths.rewards.graphql.type.GraphQLInt;
import au.com.woolworths.rewards.graphql.type.GraphQLString;
import au.com.woolworths.rewards.graphql.type.Query;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.salesforce.marketingcloud.UrlHandler;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/feature/rewards/everydayextras/signup/selections/EverydayExtrasSummaryQuerySelections;", "", "everyday-extras-sign-up_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class EverydayExtrasSummaryQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f6217a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;

    static {
        CustomScalarType customScalarType = GraphQLString.f9617a;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        f6217a = listQ;
        List listR = CollectionsKt.R(new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("isRequired", CompiledGraphQL.b(GraphQLBoolean.f9613a)).c(), d.g("errorText", customScalarType));
        b = listR;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        c = listQ2;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        d = listQ3;
        DividerType.e.getClass();
        List listQ4 = CollectionsKt.Q(new CompiledField.Builder("type", CompiledGraphQL.b(DividerType.f)).c());
        e = listQ4;
        List listR2 = CollectionsKt.R(new CompiledField.Builder("domId", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("key", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("value", CompiledGraphQL.b(customScalarType)).c());
        f = listR2;
        CompiledField compiledFieldC = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder = new CompiledField.Builder("items", a.f(EverydayExtraWpayErrorItem.f9563a));
        builder.e = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC, builder.c());
        g = listR3;
        List listR4 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("value", CompiledGraphQL.b(customScalarType)).c());
        h = listR4;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder2 = new CompiledField.Builder("cardErrors", CompiledGraphQL.b(EverydayExtraWpayError.f9562a));
        builder2.e = listR3;
        CompiledField compiledFieldC3 = builder2.c();
        CompiledField.Builder builder3 = new CompiledField.Builder("externalSystemError", CompiledGraphQL.b(EverydayExtraWpayExternalError.f9565a));
        builder3.e = listR4;
        List listR5 = CollectionsKt.R(compiledFieldC2, compiledFieldC3, builder3.c());
        i = listR5;
        List listR6 = CollectionsKt.R(d.g("altText", customScalarType), new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c());
        j = listR6;
        CompiledField compiledFieldC4 = new CompiledField.Builder("titleIcon", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC5 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC6 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("labelIcon", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder4 = new CompiledField.Builder("errors", CompiledGraphQL.b(EverydayExtraWpayErrors.f9564a));
        builder4.e = listR5;
        CompiledField compiledFieldC8 = builder4.c();
        CompiledField compiledFieldC9 = new CompiledField.Builder("cardProvidersLabel", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder5 = new CompiledField.Builder("cardProviders", a.f(CardProviderIcon.f9450a));
        builder5.e = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC4, compiledFieldC5, compiledFieldC6, compiledFieldC7, compiledFieldC8, compiledFieldC9, builder5.c());
        k = listR7;
        CompiledField compiledFieldC10 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        EverydayExtraButtonStyle.e.getClass();
        EnumType enumType = EverydayExtraButtonStyle.f;
        List listR8 = CollectionsKt.R(compiledFieldC10, new CompiledField.Builder("style", enumType).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c());
        l = listR8;
        CompiledField compiledFieldC11 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC12 = new CompiledField.Builder("price", CompiledGraphQL.b(GraphQLInt.f9616a)).c();
        ObjectType objectType = EverydayExtraButton.f9517a;
        CompiledField.Builder builder6 = new CompiledField.Builder("button", CompiledGraphQL.b(objectType));
        builder6.e = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC11, compiledFieldC12, builder6.c());
        m = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c());
        n = listR10;
        CompiledField compiledFieldC13 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("TitleTextItem", CollectionsKt.Q("TitleTextItem"));
        builder7.d = listQ;
        CompiledFragment compiledFragmentA = builder7.a();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("CheckableTextItem", CollectionsKt.Q("CheckableTextItem"));
        builder8.d = listR;
        CompiledFragment compiledFragmentA2 = builder8.a();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("SubheadTextItem", CollectionsKt.Q("SubheadTextItem"));
        builder9.d = listQ2;
        CompiledFragment compiledFragmentA3 = builder9.a();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("ParagraphTextItem", CollectionsKt.Q("ParagraphTextItem"));
        builder10.d = listQ3;
        CompiledFragment compiledFragmentA4 = builder10.a();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("Divider", CollectionsKt.Q("Divider"));
        builder11.d = listQ4;
        CompiledFragment compiledFragmentA5 = builder11.a();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("EverydayExtraWpayPayment", CollectionsKt.Q("EverydayExtraWpayPayment"));
        builder12.d = listR7;
        CompiledFragment compiledFragmentA6 = builder12.a();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("EverydayExtraSelectedPlan", CollectionsKt.Q("EverydayExtraSelectedPlan"));
        builder13.d = listR9;
        CompiledFragment compiledFragmentA7 = builder13.a();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("SmallAppIconListItem", CollectionsKt.Q("SmallAppIconListItem"));
        builder14.d = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC13, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, builder14.a());
        o = listR11;
        CustomScalarType customScalarType2 = GraphQLID.f9615a;
        CompiledField compiledFieldC14 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder15 = new CompiledField.Builder("items", d.j(EverydayExtraSummaryItem.f9560a));
        builder15.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC14, builder15.c());
        p = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c(), a.d("style", enumType));
        q = listR13;
        CompiledField compiledFieldC15 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder16 = new CompiledField.Builder("items", a.f(objectType));
        builder16.e = listR13;
        List listR14 = CollectionsKt.R(compiledFieldC15, builder16.c());
        r = listR14;
        CompiledField compiledFieldC16 = new CompiledField.Builder("navigationTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder17 = new CompiledField.Builder("content", CompiledGraphQL.b(EverydayExtraSummaryContent.f9558a));
        builder17.e = listR12;
        CompiledField compiledFieldC17 = builder17.c();
        CompiledField.Builder builder18 = new CompiledField.Builder("footer", CompiledGraphQL.b(EverydayExtraSummaryFooter.f9559a));
        builder18.e = listR14;
        List listR15 = CollectionsKt.R(compiledFieldC16, compiledFieldC17, builder18.c());
        s = listR15;
        CompiledField.Builder builder19 = new CompiledField.Builder("everydayExtraSummary", EverydayExtraSummary.f9557a);
        new CompiledArgument.Builder(Query.i);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.h);
        builder19.d = CollectionsKt.R(compiledArgument, new CompiledArgument());
        builder19.e = listR15;
        t = CollectionsKt.Q(builder19.c());
    }
}
