package au.com.woolworths.feature.rewards.everydayextras.signup.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.rewards.graphql.type.Badge;
import au.com.woolworths.rewards.graphql.type.BadgeType;
import au.com.woolworths.rewards.graphql.type.EverydayExtraButtonStyle;
import au.com.woolworths.rewards.graphql.type.EverydayExtraChoosePlan;
import au.com.woolworths.rewards.graphql.type.EverydayExtraChoosePlanContent;
import au.com.woolworths.rewards.graphql.type.EverydayExtraChoosePlanFooter;
import au.com.woolworths.rewards.graphql.type.EverydayExtraChoosePlanFooterItem;
import au.com.woolworths.rewards.graphql.type.EverydayExtraChoosePlanItem;
import au.com.woolworths.rewards.graphql.type.GraphQLID;
import au.com.woolworths.rewards.graphql.type.GraphQLInt;
import au.com.woolworths.rewards.graphql.type.GraphQLString;
import au.com.woolworths.rewards.graphql.type.Query;
import au.com.woolworths.rewards.graphql.type.SpacerType;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/feature/rewards/everydayextras/signup/selections/EverydayExtrasChoosePlanQuerySelections;", "", "everyday-extras-sign-up_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class EverydayExtrasChoosePlanQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f6213a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;

    static {
        CustomScalarType customScalarType = GraphQLString.f9617a;
        List listR = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        f6213a = listR;
        List listR2 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c());
        b = listR2;
        CompiledField compiledFieldC = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        BadgeType.e.getClass();
        List listR3 = CollectionsKt.R(compiledFieldC, new CompiledField.Builder("type", CompiledGraphQL.b(BadgeType.f)).c());
        c = listR3;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLID.f9615a;
        CompiledField compiledFieldC3 = new CompiledField.Builder("identifier", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("planTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC5 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC6 = new CompiledField.Builder("price", CompiledGraphQL.b(GraphQLInt.f9616a)).c();
        CompiledField.Builder builder = new CompiledField.Builder("badge", Badge.f9432a);
        builder.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC2, compiledFieldC3, compiledFieldC4, compiledFieldC5, compiledFieldC6, builder.c());
        d = listR4;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        SpacerType.e.getClass();
        List listR5 = CollectionsKt.R(compiledFieldC7, new CompiledField.Builder("size", CompiledGraphQL.b(SpacerType.f)).c());
        e = listR5;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC9 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC10 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        EverydayExtraButtonStyle.e.getClass();
        EnumType enumType = EverydayExtraButtonStyle.f;
        List listR6 = CollectionsKt.R(compiledFieldC8, compiledFieldC9, compiledFieldC10, new CompiledField.Builder("style", enumType).c());
        f = listR6;
        CompiledField compiledFieldC11 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("TitleTextItem", CollectionsKt.Q("TitleTextItem"));
        builder2.d = listR;
        CompiledFragment compiledFragmentA = builder2.a();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("SmallAppIconListItem", CollectionsKt.Q("SmallAppIconListItem"));
        builder3.d = listR2;
        CompiledFragment compiledFragmentA2 = builder3.a();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("EverydayExtraSubscribePlan", CollectionsKt.Q("EverydayExtraSubscribePlan"));
        builder4.d = listR4;
        CompiledFragment compiledFragmentA3 = builder4.a();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("Spacer", CollectionsKt.Q("Spacer"));
        builder5.d = listR5;
        CompiledFragment compiledFragmentA4 = builder5.a();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("EverydayExtraButton", CollectionsKt.Q("EverydayExtraButton"));
        builder6.d = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC11, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, builder6.a());
        g = listR7;
        CompiledField compiledFieldC12 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC13 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder7 = new CompiledField.Builder("items", d.j(EverydayExtraChoosePlanItem.f9522a));
        builder7.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC12, compiledFieldC13, builder7.c());
        h = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c(), d.g("actionUrl", customScalarType), a.d("style", enumType));
        i = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        j = listR10;
        CompiledField compiledFieldC14 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("EverydayExtraButton", CollectionsKt.Q("EverydayExtraButton"));
        builder8.d = listR9;
        CompiledFragment compiledFragmentA5 = builder8.a();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("NoteTextItem", CollectionsKt.Q("NoteTextItem"));
        builder9.d = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC14, compiledFragmentA5, builder9.a());
        k = listR11;
        CompiledField compiledFieldC15 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder10 = new CompiledField.Builder("items", d.j(EverydayExtraChoosePlanFooterItem.f9521a));
        builder10.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC15, compiledFieldC16, builder10.c());
        l = listR12;
        CompiledField compiledFieldC17 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g("navigationTitle", customScalarType);
        CompiledField.Builder builder11 = new CompiledField.Builder("content", CompiledGraphQL.b(EverydayExtraChoosePlanContent.f9519a));
        builder11.e = listR8;
        CompiledField compiledFieldC18 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("footer", EverydayExtraChoosePlanFooter.f9520a);
        builder12.e = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC17, compiledFieldG, compiledFieldC18, builder12.c());
        m = listR13;
        CompiledField.Builder builder13 = new CompiledField.Builder("everydayExtraChoosePlan", EverydayExtraChoosePlan.f9518a);
        new CompiledArgument.Builder(Query.d);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.c);
        builder13.d = CollectionsKt.R(compiledArgument, new CompiledArgument());
        builder13.e = listR13;
        n = CollectionsKt.Q(builder13.c());
    }
}
