package au.com.woolworths.feature.rewards.everydayextras.signup.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.rewards.graphql.type.AlertDialog;
import au.com.woolworths.rewards.graphql.type.AlertDialogAnalytics;
import au.com.woolworths.rewards.graphql.type.ContentCta;
import au.com.woolworths.rewards.graphql.type.DividerType;
import au.com.woolworths.rewards.graphql.type.DownloadableAsset;
import au.com.woolworths.rewards.graphql.type.DownloadableAssetFit;
import au.com.woolworths.rewards.graphql.type.DownloadableAssetType;
import au.com.woolworths.rewards.graphql.type.EverydayExtraButton;
import au.com.woolworths.rewards.graphql.type.EverydayExtraButtonStyle;
import au.com.woolworths.rewards.graphql.type.EverydayExtraCompareTableColumnHeader;
import au.com.woolworths.rewards.graphql.type.EverydayExtraCompareTableColumnHeadings;
import au.com.woolworths.rewards.graphql.type.EverydayExtraCompareTableLabelRowValue;
import au.com.woolworths.rewards.graphql.type.EverydayExtraCompareTableRow;
import au.com.woolworths.rewards.graphql.type.EverydayExtraCompareTableRowValue;
import au.com.woolworths.rewards.graphql.type.EverydayExtraComparisonSectionItem;
import au.com.woolworths.rewards.graphql.type.EverydayExtraFaqsSectionItem;
import au.com.woolworths.rewards.graphql.type.EverydayExtraFaqsTabSections;
import au.com.woolworths.rewards.graphql.type.EverydayExtraKeyBenefitsSectionItem;
import au.com.woolworths.rewards.graphql.type.EverydayExtraKeyBenefitsTabSections;
import au.com.woolworths.rewards.graphql.type.EverydayExtraLanding;
import au.com.woolworths.rewards.graphql.type.EverydayExtraLandingFooter;
import au.com.woolworths.rewards.graphql.type.EverydayExtraLandingTabs;
import au.com.woolworths.rewards.graphql.type.EverydayExtraTermsAndConditions;
import au.com.woolworths.rewards.graphql.type.GraphQLBoolean;
import au.com.woolworths.rewards.graphql.type.GraphQLID;
import au.com.woolworths.rewards.graphql.type.GraphQLInt;
import au.com.woolworths.rewards.graphql.type.GraphQLString;
import au.com.woolworths.rewards.graphql.type.Query;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/feature/rewards/everydayextras/signup/selections/EverydayExtrasLandingQuerySelections;", "", "everyday-extras-sign-up_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class EverydayExtrasLandingQuerySelections {
    public static final List A;
    public static final List B;
    public static final List C;
    public static final List D;
    public static final List E;
    public static final List F;
    public static final List G;
    public static final List H;
    public static final List I;
    public static final List J;
    public static final List K;
    public static final List L;

    /* renamed from: a, reason: collision with root package name */
    public static final List f6215a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        DownloadableAssetType.e.getClass();
        CompiledField compiledFieldC = new CompiledField.Builder("assetType", CompiledGraphQL.b(DownloadableAssetType.f)).c();
        CustomScalarType customScalarType = GraphQLString.f9617a;
        CompiledField compiledFieldC2 = new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLInt.f9616a;
        CompiledField compiledFieldC3 = new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType2)).c();
        DownloadableAssetFit.e.getClass();
        List listR = CollectionsKt.R(compiledFieldC, compiledFieldC2, compiledFieldC3, compiledFieldC4, new CompiledField.Builder("fit", DownloadableAssetFit.f).c(), d.g("altText", customScalarType));
        f6215a = listR;
        List listR2 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        b = listR2;
        List listR3 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c());
        c = listR3;
        CompiledField compiledFieldC5 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("TitleTextItem", CollectionsKt.Q("TitleTextItem"));
        builder.d = listR2;
        CompiledFragment compiledFragmentA = builder.a();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("MediumIconListItem", CollectionsKt.Q("MediumIconListItem"));
        builder2.d = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC5, compiledFragmentA, builder2.a());
        d = listR4;
        CompiledField.Builder builder3 = new CompiledField.Builder("items", d.j(EverydayExtraKeyBenefitsSectionItem.f9537a));
        builder3.e = listR4;
        List listQ = CollectionsKt.Q(builder3.c());
        e = listQ;
        List listR5 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        f = listR5;
        List listR6 = CollectionsKt.R(d.g("iconName", customScalarType), d.g(AnnotatedPrivateKey.LABEL, customScalarType));
        g = listR6;
        List listR7 = CollectionsKt.R(d.g("iconName", customScalarType), d.g(AnnotatedPrivateKey.LABEL, customScalarType));
        h = listR7;
        List listR8 = CollectionsKt.R(d.g("iconName", customScalarType), d.g(AnnotatedPrivateKey.LABEL, customScalarType));
        i = listR8;
        ObjectType objectType = EverydayExtraCompareTableColumnHeader.f9523a;
        CompiledField.Builder builder4 = new CompiledField.Builder("labelColumn", CompiledGraphQL.b(objectType));
        builder4.e = listR6;
        CompiledField compiledFieldC6 = builder4.c();
        CompiledField.Builder builder5 = new CompiledField.Builder("rewardsColumn", CompiledGraphQL.b(objectType));
        builder5.e = listR7;
        CompiledField compiledFieldC7 = builder5.c();
        CompiledField.Builder builder6 = new CompiledField.Builder("extraColumn", CompiledGraphQL.b(objectType));
        builder6.e = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC6, compiledFieldC7, builder6.c());
        j = listR9;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c());
        k = listQ2;
        List listR10 = CollectionsKt.R(d.g("iconName", customScalarType), d.g(AnnotatedPrivateKey.LABEL, customScalarType));
        l = listR10;
        List listR11 = CollectionsKt.R(d.g("iconName", customScalarType), d.g(AnnotatedPrivateKey.LABEL, customScalarType));
        m = listR11;
        CompiledField compiledFieldC8 = new CompiledField.Builder("rowId", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC9 = new CompiledField.Builder("altBackground", CompiledGraphQL.b(GraphQLBoolean.f9613a)).c();
        CompiledField.Builder builder7 = new CompiledField.Builder("labelValue", a.f(EverydayExtraCompareTableLabelRowValue.f9525a));
        builder7.e = listQ2;
        CompiledField compiledFieldC10 = builder7.c();
        ObjectType objectType2 = EverydayExtraCompareTableRowValue.f9527a;
        CompiledField.Builder builder8 = new CompiledField.Builder("rewardsValue", CompiledGraphQL.a(objectType2));
        builder8.e = listR10;
        CompiledField compiledFieldC11 = builder8.c();
        CompiledField.Builder builder9 = new CompiledField.Builder("extraValue", a.f(objectType2));
        builder9.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC8, compiledFieldC9, compiledFieldC10, compiledFieldC11, builder9.c());
        n = listR12;
        CompiledField compiledFieldC12 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder10 = new CompiledField.Builder("columnHeadings", CompiledGraphQL.b(EverydayExtraCompareTableColumnHeadings.f9524a));
        builder10.e = listR9;
        CompiledField compiledFieldC13 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("rows", a.f(EverydayExtraCompareTableRow.f9526a));
        builder11.e = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC12, compiledFieldC13, builder11.c());
        o = listR13;
        CompiledField compiledFieldC14 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("TitleTextItem", CollectionsKt.Q("TitleTextItem"));
        builder12.d = listR5;
        CompiledFragment compiledFragmentA2 = builder12.a();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("EverydayExtraBenefitsCompare", CollectionsKt.Q("EverydayExtraBenefitsCompare"));
        builder13.d = listR13;
        List listR14 = CollectionsKt.R(compiledFieldC14, compiledFragmentA2, builder13.a());
        p = listR14;
        CompiledField.Builder builder14 = new CompiledField.Builder("items", d.j(EverydayExtraComparisonSectionItem.f9529a));
        builder14.e = listR14;
        List listQ3 = CollectionsKt.Q(builder14.c());
        q = listQ3;
        CompiledField compiledFieldC15 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("EverydayExtraKeyBenefitsSection", CollectionsKt.Q("EverydayExtraKeyBenefitsSection"));
        builder15.d = listQ;
        CompiledFragment compiledFragmentA3 = builder15.a();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("EverydayExtraComparisonSection", CollectionsKt.Q("EverydayExtraComparisonSection"));
        builder16.d = listQ3;
        List listR15 = CollectionsKt.R(compiledFieldC15, compiledFragmentA3, builder16.a());
        r = listR15;
        CustomScalarType customScalarType3 = GraphQLID.f9615a;
        CompiledField compiledFieldC16 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType3)).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("tabName", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder17 = new CompiledField.Builder("sections", d.j(EverydayExtraKeyBenefitsTabSections.f9539a));
        builder17.e = listR15;
        List listR16 = CollectionsKt.R(compiledFieldC16, compiledFieldC17, builder17.c());
        s = listR16;
        List listQ4 = CollectionsKt.Q(new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        t = listQ4;
        List listQ5 = CollectionsKt.Q(new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        u = listQ5;
        DividerType.e.getClass();
        List listQ6 = CollectionsKt.Q(new CompiledField.Builder("type", CompiledGraphQL.b(DividerType.f)).c());
        v = listQ6;
        List listR17 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("question", CompiledGraphQL.b(customScalarType)).c(), d.g("markdownAnswer", customScalarType));
        w = listR17;
        List listQ7 = CollectionsKt.Q(new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        x = listQ7;
        CompiledField compiledFieldC18 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("TitleTextItem", CollectionsKt.Q("TitleTextItem"));
        builder18.d = listQ4;
        CompiledFragment compiledFragmentA4 = builder18.a();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("SubheadTextItem", CollectionsKt.Q("SubheadTextItem"));
        builder19.d = listQ5;
        CompiledFragment compiledFragmentA5 = builder19.a();
        CompiledFragment.Builder builder20 = new CompiledFragment.Builder("Divider", CollectionsKt.Q("Divider"));
        builder20.d = listQ6;
        CompiledFragment compiledFragmentA6 = builder20.a();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("FaqItem", CollectionsKt.Q("FaqItem"));
        builder21.d = listR17;
        CompiledFragment compiledFragmentA7 = builder21.a();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("NoteTextItem", CollectionsKt.Q("NoteTextItem"));
        builder22.d = listQ7;
        List listR18 = CollectionsKt.R(compiledFieldC18, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, builder22.a());
        y = listR18;
        CompiledField.Builder builder23 = new CompiledField.Builder("items", d.j(EverydayExtraFaqsSectionItem.f9531a));
        builder23.e = listR18;
        List listQ8 = CollectionsKt.Q(builder23.c());
        z = listQ8;
        CompiledField compiledFieldC19 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder24 = new CompiledFragment.Builder("EverydayExtraFaqsSection", CollectionsKt.Q("EverydayExtraFaqsSection"));
        builder24.d = listQ8;
        List listR19 = CollectionsKt.R(compiledFieldC19, builder24.a());
        A = listR19;
        CompiledField compiledFieldC20 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType3)).c();
        CompiledField compiledFieldC21 = new CompiledField.Builder("tabName", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder25 = new CompiledField.Builder("sections", d.j(EverydayExtraFaqsTabSections.f9533a));
        builder25.e = listR19;
        List listR20 = CollectionsKt.R(compiledFieldC20, compiledFieldC21, builder25.c());
        B = listR20;
        CompiledField compiledFieldC22 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("EverydayExtraKeyBenefitsTab", CollectionsKt.Q("EverydayExtraKeyBenefitsTab"));
        builder26.d = listR16;
        CompiledFragment compiledFragmentA8 = builder26.a();
        CompiledFragment.Builder builder27 = new CompiledFragment.Builder("EverydayExtraFaqsTab", CollectionsKt.Q("EverydayExtraFaqsTab"));
        builder27.d = listR20;
        List listR21 = CollectionsKt.R(compiledFieldC22, compiledFragmentA8, builder27.a());
        C = listR21;
        List listR22 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("termsAndConditions", CompiledGraphQL.b(customScalarType)).c());
        D = listR22;
        CompiledField compiledFieldC23 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC24 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC25 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g("actionUrl", customScalarType);
        EverydayExtraButtonStyle.e.getClass();
        List listR23 = CollectionsKt.R(compiledFieldC23, compiledFieldC24, compiledFieldC25, compiledFieldG, new CompiledField.Builder("style", EverydayExtraButtonStyle.f).c());
        E = listR23;
        CompiledField compiledFieldC26 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC27 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType3)).c();
        CompiledField.Builder builder28 = new CompiledField.Builder("items", a.f(EverydayExtraButton.f9517a));
        builder28.e = listR23;
        List listR24 = CollectionsKt.R(compiledFieldC26, compiledFieldC27, builder28.c());
        F = listR24;
        List listR25 = CollectionsKt.R(new CompiledField.Builder("eventCategory", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("eventDescription", CompiledGraphQL.b(customScalarType)).c());
        G = listR25;
        List listR26 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        H = listR26;
        List listR27 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        I = listR27;
        CompiledField compiledFieldC28 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC29 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder29 = new CompiledField.Builder("analytics", AlertDialogAnalytics.f9419a);
        builder29.e = listR25;
        CompiledField compiledFieldC30 = builder29.c();
        ObjectType objectType3 = ContentCta.f9485a;
        CompiledField.Builder builder30 = new CompiledField.Builder("primaryCta", CompiledGraphQL.b(objectType3));
        builder30.e = listR26;
        CompiledField compiledFieldC31 = builder30.c();
        CompiledField.Builder builder31 = new CompiledField.Builder("secondaryCta", objectType3);
        builder31.e = listR27;
        List listR28 = CollectionsKt.R(compiledFieldC28, compiledFieldC29, compiledFieldC30, compiledFieldC31, builder31.c());
        J = listR28;
        CompiledField compiledFieldC32 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC33 = new CompiledField.Builder("navigationTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder32 = new CompiledField.Builder("header", CompiledGraphQL.b(DownloadableAsset.f9500a));
        builder32.e = listR;
        CompiledField compiledFieldC34 = builder32.c();
        CompiledField.Builder builder33 = new CompiledField.Builder("tabs", d.j(EverydayExtraLandingTabs.f9543a));
        builder33.e = listR21;
        CompiledField compiledFieldC35 = builder33.c();
        CompiledField.Builder builder34 = new CompiledField.Builder("termsAndConditions", EverydayExtraTermsAndConditions.f9561a);
        builder34.e = listR22;
        CompiledField compiledFieldC36 = builder34.c();
        CompiledField.Builder builder35 = new CompiledField.Builder("footer", EverydayExtraLandingFooter.f9542a);
        builder35.e = listR24;
        CompiledField compiledFieldC37 = builder35.c();
        CompiledField.Builder builder36 = new CompiledField.Builder("alertDialog", AlertDialog.f9418a);
        builder36.e = listR28;
        List listR29 = CollectionsKt.R(compiledFieldC32, compiledFieldC33, compiledFieldC34, compiledFieldC35, compiledFieldC36, compiledFieldC37, builder36.c());
        K = listR29;
        CompiledField.Builder builder37 = new CompiledField.Builder("everydayExtraLanding", EverydayExtraLanding.f9540a);
        new CompiledArgument.Builder(Query.f);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.g);
        builder37.d = CollectionsKt.R(compiledArgument, new CompiledArgument());
        builder37.e = listR29;
        L = CollectionsKt.Q(builder37.c());
    }
}
