package com.google.android.gms.internal.ads;

import android.app.Activity;
import android.content.Context;
import android.view.View;
import java.util.Map;

/* loaded from: classes5.dex */
final class zzfuv implements zzfxr {
    private final zzfun zzA;
    private final zzfut zzB;
    final zzhqg zza;
    final zzhqg zzb;
    final zzhqg zzc;
    final zzhqg zzd;
    final zzhqg zze;
    final zzhqg zzf;
    final zzhqg zzg;
    final zzhqg zzh;
    final zzhqg zzi;
    final zzhqg zzj;
    final zzhqg zzk;
    final zzhqg zzl;
    final zzhqg zzm;
    final zzhqg zzn;
    final zzhqg zzo;
    final zzhqg zzp;
    final zzhqg zzq;
    final zzhqg zzr;
    final zzhqg zzs;
    final zzhqg zzt;
    final zzhqg zzu;
    final zzhqg zzv;
    final zzhqg zzw;
    final zzhqg zzx;
    final zzhqg zzy;
    final zzhqg zzz;

    public zzfuv(zzfun zzfunVar, zzfut zzfutVar, Context context, View view, Activity activity, String str, Map map, zzarw zzarwVar, zzfvd zzfvdVar) {
        this.zzA = zzfunVar;
        this.zzB = zzfutVar;
        zzhpx zzhpxVarZza = zzhpy.zza(zzfvdVar);
        this.zza = zzhpxVarZza;
        zzhpx zzhpxVarZzc = zzhpy.zzc(str);
        this.zzb = zzhpxVarZzc;
        zzhpx zzhpxVarZza2 = zzhpy.zza(zzarwVar);
        this.zzc = zzhpxVarZza2;
        zzhqg zzhqgVar = zzfutVar.zzb;
        zzhqg zzhqgVar2 = zzfunVar.zza;
        zzhqg zzhqgVar3 = zzfunVar.zzp;
        zzfzc zzfzcVarZza = zzfzc.zza(zzhpxVarZza2, zzhqgVar, zzhqgVar2, zzhqgVar3);
        this.zzd = zzfzcVarZza;
        zzfza zzfzaVarZza = zzfza.zza(zzhpxVarZza2, zzhqgVar, zzhqgVar3);
        this.zze = zzfzaVarZza;
        zzhpx zzhpxVarZza3 = zzhpy.zza(map);
        this.zzf = zzhpxVarZza3;
        zzhqg zzhqgVar4 = zzfutVar.zzb;
        zzhqg zzhqgVar5 = zzfunVar.zzp;
        zzfzi zzfziVarZza = zzfzi.zza(zzhpxVarZza2, zzhqgVar4, zzhpxVarZza3, zzhqgVar5);
        this.zzg = zzfziVarZza;
        zzfze zzfzeVarZza = zzfze.zza(zzhpxVarZza2, zzhqgVar4, zzfunVar.zzg, zzhqgVar5);
        this.zzh = zzfzeVarZza;
        zzfzs zzfzsVarZza = zzfzs.zza(zzhpxVarZza2, zzhqgVar4, zzhpxVarZza, zzhpxVarZza3, zzhqgVar5);
        this.zzi = zzfzsVarZza;
        zzfzg zzfzgVarZza = zzfzg.zza(zzhpxVarZza2, zzhqgVar4, zzhqgVar5);
        this.zzj = zzfzgVarZza;
        zzhpx zzhpxVarZza4 = zzhpy.zza(context);
        this.zzk = zzhpxVarZza4;
        zzhqg zzhqgVar6 = zzfutVar.zzb;
        zzhqg zzhqgVar7 = zzfunVar.zzp;
        zzfzo zzfzoVarZza = zzfzo.zza(zzhpxVarZza2, zzhqgVar6, zzhpxVarZza, zzhpxVarZza4, zzhpxVarZza3, zzhqgVar7);
        this.zzl = zzfzoVarZza;
        zzhqg zzhqgVar8 = zzfunVar.zza;
        zzhqg zzhqgVar9 = zzfunVar.zzg;
        zzfyy zzfyyVarZza = zzfyy.zza(zzhpxVarZza2, zzhqgVar6, zzhpxVarZza3, zzhqgVar8, zzhpxVarZza, zzhqgVar9, zzhqgVar7);
        this.zzm = zzfyyVarZza;
        zzfzk zzfzkVarZza = zzfzk.zza(zzhpxVarZza2, zzhqgVar6, zzhqgVar8, zzhqgVar7);
        this.zzn = zzfzkVarZza;
        zzfzm zzfzmVarZza = zzfzm.zza(zzhpxVarZza2, zzhqgVar6, zzhpxVarZza3, zzhqgVar8, zzhqgVar7);
        this.zzo = zzfzmVarZza;
        zzfyw zzfywVarZza = zzfyw.zza(zzhpxVarZza2, zzhpxVarZza3, zzhqgVar9, zzhqgVar7);
        this.zzp = zzfywVarZza;
        zzhqi zzhqiVarZza = zzhqj.zza(11, 0);
        zzhqiVarZza.zza(zzfzcVarZza);
        zzhqiVarZza.zza(zzfzaVarZza);
        zzhqiVarZza.zza(zzfziVarZza);
        zzhqiVarZza.zza(zzfzeVarZza);
        zzhqiVarZza.zza(zzfzsVarZza);
        zzhqiVarZza.zza(zzfzgVarZza);
        zzhqiVarZza.zza(zzfzoVarZza);
        zzhqiVarZza.zza(zzfyyVarZza);
        zzhqiVarZza.zza(zzfzkVarZza);
        zzhqiVarZza.zza(zzfzmVarZza);
        zzhqiVarZza.zza(zzfywVarZza);
        zzhqj zzhqjVarZzc = zzhqiVarZza.zzc();
        this.zzq = zzhqjVarZzc;
        zzhpx zzhpxVarZzc2 = zzhpy.zzc(view);
        this.zzr = zzhpxVarZzc2;
        zzhpx zzhpxVarZzc3 = zzhpy.zzc(activity);
        this.zzs = zzhpxVarZzc3;
        zzhqg zzhqgVar10 = zzfutVar.zzb;
        zzhqg zzhqgVar11 = zzfunVar.zzp;
        zzfyu zzfyuVarZza = zzfyu.zza(zzhpxVarZza2, zzhqgVar10, zzhpxVarZzc2, zzhpxVarZzc3, zzhqgVar11);
        this.zzt = zzfyuVarZza;
        zzhqg zzhqgVarZza = zzhpw.zza(zzfxs.zza(zzhpxVarZza4));
        this.zzu = zzhqgVarZza;
        zzfzw zzfzwVarZza = zzfzw.zza(zzhpxVarZza2, zzhqgVar10, zzhqgVarZza, zzhpxVarZzc2, zzhqgVar11);
        this.zzv = zzfzwVarZza;
        zzhqi zzhqiVarZza2 = zzhqj.zza(11, 0);
        zzhqiVarZza2.zza(zzfzcVarZza);
        zzhqiVarZza2.zza(zzfzaVarZza);
        zzhqiVarZza2.zza(zzfzeVarZza);
        zzhqiVarZza2.zza(zzfyuVarZza);
        zzhqiVarZza2.zza(zzfzwVarZza);
        zzhqiVarZza2.zza(zzfzsVarZza);
        zzhqiVarZza2.zza(zzfzgVarZza);
        zzhqiVarZza2.zza(zzfzoVarZza);
        zzhqiVarZza2.zza(zzfyyVarZza);
        zzhqiVarZza2.zza(zzfzkVarZza);
        zzhqiVarZza2.zza(zzfzmVarZza);
        zzhqj zzhqjVarZzc2 = zzhqiVarZza2.zzc();
        this.zzw = zzhqjVarZzc2;
        zzfzu zzfzuVarZza = zzfzu.zza(zzhpxVarZza2, zzfutVar.zzb, zzhpxVarZza3, zzhqgVarZza, zzfunVar.zzp);
        this.zzx = zzfzuVarZza;
        zzhqi zzhqiVarZza3 = zzhqj.zza(12, 0);
        zzhqiVarZza3.zza(zzfzcVarZza);
        zzhqiVarZza3.zza(zzfzaVarZza);
        zzhqiVarZza3.zza(zzfzeVarZza);
        zzhqiVarZza3.zza(zzfyuVarZza);
        zzhqiVarZza3.zza(zzfzwVarZza);
        zzhqiVarZza3.zza(zzfzsVarZza);
        zzhqiVarZza3.zza(zzfzgVarZza);
        zzhqiVarZza3.zza(zzfzoVarZza);
        zzhqiVarZza3.zza(zzfyyVarZza);
        zzhqiVarZza3.zza(zzfzkVarZza);
        zzhqiVarZza3.zza(zzfzmVarZza);
        zzhqiVarZza3.zza(zzfzuVarZza);
        zzhqj zzhqjVarZzc3 = zzhqiVarZza3.zzc();
        this.zzy = zzhqjVarZzc3;
        this.zzz = zzhpw.zza(zzfxp.zza(zzfunVar.zzs, zzfunVar.zzC, zzfutVar.zzb, zzhpxVarZza, zzhpxVarZzc, zzhpxVarZza2, zzhqjVarZzc, zzhqjVarZzc2, zzhqjVarZzc3, zzfunVar.zzp));
    }

    @Override // com.google.android.gms.internal.ads.zzfxr
    public final zzfxo zza() {
        return (zzfxo) this.zzz.zzb();
    }
}
