package au.com.woolworths.feature.shop.editorder.review.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.shop.graphql.type.ActionTile;
import au.com.woolworths.shop.graphql.type.BasicCoreBroadcastBanner;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.ChangeMyOrderDetailsSection;
import au.com.woolworths.shop.graphql.type.ChangeMyOrderDetailsSectionItems;
import au.com.woolworths.shop.graphql.type.ChangeMyOrderSummary;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerUI;
import au.com.woolworths.shop.graphql.type.FooterCTASection;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.IconAsset;
import au.com.woolworths.shop.graphql.type.TextWithAlt;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/feature/shop/editorder/review/selections/ChangeMyOrderSummaryQuerySelections;", "", "edit-order_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class ChangeMyOrderSummaryQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f7130a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        f7130a = listQ;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder.d = listQ;
        List listR = CollectionsKt.R(compiledFieldC, builder.a());
        b = listR;
        CompiledField compiledFieldC2 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CoreBroadcastBannerStyle.e.getClass();
        CompiledField compiledFieldC3 = new CompiledField.Builder("style", CompiledGraphQL.b(CoreBroadcastBannerStyle.f)).c();
        CompiledField.Builder builder2 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(IconAsset.f11477a));
        builder2.e = listR;
        List listR2 = CollectionsKt.R(compiledFieldC2, compiledFieldG, compiledFieldC3, builder2.c());
        c = listR2;
        CompiledField.Builder builder3 = new CompiledField.Builder("broadcastBannerUI", CompiledGraphQL.b(CoreBroadcastBannerUI.f11286a));
        builder3.e = listR2;
        List listQ2 = CollectionsKt.Q(builder3.c());
        d = listQ2;
        List listR3 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType), new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c());
        e = listR3;
        List listR4 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType), new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c());
        f = listR4;
        List listR5 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        g = listR5;
        CompiledField.Builder builder4 = new CompiledField.Builder("fulfilmentTimeSlotTitle", CompiledGraphQL.b(TextWithAlt.f11967a));
        builder4.e = listR5;
        List listR6 = CollectionsKt.R(builder4.c(), d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType), new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c());
        h = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c());
        i = listR7;
        CompiledField compiledFieldC4 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG2 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField compiledFieldC5 = new CompiledField.Builder("numberOfItems", CompiledGraphQL.b(GraphQLInt.f11442a)).c();
        CompiledField.Builder builder5 = new CompiledField.Builder("actionTiles", a.f(ActionTile.f10999a));
        builder5.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC4, compiledFieldG2, compiledFieldC5, builder5.c());
        j = listR8;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("FulfilmentMethod", CollectionsKt.Q("FulfilmentMethod"));
        builder6.d = listR3;
        CompiledFragment compiledFragmentA = builder6.a();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("ChangeMyOrderDeliveryInstructions", CollectionsKt.Q("ChangeMyOrderDeliveryInstructions"));
        builder7.d = listR4;
        CompiledFragment compiledFragmentA2 = builder7.a();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("FulfilmentTimeSlot", CollectionsKt.Q("FulfilmentTimeSlot"));
        builder8.d = listR6;
        CompiledFragment compiledFragmentA3 = builder8.a();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("CartActions", CollectionsKt.Q("CartActions"));
        builder9.d = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC6, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, builder9.a());
        k = listR9;
        CompiledField compiledFieldC7 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG3 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField.Builder builder10 = new CompiledField.Builder("items", d.j(ChangeMyOrderDetailsSectionItems.f11176a));
        builder10.e = listR9;
        List listR10 = CollectionsKt.R(compiledFieldC7, compiledFieldG3, builder10.c());
        l = listR10;
        CompiledField compiledFieldG4 = d.g("buttonId", customScalarType);
        CompiledField compiledFieldC8 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        ButtonStyle.e.getClass();
        EnumType enumType = ButtonStyle.f;
        CompiledField compiledFieldC9 = new CompiledField.Builder("style", enumType).c();
        CustomScalarType customScalarType2 = GraphQLBoolean.f11439a;
        List listR11 = CollectionsKt.R(compiledFieldG4, compiledFieldC8, compiledFieldC9, new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType2)).c());
        m = listR11;
        List listR12 = CollectionsKt.R(d.g("buttonId", customScalarType), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), a.d("style", enumType), new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType2)).c());
        n = listR12;
        ObjectType objectType = Button.f11080a;
        CompiledField.Builder builder11 = new CompiledField.Builder("cancelButton", CompiledGraphQL.b(objectType));
        builder11.e = listR11;
        CompiledField compiledFieldC10 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("checkoutButton", CompiledGraphQL.b(objectType));
        builder12.e = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC10, builder12.c());
        o = listR13;
        CompiledField.Builder builder13 = new CompiledField.Builder("banner", BasicCoreBroadcastBanner.f11044a);
        builder13.e = listQ2;
        CompiledField compiledFieldC11 = builder13.c();
        CompiledField.Builder builder14 = new CompiledField.Builder("orderDetailsSection", CompiledGraphQL.b(ChangeMyOrderDetailsSection.f11175a));
        builder14.e = listR10;
        CompiledField compiledFieldC12 = builder14.c();
        CompiledField.Builder builder15 = new CompiledField.Builder("footerCTASection", CompiledGraphQL.b(FooterCTASection.f11396a));
        builder15.e = listR13;
        List listR14 = CollectionsKt.R(compiledFieldC11, compiledFieldC12, builder15.c());
        p = listR14;
        CompiledField.Builder builder16 = new CompiledField.Builder("changeMyOrderSummary", CompiledGraphQL.b(ChangeMyOrderSummary.f11177a));
        builder16.e = listR14;
        q = CollectionsKt.Q(builder16.c());
    }
}
