package au.com.woolworths.analytics.model;

import com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView;
import com.google.android.gms.dynamite.descriptors.com.google.android.gms.measurement.dynamite.ModuleDescriptor;
import com.google.apphosting.datastore.testing.DatastoreTestTrace;
import kotlin.Metadata;
import kotlin.enums.EnumEntries;
import kotlin.enums.EnumEntriesKt;
import org.bouncycastle.asn1.BERTags;
import org.bouncycastle.math.Primes;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0010\n\u0000\b\u0086\u0081\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00000\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/analytics/model/TrackableValue;", "", "model_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes.dex */
public final class TrackableValue {
    public static final /* synthetic */ TrackableValue[] Z3;
    public static final /* synthetic */ EnumEntries a4;
    public final String d;
    public static final TrackableValue e = new TrackableValue("ACS_ADOBE_ECID", 0, "adobe.ECID");
    public static final TrackableValue f = new TrackableValue("ACS_ADOBE_PE", 1, "adobe.pe");
    public static final TrackableValue g = new TrackableValue("ACS_ADOBE_TNTA", 2, "adobe.tnta");
    public static final TrackableValue h = new TrackableValue("ACS_DETAIL_ID", 3, "acs.GAMDetailId");
    public static final TrackableValue i = new TrackableValue("ACS_STITCH_ID", 4, "acs.StitchID");
    public static final TrackableValue j = new TrackableValue("ACTIVITY_EMPTY_STATE", 5, "user.RewardsActivity");
    public static final TrackableValue k = new TrackableValue("APP_SECTION", 6, "app.Section");
    public static final TrackableValue l = new TrackableValue("ARTICLE_ID", 7, "product.ID");
    public static final TrackableValue m = new TrackableValue("BANNER_ID", 8, "banner.BannerID");
    public static final TrackableValue n = new TrackableValue("BANNER_NAME", 9, "banner.Name");
    public static final TrackableValue o = new TrackableValue("BAY_SELECTOR_BAY_NUMBER", 10, "baySelector.bayNumber");
    public static final TrackableValue p = new TrackableValue("CAMPAIGN_ID", 11, "campaign.ID");
    public static final TrackableValue q = new TrackableValue("CAROUSEL_LABEL", 12, "carousel.Label");
    public static final TrackableValue r = new TrackableValue("CAROUSEL_PAGE", 13, "carousel.Page");
    public static final TrackableValue s = new TrackableValue("CART_TOTAL_ITEMS", 14, "digitalData.cart.totalItems");
    public static final TrackableValue t = new TrackableValue("CART_TOTAL_SAVINGS", 15, "cart.TotalSavings");
    public static final TrackableValue u = new TrackableValue("CART_TOTAL_VALUE", 16, "cart.TotalValue");
    public static final TrackableValue v = new TrackableValue("CATALOGUE_AREA_CODE", 17, "catalogue.AreaCode");
    public static final TrackableValue w = new TrackableValue("CATALOGUE_END_DATE", 18, "catalogue.EndDate");
    public static final TrackableValue x = new TrackableValue("CATALOGUE_ID", 19, "catalogue.ID");
    public static final TrackableValue y = new TrackableValue("CATALOGUE_OFFER_VALIDITY", 20, "catalogue.OfferValidity");
    public static final TrackableValue z = new TrackableValue("CATALOGUE_POSTCODE", 21, "digitalData.catalogue.postcode");
    public static final TrackableValue A = new TrackableValue("CATALOGUE_PRODUCT_ID", 22, "catalogue.ProductID");
    public static final TrackableValue B = new TrackableValue("CATALOGUE_PRODUCT_NAME", 23, "catalogue.ProductName");
    public static final TrackableValue C = new TrackableValue("CATALOGUE_PRODUCT_SKU", 24, "digitalData.catalogue.product.SKU");
    public static final TrackableValue D = new TrackableValue("CATALOGUE_PRODUCT_URL", 25, "digitalData.catalogue.product.url");
    public static final TrackableValue E = new TrackableValue("CATALOGUE_PUBLISH_DATE", 26, "catalogue.PublishDate");
    public static final TrackableValue F = new TrackableValue("CATALOGUE_SALE_NAME", 27, "digitalData.catalogue.saleName");
    public static final TrackableValue G = new TrackableValue("CATALOGUE_START_DATE", 28, "catalogue.StartDate");
    public static final TrackableValue H = new TrackableValue("CATALOGUE_STATE", 29, "catalogue.State");
    public static final TrackableValue I = new TrackableValue("CATALOGUE_STORE_ID", 30, "catalogue.StoreID");
    public static final TrackableValue J = new TrackableValue("CATALOGUE_TYPE", 31, "catalogue.Type");
    public static final TrackableValue K = new TrackableValue("CHANGE_MY_ORDER_EDIT_MODE", 32, "user.ChangeMyOrderEditMode");
    public static final TrackableValue L = new TrackableValue("CHECKOUT_COLLECTION_METHOD", 33, "checkout.CollectionMethod");
    public static final TrackableValue M = new TrackableValue("CHECKOUT_DISCOUNT_TOTAL", 34, "checkout.DiscountTotal");
    public static final TrackableValue N = new TrackableValue("CHECKOUT_PACKAGING_TYPE", 35, "digitalData.checkout.packagingType");
    public static final TrackableValue O = new TrackableValue("CHECKOUT_STEP_NUMBER", 36, "digitalData.checkout.stepNumber");
    public static final TrackableValue P = new TrackableValue("CHECKOUT_STEP_TITLE", 37, "digitalData.checkout.stepName");
    public static final TrackableValue Q = new TrackableValue("CHECKOUT_TOTAL", 38, "checkout.Total");
    public static final TrackableValue R = new TrackableValue("CHECKOUT_TOTAL_VALUE", 39, "checkout.TotalValue");
    public static final TrackableValue S = new TrackableValue("CHECKOUT_WINDOW_DURATION", 40, "checkout.WindowDuration");
    public static final TrackableValue T = new TrackableValue("CHECKOUT_WINDOW_END_TIME", 41, "checkout.CollectionEndTime");
    public static final TrackableValue U = new TrackableValue("CHECKOUT_WINDOW_LABEL", 42, "window.label");
    public static final TrackableValue V = new TrackableValue("CHECKOUT_WINDOW_PRICE", 43, "checkout.WindowPrice");
    public static final TrackableValue W = new TrackableValue("CHECKOUT_WINDOW_START_TIME", 44, "checkout.CollectionStartTime");
    public static final TrackableValue X = new TrackableValue("CHECKOUT_WINDOWS", 45, "digitalData.checkout.windowsDisplayed");
    public static final TrackableValue Y = new TrackableValue("CHECKOUT_WINDOWS_SELECTED_PERIOD", 46, "checkout.SelectedTime");
    public static final TrackableValue Z = new TrackableValue("CHECKOUT_WINDOWS_SIZE", 47, "checkout.WindowsDisplayed");
    public static final TrackableValue a0 = new TrackableValue("COLLECTION_DATE", 48, "checkout.CollectionDate");
    public static final TrackableValue b0 = new TrackableValue("COLLECTION_FEE", 49, "order.CollectionFee");
    public static final TrackableValue c0 = new TrackableValue("COLLECTION_MIN_PRICE", 50, "checkout.MinPrice");
    public static final TrackableValue d0 = new TrackableValue("COLLECTION_STATE", 51, "digitalData.checkout.collectionState");
    public static final TrackableValue e0 = new TrackableValue("COLLECTION_SUBURB", 52, "digitalData.checkout.collectionSuburb");
    public static final TrackableValue f0 = new TrackableValue("COMPONENT_IMPRESSIONS", 53, "component.Impressions");
    public static final TrackableValue g0 = new TrackableValue("DEEPLINK_IS_DEEPLINK", 54, "deeplink.IsDeeplink");
    public static final TrackableValue h0 = new TrackableValue("DEEPLINK_URI", 55, "deeplink.uri");
    public static final TrackableValue i0 = new TrackableValue("DISCOUNT_TOTAL", 56, "order.DiscountTotal");
    public static final TrackableValue j0 = new TrackableValue("EDR_LINKED", 57, "user.EDR");
    public static final TrackableValue k0 = new TrackableValue("ERROR_NAME", 58, "error.Name");
    public static final TrackableValue l0 = new TrackableValue("ERROR_REASON", 59, "error.Reason");
    public static final TrackableValue m0 = new TrackableValue("EVENT_ACTION", 60, "event.Action");
    public static final TrackableValue n0 = new TrackableValue("EVENT_CATEGORY", 61, "event.Category");
    public static final TrackableValue o0 = new TrackableValue("EVENT_DESCRIPTION", 62, "event.Description");
    public static final TrackableValue p0 = new TrackableValue("EVENT_LABEL", 63, "event.Label");
    public static final TrackableValue q0 = new TrackableValue("EVENT_VALUE", 64, "event.Value");
    public static final TrackableValue r0 = new TrackableValue("EXPRESS_DELIVERY_STORE_ID", 65, "expressDelivery.StoreId");
    public static final TrackableValue s0 = new TrackableValue("EXPRESS_DELIVERY_WINDOW_STATUS", 66, "expressDelivery.WindowStatus");
    public static final TrackableValue t0 = new TrackableValue("EXPRESS_FLAG", 67, "user.ExpressFlag");
    public static final TrackableValue u0 = new TrackableValue("FEATURE_VARIANT", 68, "feature.Variant");
    public static final TrackableValue v0 = new TrackableValue("FILTER_ID", 69, "productList.FilterID");
    public static final TrackableValue w0 = new TrackableValue("HAS_BANK_CARD", 70, "user.hasBankCard");
    public static final TrackableValue x0 = new TrackableValue("HOMEPAGE_LOAD_STATUS", 71, "event.Status");
    public static final TrackableValue y0 = new TrackableValue("HORIZONTAL_LIST_ACTION_TITLE", 72, "digitalData.horizontallist.actionTitle");
    public static final TrackableValue z0 = new TrackableValue("HORIZONTAL_LIST_TITLE", 73, "digitalData.horizontallist.title");
    public static final TrackableValue A0 = new TrackableValue("INGREDIENT_AVAILABILITY", 74, "ingredient.Availability");
    public static final TrackableValue B0 = new TrackableValue("INGREDIENT_NAME", 75, "ingredient.Name");
    public static final TrackableValue C0 = new TrackableValue("INSET_BANNER_MESSAGE", 76, "banner.Message");
    public static final TrackableValue D0 = new TrackableValue("INSTORE_PRESENCE_DETAILS", 77, "user.location");
    public static final TrackableValue E0 = new TrackableValue("INSTORE_WIFI_STORE_DETAILS", 78, "user.wificonnected");
    public static final TrackableValue F0 = new TrackableValue("LIST_DETAILS", 79, "list.details");
    public static final TrackableValue G0 = new TrackableValue("LIST_SELECTION_INDEX", 80, "list.ListPositionNumber");
    public static final TrackableValue H0 = new TrackableValue("LOCATION_PERMISSION_STATUS", 81, "user.PermissionLocation");
    public static final TrackableValue I0 = new TrackableValue("MAGAZINE_ID", 82, "magazine.ID");
    public static final TrackableValue J0 = new TrackableValue("MARKET_ORDER_COUNT", 83, "user.MarketOrderCount");
    public static final TrackableValue K0 = new TrackableValue("OFFER_ACTION", 84, "offer.Action");
    public static final TrackableValue L0 = new TrackableValue("OFFER_CHANNEL", 85, "offer.Channel");
    public static final TrackableValue M0 = new TrackableValue("OFFER_CODE", 86, "offer.Code");
    public static final TrackableValue N0 = new TrackableValue("OFFER_NAME", 87, "offer.Name");
    public static final TrackableValue O0 = new TrackableValue("OFFER_PARTNER_ID", 88, "offer.PartnerID");
    public static final TrackableValue P0 = new TrackableValue("OFFER_PROFILE", 89, "offer.Profile");
    public static final TrackableValue Q0 = new TrackableValue("OFFER_RTL_ACCOUNT_ID", 90, "offer.RTLAccountID");
    public static final TrackableValue R0 = new TrackableValue("OFFER_RTL_CAMPAIGN_CODE", 91, "offer.RTLCampaignCode");
    public static final TrackableValue S0 = new TrackableValue("OFFER_RTL_CAMPAIGN_ID", 92, "offer.RTLCampaignID");
    public static final TrackableValue T0 = new TrackableValue("OFFER_RTL_COUPON_START", 93, "offer.RTLCouponStart");
    public static final TrackableValue U0 = new TrackableValue("OFFER_STATUS", 94, "offer.Status");
    public static final TrackableValue V0 = new TrackableValue("OFFER_STREAM", 95, "offer.Stream");
    public static final TrackableValue W0 = new TrackableValue("OFFER_TYPE", 96, "offer.Type");
    public static final TrackableValue X0 = new TrackableValue("OFFER_UOID", 97, "offer.UOID");
    public static final TrackableValue Y0 = new TrackableValue("OFFER_UUID", 98, "offer.UUID");
    public static final TrackableValue Z0 = new TrackableValue("ONBOARDING_CONTENT_VARIANT", 99, "content.TileVariant");
    public static final TrackableValue a1 = new TrackableValue("ONBOARDING_ID", 100, "onboarding.OnboardingID");
    public static final TrackableValue b1 = new TrackableValue("ONBOARDING_SCREEN_VARIANT", 101, "screen.Variant");
    public static final TrackableValue c1 = new TrackableValue("ORDER_COLLECTION_METHOD", 102, "order.CollectionMethod");
    public static final TrackableValue d1 = new TrackableValue("ORDER_COUNT", 103, "user.OrderCount");
    public static final TrackableValue e1 = new TrackableValue("ORDER_CROWD_SOURCED_DELIVERY_FLAG", 104, "order.CrowdSourcedDeliveryFlag");
    public static final TrackableValue f1 = new TrackableValue("ORDER_DISCOUNT_SAVINGS_TOTAL", 105, "order.discountSavingsTotal");
    public static final TrackableValue g1 = new TrackableValue("ORDER_FULFILMENT_METHOD", 106, "order.FulfilmentMethod");
    public static final TrackableValue h1 = new TrackableValue("ORDER_ID", 107, "order.ID");
    public static final TrackableValue i1 = new TrackableValue("ORDER_IS_AMENDED", 108, "order.IsAmendedOrder");
    public static final TrackableValue j1 = new TrackableValue("ORDER_LIST", 109, "digitalData.user.profile.openOrderList");
    public static final TrackableValue k1 = new TrackableValue("ORDER_PACKAGING_TYPE", 110, "order.PackagingType");
    public static final TrackableValue l1 = new TrackableValue("ORDER_PROMO_CODE_CREDIT_AMOUNT", 111, "order.promoCodeCreditAmount");
    public static final TrackableValue m1 = new TrackableValue("ORDER_PROMO_CODE_VALUE", 112, "order.promoCodeValue");
    public static final TrackableValue n1 = new TrackableValue("ORDER_REFERENCE", 113, "order.Reference");
    public static final TrackableValue o1 = new TrackableValue("ORDER_REWARDS_CREDIT_USED", 114, "order.RewardsCreditsUsed");
    public static final TrackableValue p1 = new TrackableValue("ORDER_REWARDS_DOLLARS_AMOUNT", 115, "order.rewardsDollarsAmount");
    public static final TrackableValue q1 = new TrackableValue("ORDER_SHIPPING_METHOD", 116, "order.ShippingMethod ");
    public static final TrackableValue r1 = new TrackableValue("ORDER_STATUS", 117, "order.Status");
    public static final TrackableValue s1 = new TrackableValue("ORDER_STATUS_DETAIL", 118, "order.StatusDetail");
    public static final TrackableValue t1 = new TrackableValue("ORDER_STORE_CREDIT_AMOUNT", 119, "order.storeCreditAmount");
    public static final TrackableValue u1 = new TrackableValue("ORDER_STORE_CREDIT_CODE", 120, "order.storeCreditCode");
    public static final TrackableValue v1 = new TrackableValue("ORDER_SUBSCRIPTION_TYPE", 121, "order.SubscriptionType");
    public static final TrackableValue w1 = new TrackableValue("ORDER_SUBTOTAL", 122, "order.SubTotal");
    public static final TrackableValue x1 = new TrackableValue("ORDER_TOTAL", 123, "order.Total");
    public static final TrackableValue y1 = new TrackableValue("ORDER_TOTAL_ITEMS", 124, "order.TotalItems");
    public static final TrackableValue z1 = new TrackableValue("ORDER_TOTAL_VALUE", 125, "order.TotalValue");
    public static final TrackableValue A1 = new TrackableValue("PACKAGING_FEE", 126, "digitalData.checkout.packagingFee");
    public static final TrackableValue B1 = new TrackableValue("PAGE_CATEGORY", 127, "digitalData.page.category");
    public static final TrackableValue C1 = new TrackableValue("PAGE_NUMBER", 128, "page.PageNumber");
    public static final TrackableValue D1 = new TrackableValue("PAGE_VERSION", 129, "page.Version");
    public static final TrackableValue E1 = new TrackableValue("PARTNER_NAME", 130, "partner.Name");
    public static final TrackableValue F1 = new TrackableValue("PARTNER_STORE_NAME", 131, "partner.StoreName");
    public static final TrackableValue G1 = new TrackableValue("PERK_TITLE", 132, "perk.Title");
    public static final TrackableValue H1 = new TrackableValue("PRODUCT_AD_ID", 133, "product.AdID");
    public static final TrackableValue I1 = new TrackableValue("PRODUCT_AVAILABILITY", 134, "product.Availability");
    public static final TrackableValue J1 = new TrackableValue("PRODUCT_BRAND_NAME", 135, "product.BrandName");
    public static final TrackableValue K1 = new TrackableValue("PRODUCT_CATEGORY", 136, "product.Category");
    public static final TrackableValue L1 = new TrackableValue("PRODUCT_CATEGORY_ID", 137, "product.CategoryId");
    public static final TrackableValue M1 = new TrackableValue("PRODUCT_DISCOUNT", 138, "product.Discount");
    public static final TrackableValue N1 = new TrackableValue("PRODUCT_DISPATCH_NOTE", 139, "product.DispatchNote");
    public static final TrackableValue O1 = new TrackableValue("PRODUCT_HEALTHY_STAR_RATE", 140, "product.HealthyStarRate");
    public static final TrackableValue P1 = new TrackableValue("PRODUCT_HEALTHY_SWAPS_COUNT", 141, "healthySwaps.countOfSubs");
    public static final TrackableValue Q1 = new TrackableValue("PRODUCT_IMAGE_URL", 142, "product.ImageURL");
    public static final TrackableValue R1 = new TrackableValue("PRODUCT_LIST_COUNT", 143, "productList.Count");
    public static final TrackableValue S1 = new TrackableValue("PRODUCT_LIST_FILTER_CHIPS", 144, "productList.FilterChips");
    public static final TrackableValue T1 = new TrackableValue("PRODUCT_LIST_FILTERS", 145, "productList.Filters");
    public static final TrackableValue U1 = new TrackableValue("PRODUCT_LIST_PAGE_NUMBER", 146, "productList.PageNumber");
    public static final TrackableValue V1 = new TrackableValue("PRODUCT_LIST_SORT_BY", 147, "productList.SortBy");
    public static final TrackableValue W1 = new TrackableValue("PRODUCT_LIST_TITLE", 148, "productList.Title");
    public static final TrackableValue X1 = new TrackableValue("PRODUCT_LIST_TYPE", 149, "productList.Type");
    public static final TrackableValue Y1 = new TrackableValue("PRODUCT_LIST_VIEW_TYPE", 150, "productList.View");
    public static final TrackableValue Z1 = new TrackableValue("PRODUCT_MEMBER_PRICING_TYPE", 151, "product.MemberPricingType");
    public static final TrackableValue a2 = new TrackableValue("PRODUCT_MERCHANT", 152, "product.Merchant");
    public static final TrackableValue b2 = new TrackableValue("PRODUCT_NAME", 153, "product.Name");
    public static final TrackableValue c2 = new TrackableValue("PRODUCT_ORIGINAL_PRICE", 154, "product.OriginalPrice");
    public static final TrackableValue d2 = new TrackableValue("PRODUCT_QUANTITY", ModuleDescriptor.MODULE_VERSION, "product.Quantity");
    public static final TrackableValue e2 = new TrackableValue("PRODUCT_SELLER_NAME", 156, "product.SellerName");
    public static final TrackableValue f2 = new TrackableValue("PRODUCT_SOURCE", 157, "product.Source");
    public static final TrackableValue g2 = new TrackableValue("PRODUCT_SUBCATEGORY", 158, "product.SubCategory");
    public static final TrackableValue h2 = new TrackableValue("PRODUCT_SUBTOTAL", 159, "product.SubTotal");
    public static final TrackableValue i2 = new TrackableValue("PRODUCT_UNIT_PRICE", 160, "product.Price");
    public static final TrackableValue j2 = new TrackableValue("PRODUCTS", 161, "adobe.Products");
    public static final TrackableValue k2 = new TrackableValue("PROMO_CODE", 162, "promo.Code");
    public static final TrackableValue l2 = new TrackableValue("RECIPE_CATEGORY_TITLE", 163, "recipe.Category");
    public static final TrackableValue m2 = new TrackableValue("RECIPE_ID", 164, "recipe.ID");
    public static final TrackableValue n2 = new TrackableValue("RECIPE_LIST_COUNT", 165, "recipeList.Count");
    public static final TrackableValue o2 = new TrackableValue("RECIPE_NAME", 166, "recipe.Name");
    public static final TrackableValue p2 = new TrackableValue("RECIPE_SOURCE", 167, "recipe.Source");
    public static final TrackableValue q2 = new TrackableValue("RECIPE_TAGS", 168, "recipe.Tags");
    public static final TrackableValue r2 = new TrackableValue("REDEMPTION_SETTING", 169, "rewards.RedemptionSetting");
    public static final TrackableValue s2 = new TrackableValue("REFERRER_DOMAIN", 170, "referrer_domain");
    public static final TrackableValue t2 = new TrackableValue("REWARDS_CARD_TYPE", 171, "user.ProfileRewardsCardType");
    public static final TrackableValue u2 = new TrackableValue("REWARDS_FUEL_VOUCHERS_COUNT", 172, "rewards.FuelVouchers");
    public static final TrackableValue v2 = new TrackableValue("REWARDS_GIFT_CARD_RECIPIENT", 173, "giftCard.Recipient");
    public static final TrackableValue w2 = new TrackableValue("REWARDS_GIFTING_STORE_PRODUCT_ID", 174, "product.id");
    public static final TrackableValue x2 = new TrackableValue("REWARDS_GIFTING_STORE_PROGRAM_NAME", 175, "GiftCard.ProgramName");
    public static final TrackableValue y2 = new TrackableValue("REWARDS_OFFERS_COUNT", 176, "rewards.Offers");
    public static final TrackableValue z2 = new TrackableValue("REWARDS_POINTS_EARNED", 177, "user.ProfilePointsEarned");
    public static final TrackableValue A2 = new TrackableValue("REWARDS_STATE", 178, "user.ProfileIsRewardsMember");
    public static final TrackableValue B2 = new TrackableValue("REWARDS_WALLET_CARD_VERIFY", 179, "card.verify");
    public static final TrackableValue C2 = new TrackableValue("REWARDS_WALLET_TERMS_ACCEPTED", SubsamplingScaleImageView.ORIENTATION_180, "user.IsTermsAccepted");
    public static final TrackableValue D2 = new TrackableValue("SCANNED_BARCODE", 181, "digitalData.barcode.number");
    public static final TrackableValue E2 = new TrackableValue("SCREEN_NAME", 182, "screen.Name");
    public static final TrackableValue F2 = new TrackableValue("SCREEN_TYPE", 183, "screen.Type");
    public static final TrackableValue G2 = new TrackableValue("SEARCH_CATEGORY", 184, "search.Category");
    public static final TrackableValue H2 = new TrackableValue("SEARCH_FACET_TERM", 185, "search.facetTerm");
    public static final TrackableValue I2 = new TrackableValue("SEARCH_INDEX_NAME", 186, "search.IndexName");
    public static final TrackableValue J2 = new TrackableValue("SEARCH_KEYWORD", 187, "search.Keyword");
    public static final TrackableValue K2 = new TrackableValue("SEARCH_KEYWORD_TYPE", 188, "search.KeywordType");
    public static final TrackableValue L2 = new TrackableValue("SEARCH_OBJECT_ID", 189, "search.ObjectID");
    public static final TrackableValue M2 = new TrackableValue("SEARCH_QUERY_ID", 190, "search.QueryID");
    public static final TrackableValue N2 = new TrackableValue("SEARCH_RESULT", 191, "search.Result");
    public static final TrackableValue O2 = new TrackableValue("SEARCH_RESULT_COUNT", BERTags.PRIVATE, "search.ResultsCount");
    public static final TrackableValue P2 = new TrackableValue("SEARCH_RESULT_TYPE", 193, "search.ResultType");
    public static final TrackableValue Q2 = new TrackableValue("SEARCH_TYPE", 194, "search.Type");
    public static final TrackableValue R2 = new TrackableValue("SHOPPER_ID", 195, "user.ShopperID");
    public static final TrackableValue S2 = new TrackableValue("SHOPPING_MODE", 196, "user.ShoppingMode");
    public static final TrackableValue V2 = new TrackableValue("SHOPPING_MODE_VARIANT", 197, "user.ShoppingModeVariant");
    public static final TrackableValue t3 = new TrackableValue("STORE_ID", 198, "digitalData.store.storeID");
    public static final TrackableValue x3 = new TrackableValue("STORE_NAME", 199, "store.Name");
    public static final TrackableValue y3 = new TrackableValue("SUBSCRIPTION_ALLOWED_USAGE_TYPE", 200, "subscription.AllowedUsageType");
    public static final TrackableValue z3 = new TrackableValue("SUBSCRIPTION_BILLING_PERIOD", 201, "subscription.BillingPeriod");
    public static final TrackableValue A3 = new TrackableValue("SUBSCRIPTION_ID", DatastoreTestTrace.FirestoreV1Action.DATABASE_CONTENTS_BEFORE_ACTION_FIELD_NUMBER, "subscription.ID");
    public static final TrackableValue B3 = new TrackableValue("SUBSCRIPTION_SUBSCRIBER_TYPE", DatastoreTestTrace.FirestoreV1Action.MATCHING_DOCUMENTS_FIELD_NUMBER, "user.Subscriber");
    public static final TrackableValue C3 = new TrackableValue("SUBSCRIPTION_TYPE", 204, "subscription.Type");
    public static final TrackableValue D3 = new TrackableValue("SUBSCRIPTION_USER_STATUS", 205, "user.Status");
    public static final TrackableValue E3 = new TrackableValue("SUPERS_ORDER_COUNT", 206, "user.SupersOrderCount");
    public static final TrackableValue F3 = new TrackableValue("SWRVE_ID", 207, "swrve.ID");
    public static final TrackableValue G3 = new TrackableValue("TRANSACTION_ID", 208, "digitalData.transaction.transactionID");
    public static final TrackableValue H3 = new TrackableValue("UTM_CAMPAIGN", 209, "qp.utm_campaign");
    public static final TrackableValue I3 = new TrackableValue("UTM_CONTENT", 210, "qp.utm_content");
    public static final TrackableValue J3 = new TrackableValue("UTM_MEDIUM", Primes.SMALL_FACTOR_LIMIT, "qp.utm_medium");
    public static final TrackableValue K3 = new TrackableValue("UTM_PATH", 212, "qp.utm_path");
    public static final TrackableValue L3 = new TrackableValue("UTM_SOURCE", 213, "qp.utm_source");
    public static final TrackableValue M3 = new TrackableValue("UTM_TERM", 214, "qp.utm_term");
    public static final TrackableValue N3 = new TrackableValue("VIDEO_ID", 215, "video.ID");
    public static final TrackableValue O3 = new TrackableValue("VIDEO_LENGTH", 216, "video.Length");
    public static final TrackableValue P3 = new TrackableValue("VIDEO_NAME", 217, "video.Name");
    public static final TrackableValue Q3 = new TrackableValue("VISITOR_ID", 218, "user.ProfileCRNHash");
    public static final TrackableValue R3 = new TrackableValue("WALLET_PAYMENT_INSTRUMENT_TYPE", 219, "Payment.InstrumentType");
    public static final TrackableValue S3 = new TrackableValue("WALLET_PAYMENT_TRANSACTION_AMOUNT", 220, "Transaction.Amount");
    public static final TrackableValue T3 = new TrackableValue("WALLET_PAYMENT_TRANSACTION_DATE", 221, "Transaction.Date");
    public static final TrackableValue U3 = new TrackableValue("WALLET_PAYMENT_TRANSACTION_ID", 222, "Transaction.ID");
    public static final TrackableValue V3 = new TrackableValue("WALLET_PAYMENT_TRANSACTION_MERCHANT_ID", 223, "Merchant.ID");
    public static final TrackableValue W3 = new TrackableValue("WINDOW_EXPRESS", BERTags.FLAGS, "window.isExpress");
    public static final TrackableValue X3 = new TrackableValue("WINDOW_STATUS", 225, "user.WindowStatus");
    public static final TrackableValue Y3 = new TrackableValue("WX_ID", 226, "user.app_wxid");

    static {
        TrackableValue[] trackableValueArrA = a();
        Z3 = trackableValueArrA;
        a4 = EnumEntriesKt.a(trackableValueArrA);
    }

    public TrackableValue(String str, int i3, String str2) {
        this.d = str2;
    }

    public static final /* synthetic */ TrackableValue[] a() {
        return new TrackableValue[]{e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, a0, b0, c0, d0, e0, f0, g0, h0, i0, j0, k0, l0, m0, n0, o0, p0, q0, r0, s0, t0, u0, v0, w0, x0, y0, z0, A0, B0, C0, D0, E0, F0, G0, H0, I0, J0, K0, L0, M0, N0, O0, P0, Q0, R0, S0, T0, U0, V0, W0, X0, Y0, Z0, a1, b1, c1, d1, e1, f1, g1, h1, i1, j1, k1, l1, m1, n1, o1, p1, q1, r1, s1, t1, u1, v1, w1, x1, y1, z1, A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, a2, b2, c2, d2, e2, f2, g2, h2, i2, j2, k2, l2, m2, n2, o2, p2, q2, r2, s2, t2, u2, v2, w2, x2, y2, z2, A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, L2, M2, N2, O2, P2, Q2, R2, S2, V2, t3, x3, y3, z3, A3, B3, C3, D3, E3, F3, G3, H3, I3, J3, K3, L3, M3, N3, O3, P3, Q3, R3, S3, T3, U3, V3, W3, X3, Y3};
    }

    public static TrackableValue valueOf(String str) {
        return (TrackableValue) Enum.valueOf(TrackableValue.class, str);
    }

    public static TrackableValue[] values() {
        return (TrackableValue[]) Z3.clone();
    }
}
