package com.woolworths.feature.shop.marketplace.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.graphql.common.fragment.selections.ProductCardSelections;
import au.com.woolworths.shop.graphql.type.BrandItem;
import au.com.woolworths.shop.graphql.type.CategoryItem;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.HorizontalListItem;
import au.com.woolworths.shop.graphql.type.InfoSection;
import au.com.woolworths.shop.graphql.type.InfoSectionFooter;
import au.com.woolworths.shop.graphql.type.InfoSectionItem;
import au.com.woolworths.shop.graphql.type.Marketplace;
import au.com.woolworths.shop.graphql.type.MarketplaceLandingPageName;
import au.com.woolworths.shop.graphql.type.MarketplacePageTab;
import au.com.woolworths.shop.graphql.type.MarketplacePersonalisedSegment;
import au.com.woolworths.shop.graphql.type.MarketplaceSections;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.SellerItem;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.woolworths.feature.shop.marketplace.fragment.selections.PromotionBannerFragmentSelections;
import com.woolworths.feature.shop.marketplace.fragment.selections.SectionItemSelections;
import com.woolworths.feature.shop.marketplace.fragment.selections.TileItemSelections;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/feature/shop/marketplace/selections/MarketplaceQuerySelections;", "", "marketplace_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class MarketplaceQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f19851a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        List listR = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c());
        f19851a = listR;
        List listR2 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("linkUrl", CompiledGraphQL.b(customScalarType)).c());
        b = listR2;
        CompiledField compiledFieldC = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder = new CompiledField.Builder("items", a.f(InfoSectionItem.f11497a));
        builder.e = listR;
        CompiledField compiledFieldC2 = builder.c();
        CompiledField.Builder builder2 = new CompiledField.Builder("footer", InfoSectionFooter.f11496a);
        builder2.e = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC, compiledFieldC2, builder2.c());
        c = listR3;
        MarketplaceLandingPageName.e.getClass();
        EnumType enumType = MarketplaceLandingPageName.f;
        List listR4 = CollectionsKt.R(new CompiledField.Builder("pageName", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c());
        d = listR4;
        CompiledField compiledFieldC3 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("PromotionBanner", CollectionsKt.Q("PromotionBanner"));
        builder3.b(PromotionBannerFragmentSelections.e);
        List listR5 = CollectionsKt.R(compiledFieldC3, builder3.a());
        e = listR5;
        CompiledField compiledFieldC4 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder4.b(ProductCardSelections.A);
        List listR6 = CollectionsKt.R(compiledFieldC4, builder4.a());
        f = listR6;
        CompiledField compiledFieldC5 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder5.d = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC5, builder5.a());
        g = listR7;
        CompiledField compiledFieldC6 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField.Builder builder6 = new CompiledField.Builder("items", d.j(HorizontalListItem.f11475a));
        builder6.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC6, compiledFieldG, builder6.c());
        h = listR8;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("PromotionBanner", CollectionsKt.Q("PromotionBanner"));
        builder7.d = listR5;
        CompiledFragment compiledFragmentA = builder7.a();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("MarketplaceHorizontalList", CollectionsKt.Q("MarketplaceHorizontalList"));
        builder8.d = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC7, compiledFragmentA, builder8.a());
        i = listR9;
        CompiledField compiledFieldC8 = new CompiledField.Builder("pageName", CompiledGraphQL.b(enumType)).c();
        CompiledField compiledFieldC9 = new CompiledField.Builder("displayName", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder9 = new CompiledField.Builder("items", d.j(MarketplacePersonalisedSegment.f11562a));
        builder9.e = listR9;
        List listR10 = CollectionsKt.R(compiledFieldC8, compiledFieldC9, builder9.c());
        j = listR10;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC11 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC12 = new CompiledField.Builder("isFinalLevel", CompiledGraphQL.b(GraphQLBoolean.f11439a)).c();
        CompiledField compiledFieldG2 = d.g("source", customScalarType);
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("MarketplaceItem", CollectionsKt.R("CategoryItem", "BrandItem", "SellerItem"));
        List list = TileItemSelections.f19850a;
        builder10.b(list);
        List listR11 = CollectionsKt.R(compiledFieldC10, compiledFieldC11, compiledFieldC12, compiledFieldG2, builder10.a());
        k = listR11;
        CompiledField compiledFieldC13 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("MarketplaceSectionItem", CollectionsKt.R("Sellers", "Brands", "Categories"));
        List list2 = SectionItemSelections.f19849a;
        builder11.b(list2);
        CompiledFragment compiledFragmentA2 = builder11.a();
        CompiledField compiledFieldC14 = new CompiledField.Builder("pageName", CompiledGraphQL.b(enumType)).c();
        CompiledField compiledFieldC15 = new CompiledField.Builder("displayName", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder12 = new CompiledField.Builder("items", a.f(CategoryItem.f11170a));
        builder12.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC13, compiledFragmentA2, compiledFieldC14, compiledFieldC15, builder12.c());
        l = listR12;
        CompiledField compiledFieldC16 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("MarketplaceItem", CollectionsKt.R("CategoryItem", "BrandItem", "SellerItem"));
        builder13.d = list;
        List listR13 = CollectionsKt.R(compiledFieldC16, builder13.a(), new CompiledField.Builder("logoUrl", CompiledGraphQL.b(customScalarType)).c());
        m = listR13;
        CompiledField compiledFieldC17 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("MarketplaceSectionItem", CollectionsKt.R("Sellers", "Brands", "Categories"));
        builder14.d = list2;
        CompiledFragment compiledFragmentA3 = builder14.a();
        CompiledField compiledFieldC18 = new CompiledField.Builder("pageName", CompiledGraphQL.b(enumType)).c();
        CompiledField.Builder builder15 = new CompiledField.Builder("items", a.f(BrandItem.f11055a));
        builder15.e = listR13;
        List listR14 = CollectionsKt.R(compiledFieldC17, compiledFragmentA3, compiledFieldC18, builder15.c());
        n = listR14;
        CompiledField compiledFieldC19 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("MarketplaceItem", CollectionsKt.R("CategoryItem", "BrandItem", "SellerItem"));
        builder16.d = list;
        List listR15 = CollectionsKt.R(compiledFieldC19, builder16.a());
        o = listR15;
        CompiledField compiledFieldC20 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("MarketplaceSectionItem", CollectionsKt.R("Sellers", "Brands", "Categories"));
        builder17.d = list2;
        CompiledFragment compiledFragmentA4 = builder17.a();
        CompiledField compiledFieldC21 = new CompiledField.Builder("pageName", CompiledGraphQL.b(enumType)).c();
        CompiledField.Builder builder18 = new CompiledField.Builder("items", a.f(SellerItem.f11890a));
        builder18.e = listR15;
        List listR16 = CollectionsKt.R(compiledFieldC20, compiledFragmentA4, compiledFieldC21, builder18.c());
        p = listR16;
        CompiledField compiledFieldC22 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("MarketplacePersonalised", CollectionsKt.Q("MarketplacePersonalised"));
        builder19.d = listR10;
        CompiledFragment compiledFragmentA5 = builder19.a();
        CompiledFragment.Builder builder20 = new CompiledFragment.Builder("Categories", CollectionsKt.Q("Categories"));
        builder20.d = listR12;
        CompiledFragment compiledFragmentA6 = builder20.a();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("Brands", CollectionsKt.Q("Brands"));
        builder21.d = listR14;
        CompiledFragment compiledFragmentA7 = builder21.a();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("Sellers", CollectionsKt.Q("Sellers"));
        builder22.d = listR16;
        List listR17 = CollectionsKt.R(compiledFieldC22, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, builder22.a());
        q = listR17;
        CompiledField.Builder builder23 = new CompiledField.Builder("buttonTitle", customScalarType);
        builder23.c = a.s("isHowItWorksEnabled", false);
        CompiledField compiledFieldC23 = builder23.c();
        CompiledField.Builder builder24 = new CompiledField.Builder("header", InfoSection.f11495a);
        builder24.c = a.s("isHowItWorksEnabled", false);
        builder24.e = listR3;
        CompiledField compiledFieldC24 = builder24.c();
        CompiledField.Builder builder25 = new CompiledField.Builder("tabs", a.f(MarketplacePageTab.f11560a));
        builder25.e = listR4;
        CompiledField compiledFieldC25 = builder25.c();
        CompiledField.Builder builder26 = new CompiledField.Builder("sections", d.j(MarketplaceSections.f11565a));
        builder26.e = listR17;
        List listR18 = CollectionsKt.R(compiledFieldC23, compiledFieldC24, compiledFieldC25, builder26.c());
        r = listR18;
        CompiledField.Builder builder27 = new CompiledField.Builder("marketplace", CompiledGraphQL.b(Marketplace.f11552a));
        new CompiledArgument.Builder(Query.C);
        builder27.d = au.com.woolworths.android.onesite.a.v();
        builder27.e = listR18;
        s = CollectionsKt.Q(builder27.c());
    }
}
