package com.woolworths.shop.healthylife.foodtracker.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.shop.graphql.type.DownloadableAsset;
import au.com.woolworths.shop.graphql.type.DownloadableAssetFit;
import au.com.woolworths.shop.graphql.type.DownloadableAssetType;
import au.com.woolworths.shop.graphql.type.FoodTrackerAction;
import au.com.woolworths.shop.graphql.type.FoodTrackerContentItem;
import au.com.woolworths.shop.graphql.type.FoodTrackerFooterCard;
import au.com.woolworths.shop.graphql.type.FoodTrackerPage;
import au.com.woolworths.shop.graphql.type.FooterActionType;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.ListSectionHeaderTypes;
import au.com.woolworths.shop.graphql.type.ParagraphTextItemType;
import au.com.woolworths.shop.graphql.type.Query;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/healthylife/foodtracker/selections/FoodTrackerPageQuerySelections;", "", "healthy-life-food-tracker_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class FoodTrackerPageQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f22774a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;

    static {
        DownloadableAssetType.e.getClass();
        EnumType enumType = DownloadableAssetType.f;
        CompiledField compiledFieldC = new CompiledField.Builder("assetType", CompiledGraphQL.b(enumType)).c();
        CustomScalarType customScalarType = GraphQLString.f11443a;
        CompiledField compiledFieldC2 = new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLInt.f11442a;
        CompiledField compiledFieldC3 = new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType2)).c();
        DownloadableAssetFit.e.getClass();
        EnumType enumType2 = DownloadableAssetFit.f;
        List listR = CollectionsKt.R(compiledFieldC, compiledFieldC2, compiledFieldC3, compiledFieldC4, new CompiledField.Builder("fit", enumType2).c(), d.g("altText", customScalarType));
        f22774a = listR;
        List listR2 = CollectionsKt.R(new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c());
        b = listR2;
        CompiledField compiledFieldC5 = new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c();
        ParagraphTextItemType.e.getClass();
        List listR3 = CollectionsKt.R(compiledFieldC5, new CompiledField.Builder("type", CompiledGraphQL.b(ParagraphTextItemType.f)).c());
        c = listR3;
        CompiledField compiledFieldC6 = new CompiledField.Builder("listSectionHeaderText", CompiledGraphQL.b(customScalarType)).c();
        ListSectionHeaderTypes.e.getClass();
        List listR4 = CollectionsKt.R(compiledFieldC6, new CompiledField.Builder("listSectionHeaderType", CompiledGraphQL.b(ListSectionHeaderTypes.f)).c());
        d = listR4;
        List listR5 = CollectionsKt.R(new CompiledField.Builder("assetType", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType2)).c(), a.d("fit", enumType2), d.g("altText", customScalarType));
        e = listR5;
        List listR6 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        f = listR6;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("IconListItem", CollectionsKt.Q("IconListItem"));
        builder.d = listR2;
        CompiledFragment compiledFragmentA = builder.a();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("ParagraphTextItem", CollectionsKt.Q("ParagraphTextItem"));
        builder2.d = listR3;
        CompiledFragment compiledFragmentA2 = builder2.a();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("ListSectionHeader", CollectionsKt.Q("ListSectionHeader"));
        builder3.d = listR4;
        CompiledFragment compiledFragmentA3 = builder3.a();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("DownloadableAsset", CollectionsKt.Q("DownloadableAsset"));
        builder4.d = listR5;
        CompiledFragment compiledFragmentA4 = builder4.a();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("TextWithLink", CollectionsKt.Q("TextWithLink"));
        builder5.d = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC7, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, builder5.a());
        g = listR7;
        List listR8 = CollectionsKt.R(new CompiledField.Builder("assetType", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType2)).c(), a.d("fit", enumType2), d.g("altText", customScalarType));
        h = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("assetType", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType2)).c(), a.d("fit", enumType2), d.g("altText", customScalarType));
        i = listR9;
        ObjectType objectType = DownloadableAsset.f11349a;
        CompiledField.Builder builder6 = new CompiledField.Builder("headerAsset", CompiledGraphQL.b(objectType));
        builder6.e = listR9;
        List listR10 = CollectionsKt.R(builder6.c(), new CompiledField.Builder("consentTitle", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("consentMarkdownDescription", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("termsMarkdownText", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("primaryCtaLabel", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("secondaryCtaLabel", CompiledGraphQL.b(customScalarType)).c());
        j = listR10;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("FoodTrackerConsent", CollectionsKt.Q("FoodTrackerConsent"));
        builder7.d = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC8, builder7.a());
        k = listR11;
        CompiledField.Builder builder8 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(objectType));
        builder8.e = listR8;
        CompiledField compiledFieldC9 = builder8.c();
        CompiledField compiledFieldC10 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder9 = new CompiledField.Builder("consentAction", FoodTrackerAction.f11387a);
        builder9.e = listR11;
        CompiledField compiledFieldC11 = builder9.c();
        FooterActionType.e.getClass();
        List listR12 = CollectionsKt.R(compiledFieldC9, compiledFieldC10, compiledFieldC11, new CompiledField.Builder("actionType", CompiledGraphQL.b(FooterActionType.f)).c(), new CompiledField.Builder("primaryCtaLabel", CompiledGraphQL.b(customScalarType)).c());
        l = listR12;
        CompiledField compiledFieldC12 = new CompiledField.Builder("navigationTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder10 = new CompiledField.Builder("headerAsset", CompiledGraphQL.b(objectType));
        builder10.e = listR;
        CompiledField compiledFieldC13 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("content", d.j(FoodTrackerContentItem.f11391a));
        builder11.e = listR7;
        CompiledField compiledFieldC14 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("footer", CompiledGraphQL.b(FoodTrackerFooterCard.f11392a));
        builder12.e = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC12, compiledFieldC13, compiledFieldC14, builder12.c());
        m = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder("navigationTitle", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        n = listR14;
        CompiledField compiledFieldC15 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("FoodTrackerContentFeed", CollectionsKt.Q("FoodTrackerContentFeed"));
        builder13.d = listR13;
        CompiledFragment compiledFragmentA5 = builder13.a();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("FoodTrackerWebView", CollectionsKt.Q("FoodTrackerWebView"));
        builder14.d = listR14;
        List listR15 = CollectionsKt.R(compiledFieldC15, compiledFragmentA5, builder14.a());
        o = listR15;
        CompiledField.Builder builder15 = new CompiledField.Builder("foodTrackerPage", FoodTrackerPage.f11393a);
        new CompiledArgument.Builder(Query.p);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.q);
        builder15.d = CollectionsKt.R(compiledArgument, new CompiledArgument());
        builder15.e = listR15;
        p = CollectionsKt.Q(builder15.c());
    }
}
