package com.lexisnexisrisk.threatmetrix.rl.tmxprofiling;

import com.google.android.gms.measurement.api.AppMeasurementSdk;

/* loaded from: classes6.dex */
public enum lqqqqql {
    AGENT_LOCALE("alo"),
    APP_HASHES("ih"),
    TIMEZONE_GMT_OFFSET("c"),
    TIMEZONE_DST_DIFF("z"),
    TIMEZONE_NAME("tzd"),
    DEVICE_NAME(AppMeasurementSdk.ConditionalUserProperty.NAME),
    DEVICE_LOCAL_STORAGE_COOKIE("ls"),
    DEVICE_FLASH_COOKIE("fg"),
    DEVICE_SOFTWARE_ID("swid"),
    DEVICE_DISPLAY_RESOLUTION("f"),
    DEVICE_DISPLAY_WIDTH_IN_PIXEL("bhsswpx"),
    DEVICE_DISPLAY_HEIGHT_IN_PIXEL("bhsshpx"),
    DEVICE_DISPLAY_XDPI("bhsxdpi"),
    DEVICE_DISPLAY_YDPI("bhsydpi"),
    DEVICE_DISPLAY_NATIVE_BOUND_X("bhssnbx"),
    DEVICE_DISPLAY_NATIVE_BOUND_Y("bhssnby"),
    DEVICE_FINGERPRINT("mdf"),
    APP_SELF_HASH_MD5("ah"),
    APP_SELF_HASH_SHA256("ah2"),
    SELF_HASH_BASE_MODULE("sah"),
    SELF_HASH_DSH_MODULE("mdah"),
    SELF_HASH_AUTH_MODULE("auah"),
    DEVICE_FONT_COUNT("ftsn"),
    DEVICE_FONT_HASH("fts"),
    DEVICE_BOOT_TIME("abt"),
    AGENT_APP_INFO("anv"),
    DEVICE_FREE_SPACE("afs"),
    DEVICE_TOTAL_SPACE("ats"),
    DEVICE_STATE("mds"),
    NETWORK_INFO_BSSID("wbs"),
    NETWORK_INFO_SSID_HASH("wss"),
    NETWORK_INFO_SSID("wssc"),
    NETWORK_INFO_RSSI("wrr"),
    NETWORK_INFO_TYPE("wc"),
    NETWORK_INFO_IPV4("ipv4"),
    NETWORK_INFO_IPV6("ipv6"),
    NETWORK_INFO_MAC("mac"),
    NETWORK_INFO_WFS("wfs"),
    NETWORK_INFO_VPN("vpn"),
    NETWORK_INFO_SECURITY_TYPE("wst"),
    SUBSCRIBER_CELL_INFO("asi"),
    SUBSCRIBER_CELL_ID("aci"),
    ADVERTISING_ID("adid"),
    SELINUX_MODE("se"),
    SHARED_LIB_INFO("mex2"),
    CONNECTIONS_INFO("nci"),
    APP_INSTALLATION_TIME("apit"),
    APP_MODIFICATION_TIME("amt"),
    SYSTEM_PROXY("spx"),
    NUM_OF_CPU_CORES("nhc"),
    CPU_NAME("cpn"),
    CPU_SPEED("cps"),
    MEM_TOTAL("mto"),
    MALICIOUS_APP_STATUS("mlapp"),
    AGENT_OS_VERSION("aov"),
    AGENT_SECURITY_PATCH_LEVEL("aspl"),
    AGENT_LANGUAGE("al"),
    AGENT_BRAND("ab"),
    AGENT_DEVICE("ad"),
    AGENT_MODEL("am"),
    AGENT_OS("aos"),
    AGENT_CONF_OS("cos"),
    AGENT_TYPE("at"),
    AGENT_VERSION("av"),
    AGENT_PROCESS_ID("pid"),
    AGENT_PARENT_PID("ppid"),
    DEVICE_BATTERY_STATUS("btst"),
    DEVICE_VERSION_BRAND("bhsdmo"),
    DEVICE_ENCRYPTION_STATUS("mex6"),
    DEVICE_DEV_ENABLED_STATUS("dm"),
    TAMPER_CODE_BASE_MODULE("prst"),
    TAMPER_CODE_AUTH_MODULE("autm"),
    TAMPER_CODE_BB_MODULE("bbtm"),
    TAMPER_CODE_DSH_MODULE("mdtm"),
    EM_PATH_COUNT("mr"),
    EM_PATH_STR("mrr"),
    PLUGIN_PATH_STR("pldec1"),
    LOCATION_LATITUDE("tdlat"),
    LOCATION_LONGITUDE("tdlon"),
    LOCATION_ALTITUDE("tdlalt"),
    LOCATION_ACCURACY("tdlacc"),
    LOCATION_VERTICAL_ACCURACY("tdlvacc"),
    LOCATION_MOCK_STATUS("mlst"),
    ROOT_DETECTION_PATH_COUNT("gr"),
    ROOT_DETECTION_PATH_STR("grr"),
    RAT_DETECTION_INFO("rdi"),
    FIREBASE_PUSH_TOKEN("sa_pt"),
    IN_CALL_STATUS("ics"),
    IN_CALL_TYPE("ict"),
    STRONG_ID_SIGNATURE("sid_sig"),
    STRONG_ID_RANDOM("sid_rnd"),
    STRONG_ID_TYPE("sid_type"),
    STRONG_ID_DATE("sid_date"),
    STRONG_ID_KEY("sid_key"),
    STRONG_AUTH_STATUS("sa_st"),
    CRASH_LOG_STRING("crsh"),
    USER_PERMISSIONS("upl"),
    STORAGE_EMULATED_TIMESTAMP("ait"),
    DRM_ID("drm");

    private final String aa0061aaa0061;

    lqqqqql(String str) {
        this.aa0061aaa0061 = str;
    }

    public static lqqqqql valueOf(String str) {
        return (lqqqqql) nlnnnnn.ooo006F006Foo(lqqqqql.class, str);
    }

    public String jj006Ajj006A006A() {
        return this.aa0061aaa0061;
    }
}
