package me.oriient.internal.services.dataModel.positioning;

import java.util.List;
import kotlin.Deprecated;
import kotlin.Metadata;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.DoubleSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.PluginHelperInterfacesKt;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import me.oriient.internal.services.dataModel.positioning.PositioningConfigResponse;
import org.jetbrains.annotations.NotNull;

@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0003J\u0018\u0010\b\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\n0\tHÖ\u0001¢\u0006\u0002\u0010\u000bJ\u0011\u0010\f\u001a\u00020\u00022\u0006\u0010\r\u001a\u00020\u000eHÖ\u0001J\u0019\u0010\u000f\u001a\u00020\u00102\u0006\u0010\u0011\u001a\u00020\u00122\u0006\u0010\u0013\u001a\u00020\u0002HÖ\u0001R\u0014\u0010\u0004\u001a\u00020\u00058VXÖ\u0005¢\u0006\u0006\u001a\u0004\b\u0006\u0010\u0007¨\u0006\u0014"}, d2 = {"me/oriient/internal/services/dataModel/positioning/PositioningConfigResponse.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lme/oriient/internal/services/dataModel/positioning/PositioningConfigResponse;", "()V", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "internal_publishRelease"}, k = 1, mv = {1, 9, 0}, xi = 48)
@Deprecated
/* loaded from: classes7.dex */
public final class PositioningConfigResponse$$serializer implements GeneratedSerializer<PositioningConfigResponse> {

    @NotNull
    public static final PositioningConfigResponse$$serializer INSTANCE;
    private static final /* synthetic */ PluginGeneratedSerialDescriptor descriptor;

    static {
        PositioningConfigResponse$$serializer positioningConfigResponse$$serializer = new PositioningConfigResponse$$serializer();
        INSTANCE = positioningConfigResponse$$serializer;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("me.oriient.internal.services.dataModel.positioning.PositioningConfigResponse", positioningConfigResponse$$serializer, 22);
        pluginGeneratedSerialDescriptor.k("isPreheatingEnabledByDefault", true);
        pluginGeneratedSerialDescriptor.k("enableAutoStartPositioning", true);
        pluginGeneratedSerialDescriptor.k("enableAutoCalib", true);
        pluginGeneratedSerialDescriptor.k("ignorePublicAPIIsAutomaticCalibrationEnabled", true);
        pluginGeneratedSerialDescriptor.k("autoStartPositioningPauseAfterAutoStopMinutes", true);
        pluginGeneratedSerialDescriptor.k("autoStartPositioningPauseAfterErrorMinutes", true);
        pluginGeneratedSerialDescriptor.k("autoStartPositioningPauseAfterClientStopMinutes", true);
        pluginGeneratedSerialDescriptor.k("autoStartPositioningPauseAfterClientStartMinutes", true);
        pluginGeneratedSerialDescriptor.k("enableChargingBasedAutoStartPositioning", true);
        pluginGeneratedSerialDescriptor.k("maximumLocationAccuracyToAutoStartMeters", true);
        pluginGeneratedSerialDescriptor.k("isAutomaticPositioningPartOfCalibration", true);
        pluginGeneratedSerialDescriptor.k("stopNoMovementSec", true);
        pluginGeneratedSerialDescriptor.k("stopBackgroundSec", true);
        pluginGeneratedSerialDescriptor.k("positioningSessionTimeoutMinutes", true);
        pluginGeneratedSerialDescriptor.k("backgroundCalibrationTimeoutMinutes", true);
        pluginGeneratedSerialDescriptor.k("allowPositioningOutOfBuilding", true);
        pluginGeneratedSerialDescriptor.k("allowPositioningWhenLocationIsUnknown", true);
        pluginGeneratedSerialDescriptor.k("maxPositionAgeToEventTagSeconds", true);
        pluginGeneratedSerialDescriptor.k("noMovementDelta", true);
        pluginGeneratedSerialDescriptor.k("supportedCustomEventTagTypes", true);
        pluginGeneratedSerialDescriptor.k("secondsSinceChargingToUseKiosk", true);
        pluginGeneratedSerialDescriptor.k("autoStop", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    private PositioningConfigResponse$$serializer() {
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    @NotNull
    public KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = PositioningConfigResponse.$childSerializers;
        BooleanSerializer booleanSerializer = BooleanSerializer.f24779a;
        KSerializer<?> kSerializerD = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD2 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD3 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD4 = BuiltinSerializersKt.d(booleanSerializer);
        DoubleSerializer doubleSerializer = DoubleSerializer.f24792a;
        return new KSerializer[]{kSerializerD, kSerializerD2, kSerializerD3, kSerializerD4, BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(booleanSerializer), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(booleanSerializer), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(booleanSerializer), BuiltinSerializersKt.d(booleanSerializer), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(kSerializerArr[19]), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(PositioningConfigResponse$AutoStopResponse$$serializer.INSTANCE)};
    }

    @Override // kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    @NotNull
    /* renamed from: getDescriptor */
    public SerialDescriptor getB() {
        return descriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    @NotNull
    public KSerializer<?>[] typeParametersSerializers() {
        return PluginHelperInterfacesKt.f24815a;
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public PositioningConfigResponse deserialize(@NotNull Decoder decoder) {
        Double d;
        int i;
        Double d2;
        Double d3;
        Double d4;
        Boolean bool;
        Double d5;
        Boolean bool2;
        Boolean bool3;
        int i2;
        Boolean bool4;
        Double d6;
        int i3;
        int i4;
        Intrinsics.h(decoder, "decoder");
        SerialDescriptor b = getB();
        CompositeDecoder compositeDecoderB = decoder.b(b);
        KSerializer[] kSerializerArr = PositioningConfigResponse.$childSerializers;
        Boolean bool5 = null;
        Double d7 = null;
        Boolean bool6 = null;
        Double d8 = null;
        Double d9 = null;
        Boolean bool7 = null;
        Double d10 = null;
        Double d11 = null;
        Double d12 = null;
        Boolean bool8 = null;
        Double d13 = null;
        Double d14 = null;
        List list = null;
        PositioningConfigResponse.AutoStopResponse autoStopResponse = null;
        Boolean bool9 = null;
        Boolean bool10 = null;
        Boolean bool11 = null;
        Boolean bool12 = null;
        Double d15 = null;
        Double d16 = null;
        Double d17 = null;
        Double d18 = null;
        int i5 = 0;
        boolean z = true;
        while (z) {
            Boolean bool13 = bool7;
            int iU = compositeDecoderB.u(b);
            Double d19 = d8;
            switch (iU) {
                case -1:
                    z = false;
                    d11 = d11;
                    bool7 = bool13;
                    bool6 = bool6;
                    d7 = d7;
                    bool12 = bool12;
                    d16 = d16;
                    d14 = d14;
                    d8 = d19;
                    i5 = i5;
                case 0:
                    d = d7;
                    Boolean bool14 = bool12;
                    i = i5;
                    Boolean bool15 = bool6;
                    Boolean bool16 = bool11;
                    Double d20 = d10;
                    Double d21 = d17;
                    d2 = d16;
                    d14 = d14;
                    d3 = d18;
                    d4 = d21;
                    bool9 = (Boolean) compositeDecoderB.k(b, 0, BooleanSerializer.f24779a, bool9);
                    d10 = d20;
                    bool7 = bool13;
                    bool = bool10;
                    d11 = d11;
                    d5 = d15;
                    bool2 = bool16;
                    bool3 = bool14;
                    bool6 = bool15;
                    i2 = 1;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 1:
                    d = d7;
                    Boolean bool17 = bool12;
                    Boolean bool18 = bool6;
                    Boolean bool19 = bool11;
                    i = i5;
                    Double d22 = d17;
                    d2 = d16;
                    d14 = d14;
                    d3 = d18;
                    d4 = d22;
                    bool = (Boolean) compositeDecoderB.k(b, 1, BooleanSerializer.f24779a, bool10);
                    d11 = d11;
                    bool7 = bool13;
                    bool2 = bool19;
                    d5 = d15;
                    bool6 = bool18;
                    bool3 = bool17;
                    i2 = 2;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 2:
                    Boolean bool20 = bool6;
                    Double d23 = d16;
                    d = d7;
                    Boolean bool21 = (Boolean) compositeDecoderB.k(b, 2, BooleanSerializer.f24779a, bool11);
                    bool = bool10;
                    bool7 = bool13;
                    i = i5;
                    bool6 = bool20;
                    d5 = d15;
                    d3 = d18;
                    bool3 = bool12;
                    d4 = d17;
                    i2 = 4;
                    d2 = d23;
                    bool2 = bool21;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 3:
                    bool4 = bool6;
                    d6 = d16;
                    d = d7;
                    Boolean bool22 = (Boolean) compositeDecoderB.k(b, 3, BooleanSerializer.f24779a, bool12);
                    bool2 = bool11;
                    bool7 = bool13;
                    i = i5;
                    i2 = 8;
                    bool = bool10;
                    d5 = d15;
                    d3 = d18;
                    bool3 = bool22;
                    d4 = d17;
                    d2 = d6;
                    bool6 = bool4;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 4:
                    bool4 = bool6;
                    d6 = d16;
                    d = d7;
                    Double d24 = (Double) compositeDecoderB.k(b, 4, DoubleSerializer.f24792a, d15);
                    bool3 = bool12;
                    bool7 = bool13;
                    i = i5;
                    i2 = 16;
                    d5 = d24;
                    bool2 = bool11;
                    d3 = d18;
                    bool = bool10;
                    d4 = d17;
                    d2 = d6;
                    bool6 = bool4;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 5:
                    d = d7;
                    bool7 = bool13;
                    Double d25 = (Double) compositeDecoderB.k(b, 5, DoubleSerializer.f24792a, d16);
                    i2 = 32;
                    d5 = d15;
                    i = i5;
                    bool6 = bool6;
                    bool3 = bool12;
                    d3 = d18;
                    bool2 = bool11;
                    d4 = d17;
                    d2 = d25;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 6:
                    d = d7;
                    bool7 = bool13;
                    Double d26 = (Double) compositeDecoderB.k(b, 6, DoubleSerializer.f24792a, d17);
                    i2 = 64;
                    d2 = d16;
                    i = i5;
                    bool6 = bool6;
                    d5 = d15;
                    d3 = d18;
                    d4 = d26;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 7:
                    d = d7;
                    bool7 = bool13;
                    Double d27 = (Double) compositeDecoderB.k(b, 7, DoubleSerializer.f24792a, d18);
                    i2 = 128;
                    d4 = d17;
                    i = i5;
                    bool6 = bool6;
                    d3 = d27;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 8:
                    d = d7;
                    i2 = 256;
                    bool7 = (Boolean) compositeDecoderB.k(b, 8, BooleanSerializer.f24779a, bool13);
                    i = i5;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 9:
                    d = d7;
                    i2 = 512;
                    d19 = (Double) compositeDecoderB.k(b, 9, DoubleSerializer.f24792a, d19);
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 10:
                    bool6 = (Boolean) compositeDecoderB.k(b, 10, BooleanSerializer.f24779a, bool6);
                    i2 = 1024;
                    d = d7;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 11:
                    d7 = (Double) compositeDecoderB.k(b, 11, DoubleSerializer.f24792a, d7);
                    i2 = 2048;
                    d = d7;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 12:
                    i3 = 4096;
                    d = d7;
                    d10 = (Double) compositeDecoderB.k(b, 12, DoubleSerializer.f24792a, d10);
                    i2 = i3;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 13:
                    i3 = 8192;
                    d = d7;
                    d11 = (Double) compositeDecoderB.k(b, 13, DoubleSerializer.f24792a, d11);
                    i2 = i3;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 14:
                    i3 = 16384;
                    d = d7;
                    d12 = (Double) compositeDecoderB.k(b, 14, DoubleSerializer.f24792a, d12);
                    i2 = i3;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 15:
                    i3 = 32768;
                    d = d7;
                    bool8 = (Boolean) compositeDecoderB.k(b, 15, BooleanSerializer.f24779a, bool8);
                    i2 = i3;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 16:
                    i4 = 65536;
                    bool5 = (Boolean) compositeDecoderB.k(b, 16, BooleanSerializer.f24779a, bool5);
                    i2 = i4;
                    d = d7;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 17:
                    i3 = 131072;
                    d = d7;
                    d13 = (Double) compositeDecoderB.k(b, 17, DoubleSerializer.f24792a, d13);
                    i2 = i3;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 18:
                    i3 = 262144;
                    d = d7;
                    d14 = (Double) compositeDecoderB.k(b, 18, DoubleSerializer.f24792a, d14);
                    i2 = i3;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 19:
                    i3 = 524288;
                    d = d7;
                    list = (List) compositeDecoderB.k(b, 19, kSerializerArr[19], list);
                    i2 = i3;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 20:
                    i4 = 1048576;
                    d9 = (Double) compositeDecoderB.k(b, 20, DoubleSerializer.f24792a, d9);
                    i2 = i4;
                    d = d7;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                case 21:
                    i3 = 2097152;
                    d = d7;
                    autoStopResponse = (PositioningConfigResponse.AutoStopResponse) compositeDecoderB.k(b, 21, PositioningConfigResponse$AutoStopResponse$$serializer.INSTANCE, autoStopResponse);
                    i2 = i3;
                    i = i5;
                    bool7 = bool13;
                    d3 = d18;
                    d4 = d17;
                    d2 = d16;
                    d5 = d15;
                    bool3 = bool12;
                    bool2 = bool11;
                    bool = bool10;
                    bool10 = bool;
                    bool11 = bool2;
                    bool12 = bool3;
                    d15 = d5;
                    d16 = d2;
                    d17 = d4;
                    d18 = d3;
                    d7 = d;
                    i5 = i | i2;
                    d8 = d19;
                default:
                    throw new UnknownFieldException(iU);
            }
        }
        Boolean bool23 = bool6;
        Double d28 = d8;
        Boolean bool24 = bool11;
        Boolean bool25 = bool12;
        int i6 = i5;
        Double d29 = d10;
        Double d30 = d11;
        Double d31 = d14;
        Boolean bool26 = bool9;
        Boolean bool27 = bool10;
        Double d32 = d16;
        Boolean bool28 = bool7;
        compositeDecoderB.c(b);
        PositioningConfigResponse.AutoStopResponse autoStopResponse2 = autoStopResponse;
        return new PositioningConfigResponse(i6, bool26, bool27, bool24, bool25, d15, d32, d17, d18, bool28, d28, bool23, d7, d29, d30, d12, bool8, bool5, d13, d31, list, d9, autoStopResponse2, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.SerializationStrategy
    public void serialize(@NotNull Encoder encoder, @NotNull PositioningConfigResponse value) {
        Intrinsics.h(encoder, "encoder");
        Intrinsics.h(value, "value");
        SerialDescriptor b = getB();
        CompositeEncoder compositeEncoderB = encoder.b(b);
        PositioningConfigResponse.write$Self$internal_publishRelease(value, compositeEncoderB, b);
        compositeEncoderB.c(b);
    }
}
