package au.com.woolworths.graphql.common.fragment.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.sdui.shop.fragment.selections.AnalyticsFieldsSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.AisleSide;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.CartProductInfo;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLFloat;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.InStoreAvailabilityInfo;
import au.com.woolworths.shop.graphql.type.InStoreLocationDetails;
import au.com.woolworths.shop.graphql.type.InStoreLocationDisplayInfo;
import au.com.woolworths.shop.graphql.type.InStoreLocationInfo;
import au.com.woolworths.shop.graphql.type.InStoreLocationType;
import au.com.woolworths.shop.graphql.type.InfoSheet;
import au.com.woolworths.shop.graphql.type.MemberPriceInfo;
import au.com.woolworths.shop.graphql.type.MultiBuyPriceInfo;
import au.com.woolworths.shop.graphql.type.ProductCategoryItem;
import au.com.woolworths.shop.graphql.type.ProductInStoreDetails;
import au.com.woolworths.shop.graphql.type.ProductInlineLabel;
import au.com.woolworths.shop.graphql.type.ProductListMarketplace;
import au.com.woolworths.shop.graphql.type.ProductPromotionInfo;
import au.com.woolworths.shop.graphql.type.ProductPromotionTypes;
import au.com.woolworths.shop.graphql.type.ProductShoppingList;
import au.com.woolworths.shop.graphql.type.ProductTrolley;
import au.com.woolworths.shop.graphql.type.ProductVarieties;
import au.com.woolworths.shop.graphql.type.PurchaseRestriction;
import au.com.woolworths.shop.graphql.type.RewardsOfferAnalytics;
import au.com.woolworths.shop.graphql.type.RewardsOfferInfo;
import au.com.woolworths.shop.graphql.type.RewardsOfferStatus;
import au.com.woolworths.shop.graphql.type.TagLabel;
import au.com.woolworths.shop.graphql.type.TagStyle;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.google.android.gms.measurement.api.AppMeasurementSdk;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.ErrorBundle;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/graphql/common/fragment/selections/ProductCardSelections;", "", "shop-product_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes4.dex */
public final class ProductCardSelections {
    public static final List A;

    /* renamed from: a, reason: collision with root package name */
    public static final List f9027a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        CompiledField compiledFieldC = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g(UrlHandler.ACTION, customScalarType);
        ButtonStyle.e.getClass();
        EnumType enumType = ButtonStyle.f;
        CompiledField compiledFieldC2 = new CompiledField.Builder("style", enumType).c();
        CustomScalarType customScalarType2 = GraphQLBoolean.f11439a;
        List listR = CollectionsKt.R(compiledFieldC, compiledFieldG, compiledFieldC2, new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType2)).c());
        f9027a = listR;
        List listR2 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g(UrlHandler.ACTION, customScalarType), a.d("style", enumType), new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType2)).c());
        b = listR2;
        CompiledField compiledFieldC3 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType = Button.f11080a;
        CompiledField.Builder builder = new CompiledField.Builder("button", CompiledGraphQL.b(objectType));
        builder.e = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC3, compiledFieldC4, builder.c());
        c = listR3;
        CompiledField.Builder builder2 = new CompiledField.Builder("button", CompiledGraphQL.b(objectType));
        builder2.e = listR;
        CompiledField compiledFieldC5 = builder2.c();
        CompiledField.Builder builder3 = new CompiledField.Builder("status", customScalarType);
        builder3.c = a.s("includeAvailabilityInfoStatus", false);
        CompiledField compiledFieldC6 = builder3.c();
        CompiledField.Builder builder4 = new CompiledField.Builder("infoSheet", InfoSheet.f11498a);
        builder4.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC5, compiledFieldC6, builder4.c());
        d = listR4;
        ProductPromotionTypes.e.getClass();
        List listR5 = CollectionsKt.R(new CompiledField.Builder("type", CompiledGraphQL.b(ProductPromotionTypes.f)).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c());
        e = listR5;
        CompiledField compiledFieldC7 = new CompiledField.Builder("type", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC8 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType3 = GraphQLInt.f11442a;
        List listR6 = CollectionsKt.R(compiledFieldC7, compiledFieldC8, new CompiledField.Builder("priority", customScalarType3).c());
        f = listR6;
        CompiledField compiledFieldC9 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("ProductTrolley", CollectionsKt.Q("ProductTrolley"));
        List list = ProductTrolleySelections.f9029a;
        builder5.b(list);
        List listR7 = CollectionsKt.R(compiledFieldC9, builder5.a());
        g = listR7;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("ProductTrolley", CollectionsKt.Q("ProductTrolley"));
        builder6.d = list;
        List listR8 = CollectionsKt.R(compiledFieldC10, builder6.a());
        h = listR8;
        CustomScalarType customScalarType4 = GraphQLFloat.f11440a;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("minimum", CompiledGraphQL.b(customScalarType4)).c(), new CompiledField.Builder("maximum", CompiledGraphQL.b(customScalarType4)).c(), new CompiledField.Builder("increment", CompiledGraphQL.b(customScalarType4)).c(), new CompiledField.Builder("default", CompiledGraphQL.b(customScalarType4)).c(), d.g("unit", customScalarType));
        i = listR9;
        CompiledField compiledFieldG2 = d.g("locationText", customScalarType);
        InStoreLocationType.e.getClass();
        EnumType enumType2 = InStoreLocationType.f;
        List listR10 = CollectionsKt.R(compiledFieldG2, new CompiledField.Builder("locationType", enumType2).c());
        j = listR10;
        CompiledField compiledFieldC11 = new CompiledField.Builder("aisleNumber", CompiledGraphQL.b(customScalarType3)).c();
        AisleSide.e.getClass();
        List listR11 = CollectionsKt.R(compiledFieldC11, new CompiledField.Builder("aisleSide", CompiledGraphQL.b(AisleSide.f)).c(), new CompiledField.Builder("bayNumber", CompiledGraphQL.b(customScalarType3)).c(), d.g("bayNumberAlternate", customScalarType3), new CompiledField.Builder("floorNumber", CompiledGraphQL.b(customScalarType3)).c(), d.g("location", customScalarType), new CompiledField.Builder("x", CompiledGraphQL.b(customScalarType4)).c(), new CompiledField.Builder("y", CompiledGraphQL.b(customScalarType4)).c(), new CompiledField.Builder("z", CompiledGraphQL.b(customScalarType4)).c());
        k = listR11;
        List listR12 = CollectionsKt.R(d.g("locationText", customScalarType), a.d("locationType", enumType2));
        l = listR12;
        CompiledField.Builder builder7 = new CompiledField.Builder(ErrorBundle.DETAIL_ENTRY, InStoreLocationDetails.f11492a);
        builder7.e = listR11;
        CompiledField compiledFieldC12 = builder7.c();
        CompiledField.Builder builder8 = new CompiledField.Builder("displayInfo", InStoreLocationDisplayInfo.f11493a);
        builder8.e = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC12, builder8.c());
        m = listR13;
        CompiledField compiledFieldC13 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC14 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC15 = new CompiledField.Builder("sellerName", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("brandName", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder9 = new CompiledField.Builder("lowestMarketPriceDescription", customScalarType);
        builder9.c = a.s("includeLowestPrice14Days", false);
        List listR14 = CollectionsKt.R(compiledFieldC13, compiledFieldC14, compiledFieldC15, compiledFieldC16, builder9.c());
        n = listR14;
        List listR15 = CollectionsKt.R(d.g("offerName", customScalarType), d.g("campaignStream", customScalarType), d.g("channel", customScalarType), d.g("status", customScalarType), d.g("offerType", customScalarType), d.g("partnerId", customScalarType), d.g("rtlAccountID", customScalarType), d.g("rtlCampaignID", customScalarType), d.g("rtlCampaignCode", customScalarType));
        o = listR15;
        List listR16 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), a.d("style", enumType), new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType2)).c());
        p = listR16;
        CompiledField compiledFieldC17 = new CompiledField.Builder("offerId", CompiledGraphQL.b(customScalarType)).c();
        RewardsOfferStatus.e.getClass();
        CompiledField compiledFieldC18 = new CompiledField.Builder("offerStatus", CompiledGraphQL.b(RewardsOfferStatus.f)).c();
        CompiledField compiledFieldG3 = d.g("displayStatus", customScalarType);
        CompiledField compiledFieldC19 = new CompiledField.Builder("displayExpiry", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder10 = new CompiledField.Builder("minimumSpend", customScalarType);
        builder10.c = a.s("includeOfferMinimumSpend", false);
        CompiledField compiledFieldC20 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("offerAnalytics", RewardsOfferAnalytics.f11883a);
        builder11.e = listR15;
        CompiledField compiledFieldC21 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("boostButton", objectType);
        builder12.e = listR16;
        List listR17 = CollectionsKt.R(compiledFieldC17, compiledFieldC18, compiledFieldG3, compiledFieldC19, compiledFieldC20, compiledFieldC21, builder12.c());
        q = listR17;
        CompiledField compiledFieldC22 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c();
        TagStyle.e.getClass();
        List listR18 = CollectionsKt.R(compiledFieldC22, new CompiledField.Builder("style", TagStyle.f).c());
        r = listR18;
        List listR19 = CollectionsKt.R(new CompiledField.Builder("totalCount", CompiledGraphQL.b(customScalarType3)).c(), d.g(AnnotatedPrivateKey.LABEL, customScalarType), new CompiledField.Builder("priceFamilyId", CompiledGraphQL.b(customScalarType)).c());
        s = listR19;
        List listR20 = CollectionsKt.R(d.g(AppMeasurementSdk.ConditionalUserProperty.NAME, customScalarType), d.g("categoryLevel", customScalarType3));
        t = listR20;
        List listR21 = CollectionsKt.R(new CompiledField.Builder("header", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType));
        u = listR21;
        List listR22 = CollectionsKt.R(new CompiledField.Builder("price", CompiledGraphQL.b(customScalarType)).c(), d.g("unitPrice", customScalarType));
        v = listR22;
        List listR23 = CollectionsKt.R(d.g("totalPrice", customScalarType), d.g("totalOriginalPrice", customScalarType), d.g("totalDiscount", customScalarType));
        w = listR23;
        CompiledField compiledFieldC23 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        List list2 = AnalyticsFieldsSelections.b;
        builder13.b(list2);
        List listR24 = CollectionsKt.R(compiledFieldC23, builder13.a());
        x = listR24;
        CompiledField compiledFieldC24 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder14.b(list2);
        List listR25 = CollectionsKt.R(compiledFieldC24, builder14.a());
        y = listR25;
        CompiledField compiledFieldC25 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        ActionType.e.getClass();
        CompiledField compiledFieldC26 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.f)).c();
        CompiledField compiledFieldG4 = d.g("id", customScalarType);
        ObjectType objectType2 = Analytics.f11028a;
        CompiledField.Builder builder15 = new CompiledField.Builder("analytics", objectType2);
        builder15.e = listR25;
        List listR26 = CollectionsKt.R(compiledFieldC25, compiledFieldC26, compiledFieldG4, builder15.c());
        z = listR26;
        CompiledField compiledFieldC27 = new CompiledField.Builder("productId", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC28 = new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC29 = new CompiledField.Builder("isNew", CompiledGraphQL.b(customScalarType2)).c();
        PurchaseRestriction.e.getClass();
        CompiledField compiledFieldC30 = new CompiledField.Builder("purchaseRestriction", PurchaseRestriction.f).c();
        CompiledField compiledFieldG5 = d.g("productImage", customScalarType);
        CompiledField compiledFieldC31 = new CompiledField.Builder("isAvailable", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder16 = new CompiledField.Builder("inStoreAvailabilityInfo", InStoreAvailabilityInfo.f11488a);
        builder16.c = a.s("includeProductAvailabilityStates", false);
        builder16.e = listR4;
        CompiledField compiledFieldC32 = builder16.c();
        CompiledField compiledFieldG6 = d.g("price", customScalarType3);
        CompiledField compiledFieldG7 = d.g("unitOfMeasureLabel", customScalarType);
        CompiledField compiledFieldG8 = d.g("badgeImage", customScalarType);
        CompiledField.Builder builder17 = new CompiledField.Builder("promotionInfo", ProductPromotionInfo.f11762a);
        builder17.e = listR5;
        CompiledField compiledFieldC33 = builder17.c();
        CompiledField compiledFieldG9 = d.g("unitPriceDescription", customScalarType);
        CompiledField compiledFieldG10 = d.g("wasPrice", customScalarType);
        CompiledField compiledFieldG11 = d.g("purchaseWarning", customScalarType);
        CompiledField.Builder builder18 = new CompiledField.Builder("inlineLabels", CompiledGraphQL.a(ProductInlineLabel.f11747a));
        builder18.e = listR6;
        CompiledField compiledFieldC34 = builder18.c();
        ObjectType objectType3 = ProductTrolley.f11792a;
        CompiledField.Builder builder19 = new CompiledField.Builder("trolley", objectType3);
        builder19.e = listR7;
        CompiledField compiledFieldC35 = builder19.c();
        CompiledField.Builder builder20 = new CompiledField.Builder("trolleys", CompiledGraphQL.a(CompiledGraphQL.b(objectType3)));
        builder20.e = listR8;
        CompiledField compiledFieldC36 = builder20.c();
        CompiledField.Builder builder21 = new CompiledField.Builder("list", CompiledGraphQL.b(ProductShoppingList.f11785a));
        builder21.e = listR9;
        CompiledField compiledFieldC37 = builder21.c();
        CompiledField.Builder builder22 = new CompiledField.Builder("inStoreDetails", ProductInStoreDetails.f11746a);
        builder22.e = listR10;
        CompiledField compiledFieldC38 = builder22.c();
        CompiledField.Builder builder23 = new CompiledField.Builder("inStoreLocation", InStoreLocationInfo.f11494a);
        builder23.e = listR13;
        CompiledField compiledFieldC39 = builder23.c();
        CompiledField compiledFieldG12 = d.g("adId", customScalarType);
        CompiledField compiledFieldG13 = d.g("source", customScalarType);
        CompiledField.Builder builder24 = new CompiledField.Builder("marketplace", ProductListMarketplace.f11755a);
        builder24.e = listR14;
        CompiledField compiledFieldC40 = builder24.c();
        CompiledField.Builder builder25 = new CompiledField.Builder("rewardsOfferInfo", RewardsOfferInfo.f11884a);
        builder25.e = listR17;
        CompiledField compiledFieldC41 = builder25.c();
        CompiledField compiledFieldG14 = d.g("disclaimer", customScalarType);
        CompiledField.Builder builder26 = new CompiledField.Builder("tagLabel", TagLabel.f11962a);
        builder26.e = listR18;
        CompiledField compiledFieldC42 = builder26.c();
        CompiledField.Builder builder27 = new CompiledField.Builder("productVarieties", ProductVarieties.f11793a);
        builder27.e = listR19;
        CompiledField compiledFieldC43 = builder27.c();
        CompiledField.Builder builder28 = new CompiledField.Builder("categories", CompiledGraphQL.a(CompiledGraphQL.b(ProductCategoryItem.f11719a)));
        builder28.e = listR20;
        CompiledField compiledFieldC44 = builder28.c();
        CompiledField compiledFieldC45 = new CompiledField.Builder("isTobacco", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder29 = new CompiledField.Builder("memberPriceInfo", MemberPriceInfo.f11567a);
        builder29.e = listR21;
        CompiledField compiledFieldC46 = builder29.c();
        CompiledField.Builder builder30 = new CompiledField.Builder("multiBuyPriceInfo", MultiBuyPriceInfo.f11602a);
        builder30.e = listR22;
        CompiledField compiledFieldC47 = builder30.c();
        CompiledField.Builder builder31 = new CompiledField.Builder("cartProductInfo", CartProductInfo.f11112a);
        builder31.e = listR23;
        CompiledField compiledFieldC48 = builder31.c();
        CompiledField.Builder builder32 = new CompiledField.Builder("productCardAnalytics", objectType2);
        builder32.e = listR24;
        CompiledField compiledFieldC49 = builder32.c();
        CompiledField.Builder builder33 = new CompiledField.Builder("productCardAction", Action.f10997a);
        builder33.e = listR26;
        CompiledField compiledFieldC50 = builder33.c();
        CompiledField.Builder builder34 = new CompiledField.Builder("pricingFootnoteMd", customScalarType);
        builder34.c = a.s("includePricingFootnote", false);
        A = CollectionsKt.R(compiledFieldC27, compiledFieldC28, compiledFieldC29, compiledFieldC30, compiledFieldG5, compiledFieldC31, compiledFieldC32, compiledFieldG6, compiledFieldG7, compiledFieldG8, compiledFieldC33, compiledFieldG9, compiledFieldG10, compiledFieldG11, compiledFieldC34, compiledFieldC35, compiledFieldC36, compiledFieldC37, compiledFieldC38, compiledFieldC39, compiledFieldG12, compiledFieldG13, compiledFieldC40, compiledFieldC41, compiledFieldG14, compiledFieldC42, compiledFieldC43, compiledFieldC44, compiledFieldC45, compiledFieldC46, compiledFieldC47, compiledFieldC48, compiledFieldC49, compiledFieldC50, builder34.c());
    }
}
