package com.woolworths.shop.deliveryunlimited.wpay.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.sdui.shop.fragment.selections.AnalyticsFieldsSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedIconItem;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedPayment;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribeFooter;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribeLink;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribeTerms;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribeTermsItem;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.PaymentMethodItem;
import au.com.woolworths.shop.graphql.type.PaymentMethodSection;
import au.com.woolworths.shop.graphql.type.Query;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/deliveryunlimited/wpay/selections/DeliveryUnlimitedPaymentQuerySelections;", "", "shop-delivery-unlimited-sign-up_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class DeliveryUnlimitedPaymentQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f22711a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        List listR = CollectionsKt.R(new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c());
        f22711a = listR;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        List list = AnalyticsFieldsSelections.b;
        builder.b(list);
        List listR2 = CollectionsKt.R(compiledFieldC, builder.a());
        b = listR2;
        CompiledField compiledFieldC2 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType = Analytics.f11028a;
        CompiledField.Builder builder2 = new CompiledField.Builder("clickAnalytics", CompiledGraphQL.b(objectType));
        builder2.e = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC2, builder2.c());
        c = listR3;
        CompiledField compiledFieldC3 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField compiledFieldC5 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLBoolean.f11439a;
        List listR4 = CollectionsKt.R(compiledFieldC3, compiledFieldC4, compiledFieldG, compiledFieldC5, new CompiledField.Builder("isSelected", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("amountTitle", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amountValue", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amountToPay", CompiledGraphQL.b(GraphQLInt.f11442a)).c(), new CompiledField.Builder("cvvUrl", CompiledGraphQL.b(customScalarType)).c());
        d = listR4;
        List listR5 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType), new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(customScalarType)).c());
        e = listR5;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("AddCreditCard", CollectionsKt.Q("AddCreditCard"));
        builder3.d = listR3;
        CompiledFragment compiledFragmentA = builder3.a();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("LinkedCreditCard", CollectionsKt.Q("LinkedCreditCard"));
        builder4.d = listR4;
        CompiledFragment compiledFragmentA2 = builder4.a();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("ExpiredCreditCard", CollectionsKt.Q("ExpiredCreditCard"));
        builder5.d = listR5;
        List listR6 = CollectionsKt.R(compiledFieldC6, compiledFragmentA, compiledFragmentA2, builder5.a());
        f = listR6;
        CompiledField compiledFieldC7 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder6 = new CompiledField.Builder("paymentMethods", d.j(PaymentMethodItem.f11691a));
        builder6.e = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC7, builder6.c());
        g = listR7;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder7.d = list;
        List listR8 = CollectionsKt.R(compiledFieldC8, builder7.a());
        h = listR8;
        CompiledField compiledFieldC9 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        ButtonStyle.e.getClass();
        EnumType enumType = ButtonStyle.f;
        List listR9 = CollectionsKt.R(compiledFieldC9, new CompiledField.Builder("style", enumType).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType2)).c());
        i = listR9;
        ObjectType objectType2 = Button.f11080a;
        CompiledField.Builder builder8 = new CompiledField.Builder("button", CompiledGraphQL.b(objectType2));
        builder8.e = listR9;
        List listR10 = CollectionsKt.R(builder8.c(), new CompiledField.Builder("disclaimer", CompiledGraphQL.b(customScalarType)).c());
        j = listR10;
        List listR11 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        k = listR11;
        CompiledField compiledFieldC10 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder9 = new CompiledField.Builder("links", a.f(DeliveryUnlimitedSubscribeLink.f11329a));
        builder9.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC10, builder9.c());
        l = listR12;
        CompiledField compiledFieldC11 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder10.d = list;
        List listR13 = CollectionsKt.R(compiledFieldC11, builder10.a());
        m = listR13;
        CompiledField.Builder builder11 = new CompiledField.Builder("analytics", objectType);
        builder11.e = listR13;
        List listQ = CollectionsKt.Q(builder11.c());
        n = listQ;
        CompiledField compiledFieldC12 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldD = a.d("style", enumType);
        CompiledField compiledFieldC13 = new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder12 = new CompiledField.Builder("buttonAction", Action.f10997a);
        builder12.e = listQ;
        List listR14 = CollectionsKt.R(compiledFieldC12, compiledFieldD, compiledFieldC13, builder12.c());
        o = listR14;
        CompiledField compiledFieldC14 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder13.d = list;
        List listR15 = CollectionsKt.R(compiledFieldC14, builder13.a());
        p = listR15;
        CompiledField compiledFieldC15 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder14 = new CompiledField.Builder("terms", a.f(DeliveryUnlimitedSubscribeTermsItem.f11340a));
        builder14.e = listR12;
        CompiledField compiledFieldC16 = builder14.c();
        CompiledField.Builder builder15 = new CompiledField.Builder("button", CompiledGraphQL.b(objectType2));
        builder15.e = listR14;
        CompiledField compiledFieldC17 = builder15.c();
        CompiledField.Builder builder16 = new CompiledField.Builder("impressionAnalytics", objectType);
        builder16.e = listR15;
        List listR16 = CollectionsKt.R(compiledFieldC15, compiledFieldC16, compiledFieldC17, builder16.c());
        q = listR16;
        CompiledField compiledFieldC18 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC19 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG2 = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CompiledField.Builder builder17 = new CompiledField.Builder("iconItem", DeliveryUnlimitedIconItem.f11317a);
        builder17.e = listR;
        CompiledField compiledFieldC20 = builder17.c();
        CompiledField.Builder builder18 = new CompiledField.Builder("paymentMethodSection", CompiledGraphQL.b(PaymentMethodSection.f11692a));
        builder18.e = listR7;
        CompiledField compiledFieldC21 = builder18.c();
        CompiledField.Builder builder19 = new CompiledField.Builder("analytics", a.f(objectType));
        builder19.e = listR8;
        CompiledField compiledFieldC22 = builder19.c();
        CompiledField.Builder builder20 = new CompiledField.Builder("footer", CompiledGraphQL.b(DeliveryUnlimitedSubscribeFooter.f11328a));
        builder20.e = listR10;
        CompiledField compiledFieldC23 = builder20.c();
        CompiledField.Builder builder21 = new CompiledField.Builder("terms", CompiledGraphQL.b(DeliveryUnlimitedSubscribeTerms.f11339a));
        builder21.e = listR16;
        List listR17 = CollectionsKt.R(compiledFieldC18, compiledFieldC19, compiledFieldG2, compiledFieldC20, compiledFieldC21, compiledFieldC22, compiledFieldC23, builder21.c());
        r = listR17;
        CompiledField.Builder builder22 = new CompiledField.Builder("deliveryUnlimitedPayment", CompiledGraphQL.b(DeliveryUnlimitedPayment.f11318a));
        new CompiledArgument.Builder(Query.m);
        builder22.d = au.com.woolworths.android.onesite.a.v();
        builder22.e = listR17;
        s = CollectionsKt.Q(builder22.c());
    }
}
