package com.woolworths.feature.shop.bundles.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.graphql.common.fragment.selections.ProductCardSelections;
import au.com.woolworths.sdui.shop.fragment.selections.AnalyticsFieldsSelections;
import au.com.woolworths.sdui.shop.fragment.selections.CompatibleColorSelections;
import au.com.woolworths.sdui.shop.fragment.selections.CoreTagUISelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.BundleCTA;
import au.com.woolworths.shop.graphql.type.BundleDetails;
import au.com.woolworths.shop.graphql.type.BundleItem;
import au.com.woolworths.shop.graphql.type.BundlePricing;
import au.com.woolworths.shop.graphql.type.BundleSortOption;
import au.com.woolworths.shop.graphql.type.BundleSortOptions;
import au.com.woolworths.shop.graphql.type.BundleTitleTag;
import au.com.woolworths.shop.graphql.type.Bundles;
import au.com.woolworths.shop.graphql.type.BundlesFeedItem;
import au.com.woolworths.shop.graphql.type.BundlesHeader;
import au.com.woolworths.shop.graphql.type.Chip;
import au.com.woolworths.shop.graphql.type.CompatibleColor;
import au.com.woolworths.shop.graphql.type.CoreAlertStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerUI;
import au.com.woolworths.shop.graphql.type.CoreInsetAlertUI;
import au.com.woolworths.shop.graphql.type.CoreRadioRowUI;
import au.com.woolworths.shop.graphql.type.CoreTagUI;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLID;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.IconAsset;
import au.com.woolworths.shop.graphql.type.Link;
import au.com.woolworths.shop.graphql.type.ProductCard;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.TextWithAlt;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/feature/shop/bundles/selections/BundlesQuerySelections;", "", "bundles_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class BundlesQuerySelections {
    public static final List A;
    public static final List B;
    public static final List C;
    public static final List D;
    public static final List E;
    public static final List F;
    public static final List G;
    public static final List H;
    public static final List I;
    public static final List J;
    public static final List K;
    public static final List L;
    public static final List M;
    public static final List N;
    public static final List O;
    public static final List P;
    public static final List Q;
    public static final List R;
    public static final List S;
    public static final List T;
    public static final List U;
    public static final List V;

    /* renamed from: a, reason: collision with root package name */
    public static final List f19502a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        List list = AnalyticsFieldsSelections.b;
        builder.b(list);
        List listR = CollectionsKt.R(compiledFieldC, builder.a());
        f19502a = listR;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder2.b(list);
        List listR2 = CollectionsKt.R(compiledFieldC2, builder2.a());
        b = listR2;
        CompiledField compiledFieldG = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CompiledField compiledFieldC3 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLBoolean.f11439a;
        List listR3 = CollectionsKt.R(compiledFieldG, compiledFieldC3, new CompiledField.Builder("isSelected", CompiledGraphQL.b(customScalarType2)).c());
        c = listR3;
        CompiledField compiledFieldC4 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder3 = new CompiledField.Builder("coreRadioRowUI", CompiledGraphQL.b(CoreRadioRowUI.f11292a));
        builder3.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC4, builder3.c());
        d = listR4;
        CompiledField compiledFieldC5 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder4 = new CompiledField.Builder("options", a.f(BundleSortOption.f11070a));
        builder4.e = listR4;
        List listR5 = CollectionsKt.R(compiledFieldC5, builder4.c());
        e = listR5;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("BundleSortOptions", CollectionsKt.Q("BundleSortOptions"));
        builder5.d = listR5;
        List listR6 = CollectionsKt.R(compiledFieldC6, builder5.a());
        f = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        g = listR7;
        CompiledField compiledFieldC7 = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLID.f11441a)).c();
        CompiledField compiledFieldC8 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(customScalarType2)).c();
        ObjectType objectType = TextWithAlt.f11967a;
        CompiledField.Builder builder6 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(objectType));
        builder6.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC7, compiledFieldC8, builder6.c());
        h = listR8;
        CompiledField.Builder builder7 = new CompiledField.Builder("sortOptions", BundleSortOptions.f11071a);
        builder7.e = listR6;
        CompiledField compiledFieldC9 = builder7.c();
        CompiledField.Builder builder8 = new CompiledField.Builder("chips", CompiledGraphQL.a(CompiledGraphQL.b(Chip.f11271a)));
        builder8.e = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC9, builder8.c(), new CompiledField.Builder("totalBundles", CompiledGraphQL.b(customScalarType)).c());
        i = listR9;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder9.b(list);
        List listR10 = CollectionsKt.R(compiledFieldC10, builder9.a());
        j = listR10;
        CompiledField compiledFieldC11 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder10.b(list);
        List listR11 = CollectionsKt.R(compiledFieldC11, builder10.a());
        k = listR11;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(customScalarType)).c());
        l = listQ;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        m = listQ2;
        CompiledField compiledFieldC12 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder11.d = listQ;
        CompiledFragment compiledFragmentA = builder11.a();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder12.d = listQ2;
        List listR12 = CollectionsKt.R(compiledFieldC12, compiledFragmentA, builder12.a());
        n = listR12;
        CompiledField compiledFieldC13 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG2 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CoreBroadcastBannerStyle.e.getClass();
        CompiledField compiledFieldC14 = new CompiledField.Builder("style", CompiledGraphQL.b(CoreBroadcastBannerStyle.f)).c();
        CompiledField.Builder builder13 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(IconAsset.f11477a));
        builder13.e = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC13, compiledFieldG2, compiledFieldC14, builder13.c());
        o = listR13;
        CompiledField compiledFieldC15 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG3 = d.g("id", customScalarType);
        ActionType.e.getClass();
        EnumType enumType = ActionType.f;
        List listR14 = CollectionsKt.R(compiledFieldC15, compiledFieldG3, new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c());
        p = listR14;
        ObjectType objectType2 = Analytics.f11028a;
        CompiledField.Builder builder14 = new CompiledField.Builder("impressionAnalytics", objectType2);
        builder14.e = listR10;
        CompiledField compiledFieldC16 = builder14.c();
        CompiledField.Builder builder15 = new CompiledField.Builder("broadcastBannerDismissAnalytics", objectType2);
        builder15.e = listR11;
        CompiledField compiledFieldC17 = builder15.c();
        CompiledField.Builder builder16 = new CompiledField.Builder("broadcastBannerUI", CompiledGraphQL.b(CoreBroadcastBannerUI.f11286a));
        builder16.e = listR13;
        CompiledField compiledFieldC18 = builder16.c();
        ObjectType objectType3 = Action.f10997a;
        CompiledField.Builder builder17 = new CompiledField.Builder("broadcastBannerAction", objectType3);
        builder17.e = listR14;
        List listR15 = CollectionsKt.R(compiledFieldC16, compiledFieldC17, compiledFieldC18, builder17.c(), d.g("broadcastBannerActionLabel", customScalarType), d.g("broadcastBannerId", customScalarType), new CompiledField.Builder("broadcastBannerDismissible", CompiledGraphQL.b(customScalarType2)).c());
        q = listR15;
        CompiledField compiledFieldG4 = d.g("title", customScalarType);
        CompiledField compiledFieldG5 = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CoreAlertStyle.e.getClass();
        List listR16 = CollectionsKt.R(compiledFieldG4, compiledFieldG5, new CompiledField.Builder("style", CompiledGraphQL.b(CoreAlertStyle.f)).c());
        r = listR16;
        CompiledField compiledFieldC19 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder18.b(list);
        List listR17 = CollectionsKt.R(compiledFieldC19, builder18.a());
        s = listR17;
        CompiledField compiledFieldC20 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG6 = d.g("id", customScalarType);
        CompiledField compiledFieldC21 = new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c();
        CompiledField.Builder builder19 = new CompiledField.Builder("analytics", objectType2);
        builder19.e = listR17;
        List listR18 = CollectionsKt.R(compiledFieldC20, compiledFieldG6, compiledFieldC21, builder19.c());
        t = listR18;
        CompiledField compiledFieldC22 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder20 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder20.b(list);
        List listR19 = CollectionsKt.R(compiledFieldC22, builder20.a());
        u = listR19;
        CompiledField.Builder builder21 = new CompiledField.Builder("insetAlertUI", CompiledGraphQL.b(CoreInsetAlertUI.f11291a));
        builder21.e = listR16;
        CompiledField compiledFieldC23 = builder21.c();
        CompiledField compiledFieldG7 = d.g("insetAlertActionLabel", customScalarType);
        CompiledField.Builder builder22 = new CompiledField.Builder("insetAlertAction", objectType3);
        builder22.e = listR18;
        CompiledField compiledFieldC24 = builder22.c();
        CompiledField.Builder builder23 = new CompiledField.Builder("impressionAnalytics", objectType2);
        builder23.e = listR19;
        List listR20 = CollectionsKt.R(compiledFieldC23, compiledFieldG7, compiledFieldC24, builder23.c());
        v = listR20;
        CompiledField compiledFieldC25 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder24 = new CompiledFragment.Builder("CompatibleColor", CollectionsKt.Q("CompatibleColor"));
        builder24.b(CompatibleColorSelections.f10082a);
        List listR21 = CollectionsKt.R(compiledFieldC25, builder24.a());
        w = listR21;
        CompiledField compiledFieldC26 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder25 = new CompiledField.Builder("textColor", CompiledGraphQL.b(CompatibleColor.f11275a));
        builder25.e = listR21;
        List listR22 = CollectionsKt.R(compiledFieldC26, builder25.c());
        x = listR22;
        CompiledField compiledFieldC27 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("CoreTagUI", CollectionsKt.Q("CoreTagUI"));
        builder26.b(CoreTagUISelections.h);
        List listR23 = CollectionsKt.R(compiledFieldC27, builder26.a());
        y = listR23;
        CompiledField compiledFieldC28 = new CompiledField.Builder("prefix", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC29 = new CompiledField.Builder("price", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder27 = new CompiledField.Builder("tag", CoreTagUI.f11294a);
        builder27.e = listR23;
        List listR24 = CollectionsKt.R(compiledFieldC28, compiledFieldC29, builder27.c());
        z = listR24;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder("logo", customScalarType).c());
        A = listQ3;
        CompiledField compiledFieldC30 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder28 = new CompiledFragment.Builder("BundleStandardPricing", CollectionsKt.Q("BundleStandardPricing"));
        builder28.d = listR24;
        CompiledFragment compiledFragmentA2 = builder28.a();
        CompiledFragment.Builder builder29 = new CompiledFragment.Builder("BundleComparisonPricing", CollectionsKt.Q("BundleComparisonPricing"));
        builder29.d = listQ3;
        List listR25 = CollectionsKt.R(compiledFieldC30, compiledFragmentA2, builder29.a());
        B = listR25;
        CompiledField.Builder builder30 = new CompiledField.Builder("titleTag", BundleTitleTag.f11073a);
        builder30.e = listR22;
        CompiledField compiledFieldC31 = builder30.c();
        CompiledField compiledFieldC32 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG8 = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CompiledField.Builder builder31 = new CompiledField.Builder("pricing", CompiledGraphQL.b(BundlePricing.f11066a));
        builder31.e = listR25;
        List listR26 = CollectionsKt.R(compiledFieldC31, compiledFieldC32, compiledFieldG8, builder31.c());
        C = listR26;
        CompiledField compiledFieldC33 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder32 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder32.b(ProductCardSelections.A);
        List listR27 = CollectionsKt.R(compiledFieldC33, builder32.a());
        D = listR27;
        CompiledField compiledFieldG9 = d.g("quantity", customScalarType);
        CompiledField.Builder builder33 = new CompiledField.Builder("productCard", CompiledGraphQL.b(ProductCard.f11717a));
        builder33.e = listR27;
        List listR28 = CollectionsKt.R(compiledFieldG9, builder33.c());
        E = listR28;
        CompiledField compiledFieldC34 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder34 = new CompiledFragment.Builder("BundleProductCard", CollectionsKt.Q("BundleProductCard"));
        builder34.d = listR28;
        List listR29 = CollectionsKt.R(compiledFieldC34, builder34.a());
        F = listR29;
        CustomScalarType customScalarType3 = GraphQLInt.f11442a;
        List listR30 = CollectionsKt.R(new CompiledField.Builder("minimum", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("maximum", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("increment", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("inCart", CompiledGraphQL.b(customScalarType3)).c(), new CompiledField.Builder("addToCartLabel", CompiledGraphQL.b(customScalarType)).c(), d.g("maximumReachedLabel", customScalarType), new CompiledField.Builder("offerId", CompiledGraphQL.b(customScalarType)).c());
        G = listR30;
        CompiledField compiledFieldC35 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder35 = new CompiledFragment.Builder("BundleQuantityStepper", CollectionsKt.Q("BundleQuantityStepper"));
        builder35.d = listR30;
        List listR31 = CollectionsKt.R(compiledFieldC35, builder35.a());
        H = listR31;
        CompiledField compiledFieldC36 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder36 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder36.b(list);
        List listR32 = CollectionsKt.R(compiledFieldC36, builder36.a());
        I = listR32;
        CompiledField compiledFieldC37 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder37 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder37.b(list);
        List listR33 = CollectionsKt.R(compiledFieldC37, builder37.a());
        J = listR33;
        CompiledField.Builder builder38 = new CompiledField.Builder("bundleDetails", CompiledGraphQL.b(BundleDetails.f11064a));
        builder38.e = listR26;
        CompiledField compiledFieldC38 = builder38.c();
        CompiledField.Builder builder39 = new CompiledField.Builder("bundleItems", d.j(BundleItem.f11065a));
        builder39.e = listR29;
        CompiledField compiledFieldC39 = builder39.c();
        CompiledField.Builder builder40 = new CompiledField.Builder("bundleCta", CompiledGraphQL.b(BundleCTA.f11062a));
        builder40.e = listR31;
        CompiledField compiledFieldC40 = builder40.c();
        CompiledField.Builder builder41 = new CompiledField.Builder("bundleAnalytics", objectType2);
        builder41.e = listR32;
        CompiledField compiledFieldC41 = builder41.c();
        CompiledField.Builder builder42 = new CompiledField.Builder("bundleImpressionAnalytics", objectType2);
        builder42.e = listR33;
        List listR34 = CollectionsKt.R(compiledFieldC38, compiledFieldC39, compiledFieldC40, compiledFieldC41, builder42.c(), d.g("footerText", customScalarType));
        K = listR34;
        CompiledField compiledFieldC42 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder43 = new CompiledFragment.Builder("BasicCoreBroadcastBanner", CollectionsKt.Q("BasicCoreBroadcastBanner"));
        builder43.d = listR15;
        CompiledFragment compiledFragmentA3 = builder43.a();
        CompiledFragment.Builder builder44 = new CompiledFragment.Builder("BasicInsetAlert", CollectionsKt.Q("BasicInsetAlert"));
        builder44.d = listR20;
        CompiledFragment compiledFragmentA4 = builder44.a();
        CompiledFragment.Builder builder45 = new CompiledFragment.Builder("Bundle", CollectionsKt.Q("Bundle"));
        builder45.d = listR34;
        List listR35 = CollectionsKt.R(compiledFieldC42, compiledFragmentA3, compiledFragmentA4, builder45.a());
        L = listR35;
        CompiledField.Builder builder46 = new CompiledField.Builder("analytics", objectType2);
        builder46.e = listR;
        CompiledField compiledFieldC43 = builder46.c();
        CompiledField.Builder builder47 = new CompiledField.Builder("impressionAnalytics", objectType2);
        builder47.e = listR2;
        CompiledField compiledFieldC44 = builder47.c();
        CompiledField.Builder builder48 = new CompiledField.Builder("header", CompiledGraphQL.b(BundlesHeader.f11076a));
        builder48.e = listR9;
        CompiledField compiledFieldC45 = builder48.c();
        CompiledField.Builder builder49 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(BundlesFeedItem.f11075a)));
        builder49.e = listR35;
        List listR36 = CollectionsKt.R(compiledFieldC43, compiledFieldC44, compiledFieldC45, builder49.c(), d.g("nextPageNumber", customScalarType3));
        M = listR36;
        List listR37 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        N = listR37;
        CompiledField compiledFieldC46 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder50 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder50.b(list);
        List listR38 = CollectionsKt.R(compiledFieldC46, builder50.a());
        O = listR38;
        CompiledField compiledFieldC47 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG10 = d.g("id", customScalarType);
        CompiledField compiledFieldC48 = new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c();
        CompiledField.Builder builder51 = new CompiledField.Builder("analytics", objectType2);
        builder51.e = listR38;
        List listR39 = CollectionsKt.R(compiledFieldC47, compiledFieldG10, compiledFieldC48, builder51.c());
        P = listR39;
        CompiledField compiledFieldG11 = d.g("linkId", customScalarType);
        CompiledField.Builder builder52 = new CompiledField.Builder("linkTextWithAlt", CompiledGraphQL.b(objectType));
        builder52.e = listR37;
        CompiledField compiledFieldC49 = builder52.c();
        CompiledField.Builder builder53 = new CompiledField.Builder("linkAction", CompiledGraphQL.b(objectType3));
        builder53.e = listR39;
        List listR40 = CollectionsKt.R(compiledFieldG11, compiledFieldC49, builder53.c());
        Q = listR40;
        CompiledField compiledFieldC50 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder54 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder54.b(list);
        List listR41 = CollectionsKt.R(compiledFieldC50, builder54.a());
        R = listR41;
        CompiledField compiledFieldC51 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder55 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder55.b(list);
        List listR42 = CollectionsKt.R(compiledFieldC51, builder55.a());
        S = listR42;
        CompiledField compiledFieldG12 = d.g("image", customScalarType);
        CompiledField compiledFieldG13 = d.g("title", customScalarType);
        CompiledField compiledFieldG14 = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CompiledField.Builder builder56 = new CompiledField.Builder("cta", Link.f11514a);
        builder56.e = listR40;
        CompiledField compiledFieldC52 = builder56.c();
        CompiledField.Builder builder57 = new CompiledField.Builder("analytics", objectType2);
        builder57.e = listR41;
        CompiledField compiledFieldC53 = builder57.c();
        CompiledField.Builder builder58 = new CompiledField.Builder("impressionAnalytics", objectType2);
        builder58.e = listR42;
        List listR43 = CollectionsKt.R(compiledFieldG12, compiledFieldG13, compiledFieldG14, compiledFieldC52, compiledFieldC53, builder58.c());
        T = listR43;
        CompiledField compiledFieldC54 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder59 = new CompiledFragment.Builder("BundlesLandingPage", CollectionsKt.Q("BundlesLandingPage"));
        builder59.d = listR36;
        CompiledFragment compiledFragmentA5 = builder59.a();
        CompiledFragment.Builder builder60 = new CompiledFragment.Builder("BundlesLandingErrorPage", CollectionsKt.Q("BundlesLandingErrorPage"));
        builder60.d = listR43;
        List listR44 = CollectionsKt.R(compiledFieldC54, compiledFragmentA5, builder60.a());
        U = listR44;
        CompiledField.Builder builder61 = new CompiledField.Builder("bundles", CompiledGraphQL.b(Bundles.f11074a));
        new CompiledArgument.Builder(Query.g);
        builder61.d = au.com.woolworths.android.onesite.a.v();
        builder61.e = listR44;
        V = CollectionsKt.Q(builder61.c());
    }
}
