package com.woolworths.feature.shop.myorders.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.AnalyticsExtraContent;
import au.com.woolworths.shop.graphql.type.BasicCoreBroadcastBanner;
import au.com.woolworths.shop.graphql.type.BayNumberPreferences;
import au.com.woolworths.shop.graphql.type.BroadcastBanner;
import au.com.woolworths.shop.graphql.type.BroadcastBannerType;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.CancelWarning;
import au.com.woolworths.shop.graphql.type.Chip;
import au.com.woolworths.shop.graphql.type.ContactItem;
import au.com.woolworths.shop.graphql.type.CoreAlertStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerUI;
import au.com.woolworths.shop.graphql.type.CoreButton;
import au.com.woolworths.shop.graphql.type.CoreButtonStyle;
import au.com.woolworths.shop.graphql.type.CoreInsetAlertUI;
import au.com.woolworths.shop.graphql.type.DeliveryInstructions;
import au.com.woolworths.shop.graphql.type.DeliveryMethodBulletInfo;
import au.com.woolworths.shop.graphql.type.DeliveryMethodsTooltip;
import au.com.woolworths.shop.graphql.type.DriverRatingFeedbackAndComments;
import au.com.woolworths.shop.graphql.type.DriverRatingStarsSurvey;
import au.com.woolworths.shop.graphql.type.DriverRatingThankYou;
import au.com.woolworths.shop.graphql.type.EditOrderWarning;
import au.com.woolworths.shop.graphql.type.EditOrderWarningItem;
import au.com.woolworths.shop.graphql.type.Feed;
import au.com.woolworths.shop.graphql.type.FeedItem;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLFloat;
import au.com.woolworths.shop.graphql.type.GraphQLID;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.HorizontalListBadge;
import au.com.woolworths.shop.graphql.type.HorizontalListItem;
import au.com.woolworths.shop.graphql.type.IconAsset;
import au.com.woolworths.shop.graphql.type.InsetBanner;
import au.com.woolworths.shop.graphql.type.InsetBannerAction;
import au.com.woolworths.shop.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.shop.graphql.type.InsetBannerActionType;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.LocationImage;
import au.com.woolworths.shop.graphql.type.LocationTrackingPrimingPage;
import au.com.woolworths.shop.graphql.type.LocationTrackingPrimingPageContent;
import au.com.woolworths.shop.graphql.type.LocationTrackingPrimingPageRationale;
import au.com.woolworths.shop.graphql.type.LocationTrackingStatusImage;
import au.com.woolworths.shop.graphql.type.MyGroceriesProductListBadgeType;
import au.com.woolworths.shop.graphql.type.OnMyWayPreferences;
import au.com.woolworths.shop.graphql.type.OrderCollectionDetails;
import au.com.woolworths.shop.graphql.type.OrderCollectionParkingDetails;
import au.com.woolworths.shop.graphql.type.OrderDetailSummary;
import au.com.woolworths.shop.graphql.type.OrderDetailsItem;
import au.com.woolworths.shop.graphql.type.OrderDetailsStatus;
import au.com.woolworths.shop.graphql.type.OrderFulfilmentType;
import au.com.woolworths.shop.graphql.type.OrderHelp;
import au.com.woolworths.shop.graphql.type.OrderHelpContactTimes;
import au.com.woolworths.shop.graphql.type.OrderHelpItem;
import au.com.woolworths.shop.graphql.type.OrderHelpItemType;
import au.com.woolworths.shop.graphql.type.OrderPaymentDetailsItem;
import au.com.woolworths.shop.graphql.type.OrderPaymentDetailsItemAmountStyle;
import au.com.woolworths.shop.graphql.type.OrderStatusType;
import au.com.woolworths.shop.graphql.type.OrderStoreDetails;
import au.com.woolworths.shop.graphql.type.OrderSubtitleIcon;
import au.com.woolworths.shop.graphql.type.OrderSummary;
import au.com.woolworths.shop.graphql.type.OrderTime;
import au.com.woolworths.shop.graphql.type.ProgressStepType;
import au.com.woolworths.shop.graphql.type.ProgressStepper;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.StepsTooltip;
import au.com.woolworths.shop.graphql.type.TextWithAlt;
import au.com.woolworths.shop.graphql.type.TooltipDeliveryMethodInfo;
import au.com.woolworths.shop.graphql.type.TooltipStepInfo;
import au.com.woolworths.shop.graphql.type.TooltipType;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledArgumentDefinition;
import com.apollographql.apollo.api.CompiledCondition;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.google.android.gms.measurement.api.AppMeasurementSdk;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/feature/shop/myorders/selections/GetOrderSummaryQuerySelections;", "", "my-orders_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class GetOrderSummaryQuerySelections {
    public static final List A;
    public static final List A0;
    public static final List B;
    public static final List B0;
    public static final List C;
    public static final List C0;
    public static final List D;
    public static final List D0;
    public static final List E;
    public static final List E0;
    public static final List F;
    public static final List F0;
    public static final List G;
    public static final List G0;
    public static final List H;
    public static final List H0;
    public static final List I;
    public static final List I0;
    public static final List J;
    public static final List J0;
    public static final List K;
    public static final List K0;
    public static final List L;
    public static final List L0;
    public static final List M;
    public static final List M0;
    public static final List N;
    public static final List N0;
    public static final List O;
    public static final List O0;
    public static final List P;
    public static final List P0;
    public static final List Q;
    public static final List Q0;
    public static final List R;
    public static final List R0;
    public static final List S;
    public static final List S0;
    public static final List T;
    public static final List T0;
    public static final List U;
    public static final List U0;
    public static final List V;
    public static final List V0;
    public static final List W;
    public static final List W0;
    public static final List X;
    public static final List X0;
    public static final List Y;
    public static final List Y0;
    public static final List Z;
    public static final List Z0;

    /* renamed from: a, reason: collision with root package name */
    public static final List f20195a;
    public static final List a0;
    public static final List a1;
    public static final List b;
    public static final List b0;
    public static final List b1;
    public static final List c;
    public static final List c0;
    public static final List c1;
    public static final List d;
    public static final List d0;
    public static final List d1;
    public static final List e;
    public static final List e0;
    public static final List e1;
    public static final List f;
    public static final List f0;
    public static final List f1;
    public static final List g;
    public static final List g0;
    public static final List g1;
    public static final List h;
    public static final List h0;
    public static final List h1;
    public static final List i;
    public static final List i0;
    public static final List j;
    public static final List j0;
    public static final List k;
    public static final List k0;
    public static final List l;
    public static final List l0;
    public static final List m;
    public static final List m0;
    public static final List n;
    public static final List n0;
    public static final List o;
    public static final List o0;
    public static final List p;
    public static final List p0;
    public static final List q;
    public static final List q0;
    public static final List r;
    public static final List r0;
    public static final List s;
    public static final List s0;
    public static final List t;
    public static final List t0;
    public static final List u;
    public static final List u0;
    public static final List v;
    public static final List v0;
    public static final List w;
    public static final List w0;
    public static final List x;
    public static final List x0;
    public static final List y;
    public static final List y0;
    public static final List z;
    public static final List z0;

    static {
        CompiledField compiledFieldC = new CompiledField.Builder("iconUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC2 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC3 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("url", GraphQLString.Companion.a()).c();
        OrderHelpItemType.e.getClass();
        EnumType enumType = OrderHelpItemType.f;
        List listR = CollectionsKt.R(compiledFieldC, compiledFieldC2, compiledFieldC3, compiledFieldC4, new CompiledField.Builder("itemType", CompiledGraphQL.b(enumType)).c());
        f20195a = listR;
        List listR2 = CollectionsKt.R(new CompiledField.Builder("iconUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c(), new CompiledField.Builder("itemType", CompiledGraphQL.b(enumType)).c());
        b = listR2;
        List listR3 = CollectionsKt.R(new CompiledField.Builder("day", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("time", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        c = listR3;
        CompiledField compiledFieldC5 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC6 = new CompiledField.Builder("subTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType = ContactItem.f11278a;
        CompiledField.Builder builder = new CompiledField.Builder("contactItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(ContactItem.Companion.a()))));
        builder.e(listR3);
        List listR4 = CollectionsKt.R(compiledFieldC5, compiledFieldC6, builder.c());
        d = listR4;
        ObjectType objectType2 = OrderHelpItem.f11652a;
        CompiledField.Builder builder2 = new CompiledField.Builder("items", a.f(objectType2));
        builder2.e(listR);
        CompiledField compiledFieldC7 = builder2.c();
        CompiledField.Builder builder3 = new CompiledField.Builder("imageUrl", GraphQLString.Companion.a());
        builder3.d(CollectionsKt.Q(new CompiledCondition("includeAsyncChat", false)));
        CompiledField compiledFieldC8 = builder3.c();
        CompiledField.Builder builder4 = new CompiledField.Builder("helpTitle", GraphQLString.Companion.a());
        builder4.d(CollectionsKt.Q(new CompiledCondition("includeAsyncChat", false)));
        CompiledField compiledFieldC9 = builder4.c();
        CompiledField compiledFieldE = com.google.android.gms.common.api.internal.a.e("includeAsyncChat", false, new CompiledField.Builder("helpItems", CompiledGraphQL.a(CompiledGraphQL.b(objectType2))), listR2);
        ObjectType objectType3 = OrderHelpContactTimes.f11651a;
        List listR5 = CollectionsKt.R(compiledFieldC7, compiledFieldC8, compiledFieldC9, compiledFieldE, com.google.android.gms.common.api.internal.a.e("includeAsyncChat", false, new CompiledField.Builder("contactTimes", OrderHelpContactTimes.Companion.a()), listR4));
        e = listR5;
        CompiledField.Builder builder5 = new CompiledField.Builder("_", GraphQLBoolean.Companion.a());
        builder5.a("dummyField");
        List listR6 = CollectionsKt.R(builder5.c(), new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        f = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("amount", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        g = listR7;
        List listR8 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("amount", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        h = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("amount", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        i = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, GraphQLString.Companion.a()).c(), new CompiledField.Builder("amount", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        j = listR10;
        List listR11 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("amount", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        k = listR11;
        CompiledField compiledFieldC10 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC11 = new CompiledField.Builder("amount", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC12 = new CompiledField.Builder("amountIcon", GraphQLString.Companion.a()).c();
        OrderPaymentDetailsItemAmountStyle.e.getClass();
        EnumType enumType2 = OrderPaymentDetailsItemAmountStyle.f;
        List listR12 = CollectionsKt.R(compiledFieldC10, compiledFieldC11, compiledFieldC12, new CompiledField.Builder("amountStyle", enumType2).c());
        l = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("amount", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), a.d("amountStyle", enumType2), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        m = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder("amount", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), a.d("amountStyle", enumType2), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        n = listR14;
        ObjectType objectType4 = OrderPaymentDetailsItem.f11662a;
        CompiledField.Builder builder6 = new CompiledField.Builder("total", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(OrderPaymentDetailsItem.Companion.a()))));
        builder6.e(listR7);
        CompiledField compiledFieldC13 = builder6.c();
        CompiledField.Builder builder7 = new CompiledField.Builder("subTotal", CompiledGraphQL.b(CompiledGraphQL.a(OrderPaymentDetailsItem.Companion.a())));
        builder7.e(listR8);
        CompiledField compiledFieldC14 = builder7.c();
        CompiledField.Builder builder8 = new CompiledField.Builder("marketSubtotal", CompiledGraphQL.b(CompiledGraphQL.a(OrderPaymentDetailsItem.Companion.a())));
        builder8.e(listR9);
        CompiledField compiledFieldC15 = builder8.c();
        CompiledField.Builder builder9 = new CompiledField.Builder("paymentMethods", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(OrderPaymentDetailsItem.Companion.a()))));
        builder9.e(listR10);
        CompiledField compiledFieldC16 = builder9.c();
        CompiledField.Builder builder10 = new CompiledField.Builder("discounts", CompiledGraphQL.b(CompiledGraphQL.a(OrderPaymentDetailsItem.Companion.a())));
        builder10.e(listR11);
        CompiledField compiledFieldC17 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("savingsAndRewards", CompiledGraphQL.b(CompiledGraphQL.a(OrderPaymentDetailsItem.Companion.a())));
        builder11.e(listR12);
        CompiledField compiledFieldC18 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("refunds", CompiledGraphQL.b(CompiledGraphQL.a(OrderPaymentDetailsItem.Companion.a())));
        builder12.e(listR13);
        CompiledField compiledFieldC19 = builder12.c();
        CompiledField.Builder builder13 = new CompiledField.Builder("refundTotal", CompiledGraphQL.b(CompiledGraphQL.a(OrderPaymentDetailsItem.Companion.a())));
        builder13.e(listR14);
        List listR15 = CollectionsKt.R(compiledFieldC13, compiledFieldC14, compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, compiledFieldC19, builder13.c(), new CompiledField.Builder("disclaimer", GraphQLString.Companion.a()).c());
        o = listR15;
        List listR16 = CollectionsKt.R(new CompiledField.Builder("stockcode", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imagePath", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("quantity", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c(), new CompiledField.Builder("salesPrice", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("pricePerUnit", GraphQLString.Companion.a()).c(), new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        p = listR16;
        CompiledField compiledFieldC20 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("OrderDetailsProductCard", CollectionsKt.Q("OrderDetailsProductCard"));
        builder14.b(listR16);
        List listR17 = CollectionsKt.R(compiledFieldC20, builder14.a());
        q = listR17;
        InsetBannerActionPlacement.e.getClass();
        CompiledField compiledFieldC21 = new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.Companion.a())).c();
        InsetBannerActionType.e.getClass();
        List listR18 = CollectionsKt.R(compiledFieldC21, new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        r = listR18;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("eventLabel", GraphQLString.Companion.a()).c());
        s = listQ;
        CompiledField compiledFieldC22 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType5 = InsetBannerAction.f11510a;
        CompiledField.Builder builder15 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.Companion.a());
        builder15.e(listR18);
        CompiledField compiledFieldC23 = builder15.c();
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC24 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        ObjectType objectType6 = Analytics.f11028a;
        CompiledField.Builder builder16 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder16.e(listQ);
        List listR19 = CollectionsKt.R(compiledFieldC22, compiledFieldC23, compiledFieldC24, builder16.c());
        t = listR19;
        CompiledField compiledFieldC25 = new CompiledField.Builder("myGroceriesProductListBadgeLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        MyGroceriesProductListBadgeType.e.getClass();
        List listR20 = CollectionsKt.R(compiledFieldC25, new CompiledField.Builder("myGroceriesProductListBadgeType", CompiledGraphQL.b(MyGroceriesProductListBadgeType.Companion.a())).c());
        u = listR20;
        CompiledField compiledFieldC26 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("MyGroceriesProductListBadge", CollectionsKt.Q("MyGroceriesProductListBadge"));
        builder17.b(listR20);
        List listR21 = CollectionsKt.R(compiledFieldC26, builder17.a());
        v = listR21;
        CompiledField compiledFieldC27 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC28 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC29 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        UnionType unionType = HorizontalListItem.f11475a;
        CompiledField.Builder builder18 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder18.e(listR17);
        CompiledField compiledFieldC30 = builder18.c();
        CompiledField compiledFieldC31 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType7 = InsetBanner.f11509a;
        CompiledField.Builder builder19 = new CompiledField.Builder("insetBanner", InsetBanner.Companion.a());
        builder19.e(listR19);
        CompiledField compiledFieldC32 = builder19.c();
        UnionType unionType2 = HorizontalListBadge.f11473a;
        List listR22 = CollectionsKt.R(compiledFieldC27, compiledFieldC28, compiledFieldC29, compiledFieldC30, compiledFieldC31, compiledFieldC32, com.google.android.gms.common.api.internal.a.e("includeOrderYourGroceriesRedesign", false, new CompiledField.Builder("badges", CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListBadge.Companion.a()))), listR21));
        w = listR22;
        List listR23 = CollectionsKt.R(new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c());
        x = listR23;
        CompiledField compiledFieldC33 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder20 = new CompiledField.Builder("insetBanner", InsetBanner.Companion.a());
        builder20.e(listR23);
        List listR24 = CollectionsKt.R(compiledFieldC33, builder20.c(), new CompiledField.Builder("imageUrl", GraphQLString.Companion.a()).c(), new CompiledField.Builder("footnote", GraphQLString.Companion.a()).c());
        y = listR24;
        List listR25 = CollectionsKt.R(new CompiledField.Builder("storeName", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("storeAddress", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("actionPath", GraphQLString.Companion.a()).c());
        z = listR25;
        List listR26 = CollectionsKt.R(new CompiledField.Builder("parkingMapUrl", GraphQLString.Companion.a()).c(), new CompiledField.Builder("parkingDirections", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c());
        A = listR26;
        CompiledField compiledFieldC34 = new CompiledField.Builder("fulfillmentLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC35 = new CompiledField.Builder("fulfillmentType", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC36 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        ObjectType objectType8 = OrderCollectionParkingDetails.f11635a;
        CompiledField.Builder builder21 = new CompiledField.Builder("parkingDetails", OrderCollectionParkingDetails.Companion.a());
        builder21.e(listR26);
        List listR27 = CollectionsKt.R(compiledFieldC34, compiledFieldC35, compiledFieldC36, builder21.c());
        B = listR27;
        ObjectType objectType9 = OrderStoreDetails.f11673a;
        CompiledField.Builder builder22 = new CompiledField.Builder("storeDetails", CompiledGraphQL.b(OrderStoreDetails.Companion.a()));
        builder22.e(listR25);
        CompiledField compiledFieldC37 = builder22.c();
        ObjectType objectType10 = OrderCollectionDetails.f11634a;
        CompiledField.Builder builder23 = new CompiledField.Builder("collectionDetails", CompiledGraphQL.b(OrderCollectionDetails.Companion.a()));
        builder23.e(listR27);
        List listR28 = CollectionsKt.R(compiledFieldC37, builder23.c());
        C = listR28;
        CompiledField compiledFieldC38 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC39 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC40 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        LocationTrackingStatusImage.e.getClass();
        List listR29 = CollectionsKt.R(compiledFieldC38, compiledFieldC39, compiledFieldC40, new CompiledField.Builder("image", CompiledGraphQL.b(LocationTrackingStatusImage.Companion.a())).c());
        D = listR29;
        List listR30 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        E = listR30;
        List listR31 = CollectionsKt.R(new CompiledField.Builder("leaveUnattended", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("leaveUnattendedTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("hideLeaveUnattended", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("leaveUnattendedMessage", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("driverInstructions", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("driverInstructionsTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("canToggleLeaveUnattended", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("canEditInstructions", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        F = listR31;
        CompiledField compiledFieldC41 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType11 = OrderDetailsItem.f11645a;
        CompiledField.Builder builder24 = new CompiledField.Builder("fulfilmentItems", a.f(objectType11));
        builder24.e(listR30);
        CompiledField compiledFieldC42 = builder24.c();
        ObjectType objectType12 = DeliveryInstructions.f11312a;
        CompiledField.Builder builder25 = new CompiledField.Builder("deliveryInstructions", objectType12);
        builder25.e(listR31);
        List listR32 = CollectionsKt.R(compiledFieldC41, compiledFieldC42, builder25.c());
        G = listR32;
        List listR33 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        H = listR33;
        CompiledField.Builder builder26 = new CompiledField.Builder("fulfilmentItems", a.f(objectType11));
        builder26.e(listR33);
        List listR34 = CollectionsKt.R(builder26.c(), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        I = listR34;
        List listR35 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        J = listR35;
        List listR36 = CollectionsKt.R(new CompiledField.Builder("leaveUnattended", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("leaveUnattendedTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("hideLeaveUnattended", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("leaveUnattendedMessage", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("driverInstructions", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("driverInstructionsTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("canToggleLeaveUnattended", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("canEditInstructions", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        K = listR36;
        CompiledField compiledFieldC43 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder27 = new CompiledField.Builder("fulfilmentItems", a.f(objectType11));
        builder27.e(listR35);
        CompiledField compiledFieldC44 = builder27.c();
        CompiledField.Builder builder28 = new CompiledField.Builder("deliveryInstructions", objectType12);
        builder28.e(listR36);
        List listR37 = CollectionsKt.R(compiledFieldC43, compiledFieldC44, builder28.c());
        L = listR37;
        CompiledField compiledFieldC45 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField compiledFieldC46 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder29 = new CompiledField.Builder("title", GraphQLString.Companion.a());
        builder29.a("bannerTitle");
        List listR38 = CollectionsKt.R(compiledFieldC45, compiledFieldC46, builder29.c());
        M = listR38;
        OrderStatusType.e.getClass();
        EnumType enumType3 = OrderStatusType.f;
        List listR39 = CollectionsKt.R(new CompiledField.Builder("status", CompiledGraphQL.b(enumType3)).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        N = listR39;
        List listR40 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("time", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        O = listR40;
        List listR41 = CollectionsKt.R(new CompiledField.Builder("orderNumber", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("orderedDate", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        P = listR41;
        CompiledField compiledFieldC47 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC48 = new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c();
        ButtonStyle.e.getClass();
        List listR42 = CollectionsKt.R(compiledFieldC47, compiledFieldC48, new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        Q = listR42;
        List listR43 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        R = listR43;
        List listR44 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        S = listR44;
        CompiledField.Builder builder30 = new CompiledField.Builder("insetBanner", InsetBanner.Companion.a());
        builder30.e(listR38);
        CompiledField compiledFieldC49 = builder30.c();
        ObjectType objectType13 = OrderDetailsStatus.f11647a;
        CompiledField.Builder builder31 = new CompiledField.Builder("orderDetailsStatus", CompiledGraphQL.b(OrderDetailsStatus.Companion.a()));
        builder31.e(listR39);
        CompiledField compiledFieldC50 = builder31.c();
        ObjectType objectType14 = OrderTime.f11675a;
        CompiledField.Builder builder32 = new CompiledField.Builder("orderTime", OrderTime.Companion.a());
        builder32.e(listR40);
        CompiledField compiledFieldC51 = builder32.c();
        ObjectType objectType15 = OrderDetailSummary.f11642a;
        CompiledField.Builder builder33 = new CompiledField.Builder("orderDetailSummary", OrderDetailSummary.Companion.a());
        builder33.e(listR41);
        CompiledField compiledFieldC52 = builder33.c();
        ObjectType objectType16 = Button.f11080a;
        CompiledField.Builder builder34 = new CompiledField.Builder("changeOrderButton", Button.Companion.a());
        builder34.e(listR42);
        CompiledField compiledFieldC53 = builder34.c();
        CompiledField.Builder builder35 = new CompiledField.Builder("cancelOrderButton", Button.Companion.a());
        builder35.e(listR43);
        CompiledField compiledFieldC54 = builder35.c();
        CompiledField.Builder builder36 = new CompiledField.Builder("viewInvoiceButton", Button.Companion.a());
        builder36.e(listR44);
        List listR45 = CollectionsKt.R(compiledFieldC49, compiledFieldC50, compiledFieldC51, compiledFieldC52, compiledFieldC53, compiledFieldC54, builder36.c(), new CompiledField.Builder("instructionsMd", GraphQLString.Companion.a()).c(), new CompiledField.Builder("helpMd", GraphQLString.Companion.a()).c());
        T = listR45;
        CompiledField compiledFieldC55 = new CompiledField.Builder("currentStep", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC56 = new CompiledField.Builder("totalSteps", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        ProgressStepType.e.getClass();
        EnumType enumType4 = ProgressStepType.f;
        CompiledField compiledFieldC57 = new CompiledField.Builder("currentStepType", CompiledGraphQL.b(enumType4)).c();
        CompiledField compiledFieldC58 = new CompiledField.Builder("currentStepPosition", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        TooltipType.e.getClass();
        EnumType enumType5 = TooltipType.f;
        List listR46 = CollectionsKt.R(compiledFieldC55, compiledFieldC56, compiledFieldC57, compiledFieldC58, new CompiledField.Builder("imageName", enumType5).c());
        U = listR46;
        List listR47 = CollectionsKt.R(new CompiledField.Builder("currentStep", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("totalSteps", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder("currentStepType", CompiledGraphQL.b(enumType4)).c(), new CompiledField.Builder("currentStepPosition", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), a.d("imageName", enumType5));
        V = listR47;
        CompiledField compiledFieldC59 = new CompiledField.Builder("number", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC60 = new CompiledField.Builder("isCompleted", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC61 = new CompiledField.Builder("isNextProgressed", GraphQLBoolean.Companion.a()).c();
        CompiledField compiledFieldC62 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC63 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, GraphQLString.Companion.a()).c();
        CompiledField.Builder builder37 = new CompiledField.Builder("stepIconUrl", GraphQLString.Companion.a());
        builder37.d(CollectionsKt.Q(new CompiledCondition("includeStatusTimelineRedesign", false)));
        List listR48 = CollectionsKt.R(compiledFieldC59, compiledFieldC60, compiledFieldC61, compiledFieldC62, compiledFieldC63, builder37.c());
        W = listR48;
        CompiledField compiledFieldC64 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType17 = TooltipStepInfo.f11974a;
        CompiledField.Builder builder38 = new CompiledField.Builder("stepInfoList", a.f(objectType17));
        builder38.e(listR48);
        List listR49 = CollectionsKt.R(compiledFieldC64, builder38.c());
        X = listR49;
        List listR50 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        Y = listR50;
        List listR51 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        Z = listR51;
        List listR52 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        a0 = listR52;
        CompiledField compiledFieldC65 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField compiledFieldC66 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder39 = new CompiledField.Builder("title", GraphQLString.Companion.a());
        builder39.a("bannerTitle");
        List listR53 = CollectionsKt.R(compiledFieldC65, compiledFieldC66, builder39.c());
        b0 = listR53;
        List listR54 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        c0 = listR54;
        List listR55 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        d0 = listR55;
        CompiledField compiledFieldC67 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC68 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC69 = new CompiledField.Builder("bayNumber", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        CompiledField.Builder builder40 = new CompiledField.Builder("confirmButton", CompiledGraphQL.b(Button.Companion.a()));
        builder40.e(listR54);
        CompiledField compiledFieldC70 = builder40.c();
        CompiledField.Builder builder41 = new CompiledField.Builder("bayNumberUnknownButton", CompiledGraphQL.b(Button.Companion.a()));
        builder41.e(listR55);
        List listR56 = CollectionsKt.R(compiledFieldC67, compiledFieldC68, compiledFieldC69, compiledFieldC70, builder41.c());
        e0 = listR56;
        List listR57 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        f0 = listR57;
        List listR58 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        g0 = listR58;
        CompiledField compiledFieldC71 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC72 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC73 = new CompiledField.Builder("eta", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        CompiledField compiledFieldC74 = new CompiledField.Builder("etaType", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC75 = new CompiledField.Builder("etaDefaultIndex", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField.Builder builder42 = new CompiledField.Builder("confirmButton", CompiledGraphQL.b(Button.Companion.a()));
        builder42.e(listR58);
        List listR59 = CollectionsKt.R(compiledFieldC71, compiledFieldC72, compiledFieldC73, compiledFieldC74, compiledFieldC75, builder42.c());
        h0 = listR59;
        CompiledField compiledFieldC76 = new CompiledField.Builder("applyBackground", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        LocationImage.e.getClass();
        EnumType enumType6 = LocationImage.f;
        List listR60 = CollectionsKt.R(compiledFieldC76, new CompiledField.Builder("image", CompiledGraphQL.b(enumType6)).c(), new CompiledField.Builder("textMd", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        i0 = listR60;
        List listR61 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        j0 = listR61;
        CompiledField compiledFieldC77 = new CompiledField.Builder("header", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType18 = LocationTrackingPrimingPageRationale.f11543a;
        CompiledField.Builder builder43 = new CompiledField.Builder("rationales", a.f(objectType18));
        builder43.e(listR60);
        CompiledField compiledFieldC78 = builder43.c();
        CompiledField.Builder builder44 = new CompiledField.Builder("locationPermissionButtons", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(Button.Companion.a()))));
        builder44.e(listR61);
        List listR62 = CollectionsKt.R(compiledFieldC77, compiledFieldC78, builder44.c(), new CompiledField.Builder("footer", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        k0 = listR62;
        List listR63 = CollectionsKt.R(new CompiledField.Builder("applyBackground", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("image", CompiledGraphQL.b(enumType6)).c(), new CompiledField.Builder("textMd", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        l0 = listR63;
        List listR64 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        m0 = listR64;
        CompiledField compiledFieldC79 = new CompiledField.Builder("header", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder45 = new CompiledField.Builder("rationales", a.f(objectType18));
        builder45.e(listR63);
        CompiledField compiledFieldC80 = builder45.c();
        CompiledField.Builder builder46 = new CompiledField.Builder("locationPermissionButtons", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(Button.Companion.a()))));
        builder46.e(listR64);
        List listR65 = CollectionsKt.R(compiledFieldC79, compiledFieldC80, builder46.c(), new CompiledField.Builder("footer", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        n0 = listR65;
        ObjectType objectType19 = LocationTrackingPrimingPageContent.f11542a;
        CompiledField.Builder builder47 = new CompiledField.Builder("locationPermissionsWereNotSet", CompiledGraphQL.b(objectType19));
        builder47.e(listR62);
        CompiledField compiledFieldC81 = builder47.c();
        CompiledField.Builder builder48 = new CompiledField.Builder("doNotAllowWasSetEarlier", CompiledGraphQL.b(objectType19));
        builder48.e(listR65);
        List listR66 = CollectionsKt.R(compiledFieldC81, builder48.c());
        o0 = listR66;
        CompiledField compiledFieldC82 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC83 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        BroadcastBannerType.e.getClass();
        List listR67 = CollectionsKt.R(compiledFieldC82, compiledFieldC83, new CompiledField.Builder("type", CompiledGraphQL.b(BroadcastBannerType.Companion.a())).c(), new CompiledField.Builder("dismissible", GraphQLBoolean.Companion.a()).c(), new CompiledField.Builder("bannerId", GraphQLString.Companion.a()).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        p0 = listR67;
        List listR68 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c(), new CompiledField.Builder("type", CompiledGraphQL.b(BroadcastBannerType.Companion.a())).c(), new CompiledField.Builder("dismissible", GraphQLBoolean.Companion.a()).c(), new CompiledField.Builder("bannerId", GraphQLString.Companion.a()).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        q0 = listR68;
        ObjectType objectType20 = ProgressStepper.f11795a;
        CompiledField.Builder builder49 = new CompiledField.Builder("progressStepper", objectType20);
        builder49.e(listR46);
        CompiledField compiledFieldC84 = builder49.c();
        CompiledField compiledFieldE2 = com.google.android.gms.common.api.internal.a.e("includeProgressStepperCollectedState", false, new CompiledField.Builder("progressStepperForCollectedState", objectType20), listR47);
        ObjectType objectType21 = StepsTooltip.f11932a;
        CompiledField.Builder builder50 = new CompiledField.Builder("tooltip", objectType21);
        builder50.e(listR49);
        CompiledField compiledFieldC85 = builder50.c();
        CompiledField compiledFieldC86 = new CompiledField.Builder("orderTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC87 = new CompiledField.Builder("orderSubtitle", GraphQLString.Companion.a()).c();
        OrderSubtitleIcon.e.getClass();
        EnumType enumType7 = OrderSubtitleIcon.f;
        CompiledField compiledFieldC88 = new CompiledField.Builder("orderSubtitleIcon", enumType7).c();
        CompiledField compiledFieldC89 = new CompiledField.Builder("instructionsMd", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC90 = new CompiledField.Builder("helpMd", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder51 = new CompiledField.Builder("changeOrderButton", Button.Companion.a());
        builder51.e(listR50);
        CompiledField compiledFieldC91 = builder51.c();
        CompiledField.Builder builder52 = new CompiledField.Builder("cancelOrderButton", Button.Companion.a());
        builder52.e(listR51);
        CompiledField compiledFieldC92 = builder52.c();
        CompiledField.Builder builder53 = new CompiledField.Builder("checkInNowButton", Button.Companion.a());
        builder53.e(listR52);
        CompiledField compiledFieldC93 = builder53.c();
        CompiledField.Builder builder54 = new CompiledField.Builder("collectionBanner", InsetBanner.Companion.a());
        builder54.e(listR53);
        CompiledField compiledFieldC94 = builder54.c();
        ObjectType objectType22 = BayNumberPreferences.f11048a;
        CompiledField.Builder builder55 = new CompiledField.Builder("bayNumberPreferences", BayNumberPreferences.Companion.a());
        builder55.e(listR56);
        CompiledField compiledFieldC95 = builder55.c();
        CompiledField.Builder builder56 = new CompiledField.Builder("checkInOnMyWayButton", Button.Companion.a());
        builder56.e(listR57);
        CompiledField compiledFieldC96 = builder56.c();
        ObjectType objectType23 = OnMyWayPreferences.f11623a;
        CompiledField.Builder builder57 = new CompiledField.Builder("onMyWayPreferences", OnMyWayPreferences.Companion.a());
        builder57.e(listR59);
        CompiledField compiledFieldC97 = builder57.c();
        CompiledField compiledFieldC98 = new CompiledField.Builder("locationTrackingEnabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        ObjectType objectType24 = LocationTrackingPrimingPage.f11541a;
        CompiledField.Builder builder58 = new CompiledField.Builder("locationTrackingPrimingPage", LocationTrackingPrimingPage.Companion.a());
        builder58.e(listR66);
        CompiledField compiledFieldC99 = builder58.c();
        ObjectType objectType25 = BroadcastBanner.f11060a;
        CompiledField.Builder builder59 = new CompiledField.Builder("banner", objectType25);
        builder59.e(listR67);
        List listR69 = CollectionsKt.R(compiledFieldC84, compiledFieldE2, compiledFieldC85, compiledFieldC86, compiledFieldC87, compiledFieldC88, compiledFieldC89, compiledFieldC90, compiledFieldC91, compiledFieldC92, compiledFieldC93, compiledFieldC94, compiledFieldC95, compiledFieldC96, compiledFieldC97, compiledFieldC98, compiledFieldC99, builder59.c(), com.google.android.gms.common.api.internal.a.e("includeHandoverBanner", false, new CompiledField.Builder("handoverBanner", objectType25), listR68));
        r0 = listR69;
        List listR70 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("orderNumber", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        s0 = listR70;
        List listR71 = CollectionsKt.R(new CompiledField.Builder("key", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("value", GraphQLString.Companion.a()).c());
        t0 = listR71;
        CompiledField compiledFieldC100 = new CompiledField.Builder("eventLabel", GraphQLString.Companion.a()).c();
        ObjectType objectType26 = AnalyticsExtraContent.f11029a;
        CompiledField.Builder builder60 = new CompiledField.Builder("extraContent", CompiledGraphQL.a(CompiledGraphQL.b(objectType26)));
        builder60.e(listR71);
        List listR72 = CollectionsKt.R(compiledFieldC100, builder60.c());
        u0 = listR72;
        CompiledField compiledFieldC101 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC102 = new CompiledField.Builder("iconUrl", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC103 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField.Builder builder61 = new CompiledField.Builder("title", GraphQLString.Companion.a());
        builder61.a("bannerTitle");
        CompiledField compiledFieldC104 = builder61.c();
        CompiledField.Builder builder62 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder62.e(listR72);
        List listR73 = CollectionsKt.R(compiledFieldC101, compiledFieldC102, compiledFieldC103, compiledFieldC104, builder62.c());
        v0 = listR73;
        List listR74 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        w0 = listR74;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        x0 = listQ2;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        y0 = listQ3;
        CompiledField compiledFieldC105 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder63 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder63.b(listQ3);
        List listR75 = CollectionsKt.R(compiledFieldC105, builder63.a());
        z0 = listR75;
        CompiledField compiledFieldC106 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC107 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CoreBroadcastBannerStyle.e.getClass();
        CompiledField compiledFieldC108 = new CompiledField.Builder("style", CompiledGraphQL.b(CoreBroadcastBannerStyle.Companion.a())).c();
        UnionType unionType3 = IconAsset.f11477a;
        CompiledField.Builder builder64 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(IconAsset.Companion.a()));
        builder64.e(listR75);
        List listR76 = CollectionsKt.R(compiledFieldC106, compiledFieldC107, compiledFieldC108, builder64.c());
        A0 = listR76;
        ObjectType objectType27 = CoreBroadcastBannerUI.f11286a;
        CompiledField.Builder builder65 = new CompiledField.Builder("broadcastBannerUI", CompiledGraphQL.b(CoreBroadcastBannerUI.Companion.a()));
        builder65.e(listR76);
        List listR77 = CollectionsKt.R(builder65.c(), new CompiledField.Builder("broadcastBannerDismissible", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        B0 = listR77;
        CompiledField compiledFieldC109 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC110 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC111 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType28 = DeliveryMethodBulletInfo.f11313a;
        CompiledField.Builder builder66 = new CompiledField.Builder("bulletInfoList", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(DeliveryMethodBulletInfo.Companion.a()))));
        builder66.e(listQ2);
        List listR78 = CollectionsKt.R(compiledFieldC109, compiledFieldC110, compiledFieldC111, builder66.c(), com.google.android.gms.common.api.internal.a.e("includeDriverRating", false, new CompiledField.Builder("driverRatingBanner", BasicCoreBroadcastBanner.f11044a), listR77));
        C0 = listR78;
        CompiledField compiledFieldC112 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC113 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType29 = TooltipDeliveryMethodInfo.f11973a;
        CompiledField.Builder builder67 = new CompiledField.Builder("deliveryMethodsTabs", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(TooltipDeliveryMethodInfo.Companion.a()))));
        builder67.e(listR78);
        List listR79 = CollectionsKt.R(compiledFieldC112, compiledFieldC113, builder67.c());
        D0 = listR79;
        CompiledField compiledFieldC114 = new CompiledField.Builder("driverName", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC115 = new CompiledField.Builder("deliveryPartner", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC116 = new CompiledField.Builder("iconUrl", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder68 = new CompiledField.Builder("insetBanner", InsetBanner.Companion.a());
        builder68.e(listR73);
        CompiledField compiledFieldC117 = builder68.c();
        CompiledField compiledFieldE3 = com.google.android.gms.common.api.internal.a.e("includeFleetLiveTracking", false, new CompiledField.Builder("liveTrackingButton", Button.Companion.a()), listR74);
        ObjectType objectType30 = DeliveryMethodsTooltip.f11314a;
        List listR80 = CollectionsKt.R(compiledFieldC114, compiledFieldC115, compiledFieldC116, compiledFieldC117, compiledFieldE3, com.google.android.gms.common.api.internal.a.e("includeDeliveryMethods", false, new CompiledField.Builder("deliveryTooltip", DeliveryMethodsTooltip.Companion.a()), listR79));
        E0 = listR80;
        List listR81 = CollectionsKt.R(new CompiledField.Builder("key", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("value", GraphQLString.Companion.a()).c());
        F0 = listR81;
        CompiledField compiledFieldC118 = new CompiledField.Builder("eventLabel", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder69 = new CompiledField.Builder("extraContent", CompiledGraphQL.a(CompiledGraphQL.b(objectType26)));
        builder69.e(listR81);
        List listR82 = CollectionsKt.R(compiledFieldC118, builder69.c());
        G0 = listR82;
        CompiledField compiledFieldC119 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField compiledFieldC120 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder70 = new CompiledField.Builder("title", GraphQLString.Companion.a());
        builder70.a("bannerTitle");
        CompiledField compiledFieldC121 = builder70.c();
        CompiledField.Builder builder71 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder71.e(listR82);
        List listR83 = CollectionsKt.R(compiledFieldC119, compiledFieldC120, compiledFieldC121, builder71.c());
        H0 = listR83;
        List listR84 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        I0 = listR84;
        List listR85 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, GraphQLString.Companion.a()).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        J0 = listR85;
        List listR86 = CollectionsKt.R(new CompiledField.Builder("currentStep", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("totalSteps", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder("currentStepType", CompiledGraphQL.b(enumType4)).c(), new CompiledField.Builder("currentStepPosition", CompiledGraphQL.b(GraphQLInt.Companion.a())).c());
        K0 = listR86;
        CompiledField compiledFieldC122 = new CompiledField.Builder("number", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC123 = new CompiledField.Builder("isCompleted", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC124 = new CompiledField.Builder("isNextProgressed", GraphQLBoolean.Companion.a()).c();
        CompiledField compiledFieldC125 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC126 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, GraphQLString.Companion.a()).c();
        CompiledField.Builder builder72 = new CompiledField.Builder("stepIconUrl", GraphQLString.Companion.a());
        builder72.d(CollectionsKt.Q(new CompiledCondition("includeStatusTimelineRedesign", false)));
        List listR87 = CollectionsKt.R(compiledFieldC122, compiledFieldC123, compiledFieldC124, compiledFieldC125, compiledFieldC126, builder72.c());
        L0 = listR87;
        CompiledField compiledFieldC127 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder73 = new CompiledField.Builder("stepInfoList", a.f(objectType17));
        builder73.e(listR87);
        List listR88 = CollectionsKt.R(compiledFieldC127, builder73.c());
        M0 = listR88;
        CompiledField.Builder builder74 = new CompiledField.Builder("insetBanners", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(InsetBanner.Companion.a()))));
        builder74.e(listR83);
        CompiledField compiledFieldC128 = builder74.c();
        CompiledField compiledFieldC129 = new CompiledField.Builder("bannerAnalyticLabels", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        CompiledField.Builder builder75 = new CompiledField.Builder("changeOrderButton", Button.Companion.a());
        builder75.e(listR84);
        CompiledField compiledFieldC130 = builder75.c();
        CompiledField.Builder builder76 = new CompiledField.Builder("cancelOrderButton", Button.Companion.a());
        builder76.e(listR85);
        CompiledField compiledFieldC131 = builder76.c();
        CompiledField.Builder builder77 = new CompiledField.Builder("progressStepper", objectType20);
        builder77.e(listR86);
        CompiledField compiledFieldC132 = builder77.c();
        CompiledField.Builder builder78 = new CompiledField.Builder("tooltip", objectType21);
        builder78.e(listR88);
        CompiledField compiledFieldC133 = builder78.c();
        CompiledField compiledFieldC134 = new CompiledField.Builder("instructionsMd", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC135 = new CompiledField.Builder("helpMd", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC136 = new CompiledField.Builder("orderSubtitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC137 = new CompiledField.Builder("orderTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldD = a.d("orderSubtitleIcon", enumType7);
        CompiledField.Builder builder79 = new CompiledField.Builder("liveTrackingMapUrl", GraphQLString.Companion.a());
        builder79.d(CollectionsKt.Q(new CompiledCondition("includeP2PLiveTracking", false)));
        List listR89 = CollectionsKt.R(compiledFieldC128, compiledFieldC129, compiledFieldC130, compiledFieldC131, compiledFieldC132, compiledFieldC133, compiledFieldC134, compiledFieldC135, compiledFieldC136, compiledFieldC137, compiledFieldD, builder79.c());
        N0 = listR89;
        CoreAlertStyle.e.getClass();
        List listR90 = CollectionsKt.R(new CompiledField.Builder("style", CompiledGraphQL.b(CoreAlertStyle.f)).c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, GraphQLString.Companion.a()).c(), new CompiledField.Builder("title", GraphQLString.Companion.a()).c());
        O0 = listR90;
        ActionType.e.getClass();
        List listR91 = CollectionsKt.R(new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        P0 = listR91;
        CoreButtonStyle.e.getClass();
        EnumType enumType8 = CoreButtonStyle.f;
        CompiledField compiledFieldC138 = new CompiledField.Builder("coreButtonStyle", CompiledGraphQL.b(enumType8)).c();
        CompiledField compiledFieldC139 = new CompiledField.Builder("coreButtonLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType31 = Action.f10997a;
        CompiledField.Builder builder80 = new CompiledField.Builder("coreButtonAction", CompiledGraphQL.b(Action.Companion.a()));
        builder80.e(listR91);
        List listR92 = CollectionsKt.R(compiledFieldC138, compiledFieldC139, builder80.c(), new CompiledField.Builder("coreButtonEnabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        Q0 = listR92;
        CompiledField compiledFieldC140 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC141 = new CompiledField.Builder("subTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC142 = new CompiledField.Builder("starsRatingQuestion", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder81 = new CompiledField.Builder("insetAlert", CompiledGraphQL.b(CoreInsetAlertUI.f11291a));
        builder81.e(listR90);
        CompiledField compiledFieldC143 = builder81.c();
        ObjectType objectType32 = CoreButton.f11287a;
        CompiledField.Builder builder82 = new CompiledField.Builder("submitButton", CompiledGraphQL.b(objectType32));
        builder82.e(listR92);
        List listR93 = CollectionsKt.R(compiledFieldC140, compiledFieldC141, compiledFieldC142, compiledFieldC143, builder82.c());
        R0 = listR93;
        List listR94 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        S0 = listR94;
        CompiledField compiledFieldC144 = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLID.Companion.a())).c();
        CompiledField compiledFieldC145 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        ObjectType objectType33 = TextWithAlt.f11967a;
        CompiledField.Builder builder83 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(TextWithAlt.Companion.a()));
        builder83.e(listR94);
        List listR95 = CollectionsKt.R(compiledFieldC144, compiledFieldC145, builder83.c());
        T0 = listR95;
        List listR96 = CollectionsKt.R(new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        U0 = listR96;
        CompiledField compiledFieldC146 = new CompiledField.Builder("coreButtonStyle", CompiledGraphQL.b(enumType8)).c();
        CompiledField compiledFieldC147 = new CompiledField.Builder("coreButtonLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder84 = new CompiledField.Builder("coreButtonAction", CompiledGraphQL.b(Action.Companion.a()));
        builder84.e(listR96);
        List listR97 = CollectionsKt.R(compiledFieldC146, compiledFieldC147, builder84.c(), new CompiledField.Builder("coreButtonEnabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        V0 = listR97;
        CompiledField compiledFieldC148 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC149 = new CompiledField.Builder("subTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC150 = new CompiledField.Builder("feedbackChipsQuestion", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType34 = Chip.f11271a;
        CompiledField.Builder builder85 = new CompiledField.Builder("feedbackChips", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(Chip.Companion.a()))));
        builder85.e(listR95);
        CompiledField compiledFieldC151 = builder85.c();
        CompiledField compiledFieldC152 = new CompiledField.Builder("additionalCommentText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder86 = new CompiledField.Builder("doneButton", CompiledGraphQL.b(objectType32));
        builder86.e(listR97);
        List listR98 = CollectionsKt.R(compiledFieldC148, compiledFieldC149, compiledFieldC150, compiledFieldC151, compiledFieldC152, builder86.c());
        W0 = listR98;
        List listR99 = CollectionsKt.R(new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        X0 = listR99;
        CompiledField compiledFieldC153 = new CompiledField.Builder("coreButtonStyle", CompiledGraphQL.b(enumType8)).c();
        CompiledField compiledFieldC154 = new CompiledField.Builder("coreButtonLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder87 = new CompiledField.Builder("coreButtonAction", CompiledGraphQL.b(Action.Companion.a()));
        builder87.e(listR99);
        List listR100 = CollectionsKt.R(compiledFieldC153, compiledFieldC154, builder87.c(), new CompiledField.Builder("coreButtonEnabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        Y0 = listR100;
        CompiledField compiledFieldC155 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC156 = new CompiledField.Builder("subTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC157 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC158 = new CompiledField.Builder("badFeedbackMessage", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC159 = new CompiledField.Builder("badFeedbackQuestion", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder88 = new CompiledField.Builder("badFeedbackButton", CompiledGraphQL.b(objectType32));
        builder88.e(listR100);
        List listR101 = CollectionsKt.R(compiledFieldC155, compiledFieldC156, compiledFieldC157, compiledFieldC158, compiledFieldC159, builder88.c(), new CompiledField.Builder("neutralFeedbackMessage", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("goodFeedbackMessage", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        Z0 = listR101;
        CompiledField compiledFieldC160 = new CompiledField.Builder("surveyId", CompiledGraphQL.b(GraphQLID.Companion.a())).c();
        ObjectType objectType35 = DriverRatingStarsSurvey.f11352a;
        CompiledField.Builder builder89 = new CompiledField.Builder("starsRatingStep", DriverRatingStarsSurvey.Companion.a());
        builder89.e(listR93);
        CompiledField compiledFieldC161 = builder89.c();
        ObjectType objectType36 = DriverRatingFeedbackAndComments.f11351a;
        CompiledField.Builder builder90 = new CompiledField.Builder("feedbackAndCommentsStep", DriverRatingFeedbackAndComments.Companion.a());
        builder90.e(listR98);
        CompiledField compiledFieldC162 = builder90.c();
        ObjectType objectType37 = DriverRatingThankYou.f11353a;
        CompiledField.Builder builder91 = new CompiledField.Builder("thankYouStep", DriverRatingThankYou.Companion.a());
        builder91.e(listR101);
        List listR102 = CollectionsKt.R(compiledFieldC160, compiledFieldC161, compiledFieldC162, builder91.c(), new CompiledField.Builder("orderNumber", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        a1 = listR102;
        CompiledField compiledFieldC163 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder92 = new CompiledFragment.Builder("OrderDetailsDivider", CollectionsKt.Q("OrderDetailsDivider"));
        builder92.b(listR6);
        CompiledFragment compiledFragmentA = builder92.a();
        CompiledFragment.Builder builder93 = new CompiledFragment.Builder("OrderPaymentDetails", CollectionsKt.Q("OrderPaymentDetails"));
        builder93.b(listR15);
        CompiledFragment compiledFragmentA2 = builder93.a();
        CompiledFragment.Builder builder94 = new CompiledFragment.Builder("HorizontalList", CollectionsKt.Q("HorizontalList"));
        builder94.b(listR22);
        CompiledFragment compiledFragmentA3 = builder94.a();
        CompiledFragment.Builder builder95 = new CompiledFragment.Builder("OrderProofOfDeliveryDetails", CollectionsKt.Q("OrderProofOfDeliveryDetails"));
        builder95.b(listR24);
        CompiledFragment compiledFragmentA4 = builder95.a();
        CompiledFragment.Builder builder96 = new CompiledFragment.Builder("CurrentPickupOrderFulfilmentDetails", CollectionsKt.Q("CurrentPickupOrderFulfilmentDetails"));
        builder96.b(listR28);
        CompiledFragment compiledFragmentA5 = builder96.a();
        CompiledFragment.Builder builder97 = new CompiledFragment.Builder("CurrentPickupLocationTrackingStatus", CollectionsKt.Q("CurrentPickupLocationTrackingStatus"));
        builder97.b(listR29);
        CompiledFragment compiledFragmentA6 = builder97.a();
        CompiledFragment compiledFragmentI = d.i("includeSpiltOrderFulfilmentDetails", true, new CompiledFragment.Builder("OrderFulfilmentDetails", CollectionsKt.Q("OrderFulfilmentDetails")), listR32);
        CompiledFragment compiledFragmentI2 = d.i("includeSpiltOrderFulfilmentDetails", false, new CompiledFragment.Builder("PastPickupOrderFulfilmentDetails", CollectionsKt.Q("PastPickupOrderFulfilmentDetails")), listR34);
        CompiledFragment compiledFragmentI3 = d.i("includeSpiltOrderFulfilmentDetails", false, new CompiledFragment.Builder("DeliveryOrderFulfilmentDetails", CollectionsKt.Q("DeliveryOrderFulfilmentDetails")), listR37);
        CompiledFragment.Builder builder98 = new CompiledFragment.Builder("PastOrderOverview", CollectionsKt.Q("PastOrderOverview"));
        builder98.b(listR45);
        CompiledFragment compiledFragmentA7 = builder98.a();
        CompiledFragment.Builder builder99 = new CompiledFragment.Builder("CurrentPickupOrderOverview", CollectionsKt.Q("CurrentPickupOrderOverview"));
        builder99.b(listR69);
        CompiledFragment compiledFragmentA8 = builder99.a();
        CompiledFragment.Builder builder100 = new CompiledFragment.Builder("OrderNumberDetails", CollectionsKt.Q("OrderNumberDetails"));
        builder100.b(listR70);
        CompiledFragment compiledFragmentA9 = builder100.a();
        CompiledFragment.Builder builder101 = new CompiledFragment.Builder("DeliveryDriverDetails", CollectionsKt.Q("DeliveryDriverDetails"));
        builder101.b(listR80);
        CompiledFragment compiledFragmentA10 = builder101.a();
        CompiledFragment.Builder builder102 = new CompiledFragment.Builder("CurrentDeliveryOrderOverview", CollectionsKt.Q("CurrentDeliveryOrderOverview"));
        builder102.b(listR89);
        List listR103 = CollectionsKt.R(compiledFieldC163, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentI, compiledFragmentI2, compiledFragmentI3, compiledFragmentA7, compiledFragmentA8, compiledFragmentA9, compiledFragmentA10, builder102.a(), d.i("includeDriverRating", false, new CompiledFragment.Builder("DriverRating", CollectionsKt.Q("DriverRating")), listR102));
        b1 = listR103;
        CompiledField compiledFieldC164 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        UnionType unionType4 = FeedItem.f11385a;
        CompiledField.Builder builder103 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(FeedItem.Companion.a()))));
        builder103.e(listR103);
        List listR104 = CollectionsKt.R(compiledFieldC164, builder103.c());
        c1 = listR104;
        List listR105 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        d1 = listR105;
        List listQ4 = CollectionsKt.Q(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        e1 = listQ4;
        CompiledField compiledFieldC165 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC166 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType38 = EditOrderWarningItem.f11373a;
        CompiledField.Builder builder104 = new CompiledField.Builder("warningItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(EditOrderWarningItem.Companion.a()))));
        builder104.e(listQ4);
        CompiledField compiledFieldC167 = builder104.c();
        CompiledField compiledFieldC168 = new CompiledField.Builder("acceptLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC169 = new CompiledField.Builder("acceptButtonLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC170 = new CompiledField.Builder("cancelButtonLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder105 = new CompiledField.Builder("disclaimer", CompiledGraphQL.b(GraphQLString.Companion.a()));
        builder105.d(CollectionsKt.Q(new CompiledCondition("includeOrderDetailsChangeMyOrderUplift", false)));
        List listR106 = CollectionsKt.R(compiledFieldC165, compiledFieldC166, compiledFieldC167, compiledFieldC168, compiledFieldC169, compiledFieldC170, builder105.c());
        f1 = listR106;
        CompiledField compiledFieldC171 = new CompiledField.Builder("orderId", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        ObjectType objectType39 = OrderHelp.f11650a;
        CompiledField.Builder builder106 = new CompiledField.Builder("help", OrderHelp.Companion.a());
        builder106.a("helpList");
        builder106.e(listR5);
        CompiledField compiledFieldC172 = builder106.c();
        ObjectType objectType40 = Feed.f11384a;
        CompiledField.Builder builder107 = new CompiledField.Builder("feed", CompiledGraphQL.b(Feed.Companion.a()));
        builder107.e(listR104);
        CompiledField compiledFieldC173 = builder107.c();
        ObjectType objectType41 = CancelWarning.f11096a;
        CompiledField.Builder builder108 = new CompiledField.Builder("cancelWarning", CompiledGraphQL.b(CancelWarning.Companion.a()));
        builder108.e(listR105);
        CompiledField compiledFieldC174 = builder108.c();
        ObjectType objectType42 = EditOrderWarning.f11372a;
        CompiledField.Builder builder109 = new CompiledField.Builder("editOrderWarning", CompiledGraphQL.b(EditOrderWarning.Companion.a()));
        builder109.e(listR106);
        CompiledField compiledFieldC175 = builder109.c();
        OrderFulfilmentType.e.getClass();
        List listR107 = CollectionsKt.R(compiledFieldC171, compiledFieldC172, compiledFieldC173, compiledFieldC174, compiledFieldC175, new CompiledField.Builder("fulfilmentMethod", CompiledGraphQL.b(OrderFulfilmentType.Companion.a())).c(), new CompiledField.Builder("progress", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("progressDetail", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("showDelightAnimation", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("status", CompiledGraphQL.b(enumType3)).c());
        g1 = listR107;
        ObjectType objectType43 = OrderSummary.f11674a;
        CompiledField.Builder builder110 = new CompiledField.Builder("orderSummary", CompiledGraphQL.b(OrderSummary.Companion.a()));
        CompiledArgumentDefinition compiledArgumentDefinition = Query.f11808a;
        new CompiledArgument.Builder(Query.Companion.d());
        CompiledArgument compiledArgumentA = CompiledArgument.Builder.a();
        new CompiledArgument.Builder(Query.Companion.e());
        builder110.b(CollectionsKt.R(compiledArgumentA, CompiledArgument.Builder.a()));
        builder110.e(listR107);
        h1 = CollectionsKt.Q(builder110.c());
    }
}
