package com.woolworths.feature.shop.myorders.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.shop.graphql.type.BroadcastBannerType;
import au.com.woolworths.shop.graphql.type.ContactItem;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.OrderHelp;
import au.com.woolworths.shop.graphql.type.OrderHelpContactTimes;
import au.com.woolworths.shop.graphql.type.OrderHelpItem;
import au.com.woolworths.shop.graphql.type.OrderHelpItemType;
import au.com.woolworths.shop.graphql.type.OrderPaymentDetails;
import au.com.woolworths.shop.graphql.type.OrderPaymentDetailsItem;
import au.com.woolworths.shop.graphql.type.OrderPaymentDetailsItemAmountStyle;
import au.com.woolworths.shop.graphql.type.OrderProductList;
import au.com.woolworths.shop.graphql.type.OrderProductListFeedItem;
import au.com.woolworths.shop.graphql.type.OrderProductListFulfilmentFilter;
import au.com.woolworths.shop.graphql.type.OrderProductListFulfilmentFilterItem;
import au.com.woolworths.shop.graphql.type.OrderProductListProductPriceStyle;
import au.com.woolworths.shop.graphql.type.OrderProductListSubstitutedProduct;
import au.com.woolworths.shop.graphql.type.Query;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.google.android.gms.measurement.api.AppMeasurementSdk;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/feature/shop/myorders/selections/GetYourGroceriesQuerySelections;", "", "my-orders_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class GetYourGroceriesQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f20197a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        CompiledField compiledFieldC = new CompiledField.Builder("key", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC2 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLBoolean.f11439a;
        List listR = CollectionsKt.R(compiledFieldC, compiledFieldC2, new CompiledField.Builder("isApplied", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("count", CompiledGraphQL.b(GraphQLInt.f11442a)).c());
        f20197a = listR;
        CompiledField.Builder builder = new CompiledField.Builder("items", a.f(OrderProductListFulfilmentFilterItem.f11666a));
        builder.e = listR;
        List listQ = CollectionsKt.Q(builder.c());
        b = listQ;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c());
        c = listQ2;
        List listR2 = CollectionsKt.R(new CompiledField.Builder("productId", CompiledGraphQL.b(customScalarType)).c(), d.g("productImage", customScalarType), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("priceLabel", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("priceMatched", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("productName", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("productLabel", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("priceMatchedLabel", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("quantityTitle", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("quantityValue", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("showRating", CompiledGraphQL.b(customScalarType2)).c());
        d = listR2;
        CompiledField compiledFieldC3 = new CompiledField.Builder("productId", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g("productImage", customScalarType);
        CompiledField compiledFieldC5 = new CompiledField.Builder("quantityTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC6 = new CompiledField.Builder("quantityValue", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("priceLabel", CompiledGraphQL.b(customScalarType)).c();
        OrderProductListProductPriceStyle.e.getClass();
        CompiledField compiledFieldC8 = new CompiledField.Builder("priceStyle", CompiledGraphQL.b(OrderProductListProductPriceStyle.f)).c();
        CompiledField.Builder builder2 = new CompiledField.Builder("substitutions", a.f(OrderProductListSubstitutedProduct.f11670a));
        builder2.e = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC3, compiledFieldC4, compiledFieldG, compiledFieldC5, compiledFieldC6, compiledFieldC7, compiledFieldC8, builder2.c());
        e = listR3;
        List listR4 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g("message", customScalarType));
        f = listR4;
        CompiledField compiledFieldC9 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG2 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField compiledFieldG3 = d.g("deeplink", customScalarType);
        BroadcastBannerType.e.getClass();
        List listR5 = CollectionsKt.R(compiledFieldC9, compiledFieldG2, compiledFieldG3, new CompiledField.Builder("type", CompiledGraphQL.b(BroadcastBannerType.f)).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c(), d.g("actionLabel", customScalarType), d.g("analyticsLabel", customScalarType), d.g("dismissible", customScalarType2), d.g("bannerId", customScalarType));
        g = listR5;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("OrderProductListProductCategory", CollectionsKt.Q("OrderProductListProductCategory"));
        builder3.d = listQ2;
        CompiledFragment compiledFragmentA = builder3.a();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("OrderProductListProduct", CollectionsKt.Q("OrderProductListProduct"));
        builder4.d = listR3;
        CompiledFragment compiledFragmentA2 = builder4.a();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("OrderProductListFulfilmentStatus", CollectionsKt.Q("OrderProductListFulfilmentStatus"));
        builder5.d = listR4;
        CompiledFragment compiledFragmentA3 = builder5.a();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("BroadcastBanner", CollectionsKt.Q("BroadcastBanner"));
        builder6.d = listR5;
        List listR6 = CollectionsKt.R(compiledFieldC10, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, builder6.a());
        h = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amount", CompiledGraphQL.b(customScalarType)).c());
        i = listR7;
        List listR8 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amount", CompiledGraphQL.b(customScalarType)).c());
        j = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amount", CompiledGraphQL.b(customScalarType)).c());
        k = listR9;
        CompiledField compiledFieldC11 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC12 = new CompiledField.Builder("amount", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG4 = d.g("amountIcon", customScalarType);
        OrderPaymentDetailsItemAmountStyle.e.getClass();
        EnumType enumType = OrderPaymentDetailsItemAmountStyle.f;
        List listR10 = CollectionsKt.R(compiledFieldC11, compiledFieldC12, compiledFieldG4, new CompiledField.Builder("amountStyle", enumType).c());
        l = listR10;
        List listR11 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g(BarcodePickDeserializer.FIELD_ICON, customScalarType), new CompiledField.Builder("amount", CompiledGraphQL.b(customScalarType)).c());
        m = listR11;
        List listR12 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("amount", CompiledGraphQL.b(customScalarType)).c());
        n = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("amount", CompiledGraphQL.b(customScalarType)).c(), a.d("amountStyle", enumType), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c());
        o = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder("amount", CompiledGraphQL.b(customScalarType)).c(), a.d("amountStyle", enumType), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c());
        p = listR14;
        ObjectType objectType = OrderPaymentDetailsItem.f11662a;
        CompiledField.Builder builder7 = new CompiledField.Builder("total", a.f(objectType));
        builder7.e = listR7;
        CompiledField compiledFieldC13 = builder7.c();
        CompiledField.Builder builder8 = new CompiledField.Builder("subTotal", CompiledGraphQL.b(CompiledGraphQL.a(objectType)));
        builder8.e = listR8;
        CompiledField compiledFieldC14 = builder8.c();
        CompiledField.Builder builder9 = new CompiledField.Builder("marketSubtotal", CompiledGraphQL.b(CompiledGraphQL.a(objectType)));
        builder9.e = listR9;
        CompiledField compiledFieldC15 = builder9.c();
        CompiledField.Builder builder10 = new CompiledField.Builder("savingsAndRewards", CompiledGraphQL.b(CompiledGraphQL.a(objectType)));
        builder10.e = listR10;
        CompiledField compiledFieldC16 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("paymentMethods", a.f(objectType));
        builder11.e = listR11;
        CompiledField compiledFieldC17 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("discounts", CompiledGraphQL.b(CompiledGraphQL.a(objectType)));
        builder12.e = listR12;
        CompiledField compiledFieldC18 = builder12.c();
        CompiledField.Builder builder13 = new CompiledField.Builder("refunds", CompiledGraphQL.b(CompiledGraphQL.a(objectType)));
        builder13.e = listR13;
        CompiledField compiledFieldC19 = builder13.c();
        CompiledField.Builder builder14 = new CompiledField.Builder("refundTotal", CompiledGraphQL.b(CompiledGraphQL.a(objectType)));
        builder14.e = listR14;
        List listR15 = CollectionsKt.R(compiledFieldC13, compiledFieldC14, compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, compiledFieldC19, builder14.c(), d.g("disclaimer", customScalarType));
        q = listR15;
        CompiledField compiledFieldC20 = new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC21 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC22 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG5 = d.g("url", customScalarType);
        OrderHelpItemType.e.getClass();
        EnumType enumType2 = OrderHelpItemType.f;
        List listR16 = CollectionsKt.R(compiledFieldC20, compiledFieldC21, compiledFieldC22, compiledFieldG5, new CompiledField.Builder("itemType", CompiledGraphQL.b(enumType2)).c());
        r = listR16;
        List listR17 = CollectionsKt.R(new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType), new CompiledField.Builder("itemType", CompiledGraphQL.b(enumType2)).c());
        s = listR17;
        List listR18 = CollectionsKt.R(new CompiledField.Builder("day", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("time", CompiledGraphQL.b(customScalarType)).c());
        t = listR18;
        CompiledField compiledFieldC23 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC24 = new CompiledField.Builder("subTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder15 = new CompiledField.Builder("contactItems", a.f(ContactItem.f11278a));
        builder15.e = listR18;
        List listR19 = CollectionsKt.R(compiledFieldC23, compiledFieldC24, builder15.c());
        u = listR19;
        ObjectType objectType2 = OrderHelpItem.f11652a;
        CompiledField.Builder builder16 = new CompiledField.Builder("items", a.f(objectType2));
        builder16.e = listR16;
        CompiledField compiledFieldC25 = builder16.c();
        CompiledField.Builder builder17 = new CompiledField.Builder("imageUrl", customScalarType);
        builder17.c = a.s("includeAsyncChat", false);
        CompiledField compiledFieldC26 = builder17.c();
        CompiledField.Builder builder18 = new CompiledField.Builder("helpTitle", customScalarType);
        builder18.c = a.s("includeAsyncChat", false);
        CompiledField compiledFieldC27 = builder18.c();
        CompiledField.Builder builder19 = new CompiledField.Builder("helpItems", CompiledGraphQL.a(CompiledGraphQL.b(objectType2)));
        builder19.c = a.s("includeAsyncChat", false);
        builder19.e = listR17;
        CompiledField compiledFieldC28 = builder19.c();
        CompiledField.Builder builder20 = new CompiledField.Builder("contactTimes", OrderHelpContactTimes.f11651a);
        builder20.c = a.s("includeAsyncChat", false);
        builder20.e = listR19;
        List listR20 = CollectionsKt.R(compiledFieldC25, compiledFieldC26, compiledFieldC27, compiledFieldC28, builder20.c());
        v = listR20;
        CompiledField.Builder builder21 = new CompiledField.Builder("filter", OrderProductListFulfilmentFilter.f11665a);
        builder21.e = listQ;
        CompiledField compiledFieldC29 = builder21.c();
        CompiledField.Builder builder22 = new CompiledField.Builder("feed", CompiledGraphQL.b(CompiledGraphQL.a(OrderProductListFeedItem.f11664a)));
        builder22.e = listR6;
        CompiledField compiledFieldC30 = builder22.c();
        CompiledField compiledFieldC31 = new CompiledField.Builder("countLabel", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC32 = new CompiledField.Builder("totalLabel", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC33 = new CompiledField.Builder("totalValue", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder23 = new CompiledField.Builder("paymentDetails", CompiledGraphQL.b(OrderPaymentDetails.f11661a));
        builder23.e = listR15;
        CompiledField compiledFieldC34 = builder23.c();
        CompiledField.Builder builder24 = new CompiledField.Builder("help", OrderHelp.f11650a);
        builder24.e = listR20;
        List listR21 = CollectionsKt.R(compiledFieldC29, compiledFieldC30, compiledFieldC31, compiledFieldC32, compiledFieldC33, compiledFieldC34, builder24.c());
        w = listR21;
        CompiledField.Builder builder25 = new CompiledField.Builder("orderProductList", CompiledGraphQL.b(OrderProductList.f11663a));
        new CompiledArgument.Builder(Query.k2);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.j2);
        builder25.d = CollectionsKt.R(compiledArgument, new CompiledArgument());
        builder25.e = listR21;
        x = CollectionsKt.Q(builder25.c());
    }
}
