package com.woolworths.rewards.offers.details.fragment.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.rewards.graphql.type.Action;
import au.com.woolworths.rewards.graphql.type.ActionType;
import au.com.woolworths.rewards.graphql.type.BasicCoreBroadcastBanner;
import au.com.woolworths.rewards.graphql.type.ContentCta;
import au.com.woolworths.rewards.graphql.type.CoreBroadcastBannerStyle;
import au.com.woolworths.rewards.graphql.type.CoreBroadcastBannerUI;
import au.com.woolworths.rewards.graphql.type.DownloadableAsset;
import au.com.woolworths.rewards.graphql.type.DownloadableAssetFit;
import au.com.woolworths.rewards.graphql.type.DownloadableAssetType;
import au.com.woolworths.rewards.graphql.type.GraphQLInt;
import au.com.woolworths.rewards.graphql.type.GraphQLString;
import au.com.woolworths.rewards.graphql.type.HostedIcon;
import au.com.woolworths.rewards.graphql.type.IconAsset;
import au.com.woolworths.rewards.graphql.type.LocalAssetIconName;
import au.com.woolworths.rewards.graphql.type.OfferDetailsContentItem;
import au.com.woolworths.rewards.graphql.type.OfferDetailsFooter;
import au.com.woolworths.rewards.graphql.type.OfferDetailsHeader;
import au.com.woolworths.rewards.graphql.type.OfferDetailsStatusBadge;
import au.com.woolworths.rewards.graphql.type.RewardsOfferAnalytics;
import au.com.woolworths.rewards.graphql.type.RewardsOfferStatus;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.google.android.gms.common.Scopes;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import com.woolworths.rewards.offers.fragment.fragment.selections.ContentCtaFieldsSelections;
import com.woolworths.rewards.offers.fragment.selections.IconAssetSelections;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/rewards/offers/details/fragment/selections/OfferDetailsPageFragmentSelections;", "", "offers_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class OfferDetailsPageFragmentSelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f20883a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;

    static {
        CustomScalarType customScalarType = GraphQLString.f9617a;
        CompiledField compiledFieldC = new CompiledField.Builder("assetId", customScalarType).c();
        DownloadableAssetType.e.getClass();
        CompiledField compiledFieldC2 = new CompiledField.Builder("assetType", CompiledGraphQL.b(DownloadableAssetType.f)).c();
        CompiledField compiledFieldC3 = new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLInt.f9616a;
        CompiledField compiledFieldC4 = new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC5 = new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType2)).c();
        DownloadableAssetFit.e.getClass();
        List listR = CollectionsKt.R(compiledFieldC, compiledFieldC2, compiledFieldC3, compiledFieldC4, compiledFieldC5, new CompiledField.Builder("fit", DownloadableAssetFit.f).c(), d.g("altText", customScalarType));
        f20883a = listR;
        LocalAssetIconName.e.getClass();
        List listQ = CollectionsKt.Q(new CompiledField.Builder("iconName", CompiledGraphQL.b(LocalAssetIconName.f)).c());
        b = listQ;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        c = listQ2;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("LocalAsset", CollectionsKt.Q("LocalAsset"));
        builder.d = listQ;
        CompiledFragment compiledFragmentA = builder.a();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder2.d = listQ2;
        List listR2 = CollectionsKt.R(compiledFieldC6, compiledFragmentA, builder2.a());
        d = listR2;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("IconAsset", CollectionsKt.R("LocalAsset", "HostedIcon", "CoreIcon"));
        builder3.b(IconAssetSelections.d);
        List listR3 = CollectionsKt.R(compiledFieldC7, builder3.a());
        e = listR3;
        CompiledField compiledFieldC8 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        RewardsOfferStatus.e.getClass();
        EnumType enumType = RewardsOfferStatus.f;
        List listR4 = CollectionsKt.R(compiledFieldC8, new CompiledField.Builder("status", CompiledGraphQL.b(enumType)).c());
        f = listR4;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        g = listQ3;
        CompiledField compiledFieldC9 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder4.d = listQ3;
        List listR5 = CollectionsKt.R(compiledFieldC9, builder4.a());
        h = listR5;
        CompiledField compiledFieldC10 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CoreBroadcastBannerStyle.e.getClass();
        CompiledField compiledFieldC11 = new CompiledField.Builder("style", CompiledGraphQL.b(CoreBroadcastBannerStyle.f)).c();
        UnionType unionType = IconAsset.f9623a;
        CompiledField.Builder builder5 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(unionType));
        builder5.e = listR5;
        List listR6 = CollectionsKt.R(compiledFieldC10, compiledFieldG, compiledFieldC11, builder5.c());
        i = listR6;
        CompiledField compiledFieldG2 = d.g("id", customScalarType);
        ActionType.e.getClass();
        List listR7 = CollectionsKt.R(compiledFieldG2, new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.f)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c());
        j = listR7;
        CompiledField.Builder builder6 = new CompiledField.Builder("broadcastBannerUI", CompiledGraphQL.b(CoreBroadcastBannerUI.f9489a));
        builder6.e = listR6;
        CompiledField compiledFieldC12 = builder6.c();
        CompiledField.Builder builder7 = new CompiledField.Builder("broadcastBannerAction", Action.f9400a);
        builder7.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC12, builder7.c(), d.g("broadcastBannerActionLabel", customScalarType));
        k = listR8;
        CompiledField.Builder builder8 = new CompiledField.Builder("heroAsset", CompiledGraphQL.b(DownloadableAsset.f9500a));
        builder8.e = listR;
        CompiledField compiledFieldC13 = builder8.c();
        CompiledField.Builder builder9 = new CompiledField.Builder("leafAsset", CompiledGraphQL.b(unionType));
        builder9.e = listR2;
        CompiledField compiledFieldC14 = builder9.c();
        CompiledField.Builder builder10 = new CompiledField.Builder("roundelAsset", HostedIcon.f9622a);
        builder10.c = a.s("isTigerNewOfferEnabled", false);
        builder10.e = listR3;
        CompiledField compiledFieldC15 = builder10.c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType = OfferDetailsStatusBadge.f9687a;
        CompiledField.Builder builder11 = new CompiledField.Builder("statusBadge", objectType);
        builder11.e = listR4;
        CompiledField compiledFieldC18 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("broadcastBanner", BasicCoreBroadcastBanner.f9437a);
        builder12.e = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC13, compiledFieldC14, compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, builder12.c());
        l = listR9;
        CompiledField compiledFieldC19 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("OfferDetailsCard", CollectionsKt.Q("OfferDetailsCard"));
        builder13.b(OfferDetailsCardFragmentSelections.t);
        List listR10 = CollectionsKt.R(compiledFieldC19, builder13.a());
        m = listR10;
        CompiledField compiledFieldC20 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("OfferDetailsCard", CollectionsKt.Q("OfferDetailsCard"));
        builder14.d = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC20, builder14.a());
        n = listR11;
        CompiledField compiledFieldC21 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("ContentCta", CollectionsKt.Q("ContentCta"));
        builder15.b(ContentCtaFieldsSelections.b);
        List listR12 = CollectionsKt.R(compiledFieldC21, builder15.a());
        o = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("status", CompiledGraphQL.b(enumType)).c());
        p = listR13;
        CompiledField compiledFieldG3 = d.g(AnnotatedPrivateKey.LABEL, customScalarType);
        CompiledField.Builder builder16 = new CompiledField.Builder("cta", ContentCta.f9485a);
        builder16.e = listR12;
        CompiledField compiledFieldC22 = builder16.c();
        CompiledField.Builder builder17 = new CompiledField.Builder("statusBadge", objectType);
        builder17.e = listR13;
        List listR14 = CollectionsKt.R(compiledFieldG3, compiledFieldC22, builder17.c());
        q = listR14;
        CompiledField compiledFieldC23 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("OfferDetailsFooter", CollectionsKt.Q("OfferDetailsFooter"));
        builder18.d = listR14;
        List listR15 = CollectionsKt.R(compiledFieldC23, builder18.a());
        r = listR15;
        List listR16 = CollectionsKt.R(d.g("offerName", customScalarType), d.g("commId", customScalarType), d.g("uoid", customScalarType), d.g("campaignCode", customScalarType), d.g("campaignStream", customScalarType), d.g("channel", customScalarType), d.g("status", customScalarType), d.g("offerType", customScalarType), d.g("partnerId", customScalarType), d.g("rtlAccountID", customScalarType), d.g("rtlCampaignID", customScalarType), d.g("rtlCampaignCode", customScalarType), d.g("rtlCouponStart", customScalarType), d.g(Scopes.PROFILE, customScalarType));
        s = listR16;
        CompiledField.Builder builder19 = new CompiledField.Builder("header", CompiledGraphQL.b(OfferDetailsHeader.f9680a));
        builder19.e = listR9;
        CompiledField compiledFieldC24 = builder19.c();
        CompiledField.Builder builder20 = new CompiledField.Builder("content", d.j(OfferDetailsContentItem.f9678a));
        builder20.e = listR11;
        CompiledField compiledFieldC25 = builder20.c();
        CompiledField.Builder builder21 = new CompiledField.Builder("footer", OfferDetailsFooter.f9679a);
        builder21.e = listR15;
        CompiledField compiledFieldC26 = builder21.c();
        CompiledField.Builder builder22 = new CompiledField.Builder("offerAnalytics", CompiledGraphQL.b(RewardsOfferAnalytics.f9837a));
        builder22.e = listR16;
        t = CollectionsKt.R(compiledFieldC24, compiledFieldC25, compiledFieldC26, builder22.c());
    }
}
