package com.woolworths.rewards.offers.details.fragment.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.rewards.graphql.type.CircularProgressIndicator;
import au.com.woolworths.rewards.graphql.type.CircularProgressRing;
import au.com.woolworths.rewards.graphql.type.DownloadableAssetFit;
import au.com.woolworths.rewards.graphql.type.DownloadableAssetType;
import au.com.woolworths.rewards.graphql.type.GraphQLFloat;
import au.com.woolworths.rewards.graphql.type.GraphQLInt;
import au.com.woolworths.rewards.graphql.type.GraphQLString;
import au.com.woolworths.rewards.graphql.type.IconAsset;
import au.com.woolworths.rewards.graphql.type.LocalAssetIconName;
import au.com.woolworths.rewards.graphql.type.OfferDetailsCardRow;
import au.com.woolworths.rewards.graphql.type.OfferDetailsTrackerProgressRow;
import au.com.woolworths.rewards.graphql.type.OfferDetailsTrackerRow;
import au.com.woolworths.rewards.graphql.type.OfferDetailsTrackerTrailingElement;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.UnionType;
import com.woolworths.scanlibrary.util.widget.CircularProgressDrawable;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/rewards/offers/details/fragment/selections/OfferDetailsCardFragmentSelections;", "", "offers_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class OfferDetailsCardFragmentSelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f20882a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;

    static {
        LocalAssetIconName.e.getClass();
        EnumType enumType = LocalAssetIconName.f;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("iconName", CompiledGraphQL.b(enumType)).c());
        f20882a = listQ;
        CustomScalarType customScalarType = GraphQLString.f9617a;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        b = listQ2;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("LocalAsset", CollectionsKt.Q("LocalAsset"));
        builder.d = listQ;
        CompiledFragment compiledFragmentA = builder.a();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder2.d = listQ2;
        List listR = CollectionsKt.R(compiledFieldC, compiledFragmentA, builder2.a());
        c = listR;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder("elementLabel", CompiledGraphQL.b(customScalarType)).c());
        d = listQ3;
        List listR2 = CollectionsKt.R(d.g("pointsPrefix", customScalarType), new CompiledField.Builder("pointsLabel", CompiledGraphQL.b(customScalarType)).c());
        e = listR2;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("OfferDetailsTrackerTrailingElementLabel", CollectionsKt.Q("OfferDetailsTrackerTrailingElementLabel"));
        builder3.d = listQ3;
        CompiledFragment compiledFragmentA2 = builder3.a();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("OfferDetailsTrackerTrailingElementPoints", CollectionsKt.Q("OfferDetailsTrackerTrailingElementPoints"));
        builder4.d = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC2, compiledFragmentA2, builder4.a());
        f = listR3;
        UnionType unionType = IconAsset.f9623a;
        CompiledField.Builder builder5 = new CompiledField.Builder("rowLeadingAsset", unionType);
        builder5.e = listR;
        CompiledField compiledFieldC3 = builder5.c();
        CompiledField compiledFieldG = d.g("rowLabel", customScalarType);
        CompiledField.Builder builder6 = new CompiledField.Builder("rowTrailingElement", OfferDetailsTrackerTrailingElement.f9691a);
        builder6.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC3, compiledFieldG, builder6.c());
        g = listR4;
        List listR5 = CollectionsKt.R(new CompiledField.Builder("ringPercent", CompiledGraphQL.b(GraphQLFloat.f9614a)).c(), new CompiledField.Builder(CircularProgressDrawable.RING_COLOR_PROPERTY, CompiledGraphQL.b(customScalarType)).c());
        h = listR5;
        CompiledField.Builder builder7 = new CompiledField.Builder("primaryRing", CompiledGraphQL.b(CircularProgressRing.f9480a));
        builder7.e = listR5;
        List listQ4 = CollectionsKt.Q(builder7.c());
        i = listQ4;
        CompiledField compiledFieldG2 = d.g("progressRowTitle", customScalarType);
        CompiledField compiledFieldG3 = d.g("progressRowDescription", customScalarType);
        CompiledField.Builder builder8 = new CompiledField.Builder("progressRowCircularIndicator", CircularProgressIndicator.f9479a);
        builder8.e = listQ4;
        List listR6 = CollectionsKt.R(compiledFieldG2, compiledFieldG3, builder8.c());
        j = listR6;
        CompiledField.Builder builder9 = new CompiledField.Builder("trackerRow", OfferDetailsTrackerRow.f9690a);
        builder9.e = listR4;
        CompiledField compiledFieldC4 = builder9.c();
        CompiledField.Builder builder10 = new CompiledField.Builder("progressRow", OfferDetailsTrackerProgressRow.f9689a);
        builder10.e = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC4, builder10.c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        k = listR7;
        List listQ5 = CollectionsKt.Q(new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        l = listQ5;
        List listQ6 = CollectionsKt.Q(new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        m = listQ6;
        List listQ7 = CollectionsKt.Q(new CompiledField.Builder("iconName", CompiledGraphQL.b(enumType)).c());
        n = listQ7;
        List listQ8 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        o = listQ8;
        CompiledField compiledFieldC5 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("LocalAsset", CollectionsKt.Q("LocalAsset"));
        builder11.d = listQ7;
        CompiledFragment compiledFragmentA3 = builder11.a();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder12.d = listQ8;
        List listR8 = CollectionsKt.R(compiledFieldC5, compiledFragmentA3, builder12.a());
        p = listR8;
        CompiledField.Builder builder13 = new CompiledField.Builder("infoLeadingAsset", unionType);
        builder13.e = listR8;
        List listR9 = CollectionsKt.R(builder13.c(), d.g("infoDescription", customScalarType));
        q = listR9;
        DownloadableAssetType.e.getClass();
        CompiledField compiledFieldC6 = new CompiledField.Builder("assetType", CompiledGraphQL.b(DownloadableAssetType.f)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLInt.f9616a;
        CompiledField compiledFieldC8 = new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC9 = new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType2)).c();
        DownloadableAssetFit.e.getClass();
        List listR10 = CollectionsKt.R(compiledFieldC6, compiledFieldC7, compiledFieldC8, compiledFieldC9, new CompiledField.Builder("fit", DownloadableAssetFit.f).c(), d.g("altText", customScalarType));
        r = listR10;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("OfferDetailsTrackerComboRow", CollectionsKt.Q("OfferDetailsTrackerComboRow"));
        builder14.d = listR7;
        CompiledFragment compiledFragmentA4 = builder14.a();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("MarkdownTextItem", CollectionsKt.Q("MarkdownTextItem"));
        builder15.d = listQ5;
        CompiledFragment compiledFragmentA5 = builder15.a();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("SubheadTextItem", CollectionsKt.Q("SubheadTextItem"));
        builder16.d = listQ6;
        CompiledFragment compiledFragmentA6 = builder16.a();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("OfferDetailsInfoItem", CollectionsKt.Q("OfferDetailsInfoItem"));
        builder17.d = listR9;
        CompiledFragment compiledFragmentA7 = builder17.a();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("DownloadableAsset", CollectionsKt.Q("DownloadableAsset"));
        builder18.d = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC10, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, builder18.a());
        s = listR11;
        CompiledField.Builder builder19 = new CompiledField.Builder("rows", d.j(OfferDetailsCardRow.f9677a));
        builder19.e = listR11;
        t = CollectionsKt.Q(builder19.c());
    }
}
