package au.com.woolworths.modules.collectionmode.selections;

import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.shop.graphql.type.Badge;
import au.com.woolworths.shop.graphql.type.BadgeType;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.DeliveryWindowStatus;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.Mutation;
import au.com.woolworths.shop.graphql.type.ShoppingModeId;
import au.com.woolworths.shop.graphql.type.ShoppingModeMutationResponse;
import au.com.woolworths.shop.graphql.type.ShoppingModeType;
import au.com.woolworths.shop.graphql.type.ShoppingModeUnion;
import au.com.woolworths.shop.graphql.type.ShoppingModeVariantCondition;
import au.com.woolworths.shop.graphql.type.ShoppingModeVariantFulfilmentWindowSection;
import au.com.woolworths.shop.graphql.type.ShoppingModeVariantPrice;
import au.com.woolworths.shop.graphql.type.ShoppingModeVariantState;
import au.com.woolworths.shop.graphql.type.ShoppingModeVariantUnion;
import au.com.woolworths.shop.graphql.type.ShoppingModes;
import au.com.woolworths.shop.graphql.type.TextWithAlt;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÆ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/modules/collectionmode/selections/SelectShoppingModeMutationSelections;", "", "base-shop-app_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes4.dex */
public final class SelectShoppingModeMutationSelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f9161a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        CompiledField compiledFieldC = new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLInt.f11442a;
        List listR = CollectionsKt.R(compiledFieldC, new CompiledField.Builder("value", CompiledGraphQL.b(customScalarType2)).c(), d.g("suffix", customScalarType));
        f9161a = listR;
        List listR2 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("min", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("max", CompiledGraphQL.b(customScalarType2)).c(), d.g("suffix", customScalarType));
        b = listR2;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("Price", CollectionsKt.Q("Price"));
        builder.d = listR;
        CompiledFragment compiledFragmentA = builder.a();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("PriceRange", CollectionsKt.Q("PriceRange"));
        builder2.d = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC2, compiledFragmentA, builder2.a());
        c = listR3;
        List listQ = CollectionsKt.Q(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c());
        d = listQ;
        CompiledField compiledFieldC3 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        BadgeType.e.getClass();
        List listR4 = CollectionsKt.R(compiledFieldC3, new CompiledField.Builder("type", CompiledGraphQL.b(BadgeType.f)).c());
        e = listR4;
        CustomScalarType customScalarType3 = GraphQLBoolean.f11439a;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("_", customScalarType3).c());
        f = listQ2;
        List listR5 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        g = listR5;
        CompiledField compiledFieldC4 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        ButtonStyle.e.getClass();
        EnumType enumType = ButtonStyle.f;
        List listR6 = CollectionsKt.R(compiledFieldC4, new CompiledField.Builder("style", enumType).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType3)).c(), d.g(UrlHandler.ACTION, customScalarType), d.g("url", customScalarType));
        h = listR6;
        CompiledField compiledFieldC5 = new CompiledField.Builder("fulfilmentWindowStateTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder3 = new CompiledField.Builder("fulfilmentWindowStateSubtitle", TextWithAlt.f11967a);
        builder3.e = listR5;
        CompiledField compiledFieldC6 = builder3.c();
        CompiledField.Builder builder4 = new CompiledField.Builder("fulfilmentWindowStateButton", CompiledGraphQL.b(Button.f11080a));
        builder4.e = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC5, compiledFieldC6, builder4.c());
        i = listR7;
        List listR8 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), a.d("style", enumType), new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType3)).c(), d.g(UrlHandler.ACTION, customScalarType), d.g("url", customScalarType));
        j = listR8;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("DividerCard", CollectionsKt.Q("DividerCard"));
        builder5.d = listQ2;
        CompiledFragment compiledFragmentA2 = builder5.a();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("ShoppingModeVariantFulfilmentWindowState", CollectionsKt.Q("ShoppingModeVariantFulfilmentWindowState"));
        builder6.d = listR7;
        CompiledFragment compiledFragmentA3 = builder6.a();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("Button", CollectionsKt.Q("Button"));
        builder7.d = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC7, compiledFragmentA2, compiledFragmentA3, builder7.a());
        k = listR9;
        ShoppingModeId.e.getClass();
        CompiledField compiledFieldC8 = new CompiledField.Builder("id", CompiledGraphQL.b(ShoppingModeId.f)).c();
        CompiledField compiledFieldC9 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC10 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c();
        ShoppingModeVariantState.e.getClass();
        CompiledField compiledFieldC11 = new CompiledField.Builder("state", CompiledGraphQL.b(ShoppingModeVariantState.f)).c();
        DeliveryWindowStatus.e.getClass();
        CompiledField compiledFieldC12 = new CompiledField.Builder("status", DeliveryWindowStatus.f).c();
        CompiledField.Builder builder8 = new CompiledField.Builder("price", ShoppingModeVariantPrice.f11921a);
        builder8.e = listR3;
        CompiledField compiledFieldC13 = builder8.c();
        CompiledField.Builder builder9 = new CompiledField.Builder("conditions", CompiledGraphQL.a(ShoppingModeVariantCondition.f11918a));
        builder9.e = listQ;
        CompiledField compiledFieldC14 = builder9.c();
        CompiledField.Builder builder10 = new CompiledField.Builder("statusBadge", Badge.f11042a);
        builder10.e = listR4;
        CompiledField compiledFieldC15 = builder10.c();
        CompiledField compiledFieldG = d.g("footnote", customScalarType);
        CompiledField compiledFieldG2 = d.g("expressDeliveryStoreId", customScalarType2);
        CompiledField.Builder builder11 = new CompiledField.Builder("fulfilment", CompiledGraphQL.a(CompiledGraphQL.b(ShoppingModeVariantFulfilmentWindowSection.f11919a)));
        builder11.e = listR9;
        List listR10 = CollectionsKt.R(compiledFieldC8, compiledFieldC9, compiledFieldC10, compiledFieldC11, compiledFieldC12, compiledFieldC13, compiledFieldC14, compiledFieldC15, compiledFieldG, compiledFieldG2, builder11.c());
        l = listR10;
        CompiledField compiledFieldC16 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("ShoppingModeVariant", CollectionsKt.Q("ShoppingModeVariant"));
        builder12.d = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC16, builder12.a());
        m = listR11;
        ShoppingModeType.e.getClass();
        CompiledField compiledFieldC17 = new CompiledField.Builder("type", CompiledGraphQL.b(ShoppingModeType.f)).c();
        CompiledField compiledFieldC18 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder13 = new CompiledField.Builder("variants", d.j(ShoppingModeVariantUnion.f11922a));
        builder13.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC17, compiledFieldC18, builder13.c());
        n = listR12;
        CompiledField compiledFieldC19 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("ShoppingMode", CollectionsKt.Q("ShoppingMode"));
        builder14.d = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC19, builder14.a());
        o = listR13;
        CompiledField.Builder builder15 = new CompiledField.Builder("modes", d.j(ShoppingModeUnion.f11916a));
        builder15.e = listR13;
        List listQ3 = CollectionsKt.Q(builder15.c());
        p = listQ3;
        CompiledField compiledFieldC20 = new CompiledField.Builder("isSuccess", CompiledGraphQL.b(customScalarType3)).c();
        CompiledField.Builder builder16 = new CompiledField.Builder("shoppingModes", CompiledGraphQL.b(ShoppingModes.f11923a));
        builder16.e = listQ3;
        List listR14 = CollectionsKt.R(compiledFieldC20, builder16.c());
        q = listR14;
        CompiledField.Builder builder17 = new CompiledField.Builder("selectShoppingMode", CompiledGraphQL.b(ShoppingModeMutationResponse.f11900a));
        new CompiledArgument.Builder(Mutation.C);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Mutation.D);
        builder17.d = CollectionsKt.R(compiledArgument, new CompiledArgument());
        builder17.e = listR14;
        r = CollectionsKt.Q(builder17.c());
    }
}
