package com.woolworths.feature.shop.contentpage.fragment.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.shop.aem.components.offercard.fragment.selections.OfferCardSelections;
import au.com.woolworths.shop.aem.components.recipes.fragment.selections.RecipeSummaryCardFragmentSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionMetaData;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.BasicCoreRow;
import au.com.woolworths.shop.graphql.type.CardHeight;
import au.com.woolworths.shop.graphql.type.CatalogueCardType;
import au.com.woolworths.shop.graphql.type.CompatibleColor;
import au.com.woolworths.shop.graphql.type.ContentCardFooter;
import au.com.woolworths.shop.graphql.type.ContentCardSize;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerUI;
import au.com.woolworths.shop.graphql.type.CoreButton;
import au.com.woolworths.shop.graphql.type.CoreColorTheme;
import au.com.woolworths.shop.graphql.type.CoreForegroundColors;
import au.com.woolworths.shop.graphql.type.CoreRowUI;
import au.com.woolworths.shop.graphql.type.DownloadableAssetFit;
import au.com.woolworths.shop.graphql.type.DownloadableAssetType;
import au.com.woolworths.shop.graphql.type.EditorialCarouselItem;
import au.com.woolworths.shop.graphql.type.FooterStyle;
import au.com.woolworths.shop.graphql.type.GenericPageFeedItem;
import au.com.woolworths.shop.graphql.type.GenericPageHeader;
import au.com.woolworths.shop.graphql.type.GenericPageHeroImageType;
import au.com.woolworths.shop.graphql.type.GoogleAdBannerCard;
import au.com.woolworths.shop.graphql.type.GoogleAdCustomTargeting;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLID;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.GridListItem;
import au.com.woolworths.shop.graphql.type.HorizontalListItem;
import au.com.woolworths.shop.graphql.type.IconAsset;
import au.com.woolworths.shop.graphql.type.ImageWithAlt;
import au.com.woolworths.shop.graphql.type.InsetBannerAction;
import au.com.woolworths.shop.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.shop.graphql.type.InsetBannerActionType;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.Link;
import au.com.woolworths.shop.graphql.type.MethodItem;
import au.com.woolworths.shop.graphql.type.MoreCardStyle;
import au.com.woolworths.shop.graphql.type.PageCoverContentAlignment;
import au.com.woolworths.shop.graphql.type.PageCoverContentFormat;
import au.com.woolworths.shop.graphql.type.PageCoverImagePosition;
import au.com.woolworths.shop.graphql.type.PageCoverTitleTextSize;
import au.com.woolworths.shop.graphql.type.ParagraphTextItemType;
import au.com.woolworths.shop.graphql.type.ProductCard;
import au.com.woolworths.shop.graphql.type.TealiumAnalytics;
import au.com.woolworths.shop.graphql.type.TextWithAlt;
import au.com.woolworths.shop.graphql.type.TitleSectionTypes;
import au.com.woolworths.shop.graphql.type.UniversalInventoryNextBestAction;
import au.com.woolworths.shop.graphql.type.VerticalListAction;
import au.com.woolworths.shop.graphql.type.VerticalListItem;
import au.com.woolworths.shop.graphql.type.Video;
import com.apollographql.apollo.api.CompiledCondition;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.InterfaceType;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.google.android.gms.ads.OutOfContextTestingActivity;
import com.google.android.gms.common.api.internal.a;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.salesforce.marketingcloud.storage.db.k;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/feature/shop/contentpage/fragment/selections/ContentPageSelections;", "", "content-page_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class ContentPageSelections {
    public static final List A;
    public static final List A0;
    public static final List B;
    public static final List B0;
    public static final List C;
    public static final List C0;
    public static final List D;
    public static final List D0;
    public static final List E;
    public static final List E0;
    public static final List F;
    public static final List F0;
    public static final List G;
    public static final List G0;
    public static final List H;
    public static final List H0;
    public static final List I;
    public static final List I0;
    public static final List J;
    public static final List J0;
    public static final List K;
    public static final List K0;
    public static final List L;
    public static final List L0;
    public static final List M;
    public static final List M0;
    public static final List N;
    public static final List N0;
    public static final List O;
    public static final List O0;
    public static final List P;
    public static final List P0;
    public static final List Q;
    public static final List Q0;
    public static final List R;
    public static final List R0;
    public static final List S;
    public static final List S0;
    public static final List T;
    public static final List T0;
    public static final List U;
    public static final List U0;
    public static final List V;
    public static final List V0;
    public static final List W;
    public static final List W0;
    public static final List X;
    public static final List X0;
    public static final List Y;
    public static final List Y0;
    public static final List Z;
    public static final List Z0;

    /* renamed from: a, reason: collision with root package name */
    public static final List f19785a;
    public static final List a0;
    public static final List a1;
    public static final List b;
    public static final List b0;
    public static final List b1;
    public static final List c;
    public static final List c0;
    public static final List c1;
    public static final List d;
    public static final List d0;
    public static final List d1;
    public static final List e;
    public static final List e0;
    public static final List e1;
    public static final List f;
    public static final List f0;
    public static final List g;
    public static final List g0;
    public static final List h;
    public static final List h0;
    public static final List i;
    public static final List i0;
    public static final List j;
    public static final List j0;
    public static final List k;
    public static final List k0;
    public static final List l;
    public static final List l0;
    public static final List m;
    public static final List m0;
    public static final List n;
    public static final List n0;
    public static final List o;
    public static final List o0;
    public static final List p;
    public static final List p0;
    public static final List q;
    public static final List q0;
    public static final List r;
    public static final List r0;
    public static final List s;
    public static final List s0;
    public static final List t;
    public static final List t0;
    public static final List u;
    public static final List u0;
    public static final List v;
    public static final List v0;
    public static final List w;
    public static final List w0;
    public static final List x;
    public static final List x0;
    public static final List y;
    public static final List y0;
    public static final List z;
    public static final List z0;

    static {
        List listR = CollectionsKt.R(new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("thumbnail", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("duration", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("id", GraphQLString.Companion.a()).c());
        f19785a = listR;
        CompiledField compiledFieldC = new CompiledField.Builder("pageTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC2 = new CompiledField.Builder("heroImage", GraphQLString.Companion.a()).c();
        GenericPageHeroImageType.e.getClass();
        CompiledField compiledFieldC3 = new CompiledField.Builder("heroImageType", GenericPageHeroImageType.Companion.a()).c();
        CompiledField.Builder builder = new CompiledField.Builder("video", Video.f12006a);
        builder.e(listR);
        List listR2 = CollectionsKt.R(compiledFieldC, compiledFieldC2, compiledFieldC3, builder.c());
        b = listR2;
        List listR3 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        c = listR3;
        List listR4 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        d = listR4;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("lightHexCode", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        e = listQ;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("lightHexCode", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        f = listQ2;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder("lightHexCode", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        g = listQ3;
        List listQ4 = CollectionsKt.Q(new CompiledField.Builder("lightHexCode", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        h = listQ4;
        ObjectType objectType = CompatibleColor.f11275a;
        CompiledField.Builder builder2 = new CompiledField.Builder("primary", CompiledGraphQL.b(objectType));
        builder2.e(listQ2);
        CompiledField compiledFieldC4 = builder2.c();
        CompiledField.Builder builder3 = new CompiledField.Builder("secondary", CompiledGraphQL.b(objectType));
        builder3.e(listQ3);
        CompiledField compiledFieldC5 = builder3.c();
        CompiledField.Builder builder4 = new CompiledField.Builder("highlight", CompiledGraphQL.b(objectType));
        builder4.e(listQ4);
        List listR5 = CollectionsKt.R(compiledFieldC4, compiledFieldC5, builder4.c());
        i = listR5;
        CompiledField.Builder builder5 = new CompiledField.Builder("background", CompiledGraphQL.b(objectType));
        builder5.e(listQ);
        CompiledField compiledFieldC6 = builder5.c();
        ObjectType objectType2 = CoreForegroundColors.f11289a;
        CompiledField.Builder builder6 = new CompiledField.Builder("foreground", CompiledGraphQL.b(CoreForegroundColors.Companion.a()));
        builder6.e(listR5);
        List listR6 = CollectionsKt.R(compiledFieldC6, builder6.c());
        j = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        k = listR7;
        List listR8 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        l = listR8;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        PageCoverContentFormat.e.getClass();
        CompiledField compiledFieldC8 = new CompiledField.Builder("pageCoverContentFormat", CompiledGraphQL.b(PageCoverContentFormat.Companion.a())).c();
        PageCoverContentAlignment.e.getClass();
        CompiledField compiledFieldC9 = new CompiledField.Builder("pageCoverContentAlignment", CompiledGraphQL.b(PageCoverContentAlignment.Companion.a())).c();
        ObjectType objectType3 = CoreColorTheme.f11288a;
        CompiledField.Builder builder7 = new CompiledField.Builder("pageCoverContentTheme", CompiledGraphQL.b(CoreColorTheme.Companion.a()));
        builder7.e(listR6);
        CompiledField compiledFieldC10 = builder7.c();
        ObjectType objectType4 = ImageWithAlt.f11487a;
        CompiledField.Builder builder8 = new CompiledField.Builder("pageCoverPrimaryImage", ImageWithAlt.Companion.a());
        builder8.e(listR7);
        CompiledField compiledFieldC11 = builder8.c();
        PageCoverImagePosition.e.getClass();
        CompiledField compiledFieldC12 = new CompiledField.Builder("pageCoverPrimaryImagePosition", PageCoverImagePosition.Companion.a()).c();
        CompiledField.Builder builder9 = new CompiledField.Builder("pageCoverLogos", CompiledGraphQL.a(CompiledGraphQL.b(ImageWithAlt.Companion.a())));
        builder9.e(listR8);
        CompiledField compiledFieldC13 = builder9.c();
        CompiledField compiledFieldC14 = new CompiledField.Builder("pageCoverTitle", GraphQLString.Companion.a()).c();
        PageCoverTitleTextSize.e.getClass();
        List listR9 = CollectionsKt.R(compiledFieldC7, compiledFieldC8, compiledFieldC9, compiledFieldC10, compiledFieldC11, compiledFieldC12, compiledFieldC13, compiledFieldC14, new CompiledField.Builder("pageCoverTitleSize", PageCoverTitleTextSize.Companion.a()).c(), new CompiledField.Builder("pageCoverSubTitle", GraphQLString.Companion.a()).c());
        m = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(OutOfContextTestingActivity.AD_UNIT_KEY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("nativeCustomTemplateId", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("targeting", GoogleAdCustomTargeting.Companion.a()).c(), new CompiledField.Builder("iabSize", GraphQLString.Companion.a()).c(), new CompiledField.Builder("correlator", GraphQLString.Companion.a()).c(), new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c());
        n = listR10;
        List listR11 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        o = listR11;
        List listR12 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        p = listR12;
        CompiledField compiledFieldC15 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("link", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("image", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC18 = new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CardHeight.e.getClass();
        CompiledField compiledFieldC19 = new CompiledField.Builder("cardHeight", CompiledGraphQL.b(CardHeight.Companion.a())).c();
        CompiledField compiledFieldC20 = new CompiledField.Builder("analytics", TealiumAnalytics.Companion.a()).c();
        CompiledField compiledFieldC21 = new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c();
        ObjectType objectType5 = Analytics.f11028a;
        CompiledField.Builder builder10 = new CompiledField.Builder("actionableCardImpressionAnalytics", Analytics.Companion.a());
        builder10.e(listR11);
        CompiledField compiledFieldC22 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("actionableCardClickAnalytics", Analytics.Companion.a());
        builder11.e(listR12);
        List listR13 = CollectionsKt.R(compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, compiledFieldC19, compiledFieldC20, compiledFieldC21, compiledFieldC22, builder11.c());
        q = listR13;
        CompiledField compiledFieldC23 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder12.b(listR13);
        List listR14 = CollectionsKt.R(compiledFieldC23, builder12.a());
        r = listR14;
        ObjectType objectType6 = GoogleAdBannerCard.f11435a;
        CompiledField.Builder builder13 = new CompiledField.Builder("googleAdBannerCard", GoogleAdBannerCard.Companion.a());
        builder13.e(listR10);
        CompiledField compiledFieldC24 = builder13.c();
        UnionType unionType = UniversalInventoryNextBestAction.f11980a;
        List listR15 = CollectionsKt.R(compiledFieldC24, a.e("includeUniversalInventoryFallback", false, new CompiledField.Builder("nextBestAction", UniversalInventoryNextBestAction.Companion.a()), listR14));
        s = listR15;
        TitleSectionTypes.e.getClass();
        List listR16 = CollectionsKt.R(new CompiledField.Builder("titleSectionType", CompiledGraphQL.b(TitleSectionTypes.f)).c(), new CompiledField.Builder("titleSectionText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        t = listR16;
        DownloadableAssetType.e.getClass();
        CompiledField compiledFieldC25 = new CompiledField.Builder("assetType", CompiledGraphQL.b(DownloadableAssetType.f)).c();
        CompiledField compiledFieldC26 = new CompiledField.Builder("assetUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC27 = new CompiledField.Builder("assetWidth", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC28 = new CompiledField.Builder("assetHeight", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        DownloadableAssetFit.e.getClass();
        CompiledField compiledFieldC29 = new CompiledField.Builder("fit", DownloadableAssetFit.f).c();
        CompiledField.Builder builder14 = new CompiledField.Builder("altText", GraphQLString.Companion.a());
        builder14.a("alternativeText");
        List listR17 = CollectionsKt.R(compiledFieldC25, compiledFieldC26, compiledFieldC27, compiledFieldC28, compiledFieldC29, builder14.c());
        u = listR17;
        CompiledField compiledFieldC30 = new CompiledField.Builder("content", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ParagraphTextItemType.e.getClass();
        List listR18 = CollectionsKt.R(compiledFieldC30, new CompiledField.Builder("type", CompiledGraphQL.b(ParagraphTextItemType.Companion.a())).c());
        v = listR18;
        CompiledField compiledFieldC31 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder15.b(ActionFieldsSelections.a());
        List listR19 = CollectionsKt.R(compiledFieldC31, builder15.a());
        w = listR19;
        CompiledField compiledFieldC32 = new CompiledField.Builder("contentCardId", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC33 = new CompiledField.Builder("contentCardImageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC34 = new CompiledField.Builder("contentCardTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC35 = new CompiledField.Builder("contentCardDescription", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC36 = new CompiledField.Builder("contentCardIsVideoAvailable", GraphQLBoolean.Companion.a()).c();
        ObjectType objectType7 = Action.f10997a;
        CompiledField.Builder builder16 = new CompiledField.Builder("contentCardAction", Action.Companion.a());
        builder16.e(listR19);
        List listR20 = CollectionsKt.R(compiledFieldC32, compiledFieldC33, compiledFieldC34, compiledFieldC35, compiledFieldC36, builder16.c());
        x = listR20;
        CompiledField compiledFieldC37 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("InfoTile", CollectionsKt.Q("InfoTile"));
        List list = InfoTileFieldsSelections.g;
        builder17.b(list);
        List listR21 = CollectionsKt.R(compiledFieldC37, builder17.a());
        y = listR21;
        CompiledField compiledFieldC38 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("FullWidthContentCard", CollectionsKt.Q("FullWidthContentCard"));
        builder18.b(listR20);
        List listR22 = CollectionsKt.R(compiledFieldC38, builder18.a(), d.i("isInfoTileEnabled", false, new CompiledFragment.Builder("InfoTile", CollectionsKt.Q("InfoTile")), listR21));
        z = listR22;
        CompiledField compiledFieldC39 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder19.b(ActionFieldsSelections.a());
        List listR23 = CollectionsKt.R(compiledFieldC39, builder19.a());
        A = listR23;
        CompiledField compiledFieldC40 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder20 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(Action.Companion.a()));
        builder20.e(listR23);
        List listR24 = CollectionsKt.R(compiledFieldC40, builder20.c());
        B = listR24;
        CompiledField compiledFieldC41 = new CompiledField.Builder("verticalListTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC42 = new CompiledField.Builder("verticalListSubtitle", GraphQLString.Companion.a()).c();
        UnionType unionType2 = VerticalListItem.f12005a;
        CompiledField.Builder builder21 = new CompiledField.Builder("verticalListItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(VerticalListItem.Companion.a()))));
        builder21.e(listR22);
        CompiledField compiledFieldC43 = builder21.c();
        ObjectType objectType8 = VerticalListAction.f12004a;
        CompiledField.Builder builder22 = new CompiledField.Builder("verticalListAction", VerticalListAction.Companion.a());
        builder22.e(listR24);
        List listR25 = CollectionsKt.R(compiledFieldC41, compiledFieldC42, compiledFieldC43, builder22.c());
        C = listR25;
        List listR26 = CollectionsKt.R(new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        D = listR26;
        CompiledField compiledFieldC44 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder23.b(ActionFieldsSelections.a());
        List listR27 = CollectionsKt.R(compiledFieldC44, builder23.a());
        E = listR27;
        ObjectType objectType9 = TextWithAlt.f11967a;
        CompiledField.Builder builder24 = new CompiledField.Builder("linkTextWithAlt", CompiledGraphQL.b(TextWithAlt.Companion.a()));
        builder24.e(listR26);
        CompiledField compiledFieldC45 = builder24.c();
        CompiledField compiledFieldC46 = new CompiledField.Builder("linkId", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder25 = new CompiledField.Builder("linkAction", CompiledGraphQL.b(Action.Companion.a()));
        builder25.e(listR27);
        List listR28 = CollectionsKt.R(compiledFieldC45, compiledFieldC46, builder25.c());
        F = listR28;
        List listR29 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        G = listR29;
        List listR30 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        H = listR30;
        List listR31 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        I = listR31;
        CompiledField compiledFieldC47 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("RecipeSummaryCard", CollectionsKt.Q("RecipeSummaryCard"));
        List list2 = RecipeSummaryCardFragmentSelections.d;
        builder26.b(list2);
        List listR32 = CollectionsKt.R(compiledFieldC47, builder26.a());
        J = listR32;
        List listQ5 = CollectionsKt.Q(new CompiledField.Builder(k.a.g, CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c());
        K = listQ5;
        List listQ6 = CollectionsKt.Q(new CompiledField.Builder("source", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        L = listQ6;
        CompiledField compiledFieldC48 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder27 = new CompiledFragment.Builder("RecipeTagList", CollectionsKt.Q("RecipeTagList"));
        builder27.b(listQ5);
        CompiledFragment compiledFragmentA = builder27.a();
        CompiledFragment.Builder builder28 = new CompiledFragment.Builder("RecipeSource", CollectionsKt.Q("RecipeSource"));
        builder28.b(listQ6);
        List listR33 = CollectionsKt.R(compiledFieldC48, compiledFragmentA, builder28.a());
        M = listR33;
        CompiledField.Builder builder29 = new CompiledField.Builder("actionMetadata", d.j(ActionMetaData.f10998a));
        builder29.e(listR33);
        List listQ7 = CollectionsKt.Q(builder29.c());
        N = listQ7;
        CompiledField compiledFieldC49 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder30 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder30.b(ActionFieldsSelections.a());
        List listR34 = CollectionsKt.R(compiledFieldC49, builder30.a());
        O = listR34;
        CompiledField compiledFieldC50 = new CompiledField.Builder("navRoundelId", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC51 = new CompiledField.Builder("navRoundelImageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC52 = new CompiledField.Builder("navRoundelTitle", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder31 = new CompiledField.Builder("navRoundelAction", Action.Companion.a());
        builder31.e(listR34);
        List listR35 = CollectionsKt.R(compiledFieldC50, compiledFieldC51, compiledFieldC52, builder31.c());
        P = listR35;
        CompiledField compiledFieldC53 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder32 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder32.b(ActionFieldsSelections.a());
        List listR36 = CollectionsKt.R(compiledFieldC53, builder32.a());
        Q = listR36;
        CompiledField compiledFieldC54 = new CompiledField.Builder("pillText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder33 = new CompiledField.Builder("pillAction", CompiledGraphQL.b(Action.Companion.a()));
        builder33.e(listR36);
        List listR37 = CollectionsKt.R(compiledFieldC54, builder33.c());
        R = listR37;
        CompiledField compiledFieldC55 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder34 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder34.b(ActionFieldsSelections.a());
        List listR38 = CollectionsKt.R(compiledFieldC55, builder34.a());
        S = listR38;
        List listR39 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        T = listR39;
        FooterStyle.e.getClass();
        CompiledField compiledFieldC56 = new CompiledField.Builder("style", CompiledGraphQL.b(FooterStyle.f)).c();
        CompiledField compiledFieldC57 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, GraphQLString.Companion.a()).c();
        CompiledField.Builder builder35 = new CompiledField.Builder("logo", ImageWithAlt.Companion.a());
        builder35.e(listR39);
        List listR40 = CollectionsKt.R(compiledFieldC56, compiledFieldC57, builder35.c());
        U = listR40;
        List listR41 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        V = listR41;
        List listR42 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        W = listR42;
        CompiledField compiledFieldC58 = new CompiledField.Builder("contentCardId", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC59 = new CompiledField.Builder("contentCardImageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC60 = new CompiledField.Builder("contentCardTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC61 = new CompiledField.Builder("contentCardDescription", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder36 = new CompiledField.Builder("contentCardAction", Action.Companion.a());
        builder36.e(listR38);
        CompiledField compiledFieldC62 = builder36.c();
        CompiledField.Builder builder37 = new CompiledField.Builder("contentCardFooter", ContentCardFooter.f11281a);
        builder37.e(listR40);
        CompiledField compiledFieldC63 = builder37.c();
        CompiledField.Builder builder38 = new CompiledField.Builder("contentCardBrandImage", ImageWithAlt.Companion.a());
        builder38.e(listR41);
        CompiledField compiledFieldC64 = builder38.c();
        CompiledField compiledFieldC65 = new CompiledField.Builder("contentCardIsVideoAvailable", GraphQLBoolean.Companion.a()).c();
        ContentCardSize.e.getClass();
        CompiledField compiledFieldC66 = new CompiledField.Builder("contentCardSize", ContentCardSize.f).c();
        CompiledField compiledFieldC67 = new CompiledField.Builder("contentCardSponsoredText", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder39 = new CompiledField.Builder("contentCardAnalytics", Analytics.Companion.a());
        builder39.e(listR42);
        List listR43 = CollectionsKt.R(compiledFieldC58, compiledFieldC59, compiledFieldC60, compiledFieldC61, compiledFieldC62, compiledFieldC63, compiledFieldC64, compiledFieldC65, compiledFieldC66, compiledFieldC67, builder39.c());
        X = listR43;
        CompiledField compiledFieldC68 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder40 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder40.b(ActionFieldsSelections.a());
        List listR44 = CollectionsKt.R(compiledFieldC68, builder40.a());
        Y = listR44;
        MoreCardStyle.e.getClass();
        CompiledField compiledFieldC69 = new CompiledField.Builder("moreCardStyle", CompiledGraphQL.b(MoreCardStyle.Companion.a())).c();
        CompiledField.Builder builder41 = new CompiledField.Builder("moreCardAction", CompiledGraphQL.b(Action.Companion.a()));
        builder41.e(listR44);
        List listR45 = CollectionsKt.R(compiledFieldC69, builder41.c());
        Z = listR45;
        CompiledField compiledFieldC70 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder42 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder42.b(ActionFieldsSelections.a());
        List listR46 = CollectionsKt.R(compiledFieldC70, builder42.a());
        a0 = listR46;
        CompiledField compiledFieldC71 = new CompiledField.Builder("productCategoryTileImageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC72 = new CompiledField.Builder("productCategoryTileLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder43 = new CompiledField.Builder("productCategoryTileAction", CompiledGraphQL.b(Action.Companion.a()));
        builder43.e(listR46);
        List listR47 = CollectionsKt.R(compiledFieldC71, compiledFieldC72, builder43.c());
        b0 = listR47;
        CompiledField compiledFieldC73 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder44 = new CompiledFragment.Builder("OfferCard", CollectionsKt.Q("OfferCard"));
        builder44.b(OfferCardSelections.a());
        List listR48 = CollectionsKt.R(compiledFieldC73, builder44.a());
        c0 = listR48;
        CompiledField compiledFieldC74 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder45 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder45.b(ActionFieldsSelections.a());
        List listR49 = CollectionsKt.R(compiledFieldC74, builder45.a());
        d0 = listR49;
        CompiledField compiledFieldC75 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC76 = new CompiledField.Builder("linkCardTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC77 = new CompiledField.Builder("linkCardSubtitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC78 = new CompiledField.Builder("linkCardImage", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder46 = new CompiledField.Builder("linkCardAction", CompiledGraphQL.b(Action.Companion.a()));
        builder46.e(listR49);
        List listR50 = CollectionsKt.R(compiledFieldC75, compiledFieldC76, compiledFieldC77, compiledFieldC78, builder46.c(), new CompiledField.Builder("isQuickLinkView", GraphQLBoolean.Companion.a()).c());
        e0 = listR50;
        List listR51 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        f0 = listR51;
        List listR52 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        g0 = listR52;
        List listR53 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        h0 = listR53;
        ObjectType objectType10 = ProductCard.f11717a;
        CompiledField.Builder builder47 = new CompiledField.Builder("promotionCardProduct", CompiledGraphQL.b(ProductCard.Companion.a()));
        builder47.e(listR51);
        CompiledField compiledFieldC79 = builder47.c();
        CompiledField compiledFieldC80 = new CompiledField.Builder("promotionCardOfferId", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder48 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder48.e(listR52);
        CompiledField compiledFieldC81 = builder48.c();
        CompiledField.Builder builder49 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder49.e(listR53);
        List listR54 = CollectionsKt.R(compiledFieldC79, compiledFieldC80, compiledFieldC81, builder49.c());
        i0 = listR54;
        CompiledField compiledFieldC82 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder50 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder50.b(listR31);
        CompiledFragment compiledFragmentA2 = builder50.a();
        CompiledFragment.Builder builder51 = new CompiledFragment.Builder("RecipeSummaryCard", CollectionsKt.Q("RecipeSummaryCard"));
        builder51.b(listR32);
        CompiledFragment compiledFragmentA3 = builder51.a();
        CompiledFragment.Builder builder52 = new CompiledFragment.Builder("RecipeMoreCard", CollectionsKt.Q("RecipeMoreCard"));
        builder52.b(listQ7);
        CompiledFragment compiledFragmentA4 = builder52.a();
        CompiledFragment.Builder builder53 = new CompiledFragment.Builder("NavRoundel", CollectionsKt.Q("NavRoundel"));
        builder53.b(listR35);
        CompiledFragment compiledFragmentA5 = builder53.a();
        CompiledFragment.Builder builder54 = new CompiledFragment.Builder("Pill", CollectionsKt.Q("Pill"));
        builder54.b(listR37);
        CompiledFragment compiledFragmentA6 = builder54.a();
        CompiledFragment.Builder builder55 = new CompiledFragment.Builder("ContentCard", CollectionsKt.Q("ContentCard"));
        builder55.b(listR43);
        CompiledFragment compiledFragmentA7 = builder55.a();
        CompiledFragment.Builder builder56 = new CompiledFragment.Builder("MoreCard", CollectionsKt.Q("MoreCard"));
        builder56.b(listR45);
        CompiledFragment compiledFragmentA8 = builder56.a();
        CompiledFragment.Builder builder57 = new CompiledFragment.Builder("ProductCategoryTile", CollectionsKt.Q("ProductCategoryTile"));
        builder57.b(listR47);
        CompiledFragment compiledFragmentA9 = builder57.a();
        CompiledFragment.Builder builder58 = new CompiledFragment.Builder("OfferCard", CollectionsKt.Q("OfferCard"));
        builder58.b(listR48);
        CompiledFragment compiledFragmentA10 = builder58.a();
        CompiledFragment.Builder builder59 = new CompiledFragment.Builder("QuickLinkCard", CollectionsKt.Q("QuickLinkCard"));
        builder59.b(listR50);
        CompiledFragment compiledFragmentA11 = builder59.a();
        CompiledFragment.Builder builder60 = new CompiledFragment.Builder("PromotionCard", CollectionsKt.Q("PromotionCard"));
        builder60.b(listR54);
        List listR55 = CollectionsKt.R(compiledFieldC82, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, compiledFragmentA8, compiledFragmentA9, compiledFragmentA10, compiledFragmentA11, builder60.a());
        j0 = listR55;
        ObjectType objectType11 = Link.f11514a;
        CompiledField.Builder builder61 = new CompiledField.Builder("horizontalListTrailingLink", Link.Companion.a());
        builder61.e(listR28);
        CompiledField compiledFieldC83 = builder61.c();
        CompiledField.Builder builder62 = new CompiledField.Builder("horizontalListAnalytics", Analytics.Companion.a());
        builder62.e(listR29);
        CompiledField compiledFieldC84 = builder62.c();
        CompiledField.Builder builder63 = new CompiledField.Builder("horizontalListImpressionAnalytics", Analytics.Companion.a());
        builder63.e(listR30);
        CompiledField compiledFieldC85 = builder63.c();
        CompiledField compiledFieldC86 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC87 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC88 = new CompiledField.Builder("deepLink", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC89 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC90 = new CompiledField.Builder("actionPath", GraphQLString.Companion.a()).c();
        UnionType unionType3 = HorizontalListItem.f11475a;
        CompiledField.Builder builder64 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder64.e(listR55);
        List listR56 = CollectionsKt.R(compiledFieldC83, compiledFieldC84, compiledFieldC85, compiledFieldC86, compiledFieldC87, compiledFieldC88, compiledFieldC89, compiledFieldC90, builder64.c(), new CompiledField.Builder("actionPath", GraphQLString.Companion.a()).c(), new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c(), new CompiledField.Builder("deepLink", GraphQLString.Companion.a()).c());
        k0 = listR56;
        CompiledField compiledFieldC91 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC92 = new CompiledField.Builder("content", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder65 = new CompiledField.Builder("image", GraphQLString.Companion.a());
        builder65.a("methodImage");
        List listR57 = CollectionsKt.R(compiledFieldC91, compiledFieldC92, builder65.c());
        l0 = listR57;
        CompiledField compiledFieldC93 = new CompiledField.Builder("panelTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC94 = new CompiledField.Builder("caption", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder66 = new CompiledField.Builder("items", au.com.woolworths.feature.rewards.everydayextras.signup.selections.a.f(MethodItem.f11573a));
        builder66.e(listR57);
        List listR58 = CollectionsKt.R(compiledFieldC93, compiledFieldC94, builder66.c(), new CompiledField.Builder("disclaimer", GraphQLString.Companion.a()).c());
        m0 = listR58;
        InsetBannerActionPlacement.e.getClass();
        CompiledField compiledFieldC95 = new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.Companion.a())).c();
        InsetBannerActionType.e.getClass();
        List listR59 = CollectionsKt.R(compiledFieldC95, new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        n0 = listR59;
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC96 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField compiledFieldC97 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder67 = new CompiledField.Builder("title", GraphQLString.Companion.a());
        builder67.a("bannerTitle");
        CompiledField compiledFieldC98 = builder67.c();
        ObjectType objectType12 = InsetBannerAction.f11510a;
        CompiledField.Builder builder68 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.Companion.a());
        builder68.e(listR59);
        List listR60 = CollectionsKt.R(compiledFieldC96, compiledFieldC97, compiledFieldC98, builder68.c());
        o0 = listR60;
        CompiledField compiledFieldC99 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder69 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        List list3 = HostedIconFieldsSelections.f19789a;
        builder69.b(list3);
        List listR61 = CollectionsKt.R(compiledFieldC99, builder69.a());
        p0 = listR61;
        CompiledField compiledFieldC100 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder70 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder70.b(listR61);
        List listR62 = CollectionsKt.R(compiledFieldC100, builder70.a());
        q0 = listR62;
        UnionType unionType4 = IconAsset.f11477a;
        CompiledField.Builder builder71 = new CompiledField.Builder("leadingAsset", IconAsset.Companion.a());
        builder71.e(listR62);
        List listR63 = CollectionsKt.R(builder71.c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, GraphQLString.Companion.a()).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        r0 = listR63;
        CompiledField compiledFieldC101 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder72 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder72.b(ActionFieldsSelections.a());
        List listR64 = CollectionsKt.R(compiledFieldC101, builder72.a());
        s0 = listR64;
        CompiledField.Builder builder73 = new CompiledField.Builder("row", CompiledGraphQL.b(CoreRowUI.f11293a));
        builder73.e(listR63);
        CompiledField compiledFieldC102 = builder73.c();
        CompiledField.Builder builder74 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(Action.Companion.a()));
        builder74.e(listR64);
        List listR65 = CollectionsKt.R(compiledFieldC102, builder74.c());
        t0 = listR65;
        List listR66 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        u0 = listR66;
        List listR67 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        v0 = listR67;
        CompiledField compiledFieldC103 = new CompiledField.Builder("basicCoreRowListSectionTitle", GraphQLString.Companion.a()).c();
        ObjectType objectType13 = BasicCoreRow.f11045a;
        CompiledField.Builder builder75 = new CompiledField.Builder("basicCoreRowListItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(BasicCoreRow.Companion.a()))));
        builder75.e(listR65);
        CompiledField compiledFieldC104 = builder75.c();
        CompiledField.Builder builder76 = new CompiledField.Builder("basicCoreRowListAnalytics", Analytics.Companion.a());
        builder76.e(listR66);
        CompiledField compiledFieldC105 = builder76.c();
        CompiledField.Builder builder77 = new CompiledField.Builder("basicCoreRowListImpressionAnalytics", Analytics.Companion.a());
        builder77.e(listR67);
        List listR68 = CollectionsKt.R(compiledFieldC103, compiledFieldC104, compiledFieldC105, builder77.c());
        w0 = listR68;
        List listR69 = CollectionsKt.R(new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("thumbnail", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("duration", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("id", GraphQLString.Companion.a()).c());
        x0 = listR69;
        CompiledField compiledFieldC106 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder78 = new CompiledFragment.Builder("EditorialBanner", CollectionsKt.Q("EditorialBanner"));
        List list4 = EditorialBannerSelections.f;
        builder78.b(list4);
        List listR70 = CollectionsKt.R(compiledFieldC106, builder78.a());
        y0 = listR70;
        CompiledField compiledFieldC107 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder79 = new CompiledFragment.Builder("EditorialBanner", CollectionsKt.Q("EditorialBanner"));
        builder79.b(listR70);
        List listR71 = CollectionsKt.R(compiledFieldC107, builder79.a());
        z0 = listR71;
        UnionType unionType5 = EditorialCarouselItem.f11377a;
        CompiledField.Builder builder80 = new CompiledField.Builder("editorialCarouselItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(EditorialCarouselItem.Companion.a()))));
        builder80.e(listR71);
        List listQ8 = CollectionsKt.Q(builder80.c());
        A0 = listQ8;
        CompiledField compiledFieldC108 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder81 = new CompiledFragment.Builder("EditorialBanner", CollectionsKt.Q("EditorialBanner"));
        builder81.b(list4);
        List listR72 = CollectionsKt.R(compiledFieldC108, builder81.a());
        B0 = listR72;
        CompiledField compiledFieldC109 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder82 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder82.b(ActionFieldsSelections.a());
        List listR73 = CollectionsKt.R(compiledFieldC109, builder82.a());
        C0 = listR73;
        CompiledField compiledFieldC110 = new CompiledField.Builder("searchNavCardPlaceholderText", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder83 = new CompiledField.Builder("searchNavCardAction", CompiledGraphQL.b(Action.Companion.a()));
        builder83.e(listR73);
        List listR74 = CollectionsKt.R(compiledFieldC110, builder83.c());
        D0 = listR74;
        List listR75 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        E0 = listR75;
        List listR76 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        F0 = listR76;
        CompiledField compiledFieldC111 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder84 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder84.b(CoreIconFieldsSelections.a());
        List listR77 = CollectionsKt.R(compiledFieldC111, builder84.a());
        G0 = listR77;
        CompiledField compiledFieldC112 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder85 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder85.b(list3);
        List listR78 = CollectionsKt.R(compiledFieldC112, builder85.a());
        H0 = listR78;
        CompiledField compiledFieldC113 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder86 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder86.b(listR77);
        CompiledFragment compiledFragmentA12 = builder86.a();
        CompiledFragment.Builder builder87 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder87.b(listR78);
        List listR79 = CollectionsKt.R(compiledFieldC113, compiledFragmentA12, builder87.a());
        I0 = listR79;
        CompiledField compiledFieldC114 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC115 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CoreBroadcastBannerStyle.e.getClass();
        CompiledField compiledFieldC116 = new CompiledField.Builder("style", CompiledGraphQL.b(CoreBroadcastBannerStyle.Companion.a())).c();
        CompiledField.Builder builder88 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(IconAsset.Companion.a()));
        builder88.e(listR79);
        List listR80 = CollectionsKt.R(compiledFieldC114, compiledFieldC115, compiledFieldC116, builder88.c());
        J0 = listR80;
        CompiledField compiledFieldC117 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder89 = new CompiledFragment.Builder("Action", CollectionsKt.Q("Action"));
        builder89.b(ActionFieldsSelections.a());
        List listR81 = CollectionsKt.R(compiledFieldC117, builder89.a());
        K0 = listR81;
        CompiledField.Builder builder90 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder90.e(listR75);
        CompiledField compiledFieldC118 = builder90.c();
        CompiledField.Builder builder91 = new CompiledField.Builder("broadcastBannerDismissAnalytics", Analytics.Companion.a());
        builder91.e(listR76);
        CompiledField compiledFieldC119 = builder91.c();
        ObjectType objectType14 = CoreBroadcastBannerUI.f11286a;
        CompiledField.Builder builder92 = new CompiledField.Builder("broadcastBannerUI", CompiledGraphQL.b(CoreBroadcastBannerUI.Companion.a()));
        builder92.e(listR80);
        CompiledField compiledFieldC120 = builder92.c();
        CompiledField.Builder builder93 = new CompiledField.Builder("broadcastBannerAction", Action.Companion.a());
        builder93.e(listR81);
        List listR82 = CollectionsKt.R(compiledFieldC118, compiledFieldC119, compiledFieldC120, builder93.c(), new CompiledField.Builder("broadcastBannerActionLabel", GraphQLString.Companion.a()).c(), new CompiledField.Builder("broadcastBannerId", GraphQLString.Companion.a()).c(), new CompiledField.Builder("broadcastBannerDismissible", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        L0 = listR82;
        CompiledField compiledFieldC121 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder94 = new CompiledFragment.Builder("CoreButton", CollectionsKt.Q("CoreButton"));
        builder94.b(CoreButtonFieldsSelections.a());
        List listR83 = CollectionsKt.R(compiledFieldC121, builder94.a());
        M0 = listR83;
        CompiledField.Builder builder95 = new CompiledField.Builder("buttonSectionButton", CompiledGraphQL.b(CoreButton.f11287a));
        builder95.e(listR83);
        List listQ9 = CollectionsKt.Q(builder95.c());
        N0 = listQ9;
        List listR84 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        O0 = listR84;
        List listR85 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        P0 = listR85;
        CompiledField compiledFieldC122 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder96 = new CompiledFragment.Builder("RecipeSummaryCard", CollectionsKt.Q("RecipeSummaryCard"));
        builder96.b(list2);
        List listR86 = CollectionsKt.R(compiledFieldC122, builder96.a());
        Q0 = listR86;
        CompiledField compiledFieldC123 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder97 = new CompiledFragment.Builder("RecipeSummaryCard", CollectionsKt.Q("RecipeSummaryCard"));
        builder97.b(listR86);
        List listR87 = CollectionsKt.R(compiledFieldC123, builder97.a());
        R0 = listR87;
        CompiledField compiledFieldC124 = new CompiledField.Builder("gridListItemCount", GraphQLInt.Companion.a()).c();
        CompiledField.Builder builder98 = new CompiledField.Builder("gridListAnalytics", Analytics.Companion.a());
        builder98.e(listR84);
        CompiledField compiledFieldC125 = builder98.c();
        CompiledField.Builder builder99 = new CompiledField.Builder("gridListImpressionAnalytics", Analytics.Companion.a());
        builder99.e(listR85);
        CompiledField compiledFieldC126 = builder99.c();
        UnionType unionType6 = GridListItem.f11445a;
        CompiledField.Builder builder100 = new CompiledField.Builder("gridListItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GridListItem.Companion.a()))));
        builder100.e(listR87);
        List listR88 = CollectionsKt.R(compiledFieldC124, compiledFieldC125, compiledFieldC126, builder100.c());
        S0 = listR88;
        CompiledField compiledFieldC127 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder101 = new CompiledFragment.Builder("InfoTile", CollectionsKt.Q("InfoTile"));
        builder101.b(list);
        List listR89 = CollectionsKt.R(compiledFieldC127, builder101.a());
        T0 = listR89;
        List listR90 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        U0 = listR90;
        CompiledField compiledFieldC128 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC129 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ActionType.e.getClass();
        CompiledField compiledFieldC130 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField.Builder builder102 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder102.e(listR90);
        List listR91 = CollectionsKt.R(compiledFieldC128, compiledFieldC129, compiledFieldC130, builder102.c());
        V0 = listR91;
        CompiledField compiledFieldC131 = new CompiledField.Builder("chatEntryCardTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC132 = new CompiledField.Builder("chatEntryCardShowBeta", GraphQLBoolean.Companion.a()).c();
        CompiledField compiledFieldC133 = new CompiledField.Builder("chatEntryCardSuggestedPrompts", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        CompiledField.Builder builder103 = new CompiledField.Builder("chatEntryCardAction", CompiledGraphQL.b(Action.Companion.a()));
        builder103.e(listR91);
        List listR92 = CollectionsKt.R(compiledFieldC131, compiledFieldC132, compiledFieldC133, builder103.c());
        W0 = listR92;
        List listR93 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        X0 = listR93;
        List listR94 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        Y0 = listR94;
        CompiledField.Builder builder104 = new CompiledField.Builder("id", GraphQLID.Companion.a());
        builder104.a("catalogueCardId");
        CompiledField compiledFieldC134 = builder104.c();
        CompiledField compiledFieldC135 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder105 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a()));
        builder105.a("catalogueCardSubtitle");
        CompiledField compiledFieldC136 = builder105.c();
        CompiledField compiledFieldC137 = new CompiledField.Builder("imageLeft", GraphQLString.Companion.a()).c();
        CatalogueCardType.e.getClass();
        CompiledField compiledFieldC138 = new CompiledField.Builder("catalogueCardType", CatalogueCardType.Companion.a()).c();
        CompiledField.Builder builder106 = new CompiledField.Builder("clickAnalytics", Analytics.Companion.a());
        builder106.e(listR93);
        CompiledField compiledFieldC139 = builder106.c();
        CompiledField.Builder builder107 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder107.e(listR94);
        List listR95 = CollectionsKt.R(compiledFieldC134, compiledFieldC135, compiledFieldC136, compiledFieldC137, compiledFieldC138, compiledFieldC139, builder107.c());
        Z0 = listR95;
        List listR96 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        a1 = listR96;
        List listR97 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        b1 = listR97;
        CompiledField compiledFieldC140 = new CompiledField.Builder("image", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC141 = new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC142 = new CompiledField.Builder("cardHeight", CompiledGraphQL.b(CardHeight.Companion.a())).c();
        CompiledField compiledFieldC143 = new CompiledField.Builder("link", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC144 = new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c();
        CompiledField compiledFieldC145 = new CompiledField.Builder("analytics", TealiumAnalytics.Companion.a()).c();
        CompiledField.Builder builder108 = new CompiledField.Builder("actionableCardImpressionAnalytics", Analytics.Companion.a());
        builder108.e(listR96);
        CompiledField compiledFieldC146 = builder108.c();
        CompiledField.Builder builder109 = new CompiledField.Builder("actionableCardClickAnalytics", Analytics.Companion.a());
        builder109.e(listR97);
        List listR98 = CollectionsKt.R(compiledFieldC140, compiledFieldC141, compiledFieldC142, compiledFieldC143, compiledFieldC144, compiledFieldC145, compiledFieldC146, builder109.c());
        c1 = listR98;
        CompiledField compiledFieldC147 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder110 = new CompiledFragment.Builder("PageCover", CollectionsKt.Q("PageCover"));
        builder110.b(listR9);
        CompiledFragment compiledFragmentA13 = builder110.a();
        CompiledFragment.Builder builder111 = new CompiledFragment.Builder("UniversalInventoryContainer", CollectionsKt.Q("UniversalInventoryContainer"));
        builder111.b(listR15);
        CompiledFragment compiledFragmentA14 = builder111.a();
        CompiledFragment.Builder builder112 = new CompiledFragment.Builder("TitleSection", CollectionsKt.Q("TitleSection"));
        builder112.b(listR16);
        CompiledFragment compiledFragmentA15 = builder112.a();
        CompiledFragment.Builder builder113 = new CompiledFragment.Builder("DownloadableAsset", CollectionsKt.Q("DownloadableAsset"));
        builder113.b(listR17);
        CompiledFragment compiledFragmentA16 = builder113.a();
        CompiledFragment.Builder builder114 = new CompiledFragment.Builder("ParagraphTextItem", CollectionsKt.Q("ParagraphTextItem"));
        builder114.b(listR18);
        CompiledFragment compiledFragmentA17 = builder114.a();
        CompiledFragment.Builder builder115 = new CompiledFragment.Builder("VerticalList", CollectionsKt.Q("VerticalList"));
        builder115.b(listR25);
        CompiledFragment compiledFragmentA18 = builder115.a();
        CompiledFragment.Builder builder116 = new CompiledFragment.Builder("HorizontalList", CollectionsKt.Q("HorizontalList"));
        builder116.b(listR56);
        CompiledFragment compiledFragmentA19 = builder116.a();
        CompiledFragment.Builder builder117 = new CompiledFragment.Builder("RecipeMethod", CollectionsKt.Q("RecipeMethod"));
        builder117.b(listR58);
        CompiledFragment compiledFragmentA20 = builder117.a();
        CompiledFragment.Builder builder118 = new CompiledFragment.Builder("InsetBanner", CollectionsKt.Q("InsetBanner"));
        builder118.b(listR60);
        CompiledFragment compiledFragmentA21 = builder118.a();
        CompiledFragment.Builder builder119 = new CompiledFragment.Builder("BasicCoreRowList", CollectionsKt.Q("BasicCoreRowList"));
        builder119.b(listR68);
        CompiledFragment compiledFragmentA22 = builder119.a();
        CompiledFragment.Builder builder120 = new CompiledFragment.Builder("Video", CollectionsKt.Q("Video"));
        builder120.b(listR69);
        CompiledFragment compiledFragmentA23 = builder120.a();
        CompiledFragment.Builder builder121 = new CompiledFragment.Builder("EditorialCarousel", CollectionsKt.Q("EditorialCarousel"));
        builder121.b(listQ8);
        CompiledFragment compiledFragmentA24 = builder121.a();
        CompiledFragment.Builder builder122 = new CompiledFragment.Builder("EditorialBanner", CollectionsKt.Q("EditorialBanner"));
        builder122.b(listR72);
        CompiledFragment compiledFragmentA25 = builder122.a();
        CompiledFragment.Builder builder123 = new CompiledFragment.Builder("SearchNavCard", CollectionsKt.Q("SearchNavCard"));
        builder123.b(listR74);
        CompiledFragment compiledFragmentA26 = builder123.a();
        CompiledFragment.Builder builder124 = new CompiledFragment.Builder("BasicCoreBroadcastBanner", CollectionsKt.Q("BasicCoreBroadcastBanner"));
        builder124.b(listR82);
        CompiledFragment compiledFragmentA27 = builder124.a();
        CompiledFragment compiledFragmentI = d.i("isButtonSectionEnabled", false, new CompiledFragment.Builder("ButtonSection", CollectionsKt.Q("ButtonSection")), listQ9);
        CompiledFragment compiledFragmentI2 = d.i("isSavedRecipesContentPageMigrationEnabled", false, new CompiledFragment.Builder("GridList", CollectionsKt.Q("GridList")), listR88);
        CompiledFragment compiledFragmentI3 = d.i("isInfoTileEnabled", false, new CompiledFragment.Builder("InfoTile", CollectionsKt.Q("InfoTile")), listR89);
        CompiledFragment compiledFragmentI4 = d.i("includeChatEntryCard", false, new CompiledFragment.Builder("ChatEntryCardV3", CollectionsKt.Q("ChatEntryCardV3")), listR92);
        CompiledFragment.Builder builder125 = new CompiledFragment.Builder("CatalogueCard", CollectionsKt.Q("CatalogueCard"));
        builder125.b(listR95);
        CompiledFragment compiledFragmentA28 = builder125.a();
        CompiledFragment.Builder builder126 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder126.b(listR98);
        List listR99 = CollectionsKt.R(compiledFieldC147, compiledFragmentA13, compiledFragmentA14, compiledFragmentA15, compiledFragmentA16, compiledFragmentA17, compiledFragmentA18, compiledFragmentA19, compiledFragmentA20, compiledFragmentA21, compiledFragmentA22, compiledFragmentA23, compiledFragmentA24, compiledFragmentA25, compiledFragmentA26, compiledFragmentA27, compiledFragmentI, compiledFragmentI2, compiledFragmentI3, compiledFragmentI4, compiledFragmentA28, builder126.a());
        d1 = listR99;
        InterfaceType interfaceType = GenericPageHeader.f11428a;
        CompiledField.Builder builder127 = new CompiledField.Builder("header", GenericPageHeader.Companion.a());
        builder127.e(listR2);
        CompiledField compiledFieldC148 = builder127.c();
        CompiledField.Builder builder128 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder128.e(listR3);
        CompiledField compiledFieldC149 = builder128.c();
        CompiledField.Builder builder129 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder129.e(listR4);
        CompiledField compiledFieldC150 = builder129.c();
        CompiledField.Builder builder130 = new CompiledField.Builder("nextPageNumber", GraphQLInt.Companion.a());
        builder130.d(CollectionsKt.Q(new CompiledCondition("isSavedRecipesContentPageMigrationEnabled", false)));
        CompiledField compiledFieldC151 = builder130.c();
        CompiledField.Builder builder131 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(GenericPageFeedItem.f11427a)));
        builder131.e(listR99);
        e1 = CollectionsKt.R(compiledFieldC148, compiledFieldC149, compiledFieldC150, compiledFieldC151, builder131.c());
    }
}
