package com.woolworths.shop.modeselector.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.shop.graphql.type.Badge;
import au.com.woolworths.shop.graphql.type.BadgeType;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.DownloadableAsset;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLID;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.IconTextBanner;
import au.com.woolworths.shop.graphql.type.ModeSelectorV1AddressDetails;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.ShoppingModeDetails;
import au.com.woolworths.shop.graphql.type.ShoppingModeSelectorAddressInfo;
import au.com.woolworths.shop.graphql.type.ShoppingModeSelectorHeader;
import au.com.woolworths.shop.graphql.type.ShoppingModeSelectorHeaderButton;
import au.com.woolworths.shop.graphql.type.ShoppingModeSelectorOption;
import au.com.woolworths.shop.graphql.type.ShoppingModeSelectorOptionFulfilmentSection;
import au.com.woolworths.shop.graphql.type.ShoppingModeSelectorResponse;
import au.com.woolworths.shop.graphql.type.ShoppingModeSelectorSection;
import au.com.woolworths.shop.graphql.type.ShoppingModeSelectorStoreDetail;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.woolworths.shop.modeselector.fragment.selections.ButtonFragmentSelections;
import com.woolworths.shop.modeselector.fragment.selections.DownloadableAssetFragmentSelections;
import com.woolworths.shop.modeselector.fragment.selections.ItemFragmentSelections;
import com.woolworths.shop.modeselector.fragment.selections.ModeSelectorV1AddressDetailsDeliveryFragmentSelections;
import com.woolworths.shop.modeselector.fragment.selections.ModeSelectorV1AddressDetailsPickupFragmentSelections;
import com.woolworths.shop.modeselector.fragment.selections.ShoppingModeDetailsFragmentSelections;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.ErrorBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/modeselector/selections/ShoppingModeSelectorQuerySelections;", "", "mode-selector_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class ShoppingModeSelectorQuerySelections {
    public static final List A;
    public static final List B;
    public static final List C;
    public static final List D;

    /* renamed from: a, reason: collision with root package name */
    public static final List f23369a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        CompiledField compiledFieldC = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLID.f11441a)).c();
        CustomScalarType customScalarType = GraphQLBoolean.f11439a;
        CompiledField compiledFieldC2 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLString.f11443a;
        List listR = CollectionsKt.R(compiledFieldC, compiledFieldC2, new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType2)).c());
        f23369a = listR;
        CompiledField compiledFieldC3 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("DownloadableAsset", CollectionsKt.Q("DownloadableAsset"));
        List list = DownloadableAssetFragmentSelections.f23363a;
        builder.b(list);
        List listR2 = CollectionsKt.R(compiledFieldC3, builder.a());
        b = listR2;
        CompiledField.Builder builder2 = new CompiledField.Builder("buttons", a.f(ShoppingModeSelectorHeaderButton.f11906a));
        builder2.e = listR;
        CompiledField compiledFieldC4 = builder2.c();
        ObjectType objectType = DownloadableAsset.f11349a;
        CompiledField.Builder builder3 = new CompiledField.Builder("image", CompiledGraphQL.b(objectType));
        builder3.e = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC4, builder3.c());
        c = listR3;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("_", customScalarType).c());
        d = listQ;
        CompiledField compiledFieldC5 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("Button", CollectionsKt.Q("Button"));
        List list2 = ButtonFragmentSelections.b;
        builder4.b(list2);
        List listR4 = CollectionsKt.R(compiledFieldC5, builder4.a());
        e = listR4;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("DividerCard", CollectionsKt.Q("DividerCard"));
        builder5.d = listQ;
        CompiledFragment compiledFragmentA = builder5.a();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("Button", CollectionsKt.Q("Button"));
        builder6.d = listR4;
        List listR5 = CollectionsKt.R(compiledFieldC6, compiledFragmentA, builder6.a());
        f = listR5;
        CompiledField compiledFieldC7 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType2)).c();
        BadgeType.e.getClass();
        EnumType enumType = BadgeType.f;
        List listR6 = CollectionsKt.R(compiledFieldC7, new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c());
        g = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c());
        h = listR7;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("ShoppingModeSelectorOption", CollectionsKt.Q("ShoppingModeSelectorOption"));
        builder7.b(ItemFragmentSelections.f23364a);
        CompiledFragment compiledFragmentA2 = builder7.a();
        CompiledField.Builder builder8 = new CompiledField.Builder("fulfilment", CompiledGraphQL.a(CompiledGraphQL.b(ShoppingModeSelectorOptionFulfilmentSection.f11908a)));
        builder8.e = listR5;
        CompiledField compiledFieldC9 = builder8.c();
        ObjectType objectType2 = Badge.f11042a;
        CompiledField.Builder builder9 = new CompiledField.Builder("badge", objectType2);
        builder9.e = listR6;
        CompiledField compiledFieldC10 = builder9.c();
        CompiledField.Builder builder10 = new CompiledField.Builder("conditions", a.f(objectType2));
        builder10.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC8, compiledFragmentA2, compiledFieldC9, compiledFieldC10, builder10.c());
        i = listR8;
        CompiledField compiledFieldC11 = new CompiledField.Builder("title", customScalarType2).c();
        CompiledField.Builder builder11 = new CompiledField.Builder("items", a.f(ShoppingModeSelectorOption.f11907a));
        builder11.e = listR8;
        CompiledField compiledFieldC12 = builder11.c();
        CompiledField compiledFieldG = d.g("footnote", customScalarType2);
        CompiledField.Builder builder12 = new CompiledField.Builder("disclaimer", customScalarType2);
        builder12.c = a.s("includeServiceFees", false);
        List listR9 = CollectionsKt.R(compiledFieldC11, compiledFieldC12, compiledFieldG, builder12.c());
        j = listR9;
        CompiledField compiledFieldC13 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("DownloadableAsset", CollectionsKt.Q("DownloadableAsset"));
        builder13.d = list;
        List listR10 = CollectionsKt.R(compiledFieldC13, builder13.a());
        k = listR10;
        CompiledField compiledFieldC14 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("Button", CollectionsKt.Q("Button"));
        builder14.d = list2;
        List listR11 = CollectionsKt.R(compiledFieldC14, builder14.a());
        l = listR11;
        CompiledField.Builder builder15 = new CompiledField.Builder("image", objectType);
        builder15.e = listR10;
        CompiledField compiledFieldC15 = builder15.c();
        CompiledField compiledFieldG2 = d.g("title", customScalarType2);
        CompiledField compiledFieldG3 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType2);
        ObjectType objectType3 = Button.f11080a;
        CompiledField.Builder builder16 = new CompiledField.Builder("button", objectType3);
        builder16.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC15, compiledFieldG2, compiledFieldG3, builder16.c());
        m = listR12;
        CompiledField.Builder builder17 = new CompiledField.Builder("storeDetails", a.f(ShoppingModeSelectorStoreDetail.f11913a));
        builder17.e = listR12;
        List listQ2 = CollectionsKt.Q(builder17.c());
        n = listQ2;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType2)).c());
        o = listR13;
        CompiledField compiledFieldC16 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder18 = new CompiledField.Builder("features", a.f(IconTextBanner.f11479a));
        builder18.e = listR13;
        List listR14 = CollectionsKt.R(compiledFieldC16, builder18.c());
        p = listR14;
        CompiledField compiledFieldC17 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("ShoppingModeDetails", CollectionsKt.Q("ShoppingModeDetails"));
        builder19.b(ShoppingModeDetailsFragmentSelections.f23367a);
        List listR15 = CollectionsKt.R(compiledFieldC17, builder19.a());
        q = listR15;
        CompiledField compiledFieldC18 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder20 = new CompiledFragment.Builder("DownloadableAsset", CollectionsKt.Q("DownloadableAsset"));
        builder20.d = list;
        List listR16 = CollectionsKt.R(compiledFieldC18, builder20.a());
        r = listR16;
        CompiledField compiledFieldC19 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("Button", CollectionsKt.Q("Button"));
        builder21.d = list2;
        List listR17 = CollectionsKt.R(compiledFieldC19, builder21.a());
        s = listR17;
        CompiledField compiledFieldC20 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("ModeSelectorV1AddressDetailsDelivery", CollectionsKt.Q("ModeSelectorV1AddressDetailsDelivery"));
        builder22.b(ModeSelectorV1AddressDetailsDeliveryFragmentSelections.f23365a);
        List listR18 = CollectionsKt.R(compiledFieldC20, builder22.a());
        t = listR18;
        CompiledField compiledFieldC21 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("ModeSelectorV1AddressDetailsPickup", CollectionsKt.Q("ModeSelectorV1AddressDetailsPickup"));
        builder23.b(ModeSelectorV1AddressDetailsPickupFragmentSelections.f23366a);
        List listR19 = CollectionsKt.R(compiledFieldC21, builder23.a());
        u = listR19;
        CompiledField compiledFieldC22 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder24 = new CompiledFragment.Builder("ModeSelectorV1AddressDetailsDelivery", CollectionsKt.Q("ModeSelectorV1AddressDetailsDelivery"));
        builder24.d = listR18;
        CompiledFragment compiledFragmentA3 = builder24.a();
        CompiledFragment.Builder builder25 = new CompiledFragment.Builder("ModeSelectorV1AddressDetailsPickup", CollectionsKt.Q("ModeSelectorV1AddressDetailsPickup"));
        builder25.d = listR19;
        List listR20 = CollectionsKt.R(compiledFieldC22, compiledFragmentA3, builder25.a());
        v = listR20;
        CompiledField compiledFieldC23 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("Button", CollectionsKt.Q("Button"));
        builder26.d = list2;
        List listR21 = CollectionsKt.R(compiledFieldC23, builder26.a());
        w = listR21;
        CompiledField.Builder builder27 = new CompiledField.Builder("shoppingModeDetails", CompiledGraphQL.b(ShoppingModeDetails.f11899a));
        builder27.e = listR15;
        CompiledField compiledFieldC24 = builder27.c();
        CompiledField.Builder builder28 = new CompiledField.Builder("image", objectType);
        builder28.e = listR16;
        CompiledField compiledFieldC25 = builder28.c();
        CompiledField compiledFieldG4 = d.g("title", customScalarType2);
        CompiledField compiledFieldG5 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType2);
        CompiledField.Builder builder29 = new CompiledField.Builder("button", CompiledGraphQL.b(objectType3));
        builder29.e = listR17;
        CompiledField compiledFieldC26 = builder29.c();
        CompiledField.Builder builder30 = new CompiledField.Builder("v1AddressDetails", ModeSelectorV1AddressDetails.f11574a);
        builder30.e = listR20;
        CompiledField compiledFieldC27 = builder30.c();
        CompiledField.Builder builder31 = new CompiledField.Builder("secondaryButton", objectType3);
        builder31.c = a.s("includeInstoreUplift", false);
        builder31.e = listR21;
        List listR22 = CollectionsKt.R(compiledFieldC24, compiledFieldC25, compiledFieldG4, compiledFieldG5, compiledFieldC26, compiledFieldC27, builder31.c());
        x = listR22;
        CompiledField compiledFieldC28 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder32 = new CompiledField.Builder(ErrorBundle.DETAIL_ENTRY, CompiledGraphQL.b(ShoppingModeSelectorAddressInfo.f11902a));
        builder32.e = listR22;
        List listR23 = CollectionsKt.R(compiledFieldC28, builder32.c());
        y = listR23;
        CompiledField compiledFieldC29 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder33 = new CompiledFragment.Builder("ShoppingModeSelectorOptionsSection", CollectionsKt.Q("ShoppingModeSelectorOptionsSection"));
        builder33.c = a.s("includeInstoreUplift", true);
        builder33.d = listR9;
        CompiledFragment compiledFragmentA4 = builder33.a();
        CompiledFragment.Builder builder34 = new CompiledFragment.Builder("ShoppingModeSelectorStoreDetailsSection", CollectionsKt.Q("ShoppingModeSelectorStoreDetailsSection"));
        builder34.c = a.s("includeInstoreUplift", false);
        builder34.d = listQ2;
        CompiledFragment compiledFragmentA5 = builder34.a();
        CompiledFragment.Builder builder35 = new CompiledFragment.Builder("ShoppingModeSelectorStoreFeaturesSection", CollectionsKt.Q("ShoppingModeSelectorStoreFeaturesSection"));
        builder35.c = a.s("includeInstoreUplift", false);
        builder35.d = listR14;
        CompiledFragment compiledFragmentA6 = builder35.a();
        CompiledFragment.Builder builder36 = new CompiledFragment.Builder("ShoppingModeSelectorAddressInfoSection", CollectionsKt.Q("ShoppingModeSelectorAddressInfoSection"));
        builder36.d = listR23;
        List listR24 = CollectionsKt.R(compiledFieldC29, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, builder36.a());
        z = listR24;
        CompiledField.Builder builder37 = new CompiledField.Builder("header", CompiledGraphQL.b(ShoppingModeSelectorHeader.f11905a));
        builder37.e = listR3;
        CompiledField compiledFieldC30 = builder37.c();
        CompiledField.Builder builder38 = new CompiledField.Builder("sections", d.j(ShoppingModeSelectorSection.f11912a));
        builder38.e = listR24;
        List listR25 = CollectionsKt.R(compiledFieldC30, builder38.c());
        A = listR25;
        List listR26 = CollectionsKt.R(new CompiledField.Builder("deepLinkUrl", customScalarType2).c(), new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType2)).c());
        B = listR26;
        CompiledField compiledFieldC31 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType2)).c();
        CompiledFragment.Builder builder39 = new CompiledFragment.Builder("ShoppingModeSelector", CollectionsKt.Q("ShoppingModeSelector"));
        builder39.d = listR25;
        CompiledFragment compiledFragmentA7 = builder39.a();
        CompiledFragment.Builder builder40 = new CompiledFragment.Builder("ShoppingModeSelectorErrorResponse", CollectionsKt.Q("ShoppingModeSelectorErrorResponse"));
        builder40.d = listR26;
        List listR27 = CollectionsKt.R(compiledFieldC31, compiledFragmentA7, builder40.a());
        C = listR27;
        CompiledField.Builder builder41 = new CompiledField.Builder("shoppingModeSelector", CompiledGraphQL.b(ShoppingModeSelectorResponse.f11911a));
        new CompiledArgument.Builder(Query.E);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.D);
        builder41.d = CollectionsKt.R(compiledArgument, new CompiledArgument());
        builder41.e = listR27;
        D = CollectionsKt.Q(builder41.c());
    }
}
