package au.com.woolworths.shop.legacy.graphql.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.graphql.common.fragment.selections.ProductCardSelections;
import au.com.woolworths.shop.graphql.type.ContentCta;
import au.com.woolworths.shop.graphql.type.FilterMenuItem;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.InfoSection;
import au.com.woolworths.shop.graphql.type.InfoSectionFooter;
import au.com.woolworths.shop.graphql.type.InfoSectionItem;
import au.com.woolworths.shop.graphql.type.InsetBanner;
import au.com.woolworths.shop.graphql.type.InsetBannerAction;
import au.com.woolworths.shop.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.shop.graphql.type.InsetBannerActionType;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.MarketplaceEducationBottomSheet;
import au.com.woolworths.shop.graphql.type.ProductCard;
import au.com.woolworths.shop.graphql.type.ProductFilter;
import au.com.woolworths.shop.graphql.type.ProductList;
import au.com.woolworths.shop.graphql.type.ProductSortOption;
import au.com.woolworths.shop.graphql.type.Query;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.woolworths.product.list.legacy.fragment.selections.InsetBannerSelections;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/shop/legacy/graphql/selections/ProductsByFacetQuerySelections;", "", "product-list-legacy_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes4.dex */
public final class ProductsByFacetQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f12210a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder.b(ProductCardSelections.A);
        List listR = CollectionsKt.R(compiledFieldC, builder.a());
        f12210a = listR;
        CompiledField compiledFieldC2 = new CompiledField.Builder("key", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC3 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g("parentKey", customScalarType);
        CustomScalarType customScalarType2 = GraphQLBoolean.f11439a;
        List listR2 = CollectionsKt.R(compiledFieldC2, compiledFieldC3, compiledFieldC4, compiledFieldG, new CompiledField.Builder("hasChildren", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("isApplied", CompiledGraphQL.b(customScalarType2)).c());
        b = listR2;
        InsetBannerActionPlacement.e.getClass();
        CompiledField compiledFieldC5 = new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.f)).c();
        InsetBannerActionType.e.getClass();
        List listR3 = CollectionsKt.R(compiledFieldC5, new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.f)).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        c = listR3;
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC6 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.f)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC8 = new CompiledField.Builder("title", customScalarType).c();
        CompiledField compiledFieldG2 = d.g("iconUrl", customScalarType);
        CompiledField.Builder builder2 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.f11510a);
        builder2.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC6, compiledFieldC7, compiledFieldC8, compiledFieldG2, builder2.c());
        d = listR4;
        CompiledField compiledFieldC9 = new CompiledField.Builder("headerKey", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC10 = new CompiledField.Builder("headerTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder3 = new CompiledField.Builder("filterItems", a.f(FilterMenuItem.f11386a));
        builder3.e = listR2;
        CompiledField compiledFieldC11 = builder3.c();
        ObjectType objectType = InsetBanner.f11509a;
        CompiledField.Builder builder4 = new CompiledField.Builder("banner", objectType);
        builder4.e = listR4;
        List listR5 = CollectionsKt.R(compiledFieldC9, compiledFieldC10, compiledFieldC11, builder4.c());
        e = listR5;
        List listR6 = CollectionsKt.R(new CompiledField.Builder("key", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType), new CompiledField.Builder("isApplied", CompiledGraphQL.b(customScalarType2)).c());
        f = listR6;
        CompiledField compiledFieldC12 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("InsetBanner", CollectionsKt.Q("InsetBanner"));
        builder5.b(InsetBannerSelections.INSTANCE.get__root());
        List listR7 = CollectionsKt.R(compiledFieldC12, builder5.a());
        g = listR7;
        List listR8 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c());
        h = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("linkUrl", CompiledGraphQL.b(customScalarType)).c());
        i = listR9;
        CompiledField compiledFieldC13 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder6 = new CompiledField.Builder("items", a.f(InfoSectionItem.f11497a));
        builder6.e = listR8;
        CompiledField compiledFieldC14 = builder6.c();
        CompiledField.Builder builder7 = new CompiledField.Builder("footer", InfoSectionFooter.f11496a);
        builder7.e = listR9;
        List listR10 = CollectionsKt.R(compiledFieldC13, compiledFieldC14, builder7.c());
        j = listR10;
        List listQ = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c());
        k = listQ;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c());
        l = listQ2;
        CompiledField compiledFieldC15 = new CompiledField.Builder("bottomSheetTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("bottomSheetBody", CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType2 = ContentCta.f11282a;
        CompiledField.Builder builder8 = new CompiledField.Builder("primaryCta", objectType2);
        builder8.e = listQ;
        CompiledField compiledFieldC17 = builder8.c();
        CompiledField.Builder builder9 = new CompiledField.Builder("secondaryCta", objectType2);
        builder9.e = listQ2;
        List listR11 = CollectionsKt.R(compiledFieldC15, compiledFieldC16, compiledFieldC17, builder9.c(), d.g("showOnceOnly", customScalarType2));
        m = listR11;
        CustomScalarType customScalarType3 = GraphQLInt.f11442a;
        CompiledField compiledFieldC18 = new CompiledField.Builder("totalNumberOfProducts", customScalarType3).c();
        CompiledField compiledFieldG3 = d.g("nextPage", customScalarType3);
        CompiledField.Builder builder10 = new CompiledField.Builder("products", a.f(ProductCard.f11717a));
        builder10.e = listR;
        CompiledField compiledFieldC19 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("filters", a.f(ProductFilter.f11739a));
        builder11.e = listR5;
        CompiledField compiledFieldC20 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("sortOptions", a.f(ProductSortOption.f11786a));
        builder12.e = listR6;
        CompiledField compiledFieldC21 = builder12.c();
        CompiledField.Builder builder13 = new CompiledField.Builder("sortOptionsBanner", objectType);
        builder13.c = a.s("includeUnitPriceInsetBanner", false);
        builder13.e = listR7;
        CompiledField compiledFieldC22 = builder13.c();
        CompiledField.Builder builder14 = new CompiledField.Builder("marketplaceInfo", InfoSection.f11495a);
        builder14.e = listR10;
        CompiledField compiledFieldC23 = builder14.c();
        CompiledField.Builder builder15 = new CompiledField.Builder("marketplaceBottomSheet", MarketplaceEducationBottomSheet.f11556a);
        builder15.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC18, compiledFieldG3, compiledFieldC19, compiledFieldC20, compiledFieldC21, compiledFieldC22, compiledFieldC23, builder15.c());
        n = listR12;
        CompiledField.Builder builder16 = new CompiledField.Builder("productsByFacet", ProductList.f11749a);
        new CompiledArgument.Builder(Query.G0);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.H0);
        CompiledArgument compiledArgument2 = new CompiledArgument();
        new CompiledArgument.Builder(Query.N0);
        CompiledArgument compiledArgument3 = new CompiledArgument();
        new CompiledArgument.Builder(Query.I0);
        CompiledArgument compiledArgument4 = new CompiledArgument();
        new CompiledArgument.Builder(Query.J0);
        CompiledArgument compiledArgument5 = new CompiledArgument();
        new CompiledArgument.Builder(Query.L0);
        CompiledArgument compiledArgument6 = new CompiledArgument();
        new CompiledArgument.Builder(Query.K0);
        CompiledArgument compiledArgument7 = new CompiledArgument();
        new CompiledArgument.Builder(Query.M0);
        CompiledArgument compiledArgument8 = new CompiledArgument();
        new CompiledArgument.Builder(Query.O0);
        builder16.d = CollectionsKt.R(compiledArgument, compiledArgument2, compiledArgument3, compiledArgument4, compiledArgument5, compiledArgument6, compiledArgument7, compiledArgument8, new CompiledArgument());
        builder16.e = listR12;
        o = CollectionsKt.Q(builder16.c());
    }
}
