package au.com.woolworths.shop.legacy.graphql.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.graphql.common.fragment.selections.ProductCardSelections;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.DietaryInfo;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.IngredientAnalytics;
import au.com.woolworths.shop.graphql.type.InsetBanner;
import au.com.woolworths.shop.graphql.type.InsetBannerAction;
import au.com.woolworths.shop.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.shop.graphql.type.InsetBannerActionType;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.ListSectionHeaderTypes;
import au.com.woolworths.shop.graphql.type.ProductCard;
import au.com.woolworths.shop.graphql.type.ProductList;
import au.com.woolworths.shop.graphql.type.ProductListFeed;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.lists.data.remote.AlternativeProductsQuery;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.salesforce.marketingcloud.UrlHandler;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/shop/legacy/graphql/selections/ProductsByRecipeQuerySelections;", "", "product-list-legacy_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes4.dex */
public final class ProductsByRecipeQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f12212a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        CompiledField compiledFieldC = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        ButtonStyle.e.getClass();
        List listR = CollectionsKt.R(compiledFieldC, new CompiledField.Builder("style", ButtonStyle.f).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.f11439a)).c(), d.g(UrlHandler.ACTION, customScalarType), d.g("url", customScalarType), d.g("iconUrl", customScalarType));
        f12212a = listR;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        List list = ProductCardSelections.A;
        builder.b(list);
        List listR2 = CollectionsKt.R(compiledFieldC2, builder.a());
        b = listR2;
        List listQ = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c());
        c = listQ;
        CompiledField compiledFieldC3 = new CompiledField.Builder("ingredientDetails", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder2 = new CompiledField.Builder("swapButton", Button.f11080a);
        builder2.e = listR;
        CompiledField compiledFieldC4 = builder2.c();
        CompiledField.Builder builder3 = new CompiledField.Builder(AlternativeProductsQuery.OPERATION_NAME, a.f(ProductCard.f11717a));
        builder3.e = listR2;
        CompiledField compiledFieldC5 = builder3.c();
        CompiledField.Builder builder4 = new CompiledField.Builder("analytics", CompiledGraphQL.b(IngredientAnalytics.f11504a));
        builder4.e = listQ;
        List listR3 = CollectionsKt.R(compiledFieldC3, compiledFieldC4, compiledFieldC5, builder4.c());
        d = listR3;
        ListSectionHeaderTypes.e.getClass();
        List listR4 = CollectionsKt.R(new CompiledField.Builder("listSectionHeaderType", CompiledGraphQL.b(ListSectionHeaderTypes.f)).c(), new CompiledField.Builder("listSectionHeaderText", CompiledGraphQL.b(customScalarType)).c());
        e = listR4;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder5.d = list;
        List listR5 = CollectionsKt.R(compiledFieldC6, builder5.a());
        f = listR5;
        InsetBannerActionPlacement.e.getClass();
        CompiledField compiledFieldC7 = new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.f)).c();
        InsetBannerActionType.e.getClass();
        List listR6 = CollectionsKt.R(compiledFieldC7, new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.f)).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        g = listR6;
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC8 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.f)).c();
        CompiledField compiledFieldC9 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g("title", customScalarType);
        CompiledField.Builder builder6 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.f11510a);
        builder6.e = listR6;
        List listR7 = CollectionsKt.R(compiledFieldC8, compiledFieldC9, compiledFieldG, builder6.c());
        h = listR7;
        List listR8 = CollectionsKt.R(d.g("title", customScalarType), d.g("content", customScalarType));
        i = listR8;
        CompiledField.Builder builder7 = new CompiledField.Builder("insetBanner", CompiledGraphQL.b(InsetBanner.f11509a));
        builder7.e = listR7;
        CompiledField compiledFieldC10 = builder7.c();
        CompiledField.Builder builder8 = new CompiledField.Builder("dietaryInfo", DietaryInfo.f11346a);
        builder8.e = listR8;
        List listR9 = CollectionsKt.R(compiledFieldC10, builder8.c());
        j = listR9;
        CompiledField compiledFieldC11 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("IngredientCard", CollectionsKt.Q("IngredientCard"));
        builder9.d = listR3;
        CompiledFragment compiledFragmentA = builder9.a();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("ListSectionHeader", CollectionsKt.Q("ListSectionHeader"));
        builder10.d = listR4;
        CompiledFragment compiledFragmentA2 = builder10.a();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder11.d = listR5;
        CompiledFragment compiledFragmentA3 = builder11.a();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("DietaryDisclaimer", CollectionsKt.Q("DietaryDisclaimer"));
        builder12.c = a.s("showNutritionInfo", false);
        builder12.d = listR9;
        List listR10 = CollectionsKt.R(compiledFieldC11, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, builder12.a());
        k = listR10;
        CustomScalarType customScalarType2 = GraphQLInt.f11442a;
        CompiledField compiledFieldC12 = new CompiledField.Builder("totalNumberOfProducts", customScalarType2).c();
        CompiledField compiledFieldG2 = d.g("nextPage", customScalarType2);
        CompiledField.Builder builder13 = new CompiledField.Builder("productsFeed", d.j(ProductListFeed.f11751a));
        builder13.e = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC12, compiledFieldG2, builder13.c());
        l = listR11;
        CompiledField.Builder builder14 = new CompiledField.Builder("productsByRecipe", ProductList.f11749a);
        new CompiledArgument.Builder(Query.x0);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.z0);
        CompiledArgument compiledArgument2 = new CompiledArgument();
        new CompiledArgument.Builder(Query.y0);
        builder14.d = CollectionsKt.R(compiledArgument, compiledArgument2, new CompiledArgument());
        builder14.e = listR11;
        m = CollectionsKt.Q(builder14.c());
    }
}
