package me.oriient.internal.services.dataModel.engine;

import java.util.List;
import kotlin.Deprecated;
import kotlin.Metadata;
import kotlin.jvm.internal.Intrinsics;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.UnknownFieldException;
import kotlinx.serialization.builtins.BuiltinSerializersKt;
import kotlinx.serialization.descriptors.SerialDescriptor;
import kotlinx.serialization.encoding.CompositeDecoder;
import kotlinx.serialization.encoding.CompositeEncoder;
import kotlinx.serialization.encoding.Decoder;
import kotlinx.serialization.encoding.Encoder;
import kotlinx.serialization.internal.BooleanSerializer;
import kotlinx.serialization.internal.DoubleSerializer;
import kotlinx.serialization.internal.GeneratedSerializer;
import kotlinx.serialization.internal.IntSerializer;
import kotlinx.serialization.internal.LongSerializer;
import kotlinx.serialization.internal.PluginGeneratedSerialDescriptor;
import kotlinx.serialization.internal.PluginHelperInterfacesKt;
import kotlinx.serialization.internal.SerializationConstructorMarker;
import me.oriient.internal.services.dataModel.engine.SpecificEngineConfig;
import org.jetbrains.annotations.NotNull;

@Metadata(d1 = {"\u00006\n\u0000\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0010\u0011\n\u0002\u0018\u0002\n\u0002\b\u0003\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0002\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\bÇ\u0002\u0018\u00002\b\u0012\u0004\u0012\u00020\u00020\u0001B\u0007\b\u0002¢\u0006\u0002\u0010\u0003J\u0018\u0010\b\u001a\f\u0012\b\u0012\u0006\u0012\u0002\b\u00030\n0\tHÖ\u0001¢\u0006\u0002\u0010\u000bJ\u0011\u0010\f\u001a\u00020\u00022\u0006\u0010\r\u001a\u00020\u000eHÖ\u0001J\u0019\u0010\u000f\u001a\u00020\u00102\u0006\u0010\u0011\u001a\u00020\u00122\u0006\u0010\u0013\u001a\u00020\u0002HÖ\u0001R\u0014\u0010\u0004\u001a\u00020\u00058VXÖ\u0005¢\u0006\u0006\u001a\u0004\b\u0006\u0010\u0007¨\u0006\u0014"}, d2 = {"me/oriient/internal/services/dataModel/engine/OnDeviceEngineConfigResponse.$serializer", "Lkotlinx/serialization/internal/GeneratedSerializer;", "Lme/oriient/internal/services/dataModel/engine/OnDeviceEngineConfigResponse;", "()V", "descriptor", "Lkotlinx/serialization/descriptors/SerialDescriptor;", "getDescriptor", "()Lkotlinx/serialization/descriptors/SerialDescriptor;", "childSerializers", "", "Lkotlinx/serialization/KSerializer;", "()[Lkotlinx/serialization/KSerializer;", "deserialize", "decoder", "Lkotlinx/serialization/encoding/Decoder;", "serialize", "", "encoder", "Lkotlinx/serialization/encoding/Encoder;", "value", "internal_publishRelease"}, k = 1, mv = {1, 9, 0}, xi = 48)
@Deprecated
/* loaded from: classes7.dex */
public final class OnDeviceEngineConfigResponse$$serializer implements GeneratedSerializer<OnDeviceEngineConfigResponse> {

    @NotNull
    public static final OnDeviceEngineConfigResponse$$serializer INSTANCE;
    private static final /* synthetic */ PluginGeneratedSerialDescriptor descriptor;

    static {
        OnDeviceEngineConfigResponse$$serializer onDeviceEngineConfigResponse$$serializer = new OnDeviceEngineConfigResponse$$serializer();
        INSTANCE = onDeviceEngineConfigResponse$$serializer;
        PluginGeneratedSerialDescriptor pluginGeneratedSerialDescriptor = new PluginGeneratedSerialDescriptor("me.oriient.internal.services.dataModel.engine.OnDeviceEngineConfigResponse", onDeviceEngineConfigResponse$$serializer, 45);
        pluginGeneratedSerialDescriptor.k("enableEnginePerformanceMonitor", true);
        pluginGeneratedSerialDescriptor.k("calibrationExpirationTimeMinutes", true);
        pluginGeneratedSerialDescriptor.k("sessionProgressLogsIntervalSeconds", true);
        pluginGeneratedSerialDescriptor.k("engineUpdatesBufferSize", true);
        pluginGeneratedSerialDescriptor.k("enableValidationUploading", true);
        pluginGeneratedSerialDescriptor.k("enableRestrictedAreasValidationUploading", true);
        pluginGeneratedSerialDescriptor.k("enablePositionsUploading", true);
        pluginGeneratedSerialDescriptor.k("enableSensorsDataUploading", true);
        pluginGeneratedSerialDescriptor.k("aggressiveMode", true);
        pluginGeneratedSerialDescriptor.k("enableEventsUploading", true);
        pluginGeneratedSerialDescriptor.k("uploadWriteToFileRecords", true);
        pluginGeneratedSerialDescriptor.k("uploadingMetadataUpdateIntervalSec", true);
        pluginGeneratedSerialDescriptor.k("uploadWriteToFileIntervalSec", true);
        pluginGeneratedSerialDescriptor.k("uploadChunkLengthSeconds", true);
        pluginGeneratedSerialDescriptor.k("uploadMaxSessionLengthMin", true);
        pluginGeneratedSerialDescriptor.k("enableUploadingRecovery", true);
        pluginGeneratedSerialDescriptor.k("useDiscretionaryUploading", true);
        pluginGeneratedSerialDescriptor.k("uploadRetryIntervalMinutes", true);
        pluginGeneratedSerialDescriptor.k("timeoutIntervalSecForUploadRequest", true);
        pluginGeneratedSerialDescriptor.k("metadataSessionTimeoutIntervalForResourceSeconds", true);
        pluginGeneratedSerialDescriptor.k("metadataSessiontimeoutIntervalForRequestSeconds", true);
        pluginGeneratedSerialDescriptor.k("taskRetryDelaySeconds", true);
        pluginGeneratedSerialDescriptor.k("taskRetryMaxDelaySeconds", true);
        pluginGeneratedSerialDescriptor.k("celluralAccessAllowanceDelayDays", true);
        pluginGeneratedSerialDescriptor.k("isCellularAccessAllowed", true);
        pluginGeneratedSerialDescriptor.k("isDelayedCellularAccessAllowed", true);
        pluginGeneratedSerialDescriptor.k("isConstrainedNetworkAccessAllowed", true);
        pluginGeneratedSerialDescriptor.k("uploadUrlTimeoutHoursInterval", true);
        pluginGeneratedSerialDescriptor.k("uploadingExpirationTimeDays", true);
        pluginGeneratedSerialDescriptor.k("minimumStorageLeftToUploadPositionsMb", true);
        pluginGeneratedSerialDescriptor.k("minimumStorageLeftToUploadSensorsMb", true);
        pluginGeneratedSerialDescriptor.k("minimumStorageLeftToUploadValidationsMb", true);
        pluginGeneratedSerialDescriptor.k("minimumStorageLeftToUploadEventsMb", true);
        pluginGeneratedSerialDescriptor.k("uploadTaskMaxDelayMin", true);
        pluginGeneratedSerialDescriptor.k("controlTaskMaxTimeMin", true);
        pluginGeneratedSerialDescriptor.k("controlTaskIntervalMin", true);
        pluginGeneratedSerialDescriptor.k("chargerTaskIntervalMin", true);
        pluginGeneratedSerialDescriptor.k("uploadingWifiRequired", true);
        pluginGeneratedSerialDescriptor.k("uploadingChargerRequired", true);
        pluginGeneratedSerialDescriptor.k("librariesValidationStrategy", true);
        pluginGeneratedSerialDescriptor.k("startReportingRetryCount", true);
        pluginGeneratedSerialDescriptor.k("startReportingRetryInterval", true);
        pluginGeneratedSerialDescriptor.k("dataLoadingRetryRequestCount", true);
        pluginGeneratedSerialDescriptor.k("onDeviceCore", true);
        pluginGeneratedSerialDescriptor.k("onDeviceCorePerBuilding", true);
        descriptor = pluginGeneratedSerialDescriptor;
    }

    private OnDeviceEngineConfigResponse$$serializer() {
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    @NotNull
    public KSerializer<?>[] childSerializers() {
        KSerializer[] kSerializerArr = OnDeviceEngineConfigResponse.$childSerializers;
        BooleanSerializer booleanSerializer = BooleanSerializer.f24779a;
        KSerializer<?> kSerializerD = BuiltinSerializersKt.d(booleanSerializer);
        DoubleSerializer doubleSerializer = DoubleSerializer.f24792a;
        KSerializer<?> kSerializerD2 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD3 = BuiltinSerializersKt.d(doubleSerializer);
        IntSerializer intSerializer = IntSerializer.f24800a;
        KSerializer<?> kSerializerD4 = BuiltinSerializersKt.d(intSerializer);
        KSerializer<?> kSerializerD5 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD6 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD7 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD8 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD9 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD10 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD11 = BuiltinSerializersKt.d(intSerializer);
        KSerializer<?> kSerializerD12 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD13 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD14 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD15 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD16 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD17 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD18 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD19 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD20 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD21 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD22 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD23 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD24 = BuiltinSerializersKt.d(intSerializer);
        KSerializer<?> kSerializerD25 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD26 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD27 = BuiltinSerializersKt.d(booleanSerializer);
        KSerializer<?> kSerializerD28 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD29 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD30 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD31 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD32 = BuiltinSerializersKt.d(doubleSerializer);
        KSerializer<?> kSerializerD33 = BuiltinSerializersKt.d(doubleSerializer);
        LongSerializer longSerializer = LongSerializer.f24804a;
        return new KSerializer[]{kSerializerD, kSerializerD2, kSerializerD3, kSerializerD4, kSerializerD5, kSerializerD6, kSerializerD7, kSerializerD8, kSerializerD9, kSerializerD10, kSerializerD11, kSerializerD12, kSerializerD13, kSerializerD14, kSerializerD15, kSerializerD16, kSerializerD17, kSerializerD18, kSerializerD19, kSerializerD20, kSerializerD21, kSerializerD22, kSerializerD23, kSerializerD24, kSerializerD25, kSerializerD26, kSerializerD27, kSerializerD28, kSerializerD29, kSerializerD30, kSerializerD31, kSerializerD32, kSerializerD33, BuiltinSerializersKt.d(longSerializer), BuiltinSerializersKt.d(longSerializer), BuiltinSerializersKt.d(longSerializer), BuiltinSerializersKt.d(longSerializer), BuiltinSerializersKt.d(booleanSerializer), BuiltinSerializersKt.d(booleanSerializer), BuiltinSerializersKt.d(kSerializerArr[39]), BuiltinSerializersKt.d(intSerializer), BuiltinSerializersKt.d(doubleSerializer), BuiltinSerializersKt.d(intSerializer), BuiltinSerializersKt.d(OnDeviceEngineCoreConfigResponse$$serializer.INSTANCE), BuiltinSerializersKt.d(kSerializerArr[44])};
    }

    @Override // kotlinx.serialization.SerializationStrategy, kotlinx.serialization.DeserializationStrategy
    @NotNull
    /* renamed from: getDescriptor */
    public SerialDescriptor getB() {
        return descriptor;
    }

    @Override // kotlinx.serialization.internal.GeneratedSerializer
    @NotNull
    public KSerializer<?>[] typeParametersSerializers() {
        return PluginHelperInterfacesKt.f24815a;
    }

    @Override // kotlinx.serialization.DeserializationStrategy
    @NotNull
    public OnDeviceEngineConfigResponse deserialize(@NotNull Decoder decoder) {
        List list;
        Boolean bool;
        Boolean bool2;
        Boolean bool3;
        Boolean bool4;
        Boolean bool5;
        Boolean bool6;
        Double d;
        Boolean bool7;
        Double d2;
        SpecificEngineConfig.EngineLibrariesValidationStrategy engineLibrariesValidationStrategy;
        Double d3;
        Boolean bool8;
        Double d4;
        Double d5;
        Boolean bool9;
        OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse;
        Boolean bool10;
        Boolean bool11;
        Double d6;
        Boolean bool12;
        SpecificEngineConfig.EngineLibrariesValidationStrategy engineLibrariesValidationStrategy2;
        Double d7;
        Boolean bool13;
        Double d8;
        Double d9;
        Double d10;
        int i;
        Boolean bool14;
        OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse2;
        int i2;
        Boolean bool15;
        Intrinsics.h(decoder, "decoder");
        SerialDescriptor b = getB();
        CompositeDecoder compositeDecoderB = decoder.b(b);
        KSerializer[] kSerializerArr = OnDeviceEngineConfigResponse.$childSerializers;
        Long l = null;
        SpecificEngineConfig.EngineLibrariesValidationStrategy engineLibrariesValidationStrategy3 = null;
        List list2 = null;
        OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse3 = null;
        Long l2 = null;
        Boolean bool16 = null;
        Boolean bool17 = null;
        Integer num = null;
        Double d11 = null;
        Integer num2 = null;
        Double d12 = null;
        Double d13 = null;
        Long l3 = null;
        Long l4 = null;
        Boolean bool18 = null;
        Integer num3 = null;
        Boolean bool19 = null;
        Boolean bool20 = null;
        Boolean bool21 = null;
        Boolean bool22 = null;
        Boolean bool23 = null;
        Boolean bool24 = null;
        Integer num4 = null;
        Double d14 = null;
        Double d15 = null;
        Double d16 = null;
        Double d17 = null;
        Boolean bool25 = null;
        Boolean bool26 = null;
        Double d18 = null;
        Double d19 = null;
        Double d20 = null;
        Double d21 = null;
        Double d22 = null;
        Double d23 = null;
        Integer num5 = null;
        Boolean bool27 = null;
        Boolean bool28 = null;
        Boolean bool29 = null;
        Double d24 = null;
        Double d25 = null;
        Double d26 = null;
        Double d27 = null;
        Double d28 = null;
        Double d29 = null;
        int i3 = 0;
        int i4 = 0;
        boolean z = true;
        while (z) {
            Double d30 = d12;
            int iU = compositeDecoderB.u(b);
            int i5 = 64;
            Double d31 = d13;
            switch (iU) {
                case -1:
                    list = list2;
                    d13 = d31;
                    z = false;
                    Boolean bool30 = bool20;
                    bool = bool19;
                    bool2 = bool30;
                    Boolean bool31 = bool24;
                    bool3 = bool23;
                    bool4 = bool31;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    d3 = d11;
                    bool8 = bool18;
                    d4 = d28;
                    d5 = d29;
                    Double d32 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d32;
                    Boolean bool32 = bool;
                    bool20 = bool2;
                    bool19 = bool32;
                    Boolean bool33 = bool3;
                    bool24 = bool4;
                    bool23 = bool33;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 0:
                    Boolean bool34 = bool20;
                    bool9 = bool19;
                    list = list2;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    bool10 = bool21;
                    bool11 = bool26;
                    d6 = d18;
                    bool12 = bool27;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    d7 = d11;
                    bool24 = bool24;
                    bool23 = bool23;
                    d29 = d29;
                    bool13 = bool34;
                    d8 = d14;
                    d9 = d16;
                    d10 = d30;
                    i = 1;
                    bool18 = (Boolean) compositeDecoderB.k(b, 0, BooleanSerializer.f24779a, bool18);
                    bool14 = bool25;
                    bool27 = bool12;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 1:
                    Boolean bool35 = bool20;
                    bool9 = bool19;
                    list = list2;
                    bool10 = bool21;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    bool12 = bool27;
                    d7 = d11;
                    d28 = (Double) compositeDecoderB.k(b, 1, DoubleSerializer.f24792a, d28);
                    bool24 = bool24;
                    bool23 = bool23;
                    bool13 = bool35;
                    d8 = d14;
                    d9 = d16;
                    bool14 = bool25;
                    d10 = d30;
                    i = 2;
                    bool27 = bool12;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 2:
                    Boolean bool36 = bool20;
                    bool9 = bool19;
                    list = list2;
                    bool10 = bool21;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse4 = onDeviceEngineCoreConfigResponse3;
                    d29 = (Double) compositeDecoderB.k(b, 2, DoubleSerializer.f24792a, d29);
                    bool24 = bool24;
                    bool23 = bool23;
                    bool13 = bool36;
                    d9 = d16;
                    bool14 = bool25;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse4;
                    d10 = d30;
                    i = 4;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 3:
                    list = list2;
                    bool10 = bool21;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse5 = onDeviceEngineCoreConfigResponse3;
                    Boolean bool37 = bool19;
                    Boolean bool38 = bool20;
                    bool9 = bool37;
                    bool24 = bool24;
                    bool23 = bool23;
                    num3 = (Integer) compositeDecoderB.k(b, 3, IntSerializer.f24800a, num3);
                    bool13 = bool38;
                    d9 = d16;
                    bool14 = bool25;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse5;
                    d10 = d30;
                    i = 8;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 4:
                    list = list2;
                    Boolean bool39 = bool20;
                    bool10 = bool21;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    i = 16;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse6 = onDeviceEngineCoreConfigResponse3;
                    bool24 = bool24;
                    bool23 = bool23;
                    bool9 = (Boolean) compositeDecoderB.k(b, 4, BooleanSerializer.f24779a, bool19);
                    bool13 = bool39;
                    d9 = d16;
                    bool14 = bool25;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse6;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 5:
                    list = list2;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse7 = onDeviceEngineCoreConfigResponse3;
                    bool10 = bool21;
                    bool24 = bool24;
                    bool23 = bool23;
                    bool13 = (Boolean) compositeDecoderB.k(b, 5, BooleanSerializer.f24779a, bool20);
                    bool9 = bool19;
                    d9 = d16;
                    bool14 = bool25;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse7;
                    d10 = d30;
                    i = 32;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 6:
                    list = list2;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse8 = onDeviceEngineCoreConfigResponse3;
                    Boolean bool40 = (Boolean) compositeDecoderB.k(b, 6, BooleanSerializer.f24779a, bool21);
                    bool24 = bool24;
                    bool23 = bool23;
                    bool13 = bool20;
                    d9 = d16;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse8;
                    i = 64;
                    bool10 = bool40;
                    bool9 = bool19;
                    bool14 = bool25;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 7:
                    list = list2;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse9 = onDeviceEngineCoreConfigResponse3;
                    bool24 = bool24;
                    bool23 = bool23;
                    bool22 = (Boolean) compositeDecoderB.k(b, 7, BooleanSerializer.f24779a, bool22);
                    bool10 = bool21;
                    d9 = d16;
                    bool14 = bool25;
                    i = 128;
                    bool13 = bool20;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse9;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 8:
                    list = list2;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse10 = onDeviceEngineCoreConfigResponse3;
                    bool10 = bool21;
                    bool24 = bool24;
                    d9 = d16;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse10;
                    i = 256;
                    bool23 = (Boolean) compositeDecoderB.k(b, 8, BooleanSerializer.f24779a, bool23);
                    bool13 = bool20;
                    bool14 = bool25;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 9:
                    list = list2;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse11 = onDeviceEngineCoreConfigResponse3;
                    bool24 = (Boolean) compositeDecoderB.k(b, 9, BooleanSerializer.f24779a, bool24);
                    bool10 = bool21;
                    d9 = d16;
                    bool14 = bool25;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse11;
                    i = 512;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 10:
                    list = list2;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse12 = onDeviceEngineCoreConfigResponse3;
                    num4 = (Integer) compositeDecoderB.k(b, 10, IntSerializer.f24800a, num4);
                    bool10 = bool21;
                    d9 = d16;
                    bool14 = bool25;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse12;
                    i = 1024;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 11:
                    list = list2;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse13 = onDeviceEngineCoreConfigResponse3;
                    bool10 = bool21;
                    d9 = d16;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse13;
                    i = 2048;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = (Double) compositeDecoderB.k(b, 11, DoubleSerializer.f24792a, d14);
                    bool14 = bool25;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 12:
                    list = list2;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    OnDeviceEngineCoreConfigResponse onDeviceEngineCoreConfigResponse14 = onDeviceEngineCoreConfigResponse3;
                    d15 = (Double) compositeDecoderB.k(b, 12, DoubleSerializer.f24792a, d15);
                    bool10 = bool21;
                    d9 = d16;
                    bool14 = bool25;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse14;
                    i = 4096;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 13:
                    list = list2;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    onDeviceEngineCoreConfigResponse2 = onDeviceEngineCoreConfigResponse3;
                    d9 = (Double) compositeDecoderB.k(b, 13, DoubleSerializer.f24792a, d16);
                    i2 = 8192;
                    bool14 = bool25;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse2;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 14:
                    list = list2;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    onDeviceEngineCoreConfigResponse2 = onDeviceEngineCoreConfigResponse3;
                    i2 = 16384;
                    d17 = (Double) compositeDecoderB.k(b, 14, DoubleSerializer.f24792a, d17);
                    d9 = d16;
                    bool14 = bool25;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse2;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 15:
                    list = list2;
                    bool11 = bool26;
                    d6 = d18;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    onDeviceEngineCoreConfigResponse2 = onDeviceEngineCoreConfigResponse3;
                    bool14 = (Boolean) compositeDecoderB.k(b, 15, BooleanSerializer.f24779a, bool25);
                    i2 = 32768;
                    d9 = d16;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse2;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 16:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    Boolean bool41 = bool26;
                    d6 = d18;
                    bool15 = (Boolean) compositeDecoderB.k(b, 16, BooleanSerializer.f24779a, bool41);
                    i2 = 65536;
                    bool11 = bool15;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 17:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 131072;
                    bool15 = bool26;
                    d6 = (Double) compositeDecoderB.k(b, 17, DoubleSerializer.f24792a, d18);
                    bool11 = bool15;
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 18:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 262144;
                    d19 = (Double) compositeDecoderB.k(b, 18, DoubleSerializer.f24792a, d19);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 19:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 524288;
                    d20 = (Double) compositeDecoderB.k(b, 19, DoubleSerializer.f24792a, d20);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 20:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 1048576;
                    d21 = (Double) compositeDecoderB.k(b, 20, DoubleSerializer.f24792a, d21);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 21:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 2097152;
                    d22 = (Double) compositeDecoderB.k(b, 21, DoubleSerializer.f24792a, d22);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 22:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 4194304;
                    d23 = (Double) compositeDecoderB.k(b, 22, DoubleSerializer.f24792a, d23);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 23:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 8388608;
                    num5 = (Integer) compositeDecoderB.k(b, 23, IntSerializer.f24800a, num5);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 24:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 16777216;
                    bool27 = (Boolean) compositeDecoderB.k(b, 24, BooleanSerializer.f24779a, bool27);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 25:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 33554432;
                    bool28 = (Boolean) compositeDecoderB.k(b, 25, BooleanSerializer.f24779a, bool28);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 26:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 67108864;
                    bool29 = (Boolean) compositeDecoderB.k(b, 26, BooleanSerializer.f24779a, bool29);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 27:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 134217728;
                    d24 = (Double) compositeDecoderB.k(b, 27, DoubleSerializer.f24792a, d24);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 28:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 268435456;
                    d25 = (Double) compositeDecoderB.k(b, 28, DoubleSerializer.f24792a, d25);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 29:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 536870912;
                    d26 = (Double) compositeDecoderB.k(b, 29, DoubleSerializer.f24792a, d26);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 30:
                    list = list2;
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    i2 = 1073741824;
                    d27 = (Double) compositeDecoderB.k(b, 30, DoubleSerializer.f24792a, d27);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d9 = d16;
                    bool14 = bool25;
                    bool11 = bool26;
                    d6 = d18;
                    i = i2;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d30;
                    d7 = d11;
                    d8 = d14;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 31:
                    d13 = d31;
                    engineLibrariesValidationStrategy2 = engineLibrariesValidationStrategy3;
                    list = list2;
                    Double d33 = (Double) compositeDecoderB.k(b, 31, DoubleSerializer.f24792a, d30);
                    onDeviceEngineCoreConfigResponse = onDeviceEngineCoreConfigResponse3;
                    d7 = d11;
                    d8 = d14;
                    d9 = d16;
                    bool14 = bool25;
                    i = Integer.MIN_VALUE;
                    bool10 = bool21;
                    bool13 = bool20;
                    bool9 = bool19;
                    d10 = d33;
                    bool11 = bool26;
                    d6 = d18;
                    i3 |= i;
                    bool25 = bool14;
                    d16 = d9;
                    d14 = d8;
                    d18 = d6;
                    onDeviceEngineCoreConfigResponse3 = onDeviceEngineCoreConfigResponse;
                    bool26 = bool11;
                    d12 = d10;
                    bool19 = bool9;
                    bool20 = bool13;
                    d11 = d7;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy2;
                    bool21 = bool10;
                    list2 = list;
                case 32:
                    d13 = (Double) compositeDecoderB.k(b, 32, DoubleSerializer.f24792a, d31);
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy3;
                    i5 = 1;
                    i4 |= i5;
                    list = list2;
                    Boolean bool42 = bool20;
                    bool = bool19;
                    bool2 = bool42;
                    Boolean bool43 = bool24;
                    bool3 = bool23;
                    bool4 = bool43;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d322 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d322;
                    Boolean bool322 = bool;
                    bool20 = bool2;
                    bool19 = bool322;
                    Boolean bool332 = bool3;
                    bool24 = bool4;
                    bool23 = bool332;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 33:
                    l3 = (Long) compositeDecoderB.k(b, 33, LongSerializer.f24804a, l3);
                    d13 = d31;
                    i5 = 2;
                    i4 |= i5;
                    list = list2;
                    Boolean bool422 = bool20;
                    bool = bool19;
                    bool2 = bool422;
                    Boolean bool432 = bool24;
                    bool3 = bool23;
                    bool4 = bool432;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d3222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d3222;
                    Boolean bool3222 = bool;
                    bool20 = bool2;
                    bool19 = bool3222;
                    Boolean bool3322 = bool3;
                    bool24 = bool4;
                    bool23 = bool3322;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 34:
                    l4 = (Long) compositeDecoderB.k(b, 34, LongSerializer.f24804a, l4);
                    d13 = d31;
                    i5 = 4;
                    i4 |= i5;
                    list = list2;
                    Boolean bool4222 = bool20;
                    bool = bool19;
                    bool2 = bool4222;
                    Boolean bool4322 = bool24;
                    bool3 = bool23;
                    bool4 = bool4322;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d32222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d32222;
                    Boolean bool32222 = bool;
                    bool20 = bool2;
                    bool19 = bool32222;
                    Boolean bool33222 = bool3;
                    bool24 = bool4;
                    bool23 = bool33222;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 35:
                    l = (Long) compositeDecoderB.k(b, 35, LongSerializer.f24804a, l);
                    d13 = d31;
                    i5 = 8;
                    i4 |= i5;
                    list = list2;
                    Boolean bool42222 = bool20;
                    bool = bool19;
                    bool2 = bool42222;
                    Boolean bool43222 = bool24;
                    bool3 = bool23;
                    bool4 = bool43222;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d322222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d322222;
                    Boolean bool322222 = bool;
                    bool20 = bool2;
                    bool19 = bool322222;
                    Boolean bool332222 = bool3;
                    bool24 = bool4;
                    bool23 = bool332222;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 36:
                    l2 = (Long) compositeDecoderB.k(b, 36, LongSerializer.f24804a, l2);
                    d13 = d31;
                    i5 = 16;
                    i4 |= i5;
                    list = list2;
                    Boolean bool422222 = bool20;
                    bool = bool19;
                    bool2 = bool422222;
                    Boolean bool432222 = bool24;
                    bool3 = bool23;
                    bool4 = bool432222;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d3222222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d3222222;
                    Boolean bool3222222 = bool;
                    bool20 = bool2;
                    bool19 = bool3222222;
                    Boolean bool3322222 = bool3;
                    bool24 = bool4;
                    bool23 = bool3322222;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 37:
                    bool16 = (Boolean) compositeDecoderB.k(b, 37, BooleanSerializer.f24779a, bool16);
                    d13 = d31;
                    i5 = 32;
                    i4 |= i5;
                    list = list2;
                    Boolean bool4222222 = bool20;
                    bool = bool19;
                    bool2 = bool4222222;
                    Boolean bool4322222 = bool24;
                    bool3 = bool23;
                    bool4 = bool4322222;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d32222222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d32222222;
                    Boolean bool32222222 = bool;
                    bool20 = bool2;
                    bool19 = bool32222222;
                    Boolean bool33222222 = bool3;
                    bool24 = bool4;
                    bool23 = bool33222222;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 38:
                    bool17 = (Boolean) compositeDecoderB.k(b, 38, BooleanSerializer.f24779a, bool17);
                    d13 = d31;
                    i4 |= i5;
                    list = list2;
                    Boolean bool42222222 = bool20;
                    bool = bool19;
                    bool2 = bool42222222;
                    Boolean bool43222222 = bool24;
                    bool3 = bool23;
                    bool4 = bool43222222;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d322222222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d322222222;
                    Boolean bool322222222 = bool;
                    bool20 = bool2;
                    bool19 = bool322222222;
                    Boolean bool332222222 = bool3;
                    bool24 = bool4;
                    bool23 = bool332222222;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 39:
                    engineLibrariesValidationStrategy3 = (SpecificEngineConfig.EngineLibrariesValidationStrategy) compositeDecoderB.k(b, 39, kSerializerArr[39], engineLibrariesValidationStrategy3);
                    i5 = 128;
                    d13 = d31;
                    i4 |= i5;
                    list = list2;
                    Boolean bool422222222 = bool20;
                    bool = bool19;
                    bool2 = bool422222222;
                    Boolean bool432222222 = bool24;
                    bool3 = bool23;
                    bool4 = bool432222222;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d3222222222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d3222222222;
                    Boolean bool3222222222 = bool;
                    bool20 = bool2;
                    bool19 = bool3222222222;
                    Boolean bool3322222222 = bool3;
                    bool24 = bool4;
                    bool23 = bool3322222222;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 40:
                    num = (Integer) compositeDecoderB.k(b, 40, IntSerializer.f24800a, num);
                    i5 = 256;
                    d13 = d31;
                    i4 |= i5;
                    list = list2;
                    Boolean bool4222222222 = bool20;
                    bool = bool19;
                    bool2 = bool4222222222;
                    Boolean bool4322222222 = bool24;
                    bool3 = bool23;
                    bool4 = bool4322222222;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d32222222222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d32222222222;
                    Boolean bool32222222222 = bool;
                    bool20 = bool2;
                    bool19 = bool32222222222;
                    Boolean bool33222222222 = bool3;
                    bool24 = bool4;
                    bool23 = bool33222222222;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 41:
                    d11 = (Double) compositeDecoderB.k(b, 41, DoubleSerializer.f24792a, d11);
                    i5 = 512;
                    d13 = d31;
                    i4 |= i5;
                    list = list2;
                    Boolean bool42222222222 = bool20;
                    bool = bool19;
                    bool2 = bool42222222222;
                    Boolean bool43222222222 = bool24;
                    bool3 = bool23;
                    bool4 = bool43222222222;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d322222222222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d322222222222;
                    Boolean bool322222222222 = bool;
                    bool20 = bool2;
                    bool19 = bool322222222222;
                    Boolean bool332222222222 = bool3;
                    bool24 = bool4;
                    bool23 = bool332222222222;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 42:
                    num2 = (Integer) compositeDecoderB.k(b, 42, IntSerializer.f24800a, num2);
                    i5 = 1024;
                    d13 = d31;
                    i4 |= i5;
                    list = list2;
                    Boolean bool422222222222 = bool20;
                    bool = bool19;
                    bool2 = bool422222222222;
                    Boolean bool432222222222 = bool24;
                    bool3 = bool23;
                    bool4 = bool432222222222;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d3222222222222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d3222222222222;
                    Boolean bool3222222222222 = bool;
                    bool20 = bool2;
                    bool19 = bool3222222222222;
                    Boolean bool3322222222222 = bool3;
                    bool24 = bool4;
                    bool23 = bool3322222222222;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 43:
                    onDeviceEngineCoreConfigResponse3 = (OnDeviceEngineCoreConfigResponse) compositeDecoderB.k(b, 43, OnDeviceEngineCoreConfigResponse$$serializer.INSTANCE, onDeviceEngineCoreConfigResponse3);
                    i5 = 2048;
                    d13 = d31;
                    i4 |= i5;
                    list = list2;
                    Boolean bool4222222222222 = bool20;
                    bool = bool19;
                    bool2 = bool4222222222222;
                    Boolean bool4322222222222 = bool24;
                    bool3 = bool23;
                    bool4 = bool4322222222222;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d32222222222222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d32222222222222;
                    Boolean bool32222222222222 = bool;
                    bool20 = bool2;
                    bool19 = bool32222222222222;
                    Boolean bool33222222222222 = bool3;
                    bool24 = bool4;
                    bool23 = bool33222222222222;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                case 44:
                    list2 = (List) compositeDecoderB.k(b, 44, kSerializerArr[44], list2);
                    i5 = 4096;
                    d13 = d31;
                    i4 |= i5;
                    list = list2;
                    Boolean bool42222222222222 = bool20;
                    bool = bool19;
                    bool2 = bool42222222222222;
                    Boolean bool43222222222222 = bool24;
                    bool3 = bool23;
                    bool4 = bool43222222222222;
                    engineLibrariesValidationStrategy = engineLibrariesValidationStrategy3;
                    bool8 = bool18;
                    bool5 = bool21;
                    bool6 = bool26;
                    d = d18;
                    bool7 = bool27;
                    d2 = d30;
                    d5 = d29;
                    d3 = d11;
                    d4 = d28;
                    Double d322222222222222 = d;
                    bool26 = bool6;
                    d12 = d2;
                    bool27 = bool7;
                    d18 = d322222222222222;
                    Boolean bool322222222222222 = bool;
                    bool20 = bool2;
                    bool19 = bool322222222222222;
                    Boolean bool332222222222222 = bool3;
                    bool24 = bool4;
                    bool23 = bool332222222222222;
                    d28 = d4;
                    d29 = d5;
                    bool18 = bool8;
                    d11 = d3;
                    bool21 = bool5;
                    engineLibrariesValidationStrategy3 = engineLibrariesValidationStrategy;
                    list2 = list;
                default:
                    throw new UnknownFieldException(iU);
            }
        }
        Boolean bool44 = bool27;
        Double d34 = d12;
        Boolean bool45 = bool20;
        Boolean bool46 = bool19;
        Boolean bool47 = bool24;
        Boolean bool48 = bool23;
        List list3 = list2;
        Double d35 = d11;
        Boolean bool49 = bool18;
        Boolean bool50 = bool21;
        Double d36 = d28;
        Double d37 = d29;
        compositeDecoderB.c(b);
        Integer num6 = num5;
        Double d38 = d27;
        Boolean bool51 = bool16;
        return new OnDeviceEngineConfigResponse(i3, i4, bool49, d36, d37, num3, bool46, bool45, bool50, bool22, bool48, bool47, num4, d14, d15, d16, d17, bool25, bool26, d18, d19, d20, d21, d22, d23, num6, bool44, bool28, bool29, d24, d25, d26, d38, d34, d13, l3, l4, l, l2, bool51, bool17, engineLibrariesValidationStrategy3, num, d35, num2, onDeviceEngineCoreConfigResponse3, list3, (SerializationConstructorMarker) null);
    }

    @Override // kotlinx.serialization.SerializationStrategy
    public void serialize(@NotNull Encoder encoder, @NotNull OnDeviceEngineConfigResponse value) {
        Intrinsics.h(encoder, "encoder");
        Intrinsics.h(value, "value");
        SerialDescriptor b = getB();
        CompositeEncoder compositeEncoderB = encoder.b(b);
        OnDeviceEngineConfigResponse.write$Self$internal_publishRelease(value, compositeEncoderB, b);
        compositeEncoderB.c(b);
    }
}
