package au.com.woolworths.shop.receipts.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.ReceiptDetails;
import au.com.woolworths.shop.graphql.type.ReceiptDetailsBarcode;
import au.com.woolworths.shop.graphql.type.ReceiptDetailsCouponSection;
import au.com.woolworths.shop.graphql.type.ReceiptDetailsItem;
import au.com.woolworths.shop.graphql.type.ReceiptDetailsLineItem;
import au.com.woolworths.shop.graphql.type.ReceiptDetailsPayment;
import au.com.woolworths.shop.graphql.type.ReceiptDetailsPaymentInfo;
import au.com.woolworths.shop.graphql.type.ReceiptDownload;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.ErrorBundle;
import org.bouncycastle.i18n.TextBundle;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/shop/receipts/selections/EReceiptDetailsQuerySelections;", "", "receipts_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes4.dex */
public final class EReceiptDetailsQuerySelections {
    public static final List A;

    /* renamed from: a, reason: collision with root package name */
    public static final List f12877a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        List listR = CollectionsKt.R(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("filename", CompiledGraphQL.b(customScalarType)).c());
        f12877a = listR;
        List listR2 = CollectionsKt.R(d.g("iconUrl", customScalarType), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c(), d.g("division", customScalarType), d.g("storeNo", customScalarType));
        b = listR2;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("total", CompiledGraphQL.b(customScalarType)).c());
        c = listQ;
        List listR3 = CollectionsKt.R(new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c(), d.g("amount", customScalarType));
        d = listR3;
        List listR4 = CollectionsKt.R(d.g("prefixChar", customScalarType), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c(), d.g("amount", customScalarType));
        e = listR4;
        ObjectType objectType = ReceiptDetailsLineItem.f11842a;
        CompiledField.Builder builder = new CompiledField.Builder("header", CompiledGraphQL.b(objectType));
        builder.e = listR3;
        CompiledField compiledFieldC = builder.c();
        CompiledField.Builder builder2 = new CompiledField.Builder("items", a.f(objectType));
        builder2.e = listR4;
        List listR5 = CollectionsKt.R(compiledFieldC, builder2.c());
        f = listR5;
        List listR6 = CollectionsKt.R(d.g("prefixChar", customScalarType), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c(), d.g("amount", customScalarType));
        g = listR6;
        List listR7 = CollectionsKt.R(d.g("prefixChar", customScalarType), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c(), d.g("amount", customScalarType));
        h = listR7;
        List listR8 = CollectionsKt.R(d.g("prefixChar", customScalarType), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c(), d.g("amount", customScalarType));
        i = listR8;
        List listR9 = CollectionsKt.R(d.g("prefixChar", customScalarType), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c(), d.g("amount", customScalarType));
        j = listR9;
        CompiledField.Builder builder3 = new CompiledField.Builder("discounts", a.f(objectType));
        builder3.e = listR6;
        CompiledField compiledFieldC2 = builder3.c();
        CompiledField.Builder builder4 = new CompiledField.Builder("summaryItems", a.f(objectType));
        builder4.e = listR7;
        CompiledField compiledFieldC3 = builder4.c();
        CompiledField.Builder builder5 = new CompiledField.Builder("gst", objectType);
        builder5.e = listR8;
        CompiledField compiledFieldC4 = builder5.c();
        CompiledField.Builder builder6 = new CompiledField.Builder("receiptTotal", CompiledGraphQL.b(objectType));
        builder6.e = listR9;
        List listR10 = CollectionsKt.R(compiledFieldC2, compiledFieldC3, compiledFieldC4, builder6.c());
        k = listR10;
        List listR11 = CollectionsKt.R(d.g("prefixChar", customScalarType), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c(), d.g("amount", customScalarType));
        l = listR11;
        List listR12 = CollectionsKt.R(d.g("prefixChar", customScalarType), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c(), d.g("amount", customScalarType));
        m = listR12;
        CompiledField.Builder builder7 = new CompiledField.Builder("header", CompiledGraphQL.b(objectType));
        builder7.e = listR11;
        CompiledField compiledFieldC5 = builder7.c();
        CompiledField.Builder builder8 = new CompiledField.Builder("info", a.f(objectType));
        builder8.e = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC5, builder8.c());
        n = listR13;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c());
        o = listQ2;
        CompiledField compiledFieldC6 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("amount", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g("iconUrl", customScalarType);
        CompiledField.Builder builder9 = new CompiledField.Builder(ErrorBundle.DETAIL_ENTRY, a.f(ReceiptDetailsPaymentInfo.f11844a));
        builder9.e = listQ2;
        List listR14 = CollectionsKt.R(compiledFieldC6, compiledFieldC7, compiledFieldG, builder9.c());
        p = listR14;
        CompiledField.Builder builder10 = new CompiledField.Builder("payments", a.f(ReceiptDetailsPayment.f11843a));
        builder10.e = listR14;
        List listQ3 = CollectionsKt.Q(builder10.c());
        q = listQ3;
        List listR15 = CollectionsKt.R(d.g("prefixChar", customScalarType), d.g("amount", customScalarType), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c());
        r = listR15;
        CompiledField compiledFieldC8 = new CompiledField.Builder("savings", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder11 = new CompiledField.Builder("summaryItems", a.f(objectType));
        builder11.e = listR15;
        List listR16 = CollectionsKt.R(compiledFieldC8, builder11.c());
        s = listR16;
        List listR17 = CollectionsKt.R(d.g("sectionTitle", customScalarType), new CompiledField.Builder(ErrorBundle.DETAIL_ENTRY, a.e(customScalarType)).c());
        t = listR17;
        List listR18 = CollectionsKt.R(new CompiledField.Builder("value", CompiledGraphQL.b(customScalarType)).c(), d.g("type", customScalarType));
        u = listR18;
        CompiledField compiledFieldG2 = d.g("headerImageUrl", customScalarType);
        CompiledField compiledFieldG3 = d.g("footer", customScalarType);
        CompiledField.Builder builder12 = new CompiledField.Builder("sections", a.f(ReceiptDetailsCouponSection.f11836a));
        builder12.e = listR17;
        CompiledField compiledFieldC9 = builder12.c();
        ObjectType objectType2 = ReceiptDetailsBarcode.f11834a;
        CompiledField.Builder builder13 = new CompiledField.Builder("barcode", objectType2);
        builder13.e = listR18;
        List listR19 = CollectionsKt.R(compiledFieldG2, compiledFieldG3, compiledFieldC9, builder13.c());
        v = listR19;
        List listR20 = CollectionsKt.R(new CompiledField.Builder("value", CompiledGraphQL.b(customScalarType)).c(), d.g("type", customScalarType));
        w = listR20;
        CompiledField.Builder builder14 = new CompiledField.Builder("barcode", objectType2);
        builder14.e = listR20;
        List listR21 = CollectionsKt.R(builder14.c(), new CompiledField.Builder("transactionDetails", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("abnAndStore", CompiledGraphQL.b(customScalarType)).c());
        x = listR21;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("ReceiptDetailsHeader", CollectionsKt.Q("ReceiptDetailsHeader"));
        builder15.d = listR2;
        CompiledFragment compiledFragmentA = builder15.a();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("ReceiptDetailsTotal", CollectionsKt.Q("ReceiptDetailsTotal"));
        builder16.d = listQ;
        CompiledFragment compiledFragmentA2 = builder16.a();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("ReceiptDetailsItems", CollectionsKt.Q("ReceiptDetailsItems"));
        builder17.d = listR5;
        CompiledFragment compiledFragmentA3 = builder17.a();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("ReceiptDetailsSummary", CollectionsKt.Q("ReceiptDetailsSummary"));
        builder18.d = listR10;
        CompiledFragment compiledFragmentA4 = builder18.a();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("ReceiptDetailsInfo", CollectionsKt.Q("ReceiptDetailsInfo"));
        builder19.d = listR13;
        CompiledFragment compiledFragmentA5 = builder19.a();
        CompiledFragment.Builder builder20 = new CompiledFragment.Builder("ReceiptDetailsPayments", CollectionsKt.Q("ReceiptDetailsPayments"));
        builder20.d = listQ3;
        CompiledFragment compiledFragmentA6 = builder20.a();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("ReceiptDetailsSavings", CollectionsKt.Q("ReceiptDetailsSavings"));
        builder21.d = listR16;
        CompiledFragment compiledFragmentA7 = builder21.a();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("ReceiptDetailsCoupon", CollectionsKt.Q("ReceiptDetailsCoupon"));
        builder22.d = listR19;
        CompiledFragment compiledFragmentA8 = builder22.a();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("ReceiptDetailsFooter", CollectionsKt.Q("ReceiptDetailsFooter"));
        builder23.d = listR21;
        List listR22 = CollectionsKt.R(compiledFieldC10, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, compiledFragmentA8, builder23.a());
        y = listR22;
        CompiledField.Builder builder24 = new CompiledField.Builder("download", ReceiptDownload.f11849a);
        builder24.e = listR;
        CompiledField compiledFieldC11 = builder24.c();
        CompiledField.Builder builder25 = new CompiledField.Builder(ErrorBundle.DETAIL_ENTRY, d.j(ReceiptDetailsItem.f11840a));
        builder25.e = listR22;
        List listR23 = CollectionsKt.R(compiledFieldC11, builder25.c());
        z = listR23;
        CompiledField.Builder builder26 = new CompiledField.Builder("receiptDetails", ReceiptDetails.f11833a);
        new CompiledArgument.Builder(Query.h1);
        builder26.d = au.com.woolworths.android.onesite.a.v();
        builder26.e = listR23;
        A = CollectionsKt.Q(builder26.c());
    }
}
