package com.woolworths.rewards.offers.fragment.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.rewards.graphql.type.CircularProgressIndicator;
import au.com.woolworths.rewards.graphql.type.CircularProgressRing;
import au.com.woolworths.rewards.graphql.type.ContentCta;
import au.com.woolworths.rewards.graphql.type.GraphQLBoolean;
import au.com.woolworths.rewards.graphql.type.GraphQLFloat;
import au.com.woolworths.rewards.graphql.type.GraphQLInt;
import au.com.woolworths.rewards.graphql.type.GraphQLString;
import au.com.woolworths.rewards.graphql.type.HostedIcon;
import au.com.woolworths.rewards.graphql.type.InsetBanner;
import au.com.woolworths.rewards.graphql.type.InsetBannerAction;
import au.com.woolworths.rewards.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.rewards.graphql.type.InsetBannerActionType;
import au.com.woolworths.rewards.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.rewards.graphql.type.OfferCta;
import au.com.woolworths.rewards.graphql.type.RewardsOfferActivationMessage;
import au.com.woolworths.rewards.graphql.type.RewardsOfferAnalytics;
import au.com.woolworths.rewards.graphql.type.RewardsOfferMechanicItem;
import au.com.woolworths.rewards.graphql.type.RewardsOfferMechanics;
import au.com.woolworths.rewards.graphql.type.RewardsOfferProgressIndicator;
import au.com.woolworths.rewards.graphql.type.RewardsOfferStatus;
import au.com.woolworths.rewards.graphql.type.RewardsStatusIcon;
import au.com.woolworths.rewards.graphql.type.StandardBanner;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.ObjectType;
import com.google.android.gms.common.Scopes;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import com.woolworths.rewards.offers.fragment.fragment.selections.StandardBannerFieldsSelections;
import com.woolworths.scanlibrary.util.widget.CircularProgressDrawable;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.ErrorBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/rewards/offers/fragment/selections/RewardsOfferFieldsSelections;", "", "offers_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class RewardsOfferFieldsSelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f21043a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;

    static {
        CustomScalarType customScalarType = GraphQLString.f9617a;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("StandardBanner", CollectionsKt.Q("StandardBanner"));
        builder.b(StandardBannerFieldsSelections.f21039a);
        List listR = CollectionsKt.R(compiledFieldC, builder.a());
        f21043a = listR;
        InsetBannerActionPlacement.e.getClass();
        CompiledField compiledFieldC2 = new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.f)).c();
        InsetBannerActionType.e.getClass();
        List listR2 = CollectionsKt.R(compiledFieldC2, new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.f)).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType), d.g("actionAccessibilityHint", customScalarType));
        b = listR2;
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC3 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.f)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g("title", customScalarType);
        CompiledField compiledFieldG2 = d.g("iconUrl", customScalarType);
        CompiledField.Builder builder2 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.f9638a);
        builder2.e = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC3, compiledFieldC4, compiledFieldG, compiledFieldG2, builder2.c());
        c = listR3;
        List listR4 = CollectionsKt.R(new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("caption", CompiledGraphQL.b(customScalarType)).c(), d.g("altText", customScalarType), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c());
        d = listR4;
        CompiledField compiledFieldC5 = new CompiledField.Builder("displayLastUpdated", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC6 = new CompiledField.Builder("separator", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("selectedIndex", CompiledGraphQL.b(GraphQLInt.f9616a)).c();
        CompiledField.Builder builder3 = new CompiledField.Builder("items", a.f(RewardsOfferMechanicItem.f9839a));
        builder3.e = listR4;
        List listR5 = CollectionsKt.R(compiledFieldC5, compiledFieldC6, compiledFieldC7, builder3.c());
        e = listR5;
        List listQ = CollectionsKt.Q(new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(customScalarType)).c());
        f = listQ;
        List listR6 = CollectionsKt.R(d.g("offerName", customScalarType), d.g("commId", customScalarType), d.g("uoid", customScalarType), d.g("campaignCode", customScalarType), d.g("campaignStream", customScalarType), d.g("channel", customScalarType), d.g("status", customScalarType), d.g("offerType", customScalarType), d.g("partnerId", customScalarType), d.g("rtlAccountID", customScalarType), d.g("rtlCampaignID", customScalarType), d.g("rtlCampaignCode", customScalarType), d.g("rtlCouponStart", customScalarType), d.g(Scopes.PROFILE, customScalarType));
        g = listR6;
        List listR7 = CollectionsKt.R(d.g("title", customScalarType), d.g("message", customScalarType), new CompiledField.Builder("buttonLabel", CompiledGraphQL.b(customScalarType)).c());
        h = listR7;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("IconAsset", CollectionsKt.R("LocalAsset", "HostedIcon", "CoreIcon"));
        builder4.b(IconAssetSelections.d);
        List listR8 = CollectionsKt.R(compiledFieldC8, builder4.a());
        i = listR8;
        CompiledField compiledFieldC9 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG3 = d.g("url", customScalarType);
        CustomScalarType customScalarType2 = GraphQLBoolean.f9613a;
        List listR9 = CollectionsKt.R(compiledFieldC9, compiledFieldG3, new CompiledField.Builder("isExternalUrl", customScalarType2).c());
        j = listR9;
        ObjectType objectType = ContentCta.f9485a;
        CompiledField.Builder builder5 = new CompiledField.Builder("cta", CompiledGraphQL.b(objectType));
        builder5.e = listR9;
        List listR10 = CollectionsKt.R(builder5.c(), d.g("displayStatus", customScalarType));
        k = listR10;
        List listR11 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType), d.g("isExternalUrl", customScalarType2));
        l = listR11;
        CompiledField.Builder builder6 = new CompiledField.Builder("cta", CompiledGraphQL.b(objectType));
        builder6.e = listR11;
        List listR12 = CollectionsKt.R(builder6.c(), d.g("displayStatus", customScalarType));
        m = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("ringPercent", CompiledGraphQL.b(GraphQLFloat.f9614a)).c(), new CompiledField.Builder(CircularProgressDrawable.RING_COLOR_PROPERTY, CompiledGraphQL.b(customScalarType)).c());
        n = listR13;
        CompiledField.Builder builder7 = new CompiledField.Builder("primaryRing", CompiledGraphQL.b(CircularProgressRing.f9480a));
        builder7.e = listR13;
        List listQ2 = CollectionsKt.Q(builder7.c());
        o = listQ2;
        CompiledField compiledFieldC10 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG4 = d.g("titleSuffix", customScalarType);
        CompiledField compiledFieldC11 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder8 = new CompiledField.Builder("circularProgressIndicator", CompiledGraphQL.b(CircularProgressIndicator.f9479a));
        builder8.e = listQ2;
        List listR14 = CollectionsKt.R(compiledFieldC10, compiledFieldG4, compiledFieldC11, builder8.c());
        p = listR14;
        CompiledField compiledFieldC12 = new CompiledField.Builder("offerId", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC13 = new CompiledField.Builder("image", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG5 = d.g("bannerUrl", customScalarType);
        CompiledField.Builder builder9 = new CompiledField.Builder("standardBanner", StandardBanner.f9912a);
        builder9.c = a.s("includeDetails", false);
        builder9.e = listR;
        CompiledField compiledFieldC14 = builder9.c();
        CompiledField.Builder builder10 = new CompiledField.Builder("boostedOfferInsetBanner", InsetBanner.f9637a);
        builder10.e = listR3;
        CompiledField compiledFieldC15 = builder10.c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG6 = d.g(ErrorBundle.SUMMARY_ENTRY, customScalarType);
        CompiledField compiledFieldG7 = d.g("body", customScalarType);
        CompiledField compiledFieldG8 = d.g("formattedTermsAndConditions", customScalarType);
        CompiledField compiledFieldG9 = d.g("markdownTermsAndConditions", customScalarType);
        CompiledField compiledFieldC18 = new CompiledField.Builder("displayStatus", CompiledGraphQL.b(customScalarType)).c();
        RewardsOfferStatus.e.getClass();
        CompiledField compiledFieldC19 = new CompiledField.Builder("offerStatus", CompiledGraphQL.b(RewardsOfferStatus.f)).c();
        CompiledField.Builder builder11 = new CompiledField.Builder("mechanics", RewardsOfferMechanics.f9840a);
        builder11.c = a.s("includeDetails", false);
        builder11.e = listR5;
        CompiledField compiledFieldC20 = builder11.c();
        CompiledField compiledFieldC21 = new CompiledField.Builder("displayExpiry", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG10 = d.g("displayExpiryExtended", customScalarType);
        CompiledField.Builder builder12 = new CompiledField.Builder("statusIcons", a.f(RewardsStatusIcon.f9871a));
        builder12.c = a.s("isOfferDetailsRefactorEnabled", true);
        builder12.e = listQ;
        CompiledField compiledFieldC22 = builder12.c();
        CompiledField.Builder builder13 = new CompiledField.Builder("offerAnalytics", RewardsOfferAnalytics.f9837a);
        builder13.e = listR6;
        CompiledField compiledFieldC23 = builder13.c();
        CompiledField compiledFieldG11 = d.g("activationAnimation", customScalarType);
        CompiledField compiledFieldG12 = d.g("displayAnimation", customScalarType);
        CompiledField.Builder builder14 = new CompiledField.Builder("activationMessage", RewardsOfferActivationMessage.f9836a);
        builder14.e = listR7;
        CompiledField compiledFieldC24 = builder14.c();
        CompiledField compiledFieldG13 = d.g("brandLogoUrl", customScalarType);
        CompiledField compiledFieldG14 = d.g("brandLogoUrlCompact", customScalarType);
        CompiledField.Builder builder15 = new CompiledField.Builder("roundel", HostedIcon.f9622a);
        builder15.c = a.s("isTigerNewOfferEnabled", false);
        builder15.e = listR8;
        CompiledField compiledFieldC25 = builder15.c();
        ObjectType objectType2 = OfferCta.f9675a;
        CompiledField.Builder builder16 = new CompiledField.Builder("offerListCta", objectType2);
        builder16.e = listR10;
        CompiledField compiledFieldC26 = builder16.c();
        CompiledField.Builder builder17 = new CompiledField.Builder("offerDetailsCta", objectType2);
        builder17.c = a.s("includeDetails", false);
        builder17.e = listR12;
        CompiledField compiledFieldC27 = builder17.c();
        CompiledField.Builder builder18 = new CompiledField.Builder("offerTileProgressTracker", RewardsOfferProgressIndicator.f9841a);
        builder18.c = a.s("isOfferDetailsRefactorEnabled", false);
        builder18.e = listR14;
        CompiledField compiledFieldC28 = builder18.c();
        CompiledField.Builder builder19 = new CompiledField.Builder("offerTileAltText", CompiledGraphQL.b(customScalarType));
        builder19.c = a.s("isOfferDetailsRefactorEnabled", false);
        q = CollectionsKt.R(compiledFieldC12, compiledFieldC13, compiledFieldG5, compiledFieldC14, compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldG6, compiledFieldG7, compiledFieldG8, compiledFieldG9, compiledFieldC18, compiledFieldC19, compiledFieldC20, compiledFieldC21, compiledFieldG10, compiledFieldC22, compiledFieldC23, compiledFieldG11, compiledFieldG12, compiledFieldC24, compiledFieldG13, compiledFieldG14, compiledFieldC25, compiledFieldC26, compiledFieldC27, compiledFieldC28, builder19.c());
    }
}
