package com.woolworths.rewards.offers.fragment.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.rewards.graphql.type.ContentCta;
import au.com.woolworths.rewards.graphql.type.GraphQLBoolean;
import au.com.woolworths.rewards.graphql.type.GraphQLID;
import au.com.woolworths.rewards.graphql.type.GraphQLString;
import au.com.woolworths.rewards.graphql.type.OffersFilterAnalytics;
import au.com.woolworths.rewards.graphql.type.OffersSections;
import au.com.woolworths.rewards.graphql.type.RewardsErrorDialog;
import au.com.woolworths.rewards.graphql.type.RewardsOffersFilter;
import au.com.woolworths.rewards.graphql.type.RewardsOffersHeader;
import au.com.woolworths.rewards.graphql.type.RewardsOffersMessage;
import au.com.woolworths.rewards.graphql.type.RewardsSummaryContent;
import au.com.woolworths.rewards.graphql.type.SectionConfigs;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import com.woolworths.rewards.offers.fragment.fragment.selections.ContentCtaFieldsSelections;
import com.woolworths.rewards.offers.fragment.fragment.selections.OffersSectionsFragmentSelections;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.ErrorBundle;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/rewards/offers/fragment/selections/RewardsOfferFeedFieldsSelections;", "", "offers_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class RewardsOfferFeedFieldsSelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f21042a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;

    static {
        CustomScalarType customScalarType = GraphQLString.f9617a;
        List listQ = CollectionsKt.Q(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c());
        f21042a = listQ;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("ContentCta", CollectionsKt.Q("ContentCta"));
        List list = ContentCtaFieldsSelections.b;
        builder.b(list);
        CompiledFragment compiledFragmentA = builder.a();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("RewardsSummaryText", CollectionsKt.Q("RewardsSummaryText"));
        builder2.d = listQ;
        List listR = CollectionsKt.R(compiledFieldC, compiledFragmentA, builder2.a());
        b = listR;
        CompiledField compiledFieldC2 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder3 = new CompiledField.Builder(ErrorBundle.SUMMARY_ENTRY, RewardsSummaryContent.f9873a);
        builder3.e = listR;
        List listR2 = CollectionsKt.R(compiledFieldC2, builder3.c());
        c = listR2;
        CompiledField compiledFieldC3 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("ContentCta", CollectionsKt.Q("ContentCta"));
        builder4.d = list;
        List listR3 = CollectionsKt.R(compiledFieldC3, builder4.a());
        d = listR3;
        CompiledField compiledFieldC4 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("ContentCta", CollectionsKt.Q("ContentCta"));
        builder5.d = list;
        List listR4 = CollectionsKt.R(compiledFieldC4, builder5.a());
        e = listR4;
        CompiledField compiledFieldC5 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        ObjectType objectType = ContentCta.f9485a;
        CompiledField.Builder builder6 = new CompiledField.Builder("primaryCta", objectType);
        builder6.e = listR3;
        CompiledField compiledFieldC6 = builder6.c();
        CompiledField.Builder builder7 = new CompiledField.Builder("secondaryCta", objectType);
        builder7.e = listR4;
        List listR5 = CollectionsKt.R(compiledFieldC5, compiledFieldG, compiledFieldC6, builder7.c());
        f = listR5;
        List listR6 = CollectionsKt.R(new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c());
        g = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c());
        h = listR7;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c());
        i = listQ2;
        CustomScalarType customScalarType2 = GraphQLID.f9615a;
        CompiledField compiledFieldC7 = new CompiledField.Builder("sectionId", CompiledGraphQL.b(customScalarType2)).c();
        CustomScalarType customScalarType3 = GraphQLBoolean.f9613a;
        List listR8 = CollectionsKt.R(compiledFieldC7, new CompiledField.Builder("showSectionTitle", CompiledGraphQL.b(customScalarType3)).c());
        j = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("sectionId", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("showBanner", CompiledGraphQL.b(customScalarType3)).c());
        k = listR9;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("OffersSectionConfig", CollectionsKt.Q("OffersSectionConfig"));
        builder8.d = listR8;
        CompiledFragment compiledFragmentA2 = builder8.a();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("BannerSectionConfig", CollectionsKt.Q("BannerSectionConfig"));
        builder9.d = listR9;
        List listR10 = CollectionsKt.R(compiledFieldC8, compiledFragmentA2, builder9.a());
        l = listR10;
        CompiledField compiledFieldC9 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC10 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC11 = new CompiledField.Builder("offerIds", a.e(customScalarType)).c();
        ObjectType objectType2 = RewardsOffersMessage.f9847a;
        CompiledField.Builder builder10 = new CompiledField.Builder("message", objectType2);
        builder10.e = listR7;
        CompiledField compiledFieldC12 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("analytics", OffersFilterAnalytics.f9696a);
        builder11.e = listQ2;
        CompiledField compiledFieldC13 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("sectionConfigsFeed", CompiledGraphQL.a(CompiledGraphQL.b(SectionConfigs.f9899a)));
        builder12.e = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC9, compiledFieldC10, compiledFieldC11, compiledFieldC12, compiledFieldC13, builder12.c());
        m = listR11;
        CompiledField compiledFieldC14 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("OffersSections", CollectionsKt.R("StandardOffersSection", "ProductOffersSection", "OnboardingBanner", "StandardBanner", "SpinSurpriseBanner", "OfferFeedInlineBanner", "PersonalisedOffersBanner", "RewardsCtaCard", "MandyBanner", "NoOffersCard"));
        builder13.b(OffersSectionsFragmentSelections.r);
        List listR12 = CollectionsKt.R(compiledFieldC14, builder13.a());
        n = listR12;
        CompiledField.Builder builder14 = new CompiledField.Builder("header", RewardsOffersHeader.f9845a);
        builder14.e = listR2;
        CompiledField compiledFieldC15 = builder14.c();
        CompiledField.Builder builder15 = new CompiledField.Builder("errorMessage", RewardsErrorDialog.f9826a);
        builder15.e = listR5;
        CompiledField compiledFieldC16 = builder15.c();
        CompiledField.Builder builder16 = new CompiledField.Builder("message", objectType2);
        builder16.e = listR6;
        CompiledField compiledFieldC17 = builder16.c();
        CompiledField.Builder builder17 = new CompiledField.Builder("filters", a.f(RewardsOffersFilter.f9844a));
        builder17.e = listR11;
        CompiledField compiledFieldC18 = builder17.c();
        CompiledField.Builder builder18 = new CompiledField.Builder("sections", d.j(OffersSections.f9698a));
        builder18.e = listR12;
        o = CollectionsKt.R(compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, builder18.c(), d.g("onLoadDeepLinkUrl", customScalarType), d.g("eligibleForOnboardingBanner", customScalarType3), new CompiledField.Builder("isAutoBoostEnabled", CompiledGraphQL.b(customScalarType3)).c());
    }
}
