package au.com.woolworths.feature.product.list.v2.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.product.list.v2.fragment.selections.InsetBannerSelections;
import au.com.woolworths.feature.product.list.v2.fragment.selections.VideoAdBottomSheetSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.AdBannerNativeSize;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.CardHeight;
import au.com.woolworths.shop.graphql.type.Chip;
import au.com.woolworths.shop.graphql.type.ContentCta;
import au.com.woolworths.shop.graphql.type.FilterMenuItem;
import au.com.woolworths.shop.graphql.type.GoogleAdBannerCard;
import au.com.woolworths.shop.graphql.type.GoogleAdCustomTargeting;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLID;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.HorizontalListItem;
import au.com.woolworths.shop.graphql.type.ImageWithAlt;
import au.com.woolworths.shop.graphql.type.InfoSection;
import au.com.woolworths.shop.graphql.type.InfoSectionFooter;
import au.com.woolworths.shop.graphql.type.InfoSectionItem;
import au.com.woolworths.shop.graphql.type.InsetBanner;
import au.com.woolworths.shop.graphql.type.InsetBannerAction;
import au.com.woolworths.shop.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.shop.graphql.type.InsetBannerActionType;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.Link;
import au.com.woolworths.shop.graphql.type.MarketplaceEducationBottomSheet;
import au.com.woolworths.shop.graphql.type.ProductCard;
import au.com.woolworths.shop.graphql.type.ProductCategoryTile;
import au.com.woolworths.shop.graphql.type.ProductFilter;
import au.com.woolworths.shop.graphql.type.ProductFilterSwitch;
import au.com.woolworths.shop.graphql.type.ProductList;
import au.com.woolworths.shop.graphql.type.ProductListAnalytics;
import au.com.woolworths.shop.graphql.type.ProductListFeed;
import au.com.woolworths.shop.graphql.type.ProductListZeroResultItem;
import au.com.woolworths.shop.graphql.type.ProductListZeroResults;
import au.com.woolworths.shop.graphql.type.ProductSortOption;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.TealiumAnalytics;
import au.com.woolworths.shop.graphql.type.TextWithAlt;
import au.com.woolworths.shop.graphql.type.UniversalInventoryNextBestAction;
import au.com.woolworths.shop.graphql.type.VideoAd;
import au.com.woolworths.shop.graphql.type.VideoAdBottomSheet;
import au.com.woolworths.shop.graphql.type.VideoAdEventAnalytics;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.google.android.gms.ads.OutOfContextTestingActivity;
import com.google.android.gms.measurement.api.AppMeasurementSdk;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/feature/product/list/v2/selections/ProductListQuerySelections;", "", "product-list-v2_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class ProductListQuerySelections {
    public static final List A;
    public static final List A0;
    public static final List B;
    public static final List B0;
    public static final List C;
    public static final List C0;
    public static final List D;
    public static final List D0;
    public static final List E;
    public static final List E0;
    public static final List F;
    public static final List F0;
    public static final List G;
    public static final List G0;
    public static final List H;
    public static final List H0;
    public static final List I;
    public static final List I0;
    public static final List J;
    public static final List J0;
    public static final List K;
    public static final List K0;
    public static final List L;
    public static final List L0;
    public static final List M;
    public static final List M0;
    public static final List N;
    public static final List N0;
    public static final List O;
    public static final List O0;
    public static final List P;
    public static final List P0;
    public static final List Q;
    public static final List R;
    public static final List S;
    public static final List T;
    public static final List U;
    public static final List V;
    public static final List W;
    public static final List X;
    public static final List Y;
    public static final List Z;

    /* renamed from: a, reason: collision with root package name */
    public static final List f5640a;
    public static final List a0;
    public static final List b;
    public static final List b0;
    public static final List c;
    public static final List c0;
    public static final List d;
    public static final List d0;
    public static final List e;
    public static final List e0;
    public static final List f;
    public static final List f0;
    public static final List g;
    public static final List g0;
    public static final List h;
    public static final List h0;
    public static final List i;
    public static final List i0;
    public static final List j;
    public static final List j0;
    public static final List k;
    public static final List k0;
    public static final List l;
    public static final List l0;
    public static final List m;
    public static final List m0;
    public static final List n;
    public static final List n0;
    public static final List o;
    public static final List o0;
    public static final List p;
    public static final List p0;
    public static final List q;
    public static final List q0;
    public static final List r;
    public static final List r0;
    public static final List s;
    public static final List s0;
    public static final List t;
    public static final List t0;
    public static final List u;
    public static final List u0;
    public static final List v;
    public static final List v0;
    public static final List w;
    public static final List w0;
    public static final List x;
    public static final List x0;
    public static final List y;
    public static final List y0;
    public static final List z;
    public static final List z0;

    static {
        List listR = CollectionsKt.R(new CompiledField.Builder("tnta", GraphQLString.Companion.a()).c(), new CompiledField.Builder("pe", GraphQLString.Companion.a()).c());
        f5640a = listR;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("AdobeTargetAnalytics", CollectionsKt.Q("AdobeTargetAnalytics"));
        builder.b(listR);
        List listR2 = CollectionsKt.R(compiledFieldC, builder.a());
        b = listR2;
        CompiledField compiledFieldC2 = new CompiledField.Builder("image", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC3 = new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CardHeight.e.getClass();
        List listR3 = CollectionsKt.R(compiledFieldC2, compiledFieldC3, new CompiledField.Builder("cardHeight", CompiledGraphQL.b(CardHeight.Companion.a())).c(), new CompiledField.Builder("link", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("analytics", TealiumAnalytics.Companion.a()).c(), new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c());
        c = listR3;
        List listR4 = CollectionsKt.R(new CompiledField.Builder(OutOfContextTestingActivity.AD_UNIT_KEY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("nativeCustomTemplateId", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("targeting", GoogleAdCustomTargeting.Companion.a()).c(), new CompiledField.Builder("iabSize", GraphQLString.Companion.a()).c(), new CompiledField.Builder("correlator", GraphQLString.Companion.a()).c());
        d = listR4;
        CompiledField compiledFieldC4 = new CompiledField.Builder(OutOfContextTestingActivity.AD_UNIT_KEY, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC5 = new CompiledField.Builder("nativeCustomTemplateId", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC6 = new CompiledField.Builder("iabSpec", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("iabSize", GraphQLString.Companion.a()).c();
        AdBannerNativeSize.e.getClass();
        List listR5 = CollectionsKt.R(compiledFieldC4, compiledFieldC5, compiledFieldC6, compiledFieldC7, new CompiledField.Builder("height", CompiledGraphQL.b(AdBannerNativeSize.Companion.a())).c(), new CompiledField.Builder("targeting", GoogleAdCustomTargeting.Companion.a()).c(), new CompiledField.Builder("correlator", GraphQLString.Companion.a()).c(), new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c());
        e = listR5;
        List listR6 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("link", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("image", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("cardHeight", CompiledGraphQL.b(CardHeight.Companion.a())).c(), new CompiledField.Builder("analytics", TealiumAnalytics.Companion.a()).c(), new CompiledField.Builder("_excluded", GraphQLBoolean.Companion.a()).c());
        f = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        g = listR7;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ActionType.e.getClass();
        CompiledField compiledFieldC9 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC10 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType = Analytics.f11028a;
        CompiledField.Builder builder2 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder2.e(listR7);
        List listR8 = CollectionsKt.R(compiledFieldC8, compiledFieldC9, compiledFieldC10, builder2.c(), new CompiledField.Builder("id", GraphQLString.Companion.a()).c());
        h = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        i = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        j = listR10;
        CompiledField compiledFieldC11 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC12 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC13 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder3 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder3.e(listR10);
        List listR11 = CollectionsKt.R(compiledFieldC11, compiledFieldC12, compiledFieldC13, builder3.c(), new CompiledField.Builder("id", GraphQLString.Companion.a()).c());
        k = listR11;
        List listR12 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        l = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        m = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        n = listR14;
        CompiledField compiledFieldC14 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC15 = new CompiledField.Builder("offerId", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("offerIdV1", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("linkedEdrHashCrn", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC18 = new CompiledField.Builder("bannerTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC19 = new CompiledField.Builder("bannerDescription", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC20 = new CompiledField.Builder("bannerIconUrl", GraphQLString.Companion.a()).c();
        ObjectType objectType2 = Action.f10997a;
        CompiledField.Builder builder4 = new CompiledField.Builder("bannerButtonAction", Action.Companion.a());
        builder4.e(listR8);
        CompiledField compiledFieldC21 = builder4.c();
        ObjectType objectType3 = TextWithAlt.f11967a;
        CompiledField.Builder builder5 = new CompiledField.Builder("bannerButtonLabel", TextWithAlt.Companion.a());
        builder5.e(listR9);
        CompiledField compiledFieldC22 = builder5.c();
        CompiledField.Builder builder6 = new CompiledField.Builder("bannerAction", Action.Companion.a());
        builder6.e(listR11);
        CompiledField compiledFieldC23 = builder6.c();
        CompiledField.Builder builder7 = new CompiledField.Builder("bannerAnalytics", Analytics.Companion.a());
        builder7.e(listR12);
        CompiledField compiledFieldC24 = builder7.c();
        CompiledField.Builder builder8 = new CompiledField.Builder("bannerImpressionAnalytics", Analytics.Companion.a());
        builder8.e(listR13);
        CompiledField compiledFieldC25 = builder8.c();
        CompiledField.Builder builder9 = new CompiledField.Builder("commonAnalytics", Analytics.Companion.a());
        builder9.e(listR14);
        List listR15 = CollectionsKt.R(compiledFieldC14, compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, compiledFieldC19, compiledFieldC20, compiledFieldC21, compiledFieldC22, compiledFieldC23, compiledFieldC24, compiledFieldC25, builder9.c());
        o = listR15;
        List listR16 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        p = listR16;
        List listR17 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("productId", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("productImage", GraphQLString.Companion.a()).c());
        q = listR17;
        List listR18 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        r = listR18;
        CompiledField compiledFieldC26 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC27 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC28 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder10 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder10.e(listR18);
        List listR19 = CollectionsKt.R(compiledFieldC26, compiledFieldC27, compiledFieldC28, builder10.c(), new CompiledField.Builder("id", GraphQLString.Companion.a()).c());
        s = listR19;
        List listR20 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        t = listR20;
        List listR21 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        u = listR21;
        CompiledField compiledFieldC29 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC30 = new CompiledField.Builder("bannerTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC31 = new CompiledField.Builder("bannerForegroundColour", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC32 = new CompiledField.Builder("bannerBackgroundColour", GraphQLString.Companion.a()).c();
        ObjectType objectType4 = ImageWithAlt.f11487a;
        CompiledField.Builder builder11 = new CompiledField.Builder("bannerImage", ImageWithAlt.Companion.a());
        builder11.e(listR16);
        CompiledField compiledFieldC33 = builder11.c();
        ObjectType objectType5 = ProductCard.f11717a;
        CompiledField.Builder builder12 = new CompiledField.Builder("products", CompiledGraphQL.a(CompiledGraphQL.b(ProductCard.Companion.a())));
        builder12.e(listR17);
        CompiledField compiledFieldC34 = builder12.c();
        CompiledField.Builder builder13 = new CompiledField.Builder("bannerAction", Action.Companion.a());
        builder13.e(listR19);
        CompiledField compiledFieldC35 = builder13.c();
        CompiledField.Builder builder14 = new CompiledField.Builder("bannerAnalytics", Analytics.Companion.a());
        builder14.e(listR20);
        CompiledField compiledFieldC36 = builder14.c();
        CompiledField.Builder builder15 = new CompiledField.Builder("bannerImpressionAnalytics", Analytics.Companion.a());
        builder15.e(listR21);
        List listR22 = CollectionsKt.R(compiledFieldC29, compiledFieldC30, compiledFieldC31, compiledFieldC32, compiledFieldC33, compiledFieldC34, compiledFieldC35, compiledFieldC36, builder15.c());
        v = listR22;
        CompiledField compiledFieldC37 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder16.b(listR6);
        List listR23 = CollectionsKt.R(compiledFieldC37, builder16.a(), d.i("includeNhpEdrBanner", false, new CompiledFragment.Builder("EdrOfferBanner", CollectionsKt.Q("EdrOfferBanner")), listR15), d.i("includeNhpPersonalisedProductsBanner", false, new CompiledFragment.Builder("PersonalisedProductsBanner", CollectionsKt.Q("PersonalisedProductsBanner")), listR22));
        w = listR23;
        ObjectType objectType6 = GoogleAdBannerCard.f11435a;
        CompiledField.Builder builder17 = new CompiledField.Builder("googleAdBannerCard", GoogleAdBannerCard.Companion.a());
        builder17.e(listR5);
        CompiledField compiledFieldC38 = builder17.c();
        UnionType unionType = UniversalInventoryNextBestAction.f11980a;
        CompiledField.Builder builder18 = new CompiledField.Builder("nextBestAction", UniversalInventoryNextBestAction.Companion.a());
        builder18.e(listR23);
        List listR24 = CollectionsKt.R(compiledFieldC38, builder18.c());
        x = listR24;
        List listR25 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        y = listR25;
        List listR26 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        z = listR26;
        List listR27 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        A = listR27;
        List listR28 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("id", GraphQLString.Companion.a()).c());
        B = listR28;
        CompiledField compiledFieldC39 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC40 = new CompiledField.Builder("buttonId", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC41 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ButtonStyle.e.getClass();
        CompiledField compiledFieldC42 = new CompiledField.Builder("style", ButtonStyle.Companion.a()).c();
        CompiledField compiledFieldC43 = new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC44 = new CompiledField.Builder("iconUrl", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC45 = new CompiledField.Builder("altText", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder19 = new CompiledField.Builder("buttonAction", Action.Companion.a());
        builder19.e(listR28);
        List listR29 = CollectionsKt.R(compiledFieldC39, compiledFieldC40, compiledFieldC41, compiledFieldC42, compiledFieldC43, compiledFieldC44, compiledFieldC45, builder19.c());
        C = listR29;
        CompiledField compiledFieldC46 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder20 = new CompiledField.Builder("merchCardFullImageAction", Action.Companion.a());
        builder20.e(listR26);
        CompiledField compiledFieldC47 = builder20.c();
        CompiledField.Builder builder21 = new CompiledField.Builder("merchCardFullImageBackgroundImageWithAlt", CompiledGraphQL.b(ImageWithAlt.Companion.a()));
        builder21.e(listR27);
        CompiledField compiledFieldC48 = builder21.c();
        ObjectType objectType7 = Button.f11080a;
        CompiledField.Builder builder22 = new CompiledField.Builder("merchCardFullImageButton", Button.Companion.a());
        builder22.e(listR29);
        List listR30 = CollectionsKt.R(compiledFieldC46, compiledFieldC47, compiledFieldC48, builder22.c(), new CompiledField.Builder("merchCardFullImageTitle", GraphQLString.Companion.a()).c(), new CompiledField.Builder("merchCardFullImageDescription", GraphQLString.Companion.a()).c());
        D = listR30;
        CompiledField compiledFieldC49 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder23.b(listR25);
        CompiledFragment compiledFragmentA = builder23.a();
        CompiledFragment.Builder builder24 = new CompiledFragment.Builder("MerchCardFullImage", CollectionsKt.Q("MerchCardFullImage"));
        builder24.b(listR30);
        List listR31 = CollectionsKt.R(compiledFieldC49, compiledFragmentA, builder24.a());
        E = listR31;
        CompiledField compiledFieldC50 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC51 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC52 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC53 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC54 = new CompiledField.Builder("deepLink", GraphQLString.Companion.a()).c();
        UnionType unionType2 = HorizontalListItem.f11475a;
        CompiledField.Builder builder25 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder25.e(listR31);
        List listR32 = CollectionsKt.R(compiledFieldC50, compiledFieldC51, compiledFieldC52, compiledFieldC53, compiledFieldC54, builder25.c());
        F = listR32;
        List listR33 = CollectionsKt.R(new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        G = listR33;
        CompiledField compiledFieldC55 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("VideoAdBottomSheet", CollectionsKt.Q("VideoAdBottomSheet"));
        List list = VideoAdBottomSheetSelections.b;
        builder26.b(list);
        List listR34 = CollectionsKt.R(compiledFieldC55, builder26.a());
        H = listR34;
        CompiledField compiledFieldC56 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder27 = new CompiledFragment.Builder("VideoAdBottomSheet", CollectionsKt.Q("VideoAdBottomSheet"));
        builder27.b(list);
        List listR35 = CollectionsKt.R(compiledFieldC56, builder27.a());
        I = listR35;
        List listR36 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        J = listR36;
        List listR37 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        K = listR37;
        List listR38 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        L = listR38;
        List listR39 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        M = listR39;
        List listR40 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        N = listR40;
        CompiledField.Builder builder28 = new CompiledField.Builder("impression", Analytics.Companion.a());
        builder28.e(listR37);
        CompiledField compiledFieldC57 = builder28.c();
        CompiledField.Builder builder29 = new CompiledField.Builder("videoPlay", Analytics.Companion.a());
        builder29.e(listR38);
        CompiledField compiledFieldC58 = builder29.c();
        CompiledField.Builder builder30 = new CompiledField.Builder("videoPause", Analytics.Companion.a());
        builder30.e(listR39);
        CompiledField compiledFieldC59 = builder30.c();
        CompiledField.Builder builder31 = new CompiledField.Builder("videoErrorImpression", Analytics.Companion.a());
        builder31.e(listR40);
        List listR41 = CollectionsKt.R(compiledFieldC57, compiledFieldC58, compiledFieldC59, builder31.c());
        O = listR41;
        CompiledField compiledFieldC60 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC61 = new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder32 = new CompiledField.Builder("fallbackImage", ImageWithAlt.Companion.a());
        builder32.e(listR33);
        CompiledField compiledFieldC62 = builder32.c();
        CompiledField compiledFieldC63 = new CompiledField.Builder("duration", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        ObjectType objectType8 = VideoAdBottomSheet.f12008a;
        CompiledField.Builder builder33 = new CompiledField.Builder("transcript", VideoAdBottomSheet.Companion.a());
        builder33.e(listR34);
        CompiledField compiledFieldC64 = builder33.c();
        CompiledField.Builder builder34 = new CompiledField.Builder("termsAndConditions", VideoAdBottomSheet.Companion.a());
        builder34.e(listR35);
        CompiledField compiledFieldC65 = builder34.c();
        CompiledField.Builder builder35 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder35.e(listR36);
        CompiledField compiledFieldC66 = builder35.c();
        CompiledField.Builder builder36 = new CompiledField.Builder("eventAnalytics", VideoAdEventAnalytics.f12009a);
        builder36.e(listR41);
        List listR42 = CollectionsKt.R(compiledFieldC60, compiledFieldC61, compiledFieldC62, compiledFieldC63, compiledFieldC64, compiledFieldC65, compiledFieldC66, builder36.c());
        P = listR42;
        List listR43 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        Q = listR43;
        CompiledField compiledFieldC67 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder37 = new CompiledField.Builder("videoAdUnitVideoAd", CompiledGraphQL.b(VideoAd.f12007a));
        builder37.e(listR42);
        CompiledField compiledFieldC68 = builder37.c();
        CompiledField.Builder builder38 = new CompiledField.Builder("videoAdUnitProductCard", ProductCard.Companion.a());
        builder38.e(listR43);
        List listR44 = CollectionsKt.R(compiledFieldC67, compiledFieldC68, builder38.c());
        R = listR44;
        List listR45 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        S = listR45;
        List listR46 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        T = listR46;
        List listR47 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        U = listR47;
        CompiledField compiledFieldC69 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC70 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC71 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC72 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder39 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder39.e(listR47);
        List listR48 = CollectionsKt.R(compiledFieldC69, compiledFieldC70, compiledFieldC71, compiledFieldC72, builder39.c());
        V = listR48;
        CompiledField compiledFieldC73 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC74 = new CompiledField.Builder("buttonId", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC75 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC76 = new CompiledField.Builder("style", ButtonStyle.Companion.a()).c();
        CompiledField compiledFieldC77 = new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC78 = new CompiledField.Builder("iconUrl", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC79 = new CompiledField.Builder("altText", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder40 = new CompiledField.Builder("buttonAction", Action.Companion.a());
        builder40.e(listR48);
        List listR49 = CollectionsKt.R(compiledFieldC73, compiledFieldC74, compiledFieldC75, compiledFieldC76, compiledFieldC77, compiledFieldC78, compiledFieldC79, builder40.c());
        W = listR49;
        List listR50 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        X = listR50;
        CompiledField compiledFieldC80 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC81 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC82 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC83 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder41 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder41.e(listR50);
        List listR51 = CollectionsKt.R(compiledFieldC80, compiledFieldC81, compiledFieldC82, compiledFieldC83, builder41.c());
        Y = listR51;
        List listR52 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        Z = listR52;
        List listR53 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        a0 = listR53;
        CompiledField compiledFieldC84 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder42 = new CompiledField.Builder("merchCardGridImageWithAlt", CompiledGraphQL.b(ImageWithAlt.Companion.a()));
        builder42.e(listR45);
        CompiledField compiledFieldC85 = builder42.c();
        CompiledField.Builder builder43 = new CompiledField.Builder("merchCardListImageWithAlt", CompiledGraphQL.b(ImageWithAlt.Companion.a()));
        builder43.e(listR46);
        CompiledField compiledFieldC86 = builder43.c();
        CompiledField compiledFieldC87 = new CompiledField.Builder("merchCardTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC88 = new CompiledField.Builder("merchCardDescription", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder44 = new CompiledField.Builder("merchCardButton", Button.Companion.a());
        builder44.e(listR49);
        CompiledField compiledFieldC89 = builder44.c();
        CompiledField.Builder builder45 = new CompiledField.Builder("merchCardAction", Action.Companion.a());
        builder45.e(listR51);
        CompiledField compiledFieldC90 = builder45.c();
        CompiledField.Builder builder46 = new CompiledField.Builder("merchCardAnalytics", Analytics.Companion.a());
        builder46.e(listR52);
        CompiledField compiledFieldC91 = builder46.c();
        CompiledField.Builder builder47 = new CompiledField.Builder("merchCardImpressionAnalytics", Analytics.Companion.a());
        builder47.e(listR53);
        List listR54 = CollectionsKt.R(compiledFieldC84, compiledFieldC85, compiledFieldC86, compiledFieldC87, compiledFieldC88, compiledFieldC89, compiledFieldC90, compiledFieldC91, builder47.c());
        b0 = listR54;
        InsetBannerActionPlacement.e.getClass();
        CompiledField compiledFieldC92 = new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.Companion.a())).c();
        InsetBannerActionType.e.getClass();
        List listR55 = CollectionsKt.R(compiledFieldC92, new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        c0 = listR55;
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC93 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField compiledFieldC94 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder48 = new CompiledField.Builder("title", GraphQLString.Companion.a());
        builder48.a("bannerTitle");
        CompiledField compiledFieldC95 = builder48.c();
        CompiledField compiledFieldC96 = new CompiledField.Builder("iconUrl", GraphQLString.Companion.a()).c();
        ObjectType objectType9 = InsetBannerAction.f11510a;
        CompiledField.Builder builder49 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.Companion.a());
        builder49.e(listR55);
        List listR56 = CollectionsKt.R(compiledFieldC93, compiledFieldC94, compiledFieldC95, compiledFieldC96, builder49.c());
        d0 = listR56;
        List listR57 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        e0 = listR57;
        CompiledField compiledFieldC97 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder50 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder50.b(listR3);
        CompiledFragment compiledFragmentA2 = builder50.a();
        CompiledFragment compiledFragmentI = d.i("includeUniversalInventoryFallback", true, new CompiledFragment.Builder("GoogleAdBannerCard", CollectionsKt.Q("GoogleAdBannerCard")), listR4);
        CompiledFragment compiledFragmentI2 = d.i("includeUniversalInventoryFallback", false, new CompiledFragment.Builder("UniversalInventoryContainer", CollectionsKt.Q("UniversalInventoryContainer")), listR24);
        CompiledFragment compiledFragmentI3 = d.i("includeHorizontalList", false, new CompiledFragment.Builder("HorizontalList", CollectionsKt.Q("HorizontalList")), listR32);
        CompiledFragment compiledFragmentI4 = d.i("includeVideoAdUnit", false, new CompiledFragment.Builder("VideoAdUnit", CollectionsKt.Q("VideoAdUnit")), listR44);
        CompiledFragment compiledFragmentI5 = d.i("includeMerchCard", false, new CompiledFragment.Builder("MerchCard", CollectionsKt.Q("MerchCard")), listR54);
        CompiledFragment.Builder builder51 = new CompiledFragment.Builder("InsetBanner", CollectionsKt.Q("InsetBanner"));
        builder51.b(listR56);
        CompiledFragment compiledFragmentA3 = builder51.a();
        CompiledFragment.Builder builder52 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder52.b(listR57);
        List listR58 = CollectionsKt.R(compiledFieldC97, compiledFragmentA2, compiledFragmentI, compiledFragmentI2, compiledFragmentI3, compiledFragmentI4, compiledFragmentI5, compiledFragmentA3, builder52.a());
        f0 = listR58;
        List listR59 = CollectionsKt.R(new CompiledField.Builder("key", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("parentKey", GraphQLString.Companion.a()).c(), new CompiledField.Builder("hasChildren", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("isApplied", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        g0 = listR59;
        List listR60 = CollectionsKt.R(new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.Companion.a())).c(), new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        h0 = listR60;
        CompiledField compiledFieldC98 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField compiledFieldC99 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC100 = new CompiledField.Builder("iconUrl", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder53 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.Companion.a());
        builder53.e(listR60);
        CompiledField compiledFieldC101 = builder53.c();
        CompiledField.Builder builder54 = new CompiledField.Builder("title", GraphQLString.Companion.a());
        builder54.a("bannerTitle");
        List listR61 = CollectionsKt.R(compiledFieldC98, compiledFieldC99, compiledFieldC100, compiledFieldC101, builder54.c());
        i0 = listR61;
        CompiledField compiledFieldC102 = new CompiledField.Builder("headerKey", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC103 = new CompiledField.Builder("headerTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType10 = FilterMenuItem.f11386a;
        CompiledField.Builder builder55 = new CompiledField.Builder("filterItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(FilterMenuItem.Companion.a()))));
        builder55.e(listR59);
        CompiledField compiledFieldC104 = builder55.c();
        ObjectType objectType11 = InsetBanner.f11509a;
        CompiledField.Builder builder56 = new CompiledField.Builder("banner", InsetBanner.Companion.a());
        builder56.e(listR61);
        List listR62 = CollectionsKt.R(compiledFieldC102, compiledFieldC103, compiledFieldC104, builder56.c());
        j0 = listR62;
        List listR63 = CollectionsKt.R(new CompiledField.Builder("key", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c(), new CompiledField.Builder("isApplied", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        k0 = listR63;
        CompiledField compiledFieldC105 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder57 = new CompiledFragment.Builder("InsetBanner", CollectionsKt.Q("InsetBanner"));
        builder57.b(InsetBannerSelections.a());
        List listR64 = CollectionsKt.R(compiledFieldC105, builder57.a());
        l0 = listR64;
        List listQ = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        m0 = listQ;
        CompiledField compiledFieldC106 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC107 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC108 = new CompiledField.Builder("imageUrl", GraphQLString.Companion.a()).c();
        ObjectType objectType12 = ContentCta.f11282a;
        CompiledField.Builder builder58 = new CompiledField.Builder("buttonCta", ContentCta.Companion.a());
        builder58.e(listQ);
        List listR65 = CollectionsKt.R(compiledFieldC106, compiledFieldC107, compiledFieldC108, builder58.c(), new CompiledField.Builder("value", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        n0 = listR65;
        List listR66 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        o0 = listR66;
        List listR67 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("linkUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        p0 = listR67;
        CompiledField compiledFieldC109 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType13 = InfoSectionItem.f11497a;
        CompiledField.Builder builder59 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(InfoSectionItem.Companion.a()))));
        builder59.e(listR66);
        CompiledField compiledFieldC110 = builder59.c();
        ObjectType objectType14 = InfoSectionFooter.f11496a;
        CompiledField.Builder builder60 = new CompiledField.Builder("footer", InfoSectionFooter.Companion.a());
        builder60.e(listR67);
        List listR68 = CollectionsKt.R(compiledFieldC109, compiledFieldC110, builder60.c());
        q0 = listR68;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        r0 = listQ2;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        s0 = listQ3;
        CompiledField compiledFieldC111 = new CompiledField.Builder("bottomSheetTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC112 = new CompiledField.Builder("bottomSheetBody", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder61 = new CompiledField.Builder("primaryCta", ContentCta.Companion.a());
        builder61.e(listQ2);
        CompiledField compiledFieldC113 = builder61.c();
        CompiledField.Builder builder62 = new CompiledField.Builder("secondaryCta", ContentCta.Companion.a());
        builder62.e(listQ3);
        List listR69 = CollectionsKt.R(compiledFieldC111, compiledFieldC112, compiledFieldC113, builder62.c(), new CompiledField.Builder("showOnceOnly", GraphQLBoolean.Companion.a()).c());
        t0 = listR69;
        List listR70 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        u0 = listR70;
        CompiledField compiledFieldC114 = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLID.Companion.a())).c();
        CompiledField compiledFieldC115 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField.Builder builder63 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(TextWithAlt.Companion.a()));
        builder63.e(listR70);
        List listR71 = CollectionsKt.R(compiledFieldC114, compiledFieldC115, builder63.c(), new CompiledField.Builder("persistentId", GraphQLString.Companion.a()).c());
        v0 = listR71;
        List listR72 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        w0 = listR72;
        CompiledField compiledFieldC116 = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLID.Companion.a())).c();
        CompiledField compiledFieldC117 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField.Builder builder64 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(TextWithAlt.Companion.a()));
        builder64.e(listR72);
        List listR73 = CollectionsKt.R(compiledFieldC116, compiledFieldC117, builder64.c());
        x0 = listR73;
        List listR74 = CollectionsKt.R(new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("id", GraphQLString.Companion.a()).c());
        y0 = listR74;
        CompiledField.Builder builder65 = new CompiledField.Builder("productCategoryTileAction", CompiledGraphQL.b(Action.Companion.a()));
        builder65.e(listR74);
        List listR75 = CollectionsKt.R(builder65.c(), new CompiledField.Builder("productCategoryTileImageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("productCategoryTileLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        z0 = listR75;
        CompiledField compiledFieldC118 = new CompiledField.Builder("zeroResultProductCategoriesTitle", GraphQLString.Companion.a()).c();
        ObjectType objectType15 = ProductCategoryTile.f11720a;
        CompiledField.Builder builder66 = new CompiledField.Builder("zeroResultProductCategoriesItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(ProductCategoryTile.Companion.a()))));
        builder66.e(listR75);
        List listR76 = CollectionsKt.R(compiledFieldC118, builder66.c());
        A0 = listR76;
        List listR77 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        B0 = listR77;
        CompiledField compiledFieldC119 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder67 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder67.b(listR77);
        List listR78 = CollectionsKt.R(compiledFieldC119, builder67.a());
        C0 = listR78;
        CompiledField compiledFieldC120 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder68 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder68.e(listR78);
        List listR79 = CollectionsKt.R(compiledFieldC120, builder68.c());
        D0 = listR79;
        CompiledField compiledFieldC121 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder69 = new CompiledFragment.Builder("ZeroResultProductCategories", CollectionsKt.Q("ZeroResultProductCategories"));
        builder69.b(listR76);
        CompiledFragment compiledFragmentA4 = builder69.a();
        CompiledFragment.Builder builder70 = new CompiledFragment.Builder("HorizontalList", CollectionsKt.Q("HorizontalList"));
        builder70.b(listR79);
        List listR80 = CollectionsKt.R(compiledFieldC121, compiledFragmentA4, builder70.a());
        E0 = listR80;
        CompiledField compiledFieldC122 = new CompiledField.Builder("title", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC123 = new CompiledField.Builder("message", GraphQLString.Companion.a()).c();
        UnionType unionType3 = ProductListZeroResultItem.f11757a;
        CompiledField.Builder builder71 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(ProductListZeroResultItem.Companion.a()))));
        builder71.e(listR80);
        List listR81 = CollectionsKt.R(compiledFieldC122, compiledFieldC123, builder71.c());
        F0 = listR81;
        List listR82 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        G0 = listR82;
        List listR83 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        H0 = listR83;
        List listR84 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        I0 = listR84;
        List listR85 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        J0 = listR85;
        CompiledField compiledFieldC124 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC125 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC126 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField.Builder builder72 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder72.e(listR85);
        List listR86 = CollectionsKt.R(compiledFieldC124, compiledFieldC125, compiledFieldC126, builder72.c());
        K0 = listR86;
        CompiledField compiledFieldC127 = new CompiledField.Builder("linkId", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder73 = new CompiledField.Builder("linkTextWithAlt", CompiledGraphQL.b(TextWithAlt.Companion.a()));
        builder73.e(listR84);
        CompiledField compiledFieldC128 = builder73.c();
        CompiledField.Builder builder74 = new CompiledField.Builder("linkAction", CompiledGraphQL.b(Action.Companion.a()));
        builder74.e(listR86);
        List listR87 = CollectionsKt.R(compiledFieldC127, compiledFieldC128, builder74.c());
        L0 = listR87;
        CompiledField.Builder builder75 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder75.e(listR82);
        CompiledField compiledFieldC129 = builder75.c();
        CompiledField.Builder builder76 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder76.e(listR83);
        CompiledField compiledFieldC130 = builder76.c();
        CompiledField compiledFieldC131 = new CompiledField.Builder("image", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC132 = new CompiledField.Builder("title", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC133 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, GraphQLString.Companion.a()).c();
        ObjectType objectType16 = Link.f11514a;
        CompiledField.Builder builder77 = new CompiledField.Builder("cta", Link.Companion.a());
        builder77.e(listR87);
        List listR88 = CollectionsKt.R(compiledFieldC129, compiledFieldC130, compiledFieldC131, compiledFieldC132, compiledFieldC133, builder77.c());
        M0 = listR88;
        CompiledField compiledFieldC134 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder78 = new CompiledFragment.Builder("ProductListZeroResult", CollectionsKt.Q("ProductListZeroResult"));
        builder78.b(listR81);
        CompiledFragment compiledFragmentA5 = builder78.a();
        CompiledFragment.Builder builder79 = new CompiledFragment.Builder("ProductListFullScreenError", CollectionsKt.Q("ProductListFullScreenError"));
        builder79.b(listR88);
        List listR89 = CollectionsKt.R(compiledFieldC134, compiledFragmentA5, builder79.a());
        N0 = listR89;
        CompiledField compiledFieldC135 = new CompiledField.Builder("totalNumberOfProducts", GraphQLInt.Companion.a()).c();
        CompiledField compiledFieldC136 = new CompiledField.Builder("nextPage", GraphQLInt.Companion.a()).c();
        CompiledField compiledFieldC137 = new CompiledField.Builder("pageTitle", GraphQLString.Companion.a()).c();
        UnionType unionType4 = ProductListAnalytics.f11750a;
        CompiledField.Builder builder80 = new CompiledField.Builder("analytics", CompiledGraphQL.a(CompiledGraphQL.b(ProductListAnalytics.Companion.a())));
        builder80.e(listR2);
        CompiledField compiledFieldC138 = builder80.c();
        UnionType unionType5 = ProductListFeed.f11751a;
        CompiledField.Builder builder81 = new CompiledField.Builder("productsFeed", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(ProductListFeed.Companion.a()))));
        builder81.e(listR58);
        CompiledField compiledFieldC139 = builder81.c();
        ObjectType objectType17 = ProductFilter.f11739a;
        CompiledField.Builder builder82 = new CompiledField.Builder("filters", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(ProductFilter.Companion.a()))));
        builder82.e(listR62);
        CompiledField compiledFieldC140 = builder82.c();
        ObjectType objectType18 = ProductSortOption.f11786a;
        CompiledField.Builder builder83 = new CompiledField.Builder("sortOptions", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(ProductSortOption.Companion.a()))));
        builder83.e(listR63);
        CompiledField compiledFieldC141 = builder83.c();
        CompiledField.Builder builder84 = new CompiledField.Builder("sortOptionsBanner", InsetBanner.Companion.a());
        builder84.e(listR64);
        CompiledField compiledFieldC142 = builder84.c();
        ObjectType objectType19 = ProductFilterSwitch.f11741a;
        CompiledField.Builder builder85 = new CompiledField.Builder("marketplaceFilterSwitch", ProductFilterSwitch.Companion.a());
        builder85.e(listR65);
        CompiledField compiledFieldC143 = builder85.c();
        ObjectType objectType20 = InfoSection.f11495a;
        CompiledField.Builder builder86 = new CompiledField.Builder("marketplaceInfo", InfoSection.Companion.a());
        builder86.e(listR68);
        CompiledField compiledFieldC144 = builder86.c();
        ObjectType objectType21 = MarketplaceEducationBottomSheet.f11556a;
        CompiledField.Builder builder87 = new CompiledField.Builder("marketplaceBottomSheet", MarketplaceEducationBottomSheet.Companion.a());
        builder87.e(listR69);
        CompiledField compiledFieldC145 = builder87.c();
        ObjectType objectType22 = Chip.f11271a;
        CompiledField.Builder builder88 = new CompiledField.Builder("chips", CompiledGraphQL.a(CompiledGraphQL.b(Chip.Companion.a())));
        builder88.e(listR71);
        CompiledField compiledFieldC146 = builder88.c();
        CompiledField.Builder builder89 = new CompiledField.Builder("facetChips", CompiledGraphQL.a(CompiledGraphQL.b(Chip.Companion.a())));
        builder89.e(listR73);
        CompiledField compiledFieldC147 = builder89.c();
        CompiledField.Builder builder90 = new CompiledField.Builder("zeroResult", ProductListZeroResults.f11758a);
        builder90.e(listR89);
        List listR90 = CollectionsKt.R(compiledFieldC135, compiledFieldC136, compiledFieldC137, compiledFieldC138, compiledFieldC139, compiledFieldC140, compiledFieldC141, compiledFieldC142, compiledFieldC143, compiledFieldC144, compiledFieldC145, compiledFieldC146, compiledFieldC147, builder90.c());
        O0 = listR90;
        ObjectType objectType23 = ProductList.f11749a;
        CompiledField.Builder builder91 = new CompiledField.Builder("productList", CompiledGraphQL.b(ProductList.Companion.a()));
        new CompiledArgument.Builder(Query.F0);
        builder91.b(CollectionsKt.Q(CompiledArgument.Builder.a()));
        builder91.e(listR90);
        P0 = CollectionsKt.Q(builder91.c());
    }
}
