package com.woolworths.shop.product.details.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.sdui.shop.fragment.selections.BasicCoreRowSelections;
import au.com.woolworths.sdui.shop.fragment.selections.CoreRowUISelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.CardHeight;
import au.com.woolworths.shop.graphql.type.ContentCta;
import au.com.woolworths.shop.graphql.type.CoreAlertStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerUI;
import au.com.woolworths.shop.graphql.type.CoreInsetAlertUI;
import au.com.woolworths.shop.graphql.type.CoreRowUI;
import au.com.woolworths.shop.graphql.type.CouponBanner;
import au.com.woolworths.shop.graphql.type.CouponBannerColorTheme;
import au.com.woolworths.shop.graphql.type.CouponBannerTermsAndConditions;
import au.com.woolworths.shop.graphql.type.GenericPageFeedItem;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLFloat;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.HorizontalList;
import au.com.woolworths.shop.graphql.type.HorizontalListItem;
import au.com.woolworths.shop.graphql.type.IconAsset;
import au.com.woolworths.shop.graphql.type.ImageContent;
import au.com.woolworths.shop.graphql.type.InfoSectionFooter;
import au.com.woolworths.shop.graphql.type.InfoSectionItem;
import au.com.woolworths.shop.graphql.type.ParagraphTextItem;
import au.com.woolworths.shop.graphql.type.ParagraphTextItemType;
import au.com.woolworths.shop.graphql.type.ProductCard;
import au.com.woolworths.shop.graphql.type.ProductDetailsCoreRowDetails;
import au.com.woolworths.shop.graphql.type.ProductDetailsPage;
import au.com.woolworths.shop.graphql.type.ProductDetailsPageFooter;
import au.com.woolworths.shop.graphql.type.ProductDetailsRowAccordionExpandedContent;
import au.com.woolworths.shop.graphql.type.ProductDetailsRowUILinkContent;
import au.com.woolworths.shop.graphql.type.ProductImage;
import au.com.woolworths.shop.graphql.type.ProductRatingsAndReviewsSummary;
import au.com.woolworths.shop.graphql.type.ProductRatingsAndReviewsSummaryCta;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.RatingsAndReviewsPreviewResponse;
import au.com.woolworths.shop.graphql.type.RatingsAndReviewsPreviewSections;
import au.com.woolworths.shop.graphql.type.RoundelImage;
import au.com.woolworths.shop.graphql.type.RoundelImagePriority;
import au.com.woolworths.shop.graphql.type.TealiumAnalytics;
import au.com.woolworths.shop.graphql.type.TextWithAlt;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledArgumentDefinition;
import com.apollographql.apollo.api.CompiledCondition;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import com.woolworths.shop.productcard.data.fragment.selections.ProductTileSelections;
import fragment.selections.RatingsAndReviewsPreviewCtaSelections;
import fragment.selections.RatingsAndReviewsPreviewHeaderSelections;
import fragment.selections.RatingsAndReviewsRatingsDetailsSelections;
import fragment.selections.RatingsAndReviewsReviewDetailsSelections;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/product/details/selections/ProductDetailsPageQuerySelections;", "", "product-details_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class ProductDetailsPageQuerySelections {
    public static final List A;
    public static final List A0;
    public static final List B;
    public static final List B0;
    public static final List C;
    public static final List C0;
    public static final List D;
    public static final List D0;
    public static final List E;
    public static final List E0;
    public static final List F;
    public static final List F0;
    public static final List G;
    public static final List G0;
    public static final List H;
    public static final List H0;
    public static final List I;
    public static final List I0;
    public static final List J;
    public static final List J0;
    public static final List K;
    public static final List K0;
    public static final List L;
    public static final List L0;
    public static final List M;
    public static final List M0;
    public static final List N;
    public static final List N0;
    public static final List O;
    public static final List O0;
    public static final List P;
    public static final List Q;
    public static final List R;
    public static final List S;
    public static final List T;
    public static final List U;
    public static final List V;
    public static final List W;
    public static final List X;
    public static final List Y;
    public static final List Z;

    /* renamed from: a, reason: collision with root package name */
    public static final List f23602a;
    public static final List a0;
    public static final List b;
    public static final List b0;
    public static final List c;
    public static final List c0;
    public static final List d;
    public static final List d0;
    public static final List e;
    public static final List e0;
    public static final List f;
    public static final List f0;
    public static final List g;
    public static final List g0;
    public static final List h;
    public static final List h0;
    public static final List i;
    public static final List i0;
    public static final List j;
    public static final List j0;
    public static final List k;
    public static final List k0;
    public static final List l;
    public static final List l0;
    public static final List m;
    public static final List m0;
    public static final List n;
    public static final List n0;
    public static final List o;
    public static final List o0;
    public static final List p;
    public static final List p0;
    public static final List q;
    public static final List q0;
    public static final List r;
    public static final List r0;
    public static final List s;
    public static final List s0;
    public static final List t;
    public static final List t0;
    public static final List u;
    public static final List u0;
    public static final List v;
    public static final List v0;
    public static final List w;
    public static final List w0;
    public static final List x;
    public static final List x0;
    public static final List y;
    public static final List y0;
    public static final List z;
    public static final List z0;

    static {
        List listR = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        f23602a = listR;
        List listR2 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        b = listR2;
        List listR3 = CollectionsKt.R(new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("accessibilityLabel", GraphQLString.Companion.a()).c());
        c = listR3;
        CouponBannerColorTheme.e.getClass();
        CompiledField compiledFieldC = new CompiledField.Builder("couponBannerColorTheme", CompiledGraphQL.b(CouponBannerColorTheme.f)).c();
        CompiledField compiledFieldC2 = new CompiledField.Builder("couponBannerCouponCode", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC3 = new CompiledField.Builder("couponBannerDescription", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("couponBannerMinimumSpend", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC5 = new CompiledField.Builder("couponBannerCouponCodeAccessibilityLabel", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC6 = new CompiledField.Builder("couponBannerDescriptionAccessibilityLabel", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder = new CompiledField.Builder("couponBannerTermsAndConditions", CompiledGraphQL.b(CouponBannerTermsAndConditions.f11296a));
        builder.e(listR3);
        List listR4 = CollectionsKt.R(compiledFieldC, compiledFieldC2, compiledFieldC3, compiledFieldC4, compiledFieldC5, compiledFieldC6, builder.c());
        d = listR4;
        ObjectType objectType = CouponBanner.f11295a;
        CompiledField.Builder builder2 = new CompiledField.Builder("productDetailsCouponBanner", CouponBanner.Companion.a());
        builder2.e(listR4);
        List listQ = CollectionsKt.Q(builder2.c());
        e = listQ;
        CompiledField compiledFieldC7 = new CompiledField.Builder("image", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC8 = new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CardHeight.e.getClass();
        List listR5 = CollectionsKt.R(compiledFieldC7, compiledFieldC8, new CompiledField.Builder("cardHeight", CompiledGraphQL.b(CardHeight.Companion.a())).c(), new CompiledField.Builder("link", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("analytics", TealiumAnalytics.Companion.a()).c());
        f = listR5;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        g = listQ2;
        CompiledField compiledFieldC9 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder3.b(listQ2);
        List listR6 = CollectionsKt.R(compiledFieldC9, builder3.a());
        h = listR6;
        CompiledField compiledFieldC10 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC11 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CoreBroadcastBannerStyle.e.getClass();
        CompiledField compiledFieldC12 = new CompiledField.Builder("style", CompiledGraphQL.b(CoreBroadcastBannerStyle.Companion.a())).c();
        UnionType unionType = IconAsset.f11477a;
        CompiledField.Builder builder4 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(IconAsset.Companion.a()));
        builder4.e(listR6);
        List listR7 = CollectionsKt.R(compiledFieldC10, compiledFieldC11, compiledFieldC12, builder4.c());
        i = listR7;
        List listR8 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        j = listR8;
        CompiledField compiledFieldC13 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        ActionType.e.getClass();
        CompiledField compiledFieldC14 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC15 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType2 = Analytics.f11028a;
        CompiledField.Builder builder5 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder5.e(listR8);
        List listR9 = CollectionsKt.R(compiledFieldC13, compiledFieldC14, compiledFieldC15, builder5.c());
        k = listR9;
        ObjectType objectType3 = CoreBroadcastBannerUI.f11286a;
        CompiledField.Builder builder6 = new CompiledField.Builder("broadcastBannerUI", CompiledGraphQL.b(CoreBroadcastBannerUI.Companion.a()));
        builder6.e(listR7);
        CompiledField compiledFieldC16 = builder6.c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("broadcastBannerActionLabel", GraphQLString.Companion.a()).c();
        ObjectType objectType4 = Action.f10997a;
        CompiledField.Builder builder7 = new CompiledField.Builder("broadcastBannerAction", Action.Companion.a());
        builder7.e(listR9);
        List listR10 = CollectionsKt.R(compiledFieldC16, compiledFieldC17, builder7.c());
        l = listR10;
        List listR11 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        m = listR11;
        List listR12 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        n = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        o = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        p = listR14;
        List listR15 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        q = listR15;
        CompiledField compiledFieldC18 = new CompiledField.Builder("largeUrl", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC19 = new CompiledField.Builder("altText", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder8 = new CompiledField.Builder("imageGalleryClickAnalytics", Analytics.Companion.a());
        builder8.e(listR11);
        CompiledField compiledFieldC20 = builder8.c();
        CompiledField.Builder builder9 = new CompiledField.Builder("imageGalleryScrollAnalytics", Analytics.Companion.a());
        builder9.e(listR12);
        CompiledField compiledFieldC21 = builder9.c();
        CompiledField.Builder builder10 = new CompiledField.Builder("imageGalleryCloseAnalytics", Analytics.Companion.a());
        builder10.e(listR13);
        CompiledField compiledFieldC22 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("imageGalleryThumbnailClickAnalytics", Analytics.Companion.a());
        builder11.e(listR14);
        CompiledField compiledFieldC23 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("productDetailsThumbnailClickAnalytics", Analytics.Companion.a());
        builder12.e(listR15);
        List listR16 = CollectionsKt.R(compiledFieldC18, compiledFieldC19, compiledFieldC20, compiledFieldC21, compiledFieldC22, compiledFieldC23, builder12.c());
        r = listR16;
        CompiledField compiledFieldC24 = new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC25 = new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        RoundelImagePriority.e.getClass();
        List listR17 = CollectionsKt.R(compiledFieldC24, compiledFieldC25, new CompiledField.Builder("priority", CompiledGraphQL.b(RoundelImagePriority.f)).c());
        s = listR17;
        CompiledField.Builder builder13 = new CompiledField.Builder("productImages", a.f(ProductImage.f11745a));
        builder13.e(listR16);
        CompiledField compiledFieldC26 = builder13.c();
        CompiledField.Builder builder14 = new CompiledField.Builder("roundelImages", a.f(RoundelImage.f11886a));
        builder14.e(listR17);
        List listR18 = CollectionsKt.R(compiledFieldC26, builder14.c());
        t = listR18;
        CompiledField compiledFieldC27 = new CompiledField.Builder("title", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC28 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, GraphQLString.Companion.a()).c();
        CoreAlertStyle.e.getClass();
        List listR19 = CollectionsKt.R(compiledFieldC27, compiledFieldC28, new CompiledField.Builder("style", CompiledGraphQL.b(CoreAlertStyle.f)).c());
        u = listR19;
        List listR20 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        v = listR20;
        CompiledField compiledFieldC29 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC30 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField compiledFieldC31 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder15 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder15.e(listR20);
        List listR21 = CollectionsKt.R(compiledFieldC29, compiledFieldC30, compiledFieldC31, builder15.c());
        w = listR21;
        CompiledField.Builder builder16 = new CompiledField.Builder("insetAlertUI", CompiledGraphQL.b(CoreInsetAlertUI.f11291a));
        builder16.e(listR19);
        CompiledField compiledFieldC32 = builder16.c();
        CompiledField.Builder builder17 = new CompiledField.Builder("insetAlertAction", Action.Companion.a());
        builder17.e(listR21);
        List listR22 = CollectionsKt.R(compiledFieldC32, builder17.c(), new CompiledField.Builder("insetAlertActionLabel", GraphQLString.Companion.a()).c());
        x = listR22;
        List listR23 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        y = listR23;
        List listR24 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        z = listR24;
        List listR25 = CollectionsKt.R(new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("id", GraphQLString.Companion.a()).c());
        A = listR25;
        ObjectType objectType5 = TextWithAlt.f11967a;
        CompiledField.Builder builder18 = new CompiledField.Builder("ctaText", CompiledGraphQL.b(TextWithAlt.Companion.a()));
        builder18.e(listR24);
        CompiledField compiledFieldC33 = builder18.c();
        CompiledField.Builder builder19 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(Action.Companion.a()));
        builder19.e(listR25);
        List listR26 = CollectionsKt.R(compiledFieldC33, builder19.c());
        B = listR26;
        CompiledField compiledFieldC34 = new CompiledField.Builder("averageRatings", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c();
        CompiledField compiledFieldC35 = new CompiledField.Builder("displayRatings", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c();
        CompiledField compiledFieldC36 = new CompiledField.Builder("maximumRating", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField.Builder builder20 = new CompiledField.Builder("ratingText", CompiledGraphQL.b(TextWithAlt.Companion.a()));
        builder20.e(listR23);
        CompiledField compiledFieldC37 = builder20.c();
        CompiledField.Builder builder21 = new CompiledField.Builder("cta", ProductRatingsAndReviewsSummaryCta.f11767a);
        builder21.e(listR26);
        List listR27 = CollectionsKt.R(compiledFieldC34, compiledFieldC35, compiledFieldC36, compiledFieldC37, builder21.c());
        C = listR27;
        CompiledField compiledFieldC38 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("ProductRatingsAndReviewsSummary", CollectionsKt.Q("ProductRatingsAndReviewsSummary"));
        builder22.b(listR27);
        List listR28 = CollectionsKt.R(compiledFieldC38, builder22.a());
        D = listR28;
        List listR29 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        E = listR29;
        CompiledField compiledFieldC39 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder23.b(listR29);
        List listR30 = CollectionsKt.R(compiledFieldC39, builder23.a());
        F = listR30;
        ObjectType objectType6 = ProductRatingsAndReviewsSummary.f11766a;
        CompiledField compiledFieldE = com.google.android.gms.common.api.internal.a.e("isRatingsAndReviewsSummaryEnabled", false, new CompiledField.Builder("ratingsAndReviewsSummary", ProductRatingsAndReviewsSummary.Companion.a()), listR28);
        ObjectType objectType7 = ProductCard.f11717a;
        CompiledField.Builder builder24 = new CompiledField.Builder("product", CompiledGraphQL.b(ProductCard.Companion.a()));
        builder24.e(listR30);
        List listR31 = CollectionsKt.R(compiledFieldE, builder24.c());
        G = listR31;
        List listR32 = CollectionsKt.R(new CompiledField.Builder("url", GraphQLString.Companion.a()).c(), new CompiledField.Builder(TextBundle.TEXT_ENTRY, GraphQLString.Companion.a()).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        H = listR32;
        CompiledField.Builder builder25 = new CompiledField.Builder("countryOfOrigin", ImageContent.f11485a);
        builder25.e(listR32);
        List listQ3 = CollectionsKt.Q(builder25.c());
        I = listQ3;
        List listR33 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        J = listR33;
        List listR34 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        K = listR34;
        List listQ4 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        L = listQ4;
        List listQ5 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        M = listQ5;
        CompiledField compiledFieldC40 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder26.b(listQ4);
        CompiledFragment compiledFragmentA = builder26.a();
        CompiledFragment.Builder builder27 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder27.b(listQ5);
        List listR35 = CollectionsKt.R(compiledFieldC40, compiledFragmentA, builder27.a());
        N = listR35;
        CompiledField.Builder builder28 = new CompiledField.Builder("leadingAsset", IconAsset.Companion.a());
        builder28.e(listR35);
        List listR36 = CollectionsKt.R(builder28.c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, GraphQLString.Companion.a()).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        O = listR36;
        CompiledField compiledFieldC41 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC42 = new CompiledField.Builder("content", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ParagraphTextItemType.e.getClass();
        List listR37 = CollectionsKt.R(compiledFieldC41, compiledFieldC42, new CompiledField.Builder("type", CompiledGraphQL.b(ParagraphTextItemType.Companion.a())).c());
        P = listR37;
        List listR38 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("content", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("type", CompiledGraphQL.b(ParagraphTextItemType.Companion.a())).c());
        Q = listR38;
        CompiledField compiledFieldC43 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder29 = new CompiledFragment.Builder("ParagraphTextItem", CollectionsKt.Q("ParagraphTextItem"));
        builder29.b(listR38);
        List listR39 = CollectionsKt.R(compiledFieldC43, builder29.a());
        R = listR39;
        List listR40 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        S = listR40;
        CompiledField compiledFieldC44 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC45 = new CompiledField.Builder("url", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder30 = new CompiledField.Builder("onCtaClickAnalytics", Analytics.Companion.a());
        builder30.e(listR40);
        List listR41 = CollectionsKt.R(compiledFieldC44, compiledFieldC45, builder30.c());
        T = listR41;
        CompiledField compiledFieldC46 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder31 = new CompiledFragment.Builder("ContentCta", CollectionsKt.Q("ContentCta"));
        builder31.b(listR41);
        List listR42 = CollectionsKt.R(compiledFieldC46, builder31.a());
        U = listR42;
        List listR43 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        V = listR43;
        CompiledField compiledFieldC47 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder32 = new CompiledFragment.Builder("ProductTile", CollectionsKt.Q("ProductTile"));
        List list = ProductTileSelections.J;
        builder32.b(list);
        List listR44 = CollectionsKt.R(compiledFieldC47, builder32.a());
        W = listR44;
        List listR45 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.i("isProductTileUpliftEnabled", true, new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard")), listR43), d.i("isProductTileUpliftEnabled", false, new CompiledFragment.Builder("ProductTile", CollectionsKt.Q("ProductTile")), listR44));
        X = listR45;
        CompiledField compiledFieldC48 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC49 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC50 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC51 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC52 = new CompiledField.Builder("deepLink", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC53 = new CompiledField.Builder("actionPath", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder33 = new CompiledField.Builder("nodeId", GraphQLString.Companion.a());
        builder33.d(CollectionsKt.Q(new CompiledCondition("isProductCarouselLazyLoadingEnabled", false)));
        CompiledField compiledFieldC54 = builder33.c();
        UnionType unionType2 = HorizontalListItem.f11475a;
        CompiledField.Builder builder34 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder34.e(listR45);
        List listR46 = CollectionsKt.R(compiledFieldC48, compiledFieldC49, compiledFieldC50, compiledFieldC51, compiledFieldC52, compiledFieldC53, compiledFieldC54, builder34.c());
        Y = listR46;
        CompiledField compiledFieldC55 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder35 = new CompiledFragment.Builder("HorizontalList", CollectionsKt.Q("HorizontalList"));
        builder35.b(listR46);
        List listR47 = CollectionsKt.R(compiledFieldC55, builder35.a());
        Z = listR47;
        CompiledField compiledFieldC56 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType8 = ParagraphTextItem.f11681a;
        CompiledField.Builder builder36 = new CompiledField.Builder("productDetailsRowAccordionProductListTextItem", CompiledGraphQL.b(ParagraphTextItem.Companion.a()));
        builder36.e(listR39);
        CompiledField compiledFieldC57 = builder36.c();
        ObjectType objectType9 = ContentCta.f11282a;
        CompiledField.Builder builder37 = new CompiledField.Builder("productDetailsRowAccordionProductListCta", CompiledGraphQL.b(ContentCta.Companion.a()));
        builder37.e(listR42);
        CompiledField compiledFieldC58 = builder37.c();
        CompiledField.Builder builder38 = new CompiledField.Builder("productDetailsRowAccordionProductList", HorizontalList.f11472a);
        builder38.e(listR47);
        List listR48 = CollectionsKt.R(compiledFieldC56, compiledFieldC57, compiledFieldC58, builder38.c());
        a0 = listR48;
        CompiledField compiledFieldC59 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder39 = new CompiledFragment.Builder("ParagraphTextItem", CollectionsKt.Q("ParagraphTextItem"));
        builder39.b(listR37);
        CompiledFragment compiledFragmentA2 = builder39.a();
        CompiledFragment.Builder builder40 = new CompiledFragment.Builder("ProductDetailsRowAccordionProductList", CollectionsKt.Q("ProductDetailsRowAccordionProductList"));
        builder40.b(listR48);
        List listR49 = CollectionsKt.R(compiledFieldC59, compiledFragmentA2, builder40.a());
        b0 = listR49;
        CompiledField.Builder builder41 = new CompiledField.Builder("openActionAnalytics", Analytics.Companion.a());
        builder41.e(listR33);
        CompiledField compiledFieldC60 = builder41.c();
        CompiledField.Builder builder42 = new CompiledField.Builder("closeActionAnalytics", Analytics.Companion.a());
        builder42.e(listR34);
        CompiledField compiledFieldC61 = builder42.c();
        ObjectType objectType10 = CoreRowUI.f11293a;
        CompiledField.Builder builder43 = new CompiledField.Builder("rowUI", CompiledGraphQL.b(objectType10));
        builder43.e(listR36);
        CompiledField compiledFieldC62 = builder43.c();
        CompiledField compiledFieldC63 = new CompiledField.Builder("isExpanded", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC64 = new CompiledField.Builder("hasTopSeparator", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        UnionType unionType3 = ProductDetailsRowAccordionExpandedContent.f11734a;
        CompiledField.Builder builder44 = new CompiledField.Builder("expandedContent", CompiledGraphQL.b(ProductDetailsRowAccordionExpandedContent.Companion.a()));
        builder44.e(listR49);
        List listR50 = CollectionsKt.R(compiledFieldC60, compiledFieldC61, compiledFieldC62, compiledFieldC63, compiledFieldC64, builder44.c());
        c0 = listR50;
        List listQ6 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        d0 = listQ6;
        List listQ7 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        e0 = listQ7;
        CompiledField compiledFieldC65 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder45 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder45.b(listQ6);
        CompiledFragment compiledFragmentA3 = builder45.a();
        CompiledFragment.Builder builder46 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder46.b(listQ7);
        List listR51 = CollectionsKt.R(compiledFieldC65, compiledFragmentA3, builder46.a());
        f0 = listR51;
        CompiledField.Builder builder47 = new CompiledField.Builder("leadingAsset", IconAsset.Companion.a());
        builder47.e(listR51);
        List listR52 = CollectionsKt.R(builder47.c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, GraphQLString.Companion.a()).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        g0 = listR52;
        List listR53 = CollectionsKt.R(new CompiledField.Builder("content", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("type", CompiledGraphQL.b(ParagraphTextItemType.Companion.a())).c());
        h0 = listR53;
        CompiledField.Builder builder48 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a()));
        builder48.a("productNutritionTitle");
        List listR54 = CollectionsKt.R(builder48.c(), new CompiledField.Builder("servingsPerPack", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("servingSize", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("servingsHeader", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c(), new CompiledField.Builder("servingsRow", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c(), new CompiledField.Builder("bottomCaption", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("tableHeaderRow", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c(), new CompiledField.Builder("tableRows", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))))).c());
        i0 = listR54;
        List listR55 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        j0 = listR55;
        List listR56 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("linkUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        k0 = listR56;
        CompiledField compiledFieldC66 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType11 = InfoSectionItem.f11497a;
        CompiledField.Builder builder49 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(InfoSectionItem.Companion.a()))));
        builder49.e(listR55);
        CompiledField compiledFieldC67 = builder49.c();
        ObjectType objectType12 = InfoSectionFooter.f11496a;
        CompiledField.Builder builder50 = new CompiledField.Builder("footer", InfoSectionFooter.Companion.a());
        builder50.e(listR56);
        List listR57 = CollectionsKt.R(compiledFieldC66, compiledFieldC67, builder50.c());
        l0 = listR57;
        CompiledField compiledFieldC68 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder51 = new CompiledFragment.Builder("ParagraphTextItem", CollectionsKt.Q("ParagraphTextItem"));
        builder51.b(listR53);
        CompiledFragment compiledFragmentA4 = builder51.a();
        CompiledFragment.Builder builder52 = new CompiledFragment.Builder("ProductNutritionInfo", CollectionsKt.Q("ProductNutritionInfo"));
        builder52.b(listR54);
        List listR58 = CollectionsKt.R(compiledFieldC68, compiledFragmentA4, builder52.a(), d.i("isEverydayMarketPdpUpliftEnabled", false, new CompiledFragment.Builder("InfoSection", CollectionsKt.Q("InfoSection")), listR57));
        m0 = listR58;
        List listR59 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        n0 = listR59;
        CompiledField.Builder builder53 = new CompiledField.Builder("rowUI", CompiledGraphQL.b(objectType10));
        builder53.e(listR52);
        CompiledField compiledFieldC69 = builder53.c();
        UnionType unionType4 = ProductDetailsRowUILinkContent.f11737a;
        CompiledField.Builder builder54 = new CompiledField.Builder("linkContent", CompiledGraphQL.b(ProductDetailsRowUILinkContent.Companion.a()));
        builder54.e(listR58);
        CompiledField compiledFieldC70 = builder54.c();
        CompiledField compiledFieldC71 = new CompiledField.Builder("hasTopSeparator", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField.Builder builder55 = new CompiledField.Builder("openActionAnalytics", Analytics.Companion.a());
        builder55.e(listR59);
        List listR60 = CollectionsKt.R(compiledFieldC69, compiledFieldC70, compiledFieldC71, builder55.c());
        o0 = listR60;
        List listR61 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.h(new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"))));
        p0 = listR61;
        CompiledField compiledFieldC72 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder56 = new CompiledFragment.Builder("ProductTile", CollectionsKt.Q("ProductTile"));
        builder56.b(list);
        List listR62 = CollectionsKt.R(compiledFieldC72, builder56.a());
        q0 = listR62;
        List listR63 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.i("isProductTileUpliftEnabled", true, new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard")), listR61), d.i("isProductTileUpliftEnabled", false, new CompiledFragment.Builder("ProductTile", CollectionsKt.Q("ProductTile")), listR62));
        r0 = listR63;
        CompiledField compiledFieldC73 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC74 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC75 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC76 = new CompiledField.Builder("actionTitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC77 = new CompiledField.Builder("deepLink", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC78 = new CompiledField.Builder("actionPath", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder57 = new CompiledField.Builder("nodeId", GraphQLString.Companion.a());
        builder57.d(CollectionsKt.Q(new CompiledCondition("isProductCarouselLazyLoadingEnabled", false)));
        CompiledField compiledFieldC79 = builder57.c();
        CompiledField.Builder builder58 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(HorizontalListItem.Companion.a()))));
        builder58.e(listR63);
        List listR64 = CollectionsKt.R(compiledFieldC73, compiledFieldC74, compiledFieldC75, compiledFieldC76, compiledFieldC77, compiledFieldC78, compiledFieldC79, builder58.c());
        s0 = listR64;
        CompiledField compiledFieldC80 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder59 = new CompiledFragment.Builder("RatingsAndReviewsPreviewHeader", CollectionsKt.Q("RatingsAndReviewsPreviewHeader"));
        builder59.b(RatingsAndReviewsPreviewHeaderSelections.f23834a);
        List listR65 = CollectionsKt.R(compiledFieldC80, builder59.a());
        t0 = listR65;
        CompiledField compiledFieldC81 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder60 = new CompiledFragment.Builder("RatingsAndReviewsRatingsDetails", CollectionsKt.Q("RatingsAndReviewsRatingsDetails"));
        builder60.b(RatingsAndReviewsRatingsDetailsSelections.l);
        List listR66 = CollectionsKt.R(compiledFieldC81, builder60.a());
        u0 = listR66;
        CompiledField compiledFieldC82 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder61 = new CompiledFragment.Builder("RatingsAndReviewsReviewDetails", CollectionsKt.Q("RatingsAndReviewsReviewDetails"));
        builder61.b(RatingsAndReviewsReviewDetailsSelections.h);
        List listR67 = CollectionsKt.R(compiledFieldC82, builder61.a());
        v0 = listR67;
        CompiledField compiledFieldC83 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder62 = new CompiledFragment.Builder("RatingsAndReviewsPreviewCta", CollectionsKt.Q("RatingsAndReviewsPreviewCta"));
        builder62.b(RatingsAndReviewsPreviewCtaSelections.c);
        List listR68 = CollectionsKt.R(compiledFieldC83, builder62.a());
        w0 = listR68;
        CompiledField compiledFieldC84 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder63 = new CompiledFragment.Builder("RatingsAndReviewsPreviewHeader", CollectionsKt.Q("RatingsAndReviewsPreviewHeader"));
        builder63.b(listR65);
        CompiledFragment compiledFragmentA5 = builder63.a();
        CompiledFragment.Builder builder64 = new CompiledFragment.Builder("RatingsAndReviewsRatingsDetails", CollectionsKt.Q("RatingsAndReviewsRatingsDetails"));
        builder64.b(listR66);
        CompiledFragment compiledFragmentA6 = builder64.a();
        CompiledFragment.Builder builder65 = new CompiledFragment.Builder("RatingsAndReviewsReviewDetails", CollectionsKt.Q("RatingsAndReviewsReviewDetails"));
        builder65.b(listR67);
        CompiledFragment compiledFragmentA7 = builder65.a();
        CompiledFragment.Builder builder66 = new CompiledFragment.Builder("RatingsAndReviewsPreviewCta", CollectionsKt.Q("RatingsAndReviewsPreviewCta"));
        builder66.b(listR68);
        List listR69 = CollectionsKt.R(compiledFieldC84, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, builder66.a());
        x0 = listR69;
        CompiledField.Builder builder67 = new CompiledField.Builder("sections", d.j(RatingsAndReviewsPreviewSections.f11818a));
        builder67.e(listR69);
        List listQ8 = CollectionsKt.Q(builder67.c());
        y0 = listQ8;
        CompiledField.Builder builder68 = new CompiledField.Builder("ratingsAndReviewsPreview", RatingsAndReviewsPreviewResponse.f11817a);
        builder68.e(listQ8);
        List listQ9 = CollectionsKt.Q(builder68.c());
        z0 = listQ9;
        CompiledField compiledFieldC85 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder69 = new CompiledFragment.Builder("BasicCoreRow", CollectionsKt.Q("BasicCoreRow"));
        builder69.b(BasicCoreRowSelections.a());
        List listR70 = CollectionsKt.R(compiledFieldC85, builder69.a());
        A0 = listR70;
        CompiledField compiledFieldC86 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder70 = new CompiledFragment.Builder("CoreRowUI", CollectionsKt.Q("CoreRowUI"));
        builder70.b(CoreRowUISelections.a());
        List listR71 = CollectionsKt.R(compiledFieldC86, builder70.a());
        B0 = listR71;
        CompiledField compiledFieldC87 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder71 = new CompiledFragment.Builder("BasicCoreRow", CollectionsKt.Q("BasicCoreRow"));
        builder71.b(listR70);
        CompiledFragment compiledFragmentA8 = builder71.a();
        CompiledFragment.Builder builder72 = new CompiledFragment.Builder("CoreRowUI", CollectionsKt.Q("CoreRowUI"));
        builder72.b(listR71);
        List listR72 = CollectionsKt.R(compiledFieldC87, compiledFragmentA8, builder72.a());
        C0 = listR72;
        CompiledField compiledFieldC88 = new CompiledField.Builder("hasTopSeparator", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        UnionType unionType5 = ProductDetailsCoreRowDetails.f11723a;
        CompiledField.Builder builder73 = new CompiledField.Builder("rowDetails", CompiledGraphQL.b(ProductDetailsCoreRowDetails.Companion.a()));
        builder73.e(listR72);
        List listR73 = CollectionsKt.R(compiledFieldC88, builder73.c());
        D0 = listR73;
        List listR74 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        E0 = listR74;
        CompiledField compiledFieldC89 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC90 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC91 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField.Builder builder74 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder74.e(listR74);
        List listR75 = CollectionsKt.R(compiledFieldC89, compiledFieldC90, compiledFieldC91, builder74.c());
        F0 = listR75;
        CompiledField compiledFieldC92 = new CompiledField.Builder("chatEntryCardTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC93 = new CompiledField.Builder("chatEntryCardShowBeta", GraphQLBoolean.Companion.a()).c();
        CompiledField compiledFieldC94 = new CompiledField.Builder("chatEntryCardSuggestedPrompts", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        CompiledField.Builder builder75 = new CompiledField.Builder("chatEntryCardAction", CompiledGraphQL.b(Action.Companion.a()));
        builder75.e(listR75);
        List listR76 = CollectionsKt.R(compiledFieldC92, compiledFieldC93, compiledFieldC94, builder75.c());
        G0 = listR76;
        CompiledField compiledFieldC95 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment compiledFragmentI = d.i("isEverydayMarketPdpUpliftEnabled", false, new CompiledFragment.Builder("ProductDetailsCouponBanner", CollectionsKt.Q("ProductDetailsCouponBanner")), listQ);
        CompiledFragment.Builder builder76 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder76.b(listR5);
        CompiledFragment compiledFragmentA9 = builder76.a();
        CompiledFragment.Builder builder77 = new CompiledFragment.Builder("BasicCoreBroadcastBanner", CollectionsKt.Q("BasicCoreBroadcastBanner"));
        builder77.b(listR10);
        CompiledFragment compiledFragmentA10 = builder77.a();
        CompiledFragment.Builder builder78 = new CompiledFragment.Builder("ProductDetailsImages", CollectionsKt.Q("ProductDetailsImages"));
        builder78.b(listR18);
        CompiledFragment compiledFragmentA11 = builder78.a();
        CompiledFragment.Builder builder79 = new CompiledFragment.Builder("BasicInsetAlert", CollectionsKt.Q("BasicInsetAlert"));
        builder79.b(listR22);
        CompiledFragment compiledFragmentA12 = builder79.a();
        CompiledFragment.Builder builder80 = new CompiledFragment.Builder("ProductDetailsProductPanel", CollectionsKt.Q("ProductDetailsProductPanel"));
        builder80.b(listR31);
        CompiledFragment compiledFragmentA13 = builder80.a();
        CompiledFragment.Builder builder81 = new CompiledFragment.Builder("ProductOriginAndHealthInfo", CollectionsKt.Q("ProductOriginAndHealthInfo"));
        builder81.b(listQ3);
        CompiledFragment compiledFragmentA14 = builder81.a();
        CompiledFragment.Builder builder82 = new CompiledFragment.Builder("ProductDetailsRowAccordion", CollectionsKt.Q("ProductDetailsRowAccordion"));
        builder82.b(listR50);
        CompiledFragment compiledFragmentA15 = builder82.a();
        CompiledFragment.Builder builder83 = new CompiledFragment.Builder("ProductDetailsRowLink", CollectionsKt.Q("ProductDetailsRowLink"));
        builder83.b(listR60);
        CompiledFragment compiledFragmentA16 = builder83.a();
        CompiledFragment.Builder builder84 = new CompiledFragment.Builder("HorizontalList", CollectionsKt.Q("HorizontalList"));
        builder84.b(listR64);
        List listR77 = CollectionsKt.R(compiledFieldC95, compiledFragmentI, compiledFragmentA9, compiledFragmentA10, compiledFragmentA11, compiledFragmentA12, compiledFragmentA13, compiledFragmentA14, compiledFragmentA15, compiledFragmentA16, builder84.a(), d.i("isRatingsAndReviewsPreviewEnabled", false, new CompiledFragment.Builder("ProductDetailsRatingsAndReviewsPreview", CollectionsKt.Q("ProductDetailsRatingsAndReviewsPreview")), listQ9), d.i("isEverydayMarketPdpUpliftEnabled", false, new CompiledFragment.Builder("ProductDetailsCoreRow", CollectionsKt.Q("ProductDetailsCoreRow")), listR73), d.i("includeChatEntryCard", false, new CompiledFragment.Builder("ChatEntryCardV3", CollectionsKt.Q("ChatEntryCardV3")), listR76));
        H0 = listR77;
        List listR78 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        I0 = listR78;
        List listR79 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        J0 = listR79;
        CompiledField compiledFieldC96 = new CompiledField.Builder("id", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC97 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC98 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.Companion.a())).c();
        CompiledField.Builder builder85 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder85.e(listR79);
        List listR80 = CollectionsKt.R(compiledFieldC96, compiledFieldC97, compiledFieldC98, builder85.c());
        K0 = listR80;
        CompiledField compiledFieldC99 = new CompiledField.Builder("altText", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC100 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC101 = new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField.Builder builder86 = new CompiledField.Builder("buttonAction", Action.Companion.a());
        builder86.e(listR80);
        CompiledField compiledFieldC102 = builder86.c();
        CompiledField compiledFieldC103 = new CompiledField.Builder("buttonId", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC104 = new CompiledField.Builder("iconUrl", GraphQLString.Companion.a()).c();
        ButtonStyle.e.getClass();
        List listR81 = CollectionsKt.R(compiledFieldC99, compiledFieldC100, compiledFieldC101, compiledFieldC102, compiledFieldC103, compiledFieldC104, new CompiledField.Builder("style", ButtonStyle.Companion.a()).c());
        L0 = listR81;
        CompiledField.Builder builder87 = new CompiledField.Builder("footerMessage", TextWithAlt.Companion.a());
        builder87.e(listR78);
        CompiledField compiledFieldC105 = builder87.c();
        ObjectType objectType13 = Button.f11080a;
        CompiledField.Builder builder88 = new CompiledField.Builder("productDetailsActions", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(Button.Companion.a()))));
        builder88.e(listR81);
        List listR82 = CollectionsKt.R(compiledFieldC105, builder88.c());
        M0 = listR82;
        CompiledField.Builder builder89 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder89.e(listR);
        CompiledField compiledFieldC106 = builder89.c();
        CompiledField.Builder builder90 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder90.e(listR2);
        CompiledField compiledFieldC107 = builder90.c();
        CompiledField.Builder builder91 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(GenericPageFeedItem.f11427a)));
        builder91.e(listR77);
        CompiledField compiledFieldC108 = builder91.c();
        ObjectType objectType14 = ProductDetailsPageFooter.f11729a;
        CompiledField.Builder builder92 = new CompiledField.Builder("footer", ProductDetailsPageFooter.Companion.a());
        builder92.e(listR82);
        List listR83 = CollectionsKt.R(compiledFieldC106, compiledFieldC107, compiledFieldC108, builder92.c());
        N0 = listR83;
        ObjectType objectType15 = ProductDetailsPage.f11728a;
        CompiledField.Builder builder93 = new CompiledField.Builder("productDetailsPage", CompiledGraphQL.b(ProductDetailsPage.Companion.a()));
        CompiledArgumentDefinition compiledArgumentDefinition = Query.f11808a;
        new CompiledArgument.Builder(Query.Companion.f());
        builder93.b(CollectionsKt.Q(CompiledArgument.Builder.a()));
        builder93.e(listR83);
        O0 = CollectionsKt.Q(builder93.c());
    }
}
