package com.woolworths.dynamic.page.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.sdui.shop.fragment.selections.AnalyticsFieldsSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.CampaignCard;
import au.com.woolworths.shop.graphql.type.CategoryTile;
import au.com.woolworths.shop.graphql.type.DynamicPage;
import au.com.woolworths.shop.graphql.type.DynamicPageAction;
import au.com.woolworths.shop.graphql.type.DynamicPageBottomSheetFeedItems;
import au.com.woolworths.shop.graphql.type.DynamicPageBottomSheetTypes;
import au.com.woolworths.shop.graphql.type.DynamicPageFeedItem;
import au.com.woolworths.shop.graphql.type.DynamicPageFooterSection;
import au.com.woolworths.shop.graphql.type.DynamicPageHeaderSection;
import au.com.woolworths.shop.graphql.type.FullWidthCampaignCard;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.QuickLinkCard;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.ObjectType;
import com.salesforce.marketingcloud.UrlHandler;
import com.woolworths.dynamic.page.fragment.selections.CampaignCardSelections;
import com.woolworths.dynamic.page.fragment.selections.CampaignCopySelections;
import com.woolworths.dynamic.page.fragment.selections.CampaignTermsAndConditionsSelections;
import com.woolworths.dynamic.page.fragment.selections.ContentListSelections;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/dynamic/page/selections/DynamicPageQuerySelections;", "", "dynamic-page_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes2.dex */
public final class DynamicPageQuerySelections {
    public static final List A;
    public static final List B;

    /* renamed from: a, reason: collision with root package name */
    public static final List f19302a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        List listR = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g("imageUrl", customScalarType), d.g("imageAltText", customScalarType), d.g("shareUrl", customScalarType));
        f19302a = listR;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("CampaignCopy", CollectionsKt.Q("CampaignCopy"));
        List list = CampaignCopySelections.f19299a;
        builder.b(list);
        List listR2 = CollectionsKt.R(compiledFieldC, builder.a());
        b = listR2;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("ContentList", CollectionsKt.Q("ContentList"));
        List list2 = ContentListSelections.d;
        builder2.b(list2);
        List listR3 = CollectionsKt.R(compiledFieldC2, builder2.a());
        c = listR3;
        CompiledField compiledFieldC3 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("CampaignTermsAndConditions", CollectionsKt.Q("CampaignTermsAndConditions"));
        List list3 = CampaignTermsAndConditionsSelections.f19300a;
        builder3.b(list3);
        List listR4 = CollectionsKt.R(compiledFieldC3, builder3.a());
        d = listR4;
        CompiledField compiledFieldC4 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("CampaignCardBase", CollectionsKt.R("CampaignCard", "FullWidthCampaignCard"));
        List list4 = CampaignCardSelections.f19298a;
        builder4.b(list4);
        List listR5 = CollectionsKt.R(compiledFieldC4, builder4.a());
        e = listR5;
        CompiledField compiledFieldG = d.g("campaignCardCarouselTitle", customScalarType);
        CompiledField.Builder builder5 = new CompiledField.Builder("campaignCards", a.f(CampaignCard.f11089a));
        builder5.e = listR5;
        List listR6 = CollectionsKt.R(compiledFieldG, builder5.c());
        f = listR6;
        CompiledField compiledFieldC5 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("CampaignCardBase", CollectionsKt.R("CampaignCard", "FullWidthCampaignCard"));
        builder6.d = list4;
        List listR7 = CollectionsKt.R(compiledFieldC5, builder6.a());
        g = listR7;
        CompiledField compiledFieldG2 = d.g("campaignCardListTitle", customScalarType);
        ObjectType objectType = FullWidthCampaignCard.f11422a;
        CompiledField.Builder builder7 = new CompiledField.Builder("campaignCards", a.f(objectType));
        builder7.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldG2, builder7.c());
        h = listR8;
        ActionType.e.getClass();
        List listR9 = CollectionsKt.R(new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.f)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c());
        i = listR9;
        CompiledField compiledFieldG3 = d.g("linkCardImage", customScalarType);
        CompiledField compiledFieldG4 = d.g("linkCardSubtitle", customScalarType);
        CompiledField compiledFieldC6 = new CompiledField.Builder("linkCardTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder8 = new CompiledField.Builder("linkCardAction", CompiledGraphQL.b(Action.f10997a));
        builder8.e = listR9;
        List listR10 = CollectionsKt.R(compiledFieldG3, compiledFieldG4, compiledFieldC6, builder8.c());
        j = listR10;
        CompiledField.Builder builder9 = new CompiledField.Builder("items", a.f(QuickLinkCard.f11810a));
        builder9.e = listR10;
        List listQ = CollectionsKt.Q(builder9.c());
        k = listQ;
        List listR11 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c(), d.g("imageAltText", customScalarType), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c());
        l = listR11;
        CompiledField compiledFieldG5 = d.g("categoryTileListTitle", customScalarType);
        CompiledField.Builder builder10 = new CompiledField.Builder("categoryTileListTiles", a.f(CategoryTile.f11172a));
        builder10.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldG5, builder10.c());
        m = listR12;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("CampaignCopy", CollectionsKt.Q("CampaignCopy"));
        builder11.d = listR2;
        CompiledFragment compiledFragmentA = builder11.a();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("ContentList", CollectionsKt.Q("ContentList"));
        builder12.d = listR3;
        CompiledFragment compiledFragmentA2 = builder12.a();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("CampaignTermsAndConditions", CollectionsKt.Q("CampaignTermsAndConditions"));
        builder13.d = listR4;
        CompiledFragment compiledFragmentA3 = builder13.a();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("CampaignCardCarousel", CollectionsKt.Q("CampaignCardCarousel"));
        builder14.d = listR6;
        CompiledFragment compiledFragmentA4 = builder14.a();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("CampaignCardList", CollectionsKt.Q("CampaignCardList"));
        builder15.d = listR8;
        CompiledFragment compiledFragmentA5 = builder15.a();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("QuickLinkList", CollectionsKt.Q("QuickLinkList"));
        builder16.d = listQ;
        CompiledFragment compiledFragmentA6 = builder16.a();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("CategoryTileList", CollectionsKt.Q("CategoryTileList"));
        builder17.d = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC7, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, builder17.a());
        n = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c());
        o = listR14;
        CompiledField.Builder builder18 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(DynamicPageAction.f11356a));
        builder18.e = listR14;
        List listQ2 = CollectionsKt.Q(builder18.c());
        p = listQ2;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        List list5 = AnalyticsFieldsSelections.b;
        builder19.b(list5);
        List listR15 = CollectionsKt.R(compiledFieldC8, builder19.a());
        q = listR15;
        CompiledField compiledFieldC9 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder20 = new CompiledFragment.Builder("CampaignCopy", CollectionsKt.Q("CampaignCopy"));
        builder20.d = list;
        List listR16 = CollectionsKt.R(compiledFieldC9, builder20.a());
        r = listR16;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("ContentList", CollectionsKt.Q("ContentList"));
        builder21.d = list2;
        List listR17 = CollectionsKt.R(compiledFieldC10, builder21.a());
        s = listR17;
        CompiledField compiledFieldC11 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("CampaignTermsAndConditions", CollectionsKt.Q("CampaignTermsAndConditions"));
        builder22.d = list3;
        List listR18 = CollectionsKt.R(compiledFieldC11, builder22.a());
        t = listR18;
        CompiledField compiledFieldC12 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("CampaignCardBase", CollectionsKt.R("CampaignCard", "FullWidthCampaignCard"));
        builder23.d = list4;
        List listR19 = CollectionsKt.R(compiledFieldC12, builder23.a());
        u = listR19;
        CompiledField compiledFieldG6 = d.g("campaignCardListTitle", customScalarType);
        CompiledField.Builder builder24 = new CompiledField.Builder("campaignCards", a.f(objectType));
        builder24.e = listR19;
        List listR20 = CollectionsKt.R(compiledFieldG6, builder24.c());
        v = listR20;
        CompiledField compiledFieldC13 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder25 = new CompiledFragment.Builder("CampaignCopy", CollectionsKt.Q("CampaignCopy"));
        builder25.d = listR16;
        CompiledFragment compiledFragmentA7 = builder25.a();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("ContentList", CollectionsKt.Q("ContentList"));
        builder26.d = listR17;
        CompiledFragment compiledFragmentA8 = builder26.a();
        CompiledFragment.Builder builder27 = new CompiledFragment.Builder("CampaignTermsAndConditions", CollectionsKt.Q("CampaignTermsAndConditions"));
        builder27.d = listR18;
        CompiledFragment compiledFragmentA9 = builder27.a();
        CompiledFragment.Builder builder28 = new CompiledFragment.Builder("CampaignCardList", CollectionsKt.Q("CampaignCardList"));
        builder28.d = listR20;
        List listR21 = CollectionsKt.R(compiledFieldC13, compiledFragmentA7, compiledFragmentA8, compiledFragmentA9, builder28.a());
        w = listR21;
        CompiledField compiledFieldC14 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType2 = Analytics.f11028a;
        CompiledField.Builder builder29 = new CompiledField.Builder("analytics", objectType2);
        builder29.e = listR15;
        CompiledField compiledFieldC15 = builder29.c();
        CompiledField.Builder builder30 = new CompiledField.Builder("bottomSheetFeedItems", d.j(DynamicPageBottomSheetFeedItems.f11358a));
        builder30.e = listR21;
        List listR22 = CollectionsKt.R(compiledFieldC14, compiledFieldC15, builder30.c());
        x = listR22;
        CompiledField compiledFieldC16 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder31 = new CompiledFragment.Builder("DynamicPageBottomSheet", CollectionsKt.Q("DynamicPageBottomSheet"));
        builder31.d = listR22;
        List listR23 = CollectionsKt.R(compiledFieldC16, builder31.a());
        y = listR23;
        CompiledField compiledFieldC17 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder32 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder32.d = list5;
        List listR24 = CollectionsKt.R(compiledFieldC17, builder32.a());
        z = listR24;
        CompiledField.Builder builder33 = new CompiledField.Builder("headerSection", CompiledGraphQL.b(DynamicPageHeaderSection.f11362a));
        builder33.e = listR;
        CompiledField compiledFieldC18 = builder33.c();
        CompiledField.Builder builder34 = new CompiledField.Builder("feedItems", CompiledGraphQL.b(CompiledGraphQL.a(DynamicPageFeedItem.f11360a)));
        builder34.e = listR13;
        CompiledField compiledFieldC19 = builder34.c();
        CompiledField.Builder builder35 = new CompiledField.Builder("footerSection", DynamicPageFooterSection.f11361a);
        builder35.e = listQ2;
        CompiledField compiledFieldC20 = builder35.c();
        CompiledField.Builder builder36 = new CompiledField.Builder("bottomSheets", CompiledGraphQL.a(DynamicPageBottomSheetTypes.f11359a));
        builder36.e = listR23;
        CompiledField compiledFieldC21 = builder36.c();
        CompiledField.Builder builder37 = new CompiledField.Builder("analytics", CompiledGraphQL.b(objectType2));
        builder37.e = listR24;
        List listR25 = CollectionsKt.R(compiledFieldC18, compiledFieldC19, compiledFieldC20, compiledFieldC21, builder37.c());
        A = listR25;
        CompiledField.Builder builder38 = new CompiledField.Builder("dynamicPage", DynamicPage.f11355a);
        new CompiledArgument.Builder(Query.n);
        builder38.d = au.com.woolworths.android.onesite.a.v();
        builder38.e = listR25;
        B = CollectionsKt.Q(builder38.c());
    }
}
