package au.com.woolworths.android.onesite.databinding;

import android.view.View;
import android.widget.Button;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.core.widget.NestedScrollView;
import androidx.databinding.DataBindingComponent;
import androidx.databinding.ViewDataBinding;
import androidx.legacy.widget.Space;
import androidx.recyclerview.widget.RecyclerView;
import au.com.woolworths.android.onesite.base.ui.databinding.IncludeGenericInlineErrorStateBinding;
import au.com.woolworths.android.onesite.modules.checkout.digitalpay.DigitalPayForOrderErrorState;

/* loaded from: classes3.dex */
public abstract class FragmentPayForOrderDigitalBinding extends ViewDataBinding {
    public final LinearLayout A;
    public final LinearLayout B;
    public final LinearLayout C;
    public final Space D;
    public final TextView E;
    public final IncludeAddNewCreditCardDigitalBinding F;
    public final TextView G;
    public final IncludeAddNewGiftCardDigitalBinding H;
    public final LinearLayout I;
    public final TextView J;
    public final RecyclerView K;
    public final LinearLayout L;
    public final TextView M;
    public final View N;
    public final TextView O;
    public final TextView P;
    public final RecyclerView Q;
    public final IncludeCheckoutExpiredErrorBinding R;
    public final IncludeCheckoutExpiredErrorBinding S;
    public final RecyclerView T;
    public final RecyclerView U;
    public final LinearLayout V;
    public final IncludeGenericInlineErrorStateBinding W;
    public final TextView X;
    public final TextView Y;
    public final TextView Z;
    public final TextView a0;
    public final View b0;
    public final TextView c0;
    public final FrameLayout d0;
    public final IncludePaymentDeductionBinding e0;
    public final ImageView f0;
    public final LinearLayout g0;
    public final IncludeCheckoutErrorNoRoundedBinding h0;
    public final Button i0;
    public final IncludeCheckoutWarningBinding j0;
    public final TextView k0;
    public final TextView l0;
    public final LinearLayout m0;
    public final NestedScrollView n0;
    public DigitalPayForOrderErrorState o0;
    public final LinearLayout y;
    public final LinearLayout z;

    public FragmentPayForOrderDigitalBinding(DataBindingComponent dataBindingComponent, View view, LinearLayout linearLayout, LinearLayout linearLayout2, LinearLayout linearLayout3, LinearLayout linearLayout4, LinearLayout linearLayout5, Space space, TextView textView, IncludeAddNewCreditCardDigitalBinding includeAddNewCreditCardDigitalBinding, TextView textView2, IncludeAddNewGiftCardDigitalBinding includeAddNewGiftCardDigitalBinding, LinearLayout linearLayout6, TextView textView3, RecyclerView recyclerView, LinearLayout linearLayout7, TextView textView4, View view2, TextView textView5, TextView textView6, RecyclerView recyclerView2, IncludeCheckoutExpiredErrorBinding includeCheckoutExpiredErrorBinding, IncludeCheckoutExpiredErrorBinding includeCheckoutExpiredErrorBinding2, RecyclerView recyclerView3, RecyclerView recyclerView4, LinearLayout linearLayout8, IncludeGenericInlineErrorStateBinding includeGenericInlineErrorStateBinding, TextView textView7, TextView textView8, TextView textView9, TextView textView10, View view3, TextView textView11, FrameLayout frameLayout, IncludePaymentDeductionBinding includePaymentDeductionBinding, ImageView imageView, LinearLayout linearLayout9, IncludeCheckoutErrorNoRoundedBinding includeCheckoutErrorNoRoundedBinding, Button button, IncludeCheckoutWarningBinding includeCheckoutWarningBinding, TextView textView12, TextView textView13, LinearLayout linearLayout10, NestedScrollView nestedScrollView) {
        super(dataBindingComponent, view, 8);
        this.y = linearLayout;
        this.z = linearLayout2;
        this.A = linearLayout3;
        this.B = linearLayout4;
        this.C = linearLayout5;
        this.D = space;
        this.E = textView;
        this.F = includeAddNewCreditCardDigitalBinding;
        this.G = textView2;
        this.H = includeAddNewGiftCardDigitalBinding;
        this.I = linearLayout6;
        this.J = textView3;
        this.K = recyclerView;
        this.L = linearLayout7;
        this.M = textView4;
        this.N = view2;
        this.O = textView5;
        this.P = textView6;
        this.Q = recyclerView2;
        this.R = includeCheckoutExpiredErrorBinding;
        this.S = includeCheckoutExpiredErrorBinding2;
        this.T = recyclerView3;
        this.U = recyclerView4;
        this.V = linearLayout8;
        this.W = includeGenericInlineErrorStateBinding;
        this.X = textView7;
        this.Y = textView8;
        this.Z = textView9;
        this.a0 = textView10;
        this.b0 = view3;
        this.c0 = textView11;
        this.d0 = frameLayout;
        this.e0 = includePaymentDeductionBinding;
        this.f0 = imageView;
        this.g0 = linearLayout9;
        this.h0 = includeCheckoutErrorNoRoundedBinding;
        this.i0 = button;
        this.j0 = includeCheckoutWarningBinding;
        this.k0 = textView12;
        this.l0 = textView13;
        this.m0 = linearLayout10;
        this.n0 = nestedScrollView;
    }

    public abstract void L(DigitalPayForOrderErrorState digitalPayForOrderErrorState);
}
