package com.woolworths.rewards.card.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.rewards.graphql.type.Coachmark;
import au.com.woolworths.rewards.graphql.type.ContentCta;
import au.com.woolworths.rewards.graphql.type.DownloadableAsset;
import au.com.woolworths.rewards.graphql.type.DownloadableAssetFit;
import au.com.woolworths.rewards.graphql.type.DownloadableAssetType;
import au.com.woolworths.rewards.graphql.type.GraphQLBoolean;
import au.com.woolworths.rewards.graphql.type.GraphQLID;
import au.com.woolworths.rewards.graphql.type.GraphQLInt;
import au.com.woolworths.rewards.graphql.type.GraphQLString;
import au.com.woolworths.rewards.graphql.type.InflightPaymentData;
import au.com.woolworths.rewards.graphql.type.Query;
import au.com.woolworths.rewards.graphql.type.RewardsBalance;
import au.com.woolworths.rewards.graphql.type.RewardsFuelVouchersSummary;
import au.com.woolworths.rewards.graphql.type.RewardsPage;
import au.com.woolworths.rewards.graphql.type.RewardsRedemptionSettingIcon;
import au.com.woolworths.rewards.graphql.type.RewardsRedemptionSettingsSummary;
import au.com.woolworths.rewards.graphql.type.RewardsRedemptionUnlock;
import au.com.woolworths.rewards.graphql.type.RewardsRedemptionUnlockButton;
import au.com.woolworths.rewards.graphql.type.RewardsRedemptionUnlockConfirmation;
import au.com.woolworths.rewards.graphql.type.WalletAction;
import au.com.woolworths.rewards.graphql.type.WalletHomePage;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.salesforce.marketingcloud.UrlHandler;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/rewards/card/selections/RewardsCardHomePageQuerySelections;", "", "card_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class RewardsCardHomePageQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f20692a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;

    static {
        DownloadableAssetType.e.getClass();
        EnumType enumType = DownloadableAssetType.f;
        CompiledField compiledFieldC = new CompiledField.Builder("assetType", CompiledGraphQL.b(enumType)).c();
        CustomScalarType customScalarType = GraphQLString.f9617a;
        CompiledField compiledFieldC2 = new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLInt.f9616a;
        CompiledField compiledFieldC3 = new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType2)).c();
        DownloadableAssetFit.e.getClass();
        EnumType enumType2 = DownloadableAssetFit.f;
        List listR = CollectionsKt.R(compiledFieldC, compiledFieldC2, compiledFieldC3, compiledFieldC4, new CompiledField.Builder("fit", enumType2).c());
        f20692a = listR;
        List listR2 = CollectionsKt.R(d.g("loadingStateLabel", customScalarType), d.g("sliderLabel", customScalarType), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("iconUrl", customScalarType));
        b = listR2;
        List listR3 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        c = listR3;
        CompiledField compiledFieldC5 = new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType = DownloadableAsset.f9500a;
        CompiledField.Builder builder = new CompiledField.Builder("headerImage", CompiledGraphQL.b(objectType));
        builder.e = listR;
        CompiledField compiledFieldC6 = builder.c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType3 = GraphQLBoolean.f9613a;
        CompiledField compiledFieldC8 = new CompiledField.Builder("showAnimation", CompiledGraphQL.b(customScalarType3)).c();
        CompiledField compiledFieldC9 = new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder2 = new CompiledField.Builder("button", CompiledGraphQL.b(RewardsRedemptionUnlockButton.f9863a));
        builder2.e = listR2;
        CompiledField compiledFieldC10 = builder2.c();
        CompiledField compiledFieldC11 = new CompiledField.Builder("analyticsLabel", CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType2 = ContentCta.f9485a;
        CompiledField.Builder builder3 = new CompiledField.Builder("callToAction", objectType2);
        builder3.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC5, compiledFieldC6, compiledFieldC7, compiledFieldC8, compiledFieldC9, compiledFieldC10, compiledFieldC11, builder3.c(), d.g("showUnlock", customScalarType3));
        d = listR4;
        CompiledField compiledFieldG = d.g("coachMarkText", customScalarType);
        CompiledField compiledFieldG2 = d.g("iconUrl", customScalarType);
        CompiledField.Builder builder4 = new CompiledField.Builder("unlockConfirmation", RewardsRedemptionUnlockConfirmation.f9864a);
        builder4.e = listR4;
        List listR5 = CollectionsKt.R(compiledFieldG, compiledFieldG2, builder4.c());
        e = listR5;
        RewardsRedemptionSettingIcon.e.getClass();
        CompiledField compiledFieldC12 = new CompiledField.Builder("redemptionIcon", CompiledGraphQL.b(RewardsRedemptionSettingIcon.f)).c();
        CompiledField compiledFieldC13 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC14 = new CompiledField.Builder("value", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG3 = d.g("altText", customScalarType);
        CompiledField.Builder builder5 = new CompiledField.Builder("redemptionUnlock", RewardsRedemptionUnlock.f9862a);
        builder5.c = a.s("withRedemptionUnlock", false);
        builder5.e = listR5;
        List listR6 = CollectionsKt.R(compiledFieldC12, compiledFieldC13, compiledFieldC14, compiledFieldG3, builder5.c());
        f = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("numberOfVouchers", CompiledGraphQL.b(customScalarType2)).c());
        g = listR7;
        CompiledField.Builder builder6 = new CompiledField.Builder("redemptionSettings", CompiledGraphQL.b(RewardsRedemptionSettingsSummary.f9861a));
        builder6.e = listR6;
        CompiledField compiledFieldC15 = builder6.c();
        CompiledField.Builder builder7 = new CompiledField.Builder("fuelVouchers", CompiledGraphQL.b(RewardsFuelVouchersSummary.f9832a));
        builder7.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC15, builder7.c(), d.g("displayName", customScalarType));
        h = listR8;
        CompiledField.Builder builder8 = new CompiledField.Builder("balance", CompiledGraphQL.b(RewardsBalance.f9806a));
        builder8.e = listR8;
        List listQ = CollectionsKt.Q(builder8.c());
        i = listQ;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("assetType", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType2)).c(), a.d("fit", enumType2), d.g("altText", customScalarType));
        j = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        k = listR10;
        CompiledField compiledFieldC16 = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLID.f9615a)).c();
        CompiledField.Builder builder9 = new CompiledField.Builder("bannerImage", objectType);
        builder9.e = listR9;
        CompiledField compiledFieldC17 = builder9.c();
        CompiledField compiledFieldG4 = d.g("contentTitle", customScalarType);
        CompiledField compiledFieldG5 = d.g("contentBody", customScalarType);
        CompiledField.Builder builder10 = new CompiledField.Builder("primaryCTA", objectType2);
        builder10.e = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC16, compiledFieldC17, compiledFieldG4, compiledFieldG5, builder10.c());
        l = listR11;
        List listR12 = CollectionsKt.R(new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("bannerMessage", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("snackbarMessage", CompiledGraphQL.b(customScalarType)).c());
        m = listR12;
        CompiledField compiledFieldG6 = d.g("title", customScalarType);
        CompiledField compiledFieldG7 = d.g("content", customScalarType);
        WalletAction.e.getClass();
        CompiledField compiledFieldC18 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(WalletAction.f)).c();
        CompiledField compiledFieldG8 = d.g("showWalletBadge", customScalarType3);
        CompiledField compiledFieldG9 = d.g("showCardTabBadge", customScalarType3);
        CompiledField compiledFieldG10 = d.g("tooltip", customScalarType);
        CompiledField.Builder builder11 = new CompiledField.Builder("coachmark", Coachmark.f9481a);
        builder11.c = a.s("withProductTourCoachmark", false);
        builder11.e = listR11;
        CompiledField compiledFieldC19 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("inflightPaymentData", InflightPaymentData.f9631a);
        builder12.c = a.s("withInflightBanner", false);
        builder12.e = listR12;
        List listR13 = CollectionsKt.R(compiledFieldG6, compiledFieldG7, compiledFieldC18, compiledFieldG8, compiledFieldG9, compiledFieldG10, compiledFieldC19, builder12.c());
        n = listR13;
        CompiledField.Builder builder13 = new CompiledField.Builder("rewardsHomePage", RewardsPage.f9849a);
        builder13.e = listQ;
        CompiledField compiledFieldC20 = builder13.c();
        CompiledField.Builder builder14 = new CompiledField.Builder("walletHomePage", CompiledGraphQL.b(WalletHomePage.f9945a));
        new CompiledArgument.Builder(Query.z);
        builder14.d = au.com.woolworths.android.onesite.a.v();
        builder14.e = listR13;
        CompiledField compiledFieldC21 = builder14.c();
        CompiledField.Builder builder15 = new CompiledField.Builder("showCustomerValuePropositions", CompiledGraphQL.b(customScalarType3));
        builder15.c = a.s("withCustomerProfileManager", true);
        o = CollectionsKt.R(compiledFieldC20, compiledFieldC21, builder15.c());
    }
}
