package au.com.woolworths.feature.shop.more.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.sdui.shop.fragment.selections.AnalyticsFieldsSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.BroadcastBannerType;
import au.com.woolworths.shop.graphql.type.CoreAlertStyle;
import au.com.woolworths.shop.graphql.type.CoreInsetAlertUI;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.More;
import au.com.woolworths.shop.graphql.type.MoreDeliveryUnlimitedStatus;
import au.com.woolworths.shop.graphql.type.MoreFeedItem;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.UnreadChatbotMsg;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lau/com/woolworths/feature/shop/more/selections/MoreFeedQuerySelections;", "", "more_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class MoreFeedQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f7633a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        CompiledField compiledFieldC = new CompiledField.Builder("cardNumber", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLBoolean.f11439a;
        List listR = CollectionsKt.R(compiledFieldC, new CompiledField.Builder("canBeUnlinked", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("rewardsState", CompiledGraphQL.b(customScalarType)).c());
        f7633a = listR;
        CompiledField compiledFieldC2 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField compiledFieldG2 = d.g("badge", customScalarType);
        MoreDeliveryUnlimitedStatus.e.getClass();
        List listR2 = CollectionsKt.R(compiledFieldC2, compiledFieldG, compiledFieldG2, new CompiledField.Builder("status", CompiledGraphQL.b(MoreDeliveryUnlimitedStatus.f)).c(), new CompiledField.Builder("subscribeUrl", CompiledGraphQL.b(customScalarType)).c());
        b = listR2;
        List listR3 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType));
        c = listR3;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c());
        d = listQ;
        List listR4 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        e = listR4;
        List listR5 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        f = listR5;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("count", CompiledGraphQL.b(GraphQLInt.f11442a)).c());
        g = listQ2;
        CompiledField compiledFieldC3 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG3 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField compiledFieldG4 = d.g("url", customScalarType);
        CompiledField.Builder builder = new CompiledField.Builder("unreadChatbotMsg", UnreadChatbotMsg.f11990a);
        builder.e = listQ2;
        List listR6 = CollectionsKt.R(compiledFieldC3, compiledFieldG3, compiledFieldG4, builder.c());
        h = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType));
        i = listR7;
        CompiledField compiledFieldC4 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG5 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField compiledFieldG6 = d.g("deeplink", customScalarType);
        BroadcastBannerType.e.getClass();
        List listR8 = CollectionsKt.R(compiledFieldC4, compiledFieldG5, compiledFieldG6, new CompiledField.Builder("type", CompiledGraphQL.b(BroadcastBannerType.f)).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c(), d.g("actionLabel", customScalarType), d.g("analyticsLabel", customScalarType), d.g("dismissible", customScalarType2), d.g("bannerId", customScalarType));
        j = listR8;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c());
        k = listQ3;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        l = listR9;
        CompiledField compiledFieldG7 = d.g("title", customScalarType);
        CompiledField compiledFieldG8 = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CoreAlertStyle.e.getClass();
        List listR10 = CollectionsKt.R(compiledFieldG7, compiledFieldG8, new CompiledField.Builder("style", CompiledGraphQL.b(CoreAlertStyle.f)).c());
        m = listR10;
        CompiledField compiledFieldC5 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder2.b(AnalyticsFieldsSelections.b);
        List listR11 = CollectionsKt.R(compiledFieldC5, builder2.a());
        n = listR11;
        CompiledField compiledFieldG9 = d.g("id", customScalarType);
        ActionType.e.getClass();
        CompiledField compiledFieldC6 = new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.f)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder3 = new CompiledField.Builder("analytics", Analytics.f11028a);
        builder3.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldG9, compiledFieldC6, compiledFieldC7, builder3.c());
        o = listR12;
        CompiledField.Builder builder4 = new CompiledField.Builder("insetAlertUI", CompiledGraphQL.b(CoreInsetAlertUI.f11291a));
        builder4.e = listR10;
        CompiledField compiledFieldC8 = builder4.c();
        CompiledField.Builder builder5 = new CompiledField.Builder("insetAlertAction", Action.f10997a);
        builder5.e = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC8, builder5.c(), d.g("insetAlertActionLabel", customScalarType));
        p = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        q = listR14;
        CompiledField compiledFieldC9 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("MoreRewardsCard", CollectionsKt.Q("MoreRewardsCard"));
        builder6.d = listR;
        CompiledFragment compiledFragmentA = builder6.a();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("MoreDeliveryUnlimited", CollectionsKt.Q("MoreDeliveryUnlimited"));
        builder7.d = listR2;
        CompiledFragment compiledFragmentA2 = builder7.a();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("MoreCiscoWiFi", CollectionsKt.Q("MoreCiscoWiFi"));
        builder8.d = listR3;
        CompiledFragment compiledFragmentA3 = builder8.a();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("MoreEReceipts", CollectionsKt.Q("MoreEReceipts"));
        builder9.c = a.s("eReceiptsEnabled", false);
        builder9.d = listQ;
        CompiledFragment compiledFragmentA4 = builder9.a();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("MoreReceiptPreferences", CollectionsKt.Q("MoreReceiptPreferences"));
        builder10.c = a.s("eReceiptsEnabled", false);
        builder10.d = listR4;
        CompiledFragment compiledFragmentA5 = builder10.a();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("MoreOnlineShopping", CollectionsKt.Q("MoreOnlineShopping"));
        builder11.d = listR5;
        CompiledFragment compiledFragmentA6 = builder11.a();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("MoreChat", CollectionsKt.Q("MoreChat"));
        builder12.d = listR6;
        CompiledFragment compiledFragmentA7 = builder12.a();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("MoreNotifications", CollectionsKt.Q("MoreNotifications"));
        builder13.d = listR7;
        CompiledFragment compiledFragmentA8 = builder13.a();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("BroadcastBanner", CollectionsKt.Q("BroadcastBanner"));
        builder14.d = listR8;
        CompiledFragment compiledFragmentA9 = builder14.a();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("MoreDeleteAccount", CollectionsKt.Q("MoreDeleteAccount"));
        builder15.d = listQ3;
        CompiledFragment compiledFragmentA10 = builder15.a();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("MoreExplainingValue", CollectionsKt.Q("MoreExplainingValue"));
        builder16.d = listR9;
        CompiledFragment compiledFragmentA11 = builder16.a();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("BasicInsetAlert", CollectionsKt.Q("BasicInsetAlert"));
        builder17.c = a.s("includeBasicInsetAlert", false);
        builder17.d = listR13;
        CompiledFragment compiledFragmentA12 = builder17.a();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("MoreFoodTracker", CollectionsKt.Q("MoreFoodTracker"));
        builder18.d = listR14;
        List listR15 = CollectionsKt.R(compiledFieldC9, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, compiledFragmentA8, compiledFragmentA9, compiledFragmentA10, compiledFragmentA11, compiledFragmentA12, builder18.a());
        r = listR15;
        CompiledField.Builder builder19 = new CompiledField.Builder("feed", d.j(MoreFeedItem.f11586a));
        builder19.e = listR15;
        List listQ4 = CollectionsKt.Q(builder19.c());
        s = listQ4;
        CompiledField.Builder builder20 = new CompiledField.Builder("more", CompiledGraphQL.b(More.f11577a));
        new CompiledArgument.Builder(Query.H);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.G);
        CompiledArgument compiledArgument2 = new CompiledArgument();
        new CompiledArgument.Builder(Query.F);
        builder20.d = CollectionsKt.R(compiledArgument, compiledArgument2, new CompiledArgument());
        builder20.e = listQ4;
        t = CollectionsKt.Q(builder20.c());
    }
}
