package com.woolworths.shop.brandedshop.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.graphql.common.fragment.selections.ProductCardSelections;
import au.com.woolworths.sdui.shop.fragment.selections.AnalyticsFieldsSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.BrandedShopPage;
import au.com.woolworths.shop.graphql.type.BrandedShopPageHeader;
import au.com.woolworths.shop.graphql.type.ButtonAnalytics;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.DownloadableAssetFit;
import au.com.woolworths.shop.graphql.type.DownloadableAssetType;
import au.com.woolworths.shop.graphql.type.GenericPageBottomSheetItem;
import au.com.woolworths.shop.graphql.type.GenericPageFeedItem;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.HorizontalListItem;
import au.com.woolworths.shop.graphql.type.Link;
import au.com.woolworths.shop.graphql.type.ParagraphTextItemType;
import au.com.woolworths.shop.graphql.type.ProductSectionFeedItem;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.StaticBottomSheetFeedItem;
import au.com.woolworths.shop.graphql.type.TabItem;
import au.com.woolworths.shop.graphql.type.TabItemFeed;
import au.com.woolworths.shop.graphql.type.TextWithAlt;
import au.com.woolworths.shop.graphql.type.TitleSectionTypes;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.salesforce.marketingcloud.UrlHandler;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/brandedshop/selections/BrandedShopQuerySelections;", "", "brandedshop_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class BrandedShopQuerySelections {
    public static final List A;
    public static final List B;
    public static final List C;
    public static final List D;
    public static final List E;
    public static final List F;
    public static final List G;
    public static final List H;
    public static final List I;
    public static final List J;
    public static final List K;
    public static final List L;
    public static final List M;
    public static final List N;
    public static final List O;
    public static final List P;
    public static final List Q;

    /* renamed from: a, reason: collision with root package name */
    public static final List f21492a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        List listR = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("pageTitle", CompiledGraphQL.b(customScalarType)).c());
        f21492a = listR;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC2 = new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c();
        ParagraphTextItemType.e.getClass();
        EnumType enumType = ParagraphTextItemType.f;
        List listR2 = CollectionsKt.R(compiledFieldC, compiledFieldC2, new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c());
        b = listR2;
        CompiledField compiledFieldC3 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("ParagraphTextItem", CollectionsKt.Q("ParagraphTextItem"));
        builder.d = listR2;
        List listR3 = CollectionsKt.R(compiledFieldC3, builder.a());
        c = listR3;
        CompiledField compiledFieldC4 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC5 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC6 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder2 = new CompiledField.Builder("staticBottomSheetItems", CompiledGraphQL.b(CompiledGraphQL.a(StaticBottomSheetFeedItem.f11931a)));
        builder2.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC4, compiledFieldC5, compiledFieldC6, builder2.c());
        d = listR4;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("StaticBottomSheet", CollectionsKt.Q("StaticBottomSheet"));
        builder3.d = listR4;
        List listR5 = CollectionsKt.R(compiledFieldC7, builder3.a());
        e = listR5;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        List list = AnalyticsFieldsSelections.b;
        builder4.b(list);
        List listR6 = CollectionsKt.R(compiledFieldC8, builder4.a());
        f = listR6;
        CompiledField compiledFieldC9 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder5.b(list);
        List listR7 = CollectionsKt.R(compiledFieldC9, builder5.a());
        g = listR7;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g("assetId", customScalarType);
        DownloadableAssetType.e.getClass();
        CompiledField compiledFieldC11 = new CompiledField.Builder("assetType", CompiledGraphQL.b(DownloadableAssetType.f)).c();
        CompiledField compiledFieldC12 = new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLInt.f11442a;
        CompiledField compiledFieldC13 = new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC14 = new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType2)).c();
        DownloadableAssetFit.e.getClass();
        List listR8 = CollectionsKt.R(compiledFieldC10, compiledFieldG, compiledFieldC11, compiledFieldC12, compiledFieldC13, compiledFieldC14, new CompiledField.Builder("fit", DownloadableAssetFit.f).c(), d.g("altText", customScalarType));
        h = listR8;
        CompiledField compiledFieldC15 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG2 = d.g("titleSectionId", customScalarType);
        TitleSectionTypes.e.getClass();
        List listR9 = CollectionsKt.R(compiledFieldC15, compiledFieldG2, new CompiledField.Builder("titleSectionType", CompiledGraphQL.b(TitleSectionTypes.f)).c(), new CompiledField.Builder("titleSectionText", CompiledGraphQL.b(customScalarType)).c());
        i = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        j = listR10;
        CompiledField compiledFieldC16 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        ActionType.e.getClass();
        EnumType enumType2 = ActionType.f;
        List listR11 = CollectionsKt.R(compiledFieldC16, new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c(), d.g("id", customScalarType));
        k = listR11;
        CompiledField compiledFieldC17 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG3 = d.g("linkId", customScalarType);
        ObjectType objectType = TextWithAlt.f11967a;
        CompiledField.Builder builder6 = new CompiledField.Builder("linkTextWithAlt", CompiledGraphQL.b(objectType));
        builder6.e = listR10;
        CompiledField compiledFieldC18 = builder6.c();
        ObjectType objectType2 = Action.f10997a;
        CompiledField.Builder builder7 = new CompiledField.Builder("linkAction", CompiledGraphQL.b(objectType2));
        builder7.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC17, compiledFieldG3, compiledFieldC18, builder7.c());
        l = listR12;
        CompiledField compiledFieldC19 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        List list2 = ProductCardSelections.A;
        builder8.b(list2);
        List listR13 = CollectionsKt.R(compiledFieldC19, builder8.a());
        m = listR13;
        CompiledField compiledFieldC20 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder9.d = listR13;
        List listR14 = CollectionsKt.R(compiledFieldC20, builder9.a());
        n = listR14;
        CompiledField compiledFieldC21 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG4 = d.g("productSectionId", customScalarType);
        ObjectType objectType3 = Link.f11514a;
        CompiledField.Builder builder10 = new CompiledField.Builder("productSectionLink", objectType3);
        builder10.e = listR12;
        CompiledField compiledFieldC22 = builder10.c();
        CompiledField compiledFieldG5 = d.g("productSectionTotal", customScalarType);
        UnionType unionType = ProductSectionFeedItem.f11784a;
        CompiledField.Builder builder11 = new CompiledField.Builder("productSectionFeed", CompiledGraphQL.b(CompiledGraphQL.a(unionType)));
        builder11.e = listR14;
        List listR15 = CollectionsKt.R(compiledFieldC21, compiledFieldG4, compiledFieldC22, compiledFieldG5, builder11.c());
        o = listR15;
        CompiledField compiledFieldC23 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("ProductSection", CollectionsKt.Q("ProductSection"));
        builder12.d = listR15;
        List listR16 = CollectionsKt.R(compiledFieldC23, builder12.a());
        p = listR16;
        CompiledField compiledFieldC24 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG6 = d.g("tabItemId", customScalarType);
        CompiledField compiledFieldC25 = new CompiledField.Builder("tabItemTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder13 = new CompiledField.Builder("tabItemFeed", CompiledGraphQL.b(CompiledGraphQL.a(TabItemFeed.f11960a)));
        builder13.e = listR16;
        List listR17 = CollectionsKt.R(compiledFieldC24, compiledFieldG6, compiledFieldC25, builder13.c());
        q = listR17;
        CompiledField compiledFieldC26 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG7 = d.g("tabSectionId", customScalarType);
        CompiledField.Builder builder14 = new CompiledField.Builder("tabSectionItems", a.f(TabItem.f11959a));
        builder14.e = listR17;
        List listR18 = CollectionsKt.R(compiledFieldC26, compiledFieldG7, builder14.c());
        r = listR18;
        List listR19 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        s = listR19;
        List listR20 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c(), d.g("id", customScalarType));
        t = listR20;
        CompiledField compiledFieldC27 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG8 = d.g("linkId", customScalarType);
        CompiledField.Builder builder15 = new CompiledField.Builder("linkTextWithAlt", CompiledGraphQL.b(objectType));
        builder15.e = listR19;
        CompiledField compiledFieldC28 = builder15.c();
        CompiledField.Builder builder16 = new CompiledField.Builder("linkAction", CompiledGraphQL.b(objectType2));
        builder16.e = listR20;
        List listR21 = CollectionsKt.R(compiledFieldC27, compiledFieldG8, compiledFieldC28, builder16.c());
        u = listR21;
        List listR22 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c(), d.g("id", customScalarType));
        v = listR22;
        List listR23 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), d.g(AnnotatedPrivateKey.LABEL, customScalarType));
        w = listR23;
        CompiledField compiledFieldC29 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG9 = d.g("buttonId", customScalarType);
        CompiledField compiledFieldC30 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        ButtonStyle.e.getClass();
        CompiledField compiledFieldC31 = new CompiledField.Builder("style", ButtonStyle.f).c();
        CompiledField compiledFieldC32 = new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.f11439a)).c();
        CompiledField.Builder builder17 = new CompiledField.Builder("buttonAction", objectType2);
        builder17.e = listR22;
        CompiledField compiledFieldC33 = builder17.c();
        CompiledField compiledFieldG10 = d.g("iconUrl", customScalarType);
        CompiledField compiledFieldG11 = d.g("altText", customScalarType);
        CompiledField.Builder builder18 = new CompiledField.Builder("analytics", ButtonAnalytics.f11081a);
        builder18.e = listR23;
        List listR24 = CollectionsKt.R(compiledFieldC29, compiledFieldG9, compiledFieldC30, compiledFieldC31, compiledFieldC32, compiledFieldC33, compiledFieldG10, compiledFieldG11, builder18.c());
        x = listR24;
        List listR25 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c(), d.g("id", customScalarType));
        y = listR25;
        CompiledField compiledFieldC34 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG12 = d.g("contentCardId", customScalarType);
        CompiledField compiledFieldC35 = new CompiledField.Builder("contentCardImageUrl", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG13 = d.g("contentCardTitle", customScalarType);
        CompiledField compiledFieldG14 = d.g("contentCardDescription", customScalarType);
        CompiledField.Builder builder19 = new CompiledField.Builder("contentCardAction", objectType2);
        builder19.e = listR25;
        List listR26 = CollectionsKt.R(compiledFieldC34, compiledFieldG12, compiledFieldC35, compiledFieldG13, compiledFieldG14, builder19.c());
        z = listR26;
        List listR27 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c(), d.g("id", customScalarType));
        A = listR27;
        CompiledField compiledFieldC36 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG15 = d.g("navRoundelId", customScalarType);
        CompiledField compiledFieldC37 = new CompiledField.Builder("navRoundelImageUrl", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG16 = d.g("navRoundelTitle", customScalarType);
        CompiledField.Builder builder20 = new CompiledField.Builder("navRoundelAction", objectType2);
        builder20.e = listR27;
        List listR28 = CollectionsKt.R(compiledFieldC36, compiledFieldG15, compiledFieldC37, compiledFieldG16, builder20.c());
        B = listR28;
        CompiledField compiledFieldC38 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("ContentCard", CollectionsKt.Q("ContentCard"));
        builder21.d = listR26;
        CompiledFragment compiledFragmentA = builder21.a();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("NavRoundel", CollectionsKt.Q("NavRoundel"));
        builder22.d = listR28;
        List listR29 = CollectionsKt.R(compiledFieldC38, compiledFragmentA, builder22.a());
        C = listR29;
        CompiledField compiledFieldC39 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG17 = d.g("id", customScalarType);
        CompiledField compiledFieldC40 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG18 = d.g("actionTitle", customScalarType);
        CompiledField compiledFieldG19 = d.g("deepLink", customScalarType);
        CompiledField.Builder builder23 = new CompiledField.Builder("items", d.j(HorizontalListItem.f11475a));
        builder23.e = listR29;
        List listR30 = CollectionsKt.R(compiledFieldC39, compiledFieldG17, compiledFieldC40, compiledFieldG18, compiledFieldG19, builder23.c());
        D = listR30;
        List listR31 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), d.g("imageCardId", customScalarType), new CompiledField.Builder("imageCardImageUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("imageCardImageAltText", CompiledGraphQL.b(customScalarType)).c(), d.g("imageCardTitle", customScalarType));
        E = listR31;
        List listR32 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c(), d.g("id", customScalarType));
        F = listR32;
        CompiledField compiledFieldC41 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG20 = d.g("contentCardId", customScalarType);
        CompiledField compiledFieldC42 = new CompiledField.Builder("contentCardImageUrl", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG21 = d.g("contentCardTitle", customScalarType);
        CompiledField compiledFieldG22 = d.g("contentCardDescription", customScalarType);
        CompiledField.Builder builder24 = new CompiledField.Builder("contentCardAction", objectType2);
        builder24.e = listR32;
        List listR33 = CollectionsKt.R(compiledFieldC41, compiledFieldG20, compiledFieldC42, compiledFieldG21, compiledFieldG22, builder24.c());
        G = listR33;
        List listR34 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), d.g("paragraphTextItemId", customScalarType), new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c());
        H = listR34;
        List listR35 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        I = listR35;
        List listR36 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c(), d.g("id", customScalarType));
        J = listR36;
        CompiledField compiledFieldC43 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG23 = d.g("linkId", customScalarType);
        CompiledField.Builder builder25 = new CompiledField.Builder("linkTextWithAlt", CompiledGraphQL.b(objectType));
        builder25.e = listR35;
        CompiledField compiledFieldC44 = builder25.c();
        CompiledField.Builder builder26 = new CompiledField.Builder("linkAction", CompiledGraphQL.b(objectType2));
        builder26.e = listR36;
        List listR37 = CollectionsKt.R(compiledFieldC43, compiledFieldG23, compiledFieldC44, builder26.c());
        K = listR37;
        CompiledField compiledFieldC45 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder27 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder27.b(list2);
        List listR38 = CollectionsKt.R(compiledFieldC45, builder27.a());
        L = listR38;
        CompiledField compiledFieldC46 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder28 = new CompiledFragment.Builder("ProductCard", CollectionsKt.Q("ProductCard"));
        builder28.d = listR38;
        List listR39 = CollectionsKt.R(compiledFieldC46, builder28.a());
        M = listR39;
        CompiledField compiledFieldC47 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG24 = d.g("productSectionId", customScalarType);
        CompiledField.Builder builder29 = new CompiledField.Builder("productSectionLink", objectType3);
        builder29.e = listR37;
        CompiledField compiledFieldC48 = builder29.c();
        CompiledField compiledFieldG25 = d.g("productSectionTotal", customScalarType);
        CompiledField.Builder builder30 = new CompiledField.Builder("productSectionFeed", CompiledGraphQL.b(CompiledGraphQL.a(unionType)));
        builder30.e = listR39;
        List listR40 = CollectionsKt.R(compiledFieldC47, compiledFieldG24, compiledFieldC48, compiledFieldG25, builder30.c());
        N = listR40;
        CompiledField compiledFieldC49 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder31 = new CompiledFragment.Builder("DownloadableAsset", CollectionsKt.Q("DownloadableAsset"));
        builder31.d = listR8;
        CompiledFragment compiledFragmentA2 = builder31.a();
        CompiledFragment.Builder builder32 = new CompiledFragment.Builder("TitleSection", CollectionsKt.Q("TitleSection"));
        builder32.d = listR9;
        CompiledFragment compiledFragmentA3 = builder32.a();
        CompiledFragment.Builder builder33 = new CompiledFragment.Builder("TabSection", CollectionsKt.Q("TabSection"));
        builder33.d = listR18;
        CompiledFragment compiledFragmentA4 = builder33.a();
        CompiledFragment.Builder builder34 = new CompiledFragment.Builder("Link", CollectionsKt.Q("Link"));
        builder34.d = listR21;
        CompiledFragment compiledFragmentA5 = builder34.a();
        CompiledFragment.Builder builder35 = new CompiledFragment.Builder("Button", CollectionsKt.Q("Button"));
        builder35.d = listR24;
        CompiledFragment compiledFragmentA6 = builder35.a();
        CompiledFragment.Builder builder36 = new CompiledFragment.Builder("HorizontalList", CollectionsKt.Q("HorizontalList"));
        builder36.d = listR30;
        CompiledFragment compiledFragmentA7 = builder36.a();
        CompiledFragment.Builder builder37 = new CompiledFragment.Builder("FullWidthImageCard", CollectionsKt.Q("FullWidthImageCard"));
        builder37.d = listR31;
        CompiledFragment compiledFragmentA8 = builder37.a();
        CompiledFragment.Builder builder38 = new CompiledFragment.Builder("FullWidthContentCard", CollectionsKt.Q("FullWidthContentCard"));
        builder38.d = listR33;
        CompiledFragment compiledFragmentA9 = builder38.a();
        CompiledFragment.Builder builder39 = new CompiledFragment.Builder("ParagraphTextItem", CollectionsKt.Q("ParagraphTextItem"));
        builder39.d = listR34;
        CompiledFragment compiledFragmentA10 = builder39.a();
        CompiledFragment.Builder builder40 = new CompiledFragment.Builder("ProductSection", CollectionsKt.Q("ProductSection"));
        builder40.d = listR40;
        List listR41 = CollectionsKt.R(compiledFieldC49, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, compiledFragmentA8, compiledFragmentA9, compiledFragmentA10, builder40.a());
        O = listR41;
        CompiledField.Builder builder41 = new CompiledField.Builder("header", BrandedShopPageHeader.f11058a);
        builder41.e = listR;
        CompiledField compiledFieldC50 = builder41.c();
        CompiledField.Builder builder42 = new CompiledField.Builder("bottomSheets", CompiledGraphQL.a(GenericPageBottomSheetItem.f11426a));
        builder42.e = listR5;
        CompiledField compiledFieldC51 = builder42.c();
        ObjectType objectType4 = Analytics.f11028a;
        CompiledField.Builder builder43 = new CompiledField.Builder("analytics", objectType4);
        builder43.e = listR6;
        CompiledField compiledFieldC52 = builder43.c();
        CompiledField.Builder builder44 = new CompiledField.Builder("impressionAnalytics", objectType4);
        builder44.e = listR7;
        CompiledField compiledFieldC53 = builder44.c();
        CompiledField.Builder builder45 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(GenericPageFeedItem.f11427a)));
        builder45.e = listR41;
        List listR42 = CollectionsKt.R(compiledFieldC50, compiledFieldC51, compiledFieldC52, compiledFieldC53, builder45.c());
        P = listR42;
        CompiledField.Builder builder46 = new CompiledField.Builder("brandedShop", CompiledGraphQL.b(BrandedShopPage.f11057a));
        new CompiledArgument.Builder(Query.f);
        builder46.d = au.com.woolworths.android.onesite.a.v();
        builder46.e = listR42;
        Q = CollectionsKt.Q(builder46.c());
    }
}
