package com.google.android.gms.internal.mlkit_vision_common;

import com.google.android.gms.common.api.internal.a;
import com.google.firebase.encoders.FieldDescriptor;
import com.google.firebase.encoders.ObjectEncoder;
import com.google.firebase.encoders.ObjectEncoderContext;
import java.io.IOException;

/* loaded from: classes5.dex */
final class zzeo implements ObjectEncoder {
    static final zzeo zza = new zzeo();
    private static final FieldDescriptor zzb = a.C(1, new FieldDescriptor.Builder("systemInfo"));
    private static final FieldDescriptor zzc = a.C(2, new FieldDescriptor.Builder(com.salesforce.marketingcloud.config.a.h));
    private static final FieldDescriptor zzd = a.C(37, new FieldDescriptor.Builder("isThickClient"));
    private static final FieldDescriptor zze = a.C(61, new FieldDescriptor.Builder("clientType"));
    private static final FieldDescriptor zzf = a.C(3, new FieldDescriptor.Builder("modelDownloadLogEvent"));
    private static final FieldDescriptor zzg = a.C(20, new FieldDescriptor.Builder("customModelLoadLogEvent"));
    private static final FieldDescriptor zzh = a.C(4, new FieldDescriptor.Builder("customModelInferenceLogEvent"));
    private static final FieldDescriptor zzi = a.C(29, new FieldDescriptor.Builder("customModelCreateLogEvent"));
    private static final FieldDescriptor zzj = a.C(5, new FieldDescriptor.Builder("onDeviceFaceDetectionLogEvent"));
    private static final FieldDescriptor zzk = a.C(59, new FieldDescriptor.Builder("onDeviceFaceLoadLogEvent"));
    private static final FieldDescriptor zzl = a.C(6, new FieldDescriptor.Builder("onDeviceTextDetectionLogEvent"));
    private static final FieldDescriptor zzm = a.C(79, new FieldDescriptor.Builder("onDeviceTextDetectionLoadLogEvent"));
    private static final FieldDescriptor zzn = a.C(7, new FieldDescriptor.Builder("onDeviceBarcodeDetectionLogEvent"));
    private static final FieldDescriptor zzo = a.C(58, new FieldDescriptor.Builder("onDeviceBarcodeLoadLogEvent"));
    private static final FieldDescriptor zzp = a.C(48, new FieldDescriptor.Builder("onDeviceImageLabelCreateLogEvent"));
    private static final FieldDescriptor zzq = a.C(49, new FieldDescriptor.Builder("onDeviceImageLabelLoadLogEvent"));
    private static final FieldDescriptor zzr = a.C(18, new FieldDescriptor.Builder("onDeviceImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzs = a.C(26, new FieldDescriptor.Builder("onDeviceObjectCreateLogEvent"));
    private static final FieldDescriptor zzt = a.C(27, new FieldDescriptor.Builder("onDeviceObjectLoadLogEvent"));
    private static final FieldDescriptor zzu = a.C(28, new FieldDescriptor.Builder("onDeviceObjectInferenceLogEvent"));
    private static final FieldDescriptor zzv = a.C(44, new FieldDescriptor.Builder("onDevicePoseDetectionLogEvent"));
    private static final FieldDescriptor zzw = a.C(45, new FieldDescriptor.Builder("onDeviceSegmentationLogEvent"));
    private static final FieldDescriptor zzx = a.C(19, new FieldDescriptor.Builder("onDeviceSmartReplyLogEvent"));
    private static final FieldDescriptor zzy = a.C(21, new FieldDescriptor.Builder("onDeviceLanguageIdentificationLogEvent"));
    private static final FieldDescriptor zzz = a.C(22, new FieldDescriptor.Builder("onDeviceTranslationLogEvent"));
    private static final FieldDescriptor zzA = a.C(8, new FieldDescriptor.Builder("cloudFaceDetectionLogEvent"));
    private static final FieldDescriptor zzB = a.C(9, new FieldDescriptor.Builder("cloudCropHintDetectionLogEvent"));
    private static final FieldDescriptor zzC = a.C(10, new FieldDescriptor.Builder("cloudDocumentTextDetectionLogEvent"));
    private static final FieldDescriptor zzD = a.C(11, new FieldDescriptor.Builder("cloudImagePropertiesDetectionLogEvent"));
    private static final FieldDescriptor zzE = a.C(12, new FieldDescriptor.Builder("cloudImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzF = a.C(13, new FieldDescriptor.Builder("cloudLandmarkDetectionLogEvent"));
    private static final FieldDescriptor zzG = a.C(14, new FieldDescriptor.Builder("cloudLogoDetectionLogEvent"));
    private static final FieldDescriptor zzH = a.C(15, new FieldDescriptor.Builder("cloudSafeSearchDetectionLogEvent"));
    private static final FieldDescriptor zzI = a.C(16, new FieldDescriptor.Builder("cloudTextDetectionLogEvent"));
    private static final FieldDescriptor zzJ = a.C(17, new FieldDescriptor.Builder("cloudWebSearchDetectionLogEvent"));
    private static final FieldDescriptor zzK = a.C(23, new FieldDescriptor.Builder("automlImageLabelingCreateLogEvent"));
    private static final FieldDescriptor zzL = a.C(24, new FieldDescriptor.Builder("automlImageLabelingLoadLogEvent"));
    private static final FieldDescriptor zzM = a.C(25, new FieldDescriptor.Builder("automlImageLabelingInferenceLogEvent"));
    private static final FieldDescriptor zzN = a.C(39, new FieldDescriptor.Builder("isModelDownloadedLogEvent"));
    private static final FieldDescriptor zzO = a.C(40, new FieldDescriptor.Builder("deleteModelLogEvent"));
    private static final FieldDescriptor zzP = a.C(30, new FieldDescriptor.Builder("aggregatedAutomlImageLabelingInferenceLogEvent"));
    private static final FieldDescriptor zzQ = a.C(31, new FieldDescriptor.Builder("aggregatedCustomModelInferenceLogEvent"));
    private static final FieldDescriptor zzR = a.C(32, new FieldDescriptor.Builder("aggregatedOnDeviceFaceDetectionLogEvent"));
    private static final FieldDescriptor zzS = a.C(33, new FieldDescriptor.Builder("aggregatedOnDeviceBarcodeDetectionLogEvent"));
    private static final FieldDescriptor zzT = a.C(34, new FieldDescriptor.Builder("aggregatedOnDeviceImageLabelDetectionLogEvent"));
    private static final FieldDescriptor zzU = a.C(35, new FieldDescriptor.Builder("aggregatedOnDeviceObjectInferenceLogEvent"));
    private static final FieldDescriptor zzV = a.C(36, new FieldDescriptor.Builder("aggregatedOnDeviceTextDetectionLogEvent"));
    private static final FieldDescriptor zzW = a.C(46, new FieldDescriptor.Builder("aggregatedOnDevicePoseDetectionLogEvent"));
    private static final FieldDescriptor zzX = a.C(47, new FieldDescriptor.Builder("aggregatedOnDeviceSegmentationLogEvent"));
    private static final FieldDescriptor zzY = a.C(69, new FieldDescriptor.Builder("pipelineAccelerationInferenceEvents"));
    private static final FieldDescriptor zzZ = a.C(42, new FieldDescriptor.Builder("remoteConfigLogEvent"));
    private static final FieldDescriptor zzaa = a.C(50, new FieldDescriptor.Builder("inputImageConstructionLogEvent"));
    private static final FieldDescriptor zzab = a.C(51, new FieldDescriptor.Builder("leakedHandleEvent"));
    private static final FieldDescriptor zzac = a.C(52, new FieldDescriptor.Builder("cameraSourceLogEvent"));
    private static final FieldDescriptor zzad = a.C(53, new FieldDescriptor.Builder("imageLabelOptionalModuleLogEvent"));
    private static final FieldDescriptor zzae = a.C(54, new FieldDescriptor.Builder("languageIdentificationOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaf = a.C(60, new FieldDescriptor.Builder("faceDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzag = a.C(85, new FieldDescriptor.Builder("documentDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzah = a.C(86, new FieldDescriptor.Builder("documentCroppingOptionalModuleLogEvent"));
    private static final FieldDescriptor zzai = a.C(87, new FieldDescriptor.Builder("documentEnhancementOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaj = a.C(55, new FieldDescriptor.Builder("nlClassifierOptionalModuleLogEvent"));
    private static final FieldDescriptor zzak = a.C(56, new FieldDescriptor.Builder("nlClassifierClientLibraryLogEvent"));
    private static final FieldDescriptor zzal = a.C(57, new FieldDescriptor.Builder("accelerationAllowlistLogEvent"));
    private static final FieldDescriptor zzam = a.C(62, new FieldDescriptor.Builder("toxicityDetectionCreateEvent"));
    private static final FieldDescriptor zzan = a.C(63, new FieldDescriptor.Builder("toxicityDetectionLoadEvent"));
    private static final FieldDescriptor zzao = a.C(64, new FieldDescriptor.Builder("toxicityDetectionInferenceEvent"));
    private static final FieldDescriptor zzap = a.C(65, new FieldDescriptor.Builder("barcodeDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaq = a.C(66, new FieldDescriptor.Builder("customImageLabelOptionalModuleLogEvent"));
    private static final FieldDescriptor zzar = a.C(67, new FieldDescriptor.Builder("codeScannerScanApiEvent"));
    private static final FieldDescriptor zzas = a.C(68, new FieldDescriptor.Builder("codeScannerOptionalModuleEvent"));
    private static final FieldDescriptor zzat = a.C(70, new FieldDescriptor.Builder("onDeviceExplicitContentCreateLogEvent"));
    private static final FieldDescriptor zzau = a.C(71, new FieldDescriptor.Builder("onDeviceExplicitContentLoadLogEvent"));
    private static final FieldDescriptor zzav = a.C(72, new FieldDescriptor.Builder("onDeviceExplicitContentInferenceLogEvent"));
    private static final FieldDescriptor zzaw = a.C(73, new FieldDescriptor.Builder("aggregatedOnDeviceExplicitContentLogEvent"));
    private static final FieldDescriptor zzax = a.C(74, new FieldDescriptor.Builder("onDeviceFaceMeshCreateLogEvent"));
    private static final FieldDescriptor zzay = a.C(75, new FieldDescriptor.Builder("onDeviceFaceMeshLoadLogEvent"));
    private static final FieldDescriptor zzaz = a.C(76, new FieldDescriptor.Builder("onDeviceFaceMeshLogEvent"));
    private static final FieldDescriptor zzaA = a.C(77, new FieldDescriptor.Builder("aggregatedOnDeviceFaceMeshLogEvent"));
    private static final FieldDescriptor zzaB = a.C(78, new FieldDescriptor.Builder("smartReplyOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaC = a.C(80, new FieldDescriptor.Builder("textDetectionOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaD = a.C(81, new FieldDescriptor.Builder("onDeviceImageQualityAnalysisCreateLogEvent"));
    private static final FieldDescriptor zzaE = a.C(82, new FieldDescriptor.Builder("onDeviceImageQualityAnalysisLoadLogEvent"));
    private static final FieldDescriptor zzaF = a.C(83, new FieldDescriptor.Builder("onDeviceImageQualityAnalysisLogEvent"));
    private static final FieldDescriptor zzaG = a.C(84, new FieldDescriptor.Builder("aggregatedOnDeviceImageQualityAnalysisLogEvent"));
    private static final FieldDescriptor zzaH = a.C(88, new FieldDescriptor.Builder("imageQualityAnalysisOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaI = a.C(89, new FieldDescriptor.Builder("imageCaptioningOptionalModuleLogEvent"));
    private static final FieldDescriptor zzaJ = a.C(90, new FieldDescriptor.Builder("onDeviceImageCaptioningCreateLogEvent"));
    private static final FieldDescriptor zzaK = a.C(91, new FieldDescriptor.Builder("onDeviceImageCaptioningLoadLogEvent"));
    private static final FieldDescriptor zzaL = a.C(92, new FieldDescriptor.Builder("onDeviceImageCaptioningInferenceLogEvent"));
    private static final FieldDescriptor zzaM = a.C(93, new FieldDescriptor.Builder("aggregatedOnDeviceImageCaptioningInferenceLogEvent"));

    private zzeo() {
    }

    @Override // com.google.firebase.encoders.ObjectEncoder
    public final /* bridge */ /* synthetic */ void encode(Object obj, Object obj2) throws IOException {
        zziy zziyVar = (zziy) obj;
        ObjectEncoderContext objectEncoderContext = (ObjectEncoderContext) obj2;
        objectEncoderContext.add(zzb, zziyVar.zzc());
        objectEncoderContext.add(zzc, zziyVar.zzb());
        objectEncoderContext.add(zzd, (Object) null);
        objectEncoderContext.add(zze, (Object) null);
        objectEncoderContext.add(zzf, (Object) null);
        objectEncoderContext.add(zzg, (Object) null);
        objectEncoderContext.add(zzh, (Object) null);
        objectEncoderContext.add(zzi, (Object) null);
        objectEncoderContext.add(zzj, (Object) null);
        objectEncoderContext.add(zzk, (Object) null);
        objectEncoderContext.add(zzl, (Object) null);
        objectEncoderContext.add(zzm, (Object) null);
        objectEncoderContext.add(zzn, (Object) null);
        objectEncoderContext.add(zzo, (Object) null);
        objectEncoderContext.add(zzp, (Object) null);
        objectEncoderContext.add(zzq, (Object) null);
        objectEncoderContext.add(zzr, (Object) null);
        objectEncoderContext.add(zzs, (Object) null);
        objectEncoderContext.add(zzt, (Object) null);
        objectEncoderContext.add(zzu, (Object) null);
        objectEncoderContext.add(zzv, (Object) null);
        objectEncoderContext.add(zzw, (Object) null);
        objectEncoderContext.add(zzx, (Object) null);
        objectEncoderContext.add(zzy, (Object) null);
        objectEncoderContext.add(zzz, (Object) null);
        objectEncoderContext.add(zzA, (Object) null);
        objectEncoderContext.add(zzB, (Object) null);
        objectEncoderContext.add(zzC, (Object) null);
        objectEncoderContext.add(zzD, (Object) null);
        objectEncoderContext.add(zzE, (Object) null);
        objectEncoderContext.add(zzF, (Object) null);
        objectEncoderContext.add(zzG, (Object) null);
        objectEncoderContext.add(zzH, (Object) null);
        objectEncoderContext.add(zzI, (Object) null);
        objectEncoderContext.add(zzJ, (Object) null);
        objectEncoderContext.add(zzK, (Object) null);
        objectEncoderContext.add(zzL, (Object) null);
        objectEncoderContext.add(zzM, (Object) null);
        objectEncoderContext.add(zzN, (Object) null);
        objectEncoderContext.add(zzO, (Object) null);
        objectEncoderContext.add(zzP, (Object) null);
        objectEncoderContext.add(zzQ, (Object) null);
        objectEncoderContext.add(zzR, (Object) null);
        objectEncoderContext.add(zzS, (Object) null);
        objectEncoderContext.add(zzT, (Object) null);
        objectEncoderContext.add(zzU, (Object) null);
        objectEncoderContext.add(zzV, (Object) null);
        objectEncoderContext.add(zzW, (Object) null);
        objectEncoderContext.add(zzX, (Object) null);
        objectEncoderContext.add(zzY, (Object) null);
        objectEncoderContext.add(zzZ, (Object) null);
        objectEncoderContext.add(zzaa, zziyVar.zza());
        objectEncoderContext.add(zzab, (Object) null);
        objectEncoderContext.add(zzac, (Object) null);
        objectEncoderContext.add(zzad, (Object) null);
        objectEncoderContext.add(zzae, (Object) null);
        objectEncoderContext.add(zzaf, (Object) null);
        objectEncoderContext.add(zzag, (Object) null);
        objectEncoderContext.add(zzah, (Object) null);
        objectEncoderContext.add(zzai, (Object) null);
        objectEncoderContext.add(zzaj, (Object) null);
        objectEncoderContext.add(zzak, (Object) null);
        objectEncoderContext.add(zzal, (Object) null);
        objectEncoderContext.add(zzam, (Object) null);
        objectEncoderContext.add(zzan, (Object) null);
        objectEncoderContext.add(zzao, (Object) null);
        objectEncoderContext.add(zzap, (Object) null);
        objectEncoderContext.add(zzaq, (Object) null);
        objectEncoderContext.add(zzar, (Object) null);
        objectEncoderContext.add(zzas, (Object) null);
        objectEncoderContext.add(zzat, (Object) null);
        objectEncoderContext.add(zzau, (Object) null);
        objectEncoderContext.add(zzav, (Object) null);
        objectEncoderContext.add(zzaw, (Object) null);
        objectEncoderContext.add(zzax, (Object) null);
        objectEncoderContext.add(zzay, (Object) null);
        objectEncoderContext.add(zzaz, (Object) null);
        objectEncoderContext.add(zzaA, (Object) null);
        objectEncoderContext.add(zzaB, (Object) null);
        objectEncoderContext.add(zzaC, (Object) null);
        objectEncoderContext.add(zzaD, (Object) null);
        objectEncoderContext.add(zzaE, (Object) null);
        objectEncoderContext.add(zzaF, (Object) null);
        objectEncoderContext.add(zzaG, (Object) null);
        objectEncoderContext.add(zzaH, (Object) null);
        objectEncoderContext.add(zzaI, (Object) null);
        objectEncoderContext.add(zzaJ, (Object) null);
        objectEncoderContext.add(zzaK, (Object) null);
        objectEncoderContext.add(zzaL, (Object) null);
        objectEncoderContext.add(zzaM, (Object) null);
    }
}
