package com.woolworths.shop.checkout.fragment.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.shop.graphql.type.AddressType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.BroadcastBanner;
import au.com.woolworths.shop.graphql.type.BroadcastBannerType;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.CartProductInfo;
import au.com.woolworths.shop.graphql.type.CheckoutCollectionAddress;
import au.com.woolworths.shop.graphql.type.CheckoutCollectionMethodOption;
import au.com.woolworths.shop.graphql.type.CheckoutDeliveryPreferenceId;
import au.com.woolworths.shop.graphql.type.CheckoutFulfilmentWindows;
import au.com.woolworths.shop.graphql.type.CheckoutInfoDialog;
import au.com.woolworths.shop.graphql.type.CheckoutMarketPickupBottomSheet;
import au.com.woolworths.shop.graphql.type.CheckoutOrderTotalDetails;
import au.com.woolworths.shop.graphql.type.CheckoutOrderTotalDetailsRow;
import au.com.woolworths.shop.graphql.type.CheckoutOrderTotalDetailsRowMessage;
import au.com.woolworths.shop.graphql.type.CheckoutOrderTotalDetailsSummaryRow;
import au.com.woolworths.shop.graphql.type.CheckoutPackagingOption;
import au.com.woolworths.shop.graphql.type.CheckoutProductCampaignItem;
import au.com.woolworths.shop.graphql.type.CheckoutProductInfo;
import au.com.woolworths.shop.graphql.type.CheckoutProductInstruction;
import au.com.woolworths.shop.graphql.type.CheckoutProductRewards;
import au.com.woolworths.shop.graphql.type.CheckoutProductRow;
import au.com.woolworths.shop.graphql.type.CheckoutProductSubstitutionPreference;
import au.com.woolworths.shop.graphql.type.CheckoutProgressId;
import au.com.woolworths.shop.graphql.type.CheckoutReviewProductRow;
import au.com.woolworths.shop.graphql.type.CheckoutReviewProductsList;
import au.com.woolworths.shop.graphql.type.CheckoutReviewSupplyLimitGroups;
import au.com.woolworths.shop.graphql.type.CheckoutSegmentContent;
import au.com.woolworths.shop.graphql.type.CheckoutSegmentMessage;
import au.com.woolworths.shop.graphql.type.CheckoutSegmentProgress;
import au.com.woolworths.shop.graphql.type.CheckoutSubstitution;
import au.com.woolworths.shop.graphql.type.CheckoutSubstitutionOption;
import au.com.woolworths.shop.graphql.type.CheckoutSubstitutionPreferences;
import au.com.woolworths.shop.graphql.type.CheckoutSummaryValueType;
import au.com.woolworths.shop.graphql.type.CollectionModeId;
import au.com.woolworths.shop.graphql.type.ContentCta;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLFloat;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.IdVerificationBottomSheet;
import au.com.woolworths.shop.graphql.type.InlineMessage;
import au.com.woolworths.shop.graphql.type.InputTextLimit;
import au.com.woolworths.shop.graphql.type.InsetBanner;
import au.com.woolworths.shop.graphql.type.InsetBannerAction;
import au.com.woolworths.shop.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.shop.graphql.type.InsetBannerActionType;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.LegacyError;
import au.com.woolworths.shop.graphql.type.MarketFulfilmentAddressStatus;
import au.com.woolworths.shop.graphql.type.MarketProductRow;
import au.com.woolworths.shop.graphql.type.MarketSellerGroup;
import au.com.woolworths.shop.graphql.type.RestrictionPrompt;
import au.com.woolworths.shop.graphql.type.ShoppingModeDetails;
import au.com.woolworths.shop.graphql.type.SubstitutionState;
import com.apollographql.apollo.api.CompiledCondition;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.InterfaceType;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.google.android.gms.common.api.internal.a;
import com.google.android.gms.measurement.api.AppMeasurementSdk;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.salesforce.marketingcloud.storage.db.i;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/checkout/fragment/selections/CheckoutContentSelections;", "", "shop-checkout_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class CheckoutContentSelections {
    public static final List A;
    public static final List A0;
    public static final List B;
    public static final List B0;
    public static final List C;
    public static final List D;
    public static final List E;
    public static final List F;
    public static final List G;
    public static final List H;
    public static final List I;
    public static final List J;
    public static final List K;
    public static final List L;
    public static final List M;
    public static final List N;
    public static final List O;
    public static final List P;
    public static final List Q;
    public static final List R;
    public static final List S;
    public static final List T;
    public static final List U;
    public static final List V;
    public static final List W;
    public static final List X;
    public static final List Y;
    public static final List Z;

    /* renamed from: a, reason: collision with root package name */
    public static final List f22539a;
    public static final List a0;
    public static final List b;
    public static final List b0;
    public static final List c;
    public static final List c0;
    public static final List d;
    public static final List d0;
    public static final List e;
    public static final List e0;
    public static final List f;
    public static final List f0;
    public static final List g;
    public static final List g0;
    public static final List h;
    public static final List h0;
    public static final List i;
    public static final List i0;
    public static final List j;
    public static final List j0;
    public static final List k;
    public static final List k0;
    public static final List l;
    public static final List l0;
    public static final List m;
    public static final List m0;
    public static final List n;
    public static final List n0;
    public static final List o;
    public static final List o0;
    public static final List p;
    public static final List p0;
    public static final List q;
    public static final List q0;
    public static final List r;
    public static final List r0;
    public static final List s;
    public static final List s0;
    public static final List t;
    public static final List t0;
    public static final List u;
    public static final List u0;
    public static final List v;
    public static final List v0;
    public static final List w;
    public static final List w0;
    public static final List x;
    public static final List x0;
    public static final List y;
    public static final List y0;
    public static final List z;
    public static final List z0;

    static {
        List listR = CollectionsKt.R(new CompiledField.Builder("productId", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("productName", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("price", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c(), new CompiledField.Builder("quantity", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c(), new CompiledField.Builder("subtotal", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c(), new CompiledField.Builder("isAvailable", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("sellerName", GraphQLString.Companion.a()).c(), new CompiledField.Builder("brandName", GraphQLString.Companion.a()).c(), new CompiledField.Builder("dispatchNote", GraphQLString.Companion.a()).c());
        f22539a = listR;
        List listR2 = CollectionsKt.R(new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("eventSource", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        b = listR2;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("SnackBar", CollectionsKt.Q("SnackBar"));
        builder.b(listR2);
        List listR3 = CollectionsKt.R(compiledFieldC, builder.a());
        c = listR3;
        List listR4 = CollectionsKt.R(new CompiledField.Builder("errorCode", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("key", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        d = listR4;
        CompiledField compiledFieldC2 = new CompiledField.Builder("index", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CheckoutProgressId.e.getClass();
        EnumType enumType = CheckoutProgressId.f;
        List listR5 = CollectionsKt.R(compiledFieldC2, new CompiledField.Builder("id", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        e = listR5;
        InsetBannerActionPlacement.e.getClass();
        CompiledField compiledFieldC3 = new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.Companion.a())).c();
        InsetBannerActionType.e.getClass();
        List listR6 = CollectionsKt.R(compiledFieldC3, new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        f = listR6;
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC4 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField compiledFieldC5 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType = InsetBannerAction.f11510a;
        CompiledField.Builder builder2 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.Companion.a());
        builder2.e(listR6);
        List listR7 = CollectionsKt.R(compiledFieldC4, compiledFieldC5, builder2.c());
        g = listR7;
        List listR8 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("displayName", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("buttonText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        h = listR8;
        CollectionModeId.e.getClass();
        EnumType enumType2 = CollectionModeId.f;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("modeId", CompiledGraphQL.b(enumType2)).c());
        i = listQ;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("CheckoutCollectionAddressDelivery", CollectionsKt.Q("CheckoutCollectionAddressDelivery"));
        builder3.b(listQ);
        List listR9 = CollectionsKt.R(compiledFieldC6, builder3.a());
        j = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder("displayName", GraphQLString.Companion.a()).c(), new CompiledField.Builder("mode", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("storeAddressId", GraphQLInt.Companion.a()).c());
        k = listR10;
        CompiledField compiledFieldC7 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC8 = new CompiledField.Builder("displayName", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC9 = new CompiledField.Builder("addressButtonTitle", GraphQLString.Companion.a()).c();
        MarketFulfilmentAddressStatus.e.getClass();
        CompiledField compiledFieldC10 = new CompiledField.Builder("addressStatus", CompiledGraphQL.b(MarketFulfilmentAddressStatus.Companion.a())).c();
        AddressType.e.getClass();
        CompiledField compiledFieldC11 = new CompiledField.Builder("addressType", CompiledGraphQL.b(AddressType.Companion.a())).c();
        UnionType unionType = CheckoutCollectionAddress.f11185a;
        CompiledField.Builder builder4 = new CompiledField.Builder("addressData", unionType);
        builder4.e(listR9);
        CompiledField compiledFieldC12 = builder4.c();
        ObjectType objectType2 = ShoppingModeDetails.f11899a;
        CompiledField.Builder builder5 = new CompiledField.Builder("shoppingModeDetails", CompiledGraphQL.b(objectType2));
        builder5.e(listR10);
        List listR11 = CollectionsKt.R(compiledFieldC7, compiledFieldC8, compiledFieldC9, compiledFieldC10, compiledFieldC11, compiledFieldC12, builder5.c());
        l = listR11;
        CompiledField compiledFieldC13 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("CheckoutCollectionAddressDelivery", CollectionsKt.Q("CheckoutCollectionAddressDelivery"));
        List list = CheckoutCollectionAddressDeliverySelections.f22538a;
        builder6.b(list);
        List listR12 = CollectionsKt.R(compiledFieldC13, builder6.a());
        m = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("modeId", CompiledGraphQL.b(enumType2)).c(), new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("addressId", GraphQLInt.Companion.a()).c());
        n = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("modeId", CompiledGraphQL.b(enumType2)).c(), new CompiledField.Builder("storeId", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("addressId", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder("displayName", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("addressImageUrl", GraphQLString.Companion.a()).c(), new CompiledField.Builder("buttonText", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        o = listR14;
        CompiledField compiledFieldC14 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("CheckoutCollectionAddressDelivery", CollectionsKt.Q("CheckoutCollectionAddressDelivery"));
        builder7.b(list);
        CompiledFragment compiledFragmentA = builder7.a();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("CheckoutCollectionAddressPickup", CollectionsKt.Q("CheckoutCollectionAddressPickup"));
        builder8.b(listR14);
        List listR15 = CollectionsKt.R(compiledFieldC14, compiledFragmentA, builder8.a());
        p = listR15;
        List listR16 = CollectionsKt.R(new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        q = listR16;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        r = listQ2;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        s = listQ3;
        CompiledField compiledFieldC15 = new CompiledField.Builder("bottomSheetTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("bottomSheetBody", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("showOnceOnly", GraphQLBoolean.Companion.a()).c();
        ObjectType objectType3 = ContentCta.f11282a;
        CompiledField.Builder builder9 = new CompiledField.Builder("primaryCta", ContentCta.Companion.a());
        builder9.e(listQ2);
        CompiledField compiledFieldC18 = builder9.c();
        CompiledField.Builder builder10 = new CompiledField.Builder("secondaryCta", ContentCta.Companion.a());
        builder10.e(listQ3);
        List listR17 = CollectionsKt.R(compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, builder10.c());
        t = listR17;
        List listR18 = CollectionsKt.R(new CompiledField.Builder("displayName", GraphQLString.Companion.a()).c(), new CompiledField.Builder("mode", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("storeAddressId", GraphQLInt.Companion.a()).c());
        u = listR18;
        CompiledField compiledFieldC19 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType4 = CheckoutCollectionMethodOption.f11190a;
        CompiledField.Builder builder11 = new CompiledField.Builder("options", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutCollectionMethodOption.Companion.a()))));
        builder11.e(listR13);
        CompiledField compiledFieldC20 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("address", CompiledGraphQL.b(unionType));
        builder12.e(listR15);
        CompiledField compiledFieldC21 = builder12.c();
        ObjectType objectType5 = InsetBanner.f11509a;
        CompiledField.Builder builder13 = new CompiledField.Builder("insetBanner", InsetBanner.Companion.a());
        builder13.e(listR16);
        CompiledField compiledFieldC22 = builder13.c();
        ObjectType objectType6 = CheckoutMarketPickupBottomSheet.f11215a;
        CompiledField compiledFieldE = a.e("includeMarketPickupSheet", false, new CompiledField.Builder("marketPickupSheet", CheckoutMarketPickupBottomSheet.Companion.a()), listR17);
        CompiledField.Builder builder14 = new CompiledField.Builder("shoppingModeDetails", CompiledGraphQL.b(objectType2));
        builder14.e(listR18);
        List listR19 = CollectionsKt.R(compiledFieldC19, compiledFieldC20, compiledFieldC21, compiledFieldC22, compiledFieldE, builder14.c());
        v = listR19;
        CompiledField compiledFieldC23 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("CheckoutFulfilmentWindows", CollectionsKt.Q("CheckoutFulfilmentWindows"));
        List list2 = CheckoutFulfilmentWindowsSelections.a0;
        builder15.b(list2);
        List listR20 = CollectionsKt.R(compiledFieldC23, builder15.a());
        w = listR20;
        List listR21 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        x = listR21;
        List listR22 = CollectionsKt.R(new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        y = listR22;
        CompiledField compiledFieldC24 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("CheckoutFulfilmentWindows", CollectionsKt.Q("CheckoutFulfilmentWindows"));
        builder16.b(list2);
        List listR23 = CollectionsKt.R(compiledFieldC24, builder16.a());
        z = listR23;
        CompiledField compiledFieldC25 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC26 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC27 = new CompiledField.Builder("timeWindow", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC28 = new CompiledField.Builder("price", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC29 = new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType7 = InlineMessage.f11507a;
        CompiledField.Builder builder17 = new CompiledField.Builder("inlineMessage", InlineMessage.Companion.a());
        builder17.e(listR22);
        CompiledField compiledFieldC30 = builder17.c();
        ObjectType objectType8 = CheckoutFulfilmentWindows.f11210a;
        CompiledField.Builder builder18 = new CompiledField.Builder("windows", CompiledGraphQL.b(CheckoutFulfilmentWindows.Companion.a()));
        builder18.e(listR23);
        List listR24 = CollectionsKt.R(compiledFieldC25, compiledFieldC26, compiledFieldC27, compiledFieldC28, compiledFieldC29, compiledFieldC30, builder18.c());
        A = listR24;
        List listR25 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("price", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, GraphQLString.Companion.a()).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        B = listR25;
        CompiledField compiledFieldC31 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType9 = CheckoutPackagingOption.f11228a;
        CompiledField.Builder builder19 = new CompiledField.Builder("options", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutPackagingOption.Companion.a()))));
        builder19.e(listR25);
        List listR26 = CollectionsKt.R(compiledFieldC31, builder19.c());
        C = listR26;
        List listR27 = CollectionsKt.R(new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        D = listR27;
        CheckoutDeliveryPreferenceId.e.getClass();
        EnumType enumType3 = CheckoutDeliveryPreferenceId.f;
        CompiledField compiledFieldC32 = new CompiledField.Builder("preferenceId", CompiledGraphQL.b(enumType3)).c();
        CompiledField compiledFieldC33 = new CompiledField.Builder("isEnabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC34 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC35 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC36 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC37 = new CompiledField.Builder("value", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField.Builder builder20 = new CompiledField.Builder("inlineMessage", InlineMessage.Companion.a());
        builder20.e(listR27);
        List listR28 = CollectionsKt.R(compiledFieldC32, compiledFieldC33, compiledFieldC34, compiledFieldC35, compiledFieldC36, compiledFieldC37, builder20.c());
        E = listR28;
        List listR29 = CollectionsKt.R(new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        F = listR29;
        CompiledField compiledFieldC38 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC39 = new CompiledField.Builder("phoneNumberLabel", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC40 = new CompiledField.Builder("phoneNumber", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC41 = new CompiledField.Builder("placeholder", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC42 = new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder21 = new CompiledField.Builder("inlineMessage", InlineMessage.Companion.a());
        builder21.e(listR29);
        List listR30 = CollectionsKt.R(compiledFieldC38, compiledFieldC39, compiledFieldC40, compiledFieldC41, compiledFieldC42, builder21.c());
        G = listR30;
        List listR31 = CollectionsKt.R(new CompiledField.Builder("maxLength", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder("warningOffset", CompiledGraphQL.b(GraphQLInt.Companion.a())).c());
        H = listR31;
        List listR32 = CollectionsKt.R(new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        I = listR32;
        CompiledField compiledFieldC43 = new CompiledField.Builder("preferenceId", CompiledGraphQL.b(enumType3)).c();
        CompiledField compiledFieldC44 = new CompiledField.Builder("isEnabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC45 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType10 = InputTextLimit.f11508a;
        CompiledField.Builder builder22 = new CompiledField.Builder("inputLimit", objectType10);
        builder22.e(listR31);
        CompiledField compiledFieldC46 = builder22.c();
        CompiledField compiledFieldC47 = new CompiledField.Builder("descriptionText", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC48 = new CompiledField.Builder("placeholderText", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC49 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC50 = new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder23 = new CompiledField.Builder("inlineMessage", InlineMessage.Companion.a());
        builder23.e(listR32);
        List listR33 = CollectionsKt.R(compiledFieldC43, compiledFieldC44, compiledFieldC45, compiledFieldC46, compiledFieldC47, compiledFieldC48, compiledFieldC49, compiledFieldC50, builder23.c());
        J = listR33;
        List listR34 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        K = listR34;
        List listR35 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        L = listR35;
        CompiledField compiledFieldC51 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC52 = new CompiledField.Builder("selectedOptionTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType11 = CheckoutSubstitutionOption.f11260a;
        CompiledField.Builder builder24 = new CompiledField.Builder("options", CompiledGraphQL.b(CompiledGraphQL.a(CheckoutSubstitutionOption.Companion.a())));
        builder24.e(listR34);
        CompiledField compiledFieldC53 = builder24.c();
        ObjectType objectType12 = CheckoutInfoDialog.f11213a;
        CompiledField.Builder builder25 = new CompiledField.Builder("info", CompiledGraphQL.b(CheckoutInfoDialog.Companion.a()));
        builder25.e(listR35);
        List listR36 = CollectionsKt.R(compiledFieldC51, compiledFieldC52, compiledFieldC53, builder25.c());
        M = listR36;
        List listR37 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        N = listR37;
        CompiledField compiledFieldC54 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC55 = new CompiledField.Builder("body", GraphQLString.Companion.a()).c();
        SubstitutionState.e.getClass();
        EnumType enumType4 = SubstitutionState.f;
        CompiledField compiledFieldC56 = new CompiledField.Builder("state", CompiledGraphQL.b(enumType4)).c();
        CompiledField.Builder builder26 = new CompiledField.Builder("info", CompiledGraphQL.b(CheckoutInfoDialog.Companion.a()));
        builder26.e(listR37);
        List listR38 = CollectionsKt.R(compiledFieldC54, compiledFieldC55, compiledFieldC56, builder26.c());
        O = listR38;
        List listR39 = CollectionsKt.R(new CompiledField.Builder("maxLength", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder("warningOffset", CompiledGraphQL.b(GraphQLInt.Companion.a())).c());
        P = listR39;
        CompiledField compiledFieldC57 = new CompiledField.Builder(TextBundle.TEXT_ENTRY, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC58 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC59 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC60 = new CompiledField.Builder("placeholderText", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC61 = new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder27 = new CompiledField.Builder("inputLimit", objectType10);
        builder27.e(listR39);
        List listR40 = CollectionsKt.R(compiledFieldC57, compiledFieldC58, compiledFieldC59, compiledFieldC60, compiledFieldC61, builder27.c());
        Q = listR40;
        List listR41 = CollectionsKt.R(new CompiledField.Builder("points", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        R = listR41;
        List listR42 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        S = listR42;
        List listR43 = CollectionsKt.R(new CompiledField.Builder("totalPrice", GraphQLString.Companion.a()).c(), new CompiledField.Builder("totalOriginalPrice", GraphQLString.Companion.a()).c(), new CompiledField.Builder("totalDiscount", GraphQLString.Companion.a()).c());
        T = listR43;
        List listR44 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        U = listR44;
        CompiledField compiledFieldC62 = new CompiledField.Builder("state", CompiledGraphQL.b(enumType4)).c();
        CompiledField compiledFieldC63 = new CompiledField.Builder("header", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC64 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType13 = Button.f11080a;
        CompiledField.Builder builder28 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(Button.Companion.a()));
        builder28.e(listR44);
        List listR45 = CollectionsKt.R(compiledFieldC62, compiledFieldC63, compiledFieldC64, builder28.c());
        V = listR45;
        CompiledField compiledFieldC65 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC66 = new CompiledField.Builder("quantity", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c();
        CompiledField compiledFieldC67 = new CompiledField.Builder("productId", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC68 = new CompiledField.Builder("unitPrice", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC69 = new CompiledField.Builder("totalPrice", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC70 = new CompiledField.Builder("totalTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC71 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType14 = CheckoutProductInstruction.f11232a;
        CompiledField.Builder builder29 = new CompiledField.Builder("instruction", CompiledGraphQL.b(CheckoutProductInstruction.Companion.a()));
        builder29.e(listR40);
        CompiledField compiledFieldC72 = builder29.c();
        ObjectType objectType15 = CheckoutProductRewards.f11233a;
        CompiledField.Builder builder30 = new CompiledField.Builder("rewards", CheckoutProductRewards.Companion.a());
        builder30.e(listR41);
        CompiledField compiledFieldC73 = builder30.c();
        CompiledField.Builder builder31 = new CompiledField.Builder("removeInfo", CompiledGraphQL.b(CheckoutInfoDialog.Companion.a()));
        builder31.e(listR42);
        CompiledField compiledFieldC74 = builder31.c();
        CompiledField compiledFieldC75 = new CompiledField.Builder("allowSubstitution", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC76 = new CompiledField.Builder(i.e, CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        CompiledField compiledFieldC77 = new CompiledField.Builder("showSubstitution", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        ObjectType objectType16 = CartProductInfo.f11112a;
        CompiledField.Builder builder32 = new CompiledField.Builder("cartProductInfo", objectType16);
        builder32.e(listR43);
        CompiledField compiledFieldC78 = builder32.c();
        ObjectType objectType17 = CheckoutProductSubstitutionPreference.f11235a;
        CompiledField.Builder builder33 = new CompiledField.Builder("substitutionPreference", CheckoutProductSubstitutionPreference.Companion.a());
        builder33.e(listR45);
        List listR46 = CollectionsKt.R(compiledFieldC65, compiledFieldC66, compiledFieldC67, compiledFieldC68, compiledFieldC69, compiledFieldC70, compiledFieldC71, compiledFieldC72, compiledFieldC73, compiledFieldC74, compiledFieldC75, compiledFieldC76, compiledFieldC77, compiledFieldC78, builder33.c());
        W = listR46;
        CompiledField compiledFieldC79 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC80 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC81 = new CompiledField.Builder("deeplink", GraphQLString.Companion.a()).c();
        BroadcastBannerType.e.getClass();
        List listR47 = CollectionsKt.R(compiledFieldC79, compiledFieldC80, compiledFieldC81, new CompiledField.Builder("type", CompiledGraphQL.b(BroadcastBannerType.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("actionLabel", GraphQLString.Companion.a()).c(), new CompiledField.Builder("analyticsLabel", GraphQLString.Companion.a()).c(), new CompiledField.Builder("dismissible", GraphQLBoolean.Companion.a()).c(), new CompiledField.Builder("bannerId", GraphQLString.Companion.a()).c());
        X = listR47;
        CompiledField compiledFieldC82 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC83 = new CompiledField.Builder("descriptionText", GraphQLString.Companion.a()).c();
        ObjectType objectType18 = CheckoutSubstitution.f11258a;
        CompiledField.Builder builder34 = new CompiledField.Builder("substitution", CheckoutSubstitution.Companion.a());
        builder34.e(listR36);
        CompiledField compiledFieldC84 = builder34.c();
        ObjectType objectType19 = CheckoutSubstitutionPreferences.f11261a;
        CompiledField.Builder builder35 = new CompiledField.Builder("substitutionPreferences", CheckoutSubstitutionPreferences.Companion.a());
        builder35.e(listR38);
        CompiledField compiledFieldC85 = builder35.c();
        ObjectType objectType20 = CheckoutProductRow.f11234a;
        CompiledField.Builder builder36 = new CompiledField.Builder("products", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutProductRow.Companion.a()))));
        builder36.e(listR46);
        CompiledField compiledFieldC86 = builder36.c();
        CompiledField compiledFieldC87 = new CompiledField.Builder("useSubstitutionPreference", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField.Builder builder37 = new CompiledField.Builder("substitutionPreferenceOnboardingBanner", BroadcastBanner.f11060a);
        builder37.e(listR47);
        List listR48 = CollectionsKt.R(compiledFieldC82, compiledFieldC83, compiledFieldC84, compiledFieldC85, compiledFieldC86, compiledFieldC87, builder37.c());
        Y = listR48;
        List listR49 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        Z = listR49;
        List listR50 = CollectionsKt.R(new CompiledField.Builder("totalPrice", GraphQLString.Companion.a()).c(), new CompiledField.Builder("totalOriginalPrice", GraphQLString.Companion.a()).c(), new CompiledField.Builder("totalDiscount", GraphQLString.Companion.a()).c());
        a0 = listR50;
        CompiledField compiledFieldC88 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC89 = new CompiledField.Builder("quantity", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c();
        CompiledField compiledFieldC90 = new CompiledField.Builder("productId", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC91 = new CompiledField.Builder("unitPrice", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC92 = new CompiledField.Builder("totalPrice", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC93 = new CompiledField.Builder("totalTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC94 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC95 = new CompiledField.Builder("brandName", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder38 = new CompiledField.Builder("removeInfo", CompiledGraphQL.b(CheckoutInfoDialog.Companion.a()));
        builder38.e(listR49);
        CompiledField compiledFieldC96 = builder38.c();
        CompiledField.Builder builder39 = new CompiledField.Builder("cartProductInfo", objectType16);
        builder39.e(listR50);
        List listR51 = CollectionsKt.R(compiledFieldC88, compiledFieldC89, compiledFieldC90, compiledFieldC91, compiledFieldC92, compiledFieldC93, compiledFieldC94, compiledFieldC95, compiledFieldC96, builder39.c());
        b0 = listR51;
        CompiledField compiledFieldC97 = new CompiledField.Builder("sellerName", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC98 = new CompiledField.Builder("dispatchNote", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType21 = MarketProductRow.f11549a;
        CompiledField.Builder builder40 = new CompiledField.Builder("products", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(MarketProductRow.Companion.a()))));
        builder40.e(listR51);
        List listR52 = CollectionsKt.R(compiledFieldC97, compiledFieldC98, builder40.c());
        c0 = listR52;
        CompiledField compiledFieldC99 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC100 = new CompiledField.Builder("descriptionText", GraphQLString.Companion.a()).c();
        ObjectType objectType22 = MarketSellerGroup.f11551a;
        CompiledField.Builder builder41 = new CompiledField.Builder("sellerGroups", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(MarketSellerGroup.Companion.a()))));
        builder41.e(listR52);
        List listR53 = CollectionsKt.R(compiledFieldC99, compiledFieldC100, builder41.c());
        d0 = listR53;
        List listR54 = CollectionsKt.R(new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        e0 = listR54;
        CompiledField compiledFieldC101 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC102 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC103 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC104 = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC105 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC106 = new CompiledField.Builder("isOptedIn", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField.Builder builder42 = new CompiledField.Builder("campaignInfo", CompiledGraphQL.b(CheckoutInfoDialog.Companion.a()));
        builder42.e(listR54);
        List listR55 = CollectionsKt.R(compiledFieldC101, compiledFieldC102, compiledFieldC103, compiledFieldC104, compiledFieldC105, compiledFieldC106, builder42.c());
        f0 = listR55;
        ObjectType objectType23 = CheckoutProductCampaignItem.f11229a;
        CompiledField.Builder builder43 = new CompiledField.Builder("campaigns", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutProductCampaignItem.Companion.a()))));
        builder43.e(listR55);
        List listQ4 = CollectionsKt.Q(builder43.c());
        g0 = listQ4;
        List listR56 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        h0 = listR56;
        CompiledField compiledFieldC107 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder44 = new CompiledFragment.Builder("InsetBanner", CollectionsKt.Q("InsetBanner"));
        builder44.b(listR7);
        CompiledFragment compiledFragmentA2 = builder44.a();
        CompiledFragment.Builder builder45 = new CompiledFragment.Builder("CheckoutCollectionAddressEmpty", CollectionsKt.Q("CheckoutCollectionAddressEmpty"));
        builder45.b(listR8);
        CompiledFragment compiledFragmentA3 = builder45.a();
        CompiledFragment.Builder builder46 = new CompiledFragment.Builder("CheckoutMarketFulfilmentAddress", CollectionsKt.Q("CheckoutMarketFulfilmentAddress"));
        builder46.b(listR11);
        CompiledFragment compiledFragmentA4 = builder46.a();
        CompiledFragment.Builder builder47 = new CompiledFragment.Builder("CheckoutCollectionAddressDelivery", CollectionsKt.Q("CheckoutCollectionAddressDelivery"));
        builder47.b(listR12);
        CompiledFragment compiledFragmentA5 = builder47.a();
        CompiledFragment.Builder builder48 = new CompiledFragment.Builder("CheckoutCollectionMethod", CollectionsKt.Q("CheckoutCollectionMethod"));
        builder48.b(listR19);
        CompiledFragment compiledFragmentA6 = builder48.a();
        CompiledFragment.Builder builder49 = new CompiledFragment.Builder("CheckoutFulfilmentWindows", CollectionsKt.Q("CheckoutFulfilmentWindows"));
        builder49.b(listR20);
        CompiledFragment compiledFragmentA7 = builder49.a();
        CompiledFragment.Builder builder50 = new CompiledFragment.Builder("CheckoutFulfilmentWindowsEmptyState", CollectionsKt.Q("CheckoutFulfilmentWindowsEmptyState"));
        builder50.b(listR21);
        CompiledFragment compiledFragmentA8 = builder50.a();
        CompiledFragment.Builder builder51 = new CompiledFragment.Builder("CheckoutFulfilmentWindowsSelectedState", CollectionsKt.Q("CheckoutFulfilmentWindowsSelectedState"));
        builder51.b(listR24);
        CompiledFragment compiledFragmentA9 = builder51.a();
        CompiledFragment.Builder builder52 = new CompiledFragment.Builder("CheckoutPackagingMethod", CollectionsKt.Q("CheckoutPackagingMethod"));
        builder52.b(listR26);
        CompiledFragment compiledFragmentA10 = builder52.a();
        CompiledFragment.Builder builder53 = new CompiledFragment.Builder("CheckoutDeliveryPreferenceToggle", CollectionsKt.Q("CheckoutDeliveryPreferenceToggle"));
        builder53.b(listR28);
        CompiledFragment compiledFragmentA11 = builder53.a();
        CompiledFragment compiledFragmentI = d.i("includeContactDetails", false, new CompiledFragment.Builder("CheckoutContactDetails", CollectionsKt.Q("CheckoutContactDetails")), listR30);
        CompiledFragment.Builder builder54 = new CompiledFragment.Builder("CheckoutDeliveryPreferenceText", CollectionsKt.Q("CheckoutDeliveryPreferenceText"));
        builder54.b(listR33);
        CompiledFragment compiledFragmentA12 = builder54.a();
        CompiledFragment.Builder builder55 = new CompiledFragment.Builder("CheckoutProducts", CollectionsKt.Q("CheckoutProducts"));
        builder55.b(listR48);
        CompiledFragment compiledFragmentA13 = builder55.a();
        CompiledFragment.Builder builder56 = new CompiledFragment.Builder("CheckoutMarketProducts", CollectionsKt.Q("CheckoutMarketProducts"));
        builder56.b(listR53);
        CompiledFragment compiledFragmentA14 = builder56.a();
        CompiledFragment.Builder builder57 = new CompiledFragment.Builder("CheckoutProductCampaigns", CollectionsKt.Q("CheckoutProductCampaigns"));
        builder57.b(listQ4);
        CompiledFragment compiledFragmentA15 = builder57.a();
        CompiledFragment.Builder builder58 = new CompiledFragment.Builder("CheckoutSectionHeader", CollectionsKt.Q("CheckoutSectionHeader"));
        builder58.b(listR56);
        List listR57 = CollectionsKt.R(compiledFieldC107, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, compiledFragmentA8, compiledFragmentA9, compiledFragmentA10, compiledFragmentA11, compiledFragmentI, compiledFragmentA12, compiledFragmentA13, compiledFragmentA14, compiledFragmentA15, builder58.a());
        i0 = listR57;
        List listR58 = CollectionsKt.R(new CompiledField.Builder("eventLabel", GraphQLString.Companion.a()).c(), new CompiledField.Builder("eventDescription", GraphQLString.Companion.a()).c(), new CompiledField.Builder("eventValue", GraphQLString.Companion.a()).c());
        j0 = listR58;
        CompiledField compiledFieldC108 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField compiledFieldC109 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType24 = Analytics.f11028a;
        CompiledField.Builder builder59 = new CompiledField.Builder("analytics", Analytics.Companion.a());
        builder59.e(listR58);
        List listR59 = CollectionsKt.R(compiledFieldC108, compiledFieldC109, builder59.c());
        k0 = listR59;
        List listR60 = CollectionsKt.R(new CompiledField.Builder("title", GraphQLString.Companion.a()).c(), new CompiledField.Builder("body", GraphQLString.Companion.a()).c(), new CompiledField.Builder("type", GraphQLString.Companion.a()).c());
        l0 = listR60;
        CompiledField compiledFieldC110 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CheckoutSummaryValueType.e.getClass();
        List listR61 = CollectionsKt.R(compiledFieldC110, new CompiledField.Builder("titleType", CompiledGraphQL.b(CheckoutSummaryValueType.Companion.a())).c(), new CompiledField.Builder("value", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("valueType", CompiledGraphQL.b(CheckoutSummaryValueType.Companion.a())).c(), new CompiledField.Builder("imageUrl", GraphQLString.Companion.a()).c(), a.e("includeServiceFees", false, new CompiledField.Builder("message", CheckoutOrderTotalDetailsRowMessage.f11225a), listR60));
        m0 = listR61;
        List listR62 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("value", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("balanceToPay", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c(), new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), au.com.woolworths.feature.rewards.everydayextras.signup.selections.a.d("progressId", enumType), new CompiledField.Builder("isEnabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        n0 = listR62;
        List listQ5 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        o0 = listQ5;
        List listQ6 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        p0 = listQ6;
        List listQ7 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        q0 = listQ7;
        InterfaceType interfaceType = CheckoutReviewProductRow.f11243a;
        CompiledField.Builder builder60 = new CompiledField.Builder("products", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder60.e(listQ7);
        List listQ8 = CollectionsKt.Q(builder60.c());
        r0 = listQ8;
        List listQ9 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        s0 = listQ9;
        List listQ10 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        t0 = listQ10;
        List listQ11 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        u0 = listQ11;
        CompiledField.Builder builder61 = new CompiledField.Builder("unavailableOrderItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder61.e(listQ5);
        CompiledField compiledFieldC111 = builder61.c();
        CompiledField.Builder builder62 = new CompiledField.Builder("restrictedOrderItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder62.e(listQ6);
        CompiledField compiledFieldC112 = builder62.c();
        CompiledField.Builder builder63 = new CompiledField.Builder("exceededSupplyLimitProductGroups", au.com.woolworths.feature.rewards.everydayextras.signup.selections.a.f(CheckoutReviewSupplyLimitGroups.f11245a));
        builder63.e(listQ8);
        CompiledField compiledFieldC113 = builder63.c();
        CompiledField.Builder builder64 = new CompiledField.Builder("restrictedProductsByDeliveryMethod", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder64.e(listQ9);
        CompiledField compiledFieldC114 = builder64.c();
        CompiledField.Builder builder65 = new CompiledField.Builder("restrictedProductsByDeliPlatter", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder65.e(listQ10);
        CompiledField compiledFieldC115 = builder65.c();
        CompiledField.Builder builder66 = new CompiledField.Builder("availableOrderItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder66.e(listQ11);
        List listR63 = CollectionsKt.R(compiledFieldC111, compiledFieldC112, compiledFieldC113, compiledFieldC114, compiledFieldC115, builder66.c());
        v0 = listR63;
        CompiledField.Builder builder67 = new CompiledField.Builder("inlineMessage", InlineMessage.Companion.a());
        builder67.e(listR59);
        CompiledField compiledFieldC116 = builder67.c();
        CompiledField.Builder builder68 = new CompiledField.Builder("sections", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutOrderTotalDetailsRow.f11224a))))));
        builder68.e(listR61);
        CompiledField compiledFieldC117 = builder68.c();
        CompiledField.Builder builder69 = new CompiledField.Builder("total", CompiledGraphQL.b(CheckoutOrderTotalDetailsSummaryRow.f11226a));
        builder69.e(listR62);
        CompiledField compiledFieldC118 = builder69.c();
        CompiledField.Builder builder70 = new CompiledField.Builder("reviewProducts", CheckoutReviewProductsList.f11244a);
        builder70.e(listR63);
        CompiledField compiledFieldC119 = builder70.c();
        CompiledField.Builder builder71 = new CompiledField.Builder("panelMarkdown", GraphQLString.Companion.a());
        builder71.d(CollectionsKt.Q(new CompiledCondition("includePanelMarkdown", false)));
        List listR64 = CollectionsKt.R(compiledFieldC116, compiledFieldC117, compiledFieldC118, compiledFieldC119, builder71.c());
        w0 = listR64;
        CompiledField compiledFieldC120 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ButtonStyle.e.getClass();
        List listR65 = CollectionsKt.R(compiledFieldC120, new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        x0 = listR65;
        List listR66 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        y0 = listR66;
        CompiledField compiledFieldC121 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC122 = new CompiledField.Builder("body", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC123 = new CompiledField.Builder("imageUrls", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        CompiledField.Builder builder72 = new CompiledField.Builder("primaryButton", Button.Companion.a());
        builder72.e(listR65);
        CompiledField compiledFieldC124 = builder72.c();
        CompiledField.Builder builder73 = new CompiledField.Builder("secondaryButton", Button.Companion.a());
        builder73.e(listR66);
        List listR67 = CollectionsKt.R(compiledFieldC121, compiledFieldC122, compiledFieldC123, compiledFieldC124, builder73.c());
        z0 = listR67;
        List listR68 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        A0 = listR68;
        CompiledField.Builder builder74 = new CompiledField.Builder("productsInfo", CompiledGraphQL.a(CompiledGraphQL.b(CheckoutProductInfo.f11231a)));
        builder74.e(listR);
        CompiledField compiledFieldC125 = builder74.c();
        CompiledField.Builder builder75 = new CompiledField.Builder("message", CheckoutSegmentMessage.f11256a);
        builder75.e(listR3);
        CompiledField compiledFieldC126 = builder75.c();
        CompiledField.Builder builder76 = new CompiledField.Builder("legacyErrors", au.com.woolworths.feature.rewards.everydayextras.signup.selections.a.f(LegacyError.f11513a));
        builder76.e(listR4);
        CompiledField compiledFieldC127 = builder76.c();
        CompiledField.Builder builder77 = new CompiledField.Builder("progress", au.com.woolworths.feature.rewards.everydayextras.signup.selections.a.f(CheckoutSegmentProgress.f11257a));
        builder77.e(listR5);
        CompiledField compiledFieldC128 = builder77.c();
        CompiledField.Builder builder78 = new CompiledField.Builder("content", d.j(CheckoutSegmentContent.f11255a));
        builder78.e(listR57);
        CompiledField compiledFieldC129 = builder78.c();
        CompiledField.Builder builder79 = new CompiledField.Builder("orderTotalDetails", CompiledGraphQL.b(CheckoutOrderTotalDetails.f11223a));
        builder79.e(listR64);
        CompiledField compiledFieldC130 = builder79.c();
        CompiledField compiledFieldE2 = a.e("includeIdVerificationBottomSheet", false, new CompiledField.Builder("idVerificationBottomSheet", IdVerificationBottomSheet.f11480a), listR67);
        CompiledField.Builder builder80 = new CompiledField.Builder("restrictionPrompt", RestrictionPrompt.f11881a);
        builder80.e(listR68);
        B0 = CollectionsKt.R(compiledFieldC125, compiledFieldC126, compiledFieldC127, compiledFieldC128, compiledFieldC129, compiledFieldC130, compiledFieldE2, builder80.c());
    }
}
