package com.woolworths.shop.checkout.fragment.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.CheckoutCreditDetail;
import au.com.woolworths.shop.graphql.type.CheckoutCreditItem;
import au.com.woolworths.shop.graphql.type.CheckoutInfoDialog;
import au.com.woolworths.shop.graphql.type.CheckoutOrderAddressSegment;
import au.com.woolworths.shop.graphql.type.CheckoutOrderMarketSellerInfo;
import au.com.woolworths.shop.graphql.type.CheckoutOrderTotalDetails;
import au.com.woolworths.shop.graphql.type.CheckoutOrderTotalDetailsRow;
import au.com.woolworths.shop.graphql.type.CheckoutOrderTotalDetailsRowMessage;
import au.com.woolworths.shop.graphql.type.CheckoutOrderTotalDetailsSummaryRow;
import au.com.woolworths.shop.graphql.type.CheckoutProductInfo;
import au.com.woolworths.shop.graphql.type.CheckoutProgressId;
import au.com.woolworths.shop.graphql.type.CheckoutPromoCodeDetail;
import au.com.woolworths.shop.graphql.type.CheckoutPromotionItem;
import au.com.woolworths.shop.graphql.type.CheckoutRefundInfoBottomSheet;
import au.com.woolworths.shop.graphql.type.CheckoutReviewProductRow;
import au.com.woolworths.shop.graphql.type.CheckoutReviewProductsList;
import au.com.woolworths.shop.graphql.type.CheckoutReviewSupplyLimitGroups;
import au.com.woolworths.shop.graphql.type.CheckoutRewardsAction;
import au.com.woolworths.shop.graphql.type.CheckoutRewardsAndDiscountsTile;
import au.com.woolworths.shop.graphql.type.CheckoutRewardsRedeemInfo;
import au.com.woolworths.shop.graphql.type.CheckoutSegmentContent;
import au.com.woolworths.shop.graphql.type.CheckoutSegmentMessage;
import au.com.woolworths.shop.graphql.type.CheckoutSegmentProgress;
import au.com.woolworths.shop.graphql.type.CheckoutSummaryRewardsSegment;
import au.com.woolworths.shop.graphql.type.CheckoutSummaryValueType;
import au.com.woolworths.shop.graphql.type.ContentCta;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLFloat;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.IdVerificationBottomSheet;
import au.com.woolworths.shop.graphql.type.InlineMessage;
import au.com.woolworths.shop.graphql.type.InsetBanner;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.LegacyError;
import au.com.woolworths.shop.graphql.type.PromoDiscount;
import au.com.woolworths.shop.graphql.type.PromoDiscountItem;
import au.com.woolworths.shop.graphql.type.RestrictionPrompt;
import com.apollographql.apollo.api.CompiledCondition;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.InterfaceType;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.google.android.gms.measurement.api.AppMeasurementSdk;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/checkout/fragment/selections/CheckoutContentSummarySelections;", "", "shop-checkout_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class CheckoutContentSummarySelections {
    public static final List A;
    public static final List B;
    public static final List C;
    public static final List D;
    public static final List E;
    public static final List F;
    public static final List G;
    public static final List H;
    public static final List I;
    public static final List J;
    public static final List K;
    public static final List L;
    public static final List M;
    public static final List N;
    public static final List O;
    public static final List P;
    public static final List Q;
    public static final List R;
    public static final List S;
    public static final List T;
    public static final List U;
    public static final List V;
    public static final List W;
    public static final List X;
    public static final List Y;
    public static final List Z;

    /* renamed from: a, reason: collision with root package name */
    public static final List f22540a;
    public static final List a0;
    public static final List b;
    public static final List b0;
    public static final List c;
    public static final List c0;
    public static final List d;
    public static final List d0;
    public static final List e;
    public static final List e0;
    public static final List f;
    public static final List f0;
    public static final List g;
    public static final List g0;
    public static final List h;
    public static final List h0;
    public static final List i;
    public static final List i0;
    public static final List j;
    public static final List j0;
    public static final List k;
    public static final List k0;
    public static final List l;
    public static final List l0;
    public static final List m;
    public static final List m0;
    public static final List n;
    public static final List n0;
    public static final List o;
    public static final List o0;
    public static final List p;
    public static final List p0;
    public static final List q;
    public static final List q0;
    public static final List r;
    public static final List r0;
    public static final List s;
    public static final List s0;
    public static final List t;
    public static final List t0;
    public static final List u;
    public static final List u0;
    public static final List v;
    public static final List v0;
    public static final List w;
    public static final List w0;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        List listR = CollectionsKt.R(new CompiledField.Builder("productId", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("productName", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("price", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c(), new CompiledField.Builder("quantity", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c(), new CompiledField.Builder("subtotal", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c(), new CompiledField.Builder("isAvailable", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("sellerName", GraphQLString.Companion.a()).c(), new CompiledField.Builder("brandName", GraphQLString.Companion.a()).c(), new CompiledField.Builder("dispatchNote", GraphQLString.Companion.a()).c());
        f22540a = listR;
        List listR2 = CollectionsKt.R(new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("eventSource", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        b = listR2;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("SnackBar", CollectionsKt.Q("SnackBar"));
        builder.b(listR2);
        List listR3 = CollectionsKt.R(compiledFieldC, builder.a());
        c = listR3;
        List listR4 = CollectionsKt.R(new CompiledField.Builder("errorCode", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("key", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        d = listR4;
        CompiledField compiledFieldC2 = new CompiledField.Builder("index", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CheckoutProgressId.e.getClass();
        EnumType enumType = CheckoutProgressId.f;
        List listR5 = CollectionsKt.R(compiledFieldC2, new CompiledField.Builder("id", CompiledGraphQL.b(enumType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        e = listR5;
        InsetBannerDisplayType.e.getClass();
        List listR6 = CollectionsKt.R(new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        f = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("addressText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        g = listR7;
        List listR8 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("displayName", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("buttonText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        h = listR8;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        i = listQ;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        j = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("secondaryButtonTitle", GraphQLString.Companion.a()).c());
        k = listR10;
        CompiledField compiledFieldC3 = new CompiledField.Builder("redeemText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC5 = new CompiledField.Builder("isRedeemed", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        ObjectType objectType = CheckoutInfoDialog.f11213a;
        CompiledField.Builder builder2 = new CompiledField.Builder("redeemInfo", CheckoutInfoDialog.Companion.a());
        builder2.e(listR10);
        List listR11 = CollectionsKt.R(compiledFieldC3, compiledFieldC4, compiledFieldC5, builder2.c());
        l = listR11;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("CheckoutSummaryRewardsRegistered", CollectionsKt.Q("CheckoutSummaryRewardsRegistered"));
        builder3.b(listR9);
        CompiledFragment compiledFragmentA = builder3.a();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("CheckoutSummaryRewardsRegisteredRedeemable", CollectionsKt.Q("CheckoutSummaryRewardsRegisteredRedeemable"));
        builder4.b(listR11);
        List listR12 = CollectionsKt.R(compiledFieldC6, compiledFragmentA, builder4.a());
        m = listR12;
        UnionType unionType = CheckoutSummaryRewardsSegment.f11267a;
        CompiledField.Builder builder5 = new CompiledField.Builder("rewardsSections", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutSummaryRewardsSegment.Companion.a()))));
        builder5.e(listR12);
        List listQ2 = CollectionsKt.Q(builder5.c());
        n = listQ2;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("addressText", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("fulfilmentWindow", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        o = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder("sellerName", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("dispatchNote", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        p = listR14;
        CompiledField compiledFieldC7 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC8 = new CompiledField.Builder("addressText", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC9 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder6 = new CompiledField.Builder("sellerInfo", a.f(CheckoutOrderMarketSellerInfo.f11221a));
        builder6.e(listR14);
        List listR15 = CollectionsKt.R(compiledFieldC7, compiledFieldC8, compiledFieldC9, builder6.c());
        q = listR15;
        CompiledField compiledFieldC10 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("CheckoutOrderGroceryAddress", CollectionsKt.Q("CheckoutOrderGroceryAddress"));
        builder7.b(listR13);
        CompiledFragment compiledFragmentA2 = builder7.a();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("CheckoutOrderMarketAddress", CollectionsKt.Q("CheckoutOrderMarketAddress"));
        builder8.b(listR15);
        List listR16 = CollectionsKt.R(compiledFieldC10, compiledFragmentA2, builder8.a());
        r = listR16;
        List listR17 = CollectionsKt.R(new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        s = listR17;
        CompiledField compiledFieldC11 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder9 = new CompiledField.Builder("addressSections", d.j(CheckoutOrderAddressSegment.f11217a));
        builder9.e(listR16);
        CompiledField compiledFieldC12 = builder9.c();
        ObjectType objectType2 = InsetBanner.f11509a;
        CompiledField.Builder builder10 = new CompiledField.Builder("insetBanner", InsetBanner.Companion.a());
        builder10.e(listR17);
        List listR18 = CollectionsKt.R(compiledFieldC11, compiledFieldC12, builder10.c());
        t = listR18;
        CompiledField compiledFieldC13 = new CompiledField.Builder("title", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC14 = new CompiledField.Builder("body", GraphQLString.Companion.a()).c();
        CompiledField.Builder builder11 = new CompiledField.Builder("type", GraphQLString.Companion.a());
        builder11.d(CollectionsKt.Q(new CompiledCondition("includeServiceFees", false)));
        List listR19 = CollectionsKt.R(compiledFieldC13, compiledFieldC14, builder11.c());
        u = listR19;
        CompiledField compiledFieldC15 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CheckoutSummaryValueType.e.getClass();
        CompiledField compiledFieldC16 = new CompiledField.Builder("titleType", CompiledGraphQL.b(CheckoutSummaryValueType.Companion.a())).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("value", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC18 = new CompiledField.Builder("valueType", CompiledGraphQL.b(CheckoutSummaryValueType.Companion.a())).c();
        CompiledField compiledFieldC19 = new CompiledField.Builder("imageUrl", GraphQLString.Companion.a()).c();
        ObjectType objectType3 = CheckoutOrderTotalDetailsRowMessage.f11225a;
        CompiledField.Builder builder12 = new CompiledField.Builder("message", objectType3);
        builder12.e(listR19);
        List listR20 = CollectionsKt.R(compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, compiledFieldC19, builder12.c());
        v = listR20;
        CompiledField compiledFieldC20 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType4 = CheckoutOrderTotalDetailsRow.f11224a;
        CompiledField.Builder builder13 = new CompiledField.Builder("sections", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(objectType4))))));
        builder13.e(listR20);
        List listR21 = CollectionsKt.R(compiledFieldC20, builder13.c());
        w = listR21;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder("markdownText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        x = listQ3;
        List listR22 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("price", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        y = listR22;
        ObjectType objectType5 = PromoDiscountItem.f11797a;
        CompiledField.Builder builder14 = new CompiledField.Builder("discountItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(PromoDiscountItem.Companion.a()))));
        builder14.e(listR22);
        List listR23 = CollectionsKt.R(builder14.c(), new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        z = listR23;
        CompiledField compiledFieldC21 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC22 = new CompiledField.Builder("placeholderText", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC23 = new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType6 = PromoDiscount.f11796a;
        CompiledField.Builder builder15 = new CompiledField.Builder("discounts", PromoDiscount.Companion.a());
        builder15.e(listR23);
        List listR24 = CollectionsKt.R(compiledFieldC21, compiledFieldC22, compiledFieldC23, builder15.c());
        A = listR24;
        List listR25 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        B = listR25;
        List listR26 = CollectionsKt.R(new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        C = listR26;
        CompiledField compiledFieldC24 = new CompiledField.Builder("minimum", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC25 = new CompiledField.Builder("maximum", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC26 = new CompiledField.Builder("maximumRedeemable", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC27 = new CompiledField.Builder("increment", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC28 = new CompiledField.Builder("current", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField.Builder builder16 = new CompiledField.Builder("unRedeemableBanner", InsetBanner.Companion.a());
        builder16.e(listR26);
        List listR27 = CollectionsKt.R(compiledFieldC24, compiledFieldC25, compiledFieldC26, compiledFieldC27, compiledFieldC28, builder16.c());
        D = listR27;
        List listR28 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        E = listR28;
        ObjectType objectType7 = CheckoutRewardsRedeemInfo.f11253a;
        CompiledField.Builder builder17 = new CompiledField.Builder("rewardsRedeemInfo", CompiledGraphQL.b(CheckoutRewardsRedeemInfo.Companion.a()));
        builder17.e(listR27);
        CompiledField compiledFieldC29 = builder17.c();
        CompiledField compiledFieldC30 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC31 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType8 = Analytics.f11028a;
        CompiledField.Builder builder18 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder18.e(listR28);
        List listR29 = CollectionsKt.R(compiledFieldC29, compiledFieldC30, compiledFieldC31, builder18.c());
        F = listR29;
        List listR30 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        G = listR30;
        List listR31 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        H = listR31;
        CompiledField compiledFieldC32 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC33 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC34 = new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder19 = new CompiledField.Builder("impressionAnalytics", Analytics.Companion.a());
        builder19.e(listR30);
        CompiledField compiledFieldC35 = builder19.c();
        CompiledField.Builder builder20 = new CompiledField.Builder("buttonClickAnalytics", Analytics.Companion.a());
        builder20.e(listR31);
        List listR32 = CollectionsKt.R(compiledFieldC32, compiledFieldC33, compiledFieldC34, compiledFieldC35, builder20.c());
        I = listR32;
        List listQ4 = CollectionsKt.Q(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        J = listQ4;
        CompiledField compiledFieldC36 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("CheckoutRewardsRedeem", CollectionsKt.Q("CheckoutRewardsRedeem"));
        builder21.b(listR29);
        CompiledFragment compiledFragmentA3 = builder21.a();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("CheckoutRewardsInfo", CollectionsKt.Q("CheckoutRewardsInfo"));
        builder22.b(listR32);
        CompiledFragment compiledFragmentA4 = builder22.a();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("CheckoutRewardsLink", CollectionsKt.Q("CheckoutRewardsLink"));
        builder23.b(listQ4);
        List listR33 = CollectionsKt.R(compiledFieldC36, compiledFragmentA3, compiledFragmentA4, builder23.a());
        K = listR33;
        CompiledField compiledFieldC37 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC38 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC39 = new CompiledField.Builder("redeemedIcon", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField.Builder builder24 = new CompiledField.Builder("actionClickAnalytics", Analytics.Companion.a());
        builder24.e(listR25);
        CompiledField compiledFieldC40 = builder24.c();
        UnionType unionType2 = CheckoutRewardsAction.f11247a;
        CompiledField.Builder builder25 = new CompiledField.Builder("rewardsAction", CheckoutRewardsAction.Companion.a());
        builder25.e(listR33);
        List listR34 = CollectionsKt.R(compiledFieldC37, compiledFieldC38, compiledFieldC39, compiledFieldC40, builder25.c());
        L = listR34;
        List listR35 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        M = listR35;
        List listR36 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("primaryLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("secondaryLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("isApplied", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("code", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        N = listR36;
        CompiledField compiledFieldC41 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder26 = new CompiledFragment.Builder("CheckoutPromoCodeItem", CollectionsKt.Q("CheckoutPromoCodeItem"));
        builder26.b(listR36);
        List listR37 = CollectionsKt.R(compiledFieldC41, builder26.a());
        O = listR37;
        CompiledField compiledFieldC42 = new CompiledField.Builder("placeholderText", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC43 = new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        UnionType unionType3 = CheckoutPromotionItem.f11241a;
        CompiledField.Builder builder27 = new CompiledField.Builder("promoCodes", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutPromotionItem.Companion.a()))));
        builder27.e(listR37);
        List listR38 = CollectionsKt.R(compiledFieldC42, compiledFieldC43, builder27.c());
        P = listR38;
        CompiledField compiledFieldC44 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC45 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC46 = new CompiledField.Builder("appliedIcon", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField.Builder builder28 = new CompiledField.Builder("actionClickAnalytics", Analytics.Companion.a());
        builder28.e(listR35);
        CompiledField compiledFieldC47 = builder28.c();
        ObjectType objectType9 = CheckoutPromoCodeDetail.f11238a;
        CompiledField.Builder builder29 = new CompiledField.Builder("detail", CompiledGraphQL.b(CheckoutPromoCodeDetail.Companion.a()));
        builder29.e(listR38);
        List listR39 = CollectionsKt.R(compiledFieldC44, compiledFieldC45, compiledFieldC46, compiledFieldC47, builder29.c());
        Q = listR39;
        List listR40 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        R = listR40;
        List listR41 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        S = listR41;
        List listR42 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("primaryLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("secondaryLabel", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("isApplied", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c(), new CompiledField.Builder("code", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("amount", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        T = listR42;
        CompiledField compiledFieldC48 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC49 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType10 = CheckoutCreditItem.f11196a;
        CompiledField.Builder builder30 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutCreditItem.Companion.a()))));
        builder30.e(listR42);
        List listR43 = CollectionsKt.R(compiledFieldC48, compiledFieldC49, builder30.c());
        U = listR43;
        List listR44 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("retryButtonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        V = listR44;
        CompiledField compiledFieldC50 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder31 = new CompiledFragment.Builder("CheckoutCreditEmpty", CollectionsKt.Q("CheckoutCreditEmpty"));
        builder31.b(listR41);
        CompiledFragment compiledFragmentA5 = builder31.a();
        CompiledFragment.Builder builder32 = new CompiledFragment.Builder("CheckoutCreditItems", CollectionsKt.Q("CheckoutCreditItems"));
        builder32.b(listR43);
        CompiledFragment compiledFragmentA6 = builder32.a();
        CompiledFragment.Builder builder33 = new CompiledFragment.Builder("CheckoutCreditUnavailable", CollectionsKt.Q("CheckoutCreditUnavailable"));
        builder33.b(listR44);
        List listR45 = CollectionsKt.R(compiledFieldC50, compiledFragmentA5, compiledFragmentA6, builder33.a());
        W = listR45;
        CompiledField compiledFieldC51 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC52 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC53 = new CompiledField.Builder("appliedIcon", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField.Builder builder34 = new CompiledField.Builder("actionClickAnalytics", Analytics.Companion.a());
        builder34.e(listR40);
        CompiledField compiledFieldC54 = builder34.c();
        UnionType unionType4 = CheckoutCreditDetail.f11194a;
        CompiledField.Builder builder35 = new CompiledField.Builder("detail", CompiledGraphQL.b(CheckoutCreditDetail.Companion.a()));
        builder35.e(listR45);
        List listR46 = CollectionsKt.R(compiledFieldC51, compiledFieldC52, compiledFieldC53, compiledFieldC54, builder35.c());
        X = listR46;
        List listR47 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.i("isRewardsUplift", false, new CompiledFragment.Builder("CheckoutRewards", CollectionsKt.Q("CheckoutRewards")), listR34), d.i("isPromoCodeUplift", false, new CompiledFragment.Builder("CheckoutPromoCode", CollectionsKt.Q("CheckoutPromoCode")), listR39), d.i("includeCredit", false, new CompiledFragment.Builder("CheckoutCredit", CollectionsKt.Q("CheckoutCredit")), listR46));
        Y = listR47;
        List listR48 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        Z = listR48;
        CompiledField compiledFieldC55 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        UnionType unionType5 = CheckoutRewardsAndDiscountsTile.f11249a;
        CompiledField.Builder builder36 = new CompiledField.Builder("rewardsAndDiscounts", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutRewardsAndDiscountsTile.Companion.a()))));
        builder36.e(listR47);
        List listR49 = CollectionsKt.R(compiledFieldC55, builder36.c(), com.google.android.gms.common.api.internal.a.e("rewardsAndDiscountsImpressionUplift", true, new CompiledField.Builder("impressionAnalytics", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(Analytics.Companion.a())))), listR48));
        a0 = listR49;
        CompiledField compiledFieldC56 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder37 = new CompiledFragment.Builder("InsetBanner", CollectionsKt.Q("InsetBanner"));
        builder37.b(listR6);
        CompiledFragment compiledFragmentA7 = builder37.a();
        CompiledFragment.Builder builder38 = new CompiledFragment.Builder("CheckoutSummaryBillingAddress", CollectionsKt.Q("CheckoutSummaryBillingAddress"));
        builder38.b(listR7);
        CompiledFragment compiledFragmentA8 = builder38.a();
        CompiledFragment.Builder builder39 = new CompiledFragment.Builder("CheckoutSummaryBillingAddressEmpty", CollectionsKt.Q("CheckoutSummaryBillingAddressEmpty"));
        builder39.b(listR8);
        CompiledFragment compiledFragmentA9 = builder39.a();
        CompiledFragment compiledFragmentI = d.i("isRewardsUplift", true, new CompiledFragment.Builder("CheckoutSummaryRewardsUnregistered", CollectionsKt.Q("CheckoutSummaryRewardsUnregistered")), listQ);
        CompiledFragment compiledFragmentI2 = d.i("isRewardsUplift", true, new CompiledFragment.Builder("CheckoutSummaryRewards", CollectionsKt.Q("CheckoutSummaryRewards")), listQ2);
        CompiledFragment.Builder builder40 = new CompiledFragment.Builder("CheckoutOrderAddresses", CollectionsKt.Q("CheckoutOrderAddresses"));
        builder40.b(listR18);
        CompiledFragment compiledFragmentA10 = builder40.a();
        CompiledFragment.Builder builder41 = new CompiledFragment.Builder("CheckoutOrderSummary", CollectionsKt.Q("CheckoutOrderSummary"));
        builder41.b(listR21);
        CompiledFragment compiledFragmentA11 = builder41.a();
        CompiledFragment.Builder builder42 = new CompiledFragment.Builder("CheckoutTermsConditions", CollectionsKt.Q("CheckoutTermsConditions"));
        builder42.b(listQ3);
        List listR50 = CollectionsKt.R(compiledFieldC56, compiledFragmentA7, compiledFragmentA8, compiledFragmentA9, compiledFragmentI, compiledFragmentI2, compiledFragmentA10, compiledFragmentA11, builder42.a(), d.i("isPromoCodeUplift", true, new CompiledFragment.Builder("CheckoutPromotionCode", CollectionsKt.Q("CheckoutPromotionCode")), listR24), d.i("includeRewardsAndDiscounts", false, new CompiledFragment.Builder("CheckoutRewardsAndDiscounts", CollectionsKt.Q("CheckoutRewardsAndDiscounts")), listR49));
        b0 = listR50;
        List listR51 = CollectionsKt.R(new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        c0 = listR51;
        List listR52 = CollectionsKt.R(new CompiledField.Builder("title", GraphQLString.Companion.a()).c(), new CompiledField.Builder("body", GraphQLString.Companion.a()).c(), new CompiledField.Builder("type", GraphQLString.Companion.a()).c());
        d0 = listR52;
        List listR53 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("titleType", CompiledGraphQL.b(CheckoutSummaryValueType.Companion.a())).c(), new CompiledField.Builder("value", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("valueType", CompiledGraphQL.b(CheckoutSummaryValueType.Companion.a())).c(), new CompiledField.Builder("imageUrl", GraphQLString.Companion.a()).c(), com.google.android.gms.common.api.internal.a.e("includeServiceFees", false, new CompiledField.Builder("message", objectType3), listR52));
        e0 = listR53;
        List listR54 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("value", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("balanceToPay", CompiledGraphQL.b(GraphQLFloat.Companion.a())).c(), new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), a.d("progressId", enumType), new CompiledField.Builder("isEnabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        f0 = listR54;
        List listQ5 = CollectionsKt.Q(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        g0 = listQ5;
        CompiledField compiledFieldC57 = new CompiledField.Builder("bottomSheetTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC58 = new CompiledField.Builder("bottomSheetBody", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType11 = ContentCta.f11282a;
        CompiledField.Builder builder43 = new CompiledField.Builder("primaryCta", ContentCta.Companion.a());
        builder43.e(listQ5);
        List listR55 = CollectionsKt.R(compiledFieldC57, compiledFieldC58, builder43.c());
        h0 = listR55;
        List listQ6 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        i0 = listQ6;
        List listQ7 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        j0 = listQ7;
        List listQ8 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        k0 = listQ8;
        InterfaceType interfaceType = CheckoutReviewProductRow.f11243a;
        CompiledField.Builder builder44 = new CompiledField.Builder("products", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder44.e(listQ8);
        List listQ9 = CollectionsKt.Q(builder44.c());
        l0 = listQ9;
        List listQ10 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        m0 = listQ10;
        List listQ11 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        n0 = listQ11;
        List listQ12 = CollectionsKt.Q(new CompiledField.Builder(AppMeasurementSdk.ConditionalUserProperty.NAME, GraphQLString.Companion.a()).c());
        o0 = listQ12;
        CompiledField.Builder builder45 = new CompiledField.Builder("unavailableOrderItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder45.e(listQ6);
        CompiledField compiledFieldC59 = builder45.c();
        CompiledField.Builder builder46 = new CompiledField.Builder("restrictedOrderItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder46.e(listQ7);
        CompiledField compiledFieldC60 = builder46.c();
        CompiledField.Builder builder47 = new CompiledField.Builder("exceededSupplyLimitProductGroups", a.f(CheckoutReviewSupplyLimitGroups.f11245a));
        builder47.e(listQ9);
        CompiledField compiledFieldC61 = builder47.c();
        CompiledField.Builder builder48 = new CompiledField.Builder("restrictedProductsByDeliveryMethod", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder48.e(listQ10);
        CompiledField compiledFieldC62 = builder48.c();
        CompiledField.Builder builder49 = new CompiledField.Builder("restrictedProductsByDeliPlatter", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder49.e(listQ11);
        CompiledField compiledFieldC63 = builder49.c();
        CompiledField.Builder builder50 = new CompiledField.Builder("availableOrderItems", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutReviewProductRow.Companion.a()))));
        builder50.e(listQ12);
        List listR56 = CollectionsKt.R(compiledFieldC59, compiledFieldC60, compiledFieldC61, compiledFieldC62, compiledFieldC63, builder50.c());
        p0 = listR56;
        ObjectType objectType12 = InlineMessage.f11507a;
        CompiledField.Builder builder51 = new CompiledField.Builder("inlineMessage", InlineMessage.Companion.a());
        builder51.e(listR51);
        CompiledField compiledFieldC64 = builder51.c();
        CompiledField.Builder builder52 = new CompiledField.Builder("sections", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(objectType4))))));
        builder52.e(listR53);
        CompiledField compiledFieldC65 = builder52.c();
        CompiledField.Builder builder53 = new CompiledField.Builder("total", CompiledGraphQL.b(CheckoutOrderTotalDetailsSummaryRow.f11226a));
        builder53.e(listR54);
        CompiledField compiledFieldC66 = builder53.c();
        ObjectType objectType13 = CheckoutRefundInfoBottomSheet.f11242a;
        CompiledField.Builder builder54 = new CompiledField.Builder("refundInfo", CheckoutRefundInfoBottomSheet.Companion.a());
        builder54.e(listR55);
        CompiledField compiledFieldC67 = builder54.c();
        CompiledField.Builder builder55 = new CompiledField.Builder("reviewProducts", CheckoutReviewProductsList.f11244a);
        builder55.e(listR56);
        CompiledField compiledFieldC68 = builder55.c();
        CompiledField.Builder builder56 = new CompiledField.Builder("panelMarkdown", GraphQLString.Companion.a());
        builder56.d(CollectionsKt.Q(new CompiledCondition("includePanelMarkdown", false)));
        List listR57 = CollectionsKt.R(compiledFieldC64, compiledFieldC65, compiledFieldC66, compiledFieldC67, compiledFieldC68, builder56.c());
        q0 = listR57;
        CompiledField compiledFieldC69 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ButtonStyle.e.getClass();
        List listR58 = CollectionsKt.R(compiledFieldC69, new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        r0 = listR58;
        List listR59 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("style", ButtonStyle.Companion.a()).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        s0 = listR59;
        CompiledField compiledFieldC70 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC71 = new CompiledField.Builder("body", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC72 = new CompiledField.Builder("imageUrls", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(GraphQLString.Companion.a())))).c();
        ObjectType objectType14 = Button.f11080a;
        CompiledField.Builder builder57 = new CompiledField.Builder("primaryButton", Button.Companion.a());
        builder57.e(listR58);
        CompiledField compiledFieldC73 = builder57.c();
        CompiledField.Builder builder58 = new CompiledField.Builder("secondaryButton", Button.Companion.a());
        builder58.e(listR59);
        List listR60 = CollectionsKt.R(compiledFieldC70, compiledFieldC71, compiledFieldC72, compiledFieldC73, builder58.c());
        t0 = listR60;
        List listR61 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), d.D(new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"))));
        u0 = listR61;
        List listR62 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        v0 = listR62;
        CompiledField.Builder builder59 = new CompiledField.Builder("productsInfo", CompiledGraphQL.a(CompiledGraphQL.b(CheckoutProductInfo.f11231a)));
        builder59.e(listR);
        CompiledField compiledFieldC74 = builder59.c();
        CompiledField.Builder builder60 = new CompiledField.Builder("message", CheckoutSegmentMessage.f11256a);
        builder60.e(listR3);
        CompiledField compiledFieldC75 = builder60.c();
        CompiledField.Builder builder61 = new CompiledField.Builder("legacyErrors", a.f(LegacyError.f11513a));
        builder61.e(listR4);
        CompiledField compiledFieldC76 = builder61.c();
        CompiledField.Builder builder62 = new CompiledField.Builder("progress", a.f(CheckoutSegmentProgress.f11257a));
        builder62.e(listR5);
        CompiledField compiledFieldC77 = builder62.c();
        CompiledField.Builder builder63 = new CompiledField.Builder("content", d.j(CheckoutSegmentContent.f11255a));
        builder63.e(listR50);
        CompiledField compiledFieldC78 = builder63.c();
        CompiledField.Builder builder64 = new CompiledField.Builder("orderTotalDetails", CompiledGraphQL.b(CheckoutOrderTotalDetails.f11223a));
        builder64.e(listR57);
        CompiledField compiledFieldC79 = builder64.c();
        CompiledField compiledFieldE = com.google.android.gms.common.api.internal.a.e("includeIdVerificationBottomSheet", false, new CompiledField.Builder("idVerificationBottomSheet", IdVerificationBottomSheet.f11480a), listR60);
        CompiledField compiledFieldE2 = com.google.android.gms.common.api.internal.a.e("rewardsAndDiscountsImpressionUplift", false, new CompiledField.Builder("impressionAnalytics", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(Analytics.Companion.a())))), listR61);
        CompiledField.Builder builder65 = new CompiledField.Builder("isUserWPayMigrated", CompiledGraphQL.b(GraphQLBoolean.Companion.a()));
        builder65.d(CollectionsKt.Q(new CompiledCondition("isWPayEnabled", false)));
        CompiledField compiledFieldC80 = builder65.c();
        CompiledField.Builder builder66 = new CompiledField.Builder("restrictionPrompt", RestrictionPrompt.f11881a);
        builder66.e(listR62);
        w0 = CollectionsKt.R(compiledFieldC74, compiledFieldC75, compiledFieldC76, compiledFieldC77, compiledFieldC78, compiledFieldC79, compiledFieldE, compiledFieldE2, compiledFieldC80, builder66.c());
    }
}
