package com.woolworths.shop.checkout.fragment.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.sdui.shop.fragment.selections.CoreTagUISelections;
import au.com.woolworths.shop.graphql.type.Badge;
import au.com.woolworths.shop.graphql.type.BadgeType;
import au.com.woolworths.shop.graphql.type.CheckoutBadgeStyle;
import au.com.woolworths.shop.graphql.type.CheckoutDeliveryNowWindow;
import au.com.woolworths.shop.graphql.type.CheckoutDirectToBootNowWindow;
import au.com.woolworths.shop.graphql.type.CheckoutFulfilmentBottomSheet;
import au.com.woolworths.shop.graphql.type.CheckoutFulfilmentSuggestedGroup;
import au.com.woolworths.shop.graphql.type.CheckoutFulfilmentWindow;
import au.com.woolworths.shop.graphql.type.CheckoutFulfilmentWindowGroup;
import au.com.woolworths.shop.graphql.type.CheckoutFulfilmentWindowGroupMessage;
import au.com.woolworths.shop.graphql.type.CheckoutFulfilmentWindowSlot;
import au.com.woolworths.shop.graphql.type.CheckoutFulfilmentWindowSlotBadge;
import au.com.woolworths.shop.graphql.type.CoreIcon;
import au.com.woolworths.shop.graphql.type.CoreTagUI;
import au.com.woolworths.shop.graphql.type.DeliveryNowStatus;
import au.com.woolworths.shop.graphql.type.DirectToBootNowStatus;
import au.com.woolworths.shop.graphql.type.ExtraInfoButton;
import au.com.woolworths.shop.graphql.type.FulfilmentExtraInfo;
import au.com.woolworths.shop.graphql.type.FulfilmentWindowFooterV2;
import au.com.woolworths.shop.graphql.type.FulfilmentWindowSelectionOptionsInfo;
import au.com.woolworths.shop.graphql.type.FulfilmentWindowSlotSelectionInfo;
import au.com.woolworths.shop.graphql.type.FulfilmentWindowSlotSelectionOption;
import au.com.woolworths.shop.graphql.type.FulfilmentWindowSlotSelectionOptionId;
import au.com.woolworths.shop.graphql.type.FulfilmentWindowSlotSelectionOptionsState;
import au.com.woolworths.shop.graphql.type.FulfilmentWindowsFooter;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.InfoSection;
import au.com.woolworths.shop.graphql.type.InfoSectionItem;
import au.com.woolworths.shop.graphql.type.InsetBanner;
import au.com.woolworths.shop.graphql.type.InsetBannerAction;
import au.com.woolworths.shop.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.shop.graphql.type.InsetBannerActionType;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.TextWithAlt;
import com.apollographql.apollo.api.CompiledCondition;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.salesforce.marketingcloud.storage.db.k;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/checkout/fragment/selections/CheckoutFulfilmentWindowsSelections;", "", "shop-checkout_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class CheckoutFulfilmentWindowsSelections {
    public static final List A;
    public static final List B;
    public static final List C;
    public static final List D;
    public static final List E;
    public static final List F;
    public static final List G;
    public static final List H;
    public static final List I;
    public static final List J;
    public static final List K;
    public static final List L;
    public static final List M;
    public static final List N;
    public static final List O;
    public static final List P;
    public static final List Q;
    public static final List R;
    public static final List S;
    public static final List T;
    public static final List U;
    public static final List V;
    public static final List W;
    public static final List X;
    public static final List Y;
    public static final List Z;

    /* renamed from: a, reason: collision with root package name */
    public static final List f22541a;
    public static final List a0;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        InsetBannerActionPlacement.e.getClass();
        CompiledField compiledFieldC = new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.Companion.a())).c();
        InsetBannerActionType.e.getClass();
        List listR = CollectionsKt.R(compiledFieldC, new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.Companion.a())).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("url", GraphQLString.Companion.a()).c());
        f22541a = listR;
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC2 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.Companion.a())).c();
        CompiledField compiledFieldC3 = new CompiledField.Builder("message", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder = new CompiledField.Builder("title", GraphQLString.Companion.a());
        builder.a("bannerTitle");
        CompiledField compiledFieldC4 = builder.c();
        CompiledField compiledFieldC5 = new CompiledField.Builder("iconUrl", GraphQLString.Companion.a()).c();
        ObjectType objectType = InsetBannerAction.f11510a;
        CompiledField.Builder builder2 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.Companion.a());
        builder2.e(listR);
        List listR2 = CollectionsKt.R(compiledFieldC2, compiledFieldC3, compiledFieldC4, compiledFieldC5, builder2.c());
        b = listR2;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        c = listQ;
        CompiledField compiledFieldC6 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CheckoutBadgeStyle.e.getClass();
        EnumType enumType = CheckoutBadgeStyle.f;
        List listR3 = CollectionsKt.R(compiledFieldC6, new CompiledField.Builder("style", CompiledGraphQL.b(enumType)).c());
        d = listR3;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder3 = new CompiledFragment.Builder("FulfilmentWindowSlotSelectionInfo", CollectionsKt.Q("FulfilmentWindowSlotSelectionInfo"));
        List list = SelectionInfoSelections.f22543a;
        builder3.b(list);
        List listR4 = CollectionsKt.R(compiledFieldC7, builder3.a());
        e = listR4;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("CoreTagUI", CollectionsKt.Q("CoreTagUI"));
        builder4.b(CoreTagUISelections.a());
        List listR5 = CollectionsKt.R(compiledFieldC8, builder4.a());
        f = listR5;
        CompiledField compiledFieldC9 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("CoreTagUI", CollectionsKt.Q("CoreTagUI"));
        builder5.b(CoreTagUISelections.a());
        List listR6 = CollectionsKt.R(compiledFieldC9, builder5.a());
        g = listR6;
        CompiledField compiledFieldC10 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC11 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC12 = new CompiledField.Builder("startTime", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC13 = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC14 = new CompiledField.Builder("isAvailable", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC15 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("isPartnerDriver", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("sectionTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType2 = CheckoutFulfilmentWindowSlotBadge.f11209a;
        CompiledField.Builder builder6 = new CompiledField.Builder("badges", a.f(objectType2));
        builder6.e(listR3);
        CompiledField compiledFieldC18 = builder6.c();
        ObjectType objectType3 = FulfilmentWindowSlotSelectionInfo.f11416a;
        CompiledField.Builder builder7 = new CompiledField.Builder("selectionInfo", objectType3);
        builder7.e(listR4);
        CompiledField compiledFieldC19 = builder7.c();
        ObjectType objectType4 = CoreTagUI.f11294a;
        CompiledField.Builder builder8 = new CompiledField.Builder(k.a.g, CompiledGraphQL.a(CompiledGraphQL.b(CoreTagUI.Companion.a())));
        builder8.e(listR5);
        CompiledField compiledFieldC20 = builder8.c();
        CompiledField.Builder builder9 = new CompiledField.Builder("statuses", CompiledGraphQL.a(CompiledGraphQL.b(CoreTagUI.Companion.a())));
        builder9.e(listR6);
        List listR7 = CollectionsKt.R(compiledFieldC10, compiledFieldC11, compiledFieldC12, compiledFieldC13, compiledFieldC14, compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, compiledFieldC19, compiledFieldC20, builder9.c());
        h = listR7;
        List listR8 = CollectionsKt.R(new CompiledField.Builder("bottomSheetTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("bottomSheetBody", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        i = listR8;
        CompiledField compiledFieldC21 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType5 = CheckoutFulfilmentWindowSlot.f11208a;
        CompiledField.Builder builder10 = new CompiledField.Builder("slots", a.f(objectType5));
        builder10.e(listR7);
        CompiledField compiledFieldC22 = builder10.c();
        ObjectType objectType6 = CheckoutFulfilmentBottomSheet.f11203a;
        CompiledField.Builder builder11 = new CompiledField.Builder("bottomSheet", CompiledGraphQL.b(CheckoutFulfilmentBottomSheet.f11203a));
        builder11.e(listR8);
        List listR9 = CollectionsKt.R(compiledFieldC21, compiledFieldC22, builder11.c());
        j = listR9;
        List listR10 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("isSpecial", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        k = listR10;
        List listR11 = CollectionsKt.R(new CompiledField.Builder("messageTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        l = listR11;
        CompiledField compiledFieldC23 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("FulfilmentExtraInfo", CollectionsKt.Q("FulfilmentExtraInfo"));
        List list2 = FulfilmentExtraInfoSelections.C;
        builder12.b(list2);
        List listR12 = CollectionsKt.R(compiledFieldC23, builder12.a());
        m = listR12;
        CompiledField compiledFieldC24 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("CoreTagUI", CollectionsKt.Q("CoreTagUI"));
        builder13.b(CoreTagUISelections.a());
        List listR13 = CollectionsKt.R(compiledFieldC24, builder13.a());
        n = listR13;
        CompiledField compiledFieldC25 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("CoreTagUI", CollectionsKt.Q("CoreTagUI"));
        builder14.b(CoreTagUISelections.a());
        List listR14 = CollectionsKt.R(compiledFieldC25, builder14.a());
        o = listR14;
        List listR15 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        p = listR15;
        CompiledField compiledFieldC26 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType7 = InfoSectionItem.f11497a;
        CompiledField.Builder builder15 = new CompiledField.Builder("items", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(InfoSectionItem.Companion.a()))));
        builder15.e(listR15);
        List listR16 = CollectionsKt.R(compiledFieldC26, builder15.c());
        q = listR16;
        List listR17 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        r = listR17;
        CompiledField compiledFieldC27 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType8 = TextWithAlt.f11967a;
        CompiledField.Builder builder16 = new CompiledField.Builder("altLabel", TextWithAlt.Companion.a());
        builder16.e(listR17);
        CompiledField compiledFieldC28 = builder16.c();
        BadgeType.e.getClass();
        EnumType enumType2 = BadgeType.f;
        List listR18 = CollectionsKt.R(compiledFieldC27, compiledFieldC28, new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c());
        s = listR18;
        CompiledField compiledFieldC29 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("FulfilmentWindowSlotSelectionInfo", CollectionsKt.Q("FulfilmentWindowSlotSelectionInfo"));
        builder17.b(list);
        List listR19 = CollectionsKt.R(compiledFieldC29, builder17.a());
        t = listR19;
        CompiledField compiledFieldC30 = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC31 = new CompiledField.Builder("startTime", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldE = com.google.android.gms.common.api.internal.a.e("includeTimeSelectionContent", false, new CompiledField.Builder(k.a.g, CompiledGraphQL.a(CompiledGraphQL.b(CoreTagUI.Companion.a()))), listR13);
        CompiledField compiledFieldE2 = com.google.android.gms.common.api.internal.a.e("includeTimeSelectionContent", false, new CompiledField.Builder("statuses", CompiledGraphQL.a(CompiledGraphQL.b(CoreTagUI.Companion.a()))), listR14);
        CompiledField compiledFieldC32 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC33 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC34 = new CompiledField.Builder("secondarySubtitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC35 = new CompiledField.Builder("sectionTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC36 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC37 = new CompiledField.Builder("messageTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC38 = new CompiledField.Builder("buttonTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType9 = InfoSection.f11495a;
        CompiledField.Builder builder18 = new CompiledField.Builder("info", CompiledGraphQL.b(InfoSection.Companion.a()));
        builder18.e(listR16);
        CompiledField compiledFieldC39 = builder18.c();
        CompiledField compiledFieldC40 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC41 = new CompiledField.Builder("isEnabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        ObjectType objectType10 = Badge.f11042a;
        CompiledField.Builder builder19 = new CompiledField.Builder("badge", objectType10);
        builder19.a("deliveryNowV2Badge");
        builder19.e(listR18);
        CompiledField compiledFieldC42 = builder19.c();
        CompiledField.Builder builder20 = new CompiledField.Builder("selectionInfo", objectType3);
        builder20.e(listR19);
        List listR20 = CollectionsKt.R(compiledFieldC30, compiledFieldC31, compiledFieldE, compiledFieldE2, compiledFieldC32, compiledFieldC33, compiledFieldC34, compiledFieldC35, compiledFieldC36, compiledFieldC37, compiledFieldC38, compiledFieldC39, compiledFieldC40, compiledFieldC41, compiledFieldC42, builder20.c());
        u = listR20;
        List listR21 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLInt.Companion.a())).c(), new CompiledField.Builder("startTime", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("secondarySubtitle", GraphQLString.Companion.a()).c(), new CompiledField.Builder("sectionTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        v = listR21;
        CompiledField compiledFieldC43 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("CoreTagUI", CollectionsKt.Q("CoreTagUI"));
        builder21.b(CoreTagUISelections.a());
        List listR22 = CollectionsKt.R(compiledFieldC43, builder21.a());
        w = listR22;
        CompiledField compiledFieldC44 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("CoreTagUI", CollectionsKt.Q("CoreTagUI"));
        builder22.b(CoreTagUISelections.a());
        List listR23 = CollectionsKt.R(compiledFieldC44, builder22.a());
        x = listR23;
        List listR24 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        y = listR24;
        CompiledField compiledFieldC45 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder23 = new CompiledField.Builder("altLabel", TextWithAlt.Companion.a());
        builder23.e(listR24);
        List listR25 = CollectionsKt.R(compiledFieldC45, builder23.c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c());
        z = listR25;
        List listR26 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c());
        A = listR26;
        CompiledField compiledFieldC46 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder24 = new CompiledFragment.Builder("FulfilmentWindowSlotSelectionInfo", CollectionsKt.Q("FulfilmentWindowSlotSelectionInfo"));
        builder24.b(list);
        List listR27 = CollectionsKt.R(compiledFieldC46, builder24.a());
        B = listR27;
        FulfilmentWindowSlotSelectionOptionId.e.getClass();
        List listR28 = CollectionsKt.R(new CompiledField.Builder("enabledOptions", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(FulfilmentWindowSlotSelectionOptionId.Companion.a())))).c(), new CompiledField.Builder("excludedOptions", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(FulfilmentWindowSlotSelectionOptionId.Companion.a())))).c(), new CompiledField.Builder("selectedOption", FulfilmentWindowSlotSelectionOptionId.Companion.a()).c(), new CompiledField.Builder("isLastWindow", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        C = listR28;
        CompiledField compiledFieldC47 = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC48 = new CompiledField.Builder("startTime", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldE3 = com.google.android.gms.common.api.internal.a.e("includeTimeSelectionContent", false, new CompiledField.Builder(k.a.g, CompiledGraphQL.a(CompiledGraphQL.b(CoreTagUI.Companion.a()))), listR22);
        CompiledField compiledFieldE4 = com.google.android.gms.common.api.internal.a.e("includeTimeSelectionContent", false, new CompiledField.Builder("statuses", CompiledGraphQL.a(CompiledGraphQL.b(CoreTagUI.Companion.a()))), listR23);
        CompiledField compiledFieldC49 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC50 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC51 = new CompiledField.Builder("secondarySubtitle", GraphQLString.Companion.a()).c();
        CompiledField compiledFieldC52 = new CompiledField.Builder("sectionTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC53 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC54 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC55 = new CompiledField.Builder("isEnabled", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField.Builder builder25 = new CompiledField.Builder("badge", objectType10);
        builder25.a("directToBootNowV2Badge");
        builder25.e(listR25);
        CompiledField compiledFieldC56 = builder25.c();
        CompiledField.Builder builder26 = new CompiledField.Builder("tileBadge", objectType10);
        builder26.e(listR26);
        CompiledField compiledFieldC57 = builder26.c();
        CompiledField.Builder builder27 = new CompiledField.Builder("selectionInfo", objectType3);
        builder27.e(listR27);
        CompiledField compiledFieldC58 = builder27.c();
        ObjectType objectType11 = FulfilmentWindowSlotSelectionOptionsState.f11418a;
        List listR29 = CollectionsKt.R(compiledFieldC47, compiledFieldC48, compiledFieldE3, compiledFieldE4, compiledFieldC49, compiledFieldC50, compiledFieldC51, compiledFieldC52, compiledFieldC53, compiledFieldC54, compiledFieldC55, compiledFieldC56, compiledFieldC57, compiledFieldC58, com.google.android.gms.common.api.internal.a.e("includeExtraInfoContent", false, new CompiledField.Builder("selectionOptionsState", objectType11), listR28));
        D = listR29;
        List listR30 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        E = listR30;
        List listR31 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("style", CompiledGraphQL.b(enumType)).c());
        F = listR31;
        CompiledField compiledFieldC59 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder28 = new CompiledFragment.Builder("FulfilmentWindowSlotSelectionInfo", CollectionsKt.Q("FulfilmentWindowSlotSelectionInfo"));
        builder28.b(list);
        List listR32 = CollectionsKt.R(compiledFieldC59, builder28.a());
        G = listR32;
        List listR33 = CollectionsKt.R(new CompiledField.Builder("enabledOptions", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(FulfilmentWindowSlotSelectionOptionId.Companion.a())))).c(), new CompiledField.Builder("excludedOptions", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(FulfilmentWindowSlotSelectionOptionId.Companion.a())))).c(), new CompiledField.Builder("selectedOption", FulfilmentWindowSlotSelectionOptionId.Companion.a()).c(), new CompiledField.Builder("isLastWindow", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c());
        H = listR33;
        CompiledField compiledFieldC60 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder29 = new CompiledFragment.Builder("CoreTagUI", CollectionsKt.Q("CoreTagUI"));
        builder29.b(CoreTagUISelections.a());
        List listR34 = CollectionsKt.R(compiledFieldC60, builder29.a());
        I = listR34;
        CompiledField compiledFieldC61 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder30 = new CompiledFragment.Builder("CoreTagUI", CollectionsKt.Q("CoreTagUI"));
        builder30.b(CoreTagUISelections.a());
        List listR35 = CollectionsKt.R(compiledFieldC61, builder30.a());
        J = listR35;
        CompiledField compiledFieldC62 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC63 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC64 = new CompiledField.Builder("startTime", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC65 = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC66 = new CompiledField.Builder("isAvailable", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC67 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC68 = new CompiledField.Builder("isPartnerDriver", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC69 = new CompiledField.Builder("sectionTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder31 = new CompiledField.Builder("badges", a.f(objectType2));
        builder31.e(listR31);
        CompiledField compiledFieldC70 = builder31.c();
        CompiledField.Builder builder32 = new CompiledField.Builder("selectionInfo", objectType3);
        builder32.e(listR32);
        List listR36 = CollectionsKt.R(compiledFieldC62, compiledFieldC63, compiledFieldC64, compiledFieldC65, compiledFieldC66, compiledFieldC67, compiledFieldC68, compiledFieldC69, compiledFieldC70, builder32.c(), com.google.android.gms.common.api.internal.a.e("includeExtraInfoContent", false, new CompiledField.Builder("selectionOptionsState", objectType11), listR33), com.google.android.gms.common.api.internal.a.e("includeTimeSelectionContent", false, new CompiledField.Builder(k.a.g, CompiledGraphQL.a(CompiledGraphQL.b(CoreTagUI.Companion.a()))), listR34), com.google.android.gms.common.api.internal.a.e("includeTimeSelectionContent", false, new CompiledField.Builder("statuses", CompiledGraphQL.a(CompiledGraphQL.b(CoreTagUI.Companion.a()))), listR35));
        K = listR36;
        List listR37 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("style", CompiledGraphQL.b(enumType)).c());
        L = listR37;
        CompiledField compiledFieldC71 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder33 = new CompiledFragment.Builder("FulfilmentWindowSlotSelectionInfo", CollectionsKt.Q("FulfilmentWindowSlotSelectionInfo"));
        builder33.b(list);
        List listR38 = CollectionsKt.R(compiledFieldC71, builder33.a());
        M = listR38;
        CompiledField compiledFieldC72 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder34 = new CompiledFragment.Builder("CoreTagUI", CollectionsKt.Q("CoreTagUI"));
        builder34.b(CoreTagUISelections.a());
        List listR39 = CollectionsKt.R(compiledFieldC72, builder34.a());
        N = listR39;
        CompiledField compiledFieldC73 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder35 = new CompiledFragment.Builder("CoreTagUI", CollectionsKt.Q("CoreTagUI"));
        builder35.b(CoreTagUISelections.a());
        List listR40 = CollectionsKt.R(compiledFieldC73, builder35.a());
        O = listR40;
        CompiledField compiledFieldC74 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC75 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC76 = new CompiledField.Builder("startTime", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC77 = new CompiledField.Builder("id", CompiledGraphQL.b(GraphQLInt.Companion.a())).c();
        CompiledField compiledFieldC78 = new CompiledField.Builder("isAvailable", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC79 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC80 = new CompiledField.Builder("isPartnerDriver", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC81 = new CompiledField.Builder("sectionTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder36 = new CompiledField.Builder("badges", a.f(objectType2));
        builder36.e(listR37);
        CompiledField compiledFieldC82 = builder36.c();
        CompiledField.Builder builder37 = new CompiledField.Builder("selectionInfo", objectType3);
        builder37.e(listR38);
        CompiledField compiledFieldC83 = builder37.c();
        CompiledField.Builder builder38 = new CompiledField.Builder(k.a.g, CompiledGraphQL.a(CompiledGraphQL.b(CoreTagUI.Companion.a())));
        builder38.e(listR39);
        CompiledField compiledFieldC84 = builder38.c();
        CompiledField.Builder builder39 = new CompiledField.Builder("statuses", CompiledGraphQL.a(CompiledGraphQL.b(CoreTagUI.Companion.a())));
        builder39.e(listR40);
        List listR41 = CollectionsKt.R(compiledFieldC74, compiledFieldC75, compiledFieldC76, compiledFieldC77, compiledFieldC78, compiledFieldC79, compiledFieldC80, compiledFieldC81, compiledFieldC82, compiledFieldC83, compiledFieldC84, builder39.c());
        P = listR41;
        CompiledField compiledFieldC85 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC86 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC87 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType12 = CheckoutFulfilmentWindowGroupMessage.f11207a;
        CompiledField.Builder builder40 = new CompiledField.Builder("message", CheckoutFulfilmentWindowGroupMessage.f11207a);
        builder40.e(listR30);
        CompiledField compiledFieldC88 = builder40.c();
        CompiledField compiledFieldC89 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, GraphQLString.Companion.a()).c();
        CompiledField.Builder builder41 = new CompiledField.Builder("slots", a.f(objectType5));
        builder41.e(listR36);
        List listR42 = CollectionsKt.R(compiledFieldC85, compiledFieldC86, compiledFieldC87, compiledFieldC88, compiledFieldC89, builder41.c(), com.google.android.gms.common.api.internal.a.e("includeSuggestedTimeSlot", false, new CompiledField.Builder("slotsV2", a.f(objectType5)), listR41));
        Q = listR42;
        CompiledField compiledFieldC90 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC91 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC92 = new CompiledField.Builder("isAvailable", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC93 = new CompiledField.Builder("isSelected", CompiledGraphQL.b(GraphQLBoolean.Companion.a())).c();
        CompiledField compiledFieldC94 = new CompiledField.Builder("footer", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType13 = FulfilmentWindowFooterV2.f11414a;
        CompiledField compiledFieldE5 = com.google.android.gms.common.api.internal.a.e("includeTimeSelectionContent", false, new CompiledField.Builder("footerV2", FulfilmentWindowFooterV2.f11414a), listR10);
        CompiledField compiledFieldC95 = new CompiledField.Builder("sectionTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType14 = ExtraInfoButton.f11383a;
        CompiledField compiledFieldE6 = com.google.android.gms.common.api.internal.a.e("includeExtraInfoContent", false, new CompiledField.Builder("extraInfoButton", ExtraInfoButton.f11383a), listR11);
        ObjectType objectType15 = FulfilmentExtraInfo.f11404a;
        CompiledField compiledFieldE7 = com.google.android.gms.common.api.internal.a.e("includeExtraInfoContent", false, new CompiledField.Builder("extraInfo", objectType15), listR12);
        ObjectType objectType16 = CheckoutDeliveryNowWindow.f11199a;
        CompiledField.Builder builder42 = new CompiledField.Builder("deliveryNowV2", CheckoutDeliveryNowWindow.f11199a);
        builder42.e(listR20);
        CompiledField compiledFieldC96 = builder42.c();
        DeliveryNowStatus.e.getClass();
        CompiledField compiledFieldC97 = new CompiledField.Builder("deliveryNowStatus", CompiledGraphQL.b(DeliveryNowStatus.f)).c();
        ObjectType objectType17 = CheckoutDirectToBootNowWindow.f11202a;
        CompiledField.Builder builder43 = new CompiledField.Builder("directToBootNow", objectType17);
        builder43.e(listR21);
        CompiledField compiledFieldC98 = builder43.c();
        CompiledField.Builder builder44 = new CompiledField.Builder("directToBootNowV2", objectType17);
        builder44.e(listR29);
        CompiledField compiledFieldC99 = builder44.c();
        DirectToBootNowStatus.e.getClass();
        CompiledField compiledFieldC100 = new CompiledField.Builder("directToBootNowStatus", CompiledGraphQL.b(DirectToBootNowStatus.f)).c();
        ObjectType objectType18 = CheckoutFulfilmentWindowGroup.f11206a;
        CompiledField.Builder builder45 = new CompiledField.Builder("groups", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutFulfilmentWindowGroup.f11206a))));
        builder45.e(listR42);
        List listR43 = CollectionsKt.R(compiledFieldC90, compiledFieldC91, compiledFieldC92, compiledFieldC93, compiledFieldC94, compiledFieldE5, compiledFieldC95, compiledFieldE6, compiledFieldE7, compiledFieldC96, compiledFieldC97, compiledFieldC98, compiledFieldC99, compiledFieldC100, builder45.c());
        R = listR43;
        CompiledField compiledFieldC101 = new CompiledField.Builder("__typename", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledFragment.Builder builder46 = new CompiledFragment.Builder("FulfilmentExtraInfo", CollectionsKt.Q("FulfilmentExtraInfo"));
        builder46.b(list2);
        List listR44 = CollectionsKt.R(compiledFieldC101, builder46.a());
        S = listR44;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        T = listQ2;
        List listR45 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        U = listR45;
        CompiledField compiledFieldC102 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder47 = new CompiledField.Builder("altLabel", TextWithAlt.Companion.a());
        builder47.e(listR45);
        List listR46 = CollectionsKt.R(compiledFieldC102, builder47.c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c());
        V = listR46;
        List listR47 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        W = listR47;
        CompiledField compiledFieldC103 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder48 = new CompiledField.Builder("altLabel", TextWithAlt.Companion.a());
        builder48.e(listR47);
        List listR48 = CollectionsKt.R(compiledFieldC103, builder48.c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType2)).c());
        X = listR48;
        CompiledField compiledFieldC104 = new CompiledField.Builder("selectionOptionId", CompiledGraphQL.b(FulfilmentWindowSlotSelectionOptionId.Companion.a())).c();
        CompiledField compiledFieldC105 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder49 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(CoreIcon.f11290a));
        builder49.e(listQ2);
        CompiledField compiledFieldC106 = builder49.c();
        CompiledField compiledFieldC107 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField.Builder builder50 = new CompiledField.Builder(k.a.g, a.f(objectType10));
        builder50.a("selectionOptionsInfoTags");
        builder50.e(listR46);
        CompiledField compiledFieldC108 = builder50.c();
        CompiledField.Builder builder51 = new CompiledField.Builder("disabledBadge", CompiledGraphQL.b(objectType10));
        builder51.e(listR48);
        List listR49 = CollectionsKt.R(compiledFieldC104, compiledFieldC105, compiledFieldC106, compiledFieldC107, compiledFieldC108, builder51.c(), new CompiledField.Builder("disabledTitle", CompiledGraphQL.b(GraphQLString.Companion.a())).c(), new CompiledField.Builder("disabledDescription", CompiledGraphQL.b(GraphQLString.Companion.a())).c());
        Y = listR49;
        CompiledField compiledFieldC109 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType19 = FulfilmentWindowSlotSelectionOption.f11417a;
        CompiledField.Builder builder52 = new CompiledField.Builder("selectionOptions", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(FulfilmentWindowSlotSelectionOption.f11417a))));
        builder52.e(listR49);
        List listR50 = CollectionsKt.R(compiledFieldC109, builder52.c());
        Z = listR50;
        CompiledField compiledFieldC110 = new CompiledField.Builder("title", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        CompiledField compiledFieldC111 = new CompiledField.Builder("header", CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType20 = InsetBanner.f11509a;
        CompiledField.Builder builder53 = new CompiledField.Builder("subheader", InsetBanner.Companion.a());
        builder53.e(listR2);
        CompiledField compiledFieldC112 = builder53.c();
        CompiledField compiledFieldC113 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(GraphQLString.Companion.a())).c();
        ObjectType objectType21 = FulfilmentWindowsFooter.f11420a;
        CompiledField.Builder builder54 = new CompiledField.Builder("footer", FulfilmentWindowsFooter.f11420a);
        builder54.e(listQ);
        CompiledField compiledFieldC114 = builder54.c();
        CompiledField.Builder builder55 = new CompiledField.Builder("sectionHeader", GraphQLString.Companion.a());
        builder55.d(CollectionsKt.Q(new CompiledCondition("includeTimeSelectionContent", false)));
        CompiledField compiledFieldC115 = builder55.c();
        ObjectType objectType22 = CheckoutFulfilmentSuggestedGroup.f11204a;
        CompiledField compiledFieldE8 = com.google.android.gms.common.api.internal.a.e("includeSuggestedTimeSlot", false, new CompiledField.Builder("suggestedGroup", CheckoutFulfilmentSuggestedGroup.f11204a), listR9);
        ObjectType objectType23 = CheckoutFulfilmentWindow.f11205a;
        CompiledField.Builder builder56 = new CompiledField.Builder("options", CompiledGraphQL.b(CompiledGraphQL.a(CompiledGraphQL.b(CheckoutFulfilmentWindow.f11205a))));
        builder56.e(listR43);
        CompiledField compiledFieldC116 = builder56.c();
        CompiledField compiledFieldE9 = com.google.android.gms.common.api.internal.a.e("includeExtraInfoContent", false, new CompiledField.Builder("feesInfo", objectType15), listR44);
        ObjectType objectType24 = FulfilmentWindowSelectionOptionsInfo.f11415a;
        a0 = CollectionsKt.R(compiledFieldC110, compiledFieldC111, compiledFieldC112, compiledFieldC113, compiledFieldC114, compiledFieldC115, compiledFieldE8, compiledFieldC116, compiledFieldE9, com.google.android.gms.common.api.internal.a.e("includeExtraInfoContent", false, new CompiledField.Builder("selectionOptionsInfo", FulfilmentWindowSelectionOptionsInfo.f11415a), listR50));
    }
}
