package com.woolworths.shop.checkout.fragment.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.sdui.shop.fragment.selections.AnalyticsFieldsSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.CoreAlertStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerUI;
import au.com.woolworths.shop.graphql.type.CoreInsetAlertUI;
import au.com.woolworths.shop.graphql.type.CoreRowUI;
import au.com.woolworths.shop.graphql.type.FulfilmentExtraInfoContent;
import au.com.woolworths.shop.graphql.type.FulfilmentFeeItem;
import au.com.woolworths.shop.graphql.type.FulfilmentFeePriceInfo;
import au.com.woolworths.shop.graphql.type.FulfilmentRowAccordionExpandedContent;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.IconAsset;
import au.com.woolworths.shop.graphql.type.ParagraphTextItemType;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/checkout/fragment/selections/FulfilmentExtraInfoSelections;", "", "shop-checkout_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class FulfilmentExtraInfoSelections {
    public static final List A;
    public static final List B;
    public static final List C;

    /* renamed from: a, reason: collision with root package name */
    public static final List f22542a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        CompiledField compiledFieldC = new CompiledField.Builder("title", customScalarType).c();
        CompiledField compiledFieldG = d.g(lqlqqlq.mmm006Dm006Dm, customScalarType);
        CoreAlertStyle.e.getClass();
        List listR = CollectionsKt.R(compiledFieldC, compiledFieldG, new CompiledField.Builder("style", CompiledGraphQL.b(CoreAlertStyle.f)).c());
        f22542a = listR;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        List list = AnalyticsFieldsSelections.b;
        builder.b(list);
        List listR2 = CollectionsKt.R(compiledFieldC2, builder.a());
        b = listR2;
        CompiledField compiledFieldG2 = d.g("id", customScalarType);
        ActionType.e.getClass();
        EnumType enumType = ActionType.f;
        CompiledField compiledFieldC3 = new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c();
        ObjectType objectType = Analytics.f11028a;
        CompiledField.Builder builder2 = new CompiledField.Builder("analytics", objectType);
        builder2.e = listR2;
        List listR3 = CollectionsKt.R(compiledFieldG2, compiledFieldC3, compiledFieldC4, builder2.c());
        c = listR3;
        CompiledField.Builder builder3 = new CompiledField.Builder("insetAlertUI", CompiledGraphQL.b(CoreInsetAlertUI.f11291a));
        builder3.e = listR;
        CompiledField compiledFieldC5 = builder3.c();
        ObjectType objectType2 = Action.f10997a;
        CompiledField.Builder builder4 = new CompiledField.Builder("insetAlertAction", objectType2);
        builder4.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC5, builder4.c(), d.g("insetAlertActionLabel", customScalarType));
        d = listR4;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder5 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder5.d = list;
        List listR5 = CollectionsKt.R(compiledFieldC6, builder5.a());
        e = listR5;
        CompiledField compiledFieldC7 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder6.d = list;
        List listR6 = CollectionsKt.R(compiledFieldC7, builder6.a());
        f = listR6;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(customScalarType)).c());
        g = listQ;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        h = listQ2;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder7.d = listQ;
        CompiledFragment compiledFragmentA = builder7.a();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder8.d = listQ2;
        List listR7 = CollectionsKt.R(compiledFieldC8, compiledFragmentA, builder8.a());
        i = listR7;
        CompiledField compiledFieldC9 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG3 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CoreBroadcastBannerStyle.e.getClass();
        CompiledField compiledFieldC10 = new CompiledField.Builder("style", CompiledGraphQL.b(CoreBroadcastBannerStyle.f)).c();
        UnionType unionType = IconAsset.f11477a;
        CompiledField.Builder builder9 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(unionType));
        builder9.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC9, compiledFieldG3, compiledFieldC10, builder9.c());
        j = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c(), d.g("id", customScalarType), new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c());
        k = listR9;
        CompiledField.Builder builder10 = new CompiledField.Builder("impressionAnalytics", objectType);
        builder10.e = listR5;
        CompiledField compiledFieldC11 = builder10.c();
        CompiledField.Builder builder11 = new CompiledField.Builder("broadcastBannerDismissAnalytics", objectType);
        builder11.e = listR6;
        CompiledField compiledFieldC12 = builder11.c();
        CompiledField.Builder builder12 = new CompiledField.Builder("broadcastBannerUI", CompiledGraphQL.b(CoreBroadcastBannerUI.f11286a));
        builder12.e = listR8;
        CompiledField compiledFieldC13 = builder12.c();
        CompiledField.Builder builder13 = new CompiledField.Builder("broadcastBannerAction", objectType2);
        builder13.e = listR9;
        CompiledField compiledFieldC14 = builder13.c();
        CompiledField compiledFieldG4 = d.g("broadcastBannerActionLabel", customScalarType);
        CompiledField compiledFieldG5 = d.g("broadcastBannerId", customScalarType);
        CustomScalarType customScalarType2 = GraphQLBoolean.f11439a;
        List listR10 = CollectionsKt.R(compiledFieldC11, compiledFieldC12, compiledFieldC13, compiledFieldC14, compiledFieldG4, compiledFieldG5, new CompiledField.Builder("broadcastBannerDismissible", CompiledGraphQL.b(customScalarType2)).c());
        l = listR10;
        List listR11 = CollectionsKt.R(new CompiledField.Builder("amount", CompiledGraphQL.b(customScalarType)).c(), d.g(lqlqqlq.mmm006Dm006Dm, customScalarType));
        m = listR11;
        CompiledField compiledFieldC15 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("FulfilmentFeePriceInfo", CollectionsKt.Q("FulfilmentFeePriceInfo"));
        builder14.d = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC15, builder14.a());
        n = listR12;
        CompiledField compiledFieldC16 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG6 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField.Builder builder15 = new CompiledField.Builder("prices", a.f(FulfilmentFeePriceInfo.f11407a));
        builder15.e = listR12;
        List listR13 = CollectionsKt.R(compiledFieldC16, compiledFieldG6, builder15.c());
        o = listR13;
        CompiledField compiledFieldC17 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("FulfilmentFeeItem", CollectionsKt.Q("FulfilmentFeeItem"));
        builder16.d = listR13;
        List listR14 = CollectionsKt.R(compiledFieldC17, builder16.a());
        p = listR14;
        CompiledField compiledFieldG7 = d.g("feesInfoSectionTitle", customScalarType);
        CompiledField.Builder builder17 = new CompiledField.Builder("items", a.f(FulfilmentFeeItem.f11406a));
        builder17.e = listR14;
        List listR15 = CollectionsKt.R(compiledFieldG7, builder17.c());
        q = listR15;
        List listQ3 = CollectionsKt.Q(new CompiledField.Builder("markdownText", CompiledGraphQL.b(customScalarType)).c());
        r = listQ3;
        CompiledField compiledFieldC18 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder18.d = list;
        List listR16 = CollectionsKt.R(compiledFieldC18, builder18.a());
        s = listR16;
        CompiledField compiledFieldC19 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder19.d = list;
        List listR17 = CollectionsKt.R(compiledFieldC19, builder19.a());
        t = listR17;
        List listQ4 = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        u = listQ4;
        List listQ5 = CollectionsKt.Q(new CompiledField.Builder("coreIconName", CompiledGraphQL.b(customScalarType)).c());
        v = listQ5;
        CompiledField compiledFieldC20 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder20 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder20.d = listQ4;
        CompiledFragment compiledFragmentA2 = builder20.a();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("CoreIcon", CollectionsKt.Q("CoreIcon"));
        builder21.d = listQ5;
        List listR18 = CollectionsKt.R(compiledFieldC20, compiledFragmentA2, builder21.a());
        w = listR18;
        CompiledField.Builder builder22 = new CompiledField.Builder("leadingAsset", unionType);
        builder22.e = listR18;
        List listR19 = CollectionsKt.R(builder22.c(), d.g(lqlqqlq.mmm006Dm006Dm, customScalarType), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c());
        x = listR19;
        ParagraphTextItemType.e.getClass();
        List listR20 = CollectionsKt.R(new CompiledField.Builder("type", CompiledGraphQL.b(ParagraphTextItemType.f)).c(), new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        y = listR20;
        CompiledField compiledFieldC21 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("ParagraphTextItem", CollectionsKt.Q("ParagraphTextItem"));
        builder23.d = listR20;
        List listR21 = CollectionsKt.R(compiledFieldC21, builder23.a());
        z = listR21;
        CompiledField.Builder builder24 = new CompiledField.Builder("openActionAnalytics", objectType);
        builder24.e = listR16;
        CompiledField compiledFieldC22 = builder24.c();
        CompiledField.Builder builder25 = new CompiledField.Builder("closeActionAnalytics", objectType);
        builder25.e = listR17;
        CompiledField compiledFieldC23 = builder25.c();
        CompiledField.Builder builder26 = new CompiledField.Builder("rowUI", CompiledGraphQL.b(CoreRowUI.f11293a));
        builder26.e = listR19;
        CompiledField compiledFieldC24 = builder26.c();
        CompiledField compiledFieldC25 = new CompiledField.Builder("isExpanded", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC26 = new CompiledField.Builder("hasTopSeparator", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder27 = new CompiledField.Builder("expandedContent", FulfilmentRowAccordionExpandedContent.f11411a);
        builder27.e = listR21;
        List listR22 = CollectionsKt.R(compiledFieldC22, compiledFieldC23, compiledFieldC24, compiledFieldC25, compiledFieldC26, builder27.c());
        A = listR22;
        CompiledField compiledFieldC27 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder28 = new CompiledFragment.Builder("BasicInsetAlert", CollectionsKt.Q("BasicInsetAlert"));
        builder28.d = listR4;
        CompiledFragment compiledFragmentA3 = builder28.a();
        CompiledFragment.Builder builder29 = new CompiledFragment.Builder("BasicCoreBroadcastBanner", CollectionsKt.Q("BasicCoreBroadcastBanner"));
        builder29.d = listR10;
        CompiledFragment compiledFragmentA4 = builder29.a();
        CompiledFragment.Builder builder30 = new CompiledFragment.Builder("FulfilmentFeesInfoSection", CollectionsKt.Q("FulfilmentFeesInfoSection"));
        builder30.d = listR15;
        CompiledFragment compiledFragmentA5 = builder30.a();
        CompiledFragment.Builder builder31 = new CompiledFragment.Builder("CheckoutTermsConditions", CollectionsKt.Q("CheckoutTermsConditions"));
        builder31.d = listQ3;
        CompiledFragment compiledFragmentA6 = builder31.a();
        CompiledFragment.Builder builder32 = new CompiledFragment.Builder("FulfilmentInfoRowAccordion", CollectionsKt.Q("FulfilmentInfoRowAccordion"));
        builder32.d = listR22;
        List listR23 = CollectionsKt.R(compiledFieldC27, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, builder32.a());
        B = listR23;
        CompiledField compiledFieldC28 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder33 = new CompiledField.Builder("content", d.j(FulfilmentExtraInfoContent.f11405a));
        builder33.e = listR23;
        C = CollectionsKt.R(compiledFieldC28, builder33.c());
    }
}
