package com.woolworths.rewards.offers.fragment.fragment.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.rewards.graphql.type.ContentCta;
import au.com.woolworths.rewards.graphql.type.DownloadableAsset;
import au.com.woolworths.rewards.graphql.type.DownloadableAssetFit;
import au.com.woolworths.rewards.graphql.type.DownloadableAssetType;
import au.com.woolworths.rewards.graphql.type.GraphQLBoolean;
import au.com.woolworths.rewards.graphql.type.GraphQLID;
import au.com.woolworths.rewards.graphql.type.GraphQLInt;
import au.com.woolworths.rewards.graphql.type.GraphQLString;
import au.com.woolworths.rewards.graphql.type.IconAsset;
import au.com.woolworths.rewards.graphql.type.PersonalisedOffersStatus;
import au.com.woolworths.rewards.graphql.type.ProductOffersSectionLayout;
import au.com.woolworths.rewards.graphql.type.RewardsOffer;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.ObjectType;
import com.apollographql.apollo.api.UnionType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.woolworths.rewards.offers.fragment.selections.IconAssetSelections;
import com.woolworths.rewards.offers.fragment.selections.RewardsOfferFieldsSelections;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/rewards/offers/fragment/fragment/selections/OffersSectionsFragmentSelections;", "", "offers_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class OffersSectionsFragmentSelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f21038a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;

    static {
        CustomScalarType customScalarType = GraphQLString.f9617a;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("StandardBanner", CollectionsKt.Q("StandardBanner"));
        builder.b(StandardBannerFieldsSelections.f21039a);
        List listR = CollectionsKt.R(compiledFieldC, builder.a());
        f21038a = listR;
        CustomScalarType customScalarType2 = GraphQLID.f9615a;
        List listR2 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("mandyBannerAction", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("mandyImageUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("mandyBannerTitle", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("mandyBannerDescription", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("mandyBannerAction", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("mandyBannerActionUrl", CompiledGraphQL.b(customScalarType)).c());
        b = listR2;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        c = listQ;
        CompiledField compiledFieldC2 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder2 = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder2.d = listQ;
        List listR3 = CollectionsKt.R(compiledFieldC2, builder2.a());
        d = listR3;
        UnionType unionType = IconAsset.f9623a;
        CompiledField.Builder builder3 = new CompiledField.Builder("emptyStateIconAsset", unionType);
        builder3.e = listR3;
        List listR4 = CollectionsKt.R(builder3.c(), d.g("emptyStateTitle", customScalarType), d.g("emptyStateMessage", customScalarType));
        e = listR4;
        CompiledField compiledFieldC3 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder4 = new CompiledFragment.Builder("RewardsOffer", CollectionsKt.Q("RewardsOffer"));
        List list = RewardsOfferFieldsSelections.q;
        builder4.b(list);
        List listR5 = CollectionsKt.R(compiledFieldC3, builder4.a());
        f = listR5;
        CompiledField compiledFieldC4 = new CompiledField.Builder("sectionId", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldG = d.g("sectionTitle", customScalarType);
        ObjectType objectType = RewardsOffer.f9835a;
        CompiledField.Builder builder5 = new CompiledField.Builder("items", a.f(objectType));
        builder5.e = listR5;
        List listR6 = CollectionsKt.R(compiledFieldC4, compiledFieldG, builder5.c());
        g = listR6;
        CompiledField compiledFieldC5 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder6 = new CompiledFragment.Builder("ContentCta", CollectionsKt.Q("ContentCta"));
        builder6.b(ContentCtaFieldsSelections.b);
        List listR7 = CollectionsKt.R(compiledFieldC5, builder6.a());
        h = listR7;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder7 = new CompiledFragment.Builder("RewardsOffer", CollectionsKt.Q("RewardsOffer"));
        builder7.d = list;
        List listR8 = CollectionsKt.R(compiledFieldC6, builder7.a());
        i = listR8;
        CompiledField compiledFieldC7 = new CompiledField.Builder("sectionId", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldG2 = d.g("sectionTitle", customScalarType);
        CompiledField compiledFieldG3 = d.g("sectionSubtitle", customScalarType);
        CompiledField compiledFieldG4 = d.g("endedOffersSectionSubtitle", customScalarType);
        CompiledField.Builder builder8 = new CompiledField.Builder("sectionCta", ContentCta.f9485a);
        builder8.e = listR7;
        CompiledField compiledFieldC8 = builder8.c();
        CompiledField.Builder builder9 = new CompiledField.Builder("items", a.f(objectType));
        builder9.e = listR8;
        CompiledField compiledFieldC9 = builder9.c();
        ProductOffersSectionLayout.e.getClass();
        List listR9 = CollectionsKt.R(compiledFieldC7, compiledFieldG2, compiledFieldG3, compiledFieldG4, compiledFieldC8, compiledFieldC9, new CompiledField.Builder("layout", CompiledGraphQL.b(ProductOffersSectionLayout.f)).c());
        j = listR9;
        DownloadableAssetType.e.getClass();
        CompiledField compiledFieldC10 = new CompiledField.Builder("assetType", CompiledGraphQL.b(DownloadableAssetType.f)).c();
        CompiledField compiledFieldC11 = new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType3 = GraphQLInt.f9616a;
        CompiledField compiledFieldC12 = new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType3)).c();
        CompiledField compiledFieldC13 = new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType3)).c();
        DownloadableAssetFit.e.getClass();
        List listR10 = CollectionsKt.R(compiledFieldC10, compiledFieldC11, compiledFieldC12, compiledFieldC13, new CompiledField.Builder("fit", DownloadableAssetFit.f).c());
        k = listR10;
        CompiledField compiledFieldC14 = new CompiledField.Builder("bannerId", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder10 = new CompiledField.Builder("bannerAsset", CompiledGraphQL.b(DownloadableAsset.f9500a));
        builder10.e = listR10;
        List listR11 = CollectionsKt.R(compiledFieldC14, builder10.c(), d.g("bannerActionUrl", customScalarType));
        l = listR11;
        CompiledField compiledFieldC15 = new CompiledField.Builder("bannerId", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC16 = new CompiledField.Builder("imageUrl", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC17 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC18 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c();
        PersonalisedOffersStatus.e.getClass();
        List listR12 = CollectionsKt.R(compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, new CompiledField.Builder("status", CompiledGraphQL.b(PersonalisedOffersStatus.f)).c(), new CompiledField.Builder("bannerActionUrl", CompiledGraphQL.b(customScalarType)).c());
        m = listR12;
        CompiledField compiledFieldC19 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("IconAsset", CollectionsKt.R("LocalAsset", "HostedIcon", "CoreIcon"));
        List list2 = IconAssetSelections.d;
        builder11.b(list2);
        List listR13 = CollectionsKt.R(compiledFieldC19, builder11.a());
        n = listR13;
        CompiledField compiledFieldC20 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("IconAsset", CollectionsKt.R("LocalAsset", "HostedIcon", "CoreIcon"));
        builder12.d = list2;
        List listR14 = CollectionsKt.R(compiledFieldC20, builder12.a());
        o = listR14;
        CompiledField compiledFieldC21 = new CompiledField.Builder("inlineBannerId", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder13 = new CompiledField.Builder("inlineBannerLeadingIcon", unionType);
        builder13.e = listR13;
        CompiledField compiledFieldC22 = builder13.c();
        CompiledField.Builder builder14 = new CompiledField.Builder("inlineBannerTrailingIcon", unionType);
        builder14.e = listR14;
        CompiledField compiledFieldC23 = builder14.c();
        CompiledField compiledFieldG5 = d.g("inlineBannerTitle", customScalarType);
        CompiledField compiledFieldG6 = d.g("inlineBannerDescription", customScalarType);
        CompiledField compiledFieldC24 = new CompiledField.Builder("inlineBannerActionUrl", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType4 = GraphQLBoolean.f9613a;
        List listR15 = CollectionsKt.R(compiledFieldC21, compiledFieldC22, compiledFieldC23, compiledFieldG5, compiledFieldG6, compiledFieldC24, new CompiledField.Builder("showIsNewLabel", customScalarType4).c(), d.g("dismissible", customScalarType4));
        p = listR15;
        List listR16 = CollectionsKt.R(new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("actionUrl", CompiledGraphQL.b(customScalarType)).c());
        q = listR16;
        CompiledField compiledFieldC25 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("StandardBanner", CollectionsKt.Q("StandardBanner"));
        builder15.d = listR;
        CompiledFragment compiledFragmentA = builder15.a();
        CompiledFragment.Builder builder16 = new CompiledFragment.Builder("MandyBanner", CollectionsKt.Q("MandyBanner"));
        builder16.c = a.s("isMandyBannerEnabled", false);
        builder16.d = listR2;
        CompiledFragment compiledFragmentA2 = builder16.a();
        CompiledFragment.Builder builder17 = new CompiledFragment.Builder("NoOffersCard", CollectionsKt.Q("NoOffersCard"));
        builder17.d = listR4;
        CompiledFragment compiledFragmentA3 = builder17.a();
        CompiledFragment.Builder builder18 = new CompiledFragment.Builder("StandardOffersSection", CollectionsKt.Q("StandardOffersSection"));
        builder18.d = listR6;
        CompiledFragment compiledFragmentA4 = builder18.a();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("ProductOffersSection", CollectionsKt.Q("ProductOffersSection"));
        builder19.d = listR9;
        CompiledFragment compiledFragmentA5 = builder19.a();
        CompiledFragment.Builder builder20 = new CompiledFragment.Builder("SpinSurpriseBanner", CollectionsKt.Q("SpinSurpriseBanner"));
        builder20.c = a.s("isSpinSurpriseEnabled", false);
        builder20.d = listR11;
        CompiledFragment compiledFragmentA6 = builder20.a();
        CompiledFragment.Builder builder21 = new CompiledFragment.Builder("PersonalisedOffersBanner", CollectionsKt.Q("PersonalisedOffersBanner"));
        builder21.c = a.s("isPersonalisedOffersEnabled", false);
        builder21.d = listR12;
        CompiledFragment compiledFragmentA7 = builder21.a();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("OfferFeedInlineBanner", CollectionsKt.Q("OfferFeedInlineBanner"));
        builder22.c = a.s("isAutoBoostFeatureEnabled", false);
        builder22.d = listR15;
        CompiledFragment compiledFragmentA8 = builder22.a();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("RewardsCtaCard", CollectionsKt.Q("RewardsCtaCard"));
        builder23.c = a.s("isAutoBoostFeatureEnabled", false);
        builder23.d = listR16;
        r = CollectionsKt.R(compiledFieldC25, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, compiledFragmentA4, compiledFragmentA5, compiledFragmentA6, compiledFragmentA7, compiledFragmentA8, builder23.a());
    }
}
