package com.woolworths.shop.deliveryunlimited.signup.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.shop.graphql.type.Badge;
import au.com.woolworths.shop.graphql.type.BadgeType;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribe;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribeDisclaimer;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribeFeature;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribeFeatureLink;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribeFooter;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribeLink;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribePlanType;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribePlanTypeFeedItem;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribePlans;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribeSummary;
import au.com.woolworths.shop.graphql.type.DeliveryUnlimitedSubscribeTermsMarkdown;
import au.com.woolworths.shop.graphql.type.DownloadableAsset;
import au.com.woolworths.shop.graphql.type.DownloadableAssetFit;
import au.com.woolworths.shop.graphql.type.DownloadableAssetType;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLID;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.InsetBannerAction;
import au.com.woolworths.shop.graphql.type.InsetBannerActionPlacement;
import au.com.woolworths.shop.graphql.type.InsetBannerActionType;
import au.com.woolworths.shop.graphql.type.InsetBannerDisplayType;
import au.com.woolworths.shop.graphql.type.SpacerType;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.i18n.ErrorBundle;
import org.bouncycastle.i18n.TextBundle;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/shop/deliveryunlimited/signup/selections/DeliveryUnlimitedSubscribeQuerySelections;", "", "shop-delivery-unlimited-sign-up_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes7.dex */
public final class DeliveryUnlimitedSubscribeQuerySelections {

    /* renamed from: a, reason: collision with root package name */
    public static final List f22671a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;

    static {
        DownloadableAssetType.e.getClass();
        CompiledField compiledFieldC = new CompiledField.Builder("assetType", CompiledGraphQL.b(DownloadableAssetType.f)).c();
        CustomScalarType customScalarType = GraphQLString.f11443a;
        CompiledField compiledFieldC2 = new CompiledField.Builder("assetUrl", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLInt.f11442a;
        CompiledField compiledFieldC3 = new CompiledField.Builder("assetWidth", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC4 = new CompiledField.Builder("assetHeight", CompiledGraphQL.b(customScalarType2)).c();
        DownloadableAssetFit.e.getClass();
        List listR = CollectionsKt.R(compiledFieldC, compiledFieldC2, compiledFieldC3, compiledFieldC4, new CompiledField.Builder("fit", DownloadableAssetFit.f).c(), d.g("altText", customScalarType));
        f22671a = listR;
        CompiledField compiledFieldC5 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        BadgeType.e.getClass();
        EnumType enumType = BadgeType.f;
        List listR2 = CollectionsKt.R(compiledFieldC5, new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c());
        b = listR2;
        List listR3 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        c = listR3;
        CompiledField compiledFieldC6 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC7 = new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC8 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder = new CompiledField.Builder("link", DeliveryUnlimitedSubscribeFeatureLink.f11327a);
        builder.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC6, compiledFieldC7, compiledFieldC8, builder.c());
        d = listR4;
        CompiledField compiledFieldC9 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        ButtonStyle.e.getClass();
        EnumType enumType2 = ButtonStyle.f;
        CompiledField compiledFieldC10 = new CompiledField.Builder("style", enumType2).c();
        CustomScalarType customScalarType3 = GraphQLBoolean.f11439a;
        List listR5 = CollectionsKt.R(compiledFieldC9, compiledFieldC10, new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType3)).c());
        e = listR5;
        ObjectType objectType = Button.f11080a;
        CompiledField.Builder builder2 = new CompiledField.Builder("button", CompiledGraphQL.b(objectType));
        builder2.e = listR5;
        List listR6 = CollectionsKt.R(builder2.c(), new CompiledField.Builder("disclaimer", CompiledGraphQL.b(customScalarType)).c());
        f = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder(TextBundle.TEXT_ENTRY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        g = listR7;
        CompiledField compiledFieldC11 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC12 = new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder3 = new CompiledField.Builder("links", a.f(DeliveryUnlimitedSubscribeLink.f11329a));
        builder3.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC11, compiledFieldC12, builder3.c());
        h = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        i = listR9;
        CompiledField compiledFieldC13 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder4 = new CompiledField.Builder("bannerAsset", DownloadableAsset.f11349a);
        builder4.e = listR;
        CompiledField compiledFieldC14 = builder4.c();
        ObjectType objectType2 = Badge.f11042a;
        CompiledField.Builder builder5 = new CompiledField.Builder("badge", objectType2);
        builder5.e = listR2;
        CompiledField compiledFieldC15 = builder5.c();
        CompiledField.Builder builder6 = new CompiledField.Builder("features", a.f(DeliveryUnlimitedSubscribeFeature.f11326a));
        builder6.e = listR4;
        CompiledField compiledFieldC16 = builder6.c();
        ObjectType objectType3 = DeliveryUnlimitedSubscribeFooter.f11328a;
        CompiledField.Builder builder7 = new CompiledField.Builder("footer", CompiledGraphQL.b(objectType3));
        builder7.e = listR6;
        CompiledField compiledFieldC17 = builder7.c();
        CompiledField.Builder builder8 = new CompiledField.Builder("disclaimer", DeliveryUnlimitedSubscribeDisclaimer.f11325a);
        builder8.e = listR8;
        CompiledField compiledFieldC18 = builder8.c();
        CompiledField.Builder builder9 = new CompiledField.Builder("termsMarkdown", CompiledGraphQL.b(DeliveryUnlimitedSubscribeTermsMarkdown.f11341a));
        builder9.e = listR9;
        List listR10 = CollectionsKt.R(compiledFieldC13, compiledFieldC14, compiledFieldC15, compiledFieldC16, compiledFieldC17, compiledFieldC18, builder9.c());
        j = listR10;
        InsetBannerActionPlacement.e.getClass();
        CompiledField compiledFieldC19 = new CompiledField.Builder("placement", CompiledGraphQL.b(InsetBannerActionPlacement.f)).c();
        InsetBannerActionType.e.getClass();
        List listR11 = CollectionsKt.R(compiledFieldC19, new CompiledField.Builder("type", CompiledGraphQL.b(InsetBannerActionType.f)).c(), new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), d.g("url", customScalarType));
        k = listR11;
        InsetBannerDisplayType.e.getClass();
        CompiledField compiledFieldC20 = new CompiledField.Builder("displayType", CompiledGraphQL.b(InsetBannerDisplayType.f)).c();
        CompiledField compiledFieldC21 = new CompiledField.Builder("message", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC22 = new CompiledField.Builder("title", customScalarType).c();
        CompiledField.Builder builder10 = new CompiledField.Builder(UrlHandler.ACTION, InsetBannerAction.f11510a);
        builder10.e = listR11;
        List listR12 = CollectionsKt.R(compiledFieldC20, compiledFieldC21, compiledFieldC22, builder10.c());
        l = listR12;
        List listR13 = CollectionsKt.R(new CompiledField.Builder("iconUrl", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, CompiledGraphQL.b(customScalarType)).c());
        m = listR13;
        List listR14 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("type", CompiledGraphQL.b(enumType)).c());
        n = listR14;
        CustomScalarType customScalarType4 = GraphQLID.f11441a;
        CompiledField compiledFieldC23 = new CompiledField.Builder("identifier", CompiledGraphQL.b(customScalarType4)).c();
        CompiledField compiledFieldC24 = new CompiledField.Builder("planTitle", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC25 = new CompiledField.Builder(NotificationMessage.NOTIF_KEY_SUB_TITLE, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC26 = new CompiledField.Builder("price", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField.Builder builder11 = new CompiledField.Builder("badge", objectType2);
        builder11.e = listR14;
        List listR15 = CollectionsKt.R(compiledFieldC23, compiledFieldC24, compiledFieldC25, compiledFieldC26, builder11.c());
        o = listR15;
        SpacerType.e.getClass();
        List listQ = CollectionsKt.Q(new CompiledField.Builder("size", CompiledGraphQL.b(SpacerType.f)).c());
        p = listQ;
        CompiledField compiledFieldC27 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("InsetBanner", CollectionsKt.Q("InsetBanner"));
        builder12.d = listR12;
        CompiledFragment compiledFragmentA = builder12.a();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("DeliveryUnlimitedSubscribeFeature", CollectionsKt.Q("DeliveryUnlimitedSubscribeFeature"));
        builder13.d = listR13;
        CompiledFragment compiledFragmentA2 = builder13.a();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("DeliveryUnlimitedSubscribePlan", CollectionsKt.Q("DeliveryUnlimitedSubscribePlan"));
        builder14.d = listR15;
        CompiledFragment compiledFragmentA3 = builder14.a();
        CompiledFragment.Builder builder15 = new CompiledFragment.Builder("Spacer", CollectionsKt.Q("Spacer"));
        builder15.d = listQ;
        List listR16 = CollectionsKt.R(compiledFieldC27, compiledFragmentA, compiledFragmentA2, compiledFragmentA3, builder15.a());
        q = listR16;
        CompiledField compiledFieldC28 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g("defaultPlanSelection", customScalarType4);
        CompiledField.Builder builder16 = new CompiledField.Builder("feed", d.j(DeliveryUnlimitedSubscribePlanTypeFeedItem.f11333a));
        builder16.e = listR16;
        List listR17 = CollectionsKt.R(compiledFieldC28, compiledFieldG, builder16.c());
        r = listR17;
        List listR18 = CollectionsKt.R(new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c(), a.d("style", enumType2), new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType3)).c());
        s = listR18;
        CompiledField.Builder builder17 = new CompiledField.Builder("button", CompiledGraphQL.b(objectType));
        builder17.e = listR18;
        List listR19 = CollectionsKt.R(builder17.c(), new CompiledField.Builder("disclaimer", CompiledGraphQL.b(customScalarType)).c());
        t = listR19;
        CompiledField compiledFieldC29 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder18 = new CompiledField.Builder("planTypes", a.f(DeliveryUnlimitedSubscribePlanType.f11332a));
        builder18.e = listR17;
        CompiledField compiledFieldC30 = builder18.c();
        CompiledField.Builder builder19 = new CompiledField.Builder("footer", CompiledGraphQL.b(objectType3));
        builder19.e = listR19;
        List listR20 = CollectionsKt.R(compiledFieldC29, compiledFieldC30, builder19.c());
        u = listR20;
        CompiledField.Builder builder20 = new CompiledField.Builder(ErrorBundle.SUMMARY_ENTRY, CompiledGraphQL.b(DeliveryUnlimitedSubscribeSummary.f11338a));
        builder20.e = listR10;
        CompiledField compiledFieldC31 = builder20.c();
        CompiledField.Builder builder21 = new CompiledField.Builder("plans", CompiledGraphQL.b(DeliveryUnlimitedSubscribePlans.f11334a));
        builder21.e = listR20;
        CompiledField compiledFieldC32 = builder21.c();
        CompiledField.Builder builder22 = new CompiledField.Builder("isUserWPayMigrated", CompiledGraphQL.b(customScalarType3));
        builder22.c = a.s("isWPayEnabled", false);
        List listR21 = CollectionsKt.R(compiledFieldC31, compiledFieldC32, builder22.c());
        v = listR21;
        CompiledField.Builder builder23 = new CompiledField.Builder("deliveryUnlimitedSubscribe", DeliveryUnlimitedSubscribe.f11320a);
        builder23.e = listR21;
        w = CollectionsKt.Q(builder23.c());
    }
}
