package com.woolworths.feature.shop.recipes.details.selections;

import androidx.compose.runtime.internal.StabilityInferred;
import au.com.woolworths.dynamic.page.ui.content.d;
import au.com.woolworths.feature.rewards.everydayextras.signup.selections.a;
import au.com.woolworths.sdui.shop.fragment.selections.AnalyticsFieldsSelections;
import au.com.woolworths.shop.aem.components.recipes.fragment.selections.RecipeSummaryCardFragmentSelections;
import au.com.woolworths.shop.graphql.type.Action;
import au.com.woolworths.shop.graphql.type.ActionMetaData;
import au.com.woolworths.shop.graphql.type.ActionType;
import au.com.woolworths.shop.graphql.type.AdBannerNativeSize;
import au.com.woolworths.shop.graphql.type.Analytics;
import au.com.woolworths.shop.graphql.type.BasicCoreBroadcastBanner;
import au.com.woolworths.shop.graphql.type.Button;
import au.com.woolworths.shop.graphql.type.ButtonStyle;
import au.com.woolworths.shop.graphql.type.CardHeight;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerStyle;
import au.com.woolworths.shop.graphql.type.CoreBroadcastBannerUI;
import au.com.woolworths.shop.graphql.type.FeatureType;
import au.com.woolworths.shop.graphql.type.GoogleAdBannerCard;
import au.com.woolworths.shop.graphql.type.GoogleAdCustomTargeting;
import au.com.woolworths.shop.graphql.type.GraphQLBoolean;
import au.com.woolworths.shop.graphql.type.GraphQLFloat;
import au.com.woolworths.shop.graphql.type.GraphQLInt;
import au.com.woolworths.shop.graphql.type.GraphQLString;
import au.com.woolworths.shop.graphql.type.HorizontalList;
import au.com.woolworths.shop.graphql.type.HorizontalListItem;
import au.com.woolworths.shop.graphql.type.IconAsset;
import au.com.woolworths.shop.graphql.type.IngredientsSection;
import au.com.woolworths.shop.graphql.type.MethodDescription;
import au.com.woolworths.shop.graphql.type.MethodItem;
import au.com.woolworths.shop.graphql.type.Query;
import au.com.woolworths.shop.graphql.type.RecipeByLine;
import au.com.woolworths.shop.graphql.type.RecipeCostPerServe;
import au.com.woolworths.shop.graphql.type.RecipeDetail;
import au.com.woolworths.shop.graphql.type.RecipeFeature;
import au.com.woolworths.shop.graphql.type.RecipeMethod;
import au.com.woolworths.shop.graphql.type.RecipeNutritionTile;
import au.com.woolworths.shop.graphql.type.RecipeNutritionTileFeature;
import au.com.woolworths.shop.graphql.type.RecipeServes;
import au.com.woolworths.shop.graphql.type.RecipeUserInteraction;
import au.com.woolworths.shop.graphql.type.ShopIngredientButton;
import au.com.woolworths.shop.graphql.type.TealiumAnalytics;
import au.com.woolworths.shop.graphql.type.UniversalInventory;
import au.com.woolworths.shop.graphql.type.UniversalInventoryNextBestAction;
import au.com.woolworths.shop.graphql.type.Video;
import com.apollographql.apollo.api.CompiledArgument;
import com.apollographql.apollo.api.CompiledField;
import com.apollographql.apollo.api.CompiledFragment;
import com.apollographql.apollo.api.CompiledGraphQL;
import com.apollographql.apollo.api.CustomScalarType;
import com.apollographql.apollo.api.EnumType;
import com.apollographql.apollo.api.ObjectType;
import com.google.android.gms.ads.OutOfContextTestingActivity;
import com.lexisnexisrisk.threatmetrix.rl.tmxprofiling.lqlqqlq;
import com.salesforce.marketingcloud.UrlHandler;
import com.salesforce.marketingcloud.notifications.NotificationMessage;
import com.salesforce.marketingcloud.storage.db.k;
import com.scandit.datacapture.barcode.pick.serialization.BarcodePickDeserializer;
import java.util.List;
import kotlin.Metadata;
import kotlin.collections.CollectionsKt;
import org.bouncycastle.jcajce.util.AnnotatedPrivateKey;

@StabilityInferred
@Metadata(d1 = {"\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\bÇ\u0002\u0018\u00002\u00020\u0001¨\u0006\u0002"}, d2 = {"Lcom/woolworths/feature/shop/recipes/details/selections/RecipeDetailsQuerySelections;", "", "recipe-details_release"}, k = 1, mv = {2, 1, 0}, xi = 48)
/* loaded from: classes3.dex */
public final class RecipeDetailsQuerySelections {
    public static final List A;
    public static final List B;
    public static final List C;
    public static final List D;
    public static final List E;
    public static final List F;
    public static final List G;
    public static final List H;
    public static final List I;
    public static final List J;
    public static final List K;

    /* renamed from: a, reason: collision with root package name */
    public static final List f20315a;
    public static final List b;
    public static final List c;
    public static final List d;
    public static final List e;
    public static final List f;
    public static final List g;
    public static final List h;
    public static final List i;
    public static final List j;
    public static final List k;
    public static final List l;
    public static final List m;
    public static final List n;
    public static final List o;
    public static final List p;
    public static final List q;
    public static final List r;
    public static final List s;
    public static final List t;
    public static final List u;
    public static final List v;
    public static final List w;
    public static final List x;
    public static final List y;
    public static final List z;

    static {
        CustomScalarType customScalarType = GraphQLString.f11443a;
        List listQ = CollectionsKt.Q(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c());
        f20315a = listQ;
        CompiledField compiledFieldC = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder = new CompiledFragment.Builder("HostedIcon", CollectionsKt.Q("HostedIcon"));
        builder.d = listQ;
        List listR = CollectionsKt.R(compiledFieldC, builder.a());
        b = listR;
        CompiledField compiledFieldC2 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CoreBroadcastBannerStyle.e.getClass();
        CompiledField compiledFieldC3 = new CompiledField.Builder("style", CompiledGraphQL.b(CoreBroadcastBannerStyle.f)).c();
        CompiledField.Builder builder2 = new CompiledField.Builder(BarcodePickDeserializer.FIELD_ICON, CompiledGraphQL.b(IconAsset.f11477a));
        builder2.e = listR;
        List listR2 = CollectionsKt.R(compiledFieldC2, compiledFieldG, compiledFieldC3, builder2.c());
        c = listR2;
        CompiledField compiledFieldG2 = d.g("id", customScalarType);
        ActionType.e.getClass();
        List listR3 = CollectionsKt.R(compiledFieldG2, new CompiledField.Builder("type", CompiledGraphQL.b(ActionType.f)).c(), new CompiledField.Builder(UrlHandler.ACTION, CompiledGraphQL.b(customScalarType)).c());
        d = listR3;
        CompiledField.Builder builder3 = new CompiledField.Builder("broadcastBannerUI", CompiledGraphQL.b(CoreBroadcastBannerUI.f11286a));
        builder3.e = listR2;
        CompiledField compiledFieldC4 = builder3.c();
        CompiledField compiledFieldG3 = d.g("broadcastBannerActionLabel", customScalarType);
        CompiledField.Builder builder4 = new CompiledField.Builder("broadcastBannerAction", Action.f10997a);
        builder4.e = listR3;
        List listR4 = CollectionsKt.R(compiledFieldC4, compiledFieldG3, builder4.c());
        e = listR4;
        CompiledField compiledFieldC5 = new CompiledField.Builder("recipeCostPerServePrice", CompiledGraphQL.b(GraphQLFloat.f11440a)).c();
        CompiledField.Builder builder5 = new CompiledField.Builder("recipeCostPerServeBanner", BasicCoreBroadcastBanner.f11044a);
        builder5.e = listR4;
        List listR5 = CollectionsKt.R(compiledFieldC5, builder5.c());
        f = listR5;
        List listR6 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c());
        g = listR6;
        List listR7 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("content", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("image", customScalarType).c());
        h = listR7;
        CompiledField compiledFieldC6 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder6 = new CompiledField.Builder(lqlqqlq.mmm006Dm006Dm, MethodDescription.f11572a);
        builder6.e = listR6;
        CompiledField compiledFieldC7 = builder6.c();
        CompiledField.Builder builder7 = new CompiledField.Builder("items", a.f(MethodItem.f11573a));
        builder7.e = listR7;
        List listR8 = CollectionsKt.R(compiledFieldC6, compiledFieldC7, builder7.c(), d.g("disclaimer", customScalarType));
        i = listR8;
        List listR9 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), d.g("image", customScalarType));
        j = listR9;
        CompiledField compiledFieldC8 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder8 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        List list = AnalyticsFieldsSelections.b;
        builder8.b(list);
        List listR10 = CollectionsKt.R(compiledFieldC8, builder8.a());
        k = listR10;
        CompiledField compiledFieldC9 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder9 = new CompiledFragment.Builder("Analytics", CollectionsKt.Q("Analytics"));
        builder9.b(list);
        List listR11 = CollectionsKt.R(compiledFieldC9, builder9.a());
        l = listR11;
        CompiledField compiledFieldC10 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC11 = new CompiledField.Builder("amount", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG4 = d.g("unit", customScalarType);
        CompiledField compiledFieldC12 = new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c();
        FeatureType.e.getClass();
        List listR12 = CollectionsKt.R(compiledFieldC10, compiledFieldC11, compiledFieldG4, compiledFieldC12, new CompiledField.Builder("featureType", CompiledGraphQL.b(FeatureType.f)).c());
        m = listR12;
        CompiledField compiledFieldC13 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CustomScalarType customScalarType2 = GraphQLInt.f11442a;
        List listR13 = CollectionsKt.R(compiledFieldC13, new CompiledField.Builder("value", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("maxValue", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c());
        n = listR13;
        CompiledField compiledFieldC14 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder10 = new CompiledFragment.Builder("RecipeSummaryFeature", CollectionsKt.Q("RecipeSummaryFeature"));
        builder10.d = listR12;
        CompiledFragment compiledFragmentA = builder10.a();
        CompiledFragment.Builder builder11 = new CompiledFragment.Builder("RecipeSummaryDifficulty", CollectionsKt.Q("RecipeSummaryDifficulty"));
        builder11.d = listR13;
        List listR14 = CollectionsKt.R(compiledFieldC14, compiledFragmentA, builder11.a());
        o = listR14;
        CompiledField compiledFieldC15 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder12 = new CompiledFragment.Builder("RecipeSummaryCard", CollectionsKt.Q("RecipeSummaryCard"));
        builder12.b(RecipeSummaryCardFragmentSelections.d);
        List listR15 = CollectionsKt.R(compiledFieldC15, builder12.a());
        p = listR15;
        CompiledField compiledFieldC16 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder13 = new CompiledFragment.Builder("RecipeSummaryCard", CollectionsKt.Q("RecipeSummaryCard"));
        builder13.d = listR15;
        List listR16 = CollectionsKt.R(compiledFieldC16, builder13.a());
        q = listR16;
        List listQ2 = CollectionsKt.Q(new CompiledField.Builder(k.a.g, a.e(customScalarType)).c());
        r = listQ2;
        CompiledField compiledFieldC17 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder14 = new CompiledFragment.Builder("RecipeTagList", CollectionsKt.Q("RecipeTagList"));
        builder14.d = listQ2;
        List listR17 = CollectionsKt.R(compiledFieldC17, builder14.a());
        s = listR17;
        CompiledField compiledFieldC18 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldG5 = d.g(NotificationMessage.NOTIF_KEY_SUB_TITLE, customScalarType);
        CompiledField.Builder builder15 = new CompiledField.Builder("items", d.j(HorizontalListItem.f11475a));
        builder15.e = listR16;
        CompiledField compiledFieldC19 = builder15.c();
        CompiledField compiledFieldG6 = d.g("actionTitle", customScalarType);
        CompiledField.Builder builder16 = new CompiledField.Builder("actionMetadata", d.j(ActionMetaData.f10998a));
        builder16.e = listR17;
        List listR18 = CollectionsKt.R(compiledFieldC18, compiledFieldG5, compiledFieldC19, compiledFieldG6, builder16.c());
        t = listR18;
        List listR19 = CollectionsKt.R(new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("value", CompiledGraphQL.b(customScalarType)).c());
        u = listR19;
        CompiledField compiledFieldC20 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC21 = new CompiledField.Builder("perServeKilojoules", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC22 = new CompiledField.Builder("perServeCalories", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC23 = new CompiledField.Builder("dailyIntakePercentage", CompiledGraphQL.b(customScalarType2)).c();
        CompiledField compiledFieldC24 = new CompiledField.Builder("dailyIntakeText", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC25 = new CompiledField.Builder("disclaimer", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder17 = new CompiledField.Builder("features", a.f(RecipeNutritionTileFeature.f11867a));
        builder17.e = listR19;
        List listR20 = CollectionsKt.R(compiledFieldC20, compiledFieldC21, compiledFieldC22, compiledFieldC23, compiledFieldC24, compiledFieldC25, builder17.c());
        v = listR20;
        CustomScalarType customScalarType3 = GraphQLBoolean.f11439a;
        List listR21 = CollectionsKt.R(new CompiledField.Builder("isSaved", customScalarType3).c(), d.g("recipeUrl", customScalarType));
        w = listR21;
        List listR22 = CollectionsKt.R(new CompiledField.Builder("quantity", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("minimum", CompiledGraphQL.b(customScalarType2)).c(), new CompiledField.Builder("maximum", CompiledGraphQL.b(customScalarType2)).c());
        x = listR22;
        CompiledField.Builder builder18 = new CompiledField.Builder("servesInfo", RecipeServes.f11869a);
        builder18.e = listR22;
        List listR23 = CollectionsKt.R(builder18.c(), new CompiledField.Builder("ingredients", a.e(customScalarType)).c());
        y = listR23;
        CompiledField compiledFieldC26 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC27 = new CompiledField.Builder("link", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC28 = new CompiledField.Builder("image", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC29 = new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c();
        CardHeight.e.getClass();
        EnumType enumType = CardHeight.f;
        CompiledField compiledFieldC30 = new CompiledField.Builder("cardHeight", CompiledGraphQL.b(enumType)).c();
        CustomScalarType customScalarType4 = TealiumAnalytics.f11963a;
        List listR24 = CollectionsKt.R(compiledFieldC26, compiledFieldC27, compiledFieldC28, compiledFieldC29, compiledFieldC30, new CompiledField.Builder("analytics", customScalarType4).c(), d.g("_excluded", customScalarType3));
        z = listR24;
        CompiledField compiledFieldC31 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC32 = new CompiledField.Builder(OutOfContextTestingActivity.AD_UNIT_KEY, CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC33 = new CompiledField.Builder("nativeCustomTemplateId", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC34 = new CompiledField.Builder("iabSpec", CompiledGraphQL.b(customScalarType3)).c();
        CompiledField compiledFieldG7 = d.g("iabSize", customScalarType);
        AdBannerNativeSize.e.getClass();
        EnumType enumType2 = AdBannerNativeSize.f;
        CompiledField compiledFieldC35 = new CompiledField.Builder("height", CompiledGraphQL.b(enumType2)).c();
        CustomScalarType customScalarType5 = GoogleAdCustomTargeting.f11436a;
        List listR25 = CollectionsKt.R(compiledFieldC31, compiledFieldC32, compiledFieldC33, compiledFieldC34, compiledFieldG7, compiledFieldC35, new CompiledField.Builder("targeting", customScalarType5).c(), d.g("_excluded", customScalarType3));
        A = listR25;
        List listR26 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder(OutOfContextTestingActivity.AD_UNIT_KEY, CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("nativeCustomTemplateId", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("iabSpec", CompiledGraphQL.b(customScalarType3)).c(), d.g("iabSize", customScalarType), new CompiledField.Builder("height", CompiledGraphQL.b(enumType2)).c(), d.g("targeting", customScalarType5), d.g("correlator", customScalarType), d.g("_excluded", customScalarType3));
        B = listR26;
        List listR27 = CollectionsKt.R(new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("link", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("image", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("altText", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("cardHeight", CompiledGraphQL.b(enumType)).c(), d.g("analytics", customScalarType4), d.g("_excluded", customScalarType3));
        C = listR27;
        CompiledField compiledFieldC36 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder19 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder19.d = listR27;
        List listR28 = CollectionsKt.R(compiledFieldC36, builder19.a());
        D = listR28;
        CompiledField.Builder builder20 = new CompiledField.Builder("googleAdBannerCard", GoogleAdBannerCard.f11435a);
        builder20.e = listR26;
        CompiledField compiledFieldC37 = builder20.c();
        CompiledField.Builder builder21 = new CompiledField.Builder("nextBestAction", UniversalInventoryNextBestAction.f11980a);
        builder21.e = listR28;
        List listR29 = CollectionsKt.R(compiledFieldC37, builder21.c());
        E = listR29;
        CompiledField compiledFieldC38 = new CompiledField.Builder("__typename", CompiledGraphQL.b(customScalarType)).c();
        CompiledFragment.Builder builder22 = new CompiledFragment.Builder("ActionableCard", CollectionsKt.Q("ActionableCard"));
        builder22.d = listR24;
        CompiledFragment compiledFragmentA2 = builder22.a();
        CompiledFragment.Builder builder23 = new CompiledFragment.Builder("GoogleAdBannerCard", CollectionsKt.Q("GoogleAdBannerCard"));
        builder23.c = a.s("includeUniversalInventoryFallback", true);
        builder23.d = listR25;
        CompiledFragment compiledFragmentA3 = builder23.a();
        CompiledFragment.Builder builder24 = new CompiledFragment.Builder("UniversalInventoryContainer", CollectionsKt.Q("UniversalInventoryContainer"));
        builder24.c = a.s("includeUniversalInventoryFallback", false);
        builder24.d = listR29;
        List listR30 = CollectionsKt.R(compiledFieldC38, compiledFragmentA2, compiledFragmentA3, builder24.a());
        F = listR30;
        CompiledField compiledFieldC39 = new CompiledField.Builder(AnnotatedPrivateKey.LABEL, CompiledGraphQL.b(customScalarType)).c();
        ButtonStyle.e.getClass();
        List listR31 = CollectionsKt.R(compiledFieldC39, new CompiledField.Builder("style", ButtonStyle.f).c(), new CompiledField.Builder("enabled", CompiledGraphQL.b(customScalarType3)).c(), d.g(UrlHandler.ACTION, customScalarType), d.g("url", customScalarType));
        G = listR31;
        CompiledField.Builder builder25 = new CompiledField.Builder("button", CompiledGraphQL.b(Button.f11080a));
        builder25.e = listR31;
        List listQ3 = CollectionsKt.Q(builder25.c());
        H = listQ3;
        List listR32 = CollectionsKt.R(new CompiledField.Builder("url", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("thumbnail", CompiledGraphQL.b(customScalarType)).c(), new CompiledField.Builder("duration", CompiledGraphQL.b(customScalarType)).c(), d.g("id", customScalarType));
        I = listR32;
        CompiledField compiledFieldC40 = new CompiledField.Builder("id", CompiledGraphQL.b(customScalarType)).c();
        CompiledField.Builder builder26 = new CompiledField.Builder("recipeCostPerServe", RecipeCostPerServe.f11856a);
        builder26.e = listR5;
        CompiledField compiledFieldC41 = builder26.c();
        CompiledField compiledFieldG8 = d.g("recipeUrl", customScalarType);
        CompiledField compiledFieldC42 = new CompiledField.Builder("title", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC43 = new CompiledField.Builder("image", CompiledGraphQL.b(customScalarType)).c();
        CompiledField compiledFieldC44 = new CompiledField.Builder("ingredientProductIds", a.e(customScalarType)).c();
        CompiledField compiledFieldC45 = new CompiledField.Builder("ingredients", a.e(customScalarType)).c();
        CompiledField compiledFieldG9 = d.g("sourceName", customScalarType);
        CompiledField compiledFieldC46 = new CompiledField.Builder(k.a.g, a.e(customScalarType)).c();
        CompiledField.Builder builder27 = new CompiledField.Builder("method", CompiledGraphQL.b(RecipeMethod.f11864a));
        builder27.e = listR8;
        CompiledField compiledFieldC47 = builder27.c();
        CompiledField.Builder builder28 = new CompiledField.Builder("byline", RecipeByLine.f11855a);
        builder28.e = listR9;
        CompiledField compiledFieldC48 = builder28.c();
        ObjectType objectType = Analytics.f11028a;
        CompiledField.Builder builder29 = new CompiledField.Builder("impressionAnalytics", objectType);
        builder29.e = listR10;
        CompiledField compiledFieldC49 = builder29.c();
        CompiledField.Builder builder30 = new CompiledField.Builder("analytics", objectType);
        builder30.e = listR11;
        CompiledField compiledFieldC50 = builder30.c();
        CompiledField.Builder builder31 = new CompiledField.Builder("features", CompiledGraphQL.a(CompiledGraphQL.b(RecipeFeature.f11859a)));
        builder31.e = listR14;
        CompiledField compiledFieldC51 = builder31.c();
        CompiledField.Builder builder32 = new CompiledField.Builder("latestRecipes", HorizontalList.f11472a);
        builder32.e = listR18;
        CompiledField compiledFieldC52 = builder32.c();
        CompiledField.Builder builder33 = new CompiledField.Builder("nutritionTile", RecipeNutritionTile.f11866a);
        builder33.e = listR20;
        CompiledField compiledFieldC53 = builder33.c();
        CompiledField.Builder builder34 = new CompiledField.Builder("userInteraction", RecipeUserInteraction.f11875a);
        builder34.e = listR21;
        CompiledField compiledFieldC54 = builder34.c();
        CompiledField.Builder builder35 = new CompiledField.Builder("ingredientsSection", CompiledGraphQL.b(IngredientsSection.f11506a));
        builder35.e = listR23;
        CompiledField compiledFieldC55 = builder35.c();
        CompiledField.Builder builder36 = new CompiledField.Builder("universalInventory", UniversalInventory.f11978a);
        builder36.e = listR30;
        CompiledField compiledFieldC56 = builder36.c();
        CompiledField.Builder builder37 = new CompiledField.Builder("shopIngredientButton", CompiledGraphQL.b(ShopIngredientButton.f11897a));
        builder37.e = listQ3;
        CompiledField compiledFieldC57 = builder37.c();
        CompiledField.Builder builder38 = new CompiledField.Builder("video", Video.f12006a);
        builder38.e = listR32;
        List listR33 = CollectionsKt.R(compiledFieldC40, compiledFieldC41, compiledFieldG8, compiledFieldC42, compiledFieldC43, compiledFieldC44, compiledFieldC45, compiledFieldG9, compiledFieldC46, compiledFieldC47, compiledFieldC48, compiledFieldC49, compiledFieldC50, compiledFieldC51, compiledFieldC52, compiledFieldC53, compiledFieldC54, compiledFieldC55, compiledFieldC56, compiledFieldC57, builder38.c());
        J = listR33;
        CompiledField.Builder builder39 = new CompiledField.Builder("recipeDetails", RecipeDetail.f11857a);
        new CompiledArgument.Builder(Query.p2);
        CompiledArgument compiledArgument = new CompiledArgument();
        new CompiledArgument.Builder(Query.o2);
        CompiledArgument compiledArgument2 = new CompiledArgument();
        new CompiledArgument.Builder(Query.q2);
        builder39.d = CollectionsKt.R(compiledArgument, compiledArgument2, new CompiledArgument());
        builder39.e = listR33;
        K = CollectionsKt.Q(builder39.c());
    }
}
